### ISSUE TITLE
[QUEST][NPC] Unleash The Raptors

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Quest jest ukończalny, ale nie działa prawidłowo.
**Obecne działanie**: 
Raptory które uwalniamy atakują nas.
**Oczekiwane działanie**:
Raptory nie powinny nas atakować.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć quest itemu przy wiatraku: [Raptor Bait](http://www.wowhead.com/item=33070)
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/quest=11147/deprecated-unleash-the-raptors](http://www.wowhead.com/quest=11147/deprecated-unleash-the-raptors)
2. [https://www.youtube.com/watch?v=xeegSxT9Leg](https://www.youtube.com/watch?v=xeegSxT9Leg)
3. [https://www.youtube.com/watch?v=C0EsvnMP5Bg](https://www.youtube.com/watch?v=C0EsvnMP5Bg)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
done
