### ISSUE TITLE
[QUEST] Klaven's Tower

### ISSUE THREAD

**Issue by plaszczu** [RaphaelSunwell/Sunwell-BugTracker-SCv2#10]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Majac Klucz do skrzynii nie mozna jej otworzyc

**Obecne działanie**: Nie da sie otworzyc skrzynii

**Oczekiwane działanie**: Mozliwosc otwarcia skrzynii kiedy posiada sie klucz

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Klasa Rouge, quest na 20 lvl dla tej klasy
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=2359/klavens-tower
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 70, 74 Westfall

**Comment by ThePuppetMaster** [comment]
> Would just like to add that you NEED to have to trained your lockpicking to 70, or you won't be able to open it. The key you get from pickpocketing won't do the trick.
