### ISSUE TITLE
[Spell] [Dk] Runeforge

### ISSUE THREAD

**Issue by Szogun13** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1003]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Posiadam Dk. NIestety po ostatnim ataku hakerskim nie posiadam w spellbooku umiejętności runeforge 

**Obecne działanie**: Brak umiejętności 

**Oczekiwane działanie**: Przywrócenie do mojego spellbooka tej tumiejetnosci

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=53428/runeforging
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Crackaw** [comment]
Jeżeli problem nadal występuję, to proszę napisać ticketa do gm'a i tam próbować rozwiązać ten problem.

**Comment by Crackaw** [comment]
#821
