### ISSUE TITLE
[SPELL] Hand of Salvation

### ISSUE THREAD

**Issue by Redziked** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1006]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Mimo posiadania talentu Blessed Hands który powinien zwiększać moc Hos'a o 100%, nie dzieje się tak i ikonka i na pasku i na rzuconej osobie nadal pokazuje 2%
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Jeżeli paladyn posiada Blessed Hands HoS powinien redukować threat o 4% na sekunde.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć na paladynie talent Blessed Hands
2. Użyć na sobie HoS'a
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.evowow.com/?spell=1038
2.  http://wotlk.evowow.com/?spell=53661
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Philosophers** [comment]
Sprawdzałeś czy nie jest to tylko visual bug? Może pokazuje 2 a redukuje 4%?

**Comment by Crackaw** [comment]
Prosiłbym jednak o namacalne dowody, bo nie jesteśmy w stanie zmieniać tooltipa nie ingerując w waszego klienta gry :/
