### ISSUE TITLE
[ULDUAR] Kologarn

### ISSUE THREAD

**Issue by gretowy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1008]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Boss nie posiada cd pomiędzy melee a innymi spelami.

**Obecne działanie**: 
[18:31:26.702] Kologarn Overhead Smash Wykopmidol 25167 (A: 4441)
[18:31:26.702] Kologarn Overhead Smash Tremor Wykopmidol 1273
[18:31:26.740] Kologarn hits Wykopmidol 16416 (O: 381, A: 2964)

**Oczekiwane działanie**: Pomiędzy wszelkimi działaniami powinien występować przynajmniej 1s GCD. (Tak jak poprawiliście Thorima i casty jego żonki)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Spojrzeć w logi tanków na kologarnie.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Wojtyas** [comment]
Do deva: ten skill powinien działać jak każdy "next swing" czyli heroic strike czy cleave, i powinien zastąpić następny melee atak.

**Comment by jasprx** [comment]
No właśnie, a działa jak np Revenge - jest instant niezależnie od swinga.
