### ISSUE TITLE
[QUEST] [627] Favor for Krazek

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#101]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: brak bloodstone veinow

**Obecne działanie**: W jaskini nie ma lesser bloodstone vein

**Oczekiwane działanie**: W jaskini Darkwhisker Gorge (.tele darkwhisker) nie pojawiaja sie Lesser Bloodstone Deposit [id 2653]. Powinny byc, powinno moc sie je kopac od 65 miningu i powinny dropic Lesser Bloodstone Ore id 4278. Nie ma nigdzie info ile ore z veina powinno byc - mozna dac po prostu 1, bo wowhead mowi, ze tych veinow ma byc 10 w tej jaskini, ale nie podano zadnych coordow.
**Co należy zrobić, aby odtworzyć ten błąd**: wziac quest id 627, isc do jaskini Darkwhisker Gorge (.tele darkwhisker). 

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=4278/lesser-bloodstone-ore#comments
2. http://www.wowhead.com/quest=627/favor-for-krazek
3. http://www.wowhead.com/object=2653/lesser-bloodstone-deposit

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
brak, trzeba recznie dodac 10 depositow

**Comment by Radeghost** [comment]
Okazuje sie ze sa jakies gobjecty Lesser bloodstone deposit, ale ich w ogole nie widac jak sie do nich teleportowalem.
Jak sprawdzic: .tele darkwhisker, .gobject near 100 i jest lista gobow

**Comment by c0me10** [comment]
Yeah, it is bug. Confirmed. Ore not spawning for mining.

**Comment by Hekael** [comment]
Przyglądałem się temu, sam quest jest do wykonania, veiny się spawnią ALE wychodzi na to że w jaskini jest ograniczona ilość veinów do zespawnienia, jak pokopie się mithill, gold, silver i iron które też tam występują jest szansa że zespawni się bloodstone vein

**Comment by Shon-su** [comment]
podniesiono szansę spawnu Bloodstone ore. Nie dograne jeszcze
