### ISSUE TITLE
[Spell][Mage] Blink

### ISSUE THREAD

**Issue by grigorlives** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1010]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Blinka nie da się użyć w stunie, wyskakuje error "can't do that while stunned".
![wowscrnshot_050417_170336](https://cloud.githubusercontent.com/assets/16683952/25710545/dc5d5b82-30ec-11e7-8e76-1d0a2e614419.jpg)

**Oczekiwane działanie**: Blinka POWINNO się dać użyć w stunie, jak wskazuje sam opis spella.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dostać stun, np. shadowfury, concussion blow, charge stun, cokolwiek.
2. Walić w klawisz blinka.
3. Enrage.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=1953/blink

**Comment by Crackaw** [comment]
Naprawione. Do zamknięcia.
