### ISSUE TITLE
[spell][warlock] Mana Drain

### ISSUE THREAD

**Issue by dathremar** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1012]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Mana drain nie przerywa CC, ktore powinien przerywac.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
jw.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
http://wowwiki.wikia.com/wiki/Patch_3.3.3  [Drain Mana]: Drain Mana now clears away any Crowd Control effects such as Hex, Fear, Polymorph, Blind and Seduce. 

Mana drain powinien natychmiastowo przerywac wszelkie efekty CC, ktore moga byc przerwane przez DMG (tj. wszystko nie liczac stuna,silenca,interrupta,disarma,immobiliza) - podobnie dziala zreszta mana burn priesta, ktory natychmiastowo przerywa przerywalne efekty CC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  wycastowac feara
2.  wycastowac mana draina w osobe z debuffem z feara
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=5138
2. http://wowwiki.wikia.com/wiki/Drain_Mana
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by dathremar** [comment]
*nie powinno przerywac natychmiastowo, tylko w momencie 1wszego ticku / poczatku zabierania many celowi.

**Comment by Crackaw** [comment]
Hmmm, miałby ktoś czas przetestować to czy u huntera z Viper Sting nie jest podobnie?

**Comment by Crackaw** [comment]
Viper sting miał podobnie xd

**Comment by Randomdog** [comment]
.
