### ISSUE TITLE
[OBJECT] The Holy Spring (reopen)

### ISSUE THREAD

**Issue by Akha72** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1014]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

Nie mając w logu żadnego z wymienionych questów po otwarciu objectu The Holy Spring nie można wyciągnać itemu Holy Spring Water.

Wszystko w zgłoszeniu (https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/936)

**Comment by Shon-su** [comment]
poprawione tylko jeszcze nie dograne, powinno pojawić się w najbliższym czasie w changelogu.
