### ISSUE TITLE
[Paladin] Hand of Protection

### ISSUE THREAD

**Issue by Heartbraker** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1015]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wraz z fixem - https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/919 powstał kolejny bug... Jeszcze raz opis zmiany z 2.2.0 zamieszczony również w poprzednim zgłoszeniu - 
"Patch 2.2.0:
Blessing of Protection: This spell can no longer be cast on others
when stunned. It can only be cast on self (to break the stun) under
those circumstances."

**Obecne działanie**: W tej chwili nie można użyć hopa na siebie mając na sobie physical stuny (mam nadzieję, że tylko ze stunami coś zmienialiście, bo nie testowałem reszty)

**Oczekiwane działanie**: HoP powinien być możliwy do rzucenie na siebie w każdym 'fizycznym' cc - na stunie też

**Co należy zrobić, aby odtworzyć ten błąd**:

1. cheap shot w palka
2. próba użycia hand of protection
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Crackaw** [comment]
W związku z brakiem dowodów na możliwość selfcasta HoP w czasie stunów usunięta została możliwość castowania na kogokolwiek w czasie stuna.

**Comment by Heartbraker** [comment]
To może jeszcze raz (już trzeci) : 
"Patch 2.2.0:
Blessing of Protection: This spell can no longer be cast on others
when stunned. It can only be cast on self (to break the stun) under
those circumstances."
Przecież jest tu czarno na białym napisane, że nie można castować tego na INNYCH i jest nawet dodane, że można na siebie - cały czas mowa o cc na które hop daje immunity czyli fizycznych.

Ten fragment z patch notes posłużył jako wystarczający dowód w https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/919 a tutaj nagle jest brak dowodów?

**Comment by Akha72** [comment]
Znajdź jakiś filmik i problem solved.

**Comment by Heartbraker** [comment]
https://www.youtube.com/watch?v=OveRM0T6_ls   8:03 hop z cs'a

**Comment by Crackaw** [comment]
Naprawione, jednakże mając na sobie hamer palka nie wycastujemy tego
