### ISSUE TITLE
[Core] Prawidlowy czas wyjscia z combatu

### ISSUE THREAD

**Issue by szopn** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1019]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Combat schodzi po 6 lub 5.5 sekundach, a nie tak jak powinien (tzn. po 5s)

**Obecne działanie**: jak wyzej

**Oczekiwane działanie**: Combat powinien schodzic po 5sekundach

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Dac roguem spell gouge z talentem Improved Gouge ( z talentem disorient trwa 5.5s)
2.  Sprobowac wejsc w stealtha zanim przeciwnik nas zaatakuje ( powinnismy miec 0.5 sekundowy bufor aby wejsc w stealtha zanim przeciwnik nas zaatakuje)
3.  Dostac od przeciwnika dowolnym spellem odrazu jak skonczy mu sie gouge

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Combat?oldid=2326993
2. http://wowwiki.wikia.com/wiki/Combat?oldid=2304571
3. http://wowwiki.wikia.com/wiki/Combat?oldid=2231868

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by MonichSC** [comment]
U mnie wszystko działa dobrze, mam te 0,5s na wejście w stealth.
Testowałeś to na PvP czy PvE?

**Comment by bartekmad** [comment]
Bullshit, pamiętam jak na starym sunwellu rogale zaczęły płakać jak combat został poprawiony(czyli wydłużony) - teraz działa tak jak ma działać.

**Comment by sitovsky** [comment]
Combat timer powinien byc randomowy na sunwellu, przynajmniej taki byl ostatnio - tak jest najbardziej blizzlike jak sie da. 6 lub 5.5s
