### ISSUE TITLE
[Quest(16) - Mage] "Investigate the Blue Recluse"

### ISSUE THREAD

**Issue by voytas7900** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1020]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest dla Maga lvl 16 do wzięcia w SW na szczycie wieży Magów. http://www.wowhead.com/quest=1920/investigate-the-blue-recluse

**Obecne działanie**: W celu przywołania mobków urzywamy 
https://drive.google.com/file/d/0B-yR9LGeRhPVRXZKM3VBeE5nQVU/view?usp=sharing
http://www.wowhead.com/item=7308/cantation-of-manifestation .
Po zabiciu spawnów, nie można użyć 
https://drive.google.com/file/d/0B-yR9LGeRhPVTkpuWmJKemNteDA/view?usp=sharing
http://www.wowhead.com/item=7247/chest-of-containment-coffers
 bez namierzania moba, ani namierzyć mobka w celu użycia w/w itemu.

**Oczekiwane działanie**: Naprawa itemu
https://drive.google.com/file/d/0B-yR9LGeRhPVTkpuWmJKemNteDA/view?usp=sharing
http://www.wowhead.com/item=7247/chest-of-containment-coffers ,
 lub problemu z namierzaniem moba.

**Co należy zrobić, aby odtworzyć ten błąd**: W niżej podanej lokalizacji (jest to piwnica w Tawernie w Mage Quarter w Stormwind City) należy użyć zwoju "cantation-of-manifestation" aby pojawiły sie moby. Należy zjechać im HP do minimum i wtedy powinniśmy użyć na nich "chest-of-containment-coffers" aby otrzymać quest item filled-containment-coffer.
http://www.wowhead.com/item=7292/filled-containment-coffer .
Do ukończenia questa potrzebujemy ich trzy sztuki.

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**: http://www.wowhead.com/quest=1920/investigate-the-blue-recluse

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 
https://drive.google.com/file/d/0B-yR9LGeRhPVRFJtMVV6ZFcyd3c/view?usp=sharing

**Comment by Shon-su** [comment]
#576
