### ISSUE TITLE
[Hunter] Bugi trapów huntera

### ISSUE THREAD

**Issue by CiriSunwell** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1021]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Trapy huntera są zbugowane przez co survival spec jest tak zboostowany ze to jest jakieś nieporozumienie.

**Obecne działanie**: Explosive trap posiada za duży przelicznik crita. Można odpalać talent Lock and Load przy pomocy trapów do CC na celach które są immune na CC.

**Oczekiwane działanie**: Explosive trap powinien być traktowany jak spell i zadawać tylko 150% critical damage. Nie powinna istnieć możliwość odpalenia procu talentu Lock and Load żadnym trapem wywołującym CC (Frost trap, Freezing trap, Freezing arrow) na celach które są immune na CC.

**Co należy zrobić, aby odtworzyć ten błąd**: 
1. Założyć Glyph of Explosive Trap. 
2. Użyć na dowolnym celu Explosive Trap
3. Zobaczyć za ile uderza zwykły hit a za ile crit (zarówno z pierwszego dmg jak i z doty). 
4. Użyć dowolnego z trapów od CC (najlepiej Frost trap) wymienionego w opisie talentu Lock and Load na celu który ma immune na CC
5. Zaobserwować darmowy proc talentu Lock and Load.

Explosive trap id: 49067
Lock and Load id : 56342
Frost trap id: 13809
Freezing trap id: 14311
Freezing arrow id: 60192
Glyph of Explosive Trap : http://www.wowhead.com/item=42908/charred-glyph

@spyke13 Poprawione.

**Comment by spyke13** [comment]
Nie powinna istnieć możliwość odpalenia procu talentu Lock and Load **żadnym** trapem na celach które są immune na CC.

Explosive trap i immolation trap moze odpalic ten talent. Nawet jesli cel ma immune na CC. (niby mala pomylka ale moge popsuc)

**Comment by CiriSunwell** [comment]
Część dotycząca explosive trapa została naprawiona, ale nadal czekam na fix reszty trapów. Czy coś w tym kierunku zostanie zrobione czy jest to zbyt trudny do naprawienia bug ?

**Comment by CiriSunwell** [comment]
It is not bugged, i know you guys want to Top dps by just putting Explosive trap with bugged glyph, but sadly after this fix you need put more effort.
