### ISSUE TITLE
efekty stealth i absorby

### ISSUE THREAD

**Issue by dathremar** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1023]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Efekty stealth w polaczeniu z absorbami daja praktycznie niewykrywalnosc.

**Obecne działanie**: 
Jezeli ktos siedzi w stealth i absorba na sobie i zaatakujemy go jakims AoE, to nie wyrzuci go ze stealtha, chyba, ze przebijemy banke.

**Oczekiwane działanie**: 
"pierwszy atak" powinien zawsze wyrzucac ze stealtha. Absorby powinny chronic jedynie przed nastepnymi tickami AoE - przyklad, jezeli DK poloze na ziemi DND, to rog z absorbem bedzie mogl w nie wejsc, ale jezeli DK rzuci DND w miejsce, gdzie siedzi schowany rogal, to powinno go odrazu wyrzucic ze stealtha. Podobnie z rzuceniem consecration - niewidzialny moze przejsc po rzuconym consecration, ale nie jezeli paladyn uzyje consy kiedy w jej range stoi niewidzialny, to powinno go odrazu wykryc - albo striggerowaniem przez rogala explosive trapa - sam wybuch go wyrzuci, nastepujace ticki juz nie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  testowalem to z night elfem priestem
2.  priest rzuca sobie banke i daje shadowmelda
3. hunter uzywa volleya na miejscu, gdzie stoi priest 

**Linki WoWHead/OpenWoW**:

1.  pozwole sobie darowac linkowanie kazdego spela zapewniajacego efekt stealth w grze , oraz kazdego spella AoE w grze. Fixniecia wymaga prawdopodobnie sama mechanika niewidzialnosci, a nie poszczegolne spelle.
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by kovaq** [comment]
Daj chociaz jeden link, ktory potwierdza Twoje slowa, to bylo specjalnie sprawdzane przed otwarciem servera.

**Comment by Rosenkrantz** [comment]
http://www.arenajunkies.com/topic/133038-druid-stealth-working-differently-than-rogue-stealth/?p=1959182

http://www.arenajunkies.com/topic/64037-how-do-you-get-the-sap/ kilka postów na obu stronach.

Ogólna zasada wybrzmiewa zawsze tak samo:
-jeżeli obszarówka jest pozostawiona na ziemi i nie wymaga podtrzymywania, rogue nie zostanie wyrzucony ze stealth, dopóki absorb trzyma (dotka z consecration, DND, Flamestrike)
-jeżeli obszarówka wymaga aktywności od przeciwnika (rain of fire, blizzard, volley) lub bezpośrednio trafi rogue - również dotyczy zrzucenia consecration, DND, Flamestrike na jego głowę - wtedy rogue traci stealth, niezależnie od posiadanego absorba.

Aktualnie jestem absolutnie pewien tylko tego, że Blizzard nie wyrzuca rogue ze stealth w żadnym przypadku, ani gdy trafię go bezpośrednio, ani gdy przez niego przebiegnie - combat text pokazuje tylko  "absorbed", dostaję combat, rogala dalej ani śladu. Co do innych AoE, nie mogę mieć pewności.

**Comment by Namzaj** [comment]
Było zgłasza parę miesięcy temu:

https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/706
