### ISSUE TITLE
[spell][druid]Cat Form / Tracking

### ISSUE THREAD

**Issue by LittleAmnesia** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1025]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wejście w formę kota aktywuje Track Humanoids

**Obecne działanie**: Wejście w formę kota aktywuje Track Humanoids bez względu na tracking
edit: dowolne działanie w formie kota bez ustawionego trackingu aktywuje track humanoids

**Oczekiwane działanie**: track humanoids w przypadku wejścia w kota gdy nie jest ustawiony tracking profesji (mining/herbalism)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Kup dowolną profesję zbieracką 
2. aktywuj find herbs/ore
3. aktywuj formę kota

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Cat_Form
2. http://www.wowhead.com/spell=768/cat-form
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Crackaw** [comment]
![image](https://cloud.githubusercontent.com/assets/25255402/26354139/b06cf434-3fc3-11e7-9ba2-10bc4071bec4.png)

**Comment by LittleAmnesia** [comment]
owszem. czytać umiem i znam angielski wystarczająco by zrozumieć sens, jednakże problem nie dotyczy trackingu non-profession tylko >dowolnego< trackingu. 
dodatkowo po ostatnich obserwacjach mogę stwierdzić że błąd nie jest stały. objawia się losowo, często po zalogowaniu na postać i prawdopodobnie ustępuje po zebraniu herbów.
