### ISSUE TITLE
[QUEST]he Black Knight's Fall

### ISSUE THREAD

**Issue by laaager** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1027]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:http://i64.tinypic.com/8yt8ya.jpg jak widać nie mogę zagadać do typa  i wezwać moba 

**Obecne działanie**: Nie można wezwać moba od questu

**Oczekiwane działanie**: 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by KamaN442** [comment]
mozna ale masz zlego mounta http://wow.zamimg.com/uploads/screenshots/normal/352699-the-black-knights-fall.jpg

**Comment by laaager** [comment]
dzieki
