### ISSUE TITLE
Koltira Deathweaver nie znika, wiec sie nie respi.

### ISSUE THREAD

**Issue by Holeheart** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1028]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: jeden ze startowych questow dk... npc koltira deathweaver - dk ktorego mamy znalesc w scarlet hold, nie znika - wiec sie nie respi.

**Obecne działanie**: Koltira Deathweaver (po uwolnieniu), walczy z scarletami i nie moze zniknac, moze to trwac do nastepnego stulecia jesli ktos mu nie pomoze pokonac owych scarletow, zeby znikl - i dzieki temu mogl sie zrespic dla nastepnego gracza.

**Oczekiwane działanie**: Nie wiem dokladnie, chyba po prostu po czasie powinien zniknac nie zaleznie od tego czy walczy czy nie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. zabic wszystko z czym walczy?
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Rosenkrantz** [comment]
https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/636
