### ISSUE TITLE
[Quest] Hold Five Bases

### ISSUE THREAD

**Issue by Artanis02** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1029]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po zrobieniu questa PVP "Take Four Bases" nie pojawia się kolejny quest z chain'a: "Take Five Bases". Dzięki tym questom dostaje się Tabard of Defilers, dość przyjemny item :)

**Obecne działanie**: Bierzemy q od npc w Hammerfall, idziemy na AB, utrzymujemy 4 bazy, oddajemy q, a kolejny q się nie pojawia.

**Oczekiwane działanie**: Po oddaniu questa Take Four Bases powinien się pojawić quest "Take Five Bases, któy w nagrode da nam tabard.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. W Arathi Highlands (Hammerfall) należy wziąć q od NPC za wioską
2. Należy pójść na BG Arathi Basin i utrzymać w jednym momencie 4 bazy
3. Oddać q
4. Zobaczymy, że npc nie daje kolejnego q

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=8122/take-five-bases
2. http://www.wowhead.com/npc=15021/deathmaster-dwire
3. http://www.wowhead.com/quest=8121/take-four-bases

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
73.30 Arathi Highlands

**Comment by Rosenkrantz** [comment]
Kolega na pewno ma Exalted z The Defilers?

**Comment by Artanis02** [comment]
O kierwa :D sory, do zamknięcia.
