### ISSUE TITLE
[NPC] [4484][GUID:32783] Feero Ironhand

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#103]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: podczas wykonywania questa [976]Supplies to Auberdine, trzeba tego moba eskortowac. Zapada sie on pod ziemie, potem wraca i lewituja nad nia. Bug z waypointami prawdopodobnie.

**Comment by kovaq** [comment]
Zgadza sie
https://youtu.be/exzxjxh8fUU

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane dzisiaj (tj. 27.01) około 6 rano.
