### ISSUE TITLE
Seal of Vengeance

### ISSUE THREAD

**Issue by faralen** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1030]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Seal of Vengeance u paladyna nie działa poprawnie.

**Obecne działanie**: Seal podczas stackowania (stacki od 1 do 4) zadaje tylko Damage over Time, bonus dmg od melee i innych skilli jest dodawany dopiero po nastackowaniu (5 stack).

**Oczekiwane działanie**: Damage naliczanu już od 1 stacka.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://us.battle.net/wow/en/game/patch-notes/3-2-0
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by SynuZuy** [comment]
https://youtu.be/0Y88l_tVXAk?t=31s
wklejam link do filmu z globala, w którym widać damage z seala przy 1-4 stacku doty. 
W filmie występuje Seal of Corruption - odpowiednik hordy ale mechanika jest ta sama http://wowwiki.wikia.com/wiki/Seal_of_Corruption
Przetestowałem też seal na kukle na naszym serwerze i żeczywiście dodatkowy damage z melee ataku pojawia się dopiero przy 5 stacku - jeśli będzie trzeba prześle stosowny film

**Comment by yeniz** [comment]
A jesteś pewien, że w później nie zostało to zmienione (wotlk patche) na formę jaką teraz mamy, bo wiele talentów i spelli było zmienianych, a my gramy jednak na 3.3.5

**Comment by SynuZuy** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17034

tu znalazłem podobny problem

2017-05-31 20:29 GMT+02:00 yeniz <notifications@github.com>:
