### ISSUE TITLE
[NPC][Horde Tribal Leatherworking Trainer] brak możliwości oduczenia się specjalizacji Tribal Leatherworking

### ISSUE THREAD

**Issue by eciek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1032]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak dodatkowej opcjii dialogowej przy rozmowie z trenerem Tribal Leatherworking hordy 

**Obecne działanie**: Po nauczeniu się specjalizacji Trbal Leatherworking, u trenera tej właśnie specjalizacji powinna być możliwość oduczenia się jej za opłatą bez utraty całego leatherworking.
Jednak kliknięcie na trenera otwiera bezpośrednio okienko nauki nowych receptur, bez możliwosci wybrania opcji unlearn.

**Oczekiwane działanie**: Przy kliknięciu powinna być opcja do wyboru czy chcę nauczyć się nowych patternów, czy chcę się oduczyć specjalizacji.
[Tutaj](https://youtu.be/Sp2bhIQBS0A?t=190) przesyłam filmik z youtube gdzie w okolicach 3min 10s gracz poznaje Tribal leatheworking, a przy kolejnej rozmowie ma możliwość oduczenia się tribal LW 
"I wish to unlearn Tribal Leatherworking".

**Co należy zrobić, aby odtworzyć ten błąd**:

1. zdobądź lvl 40+ oraz Leatherworking na 225+
2. wykonaj misję [Tribal Leatherworking](http://wowwiki.wikia.com/wiki/Quest:Tribal_Leatherworking)
3. Przy kolejnej rozmowie nie pojawia się dodatkowa opcja dialogowa

**Linki WoWHead/OpenWoW**:
Ze względu na to że w obecnej wersji już nie ma specjalizacji, na Wowhead nie ma informacji na ten temat, posłużyłem się więc wowwiki.wikia.com 
1. http://wowwiki.wikia.com/wiki/Leatherworking#Switching_a_specialization <Dokładne opisanie jak powinno się zmienić specjalizację (opcja ta została wprowadzona w w wersji 2.1.3, a przy 4.0 usunięto specjalizacje całkowicie)
2. http://wowwiki.wikia.com/wiki/Quest:Tribal_Leatherworking

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie posiadam addonów, załaczam zrzut ekranu z mapy z lokalizacją trenera Tribal LW dla Hordy
![image](https://cloud.githubusercontent.com/assets/28862379/26306034/1ae3c018-3ef2-11e7-8813-30dcca0eead3.png)

**Comment by kovaq** [comment]
O ile sie nie myle, na wotlku zostalo to nieco zmienione. Niemniej jednak duzo kreci sie wokol samej ksiazki w steamwheedle port. Zacznijmy tak przy okazji od tego, ze u nas ona nie dziala, lezy jako pusta tekstura.
http://www.wowhead.com/object=177226/book-evil-soothsaying-for-dummies#comments
http://wowwiki.wikia.com/wiki/Book_%22Soothsaying_for_Dummies%22
Tutaj jeszcze jest kilka przyjemnych linkow dotyczacych zgloszenia:
http://db.vanillagaming.org/?quest=5148#wh-comments
