### ISSUE TITLE
[Ulduar]Kologarn Overhead smash

### ISSUE THREAD

**Issue by jasprx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1034]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie wiem co, ale po ostatnich poprawkach Mimirona stało się coś z Kologarnem... Overhead smash nie ma odstpu od meele ataków. W efekcie czego łącznie 50k dmg w ciągu 0,2 sekundy w tanka jest nie do wyleczenia.

**Obecne działanie**: Kologarn nie ma odstępu pomiędzy Overhead Smash a meele atakiem.

**Oczekiwane działanie**: Mimo tego, że w opisie wowwiki jest to "instant attack" powinien mieć odstęp meele swinga (na Kologarnie na pewno pomad sekundę). 
**Co należy zrobić, aby odtworzyć ten błąd**:

1. udać się do ulduaru25, zaatakować Kologarna
2. zaczekać aż boss użyje Overhead Smash
3. umrzeć od tego dmg.

**Linki WoWHead/OpenWoW**:

1- wiki, 2- screenshot z recountem

1. http://wowwiki.wikia.com/wiki/Kologarn
2. https://zapodaj.net/8b75c684a2d97.jpg.html

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Pangrvszka** [comment]
Ten bug jest od bardzo dawna i był już zgłoszony tutaj raz.

**Comment by Kowson** [comment]
Jako, że nic się w tej sprawie nie rusza, a jest to naprawdę irytujące to podaję moją propozycje rozwiązania tej sprawy:
W evencie odpowiedzialnym za Overhead Smasha (EVENT_SMASH), po wycastowaniu spella dodać linijkę:
"me->resetAttackTimer();"
Dzięki temu odnowi się cooldown na melee swinga po rzuceniu smasha.

**Comment by Lajceps** [comment]
Bump! Ludzie litości, właśnie sie wku***** na tym prostym boss'e bo od miesiąca nikt nie ma czasu buga poprawić. 
Ja rozumiem że można nie mieć czasu na poprawki inst typu 80HC ale Ulduar to teraz główny kontent na litość bosą!:(
