### ISSUE TITLE
[SPELL]Elemental Shaman T8(4/5) Electrified (DoT) Stackowanie

### ISSUE THREAD

**Issue by microjp** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1035]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Electrified to DoT nakładany gdy cel dostanie krytyczne obrażenia od Lightning Bolt. Trwa 4 sekundy i w tym czasie daje dwa tick'i po 4% dmg Lightning Bolt'a. Razem 8% tak jak jest to opisane w secie. Link do setu niżej.

**Obecne działanie**: Dotka powinna się stackować, nakładać kolejną dotke za każdym razem gdy cel zostanie trafiony krytycznym Lightning Boltem. Aktualnie odświeża on swój czas lecz nie atakuje jeśli czas pomiędzy krytycznymi atakami jest mniejszy niż 2 sekundy. Więc przy częstym krytyku istnieje szansa że przez jakiś czas target nie dostanie żadnego dmg od tej DoT'ki. Wykres z World of Logs przedstawiający dmg z Electrified na XT HM : http://imgur.com/a/dy8tt
Link do Screena z recount na kukłach: http://imgur.com/a/yxXfY

**Oczekiwane działanie**: Electrified powinno działać tak jak na przykład Ignite u maga fire, a więc dokładać kolejny DMG lub kolejną taką samą DoT'ke w czasie działania poprzedniej.
Poniżej podam link do BugTrackera z serwera Dalaran-WoW, gdzie występował podobny problem.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Odpowiednio często castować krytyczny atak z Lightning Bolt posiadając 4 części setowe t8
2. 
3. 

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/spell=64928/item-shaman-t8-elemental-4p-bonus - Bonus z 4 części
2. http://imgur.com/a/zgy64 - screen z komentarzy na Wowhead.com

Link do Github z Dalaran-WoW :  https://github.com/dalaranwow/dalaran-wow/issues/2622

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Wojtyas** [comment]
Potwierdzam, Electrified powinno działać jak Ignite.

**Comment by Wojtyas** [comment]
Jednocześnie chciałbym zaznaczyć, iż teraz występuje bug polegający na tym, że Lightning Bolty, które procują z talentu Lightning Overload też nakładają dotę Electrified, a nie powinny.
"Lightning Bolts crits that are a result of a Lightning Overload proc do not trigger this set bonus."
