### ISSUE TITLE
[Paladin] Setówka PvP retri za conquesty

### ISSUE THREAD

**Issue by Nimhith** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1038]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
U vendora Conquestów w Dalaran (Magister Sarien- Emblem of Conquest Quartermaster) można kupić setówke PvP pod holy paladina, pod retri jednak nie ma takiej opcji.
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Według AtlasLoota te shouldery powinny być dostępne dla każdego speca. Sprawdzając na altach(inne klasy) również były dostępne shouldery dla wszystkich speców- np, pod Shadow i Disci na Preju.

http://wowwiki.wikia.com również potwierdza obecność tego itemu u vendora:
This item is sold by the following vendors for 46  [Emblem of Conquest]:

Alliance 15 Arcanist Firael <Emblem of Conquest Quartermaster> in Dalaran
Horde 15 Magister Sarien <Emblem of Conquest Quartermaster> in Dalaran
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do vendora od Conquestów w Dalaran
2. Pogadać z NPC
3. Poszukać setówek retri PvP i stwierdzić, że brakuje shoulderów.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Deadly_Gladiator%27s_Scaled_Shoulders
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Dalaran 65,7 24.4

**Comment by Heartbraker** [comment]
Bug wisi ponad miesiąc, a cały fix polega na dodaniu jednego itemu do vendora...
