### ISSUE TITLE
[quest][reopen]Song of Wind and Water 

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1039]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

Opis:
Z góry uprzedzam, że zakładam to zgłoszenie jako trzecia osoba. Poprzednie zostały zamknięte pomimo, że błąd nie został usunięty, mimo, że w komentarzach po zamknięciu zgłoszenia zgłaszano, że nie usunięto błędu, a nawet go jeszcze bardziej zbugowano. A jest do bardzo ważny quest jeden z 3 dających reputację dla Oracles. Nie wykonanie go uniemożliwia pobieranie jednego z 3 daily questów, co powoduje, że robienie Repy dla Oracles wydłuża się o 1/3.

Obecne działanie: Po użyciu quest itema, Drums of Tempest zmieniamy formę w Hairpoon, The Great of Tempest, którym kierujemy. Mamy zabić i "pożreć" 3 żywiołaki Storm Revenant i 3 żywiołaki Aqueous Spirit. Niestety przeciwnicy zadają ponad 10x większe obrażenia niż nasza postać. Choć według Wowheada i filmów z Youtube nasza postać powinna zadawać nawet do 3000 pkt obrażeń, czyli zadajemy co najmniej10x mniejsze obrażenia niż powinniśmy przez co quest jest awykonalny (zadajemy w formie żywiołaka wody ok 50-137 max jakie udało mi się osiągnąć, obrazeń)
Przeciwnik bije od 100 do 1000 obrażeń. Próbowałem "zmiękczyć przeciwnika bijąc go zanim zmienię swoja postać w żywiołaka i dopiero jak będzie miał 10-20% życia zmienić się w formę żywiołaka. Niestety w przypadku żywiołaków wody tydzień temu ta metoda działała (ukończyłem z wielkim trudem ten quest) a obecnie w przypadku żywiołaka powietrza żadna metoda nie działa, **więc zapewne przy naprawie questu został on jeszcze bardziej uszkodzony**.
**Przy okazji dodam, że zabijanie1 żywiołaka Aqueous Spirit przez 40 minut najczęściej kończy się atakiem gracza przeciwnej frakcji, co jest mega frustrujące. Ale nie ma się co dziwić, gdy prawie godzinę gracz męczy się z jednym NPC'em**.

Oczekiwane działanie: Pojedynczy atak  powinien zadawać ok 2-3k obrażeń.

Co należy zrobić, aby odtworzyć ten błąd:

    Wziąć questa, polecieć we wskazane miejsce i użyć quest itemu
    Zaatakować wskazane moby i poprawić zadawane przez nas obrażenia do faktycznej wartości WoW, czyli  2-3 k obrażń.

Linki WoWHead/OpenWoW:

1. http://www.wowhead.com/quest=12726/song-of-wind-and-water
2. https://www.youtube.com/results?search_query=Song+of+Wind+and+Water&page=&utm_source=opensearch (link do Youtube gdzie pokazano jak powinien działać quest)

Lokalizacja z koordynatów GPS (X, Y, Z, Map):

**Comment by Isilion** [comment]
Próba wykonania  tego questa była weryfikowana przy GMie w grze (nick Starter) i rownież potwierdził awykonalność questa przez dziesięciokrotnie zaniżone DMG naszej postaci w formie żywiołaka.

**Comment by Afgann** [comment]
Poprawka nie została jeszcze wgrana, nic się nie zmieniło.
