### ISSUE TITLE
[QUEST] Blackfathom Villainy

### ISSUE THREAD

**Issue by Azhija** [RaphaelSunwell/Sunwell-BugTracker-SCv2#104]
#[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Postacią z hordy nie jestem w stanie podnieść questa Blackfathom Villainy od NPC 
 Argent Guard Thaelrid w Blackfathom Deeps.

**Obecne działanie**: NPC Argent Guard Thaelrid nie daje questa, jest hostile dla hordy

**Oczekiwane działanie**: NPC nie powinien być hostile, powinno dać się z nim porozmawiać i podnieść quest

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Postacią z hordy spróbować porozmawiać z Argent Guard Thaelrid

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=4787
2. http://wotlk.openwow.com/quest=6561

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by xnemeyethx** [comment]
Potwierdzam :<

**Comment by kovaq** [comment]
http://wowwiki.wikia.com/wiki/Quest:Blackfathom_Villainy_(Horde) Ja skorzystalem z tego linku, ale mob dziala jak nalezy.
https://youtu.be/Mkhu62vmiNA
