### ISSUE TITLE
[spell][warlock] Mana Drain, zbugowaliście poprawne działanie spella.

### ISSUE THREAD

**Issue by Randomdog** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1043]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Mój post odnosi się do zgłoszenia, które napisał gracz Dathremar. ->>https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/1012

Nie wiem czy developerzy zdają sobię sprawę, ale tekst na stronie wowwiki może edytować każdy użytkownik. 
Jak widać w tym linku -> http://wowwiki.wikia.com/wiki/Patch_3.3.3, tekst był zmieniany 2h temu, aktualnie nie zawiera żadnej notki o spellu drain mana, który niby powinien przerywać CC.
Sytuacje takie mogą wykorzystywać graczę prywatnych serwerów, by dopasować działanie spelli na PvP pod siebie. Nie wnikam już, czy zrobił to ktoś od nas (nie zdziwiłbym się), ale to trochę zagranie nie fair.

http://us.battle.net/wow/en/game/patch-notes/3-3-3. Na oficjalnej stronie battle.net nie ma oczywiście żadnej wzmianki o tej umiejętności warlocka.
Następnym razem prosiłbym devów, by sprawdzali dokładnie zgłoszenia, takie jak te powyżej.

 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Cofnąc działanie Drain Mana do poprzedniego stanu.

**Comment by Baggedmilk** [comment]
http://wowwiki.wikia.com/wiki/Drain_Mana
In an earlier version, Mana Drain did not break crowd control, such as Polymorph or Fear. However, this has been changed.
kiedys moze i nie przerywalo cc, ale stad mozna wywnioskowac, ze na wotlku przerywalo

**Comment by Elaatu** [comment]
In an earlier version, Mana Drain did not break crowd control, such as Polymorph or Fear. However, this has been changed **# until Patch 3.3.3.**

Mamy patch 3.3.5a, a cytując wypowiedz Baggedmilk trzeba zwrócić uwagę na: In an earlier version, Mana Drain i  However, this has been changed. A w 4.0.6 skill usunięty.

**Comment by Crackaw** [comment]
http://forum.warmane.com/showthread.php?t=355017
Troszeczkę poszukaliśmy na ten temat i okazało się, że po prostu jakiś gościu pewnie się wkurzył na ten spell i pozmieniał wszędzie changelogi na wowwiki itd tylko dlatego, by na jego serwerze dodali usuwanie fearów itd za pomocą Mana draina ;__; Dałem się złapać. Jeśli chcecie by taka sytuacja się nie powtórzyła, to proszę po prostu o pomoc, bo sam wszystkiego nie zweryfikuję, bo to po prostu trwa i mógłbym w tym czasie naprawiać co innego. Serdecznie zapraszam do dyskusji tutaj i rozmowy na temat spelli, umiejętności, oraz mechanik, a sunwell na pewno będzie lepszym miejscem do grania.

**Comment by Randomdog** [comment]
Dzięki za szybką weryfikację Crackaw. Pokazuje to tylko, że wowwiki jest kiepskim źródłem informacji, jeśli ktoś może tak po prostu sobie wejść i coś zmienić.

**Comment by Baggedmilk** [comment]
to ladnie koles przycwaniakowal z tymi zmianami;p
