### ISSUE TITLE
[Object][Battleground] Huge Seaforium Bombs

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1046]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Obecnie Huge Seaforium Bombs nie znikają po podniesieniu zaburzając balans BG.

**Obecne działanie**: Huge Seaforium Bombs nie znikają po podniesieniu.

**Oczekiwane działanie**: Po podniesieniu jednej bomby object powinien znikać i posiadać 10sec respawn time.
http://wowwiki.wikia.com/wiki/Huge_Seaforium_Bombs
http://wow.gamepedia.com/Huge_Seaforium_Bombs

"The respawn timer on Seaforium Bombs and Huge Seaforium Bombs have been reduced."
"A pile of Huge Seaforium Bombs will despawn after a single bomb is looted, and then respawn 10 seconds later."

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Crackaw** [comment]
Naprawione
