### ISSUE TITLE
[Ulduar][Iron Council] Overwhelming Power

### ISSUE THREAD

**Issue by raveeneer** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1050]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Overwhelming Power - po 35 sec. (na Sunwellu po 25 sec.) Meltdown zadaje obrażenia (śmiertelne) osobie posiadającej debuff'a oraz wszystkm w promieniu 15 yd od tej osoby.

**Obecne działanie**: Notorycznie naprawiany bug wraca po raz kolejny. Mianowicie po upływie debuff'a Overwhelming Power, nie występuje Meltdown. 

Testowane dnia 1.06.2017 (20:25) na Ulduar w wersji 25 man. 

**Oczekiwane działanie**: Opis, znajdujący się wyżej, wyjaśnia prawidłowe działanie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Otrzymać debuff Overwhelming Power,
2. Nie zginać od Meltdown po upływie 25 sec.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=61888/overwhelming-power
2. http://www.wowhead.com/spell=61889/meltdown
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Heartbraker** [comment]
Napisz jeszcze jaka klasa/klasy tankowały pomoże to ustalić czy nie ginie się z powodu dodge/missa czy jakiegoś talentu.
U mnie na u10, również 1.06.2017, prot pal zginął normalnie od Meltdown

**Comment by raveeneer** [comment]
Był to prot pal oraz dk blood, obaj przezyli.

**Comment by yeniz** [comment]
obecnie jest tak, że na 10 działa, a na 25 nie działa
edit: i na 25 wydaje mi się za krótki czas trwania tego debuffa

**Comment by raveeneer** [comment]
Instance / Ulduar | Author: sitdev 
- Boss Steelbreaker: Overwhelming Power trwa 25 sekund w wersji 25man, i 60 sekund w wersji 10man.

Sprawdziłem dokładnie, debuff trwa 25 sec na 25 man, więc tutaj nie ma problemu. Na 10 nie zwracam na to uwagi, bo zawsze pada bez zmiany tanka.
