### ISSUE TITLE
ROGUE  jego skile nie dzialaja absolutnie NIE DZIALAJA !

### ISSUE THREAD

**Issue by Qromwell** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1052]
UPDATE DO POSTU !

Skile jak CLOACK OF SHADOW oraz VANISH faktycznie zostaly naprawione.
              SHADOW SETP dziala rownież poprawnie.

Problem jest inny.  Kiedy jest malo ludzi na serwerze wszystko dziala normalnie. Nawet shadow step teleportuje tak jak powinien. Dopiero wieczorem kiedy jest wiecej ludzina serwerze pojawiaja sie bledy.
Nie widze innegowytlumaczenia jak lag serwera. Przez male opoznnia Vanish moze sprawiac wrazenie ze nie dziala jak i shadow step zle wtedy teleportuje.

Dziekuje za uwage i poprawione skile.

**Comment by spyke13** [comment]
Calkiem sie usmialem czytajac to zgloszenie :D

**Comment by Qromwell** [comment]
Nie widze nic zabawnego. Opisalem to co nie dziala. Co jeszcze moze mam to udowodnic i podanie napisac ze zdjeciem i osiagnieciami?

**Comment by spyke13** [comment]
"Do tego zaden ale to absolutnie zaden spel w czasie trwania cloack of shadow nie ma prawa zranic ani zadzialac na rogala, do tego zdejmuje aktualnie wszystkie doty magiczne z rogala."

PRzeczytaj opis tego skilla na swoim rogalu

**Comment by Qromwell** [comment]
Dokladnie to co napisalem. I czlowieku jak nie masz czego sie czepiac to czep sie swoich rodzicow.

**Comment by szopn** [comment]
Co do Vanisha kolega ma racje. Uzycie Vanisha powinno dzialac jak uzycie shadowmelda tzn. wszystkie lecace spelle w naszym kierunku powinny zostac uzyte ale nie powinny do nas doleciec.

Smieszna sprawa jest tez to ze wczoraj wieczorem mass dispel wyciagal ze stealtha. 

Czas trwania combatu jest za dlugi. Wysylalem linki z wowwiki gdzie jest jasno napisane ze trwa 5s.

Shadowstep rzeczywiscie zle teleportuje na gracza zamiast za gracza.

**Comment by szopn** [comment]
6s bylo dopiero od Cata
http://www.wowhead.com/forums&topic=23860&p=212420

Nie ma znalazlem zadnego dowodu na to ze combat powinien konczyc sie pozniej poza jakims bredzeniem na forum at gdzie nie ma zadnych dowodow

**Comment by spyke13** [comment]
Cloak of shadow sciaga wszystkie magiczne debuffy i daje 90% szans na resist kolejnych spelli przez 5 sek. Wiec gdzie Ty widzisz "Do tego zaden ale to absolutnie zaden spel w czasie trwania cloack of shadow nie ma prawa zranic ani zadzialac na rogala"

http://www.wowhead.com/spell=65961/cloak-of-shadows  opis niby skilla moba ale taki sam jak u rogala. Gdzie tu Twoje unikanie kazdego spella.

Z vanisha spelle typu channeling (penance) powinny wywalac i rakietka z engi. Na AT da rade dispelem wyciagnac z vanisha, nie wiem jak bylo na globie.

**Comment by Crackaw** [comment]
Mógłbym może dowody na tego vanisha? Serio, już słyszę któryś raz, że naprawcie vanisha pls, nic nie działa, a żadne dowody nie zostały przedstawione. Vanish sprawdzany był wiele razy i myślę, że został naprawiony, więc proszę o dowody, a co do znikania do owszem, dostajemy zmniejszony zakres wykrywania, ale nadal możemy zostać wykryci przez kogoś kto stoi praktycznie przy tobie. Proszę również o zgłaszanie spelli osobno, ułatwia to pracę i możemy łatwiej rozdzielić ich naprawę. Bugtracker nie jest forum od żalenia się na spelle tylko na zgłaszanie faktycznych bugów.
