### ISSUE TITLE
[Mage][Talent][Ignite]

### ISSUE THREAD

**Issue by LosowaNazwa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1053]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Kiedy 2 spell criticale uderza w target w tym samym momencie, do ignite'a zostaje liczony tylko damage z drugiego spella:
https://www.youtube.com/watch?v=37zKatP6C0E - scorch + fireblast uderzyly w tym samym momencie, obydwa byly criticalami i w sumie zadaly 7990 dmg, a wiec ignite powinien zadac lacznie 3196 dmg (1598 na tick) a jak widac zadal 1924 damage (962 na tick) a jest to dokladnie 40% z 4810 czyli damage'u samego fireblasta.

To samo stalo sie tutaj, tym razem fireball polaczony z pyroblastem:
https://www.youtube.com/watch?v=0xdbEIDXGWo
W sumie zadaly 14811 wiec oczekiwany dmg ignite'a to ~5924 (~2962 na tick), ale jak widac zadal 3150 obrazen (1575/tick) czyli 40% dmg samego pyroblasta (7877)

**Oczekiwane działanie**: Ignite powinien zadawac 40% z obydwu spelli, jesli uderza one w tym samym momencie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Ignite_(old) - na dole jest o Ignite Munching
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Heartbraker** [comment]
Skoro Ignite Munching było na globie to skąd pomysł, że tu nie powinno tego być?:P

**Comment by LosowaNazwa** [comment]
Na globie ignite munching było bugiem, tak samo jak oddzialywanie saronite bomb na pewne platformy. Działanie talentu chyba powinno się zgadzać z opisem?

**Comment by yeniz** [comment]
Dzisiaj porobiłem testy i takie coś dziwnego mi wyszło po wycastowaniu scorch->cone of cold w tym samym ułamku sekundy http://imgur.com/a/xzZIP (niby najpierw uderzyłem scorch z kryta, ale ignite się nałożyło dopiero po cone of cold) , podobna rzecz się dzieje przy castowaniu frostbolt+ice lance na jednym ładunku finger of frost, oba spelle czerpią benefity z niego( i ew jeśli celem jest war ze spell reflect odbija oba spelle)

**Comment by Elaatu** [comment]
LosowaNazwa dzialanie spella powinno sie zgadzac z tym co bylo na globie, o ile platformy rozwalane od saronite bomby zostały naprawione to Munching zawsze byl na globie.

**Comment by LosowaNazwa** [comment]
Ignite Munching bylo bugiem na globie, czyli dzialaniem nieporzadanym. Czemu nie zostalo naprawione? Tego nie wiem, nie znam sie na programowaniu. Napewno jest to mozliwe, bo bylem swiadkiem poprawnego dzialania (wedlug opisu spella) na innym prywatnym serwerze. Dodatkowo, jaki jest sens w odwzorowywaniu czegos co nie dzialalo poprawnie, skoro moze byc inaczej?

**Comment by Badrng** [comment]
Munching wynikał z ograniczeń ówczesnych serwerów i silnika gry, ale nie występował w każdym takim przypadku. Także jeśli faktycznie dzieje się to za każdym razem kiedy spelle critną w tym samym czasie, to raczej jest to przegięcie w drugą stronę. Żeby odtworzyć działanie tego buga trzeba by odtworzyć działanie serwerów i innych czynników w  tamtym czasie, co jest raczej niemożliwe. Wszelkie inne próby zaimplementowania tego będą sztuczne i wcale nie "blizzlike".
