### ISSUE TITLE
[SPELL][ROGUE][Cheap Shot] - złe działanie

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1059]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Nie działający poprawnie czar Cheap Shot. Postać Rogue (Aridei - Human)

**Obecne działanie**: 
Kiedy na targecie jest używany czar Cheap Shot, moja postać przestaje atakować cel, a ogólnie cel jest czyszczony(czyli moja postać nic nie ma na targecie).

**Oczekiwane działanie**: 
Użycie czaru Cheap Shot nie powinno czyścić targetu i moja postać nadal powinna mieć i target i atakować go automatycznie.

**Co należy zrobić, aby odtworzyć ten błąd**:
Szczerze to nie wiem, co tu mam wpisać, oprócz tego, że wystarczy użyć czar Cheap Shot na jakimś targecie...

**Linki WoWHead/OpenWoW**:
http://www.wowhead.com/spell=1833/cheap-shot

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie ma dokładnej lokalizacji, wszędzie występuje ten błąd.

**Comment by xsitdev** [comment]
Nie jesteśmy w stanie tego odtworzyć, #invalid.
