### ISSUE TITLE
[QUEST]Frankly, It Makes No Sense

### ISSUE THREAD

**Issue by Trzyememce** [RaphaelSunwell/Sunwell-BugTracker-SCv2#106]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Problem z questem, ktoś może  zostać odebrany jako osoba używająca flyhack. Możliwe, że to visual.

**Obecne działanie**: Skorpion, w którym się poruszamy lata.

**Oczekiwane działanie**: Powinien chodzić po ziemi i pływać.

**Co należy zrobić, aby odtworzyć ten błąd**:
![wowscrnshot_112416_133230](https://cloud.githubusercontent.com/assets/23569717/20598777/0ab97752-b24b-11e6-8150-bc49e4079509.jpg)
![wowscrnshot_112416_133259](https://cloud.githubusercontent.com/assets/23569717/20598781/0eb397f2-b24b-11e6-9e29-f3732464c60d.jpg)

1. Wziąć quest Frankly, It Makes No Sense
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10672/frankly-it-makes-no-sense
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by xsitdev** [comment]
Niestety nie udalo sie odtworzyc bledu, w przypadku ponownego wystapienia prosimy o ponowne dodanie.
