### ISSUE TITLE
[QUEST] Escape from Durnholde

### ISSUE THREAD

**Issue by Calendil410** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1060]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jest to chain questów pozwalających dostać się do Black Morass. Questa rozpoczynamy w Caverns of Time następnie wchodzimy do Old Hillsbrad Foothills rozmawiamy z NPC przy wyjściu z jaskini, robimy dywersje a potem rozmawiamy z Thrallem i dostajemy questa z ucieczką. 

**Obecne działanie**: Thrall nie posiada żadnych opcji dialogowych pozwalających rozpocząć ucieczkę. 

**Oczekiwane działanie**: Thrall posiada opcje dialogową rozpoczynającą ucieczkę.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rozpocząć chain questów w Caverns of Time. 
2. Dojść do Thralla w Old Hillsbrad Foothills.
3. Porozmawiać z Thrallem.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=29599/escape-from-durnholde
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: ![wowscrnshot_060417_205547](https://cloud.githubusercontent.com/assets/28513544/26764519/66e5913c-4968-11e7-925a-20e5af5e7d7f.jpg)

**Comment by Afgann** [comment]
Opcja dialogowa u Thralla pojawia się po zabiciu bossa Lieutenant Drake (wcześniej trzeba podłożyć 5 bomb).

**Comment by Calendil410** [comment]
Sprawdziłem, działa.
