### ISSUE TITLE
[Spell][Mage][Living Bomb]

### ISSUE THREAD

**Issue by dominix12345** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1061]
Opis:
Brak możliwości nakładania bomby.
Obecne działanie
Bomby nie da się narzucić na cel gdzyż podobno jest już na narzucona silniejsza.
Dodam zdjęcia jak to wygląda w grze 
http://imgur.com/dAAu9Sp
http://imgur.com/hRy1ZSP
http://imgur.com/178qv40
Na pierwszym zdjęciu widać nawet ze  zaczyna się gc ale bomby nadal nie ma na targecie.
Mam ustawione również adony które pokazują mi czy bomba jest narzucona 
http://imgur.com/0nc5uFV
http://imgur.com/JDeyF8q
Czasami taka sytuacja zdarza się kilkukrotnie podczas jednego bicia bossa, a czasami nie widzę tego błędu wcale. Niestety jeszcze nie zauważyłem od czego jest to zależne.
Widziałem na forum ze jeden gracz zgłaszał coś podobnego.
https://forum.sunwell.pl/index.php?/topic/4062-problemy-z-living-bomba/
Oczekiwane działanie:
Spell Living bomb powinno dać się używać na target gdy poprzednia bomba wybuchnie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Living_Bomb?oldid=2407389
2. 
3.

**Comment by Rastlinek** [comment]
To samo samo jest z ze spelem maga Ice barier, w obu przypadkach błąd (nie mam pewności czy to błąd) występuje jeżeli podczas rzucania spella mieliśmy jakieś odpałki do spell power to przy kolejnej próbie rzucenia czaru jest właśnie ten komunikat że silniejszy spell jest aktywny. Tak samo jak byśmy próbowali rzucić arcane intelekt rank 1 gdy na targecie jest już rank 2 po prostu się nie da. Nie wiem jak jest z living bombą ale wiem że Ice barier nie bierze bonusu ze spell power więc powinna zawsze się dać odświeżyć. 

W twoim przypadku nie widać dota z living bomby ale jak odpalił cie się np trinket i rzuciłeś bombę która jest teoretycznie mocniejsza bo masz więcej spell pwoer i ta bomba critneła to odpalił ci się talent bodajże ignite (dopalanie) który też jest mocniejszy bo bierze % z bomby, a między czasie skończyła Ci się odpałka z trinketa to nie możesz rzucić słabszego spella dopuki te mocniejsze doty się nie pokończą. Nie mam pewności ale czy tak jest z living bombą ale na 100% jest tak z ice barierą. 

Edit: dominix12345 możesz porobić testy na kukłach rzucaj bombe a potem zdejmij np broń, żebyś miał mniej SP, i sprawdź czy błąd będzie dalej występował.

**Comment by Elaatu** [comment]
Dominix12345 to o czym Ty piszesz to jest tzw Debuff Cap. Living Bomb jest na targecie, zadaje dmg ale go nie widzisz. Wedlug starych adminow sunka byl to problem clienta i nie da sie tego naprawic ( a przynajmniej nie jest to blizzlike) moze nowa administracja cos z tym zrobi.
Podsumowujac zarzucanie Living Bomba dziala prawidlowo. 

BTW Rastlinek w jednym jak i 2 przypadku nie jest to blad. Ice Barrier jak masz wiecej sp to wiecej absorbuje, wiec nie mozesz go podmienic, w przypadku living bomba nie wazne ile masz sp dopoki nie zejdzie dota nie da sie odnowic

**Comment by Rastlinek** [comment]
Elaatu tak właśnie myślałem dlatego pisałem że nie jestem pewien że to błąd, ale pierwszych 3 skrinach nie widać living bomba, może być że go nie widać i zadaje obrażenia a może być że go nie widać i nie zadaje obrażeń :) Tego nie wiem trzeba by sprawdzić combat loga co tam jest napisane.

**Comment by LosowaNazwa** [comment]
Polecam MikScrollingBattleText, w momencie wybuchu living bomba. idealnie pokazuje damage z last ticka i wybuchu
