### ISSUE TITLE
[Instance] Zul'Farrak Event + bossy

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#107]
Opis: Event w Zul'Farrak nie dziala. Moby, m.in Sargeant Bly ID 7604 zapadaja sie pod ziemie albo nie wychodza z klatek. Prawdopodobnie cos z ich AI jest nie tak.
Jak ma byc: https://www.youtube.com/watch?v=QeWPi4vQjgo

**Comment by ThePuppetMaster** [comment]
Osoba testująca:
"Ogólnie losowo może zakończyć się wycieczka na ZF, lecz gdy chciało się "przyśpieszyć" i party leciało na dół zbić wszystko to wtedy się zacinały npc. Gdy się czekało na szczycie schodów to było wszystko w porządku."

**Comment by Danieloses** [comment]
Jeżeli poczekamy i damy odbyć dialog ekipie z Sergeant'em Bly na czele wszystko zadziała, jednak jeśli zaatakujemy bossa przed ich interakcją npc się zawieszą.
