### ISSUE TITLE
(NPC) Mortog Steamhead - Colifng Reservoir (entrance)

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1073]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: NPC, który stoi w Colifng Reservoir (entrance) powinien sprzedawać pewne itemki za Coilfang Armaments, oraz skupować śmieci jakie wynosimy z instancji.

**Obecne działanie**: Niestety niczego nie oferuje, jak również niczego nie skupuje (przynajmniej dla Ally).

**Oczekiwane działanie**: Dodać opcje handlu wraz z oferowanymi przez niego itemami

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać itemki do sprzedaży według listy z Wowheada
2. Dodać opcje kupna
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=23373/mortog-steamhead#sells
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Outland - Zangarmarsh - Colifng Reservoir (entrance) 51,5/35,5

**Comment by tetriandoh** [comment]
Bzdura npc działa poprawnie bo zapewne nie doczytałeś (lub nie znasz angielskiego) że należy mieć reputacje "Cenarion Expedition" na poziomie **exalted** piszą o tym w komentarzach oraz sam npc bodajże ma kwestie że nie handluje bez reputacji.
