### ISSUE TITLE
Brak lootu companionow w gniazdach 

### ISSUE THREAD

**Issue by Kefsham** [RaphaelSunwell/Sunwell-BugTracker-SCv2#108]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

W gniazdach, ktore znajdują sie w kilku lokacjach(The Barrens, Wetlands, Dustwallow Marsh, Un'goro Crater), możemy napotkać gniazda, z ktorych powinny dropić companiony. Niestety - gniazda są, natomiast brak w środku hatchlingow

Po kliknieciu na gniazdo nastepuje akcja zebrania itemu, natomiast w środku jest pusto

Oczekiwane działanie: Po kliknieciu w gniazdo powinniśmy mieć możliwość zabrania hatchlinga, odpowiedniego dla każdej lokacji.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wprowadzic loot do gniazd

**Linki WoWHead/OpenWoW**: na pokładzie darting hatchling znajdującego sie w dustwallow marsh

1. http://www.wowhead.com/object=202080/darts-nest
2. http://www.wowhead.com/item=48112/darting-hatchling
https://www.youtube.com/watch?v=9X6LJE5KPsE

**Comment by Seavitia** [comment]
Wedle OpenWow drop rate z gniazda powinien wynosić 100%.
Problem dotyczy wszystkich hatchlingów (Razormaw hatchling, darting hatchling, leaping hatchling oraz ravasaur hatchling)

**Comment by xnemeyethx** [comment]
To jest niestety dodane od patcha 3.2 :<

**Comment by ThePuppetMaster** [comment]
Powinno działać
