### ISSUE TITLE
HUNTER

### ISSUE THREAD

**Issue by Masakanashi** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1084]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Pet food nie daje efektu, który powinien (spiced mammoth treats )

**Oczekiwane działanie**: Po zjedzeniu, pet powinien otrzymać boost do staminy i obrażeń

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Hunter gotuje lub kupuje dany food (recka z cookingu za marki z daily)
2. Karmimy tym peta
3. Pet ie dostaje boosta który powinien

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Kowson** [comment]
Fałszywa informacja. Spiced Mammoth Treats jak najbardziej działa, używam od dawna i nigdy nie było z tym problemu. Nawet przed chwilą sprawdziłem, żeby się upewnić.

**Comment by valcy** [comment]
Kliknij prawym na ten food a nie karm go jak zwyklym zarciem :s

**Comment by Akha72** [comment]
Banany na BT za takie reporty :V
