### ISSUE TITLE
[Shaman][Talent] Lightning Overload

### ISSUE THREAD

**Issue by Rosenkrantz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1085]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: w.w. talent potrafi procnąć kilkukrotnie z jednego casta - dość zabawnie wygląda, gdy się rzuci 1 Lightning Bolt, widzi się dmg powiedzmy 3200, a potem 1600-800-400-200 w jednym momencie. 

**Obecne działanie**: Przy rzuceniu Lightning Bolt/Chain Lightning szaman ma 33% szans na to, że zaklęcie procnie talent, rzucając nowy LB/CL, zadający połowę obrażeń, który TEŻ ma 33% szans na procnięcie następnego LB/CL, zadającego połowę obrażeń... i tak prawdopodobnie ad infinitum, najwięcej, ile widziałem, to 5 dodatkowych. Na szczęście ciąg jest zbieżny (lim n/2 = 2) i nie ma możliwości one-shotowania wszystkiego co się rusza.

**Oczekiwane działanie**: Tylko oryginalny Lightning Bolt/Chain Lightning powinien móc włączać Lightning Overload (w wypadku CL na dowolnym trafionym celu z osobna, zadając dmg odpowiednio do celu, z którego przeskakuje - ale to zdaje się działać poprawnie, więc proszę tylko nie zepsuć przy okazji :P ).

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rzucać piorunami do skutku
2. ???
3. Profit

**Linki WoWHead/OpenWoW**:

1. http://wowis.net/wishead/?spell=30679 rank 3

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: nie dotyczy

**Comment by Merisorax** [comment]
"Tylko oryginalny Lightning Bolt/Chain Lightning powinien móc włączać Lightning Overload" - Nigdzie na stronie, na której wstawiłeś nie widzę żeby było coś takiego napisane. Ja wysiliłem się troszkę bardziej proszę bardzo: 
"LO procs seem to be able to proc LO as well , while the damage the resulting spell does is still calculated as half of the original one."
- http://wowwiki.wikia.com/wiki/Lightning_Overload 
- http://wow.gamepedia.com/Lightning_Overload

"It can indeed proc off itself, to much enjoyment when it happens with Chain Lightning. :)" 
- http://www.wowhead.com/forums&topic=25609/lightning-overload

**Comment by Rosenkrantz** [comment]
Gdyby działało tak, jak piszą na tej stronie, to by znaczyło, że powinienem widzieć 3200, a potem 1600-1600-1600-1600 praktycznie dowolną ilość razy. Jeżeli wygrasz w totka to zabijasz ludzi na arenie jednym zaklęciem. Ten opis jest raczej spowodowany mylną interpretacją tego, co się dzieje przy Chain Lightningu.

Chain Lightning może procnąć Overload z każdego celu osobno. Cel, na którym procnął Overload, staje się dla niego pierwszym celem, przez co piorun skacze do kilku celów od szamana. Początkowy damage dla overloada to damage tego celu, od którego procnął, nie pierwszego.

Dyskusja na forum jest z patcha 2.4.3.

**Comment by Wojtyas** [comment]
"LO procs seem to be able to proc LO as well , while the damage the resulting spell does is still calculated as half of the original one"

Dla każdego kolejnego lightning bolta, 'original one' jest ten poprzedni, który wywołał kolejny mirror. Czyli pierwszy mirror LO ma 50% dmg pierwszego (original one'a). Z kolei trzeci jest mirrorem drugiego (drugi w tym momencie jest original), i powinien zadać 50% dmg drugiego LO. Tak więc powinno być dokładnie tak jak napisałeś na samym początku: "... 3200, a potem 1600-800-400-200..."
Dla mnie wszystko działa poprawnie w tej kwestii ;P

**Comment by Namzaj** [comment]
http://i67.tinypic.com/vqodq0.jpg

Odnośnie tego obniżania dmg, z drugiego spella o 50%.

**Comment by darkclif** [comment]
Mnie bardziej ciekawi to zdanie "Na szczęście ciąg jest zbieżny (lim n/2 = 2) i nie ma możliwości one-shotowania wszystkiego co się rusza." Jak ten ciąg ma się do przedstawionej sytuacji? Nie chodziło bardziej o coś w stylu lim DMG/2^n = 0 gdy n zmierza do nieskończoności gdzie DMG jest zadanymi obrażeniami z pierwszego spella który striggerował LO?

**Comment by Rosenkrantz** [comment]
Tak, jak widać po opisie sytuacji chodzi mi o ciąg, w którym każdy następny wyraz jest połową poprzedniego :p jakieś zaćmienie umysłowe miałem.
