### ISSUE TITLE
Reputacja dla Steamwheedle Cartel

### ISSUE THREAD

**Issue by Durotos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1087]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Reputacja dla Steamwheedle Cartel

**Obecne działanie**:  Moby przy miastach Goblinow nie dają reputacji po wbiciu Revered.

**Oczekiwane działanie**: Mobki powinni dawać repe.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wow.gamepedia.com/Mobs_which_affect_reputation_with_Steamwheedle_Cartel tu wszystko jest.
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Booty Bay. Ratchet. Everlook . Gadgetzan

**Comment by Akha72** [comment]
To działa tak, że bijesz np piratów w Barrens i dostajesz repe z Ratchet aż do poziomu revered (z innymi miastami dalej leci), aby wbić exalted musisz zmienić moby na dające domyślnie innemu miastu repe lub tłuc named npc. Taki sposób działał, może coś się zbugowało, ale to nwm, bo z tego zgłoszenia nic nie wynika.

EDIT: fakt, mój błąd. Miałem exalted z Ratchet i revered z pozostałymi, ale potem dobiłem na evencie, nie npcach. Punkt dla Ciebie.

**Comment by Rastlinek** [comment]
To działa dopiero od cata na woltku one nie dają repy na revered. Polecam poczytać komentarze tutaj http://www.wowhead.com/achievement=2336/insane-in-the-membrane#comments a zwłaszcza to "As of 4.1, pirates in Tanaris were giving me full Gadgetzan rep from revered to exalted. While this still left me with Everlook taking the longest, it was a welcome surprise. A co klepać ma exalted to nie wiem :)
