### ISSUE TITLE
[RACIAL][Human] [Mace Specialization] [Sword Specialization]

### ISSUE THREAD

**Issue by dilldadisbak** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1095]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Racial mace i sword specialization nie dzialaja poprawnie, nie dzialaja w ogole lub dziala na plus

**Obecne działanie**: Niezaleznie od posiadanej broni dodaje nam 3 expertise mimo iz przy najechaniu na statystyke pokazuje przykladowo 13 koncowy wynik to 16 nie afektowany poprzez zmiany broni.

**Oczekiwane działanie**: Zmiana broni powinna dzialac jak modyfikator expertise podnoszac go o 3 w zaleznosci od tego czy zalozony jest mace czy sword.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Stworzyc postac w rasie humana
2. Zmieniac bron miedzy axe, swordem a macka
3. Obserwowac zmiany expertise

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Sword_Specialization_(human_racial)
2. http://wowwiki.wikia.com/wiki/Mace_Specialization_(human_racial)
3. https://zapodaj.net/83db9b513bb4b.jpg.html
4. https://zapodaj.net/00d56770e7d51.jpg.html
5. https://zapodaj.net/eaf83c9e13870.jpg.html

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Unbugable** [comment]
A zdejmij cały gear i wtedy zobacz. Pamięć już nie ta, ale coś mi mówi, że po prostu (podobnie jak z hitem draenei) racial nie dodaje się wizualnie w okienku postaci.

**Comment by dilldadisbak** [comment]
Tylko ze tutaj ten racial sie wizualnie dodaje przy sciagnieciu np calego gearu (nawiasem to zostaje 0 tak jak powinno) a zalozeniu i manipulacji przy broni przy czym nie jestem pewien czy to tylko wizual czy mechanicznie tez cos sie dzieje z ta statyska

**Comment by dilldadisbak** [comment]
bump

**Comment by MonichSC** [comment]
To tylko visual, zmień broń i zrób reloga, wyświetli się poprawna wartość.
