### ISSUE TITLE
[TALENT][DK] Bone Shield ICD

### ISSUE THREAD

**Issue by mjgolebiewski** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1097]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Bone Shield nie posiada internal cd - stacki spadają od każdego direct dmg. Podobnie jak w elemental shieldach szamana, BS po procnięciu stacka powinien załączać się cooldown - obrażenia powinny być obniżone przez cały czas trwania buffa co z ICD 3s efektywnie daje nam conajmniej 9 sekund -20% do otrzymywanych obrażeń (12s z glyphem).

**Obecne działanie**: Bone Shield spada praktycznie od razu (zwłaszcza w sytuacji gdzie otrzymujemy dmg od większej ilości przeciwników); nie posiada internal cd jak pozostałe shieldy ze stackami.

**Oczekiwane działanie**: Po procnięciu Bone Shield załącza się ICD (3s) który gwarantuje co najmniej 9 sekund buffa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Złap agro kilku mobów 
2. Włącz Bone Shield
3. Stacki spadają od każdego direct dmg

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Bone_Shield?diff=2185031&oldid=2178684
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Akha72** [comment]
Jakiś dowód (bo w tym linku z wowwiki nic o icd nie jest napisane) ?

**Comment by mjgolebiewski** [comment]
http://www.wowhead.com/forums&topic=99398/question-about-bone-shield
http://www.mmo-champion.com/threads/899254-Question-about-Bone-Shield (thread z cata, ale poza przeniesieniem do blood funkcjonalność bsa sie nie zmieniła)

Po wrzuceniu hasła 'bone shield icd' wyskakuje sporo odnośników, wybrałem te najrozsądniejsze - nadal są to źródła dosyć niepewne. Najbardziej prawdopodobnym jednak wydaje się że w zamyśle blizzard chciał zrobić z BS coś na zasadzie barkskin (skill druida).

Edit:
https://github.com/TrinityCore/TrinityCore/issues/1412
Okazuje się że na bugtrackerze trinity core był już podobny problem (z tym że ustalona została błędna wartość - 1,5s).

**Comment by Heartbraker** [comment]
Już była podejmowana próba naprawy https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/440 która doprowadziła do znacznie poważniejszego buga - https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/632 - stacki w ogóle nie schodziły ;p (przynajmniej w pvp)

**Comment by Danieloses** [comment]
Dobra próba naciągnięcia mechaniki na swoją korzyść. Spośród wszystkich źródeł  z google wybrałeś dwa jedyne linki gdzie jest dosłownie parę komentarzy mówiacych o błędnym 3sec internal CD, podczas gdy miałeś dostęp do dziesiątek linków, w których jest opisane prawidłowe działanie "2sec". Pominąłeś nawet najbardziej oczywiste źródło czyli wowwiki  "Patch 6.0.2 (14-October-2014): Bone Shield charges can now be consumed at a rate of once per second (up from once every 2 seconds)".

**Comment by mjgolebiewski** [comment]
@Danieloses 
Dzięki za znalezienie konkretnej wartości. Nie będę edytował głównego posta żeby Twój komentarz miał sens. Pomimo przypisania mi niskich pobudek i ataku ad personam potwierdzasz jednak istnienie buga - na chwilę obecną nie ma żadnego ICD i Bone Shield znika zdecydowanie zbyt szybko, zwłaszcza w przypadku dostawania obrażeń z różnych źródeł bądź od targetu z wysokim attack speedem.
