### ISSUE TITLE
[Quest] The Traitor's Shadow

### ISSUE THREAD

**Issue by Io36** [RaphaelSunwell/Sunwell-BugTracker-SCv2#11]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W chwili obecnej nie można wykonać q The Traitor's Shadow. Bład pojawił sie po wieczornym wgraniu bazy danych.

**Obecne działanie**: Można podejść do q itemu (http://www.wowhead.com/object=181150/dusty-journal#starts) kończącego q, zagadać, ale nie ma opcji kończącej q ani rozpoczynającej następny q Hints of the Past

**Oczekiwane działanie**: Działający q

1. Podejść do q itemu w koordynatach 79.6, 17.7 
2. Zakończyć q gadając z q item (dziwnie to brzmi)
3. Pobrac nowy q od q itemu Hints of the Past

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Podejść do q itemu w koordynatach 79.6, 17.7 
2. Próbować zakończyć q 

**Linki WoWHead/OpenWoW**: 

1. www.wowhead.com/quest=9161/the-traitors-shadow
2. http://www.wowhead.com/object=181150/dusty-journal#starts
3. http://www.wowhead.com/quest=9162/hints-of-the-past

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 79.6, 17.7

**Comment by ThePuppetMaster** [comment]
Powinno już działać.
