### ISSUE TITLE
[EVENT][QUEST] Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by tageib** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1100]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:W kalendarzu jak co niedziele zapisany jest event Stranglethorn Fishing Extravaganza, niestety NPC Riggle Bassbait rozpoczynający go w BootyBay nie pojawia się w odpowiednim czasie, lecz godzinę później. Proszę o przesunięcie eventu w kalendarzu bądź o poprawienie czasu w jakim NPC pojawia się.
**Obecne działanie**: Riggle Bassbait nie pojawia się w ciągu co najmniej godziny od planowanego rozpoczęcia się eventu

**Oczekiwane działanie**: Riggle Bassbait powinien pojawic się w Booty Bay o godzinie 14:00

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przyjść w niedzielę do Booty Bay o godzinie 14
2. Czekać aż się nie pojawi (XD) do godziny 15
3. Brak profitu

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=44765/stranglethorn-fishing-extravaganza
2. http://www.wowhead.com/npc=15077/riggle-bassbait
3. http://www.wowhead.com/stranglethorn-fishing-extravaganza

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
27, 76 Stranglethorn Vale

**Comment by Akha72** [comment]
Pojawia się wraz z eventem o 15tej, event trwa do 17, npc do 18tej.

**Comment by Crackaw** [comment]
Zamykam. Jeżeli błąd nadal występuje proszę o komentarz z prośbą o reopen
