### ISSUE TITLE
[Hunter] Trapy, pytanie/dyskusja

### ISSUE THREAD

**Issue by bugbuster20** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1102]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Na wstępie chciałem prosić o nie obrzucanie błotem, ponieważ nie znalazłem dobrych źródeł, ale wydaje mi się, że trapy huntera mają ciut za duży zasięg. Pytanie brzmi, jak rozumieć promień łapania trapów huntera? 2 yd od środka koła pokazanego podczas rzucania freezing arrow, czy 2yd od krawędzi obręczy (co wydaje mi się nielogiczne i nieintuicyjne), czyli na oko 6 yd. 

**Obecne działanie**: Obecnie trapy huntera posiadają większy radius niż melee range, co widać na załączonym filmiku. W duelu stoimy maksymalnie daleko od siebie, tak aby sięgał nas auto attack i jak widać trap łapie przeciwnika, mimo rzucenia go nawet lekko za plecy.

**Oczekiwane działanie**: Trapy huntera powinny prawdopodobnie łapać 2 yard od środka koła i działać tak samo jak pozostałe aoe tj. ich zasięg nie powinien wychodzić poza okrąg (nie tak drastycznie, bo pozostałe aoe również MINIMALNIE odstają)

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  postawić kilka trapów w określonych odległościach od targetu.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1.  https://wotlk-twinhead.twinstar.cz/?spell=14310
2.  http://wotlk.evowow.com/?spell=60192
3.  https://vimeo.com/222084073

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by dathremar** [comment]
Zasieg trapow nie byl nigdzie okreslony na globalu, jednak byl duzo wiekszy niz marker AoE trapa. Na warmane(strzelam, ze piszac reporta sugerowales sie dzialaniem trapow na tym serwerze) na 100% maja wlasne skrypty, ktore znaczaco odbiegaja od retaila. 
https://www.warcraftmovies.com/movieview.php?id=145315 
2:07
2:27
4:40 
Tak dzialaly trapy na retailu - range byl ogromny, prawdopodobnie nawet wiekszy niz obecnie na sunwellu.

**Comment by Danieloses** [comment]
Trapy raczej miały taki range na wotlku jaki mamy obecnie na sunwellu, może ci się wydawać, że mniejszy (3yardy), ponieważ rzeczywiście na vanilli, tbc, cata itd. wszędzie były 3yardy. To 5 wotlkowe to jakiś nieudany eksperyment blizzarda xD, ale tak właśnie było na retailu.
