### ISSUE TITLE
[ACHIEVEMENT] Torch Juggler

### ISSUE THREAD

**Issue by Iskrowy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1106]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie mozna lapac pochodni, po zlapaniu znikaja kompletnie

**Obecne działanie**: W Orgrimmarze te pochodnie dzialaja normalnie, ale w Dalaran nie mozna ich lapac

**Oczekiwane działanie**: Powinny pojawiac sie w ekwipunku po zlapaniu i powinny naliczac sie do licznika z achievementa. 
**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by yeniz** [comment]
potwierdzam, również nie można użyć q itemu(Unlit Torches) do daily "Torch Catching"

**Comment by MonichSC** [comment]
Łatka naprawiajaca unlit torches czeka już na wgranie na serwer.
