### ISSUE TITLE
[PRZEDMIOT][NIE DZIAŁA] META GEM "EMBER SKYFLARE DIAMOND"

### ISSUE THREAD

**Issue by kacak0** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1107]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Gem nie daje bonusów.

**Obecne działanie**:  Gem nie daje bonusów.

**Oczekiwane działanie**: Gem powinien zwiększać spell power o 25 i intellect o 2%.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Włożyć gem w przedmiot, założyć przedmiot, założyć 3 czerwone gemy.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=41333/ember-skyflare-diamond
2. 
3.

**Comment by xsitdev** [comment]
Nie jestem w stanie potwierdzić, założony gem prawidłowo zwiększa staty do postaci.
