### ISSUE TITLE
[SPELL] Flametongue Weapon

### ISSUE THREAD

**Issue by mrskiner** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1108]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Shaman, Flametongue weapon

**Obecne działanie**: umiejętnosc nie działa od 6 poziomu umiejętnosci, poprzednie działają,używajac na obie bronie działa tylko na jedną, buffuje drugą ale ta nie daje już spell bonus oraz nie zadaje obrazen od ognia. Edit: Sprawdziłem bardziej szczegółowo, poziom umiejętnosci od 1 do 5 działa dobrze na obie bronie, jest problem z poziomem 6tym.

**Oczekiwane działanie**: Flametongue weapon na obu broniach powinien sie aktywowac z kadzym atakiem i zadawac obrazenia od ognia, dodatkowo powinienem otrzymywać spell bonus z obu broni, a nie tylko z jednej jak w tym przypadku.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Shaman 58 poziom bo taki mam.
2. Rozwinac drzewko enhancement  w talentach
3. Załozyc 2 bronie jedno reczne, zbuffowac i sprawdzic spell bonus w statystykach, oraz uderzac moby i podziwiać jak bardzo to nie działa.

**Linki WoWHead/OpenWoW**:

1. to jest tak oczywisty błąd ze nie będe szukał, a na starym sunwellu bo gralem, działało poprawnie.
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Rosenkrantz** [comment]
Bić z ognia raczej powinno, ale spell dmg? Z talentami na 80lv to daje 274 SD, nigdy nie zobaczyłbyś ele szama z tarczą w PvE, bo nawet biały daggerek od vendora byłby bardziej opłacalny, dopiero tarcza z Marrowgara HC mogłaby być... równa. Sam zobacz staty: http://wowis.net/wishead/?item=50616  Przez zdrowy rozsądek śmiem wątpić w tą część.

**Comment by mrskiner** [comment]
Nie do końca rozumiem o co chodzi Rosenkrantz, może pomyliłes ele z enh, a mi chodzi o enhancement, walka dwiema brońmi na raz, wilki i te sprawy.

**Comment by mrskiner** [comment]
Jak zwykle, ogromne zainteresowanie bugiem który można naprawić w moment.

**Comment by mrskiner** [comment]
Update: wbiłem 64 i dostałem kolejny poziom umiejętnosci "7", ten działa poprawnie, wygląda na to że jest problem z poziomem 6 flametongue weapon.
