### ISSUE TITLE
EVENT Midsummer

### ISSUE THREAD

**Issue by Sh4dowson** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1109]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Brak NPC związanych z eventem po stronie Ally oraz brak ogniska dla Hordy w Feralas (the forgotten coast)   **:

**Obecne działanie**: Brak NPC, brak ogniska

**Oczekiwane działanie**: NPC i ognisko powinny znajdować się w eventowym obozowisku

**Co należy zrobić, aby odtworzyć ten błąd**:

1. udać się na miejsce eventu Feralas (the forgotten coast)
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by grigorlives** [comment]
Ognisko jest kawałek na lewo od Feathermoon Stronghold, a przynajmniej wczoraj tam było, completable ale do poprawki.

**Comment by Heartbraker** [comment]
Na wotlku nie powinno być żadnego ogniska na The Forgotten Coast. Patrzysz na guide dla późniejszych dodatków.
