### ISSUE TITLE
[NPC] Kruban Darkblade (ID 14843)

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#111]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: NPC stoi przed auction housem w Orgrimmarze mimo tego, że nie ma Darkmoona.

**Oczekiwane działanie**: NPC powinien się pojawić tydzien przed Darkmoon Faire oraz w czasie Darkmoon, ale tylko i wyłącznie jeżeli Darkmoon będzie miał miejsce w Mulgore.

"He is only available the week before Darkmoon Faire is set up in Mulgore, and during the fair."

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Pójść do Orgrimmaru niedaleko Auction House.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Kruban_Darkblade
2. http://db.vanillagaming.org/?npc=14843#starts
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
52.9/66.6 Orgrimmar - Valley of Strength

**Screeny**:
1. http://i.imgur.com/OQUAM2N.jpg

**PROPOZYCJA**:
Można przestawić tego npc na kordy 53.7/66.4 - dokładnie w to miejsce http://i.imgur.com/j6sXKDP.jpg - w blizzowym miejscu średnio pasuje miejsce, w którym stoi i (moim zdaniem) troche przeszkadza psując stylistykę Orgri.

**Comment by kovaq** [comment]
Ork stoi w prawidlowym miejscu, natomiast rzeczywiscie pojawia sie troszke za wczesnie.
Dodatkowo nie tanczy w momencie uzycia interakcji - pytani gdzie jest darkmoon.

"He annouces the arrival of the Darkmoon Faire. If you choose to say

_The Darkmoon Faire has already arrived, you say? Where is it located?_

he will answer your question and burst into dance. One can't help but love watching an Orc dance .."

**Comment by Shon-su** [comment]
poprawione, nie dograne. On teraz stoi chyba cały czas
