### ISSUE TITLE
[World Event] Midsummer Fire Festival - Feralas (brak NPC'ów)

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1114]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Obok namiotów World Eventu Midsummer Fire Festival  powinni znajdować się NPC'e zlecający questy.

**Obecne działanie**: W lokacji Feralas dla Ally (koord. 46,9/44,0) znajduje się namiot tego World Eventu, niestety brak jakichkolwiek NPCów zlecających questy. Niestety przez brak NPCów World Eventu w Feralas nie da się zaliczyć co najmniej 3 Achievelemntów:
1. Flame Warden of Kalimdor
2. King of the Fire Festival
3. The Fores of Azeroth

**Oczekiwane działanie**: 
Dodać NPC'ów w Feralas.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać odpowiednich NPCów zlecających/odbierających questy.
2. Dodać ognisko w ramach questu Desecrate this Fire! dla Hordy.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11817/honor-the-flame
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Kalimdor - Feralas 46,9/44,0

**Comment by kovaq** [comment]
Bylem tam dzis i zgasilem aliancki ogien bez problemu. NPC znajduje sie na wyspie, za wioska night elfow. Ty pewnie myslisz, ze ten namiot przy molo na kontynencie to miejsce, w ktorym powinny stac npce?

**Comment by Rastlinek** [comment]
To jest link do cata, NPC są na wyspie.
