### ISSUE TITLE
[NPC] Grimtotem Naturalist (ID 7726) Używa nieodpowiednich skilli

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#112]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Grimtotem Naturalist (ID 7726) używa nieodpowiednich skilli związanych z bear form oraz humanoid form.

**Obecne działanie**: Jeżeli Grimtotem Naturalist jest w Bear Formie to używa wszystkich 4 dostępnych skilli: Demoralizing Roar, Maul, Rejuvenation, Wrath.

**Oczekiwane działanie**: Będąc w Bear Form Grimtotem Naturalist powinien używać: Melee Attack, Demoralizing Roar, Maul. Będąc w Humanoid Form: Melee Attack, Rejuvenation, Wrath.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakować kilku Grimtotem Naturalist i sprawdzić ich zachowanie w walce.

**Linki WoWHead/OpenWoW**:

1. https://vanilla-twinhead.twinstar.cz/?npc=7726#abilities
2. http://wotlk.openwow.com/npc=7726#abilities

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
70.9 / 38.2 Feralas

**Comment by kovaq** [comment]
Mob ma problemy z movementem, z shapeshiftem i z castami.
https://youtu.be/SMnNCBxLTEg
