### ISSUE TITLE
Combat nie wbija się gdy bufujemy gracza w combacie

### ISSUE THREAD

**Issue by Rastlinek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1120]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  W PvP/PvE jak bufujemy lub leczymy osobę w combacie nie wbija combatu osobie rzucającej buf/leczenie. Na RHC spell  Focus Magic http://wotlk.evowow.com/?spell=54646 nie wbił combatu, ale za to Arcane Intellect http://wotlk.evowow.com/?spell=42995 wbija combat.

**Obecne działanie**: Bufując osobę w combacie nie dostajemy combatu.

**Oczekiwane działanie**: Po leczeniu lub bufowaniu targetu w combacie powinien wbić się combat osobie rzucającej bufa/leczenie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Jedna osoba wbija combat w walce a druga leczy/buje osobę w combacie.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Combat
2. https://forum.sunwell.pl/index.php?/topic/5454-re-sap-rogala/
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Namzaj** [comment]
https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/790

https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/789 


Było :D
