### ISSUE TITLE
EOE25 trzecia faza nie dziala aoe healing na smokach

### ISSUE THREAD

**Issue by Baggedmilk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1121]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:na trzeciej fazie malygosa nie dziala obszarowy healing

**Obecne działanie**: na trzeciej fazie malygosa nie dziala obszarowy healing

**Oczekiwane działanie**: na trzeciej fazie malygosa powinien dzialac obszarowy healing

**Co należy zrobić, aby odtworzyć ten błąd**:

1. dotrwac do trzeciej fazy malygosa
2. wbic pare stackow
3. uzyc aoe healingu

**Linki WoWHead/OpenWoW**:

1. https://wotlk-twinhead.twinstar.cz/?npc=31734
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Baggedmilk** [comment]
naprawione czy co? w wiekszosc zgloszen poprostu zamykacie nie podajac zadnej informacji
@down
dziekuje

**Comment by Crackaw** [comment]
Naprawione. Poprawka powinna wejść z najbliższym updatem
