### ISSUE TITLE
Shutting Down Manaforge Coruu

### ISSUE THREAD

**Issue by MrCichy94** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1122]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Z racji iż od początku robię lore, kolejny nie działający poprawnie quest. 
http://www.wowhead.com/quest=10330/shutting-down-manaforge-coruu

**Obecne działanie**: Nie zalicza poprawnie wykonanego questa. Wszystko działa poprawnie, aż do samego końca. Wydaje mi się, z obserwacji własnych poprzedniego questa bliźniaczego, że na końcu obrony shoutdown'u manaforge'a powinna być animacja wybuchu- wówczas we wcześniejszym następowało zaliczenie. Tutaj tego brak i quest jest zaliczany tylko przez carbonite. 

**Oczekiwane działanie**: Zaliczenie ukończonego poprawnie questa.

**Co należy zrobić, aby odtworzyć ten błąd**: Jest to chain. Quest 9 polega na wylotowaniu Coruu Access Crystal i za jego pomocą wyłączeniu manaforge'a. Bronimy 2 minuty przed technikami i powinno być gotowe. Nie zalicza questa (mi nie zaliczyło razów 3, w tym raz wziąłem go ponownie po skasowaniu).
1. http://screenshooter.net/102994108/luvlvbb
2. http://screenshooter.net/102994108/qrnfefo
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10330/shutting-down-manaforge-coruu
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 
netherstorm (outland), prawa dolna wyspa.

**Comment by ethuath** [comment]
Nie tak dawno jak miesiąc temu robiłem wszystkie questy z Netherstorm i wszystko działało. Nie wiem czy coś się popsuło, czy może coś robisz źle. W każdym razie do weryfikacji.

**Comment by MrCichy94** [comment]
Zaraz po resecie realmu zrobiłem bez problemu. 
(jedyna różnica to z aurą która nie zadaje dmg z mojej strony). 
Tak więc już działa poprawnie. 

Zaspamuję- pięknie ten netherstorm zrobiliście :) Lore siedzi.
