### ISSUE TITLE
[Pet] Znikający pet huntera

### ISSUE THREAD

**Issue by Bujaczek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1129]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Permanentnie znikający pet huntera po śmierci postaci, pomimo nabitego "wskaźnika szczęścia' na kolor zielony.

**Oczekiwane działanie**: Pet nie powinien uciekać sam z siebie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ghost** [comment]
Yyy... Możesz użyć Call Pet i go przyzwać, albo go ressnąć.

**Comment by Bujaczek** [comment]
Napisałem specjalnie "Permanentnie znikający pet" oznacza to, że pet znika na zawsze, a nie tylko do czasu przyzwania... Używałem wielokrotnie i nie podziałało, sprawdziłem nawet skillem Call Stabled Pet i nie było żadnego peta.

**Comment by ghost** [comment]
To coś Ci się zbugowało, ja nie miałem takiego przypadku. Pozostaje Ci złapać nowego, bo ciężko będzie to naprawić, skoro występuje to raz na tysiąc razy :P

**Comment by ghost** [comment]
Napisz ewentualnie wszystkie istotne informacje i może ktoś to naprawi ;P

**Comment by Crackaw** [comment]
Napisz ticket w grze po prostu, jeśli ten bug nadal występuję u ciebie, po złapaniu peta.
