### ISSUE TITLE
[NPC] Grimtotem Naturalist (ID 7726) Bear Form Visual

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#113]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Grimtotem Naturalist (ID 7726) mimo tego, że posiada na sobie buff 'Bear Form' nie jest wizualnie w formie miśka.

**Obecne działanie**: Grimtotem Naturalist (ID 7726) mimo tego, że posiada na sobie buff 'Bear Form' nie jest wizualnie w formie miśka, ale używa skilla 'Maul', który defacto nie pasuje do jakiego visual formy.

**Oczekiwane działanie**:  Grimtotem Naturalist jeżeli posiada buff 'Bear Form' powinien mieć model druidowego misia taurena.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakować kilku Grimtotem Naturalist i sprawdzić ich zachowanie w walce.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Grimtotem_Naturalist

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
70.9 / 38.2 Feralas

**Comment by ThePuppetMaster** [comment]
Sprawdziłem. Rzeczywiście NPC nie ma wizualnie formy, ale po zaatakowaniu problem znika i NPC normalnie zamienia się w misia.
