### ISSUE TITLE
Explosive Trap BUG

### ISSUE THREAD

**Issue by anibus21** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1131]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Od wprowadzenia nowego REV'a w dniu 05.07 Explosive trap zaczal sie bugowac.
**Obecne działanie**:
Obecnie dziala to wiec tak ze stawiamy trapa, mobek w niego wbiega, trap sie aktywuje i znika niepozostawiajac efektu zadnego ani w postaci inicjujacego dmg ani doty...

**Oczekiwane działanie**:
Tak jak do tej pory dzialalo, trap w momencie aktywowania exploduje a nastepnie zostawia plame ktora zadaje aoe dmg w postaci doty trawjacej kilkanascie sek.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pulamy grupke mobkow
2.  Stawiamy kilkakrotnie explosive trap
3.  Obserwujemy efekty (ok 1/3-4 trapow aktywuje sie poprawnie)

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by mjgolebiewski** [comment]
bump, podobnie znika snake trap

**Comment by ghost** [comment]
Potwierdzam. Trapy nie działają.

**Comment by Crackaw** [comment]
Można wiedzieć w jakich przypadkach i czy dzisiaj sprawdzałeś?

**Comment by ghost** [comment]
Sory, że dopiero teraz, ale nie miałem zbytnio czasu. Trapy już działają, za to nie działa Daze z Chimera Shotu i Multi Shotu jeżeli mamy w to talenty w MM. :)

**Comment by Crackaw** [comment]
Trapu nie działały. Przynajmniej nie zawsze ;) Problem był ze snake trapem i innymi aurami które dostawały dziki zasięg.

**Comment by ghost** [comment]
Nie no 2 dni temu byłem na RHC i żaden trap mi nie działał, wyglądało jakby moby je resistowały :D
