### ISSUE TITLE
[Visual] Dziwny back po wejściu na mounta

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#114]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po wejściu na mounta nasz back zachowuje sie dziwnie, zmienia szybko swoja pozycje, 'wchodząc' w naszego mounta.

**Dowód**: https://youtu.be/CpTwCsnPXw0

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść na mounta jako Blood Elf (nie wiem czy w innych rasach też to występuje).

**Comment by xsitdev** [comment]
To trzeba by kierowac do Blizzarda 👍
