### ISSUE TITLE
Latanie na Black Qiraji Battle Tank po Estern Kingsdoms

### ISSUE THREAD

**Issue by polip22** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1147]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Bug z lataniem po Estern Kingsdoms.

**Obecne działanie**: Latam po Estern Kingsdoms na Black Qiraji Battle Tank.

![obraz](https://user-images.githubusercontent.com/30083863/28079714-b90bf622-6669-11e7-9f9e-ec94fdcafe1f.png)

**Oczekiwane działanie**: Legendarnym mountem Black Qiraji Battle Tank powinno się dać normalnie jeździć jak np. na raptorze, a nie latać jak po northrend czy outland.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Teleportować się do Eversong Woods.
2. Wsiąść na Legendarnego mounta Black Qiraji Battle Tank.
3. Użyć klawisza skakania/latania w tym przypadku "spacji" i cieszyć się lataniem.

**Comment by Rosenkrantz** [comment]
Sprawdź tez Azuremyst/Bloodmyst Isle, prawdopodobnie też się będzie dało latać - startowe strefy Draenei/BE są umiejscowione w tej samej instancji, co Outland.

**Comment by Baggedmilk** [comment]
odpowiedz od cule jak ktos sie wspominal o tym mouncie pay2win
"Mount został wyłączony zarówno na arenach jak i BG oraz absolutnie nie można nim latać po Kalimidorze czy EK. 

Działa on jak np. Celestial Steed. 

Co do samego posta, na przyszłość proszę Cię o składanie zdań w inny sposób i unikanie pretensjonalnego tonu, skoro nie masz (jak sam stwierdziłeś) pojęcia jak działa on tutaj, a tylko podejrzewasz jak może działać. 

Zamykam. "

**Comment by bog666** [comment]
iks de
