### ISSUE TITLE
Zul'Farrak - event bug

### ISSUE THREAD

**Issue by Itashii** [RaphaelSunwell/Sunwell-BugTracker-SCv2#115]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po zejsciu 5tki npc na dół i ubiciu bosów któe sie zespawniły, npc nie podchodzą do "fontanny" i jest brak mozliwosci porozmawiania/odpalenia eventu

**Obecne działanie**: Npc schodzą i stoją w miejscu bez żadnej reakcji

**Oczekiwane działanie**: Powinnie podejsć do fontanny, i u npc : "Sergeant Bly" powinna być możliwość rozpoczęcia dialogu. Oraz u npc "Weegli Blastfuse" też powinien być dialog, który skutkuje otwarciem drzwi do ostatniego bossa, oraz użyciem Hs'a przez piatke npc. 

Niestety nie wiem jak powinien dialog wygladac z goblinem, ale wiem jak z "Sergant Bly"
'po uzyciu dialogu powinno byc napisane w tej ksiazce tak : Thanks a lot. <nick gracza>. We couldn't have mad it without you. Oh and if I had mentioned before something about repaying you for saving us, well... you can forget it!'

I nasza opcja wyboru dialogu to : That's it! I'm Tired of helpung you out. It;s time we settled things on the battlefield!

po wyborze tej opcji dialogowej npc"Sergant Bly" zaczyna mówić do osoby, która jako pierwsza wybralła opcje dialogową.

"What? How dare you say that to me?!?"

"After all we've benn through? Well, I didn't like you anyway!!"
po wypowiedzeniu tej kwestii

Wtedy npc :
Sergant Bly
Raven
Oro Eyegouge
Sandfury Executioner
Murta Grimgut

zaczynają nas bić, a 
Weegli Blastfuse ucieka do ostatniego bossa z tekstem: " I'm out of there!"
i znika

**Co należy zrobić, aby odtworzyć ten błąd**:

uwolnić ich z klatki i przejsc pierwsza faze eventu i potem czekać na rozwój akcji.

**Linki WoWHead/OpenWoW**:

http://www.wowhead.com/npc=7607/weegli-blastfuse
http://www.wowhead.com/npc=7608/murta-grimgut
http://www.wowhead.com/npc=7605/raven
http://www.wowhead.com/npc=7606/oro-eyegouge
http://www.wowhead.com/npc=7604/sergeant-bly
http://www.wowhead.com/npc=7274/sandfury-executioner

https://www.youtube.com/watch?v=g-kIg-wowlw
**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by xnemeyethx** [comment]
Potwierdzam :<
