### ISSUE TITLE
[SPELL] Conflagrate.

### ISSUE THREAD

**Issue by khanvigo** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1153]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Spell ma niewłaściwy range oraz zły współczynnik crit.

**Obecne działanie**: Range spellu jest o kilka yard mniejszy niż powinien być (ss1, link 1 i 2). Jak widać na ss1 immolate z tej odległości założyłem a conflagrate out of range Oraz uzyskuje za mało uderzeń krytycznych (ss2,). Jak widac na ss2 posiadam un-buffed 25% crit, dodatkowo crit conflagrate powiększony jest o umiejętność Fire and Brimstone o 25%, (ss3) Devastation o 5% (ss4) oraz Backlash o 3%.(ss5)  a spell crituje tylko na poziomie 20-25%. 

**Oczekiwane działanie**: Range: Conflagrate tak jak np: Immolate, Inicerate i Chaos Bolt powinien mieć taki sam base range (Co ciekawe w grze jest 36y a na wowhead 40y.) powiększony o umiejętność Destructive Reach (20% zmiększenie zasięgu destro spelli). 
Crit: Spell powinien critowac częściej. Być może obecnie nie jest on modyfikowany o umiejętności podane jak powyżej.

Co należy zrobić, aby odtworzyć ten błąd**:

1. Range: Wystarczy na kukle wyjść na max range immolate, rzucić spell immolate a po nim conflagrate. 
2. Crit: Można to sprawdzić każdym dostępnym miernikiem dps jak np: Recount.
3. 

**Linki WoWHead/OpenWoW**:

1. ss1 http://i67.tinypic.com/2mnnmgo.jpg
2. link 1 http://www.wowhead.com/spell=17962/conflagrate
3. link 2 http://www.wowhead.com/spell=348/immolate
4, ss2 http://i67.tinypic.com/e03k14.jpg
5, ss3 http://i68.tinypic.com/2eqf9ky.jpg
6. ss4 http://i68.tinypic.com/166iqon.jpg
7. ss5 http://i66.tinypic.com/mjqxhx.jpg

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: - nie dotyczy.

**Comment by Crackaw** [comment]
Jutro fix powinien być już na serwerze :)
