### ISSUE TITLE
[ULDUAR] Freya - Ancient Water Spirit

### ISSUE THREAD

**Issue by Sensza** [RaphaelSunwell/Sunwell-BugTracker-SCv2#1155]
**Opis**:  W jednej z fal podczas walki przyzywane są trzy elementale, a wśród nich znajduje się Ancient Water Spirit używający umiejętności Tidal Wave. Spell powoduje odepchnięcie wszystkich graczy przed elementalem.

**Obecne działanie**: Czar "Tidal Wave" jest nieprzerywalny, a Ancient Water Spirit niestunowalny/niefearowalny/niesilence'owalny itd.

**Oczekiwane działanie**:  Czar "Tidal Wave" powinien być nieprzerywalny, lecz powinno być możliwe nałożenie CC na moba, w celu zatrzymania castowania. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Zainicjować walkę z Freyą w dowolnym trybie - normal/hm.
2.  Spróbować przerwać 2 sekundowy cast Tidal Wave.
3. 

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/spell=62935/tidal-wave#used-by-npc
2.  http://www.wowhead.com/npc=33202/ancient-water-spirit#comments
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Heartbraker** [comment]
Chyba specjalnie to zrobili tak, żeby w ogóle nie dało się tego przerywać (nie chce mi się teraz tych tematów na forum szukać, ale pewnie Graal o tym pisał).
Ale sam Tidal Wave działa beznadziejnie, często odrzuca ludzi stojących nawet za plecami Ancienta + ludzi których uderzy odpycha losowo w różne strony, czasem dobrze w kierunku w który wycastował spell, a czasem w drugą stronę - za plecy Ancienta.
Wygląda trochę tak jakby brał pod uwagę ustawienie graczy w momencie kiedy zaczyna cast, a nie kiedy go kończy (pierwsze lepsze przypuszczenie co może być nie tak - nie wiem czy o to chodzi, nie testowałem)
