### ISSUE TITLE
[Quests] Chapter I, II, III, IV.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#116]
**Opis**: Quest polega na zebraniu poszczególnych stron, aby utworzyć rozdział. 

**Obecne działanie**: W chwili, gdy gracz zbierze odpowiednie strony, aby utworzyć rozdział, kolejno: Rozdział I, II, III oraz IV, dostaje Quest o nazwie: "The Green Hills of Stranglethorn". **Po wykonaniu questa, gracz ma możliwość wykonania kolejny raz quest ze stronami.** Z questa wynika, że gracz powinien dostać 1100xp za jego wykonanie, natomiast na tę chwilę wygląda to tak, że gracz nie otrzymuje nic.
https://youtu.be/aTRTMOLvVsE

**Oczekiwane działanie**: Questy ze stronami powinny być możliwe do wykonania jedynie raz. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest na strony (I, II, III lub IV) od NPC. 
2. Odnaleźć strony, przynajmniej po 2x każdą.
3. Oddać quest.

**Linki WoWHead/OpenWoW**:

1. Quest na strony: 
**[Chapter I]: http://wotlk.openwow.com/quest=339**

[Page 1] http://wotlk.openwow.com/item=2725
[Page 4] http://wotlk.openwow.com/item=2728
[Page 6] http://wotlk.openwow.com/item=2730
[Page 8] http://wotlk.openwow.com/item=2732

**[Chapter II]: http://wotlk.openwow.com/quest=340**

[Page 10] http://wotlk.openwow.com/item=2734
[Page  11] http://wotlk.openwow.com/item=2735
[Page 14] http://wotlk.openwow.com/item=2738
[Page 16] http://wotlk.openwow.com/item=2740

**[Chapter III]: http://wotlk.openwow.com/quest=341**

[Page 18] http://wotlk.openwow.com/item=2742
[Page 20] http://wotlk.openwow.com/item=2744
[Page 21] http://wotlk.openwow.com/item=2745
[Page 24] http://wotlk.openwow.com/item=2748

**[Chapter IV]: http://wotlk.openwow.com/quest=342**

[Page 25] http://wotlk.openwow.com/item=2749
[Page 26] http://wotlk.openwow.com/item=2750
[Page 27] http://wotlk.openwow.com/item=2751

2. Quest na rozdziały (I, II, III, IV): http://wotlk.openwow.com/quest=338

**[Chapter I]: http://wotlk.openwow.com/item=2756
[Chapter II]: http://wotlk.openwow.com/item=2757
[Chapter III] http://wotlk.openwow.com/item=2758
[Chapter IV]: http://wotlk.openwow.com/item=2759**

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
x

**Comment by RaphaelSunwell** [comment]
Q działają dobrze możne. Exp dostaje się za 1 zrobienie. Sprawdzane - działa.

**Comment by Mithras2801** [comment]
Questy można wykonywać kilkakrotnie. Powinno być tylko 1 raz możliwe do zrobienia. W info nie jest napisane, że quest jest repetable.

Więc wykonujemy go raz.

**Comment by KamaN442** [comment]
pierwsze wykonanie daje expa drugie natomiast nic juz nie daje .
