### ISSUE TITLE
[OBJECT][VISUAL] Ogre Head On A Stick = Party

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#119]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Brak animacji wbitej głowy na włócznię.
**Obecne działanie**: 
Brak animacji wbitej głowy na włócznię. [http://i.imgur.com/sYGut0p.jpg](http://i.imgur.com/sYGut0p.jpg)
**Oczekiwane działanie**: 
Po kliknięciu w odpowiednim miejscu powinna się ukazać głowa na włóczni.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest http://www.wowhead.com/quest=3825/ogre-head-on-a-stick-party#comments
2. Udać się w miejsce podane koordynatami
3. Kliknąć na obiekt.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=3825/ogre-head-on-a-stick-party#screenshots
2. http://db.vanillagaming.org/?quest=3825#wh-screenshots
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Map: 0 (Eastern Kingdoms) Zone: 46 (Burning steppes) Area: 249 (Dreadmaul Rock) Phase: 1
X: -7943.945312 
Y: -2642.912842
Z: 218.210526

**Comment by Mithras2801** [comment]
Zgadzam się.

**Comment by Shon-su** [comment]
poprawione
