### ISSUE TITLE
[NPC] Bragor Bloodfist

### ISSUE THREAD

**Issue by grigorlives** [RaphaelSunwell/Sunwell-BugTracker-SCv2#12]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak npc Bragor Bloodfist.

**Obecne działanie**: Nie ma npc tam gdzie powinien być ani w pobliżu.

**Oczekiwane działanie**: Npc powinien stać w sali Sylvanas, koordy 56.2 92.1 Undercity.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Iść do Undercity.
2. Dojść do sali Sylvanas, 56.2 92.1
3. Pospamić macrem /tar bragor.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=36273
2. http://www.wowhead.com/npc=36273/bragor-bloodfist
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
56.2 92.1 Undercity
![wowscrnshot_111916_104751](https://cloud.githubusercontent.com/assets/16683952/20456011/8e77d37a-ae6a-11e6-9f3a-1d70d3d77f18.jpg)

**Comment by Shon-su** [comment]
Added in patch 3.3.0.10522 
http://www.wowhead.com/npc=36273/bragor-bloodfist

**Comment by grigorlives** [comment]
O kurde faktycznie, już się przyzwyczaiłem do niego. Varimathrasa na odpowiedni patch też nie ma, co jest problematyczne ze względu na questy na insty które dawał jeden a potem drugi.
Linki: http://www.wowhead.com/npc=2425/varimathras http://wotlk.openwow.com/npc=31565 ewentualnie zrobię 2 report.

**Comment by adraeth** [comment]
Blokuje:
http://www.wowhead.com/quest=550/deprecated-battle-of-hillsbrad
