### ISSUE TITLE
[NPC] Mosh'Ogg Witch Doctor.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#120]
**Obecne działanie**: NPC pomimo cc (w tym przypadku poly) rzuca swój spell na gracza.
https://youtu.be/WByHBdnWnPk

**Oczekiwane działanie**: NPC nie powinien używać spelli, w chwili gdy ma cc.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Być magiem.
2. Odnaleźć npc i użyć na nim polymorph.

**Linki WoWHead/OpenWoW**:

1. [Ogr] http://wotlk.openwow.com/npc=1144
2. [Spell ogra] http://wotlk.openwow.com/spell=11980
3. [Spell maga] http://wotlk.openwow.com/spell=12825#see-also-ability

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
x

**Comment by myentos** [comment]
Ustaw film jako niepubliczny, bo prywatne tylko Ty możesz oglądać.

**Comment by Kougraa** [comment]
Film byl w trakcie przetwarzania. Teraz powinno być ok.

**Comment by kovaq** [comment]
https://youtu.be/a6iWX4ChfRE
Potwierdzam.

**Comment by DinozaurWKamizelce** [comment]
Nie mam tera czasu szukać ID ale miałem ten (a nawet wiekszy problem) z mobem przyzywanym z ostatniego q chaina z rogu u Wyrmrestów (Managaur) i strażą przyboczną Calida Scorpidstinga w Tanaris. Moby nie dość że atakowały w owcy to używały specjalnych zdolności.

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane dzisiaj (tj. 27.01) około 6 rano.
