### ISSUE TITLE
[NPC] 938 - Kurzen Commando (brak umiejętności)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#121]
**Opis**: W chwili obecnej dane NPC nie używają umiejętności ukrycia.

**Obecne działanie**: Wszystkie te npc nie są ukryte.

**Oczekiwane działanie**: NPC wymienione powinny być ukryte jak rogue. Jedynie uderzenie wyrzuca ich z ukrycia.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Iść na miejsce z tymi NPC
2. Sprawdzić czy są w ukryciu.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=938/kurzen-commando#abilities
2. http://www.wowhead.com/spell=22766/sneak

**Comment by Shon-su** [comment]
fix podesłany
