### ISSUE TITLE
[INSTANCJA]Utgarde Keep

### ISSUE THREAD

**Issue by Nuy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#122]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Z tą instancją są tylko 2 małe problemy. Pierwszy problem to moby w "paczkach" nie są ze sobą połączone w chain-pull przez co można wyciągać je pojedynczo/po dwa, chociaż stoją blisko siebie. Drugi problem to podwójny RP event na ostatnim bossie podczas jego przechodzenia w drugą fazę walki co dosyć śmiesznie wygląda, ale jest to tylko i wyłącznie wizualny problem.

**Obecne działanie**: Moby nie są ze sobą połączone w chain-pull i jest podwójny RP event na ostatnim bossie.

**Oczekiwane działanie**: Moby powinny być ze sobą połączone w chain-pull, czyli jeśli w "paczce" 4-ech mobów pullniemy jednego, to wszystkie 4 powinny się zaggrować. Powinien być jeden, normalny RP event po przejściu ostatniego bossa w drugą fazę walki.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pullnąć jednego moba z "paczki" 4-ech mobów w instancji UK i zrobić ostatniego bossa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/utgarde-keep
2. http://www.wowhead.com/npc=23954
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: -

**Comment by Shon-su** [comment]
poprawione
