### ISSUE TITLE
[INSTANCJA][BOSS][NPC]Jedoga Shadowseeker

### ISSUE THREAD

**Issue by Nuy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#123]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Instancja działa dobrze z wyjątkiem jednego bossa - Jedoga Shadowseeker. Kiedy wlatuje w powietrze, to już nie zlatuje, bo nie działa event poświęcenia jednego z Twilight Volunteer przez co nie da się zrobić tego bossa.

**Obecne działanie**: Nie da się zrobić tego bossa, bo nie działa event poświęcenia jednego z Twilight Volunteer. Jeden z mobków tego typu powinien podczas tego eventu wstać i powoli podchodzić pod bossa będącego w powietrzu i jeśli grupa zabije tego mobka lub uda mu się dojść i zostanie poświęcony, to boss powinien zlecieć na ziemię i kontynuować walkę. 

**Oczekiwane działanie**: Działający event poświęcenia jednego z mobków typu Twilight Volunteer. Mobki te powinny być odporne na KAŻDY rodzaj CC - to tak na zaś.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zbić HP tego bossa do około 50%.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=29310/jedoga-shadowseeker
2. http://www.wowhead.com/npc=30385/twilight-volunteer

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: -

**Comment by Nuy** [comment]
Dzisiaj zadziałało, ale jak widać coś się czasami nie "triggeruje" przez co czasami żaden z Twilight Volunteer się nie poświęca i walka się zawiesza.

**Comment by myentos** [comment]
Potwierdzam: [https://youtu.be/2NrwCpV8aqI](https://youtu.be/2NrwCpV8aqI)

**Comment by MonichSC** [comment]
Powinno być już wgrane, do przetestowania
