### ISSUE TITLE
[INSTANCJA]Azjol-Nerub

### ISSUE THREAD

**Issue by Nuy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#124]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Event "watcherów" przed bossem Krik'thir the Gatewatcher jest akutalnie całkowicie spieprzony. Kiedy pullniemy jednego z watcherów za chwilę nadchodzi drugi z obstawą a kolejni watcherzy po pullnięciu pierwszego powinni przychodzić w przynajmniej kilkusekundowych odstępach a nie natychmiast tak jak jest teraz. Event bossa Hadronox jest zbugowany w ten sposób, że kiedy Hadronox dojdzie już na górę tunelu, to mimo że nie ma już obok niego żadnych nerubianów z nim walczących, to dalej odnawia mu się HP kiedy go zaatakujemy. Oprócz tego nie da się z nim walczyć w tunelu lub na dole, bo kiedy tego spróbujemy Hadronox ciągle się resetuje i zaczyna wchodzić z powrotem na górę. Reszta instancji działa dobrze.

**Obecne działanie**: Kolejni watcherzy po pullnięciu pierwszego przychodzą za szybko (praktycznie natychmiast) przez co strasznie trudno jest bić się z dwoma/trzema na raz. Czasami Hadronox resetuje sobie ciągle HP będąc na górze tunelu a oprócz tego nie da się z nim walczyć w tunelu lub na jego dole, bo w tych miejscach ciągle się resetuje i zaczyna wchodzić na górę.

**Oczekiwane działanie**: Powinny być przynajmniej kilkusekundowe odstępy przed automatycznym przychodzeniem kolejnych watcherów po pullnięciu pierwszego (nie wiem dokładnie jak długie odstępy). Hadronox nie powinien resetować sobie HP kiedy już zabije wszystkich nerubian z nim walczących lub kiedy mu z tym pomożemy. Powinno dać się walczyć z Hadronox w tunelu lub na samym jego dole i kiedy w tych miejscach go zaggrujemy event jego wchodzenia na górę tunelu powinien zostać zatrzymany.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pullnąć jednego z watcherów przed pierwszym bossem.
2. Spróbować zabić bossa Hadronox.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=28684/krikthir-the-gatewatcher
2. http://www.wowhead.com/npc=28731/watcher-silthik
3. http://www.wowhead.com/npc=28729/watcher-narjil
4. http://www.wowhead.com/npc=28730/watcher-gashra
5. http://www.wowhead.com/npc=28921/hadronox

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: -

**Comment by Triceps69** [comment]
Potwierdzam, instancja dalej jest zbugowana.

**Comment by ellynd** [comment]
również potwierdzam, robiłem przed chwilą na normie i moby przy 1wszym bossie pullają się za szybko
