### ISSUE TITLE
[NPC] 942 - Kurzen Witch Doctor (nie używa umiejętności)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#125]
**Opis**: Podany NPC przyzywa jedynie searing totem i bije melee

**Obecne działanie**: Wyżej opisane

**Oczekiwane działanie**: NPC ten powinien castować Lighting Bolt'a i bić melee (jedynie jak się podejdzie) ale również castować. Do tego totemu nie jestem pewien bo na wowhead nie jest napisane.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Iść do miejsca z NPC
2. Sprawdzić czy castuje i co daje i castuje

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=942/kurzen-witch-doctor#abilities
2. http://www.wowhead.com/spell=57780/lightning-bolt

**Comment by xsitdev** [comment]
They dont cast any of those, the only spell that they cast is a searing totem 3
-----
Actually, they don't just cast searing totem 3, they also cast Purge, which can dispel magic offensively, like Power Word: Fortitude and Frost Armor.

Nie castuje lighitning bolt'a. Blad WoWhead.
