### ISSUE TITLE
[OBJECT]Tattered  Chest

### ISSUE THREAD

**Issue by Mojsik** [RaphaelSunwell/Sunwell-BugTracker-SCv2#126]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Tattered Chest znajdujący się w budynku na Dabyrie Farmstead jest tylko wizualną atrapą

**Obecne działanie**: Chest jest tylko teksturą, nie można na niego kliknąć.

**Oczekiwane działanie**: Chest powinien móc być otwierany i lootowany.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Zmienić teksturę na aktywny model Tattered Chest

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/object=2844/tattered-chest
2. 
3. 

**Lokalizacja z koordynatów GPS (56.4, 36.5, Arathi Highlands)**:

**Comment by xsitdev** [comment]
Chest, o ktorym tutaj napisales to faktycznie Tattered Chest, jednak jest on wylacznie lootowany przez Horde. Alliance nie moze lootowac tego chestu.

**Comment by Mojsik** [comment]
Wiedziałem, że coś nie tak! Grając po stronie Hordy na drugim serwerze
starego Sunwella otwierałem, ale na starym po stronie ally nie mogłem!
Dziękuję za szybką odpowiedź.

2016-11-26 1:30 GMT+01:00 xsitdev <notifications@github.com>:
