### ISSUE TITLE
FISHING

### ISSUE THREAD

**Issue by Myciej** [RaphaelSunwell/Sunwell-BugTracker-SCv2#13]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: FISHING Z MOSTU

**Obecne działanie**: Nie można łowić z mostu lub spławik ląduje pod most

**Oczekiwane działanie**:  można łowić z mostu i zarzucać dalej spławik

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść na jakikolwiek most przy którym pojawia się fishing shool 
2. Spróbować złowić coś z  fishing shool'a
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shaverash** [comment]
Nie musi być koniecznie most, wystarczy niewielkie wzniesienie nad taflą wody i już to uniemożliwia łowienie.

**Comment by redemptoris** [comment]
Potwierdzam, nie moge lowic z podestow w Booty Bay i Southshore (a na pewno powinno dac sie tam lowic, pamietam to z globca, zreszta tam sa schoole co wskazuje na punkt polowu). Problem jest chyba z wysokoscia nad poziomem morza, jesli znajduje sie wyzej niz jakies (na oko) 2 metry to wtedy nie da sie zarzucic splawika

**Comment by Mithras2801** [comment]
Działa.

**Comment by r00emek** [comment]
Wczoraj i dziś nie działało i nie działa nadal. Testowane z pomostu w Auberdine Darkshore.
