### ISSUE TITLE
[Talent][Mage]Fingers of Frost

### ISSUE THREAD

**Issue by khaztiv** [RaphaelSunwell/Sunwell-BugTracker-SCv2#133]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Talent Fingers of Frost nie proca od efektów chill

**Obecne działanie**: Obecnie talent proca od talentu Frostbite

**Oczekiwane działanie**: Fingers of Frost powinien procac od efektów chill maga tj. spolnienia od np od frostbolta, ice armor itp.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ustawić magowi talenty frost z dwoma talentami nas interesujacymi tj. frostbite i fingers of frost
2. bic mobki 
3. obserwowac proce

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=44545
2. http://wotlk.openwow.com/spell=12497
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by BialyADI** [comment]
Fingers of Frost nie powinien procować od Frostbite, więc mamy tu 2 bugi.

**Comment by Nuy** [comment]
Nie zauważyłem tego, bo nie bierze się tego talentu pod expienie/farmienie.

**Comment by Danieloses** [comment]
efekty chill to ice armor, frostbolt, frostfire bolt, cone of cold

**Comment by Nuy** [comment]
Chill = spowolnienie lodowe a Frostbite nie spowalnia.

**Comment by khaztiv** [comment]
macie racje nie powinien procac od frostbite jedynie od efektow spowolnien

**Comment by xsitdev** [comment]
Prosze o film potwierdzajacy Wasza wersje oraz wiecej informacji chetnie zrodla WoWwikki etc.

**Comment by Nuy** [comment]
Dobra, zgłoszenie jest jednak błędne. Tutaj nie chodzi o to, że Frostbite nabija FoF a o to, że te dwa efekty nigdy nie mogą wejść oddzielnie i ZAWSZE wchodzą jednocześnie.

http://wowwiki.wikia.com/wiki/Frostbite_(mage_talent)

"In PvP, the Frostbite effect is subject to diminishing returns. **It will also always proc along with Fingers of Frost if both are fully talented**."
