### ISSUE TITLE
[SPELL] Judgement of Justice

### ISSUE THREAD

**Issue by Bravd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#136]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak Redukcji Movement Speed z Judgement of Justice (Paladyn)

**Obecne działanie**: Po Użyciu Judgement of Justice na Gnomim Magu, który dosiadał Mechanostridera (60%) nie ograniczyło mu prędkości poruszania się.
**Oczekiwane działanie**: Powinno spowolnić go do maksymalnej prędkości poruszania się na piechotę (domyślnie 100%, można tą wartość talentami/przedmiotami podnieść do 115%)

**Rzuciałem ten skill jak byłem w wodzie, gnom właśnie wychodził z niej ( nie wiem czy to ma znaczenie). Miałem na sobie Seal of Command. Prędkość była zbyt duża gdyż inny gracz na mouncie bez spowolnienia nie mógł go dogonić (mount także 60%) Będę testował to jeszcze na innych przypadkach, a obserwacje zamieszczę tutaj (jeśli można edytować) albo usunę tą ISSUE i założę nową pod tą samą nazwą,**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=53407
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
38.5, 31.7, Stranglethorn Vale

**Comment by xsitdev** [comment]
Jak sprawdzisz dokladnie napisz ponownie issue, akutalnie nie moge tego odwzorowac.

**Comment by felmad** [comment]
Dziwne, bo ten Judg u mnie działa w przypadku każdej osoby na mouncie lub mającej jakiekolwiek efekty biegania szybciej niż 100% biegnąc.
