### ISSUE TITLE
Undercity mailbox x2

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#138]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Obecne działanie**: W Uc znajdują sie dwa mailboxy jeden na drugim. 

**Oczekiwane działanie**: Jeden z mailboxów powinien zostać skasowany.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do Undercity.

**Screen**:

1. http://i.imgur.com/5I8cCHE.jpg

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
1555.9123589, 234.463303, -43.102592, 0

**Comment by Shon-su** [comment]
poprawka czeka na wgranie
