### ISSUE TITLE
[Quest][The Barrens] Samophlange

### ISSUE THREAD

**Issue by garlyn** [RaphaelSunwell/Sunwell-BugTracker-SCv2#14]
**Opis:** W chwili obecnej nie można wykonać questa Samophlange.

**Obecne działanie:** Można podejść do npc (http://www.wowhead.com/object=4141/control-console) kończącego q, ale nie ma opcji kończącej quest ani rozpoczynającej następny quest z chaina. Nie ma nawet tego znaku zapytania, który się pojawia nad npc'ami do oddania questa.

**Oczekiwane działanie:** Działający quest

Podejść do npc w koordynatach The Barrens 52,11.
Zakończyć quest gadając z npc.
Rozpocząć nowy quest z chaina.

**Co należy zrobić, aby odtworzyć ten błąd:**
Podejść do npc w koordynatach The Barrens 52,11
Próbować zakończyć q

**Linki WoWHead/OpenWoW:**

http://www.wowhead.com/object=4141/control-console
http://www.wowhead.com/quest=29021/samophlange

**Lokalizacja z koordynatów GPS (X, Y, Z, Map):** 52,11

**Comment by ThePuppetMaster** [comment]
Powinno już działać.
