### ISSUE TITLE
[SPELL] Holy Wrath

### ISSUE THREAD

**Issue by Gayfish1** [RaphaelSunwell/Sunwell-BugTracker-SCv2#141]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Holy Wrath zadaje obrażenia tylko demonom i nieumarłym. Na załączonym screenshocie widać cyferki z recounte'a. Spell używany obok dwóch mobków (jeden demon drugi nie).

**Obecne działanie**: Holy Wrath bije tylko nieumarłych i demony

**Oczekiwane działanie**: Holy Wrath powinien bić wszystkich, ale dodatkowo stunować nieumarłych i demony

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Używać Holy Wrath przy innych stworzeniach niż nieumarli czy demony
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=48817
2. http://imgur.com/a/jAbsM
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by xsitdev** [comment]
Sends bolts of holy power in all directions, causing X Holy damage AND stunning all Undead and Demon targets within 10 yds for 3 sec.

Nie powinien zadawac obrazen w sposob opisany przez Ciebie.
