### ISSUE TITLE
[SKILL Priest] Dispel Magic Rank 2 priest

### ISSUE THREAD

**Issue by Votiag** [RaphaelSunwell/Sunwell-BugTracker-SCv2#142]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 

**Obecne działanie**: Skill nie dziala zgodnie z opisem na tooltipie tj. nie sciaga 2 magic debufow z friendly targetu, hostile target nie testowalem bo nie bylo jak ale tez pewnie nie dziala

**Oczekiwane działanie**:rank 2 powinien sciaga 2 magic debuffy z friendly targetu i 2 buffy z hostile targetu

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Radeghost** [comment]
Ten skill dziala, wlasnie sprawdzilismy
