### ISSUE TITLE
[Skill][Priest] Dispel Magic rank2

### ISSUE THREAD

**Issue by Votiag** [RaphaelSunwell/Sunwell-BugTracker-SCv2#143]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: nie dziala jak opisuje tooltip

**Obecne działanie**: dziala jak rank 1

**Oczekiwane działanie**: spell powinien dispelowac 2 pozytywne buffy z przeciwnika, a z friendly celu 2 negatywne

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  daj sobie jakie kolwiek 2 magic buffy czy debuffy by zobaczyc jak dziala dispellowanie rank 2 Dispell magic
2. 
3. 

**Linki WoWHead/OpenWoW**:

1.  http://wotlk.openwow.com/spell=988
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Votiag** [comment]
3 raz nie bede zglaszal tego samego bugu bo tak ciezko zrozumiec wam opis cholernego tooltipa

**Comment by Radeghost** [comment]
buffy/debuffy maja byc MAGIC, a ty pewnie probujesz jakies disease na kiju sciagac

**Comment by Votiag** [comment]
zaloz priest sprawdz i wtedy sie wypowiadaj

**Comment by Radeghost** [comment]
sprawdzilem, dziekuje
