### ISSUE TITLE
[QUEST] That Which Creates Can Also Destroy [12459]

### ISSUE THREAD

**Issue by Triceps69** [RaphaelSunwell/Sunwell-BugTracker-SCv2#144]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Moby Weakened Reanimated Frost Wyrm [27821] są zbyt wysoko, przez co nie można ich zaagrować, a po użyciu quest itemu dalej są w górze. Klasy z zasięgiem 30y nie są w stanie zaagrować tych mobów.

**Oczekiwane działanie**: Normalnie jest tak, że one latają po swoich trasach i przelatują nad wzniesieniami i wtedy można je zaagrować, u nas jest to niemożliwe

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12459/that-which-creates-can-also-destroy
2. 
![wowscrnshot_112716_042030](https://cloud.githubusercontent.com/assets/23584783/20645265/dfc15244-b458-11e6-8f41-8e823f60be68.jpg)

3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by kovaq** [comment]
Aktualnie dziala.
https://youtu.be/kRGv_Fhzo4A
