### ISSUE TITLE
[INSTANCE][NPC] Scarlet Monastery: Graveyard - nadprogramowy boss

### ISSUE THREAD

**Issue by Heartbraker** [RaphaelSunwell/Sunwell-BugTracker-SCv2#145]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:W instancji Scarlet Monastery Graveyard można znaleźć bossa eventowego - Scorn, w wersji z patcha1.11  

**Obecne działanie**: Po zabiciu last bossa http://www.wowhead.com/npc=4543/bloodmage-thalnos w drodze powrotnej do wejścia instancji pojawia się boss który był dostępny jedynie podczas eventu "Scourge Invasion"

**Oczekiwane działanie**: Scorn nie powinien się w ogóle pojawiać po zabiciu Bloodmage Thalnos

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabić Bloodmage Thalnos - id 4543
2. Iść w kierunku wejścia do instancji aż trafi się na Scorna - id 14693
3. 

**Linki WoWHead/OpenWoW**:

1. Scorn - http://wotlk.openwow.com/npc=14693 / http://www.wowhead.com/npc=14693/scorn#comments
2. Bloodmage Thalnos - http://www.wowhead.com/npc=4543/bloodmage-thalnos
3. Scourge Invasion - http://wowwiki.wikia.com/wiki/Scourge_Invasion

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
-

**Comment by Danieloses** [comment]
Potwierdzam, również natknęliśmy się na Scorn'a.

**Comment by darkclif** [comment]
https://github.com/Kittnz/Sunwell/blob/831ac9da07abf607cfb585a4435a0734759da977/sql/world%20fixes/instances/EasternKingdom/scarlet_monastery.sql#L537

Prawdopodobnie trzeba wyjąć z bazy tą linijkę.

**Comment by ThePuppetMaster** [comment]
Done
