### ISSUE TITLE
[QUEST][NPC] Tomb of the Lightbringer

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#147]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
NPC [Anchorite Truuen](http://www.wowhead.com/npc=17238/anchorite-truuen) biegnie zbyt szybko i nie zważa na to czy ktoś atakuje. Dodatkowo na końcu gdy pojawi się duch Uthera, dialogi pojawiają się zbyt szybko.
**Obecne działanie**: 
NPC [Anchorite Truuen](http://www.wowhead.com/npc=17238/anchorite-truuen) biegnie zbyt szybko i nie zważa na to czy ktoś atakuje. Dodatkowo na końcu gdy pojawi się duch Uthera, dialogi pojawiają się zbyt szybko.
**Oczekiwane działanie**: 
NPC powinien iść o wiele mniejszym tempem oraz reagować na to że go ktoś atakuje. Uther powinien mówić wolniej.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest [Tomb of The Lightbringer](http://www.wowhead.com/quest=9446/tomb-of-the-lightbringer)
2. Eskortować NPC
3. 

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/quest=9446/tomb-of-the-lightbringer](http://www.wowhead.com/quest=9446/tomb-of-the-lightbringer)
2. [https://www.youtube.com/watch?v=6A6k8EFoIzc](https://www.youtube.com/watch?v=6A6k8EFoIzc)
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
NPC ma około 1.1 - 1.15 speed

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
