### ISSUE TITLE
Quest Blueleaf Tubers

### ISSUE THREAD

**Issue by Jarek250** [RaphaelSunwell/Sunwell-BugTracker-SCv2#148]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Nie działa quest Blueleaf Tubers

**Obecne działanie**: nie mozna uzyc  Crate With Holes w instancji by zespawnic npc ktory podza za graczem i szuka Blueleaf Tuber

**Oczekiwane działanie**: powinno dac sie uzyc  Crate With Holes 
**Co należy zrobić, aby odtworzyć ten błąd**: wziasc quest Blueleaf Tubers i udac sie do instancji  Razorfen Kraul

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:http://wotlk.openwow.com/quest=1221

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://www.youtube.com/watch?v=mD8mg1iQ9T0
tu pokazane jak to powinno dzialac

**Comment by felmad** [comment]
Potwierdzam - zadanie nie działa w ogóle.

**Comment by c0me10** [comment]
Yeah it is bug. There is something wrong about summon pet. It always says "Requires Nearby Tubers" even u are in right place.

**Comment by kovaq** [comment]
Potwierdzam. Przebieglem cale RFK i nic nie dalo sie zrobic. Prawdopodobnie Crate with Holes ( http://wotlk.openwow.com/item=5880) nie akceptuje RFK jako lokacji i nie pozwala przyzwac tego "niuchacza".
Filmu nie wrzucam, bo to by bylo 10 minut biegania po instancji w poszukiwaniu najciemniejszych miejsc.

**Comment by Shon-su** [comment]
#547
