### ISSUE TITLE
[QUEST] Triage

### ISSUE THREAD

**Issue by Ruthelis** [RaphaelSunwell/Sunwell-BugTracker-SCv2#15]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: NPC respią się z małą ilością życia, które spada tak szybko, że nawet po natychmiastowym spawnie i cascie bandaża nie ma możliwości wykonać questa, gdyż giną za szybko

**Obecne działanie**: Za szybko spada życia mobkom (lub respią się ze zbyt mała ilością życia)

**Oczekiwane działanie**: Przy aktualnej prędkości spadku życia npc powinny sie respić z min. 80% hp)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by FrostyGM** [comment]
Zgłoszenie jest niekompletne, brak linków do WoWHead/OpenWoW, screenów ani opisu co należy zrobić by odtworzyć błąd.
