### ISSUE TITLE
[QUEST][MINOR] The Tome of Valor

### ISSUE THREAD

**Issue by Camiinus** [RaphaelSunwell/Sunwell-BugTracker-SCv2#151]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

NPC wymagany do questa nie zachowuje się tak jak powinien, przez co quest jest możliwy do wykonania, lecz uciążliwy (szczególnie jeśli robi go naraz kilka osób).
Bug nie jest poważny, ponieważ nadal da się wykonać questa, toteż nie jest konieczna jego szybka naprawa.

**Obecne działanie**:

A. NPC Daphne Stilwell znika jeżeli ktoś wcześniej wykona quest, przez co trzeba czekać na jej respawn.
B. Ta sytuacja wydaje się zdarzać losowo: NPC Daphne Stilwell czasami znika zaraz po wzięciu questa przez gracza, co uniemożliwia jego wykonanie. W tej sytuacji również gracz musi czekać na jej ponowny respawn.

**Oczekiwane działanie**:

Po wykonaniu questa przez jednego gracza NPC nie powinien znikać (ewentualnie zniknąć i szybko się zespawnić). Co ważniejsze, NPC nie powinien znikać zaraz po wzięciu questa przez gracza.

**Co należy zrobić, aby odtworzyć ten błąd**:

A. Spróbować wziąć questa zaraz po tym jak zrobił go inny gracz.
B. Próbować brać questa kilka razy (sytuacja ze znikającym NPC zaraz po wzięciu questa).

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=1651 - quest
2. http://www.wowhead.com/npc=6182 - NPC Daphne Stilwell

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Westfall; 42.0, 89.0

**Comment by kovaq** [comment]
Potwierdzam. Za pierwszym razem zanim zaczalem nagrywac kobitka wpadla mi pod tekstury i znikla. Po zaczeciu nagrywania grzecznie zrobila ze mna questa, a po wyrzuceniu i probie zapetlenia questa przy wzieciu q miala juz bro nw rekach, nastepnie najzwyczajnie w swiecie znikla, nawet komenda jej nie znajduje.
https://youtu.be/-NIpQ9gwaHU

**Comment by Shon-su** [comment]
27.02 działa dobrze
