### ISSUE TITLE
Uldaman, Staff of Prehistoria

### ISSUE THREAD

**Issue by rigormortified** [RaphaelSunwell/Sunwell-BugTracker-SCv2#153]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Boss do którego otwarcia potrzebne są 2 itemy : The Shaft of Tsol i Gni'kiv Medallion aby utworzyć Staff of Prehistoria, nie trzeba mieć tych dwóch itemów.

**Obecne działanie**: Można go przyciągnąć dowonlym petem, testowane na warlocku

**Oczekiwane działanie**: możliwe aggro dopiero po otwarciu drzwi itemem Staff of Prehistoria

**Co należy zrobić, aby odtworzyć ten błąd**:

1. podejść do drzwi żeby zobaczyć nameplate z bossem
2. wysłać peta do ataku
3. po czym można go normalnie zabić

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=7733/staff-of-prehistoria
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Uldaman, Eastern Kingdoms

**Comment by kovaq** [comment]
https://youtu.be/s2H6tZpcKUg
Dziala.
