### ISSUE TITLE
[QUEST[Dungeon] - Data Rescue (Gnomeregan)

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#154]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest polega na uzyskaniu kolejnych "Punch Card" aż do uzyskania Prismatic Punch Card, która jest potrzebna do ukończenia zadania.

**Obecne działanie**:  Obecnie konsole Matrix Punchograph 3005 (A, B, C) działają natomiast konsola Matrix Punchograph 3005-D mimo poprzez posiadanie "Red Punch Card", w której opisie jest zawarta informacja o możliwości uzyskania dostępu do konsoli 3005-D dzięki niej, nie działa. Dokładniej wyświetla nam się prawidłowy dialog "Red Punch Detected. Access Granted." lecz nie ma opcji dialogowej potrzebnej do uzyskania quest itemu kończącego quest.

Screenshot: http://imgur.com/xBhxdJi

**Oczekiwane działanie**: Powinniśmy uzyskać opcję dialogową, po której użyciu dostajemy "Prismatic Punch Card" kończący quest. Na screenshot'cie widać obecność oraz opis Red Punch Card oraz dialog z konsolą Matrix Punchograph 3005-D.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Uzyskać Red Punch Card
2. Użyć Matrix Punchograph 3005-D
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=9281
2. http://wotlk.openwow.com/object=142696
3. http://wotlk.openwow.com/item=9316

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Gnomeregan - Workshop, Engineering Labs

**Comment by Shon-su** [comment]
Quest działa prawidłowo. Aby wyświetliła się ostatnia opcja konieczne jest posiadanie skilla Engi na poziomie conajmniej 160 oraz itemu http://www.wowhead.com/item=9327/security-delta-data-access-card
