### ISSUE TITLE
[QUEST] - Vindicator Aldar 

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#155]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Vindicator Aldar is an Alliance-only quest in the draenei starting region Ammen Vale. This quest is not required for A [4] Inoculation, but gives a few extra XP so it is recommended that you get this quest before Inoculation. It appears that you must complete the A [3] Healing the Lake quest chain from Botanist Taerix before she will offer this quest.

**Obecne działanie**: Brak Questu z Quest chaina (nie zleca)

**Oczekiwane działanie**: Po wykonaniu questu - Healing the Lake Botanist Taerix powinna zlecić kolejny quest - Vindicator Aldar (nie zleca)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzić czemu nie zleca się ten quest w quest chainie.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wow.gamepedia.com/Quest:Vindicator_Aldar
2. http://www.wowhead.com/quest=10304/vindicator-aldar
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
AzureMyst Isle 79,1/46,5

**Comment by ThePuppetMaster** [comment]
Powinno działać.
