### ISSUE TITLE
[QUEST] What We Know...

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#156]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:We've learned much of our enemies in recent days. The blood elves are led by a being known as Sironas and plot to destroy us. Ultimately, they seek to enslave O'ros and regain control of the Exodar.

Light be praised, we have stopped their supply line by destroying the sun gate. Unfortunately, they continue to use the contaminant of the Vector Coil to poison the land, using the mutagenic properties of the fallout to their advantage.

With this knowledge, Admetius has devised a plan. Seek him out. 

**Obecne działanie**: Nie jest zlecany (jako pierwszy quest z chaina:
A [20] What We Know...
A [20] What We Don't Know...
A [20] Vindicator's Rest
A [20] Clearing the Way

**Oczekiwane działanie**: Vindicator Aesom powinien zlecić ten quest.
**Co należy zrobić, aby odtworzyć ten błąd**: j.w.

1. Sprawdzić czemu NPC nie zleca questu, choć nie ma w nim ograniczenia rasy, klasy, profki
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9753/what-we-know
2. http://wow.gamepedia.com/Quest:What_We_Know...
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Bloodmyst Isle 55.5/55,5

**Comment by ThePuppetMaster** [comment]
Powinno działać.
