### ISSUE TITLE
[QUEST] The Bloodcurse Legacy

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#157]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Description
Dear friend,

My hand trembles as I ink this letter. I pray that it reaches you in time.

Last night, Edward Hanes, captain of the ship 'Lost Hope', appeared before me in my tent. The same Edward Hanes that died of scurvy 20 years ago.

This apparition told me a tale that made my heart tremble. A tale that I need you to hear and a mission that I need you to accomplish. Will you do it? Will you seek out Edward on Wyrmscar Island, northeast of your base?

Regards,

Admiral Odesyus

Completion
Have you heard of the bloodcurse, landlubber? No, of course you haven't. The bloodcurse is what sunk all these ships. The spoiled, desecrated part of the water here is known as Bloodcursed Reef - a part of the world you never want to visit. I've been here myself for 20 years.

Scurvy my foot! I died on these wild shores as food for the dragons... Ah, but that's another story for another time. Right now, we have to help the poor souls that are trapped in that reef.

**Obecne działanie**: O ile item w postaci listu "A Letter from the Admiral" (http://wow.gamepedia.com/A_Letter_from_the_Admiral) gracz faktycznie otrzymuje i jest z wykrzyknikiem, czyli zawiera quest do pobrania, to niestety klikanie na ten list powoduje jedynie komendę "You don't requirements for that quest". Chociazest nie ma ograniczeń rasowych, klasowych, profek.
Jest to pierwszy quest z chaina:
A [18] The Bloodcurse Legacy
A [18] The Bloodcursed Naga
A [18] The Hopeless Ones...
A [19] Ending the Bloodcurse

**Oczekiwane działanie**: Item o nazwie  "A Letter from the Admiral" powinien uruchamiać quest "The Bloodcurse Legacy". 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzić skrypt itemu o nazwie "A Letter from the Admiral" czemu nie zleca questa "The Bloodcurse Legacy". 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9672/the-bloodcurse-legacy
2. http://www.wowhead.com/item=24132/a-letter-from-the-admiral
3. http://wow.gamepedia.com/Quest:The_Bloodcurse_Legacy

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Torba gracza (wcześniej skrzynka listowa)

**Comment by ThePuppetMaster** [comment]
Powinno działać.
