### ISSUE TITLE
[QUEST - Class - Warrior] - Strength of One

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#158]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: escription
When the ship crashed, our menagerie was scattered on the northeast beaches of this isle. I have been handed a key that unlocks the cage holding one of the deadlier specimens, a death ravager. The creature is little armored but resistant to most magic. It must be killed by a simple blade.

Take this key and release the creature from both its prison and its pain. We cannot afford to have it escape and cause even more damage to the ecology than we already have. 

**Obecne działanie**: NPC Ruada <Warrior Trainer> nie ma w opcjach dialogu tego questu (możliwe, że jako Dwarf nie mogę pobrać tego questa w Azuremyst Isle, lecz na strinach opisowych nic nie jest napisane, że tylko dla Dranei jest ten quest)

**Oczekiwane działanie**: NPC Ruada powinna posiadać w opcjach dialogowych zlecenie tego questu.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Hm, dodać quest do dialogu NPC'a?
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9582/strength-of-one
2. http://wow.gamepedia.com/Quest:Strength_of_One
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Azuremyst Isle 50.0/50.5

**Comment by ThePuppetMaster** [comment]
Powinno działać
