### ISSUE TITLE
[CLASS SPELL][PALADIN]

### ISSUE THREAD

**Issue by dilldadisbak** [RaphaelSunwell/Sunwell-BugTracker-SCv2#159]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Nie można nauczyć się umiejętności summon charger na 40 lvlu u paladyna

**Oczekiwane działanie**: Powinno móc się go nauczyć co również przyznaje journeymen  riding

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Spróbować nauczyć się chargera na paladynie lvl 40
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by myentos** [comment]
Aby nauczyć się jazdy na 40 poziom, należy iść do trenera od jazdy a dopiero wtedy do trenera klasowego aby uzyskać mounta. Tak jest poprawnie.

**Comment by Danieloses** [comment]
Potwierdzam, pierwszy komentarz - http://www.wowhead.com/spell=23214/summon-charger#comments

**Comment by Io36** [comment]
Tylko mount paladyna na lv 20 tak działa. Ten na 40 trzeba wpierw iść do trenera, tak jak poprzednicy napisali.
