### ISSUE TITLE
[NPC] 19423 i 19640 - Bleeding Hollow Riding Worg i Bleeding Hollow Worg

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#16]
**Opis**: Kilkakrotność danych npc.

**Obecne działanie**: Problem polega na tym, że wymienione NPC mnożą się i chodzą w jednej teksturze. Po zaatakowaniu widać ich ilość.

**Oczekiwane działanie**: Tekstury nie powinny się nanosić, powinna być jedna jednostka, a nie kilka.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się na miejsce.
2. Zaatakować NPC
3. Sprawdzić ilość.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=19423/bleeding-hollow-worg#drops
2. http://www.wowhead.com/npc=19640/bleeding-hollow-riding-worg
3.

**Comment by Shon-su** [comment]
done
