### ISSUE TITLE
Warlockowe pety, a lvling

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#160]
**Opis**: Podczas lvlowania peta warlockowego traci on swoje umiejętności z paska kiedy one się upgrade'uja do wyższego rank'u i trzeba dodawać manualnie ze spellbook'a.

**Obecne działanie**: jw

**Oczekiwane działanie**: Skille peta powinny się upgrade'ować na pasku, a nie że trzeba dodawać ze spellbooka.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przyzwać peta.
2. Zdobyć lvle dla peta.
3. Przyzwać (sprawdzić bez) peta i zobaczyć umiejętności czy są usunięte

**Comment by Mithras2801** [comment]
Potwierdzam ponownie. Umiejętności peta nie upgrade'uja sie na pasku. Wywala za każdym razem i trzeba ze spellboka dodawać.

**Comment by ThePuppetMaster** [comment]
Mam też potwierdzenia od innych Locków.
