### ISSUE TITLE
[NPC][19055]Windroc Matriartch

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#161]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Respi sie wiele razy w jednym miejscu i ma zbugowane waypointy

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/wuteU

**Comment by ThePuppetMaster** [comment]
Problem dotyczy spawnu mobów aktywowanego podczas questu. Problem jest globalny.
