### ISSUE TITLE
[quest] mission-the-abyssal-shelf 

### ISSUE THREAD

**Issue by czajaj** [RaphaelSunwell/Sunwell-BugTracker-SCv2#163]
**Opis**: robiac ten quest mozna niechcacy zabic ludzi z przeciwnej frakcji
* http://www.wowhead.com/quest=10163/mission-the-abyssal-shelf
*Obecne działanie**: jak wyżej 

**Oczekiwane działanie**:  nie powinno dac sie zabijac graczy za pomoca bomby do questa,  co u nas skutkuje banem

**Co należy zrobić, aby odtworzyć ten błąd**:wziac quest i rzucic bombe w gracza przeciwnej frakcji 

1.*** http://www.wowhead.com/quest=10163/mission-the-abyssal-shelfLinki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Radeghost** [comment]
bump

**Comment by Shon-su** [comment]
fix wysłany
