### ISSUE TITLE
[TALENT][MAG] Precision

### ISSUE THREAD

**Issue by fruvel** [RaphaelSunwell/Sunwell-BugTracker-SCv2#164]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po wpakowaniu 3 pkt w ten talent, nie zwieksza sie hit, tzn nadal missujemy w moby ktore sa na naszym lvlu, badz nizszym, a o wyzszych to juz nie wspominam

**Obecne działanie**: nie zwieksza hita ze spelli o 3%, chyba ze te 3% to nic, wiec nie wiem czy oplaca sie naprawiac =), 

**Oczekiwane działanie**: powinien dodac 3% hita ze spelli, ogolem, wiec powiedzmy ze mam aktualnie 2% hita z itemow, ten talent da mi 3% wiec mam miec 5% hita

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wpakowac pkt w te talenty
2. miec ok 38 lvl, bic moby na swoim lvl nizszym i wyzszym
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=29440
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
40.0 35.7 np: stranglethorn vale

**Comment by Nuy** [comment]
Zwiększa a twoje "bo mi się tak wydaje" nie ma żadnego merytorycznego znaczenia. Miałem ten talent + talent pod hita z drzewka Arcane i praktycznie zawsze trafiałem na heroicach.

http://wowwiki.wikia.com/wiki/Spell_hit

**Comment by Io36** [comment]
Ten talent nigdy nie zwiększy hit w hit capie. Zwiększa procent, ale w tabeli ci ego nie pokaże. Jeśli uważasz, że nie działa po testuj na mobach bez talentu i z talentem (nie mając żadnego hit z itemków).
