### ISSUE TITLE
[Item][6838] Scorched Spider Fang

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#165]
**Opis**: Item dropi z NPC entry 1111. Powinien miec 100% drop chance,  a ma mniej. Powinien miec np 65% szansy na drop 2 fangow i 45% szansy na drop 1 fangu (zrodlo w linku ponizej).
To item do questa 1701

Zrodlo: http://www.wowhead.com/item=6838/scorched-spider-fang

**Comment by myentos** [comment]
[http://wotlk.openwow.com/item=6838](http://wotlk.openwow.com/item=6838)
Jest dobrze
