### ISSUE TITLE
[ITEM] Fel Weightstone

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#166]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Enchant broni [Fel Weightstone](http://www.wowhead.com/item=28420/fel-weightstone) nie działa na każdym typie broni. 
**Obecne działanie**: 
Enchant broni [Fel Weightstone](http://www.wowhead.com/item=28420/fel-weightstone) nie działa na każdym typie broni. Próbowałem na one hand sword, two hand axe, two hand mace i zadziałało tylko na mace. Bronie nie przekraczały podanego w opisie item lvlu oraz nie miały zbyt małego ilvl. Testowałem na broniach z outland.
**Oczekiwane działanie**: 
Enchant powinien działać na każdym typie broni.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć Fel Weightstone na różnych typach broni nie przekraczających 165 ilvl oraz nie będących na niższym o ileś tam. Najlepiej wypróbować na itach z out.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/item=28420/fel-weightstone](http://www.wowhead.com/item=28420/fel-weightstone)
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Io36** [comment]
.... przetłumacz sobie co znaczy ten item. Powiem tak, zgłoszenie można zamknąć. Item powinien działać tylko na broń obuchową (czytaj młoty, maczugi itp). Na broń "ostrą" należy szukać itemku z nazwą "Sharpening stones".

**Comment by myentos** [comment]
Ahahahaha, o kurde racja. Szczerze mówiąc to właśnie tego jednego słowa nie znałem. Na swoją obronę dodam jedynie że na jednym z serwerów to działało na każdym typie broni i to mnie zmyliło. Dzięki :)
