### ISSUE TITLE
[SPELL]Hunter Volley

### ISSUE THREAD

**Issue by charmelina** [RaphaelSunwell/Sunwell-BugTracker-SCv2#167]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Występuje bug związany z aa podczas castowania umiejętności Volley.

**Obecne działanie**: Występuje bug związany z aa podczas castowania umiejętności Volley. Kiedy mamy zaznaczony target i będziemy castować Volley to podczas tego casta nasza postać będzie autoattackować zaznaczony target bez przerwania casta. 

**Oczekiwane działanie**: Volley jest umiejętnością castowaną więc nie powinno się móc nic robić bez przerywania casta.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. ZAZNACZYĆ TARGET DO AUTOATTACKOWANIA
2. WYCASTOWAĆ VOLLEY
3. ZAOBSERWOWAĆ BŁĄD :)

**Comment by valcy** [comment]
Zaden auto shot/attack nie powinien byc wykonany podczas castowania czy channelowania.
Wyjatkiem jest steady shot.

**Comment by kovaq** [comment]
https://youtu.be/HiIh77c3H0Q
Wciaz sa z tym problemy.
