### ISSUE TITLE
[NPC] Wrath Master

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#168]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
[Wrath Master](http://www.wowhead.com/npc=19005/wrath-master) na tym poziomie nie powinien znajdować się w tym miejscu. Stoi obok quest obiektu i będzie zabijać low lvli. Da się go ominąć, ale niektórzy mogą mieć problemy.
**Obecne działanie**: 
[Wrath Master](http://www.wowhead.com/npc=19005/wrath-master) stoi w złym miejscu. 
**Oczekiwane działanie**: 
[Wrath Master](http://www.wowhead.com/npc=19005/wrath-master) na tym poziomie nie powinien znajdować się w tym miejscu.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się w miejsce podane koordynatami
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=19005/wrath-master
2. [Dowód](http://i.imgur.com/uyzVW0Z.jpg)
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Map: 530 (Outland) Zone: 3483 (Hellfire Peninsula) Area: 3804 (The Legion Front) Phase: 1
X: -418.510010
Y: 1828.479980
Z: 74.199997

**Comment by ThePuppetMaster** [comment]
Done
