### ISSUE TITLE
[QUEST][NPC] Thassarian ID 29799

### ISSUE THREAD

**Issue by Triceps69** [RaphaelSunwell/Sunwell-BugTracker-SCv2#169]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:NPC dla ally, stojący na statku w Icecrown daje nam odrazu wszystkie questy jakie ma do zaoferowania, bez trzymania się żadnej kolejności w chainach itp.

**Obecne działanie**: JW

**Oczekiwane działanie**: NPC powinien dawać nam questy po kolei

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pojsc do NPC Thassarian
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=29799/thassarian
![wowscrnshot_112816_151450](https://cloud.githubusercontent.com/assets/23584783/20671529/ecc4c662-b57d-11e6-87c8-6f44b0554f25.jpg)

2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
http://wowwiki.wikia.com/wiki/Quest:Sneak_Preview_(Alliance)

**Comment by Shon-su** [comment]
poprawione
