### ISSUE TITLE
[QUEST][NPC] High Captain Justin Bartlett ID 30344

### ISSUE THREAD

**Issue by Triceps69** [RaphaelSunwell/Sunwell-BugTracker-SCv2#170]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: NPC daje nam odrazu wszystkie questy

**Oczekiwane działanie**: Powinna być zachowana kolejność w dawanych questach.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Pójsć do NPC High Captain Justin Bartlett
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=30344/high-captain-justin-bartlett
2. ![wowscrnshot_112816_152058](https://cloud.githubusercontent.com/assets/23584783/20671608/48cf0242-b57e-11e6-9acb-2aa776a54a5b.jpg)
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawka dosłana
