### ISSUE TITLE
[mobs] w grze

### ISSUE THREAD

**Issue by fruvel** [RaphaelSunwell/Sunwell-BugTracker-SCv2#171]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  moby stoja na swoim miejscu, jednak sa na szaro tak jakby je ktos uderzyl

**Obecne działanie**:  moby stoja na swoim miejscu, jednak sa na szaro tak jakby je ktos uderzyl, i nie zdarza sie to zawsze, ale coraz czestrzy jest to problem, bo po zabiciu nie ma loota ani doswiadczenia

**Oczekiwane działanie**: moby powinny wracac na swoje miejsce calkowicie zresetowane 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. isc do stv 
2. posprawdzac akurat mi sie zdarzylo w ziata'jai ruins
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
42.7 34.5 stranglethorn vale

**Comment by ThePuppetMaster** [comment]
Nie jestem w stanie odtworzyć.
