### ISSUE TITLE
[NPC] Bleeding Hollow Tormentor (19424)

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#172]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mob rzuca feara na siebie.

**Obecne działanie**: Mob - Bleeding Hollow Tormentor (19424) rzuca feara na samego siebie.

**Oczekiwane działanie**: Mob powinien rzucać feara na aktualnie atakowany target.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakować ww. moba.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=19424

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
-1087, 1991, 67, 530

**Comment by Shon-su** [comment]
Cytat z komentarzy na wowheadzie:
`Can fear a second target, will never fear the guy highest on his threatlist.`

Tak też jest zrobione zarówno na sunwellu jak i TC. Jesli ktoś ma dowód że powinno być inaczej proszę o jego zamieszczenie.
