### ISSUE TITLE
[ITEM] Dragon's call

### ISSUE THREAD

**Issue by navaro19** [RaphaelSunwell/Sunwell-BugTracker-SCv2#175]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:nie dziala w 100% tak jak powinien

**Obecne działanie**: przyzywa malego smoka, ale nie atakuje on celu

**Oczekiwane działanie**: po wezwaniu smoka, ten powinien atakowac naszego wroga
**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=10847/dragons-call
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by RaphaelSunwell** [comment]
Poprawione
