### ISSUE TITLE
[PRZEDMIOT] Pattern: Heavy Leather Ball 

### ISSUE THREAD

**Issue by Vooktian** [RaphaelSunwell/Sunwell-BugTracker-SCv2#176]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:U vendora brakuje przepisu Pattern: Heavy Leather Ball 

**Obecne działanie**: Brak przepisu u vendora

**Oczekiwane działanie**: Obecność przedmiotu u vendora Tamar w Ogrimmar

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Otworzyć sklep z pozycji normalnego gracza.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=18731/pattern-heavy-leather-ball
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by charmelina** [comment]
jest jeden do kupienia dziennie :)

**Comment by RaphaelSunwell** [comment]
Pattern: Heavy Leather Ball jest do kupienia raz dziennie.
