### ISSUE TITLE
[NPC] Overthane Balargarde <Master of Jotunheim> ID 31016

### ISSUE THREAD

**Issue by Triceps69** [RaphaelSunwell/Sunwell-BugTracker-SCv2#177]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:NPC pojawia się do zrobienia questa http://www.wowhead.com/quest=13142/banshees-revenge

**Obecne działanie**: Po wipe NPC nie znika, czego skutkiem jest sytuacja przedstawiona na screenie. w jednym miejscu stoi kilka NPC

**Oczekiwane działanie**: NPC po wipie powinien zniknać, przez co zawsze spawnuje się swieży.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wziać quest  http://www.wowhead.com/quest=13142/banshees-revenge
2. zobaczyc ile stoi npc w jednym miejscu 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13142/banshees-revenge
2. http://www.wowhead.com/npc=31016/overthane-balargarde
3. 

![wowscrnshot_112816_221141](https://cloud.githubusercontent.com/assets/23584783/20686286/567af402-b5b8-11e6-8a2f-847709df4075.jpg)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by myentos** [comment]
[Filmik]( https://www.youtube.com/watch?v=20QMt4qMVeI&feature=youtu.be)

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane dzisiaj (tj. 27.01) około 6 rano.
