### ISSUE TITLE
[QUEST] A Daughter Love (prosta naprawa)

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#178]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Brak ikonki znaku zapytania na grobie (choć klikajac na grób quest mozna oddać)

**Oczekiwane działanie**: Powinien być nad grobem znak zapytania by oddać quest
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać znak zapytania by po wykonaniu questu widzieć co kliknąć.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=26797/a-daughters-love
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Radeghost** [comment]
Nie bug
