### ISSUE TITLE
[QUEST] The Weathered Grave (prosta naprawa)

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#179]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Brak wykrzyknika nad grobem, gdzie możemy przyjąć quest (choć klikając na grób da się wywołać okno questu)

**Oczekiwane działanie**: Dodać do grobu wykrzyknik.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać do grobu wykrzyknik.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=26793/the-weathered-grave
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Radeghost** [comment]
Jest blizzlike. Ogladalem filmiki z retaila z WotLK i rowniez nie bylo wykrzyknikow przy takich gobjectach,
