### ISSUE TITLE
[SPELL]Wild Growth

### ISSUE THREAD

**Issue by rosenoo** [RaphaelSunwell/Sunwell-BugTracker-SCv2#180]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: nie leczy wszystkich w zasięgu.

**Obecne działanie**: zauważyłem że wild growth nie zawsze leczy  wszystkich w party (są w zasięgu) raz targetuje prawidłowo albo wcale..

**Oczekiwane działanie**: ....

**Co należy zrobić, aby odtworzyć ten błąd**: poprawić działanie by łapał każdy target w zasięgu.

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**: http://wotlk.openwow.com/spell=53248

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Heals up to 5 friendly party or raid members within 15 yards of the target for 861 over 7 sec

**Comment by RaphaelSunwell** [comment]
Wild Growth działa dobrze. Mylisz działanie z późniejszych dodatków.
