### ISSUE TITLE
Brakujace Technique u Vendorów

### ISSUE THREAD

**Issue by ThePuppetMaster** [RaphaelSunwell/Sunwell-BugTracker-SCv2#181]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Przy okazji zmian w profesjach dostało się też tym, w które nie mieliśmy ingerować.

**Obecne działanie**: Brakuje recept do Inskrypcji, na glyphy u vendorów.

**Oczekiwane działanie**:
1. Item 50166 u vendorów 28723 30734 30735
2. Itemy 50168 50167 u vendora 28723

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=50166
2. http://wotlk.openwow.com/item=50168
3. http://wotlk.openwow.com/item=50167
4. http://www.wowhead.com/npc=28723/larana-drome
5. http://www.wowhead.com/npc=30734/jezebel-bican
6. http://www.wowhead.com/npc=30735/kul-inkspiller

**Comment by ThePuppetMaster** [comment]
Poprawiłem, zamykam.

**Comment by RaphaelSunwell** [comment]
do sprawdzenia.
