### ISSUE TITLE
[QUEST][NPC] Planting the Banner

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#182]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Po użyciu [quest itemu](http://www.wowhead.com/item=30416) powinny pojawiać się pod wieżą NPC i atakować falami osobnika na szczycie wieży gdzie został użyty q item. 
**Obecne działanie**: 
NPC pojawiają się pod wieżą ale tylko stoją. Zanim użyłem flagi, zapewne ktoś to już zrobił, ale może być też tak, że same się spawnują mimo użycia baneru.
[Dowód](https://www.youtube.com/watch?v=DvgZAHUIlSM&feature=youtu.be)
**Oczekiwane działanie**: 
NPC powinny atakować falami osobnika na szczycie wieży.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest [http://www.wowhead.com/quest=10518/planting-the-banner](http://www.wowhead.com/quest=10518/planting-the-banner)
2. Uzyskać banner od [http://www.wowhead.com/npc=21296/bladespire-champion](http://www.wowhead.com/npc=21296/bladespire-champion)
3. Użyć go na wieży podanej w queście. 

**Linki WoWHead/OpenWoW**:

1.[http://www.wowhead.com/quest=10518/planting-the-banner]( http://www.wowhead.com/quest=10518/planting-the-banner)
2. [http://www.wowhead.com/item=30416/bladespire-clan-banner](http://www.wowhead.com/item=30416/bladespire-clan-banner)
3. [http://www.wowhead.com/npc=21296/bladespire-champion](http://www.wowhead.com/npc=21296/bladespire-champion)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by kovaq** [comment]
Wciaz wystepuje:
https://youtu.be/TbDtPHZdFMI

**Comment by Shon-su** [comment]
fix podesłany
