### ISSUE TITLE
[QUEST][NPC] Getting the Bladespire Tanked

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#183]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Po użyciu na [ogrze ](http://www.wowhead.com/npc=19995/bladespire-brute)podczas walki z nim [quest itemu](http://www.wowhead.com/item=30353/bloodmaul-brutebane-keg) NPC nas nie atakuje ale jesteśmy w combacie. Po oddaleniu się combat znika, ale później NPC jest bugnięty. Gdy podejdziemy do niego, NPC nie zaatakuje dopóki sami go nie zaatakujemy. Zauważyłem również, że po użyciu [quest itemu](http://www.wowhead.com/item=30353/bloodmaul-brutebane-keg) i zaatakowaniu go, NPC po pewnym czasie ucieka z walki. [Dowód:](https://www.youtube.com/watch?v=eB3U_mzDIX4&feature=youtu.be)
**Obecne działanie**: 

**Oczekiwane działanie**: 
NPC nie powinien uciekać z walki, gdy został odurzony browarem. 
NPC nie powinien być obojętny na nas po tym jak użyliśmy podczas walki qitemu oraz po tym jak uciekliśmy z combatu.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest 
2. Postawić q item przed ogrem podczas walki
3. Reszta na filmie.

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/quest=10512/getting-the-bladespire-tanked](http://www.wowhead.com/quest=10512/getting-the-bladespire-tanked)
2. [http://www.wowhead.com/item=30353/bloodmaul-brutebane-keg](http://www.wowhead.com/item=30353/bloodmaul-brutebane-keg)
3. [http://www.wowhead.com/npc=19995/bladespire-brute](http://www.wowhead.com/npc=19995/bladespire-brute)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
