### ISSUE TITLE
[QUEST][NPC] A Dire Situation

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#184]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Użycie q itemu na [wilku](http://www.wowhead.com/npc=20058/bloodmaul-dire-wolf) sprawia, że zalicza podwójnie do q. [Dowód](https://www.youtube.com/watch?v=4x0Lb9tiWyw&feature=youtu.be)
**Obecne działanie**: 
Użycie q itemu na [wilku](http://www.wowhead.com/npc=20058/bloodmaul-dire-wolf) sprawia, że zalicza podwójnie do q. [Dowód](https://www.youtube.com/watch?v=4x0Lb9tiWyw&feature=youtu.be)
**Oczekiwane działanie**: 
Powinno zaliczać jednorazowo.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest [http://www.wowhead.com/quest=10506/a-dire-situation](http://www.wowhead.com/quest=10506/a-dire-situation)
2. Użyć [http://www.wowhead.com/spell=36310/rinas-diminution-powder#comments](http://www.wowhead.com/spell=36310/rinas-diminution-powder#comments) na wilku
3. 

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/npc=20058/bloodmaul-dire-wolf](http://www.wowhead.com/npc=20058/bloodmaul-dire-wolf)
2. [http://www.wowhead.com/quest=10506/a-dire-situation](http://www.wowhead.com/quest=10506/a-dire-situation)
3. [http://www.wowhead.com/spell=36310/rinas-diminution-powder](http://www.wowhead.com/spell=36310/rinas-diminution-powder)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
