### ISSUE TITLE
[QUEST] The Ancient Armor of the Kvaldir

### ISSUE THREAD

**Issue by mordeusz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#185]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest jest do wykonania, jedyny problem jaki występuje to problem z użyciem samolotu żeby dostać się na wyspę przy której znajduję się quest item jak i podróż powrotna. 

**Obecne działanie**: Po dialogu z NPC Alanya i wejściu na samolot odrazu nas wyrzuca z niego tak jakbyśmy z niego wyszli w powietrzu, gdyż dostajemy spadochron. Problem występuję w przypadku podróży w obie strony. Żeby zaliczyć quest trzeba się dostać w odpowiednie miejsca piechotą.

**Oczekiwane działanie**: Po wejściu w samolot nie powinno nas z niego wyrzucać.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wziąć questa i porozmawiać z NPC Alanya
2.  Dostać się na wyspę na którą powinien nas zabrać samolot i spróbować użyć samolotu.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11567/the-ancient-armor-of-the-kvaldir
2. https://www.youtube.com/watch?v=zBbxkpjGMgg tak powinno to wszystko wyglądać.
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Neos3452** [comment]
Naprawione w trinitycore:
https://github.com/TrinityCore/TrinityCore/issues/11154

wystarczy przekleic SQL i smiga.

**Comment by Shon-su** [comment]
Dzięki za podesłanie.
