### ISSUE TITLE
[QUEST] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by mordeusz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#189]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest polega na zabraniu za pomocą gryfa przestraszonych mieszkańców wioski, niestety podczas podlatywania do Npcow(wystarczy tez miec ich w zasiegu wzroku) oni po prostu znikaja

**Obecne działanie**: Npc znikaja z nie wiadomych mi przyczyn

**Oczekiwane działanie**: Npce powinny poruszac sie na fearze po miescie i nie powinny znikac.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wziac questa i wejsc na gryfa
2.  Zaczac latac po miescie
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender
2. https://www.youtube.com/watch?v=5BASWje_pvg&feature=youtu.be nagrany filmik najlepiej spojrzec na 1:30 a potem 2:30
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by zbynew** [comment]
podbijam, najwazniejszy quest zbugowany, nie można kontynuować super serii w dragonblight. FIX IT!

**Comment by Sleepingdog03** [comment]
Uda się by NPC wsiadł na gryfa, ale po chwili znika. Ten quest blokuje całą linię fabularną w Dragonblight. Bardzo proszę o szybką naprawę.

**Comment by myentos** [comment]
Jeżeli ktoś jest na niego bardzo napalony, to można go ukończyć po restarcie.

**Comment by Sleepingdog03** [comment]
Jak po resecie jakiś inaczej zachowują się npc ?

**Comment by myentos** [comment]
Zrobiłem go zaraz po restarcie, NPC do zadania normalnie wskakiwały na gryfa. No może z 3 NPC znikały, a tak to reszta zachowywała się normalnie.

**Comment by Sleepingdog03** [comment]
Nigdy nie wiem kiedy jest tu reset . Mówisz o reszcie daly Quest ?

**Comment by myentos** [comment]
Mówię o Flight of the Wintergarde Defender i tylko o tym. Restart nie jest z góry ustalony ani w pewnych odstępach czasu. Administracja restartuje serwer gdy zajdzie taka potrzeba, mi się akurat wczoraj udało.

**Comment by Sleepingdog03** [comment]
Ok dzięki za info

**Comment by Yhavi** [comment]
Dzisiaj rano ( ok. 8:00) udało mi się załadować 4x npców. Reszta dalej znikała

**Comment by Sleepingdog03** [comment]
Teraz o 19.20 nic nie działa każdy npc znika

**Comment by Nuy** [comment]
Nie działa. Proszę o rychłe naprawienie, bo bez zrobienia tego questa nie da się wykonać praktycznie wszystkich następnych w Wintergarde co bardzo utrudnia expienie.

**Comment by zaner89** [comment]
zgodnie z blizzlike kazdego npc mozna odwiedz tylko raz ale u nas zamiast ta uniatowość odnosic sie jedynie do gracza robiącego quest odnosi sie do całej populacji serwera

**Comment by Mojsik** [comment]
To nie chodzi o to, aby ktoś kto chce zrobić quest musiał siedzieć i wyczekiwać wipe serwera. Powinien działać normalnie.

**Comment by myentos** [comment]
No nie chodzi o to, ja tylko podałem tipa, który może niektórym pomóc. Wiadome, powinni to naprawić, ale zanim to zrobią macie jakąś możliwość.

**Comment by Sleepingdog03** [comment]
Dziś próbowałem wykonać quest ale nadal NPC znikają

**Comment by tokacz** [comment]
quest nadal nie działa, a szkoda

**Comment by ThePuppetMaster** [comment]
Proszę skończyć komentarze typu "nadal nie działa". Zgłoszenie dostało label. Bug Tracker to nie forum.

**Comment by tokacz** [comment]
quest dodany dopiero w patchu 3.3.0, a server ustawiony na 3.02 chyba, że coś się zmieniło

**Comment by Mithras2801** [comment]
Quest wykonywalny jest już.

**Comment by Larousene** [comment]
Bump! Questa nie da się nawet rozpocząć. Gdy wsiadam na gryfa, nie mogę się zarówno nim ruszyć jak i z niego zsiąść
