### ISSUE TITLE
[QUEST][SHAMAN] Call of Fire (part 5 of 5)

### ISSUE THREAD

**Issue by Vaelevian** [RaphaelSunwell/Sunwell-BugTracker-SCv2#19]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest polega na porozmawianiu z Kranal Fiss.

**Obecne działanie**: Nie mozna oddac questa [Call of Fire] part 5 of 5 u Kranal Fiss.

**Oczekiwane działanie**: Gracz powinien móc porozmawiać z Kranal Fiss w celu oddania questa i wzięcia kolejnego.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejść do Kranal Fiss z questem Call of Fire part 4 of 5.
2. Spróbować wejść w interakcję z NPC.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Quest:Call_of_Fire_(Horde)
2. http://wowwiki.wikia.com/wiki/Kranal_Fiss
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 
(55.0 20.0)Durotar, obok Valley of Trias

**Comment by vathion** [comment]
Jest to quest Call of Fire (Part 5 of 5). I koordynaty trzeba odpowiednio zmienić na coś koło (55.0 20.0) Reszta jest dobrze.

**Comment by Vaelevian** [comment]
Dziękuję, już poprawiam.
