### ISSUE TITLE
[QUEST] Investigate the Blue Recluse

### ISSUE THREAD

**Issue by Ahanai** [RaphaelSunwell/Sunwell-BugTracker-SCv2#190]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Problem z questem dla magów w Stormwind.

**Obecne działanie**: Nie da się wykonać questu, po zbiciu HP przywołanego Rift Spawnu użycie itemu, aby go "złapać", nie daje żadnych efektów.

**Oczekiwane działanie**: Po zbiciu HP przywołanych mobków powinno się użyć itemu, by je złapać i wykonać quest.

**Co należy zrobić, aby odtworzyć ten błąd**:

Jest to quest dla magów, który otrzymujemy na 10 czy 15 lvlu od NPC Jennea Cannon w Wizard's Sanctum w Stormwind. Należy wziąć itemy zza jej pleców i udać się do Blue Recluse, użyć jednego z itemów i zabić przywołane moby, potem użyć na nich drugiego itemu.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=1920/investigate-the-blue-recluse
2. 
3. 

Możliwe, że coś robię nie tak, ale wg mnie quest nie działa jak powinien.

**Comment by Towoku** [comment]
[quest] Investigate the Alchemist Shop [part 2 of 3] #80 duplikat.
