### ISSUE TITLE
[Quest]Klockmort's Essentials

### ISSUE THREAD

**Issue by felmad** [RaphaelSunwell/Sunwell-BugTracker-SCv2#191]
**Opis**: Zadanie u NPC jest dostępne na nieodpowiednim poziomie

**Obecne działanie**: Przychodzimy do NPC na odpowiednim (30) poziomie by przyjąć zadanie, jednakże zadania nie ma.

**Oczekiwane działanie**: NPC powinien mieć możliwość przekazania nam zadania od poziomu 30.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wbijamy poziom 30-32
2. Udajemy się w miejsce przebywania NPC który daje zadanie

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=2925
2. http://wowwiki.wikia.com/wiki/Quest:Klockmort%27s_Essentials

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: NPC - http://wotlk.openwow.com/npc=6142 (59.5, 45.4)

**Comment by felmad** [comment]
Nie wiem czy było coś zmieniane, ale na 33 poziomie zadanie się pojawiło, chociaż wowwiki mówi inaczej.

**Comment by RaphaelSunwell** [comment]
Zadanie pojawia się od 24 lvl. 
Opewnwow: Requires level: 24

**Comment by felmad** [comment]
Dla mnie pojawiło się na 33 poziomie, dlatego można się przyjrzeć czy jest to poprawne, chyba że to już zostało wykonane.
