### ISSUE TITLE
[STATYSTYKA] CRITICAL STRIKE JEST ŹLE OBLICZANY

### ISSUE THREAD

**Issue by plessico** [RaphaelSunwell/Sunwell-BugTracker-SCv2#192]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Statystyka critical strike jest źle obliczana

**Obecne działanie**:Mam 3% criticala, kiedy samo agility dodaje mojej postaci 9% criticala. Wszystkie bronie mam wyskillowane na maxa

**Oczekiwane działanie**:Critical musi być obliczany poprawnie 
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Grać rougiem
2. Polevelować trochę w tanaris
3. Sprawdzić swoje statystyki criticala oraz agility i je porównać

**Linki WoWHead/OpenWoW**:

1. 
![wowscrnshot_112916_205950](https://cloud.githubusercontent.com/assets/24256650/20726989/0748b03e-b678-11e6-9c69-2b2cc0795159.jpg)
![wowscrnshot_112916_210012](https://cloud.githubusercontent.com/assets/24256650/20726996/11994bc0-b678-11e6-8126-5966bcce19b2.jpg)
![wowscrnshot_112916_210022](https://cloud.githubusercontent.com/assets/24256650/20727001/14061352-b678-11e6-9e4f-f1f210aa89f1.jpg)
![wowscrnshot_112916_210026](https://cloud.githubusercontent.com/assets/24256650/20727003/15f30b52-b678-11e6-8272-eb4817e5116e.jpg)
![wowscrnshot_112916_211009](https://cloud.githubusercontent.com/assets/24256650/20727082/5bcc4ab2-b678-11e6-90bb-13fca1532ce0.jpg)

2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Lebiedz** [comment]
Prawdopodobnie masz buga z wyświetlaniem crita - spójrz #188
