### ISSUE TITLE
[QUEST] Battle of Hillsbrad (7) - Brak NPC

### ISSUE THREAD

**Issue by halbazzer** [RaphaelSunwell/Sunwell-BugTracker-SCv2#193]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak NPC "Bragor Bloodfist" (Undercity: 56.2, 92,2) odbierającego quest

**Obecne działanie**: n/d

**Oczekiwane działanie**: w podanych koordynatach powinien być NPC

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  zapewne wystarczy wykonać chain "Battle of Hillsbrad" do powyższego q
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. https://wotlk-twinhead.twinstar.cz/?quest=14351
2. http://wowwiki.wikia.com/wiki/Quest:Battle_of_Hillsbrad_%287%29
3. http://www.wowhead.com/quest=550/deprecated-battle-of-hillsbrad

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Undercity 56.2, 92.2

**Comment by RaphaelSunwell** [comment]
Npc dodany.

**Comment by halbazzer** [comment]
NPC jest, ale nie "odbiera" questa..

na mapie UC pojawia się nawet znaczek "?", a nad NPC'em nie ma "?" i rozmowa z nim nie przynosi rezultatu (pokazuje się tylko standardowy tekst NPC'a + "Goodbye")
