### ISSUE TITLE
[quest] Fiora Longears

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#194]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Speak with Fiora Longears on the docks at Auberdine in Darkshore.
Description
Oh, to be at sea once again! To feel the kiss of the wind, and to have the waves rock me like my blessed mother, long ago!

Oh, I wish I had your fortune, good <class>, for I see the sea in your future!

It's my job to tell eager souls of the land of Kalimdor, the land of opportunity! If you're willing to try your luck across the sea, then take a ship from here to the lovely port of Auberdine. Speak there with my partner, the elf, Fiora Longears.

She'll start you on your Kalimdor adventure! 

**Obecne działanie**: Brak zlecenia questu przez NPC Red Jack Flinta (dodam, że w wersji WoW 3.3.5a powinien być dostępny dla gracza.

**Oczekiwane działanie**: Powinien znajdować się znak wykrzyknika nad NPC'em (a jest no clickable)

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Dać możliwość przyjęcia przez gracza questu
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=1132/fiora-longears
2. http://db.vanillagaming.org/?quest=1132
3. http://db.vanillagaming.org/?npc=4455

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Wetlands 9,9/57,9

**Comment by felmad** [comment]
Jak widać w komentarzu na wowhead, quest na 3.3.5 został usunięty, a konkretniej na patchu 3.3.0, więcej info można znaleźć na wowwiki, ale nie stoi na przeszkodzie dodanie go ponownie, o czym wspomniałem w tym temacie: http://forum.sunwell.pl/viewtopic.php?f=64&t=1520

**Comment by RaphaelSunwell** [comment]
Quest dodany.

**Comment by Isilion** [comment]
Quest może i dodany, lecz i tak nie do sfinalizowania, gdyż odbiorca - Fiora Longears jest unclickable i bez znaku zapytania.
Trochę to trwa z usunięciem błędu, blokując listę questów graczom.
