### ISSUE TITLE
[NPC] Wooly Mammoth Bull i atakowanie innych graczy 

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#195]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Podczas questa Kaw the Mammoth Destroyer [11879] wsiadamy na jakiegokolwiek Wooly Mammoth Bull [25743]. Te NPC maja unikalne skille kiedy na nich jestesmy.

**Obecne działanie**: Spelle Mammoth Charge [46315], Thundering Roar [46316] i Mammoth Trample [46317] dzialaja na graczy

**Oczekiwane działanie**: Powyzsze spelle nie powinny dzialac na graczy i na inne moby. Powinien dzialac tylko na NPC entry: 25880, 25881 i 25802, zgodnie z opisem. Poza tym po ukonczeniu tego questa, 11879, NPC Mammoth Bull [25743] powinny juz nie byc dla nas hostile, lecz neutral.

http://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer
"When you complete this quest, the Wooly Mammoth Bulls will no longer be hostile to you."
^ te moby nie sa hostile kiedy mamy quest (tak ma byc, musimy wsiasc na nie), ale po quescie juz sa hostile, mimo, ze nie powinny

**Comment by morgaur** [comment]
Od siebie dodam ,że przy tym q podczas szarży na Kawa 3x wpadłem w textury

**Comment by Mithras2801** [comment]
Gracze usilnie ten bug wykorzystują. Sam ostatnio padłem 5 razy na 20 min. Widać, że gracze wiedzą o tym bygu i wpierw wskakują  na mounta i target player.

**Comment by Shon-su** [comment]
poprawione
