### ISSUE TITLE
[QUEST] Brothers in death

### ISSUE THREAD

**Issue by DebowyMocny** [RaphaelSunwell/Sunwell-BugTracker-SCv2#196]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Brothers of death jest kluczowym questem wśród questów startowych Death Knighta. Fakt że ten quest nie działa sprawia, że pójście dalej jako Death knight jest niemożliwe.
**Obecne działanie**:
 Nie ma NPC o nazwie Koltira Deathweaver który jest wymagany do zrobienia tego questa. Nie spawnuje się już od godziny. 

**Oczekiwane działanie**: 
NPC powinien się znajdować w piwnicy w scarlet hold.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac quest brothers in death
2. Przyjść do piwnicy Scarlet hold (Lokacji gdzie powinien się ten ów npc znajdować)

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12725/brothers-in-death
2. http://www.wowhead.com/npc=28912/koltira-deathweaver
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
63.68

**Comment by Adasniezgodka** [comment]
Potwierdzam, nie ma npc.

**Comment by RaphaelSunwell** [comment]
Poprawione

**Comment by ramciachciach** [comment]
brak moba. Podbijam.
