### ISSUE TITLE
[TELEPORT] Naxxanar - Borean Tundra

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#197]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Wszystkie teleporty w Naxxanar działają oprócz jednego, powrotnego, na samym szczycie.
**Obecne działanie**: 
[Filmik](https://www.youtube.com/watch?v=XWKBrNccsM0&feature=youtu.be)
**Oczekiwane działanie**: 
Teleport na szczycie zigguratu Naxxanar powinien przenieść nas do środka zigguratu.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dostać się na górę zigguratu
2. Wejść w visual teleportu

**Comment by Mithras2801** [comment]
Potwierdzam. Teleport powinien nas teleportować w to samo miejsce i w tą samą stronę co teleport z dołu.
