### ISSUE TITLE
[QUEST] Take No Chances

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#198]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Na jednym worku można zaliczyć cały q objective.
**Obecne działanie**: 
[Filmik](https://www.youtube.com/watch?v=XwZ2teOGrrk&feature=youtu.be)
**Oczekiwane działanie**:
Na jednym worku powinno zaliczyć raz q objective.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć [q itemu](http://www.wowhead.com/item=35491) obok worka

**Linki WoWHead/OpenWoW**:

1.[ http://www.wowhead.com/quest=11913/take-no-chances]( http://www.wowhead.com/quest=11913/take-no-chances)
2. [http://www.wowhead.com/item=35491](http://www.wowhead.com/item=35491)

**Comment by Mithras2801** [comment]
bump potwierdzam.

**Comment by Shon-su** [comment]
poprawione, nie dograne
