### ISSUE TITLE
[QUEST][SHAMAN] Call of Fire (Part 4 of 5)

### ISSUE THREAD

**Issue by vathion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#20]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wcześniej zgłoszony przez innego gracza ten sam błąd dotyczy kolejnej części chaina oraz ma podane błędnie koordynaty tego questa. Quest polega na zabiciu mobka Minor Manifestation of Fire pod wpływem eliksiru Fire Sapta, z którego dropi Glowing Ember, dzięki któremu możemy zagadać do znajdującego się obok Brazier of the Dormant Flame i zakończyć tam quest, dostając ostatni quest do chaina Call of Fire na Totem of Fire szamana.

**Obecne działanie**: Po zabiciu Minor Manifestation of Fire, dropi nam Glowing Ember i zalicza quest, lecz nie jesteśmy go w stanie oddać, ponieważ Brazier of the Dormant Flame nie ma opcji oddania questa, a jedynie zębatkę, która otwiera puste okno dialogowe.

**Oczekiwane działanie**: Po zabiciu Minor Manifestation of Fire, dropi nam Glowing Ember i zalicza quest, który możemy oddać znajdującemu się obok Brazier of the Dormant Flame i dostać od niego ostatnią część Call of Fire (Part 5 of 5).

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabrać quest od Telf Joolam, a następnie zagadać do niego ponownie by dał nam Fire Sapta.
2. Wypić Fire Sapta przy wielkim kamieniu zaraz obok niego i zabić Minor Manifestation of Fire znajdujący się obok, z którego dropi Glowing Ember.
3. Kliknąć na Brazier of the Dormant Flame - tu pojawia się problem.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=1526
2. http://www.wowhead.com/quest=1526/call-of-fire
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: (39.0 58.0) Durotar

**Comment by ThePuppetMaster** [comment]
Testy wykazały poprawność działania questa.
