### ISSUE TITLE
[QUEST][NPC] Repurposed Technology

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#200]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Po zabiciu [NPC](http://www.wowhead.com/npc=25623/harvest-collector) mamy za zadanie użyć na nim [q itemu](http://www.wowhead.com/item=35943)
**Obecne działanie**: 
Gdy użyjemy na zmarłym NPC q itemu, zwłoki NPC nie znikają zbyt szybko, co daje możliwość kolejnego użycia q itemu.
**Oczekiwane działanie**: 
Na jednym NPC powinno dać się tylko raz użyć q item.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć [q item](http://www.wowhead.com/item=35943/jeremiahs-tools) na zmarłym [NPC](http://www.wowhead.com/npc=25623/harvest-collector)

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/quest=12035/repurposed-technology](http://www.wowhead.com/quest=12035/repurposed-technology)
2. [http://www.wowhead.com/npc=25623/harvest-collector](http://www.wowhead.com/npc=25623/harvest-collector)
3. [http://www.wowhead.com/item=35943/jeremiahs-tools](http://www.wowhead.com/item=35943/jeremiahs-tools)

**Comment by Shon-su** [comment]
poprawione
