### ISSUE TITLE
[QUEST][NPC] The Earthbinder - Hellfire Peninsula

### ISSUE THREAD

**Issue by Dzdzia** [RaphaelSunwell/Sunwell-BugTracker-SCv2#202]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Po wzięciu Q "The Earthbinder" od Tola'thion dostaje q item, który następnie mam oddać do Earthbinder Galandria Nightbreeze jednakże nad głową NPC-a nie wyświetla się znak zapytania, nie ma możliwości oddania Q

**Obecne działanie**: Brak "?" nad głową NPC, co skutkuje brakiem możliwości oddania Q

**Oczekiwane działanie**: Powinno się dać oddać Q

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest The Earthbinder od Tola'thion w Cenarion Post, w Hellfire Peninsula
2. Spróbować go oddać do Earthbinder Galandria Nightbreeze
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10349/the-earthbinder
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 
![wowscrnshot_113016_152758](https://cloud.githubusercontent.com/assets/18365034/20756069/a17ead2c-b711-11e6-99db-a4b3a55bebfd.jpg)

**Comment by myentos** [comment]
To nie jest bug. Wystarczy chwilę poczekać. Ktoś przed Tobą oddał q, który powoduje, że ona schodzi na dół i zasiewa coś tam z czego wyrasta gigant którego trzeba zabić, inaczej on zabije wszystkie npc od q. Po zabiciu giganta, ta laska wychodzi na górę i musisz jakiś czas odczekać, niecałe 20 sekund, aby oddać q.

**Comment by Dzdzia** [comment]
40 min to chwila? Była rozmowa z gm-em Poprosił, abym wrzucił na BT

**Comment by myentos** [comment]
O to w takim razie bug. Kilkakrotnie uspokajałem ludzi aby poczekali te pół minuty i za każdym razem udawało się oddać q.

**Comment by Shon-su** [comment]
bardzo nieprawdopodobna sytuacja, no ale widocznie jakoś się może zdarzyć. NPC się "odblokowywuje" po zabiciu golema sumniętego. Dorzuciłem coś co powinno pomóc
