### ISSUE TITLE
Znikniecie Petów huntera

### ISSUE THREAD

**Issue by Xarafis** [RaphaelSunwell/Sunwell-BugTracker-SCv2#204]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zniknięcie z niewyjaśnionych przyczyn wszystkich petów u huntera, które zdobyłem (a miałem rare peta z sholazar basin).

**Obecne działanie**: Nie przyzywa żadnego peta.

**Oczekiwane działanie**: Powinienem móc przywołać pety uprzednio zdobyte.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Nie mam zielonego pojęcia jak to odtworzyć. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by valcy** [comment]
Opisz dokladniej w jaki sposob ten pet zniknal. Jezeli pet zginal to nie przywiesz go call petem tylko revivem.

**Comment by ThePuppetMaster** [comment]
Rozmawiałem z osobą zgłaszającą. Nie tylko aktywny pet wyparował, pety zniknęły od stable mastera.
