### ISSUE TITLE
[MOBY] Latające w powietrzu moby [?]

### ISSUE THREAD

**Issue by wilq1337** [RaphaelSunwell/Sunwell-BugTracker-SCv2#206]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Moby po wzięciu aggro podczas używania latającego mounta, zaczynają lewitować, mogą zadawać obrażenia graczu.

**Obecne działanie**: Jak wyżej. Filmik ukazujący buga: https://youtu.be/dbtErLMtnEg

**Oczekiwane działanie**: Moby nie powinny lewitować tylko zostać przy ziemi.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć fly mounta
2. Złapać aggro od moba
3.  Wylecieć nad ziemię

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 78.4, 81

**Comment by Koloolok** [comment]
potwierdzam

**Comment by untouched1999** [comment]
potwierdzam

**Comment by xsitdev** [comment]
Rozwiązane kilka tygodni temu.
