### ISSUE TITLE
Q Take No Chances - Borean Tundra

### ISSUE THREAD

**Issue by morgaur** [RaphaelSunwell/Sunwell-BugTracker-SCv2#207]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Quest Take No Chances w Borean Tundra

**Obecne działanie*: Obecnie da się podpalić jeden worek 8 razy

**Oczekiwane działanie**: Po podpaleniu worka powinien on zniknąć i szukamy następnego

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć q Take No Chances w borean
2. podpalic 1 worek 8x
3. zobaczyc dzialanie

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11913/take-no-chances
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by myentos** [comment]
[https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/198](https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/198)
