### ISSUE TITLE
[QUEST][Objective]The Stave of Equinex

### ISSUE THREAD

**Issue by Vaelevian** [RaphaelSunwell/Sunwell-BugTracker-SCv2#21]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest polega na zebraniu 4 ogni: 
Flame of Imbel
Flame of Lahassa
Flame of Byltan
Flame of Samha
Po ich zebraniu należy udać się do Equinex Monolith i w jego pobliżu użyć Troya's Stave, co finalnie da Nam przedmiot Stave of Equinex.

**Obecne działanie**: Przedmioty można zebrać i użyć Troya's Stave, jednak po otrzymaniu Stave of Equinex nie ma możliwości oddania skończonego questa do Equinex Monolith (brak zółtego znaku zapytania nad nim).

**Oczekiwane działanie**: Po zebraniu przedmiotów i użyciu Troya's Stave powinniśmy otrzymać Stave of Equinex, który możemy oddać do Equinex Monolith.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Udać się do Feralas i wziąć quest od Troyas Moonbreeze.
2. Zebrać wymagane przedmioty i stworzyć Stave of Equinex.
3. Spróbować oddać quest do Equinex Monolith.

**Linki WoWHead/OpenWoW**:

1. http://db.vanillagaming.org/?npc=7764
2. http://www.wowhead.com/quest=2879/the-stave-of-equinex
3. http://www.wowhead.com/object=144063/equinex-monolith

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
39.0 , 13.0. Feralas.

**Comment by ThePuppetMaster** [comment]
Powinno już działać.
