### ISSUE TITLE
[GUILD BANK] Info zakładki da się edytować bez pozwoleń

### ISSUE THREAD

**Issue by deltoro95** [RaphaelSunwell/Sunwell-BugTracker-SCv2#211]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Każdy niezależnie od poziomu uprawnień może zmienić informacje o zakładce w guild banku. Problem występuje w gildii http://sunwell.pl/guild/1/240 . Nie wiem jak w innych.
**Obecne działanie**: Bez względu na ustawienie "update tab text" czy "deposit items" każdy obecny w gildii gracz może zmienić informację zakładki w Guild Banku.

**Oczekiwane działanie**: Każda ranga, która ma odznaczone "update tab text" powinna mieć nieedytowalną informację.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Kupić zakładkę w GB
2. Zaprosić alta, dać mu rangę bez pozwoleń.
3. Zmienić tekst w tab info.

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy
![wowscrnshot_120116_113943](https://cloud.githubusercontent.com/assets/24293013/20792214/e9fb5050-b7c0-11e6-8a30-792d27ac8648.jpg)

**Comment by ThePuppetMaster** [comment]
Brak screenów z ustawieniami uprawnień dla poszczególnych rang.
