### ISSUE TITLE
[GUILD] Opóźnione Guild Control

### ISSUE THREAD

**Issue by deltoro95** [RaphaelSunwell/Sunwell-BugTracker-SCv2#212]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po zalogowaniu się na postać opcja Guild Control w oknie gildii nie działa poprawnie. Trzeba odczekać ok. minutę, żeby wszystkie taby i rangi się pojawiły

**Obecne działanie**: Dość długi czas oczekiwania na pojawienie się opcji w Guild Control

**Oczekiwane działanie**: Natychmiastowy dostęp do tych opcji.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Założyć gildię
2. Stworzyć kilka rang
3. Przelogować się i otworzyć Guild Control

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
![wowscrnshot_120116_120310](https://cloud.githubusercontent.com/assets/24293013/20792496/5daac714-b7c2-11e6-8215-18e9b086c8e1.jpg)

**Comment by ThePuppetMaster** [comment]
Nikt z osób testujących nie był w stanie odtworzyć błędu.
