### ISSUE TITLE
[Quest] [NPC] Knowledge is a Terrible Burden

### ISSUE THREAD

**Issue by Howix** [RaphaelSunwell/Sunwell-BugTracker-SCv2#213]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Quest polega na zdaniu raportu. trzeba go tylko oddać. ale niestety nie da się.
NPC- Koltira Deathweaver (horde) 

**Obecne działanie**: Nie da się oddać zadania. Na mapie widać znak " ? " ale nad NPC już nie.
NPC- Koltira Deathweaver (horde) 

**Oczekiwane działanie**: Możliwość rozmowy z NPC. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13401/knowledge-is-a-terrible-burden
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Icecrown, Statek Orgrim's Hammer

**Comment by ThePuppetMaster** [comment]
http://www.wowhead.com/npc=29799/thassarian
NPC jest w sterowcu, poszukaj sterowca.
