### ISSUE TITLE
[QUEST][NPC] Hezrul Bloodmark

### ISSUE THREAD

**Issue by k3lus** [RaphaelSunwell/Sunwell-BugTracker-SCv2#214]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Hezrul wraz z 2 centaurami nie patroluje w okół oazy.
![wowscrnshot_112916_222850](https://cloud.githubusercontent.com/assets/16786142/20794749/18b1a3f6-b7ce-11e6-9bf5-294018a7dbab.jpg)

**Obecne działanie**: Hezrul wraz z dwoma strażnikami stoi w miejscu. Strażnicy nie łapią agrro (podczas ataku z dystansu)

**Oczekiwane działanie**: Hezrul i 2 strażników powinni patrolować oazę wg ruchu wskazówek zegara. Strażnicy powinni mieć grupowe agrro (kiedy Hezrul jest atakowany oni automatycznie łapią agrro)

**Co należy zrobić, aby odtworzyć ten błąd**: n/d

**Linki WoWHead/OpenWoW**:
http://db.vanillagaming.org/?npc=3396#wh-comments (na open wow jest podana mapa z Mulgore)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione
