### ISSUE TITLE
[QUEST][ZŁE FAZOWANIE]Quest chain prowadzacy do Battle of the undercity

### ISSUE THREAD

**Issue by Baggedmilk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#215]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po oddaniu questa http://wotlk.openwow.com/quest=13257 faza w ktorej jestesmy odrazu sie zmienia i nie mozna wziac nastepnego questa od Thralla http://wotlk.openwow.com/quest=13266

**Obecne działanie** Po oddaniu questa http://wotlk.openwow.com/quest=13257 powinnismy byc wstanie wziac quest nastepny http://wotlk.openwow.com/quest=13266 i wejsc do portalu postawionego przez Jaine

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac quest http://wotlk.openwow.com/quest=13257 i oddac go u Thralla
2. Faza budynku sie automatycznie zmieni i nie bedziemy wstanie wziac questa nastepnego http://wotlk.openwow.com/quest=13266
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=13257
2. http://wotlk.openwow.com/quest=13266
3. filmik z youtube https://www.youtube.com/watch?v=cqvnd_1aleY
prosze obejrzec od 2:00

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by kovaq** [comment]
Pewnie wiesz, ze Battle of Undercity nie jest zrobione i jest to quest rozwiazanie zapobiegajace permamentnemu wpadaniu w zle fazowanie?

**Comment by Baggedmilk** [comment]
A skad mam takie rzeczy wiedziec? Zglaszam niedzialacy chain poprostu.

**Comment by Io36** [comment]
@kovaq Niech zostanie zgłoszenie może kiedyś naprawią.

**Comment by Mithras2801** [comment]
2 chainy jeszcze za czasów starego sunwella nie działały bo nie zostały poprawione cały chain był zgłaszany przeze mnie kiedyś ^^
