### ISSUE TITLE
[Quest] Ruthless Cunning (9927)

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#216]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest Ruthless Cunning (9927) jest po części zbugowany, ponieważ Warmaul Ogre Banner (25552) jest możliwy do użycia losowo czasami działa na mobach Kil'Sorrow a czasami nie, pojawia się wtedy komunikat 'Invalid Target'. 

**Obecne działanie**: Warmaul Ogre Banner (25552) posiada losowe działanie na mobach w Kil'Sorrow Fortress.

**Oczekiwane działanie**: Warmaul Ogre Banner (25552) powinien zawsze działać na zabitych mobach w Kil'Sorrow Fortress

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa Ruthless Cunning i polecieć do Kil'Sorrow Fortress, zabijać tam moby i próbować postawić banner. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9927/ruthless-cunning
2. http://www.wowhead.com/item=25552/warmaul-ogre-banner
3. "These banners can be placed on any dead Kil'sorrow mobs found in Kil'sorrow Fotress."

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
-2801, 6381, 96, 530

**EDIT:** #255 ten sam błąd.

**Comment by ellynd** [comment]
Quest Returning the Favor http://www.wowhead.com/quest=9931/returning-the-favor również ten sam błąd

**Comment by Shon-su** [comment]
poprawione
