### ISSUE TITLE
[Dual Spec] glyphy

### ISSUE THREAD

**Issue by Votiag** [RaphaelSunwell/Sunwell-BugTracker-SCv2#217]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  

**Obecne działanie**: w obecniej chwili nie jestem w stanie dac 2 tych samych glyphow do speca shadow jak i discipline gdyz wykrywa je jako ten sam
**Oczekiwane działanie**: kazdy spec ma osobna tabele glyphow i nie wplywaja one na siebie

**Co należy zrobić, aby odtworzyć ten błąd**:

1. zalozyc glyph do speca A i B
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Potwierdzam, przetestowane.

**Comment by xsitdev** [comment]
Glyph można spokojnie założyć, wystarczy przelogować postać w celu zapisu glyphu do odpowiedniego specu.
