### ISSUE TITLE
[MOVEMAPS] latające moby na outland

### ISSUE THREAD

**Issue by navaro19** [RaphaelSunwell/Sunwell-BugTracker-SCv2#219]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: moby gonią graczy bez względu na przeszkody

**Obecne działanie**: po zaagrowaniu moba w hellfire i oddaleniu się na fly mouncie mob goni nas biegnąc w powietrzu

**Oczekiwane działanie**: moby powinny nas namierzyć, ale stać na ziemi

**Co należy zrobić, aby odtworzyć ten błąd**:

1. podlecieć do jakiegokolwiek agresywnego moba na outland przy użyciu fly mounta
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Kougraa** [comment]
#206
