### ISSUE TITLE
[NPC]Farseer Eannu

### ISSUE THREAD

**Issue by Vaelevian** [RaphaelSunwell/Sunwell-BugTracker-SCv2#22]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: NPC powinien stać pod koordynatami (55.6, 28.8).

**Obecne działanie**: Brak NPC Farseer Eannu w Ironforge.

**Oczekiwane działanie**: NPC powinien się znajdować pod koordynatami (55.6, 28.8) W Ironforge.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się pod wskazane koordynaty.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=35073/farseer-eannu
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Ironforge (55.6, 28.8)

**Comment by Shon-su** [comment]
dodany dopiero w patchu 3.2
