### ISSUE TITLE
Ponowne otwarcie do zgłoszenia Chaptery I II III IV !!

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#220]
https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/116

zgłoszenie jest poprawne lecz źle zrozumiene. 
Questy te powinny być możliwe tylko 1 raz. Obecnie można je zrobić kilka razy.

**Comment by felmad** [comment]
Powinna być możliwość robienia tych zadań, bo jak zgubimy q item to jak wtedy zdobędziemy go ponownie?

**Comment by Kougraa** [comment]
Powinna być możliwość robienia tych questów w nieskończoność, bo jak zgubimy q item to nie będziemy mieli możliwośći zdobycia itemu ponownie - tak. Jeśli wykonamy quest na rozdziały [http://wotlk.openwow.com/quest=338] to powinno automatycznie zamknąć możliwość ponownego wykonywania questów na strony.
