### ISSUE TITLE
[SPELL] Stop Time (49838)

### ISSUE THREAD

**Issue by Tyrambugi** [RaphaelSunwell/Sunwell-BugTracker-SCv2#221]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Jest to zaklęcie dostępne pod przyciskiem 2, gdy latamy na Amber Drake w instancji Oculus. Opis spella mówi "Halts the passage of time, freezing all enemy dragons in place for 10 sec." przez co rozumiem, że trash, który składa się z humanoid i mechanical nie powinien byc stunowany.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Spell w tytule stunuje nie tylko smoki, ale tez wszystko co może zostać zestunowane, tyczy się to każdego trashu, który musimy zabić, aby przejść instancje.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Stop Time powinien stunować tylko smoki, które latają wokół oculusa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść do instancji Oculus.
2. Odebrać od npc amber drake i wsiąść na niego.
3. Użyć spella Stop Time przy jakimkolwiek trashu.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=49838
2. http://wotlk.openwow.com/npc=27755
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione
