### ISSUE TITLE
[NPC] 5615 - Wastewander Rogue (bug)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#222]
**Opis**: Jednostki chodzą sobie jedynie.

**Obecne działanie**: Idziemy na miejsce i jednostki chodzą widzialne 

**Oczekiwane działanie**: Te jednostki powinny chodzić w niewidzialności.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Iść na miejsce
2. Zobaczyć jednostki.

**Linki WoWHead/OpenWoW**:

1. Wastewander Rogue - http://wotlk.openwow.com/npc=5615
2. http://wowwiki.wikia.com/wiki/Wastewander_Rogue dodatkowo dropy są podane i szanse na nie

**Comment by Shon-su** [comment]
poprawione
