### ISSUE TITLE
[QUEST] Brothers in Death (DK)

### ISSUE THREAD

**Issue by ramciachciach** [RaphaelSunwell/Sunwell-BugTracker-SCv2#224]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Kluczowy quest DK. Warty 1 talent point i dalsze pójście w chain. MUST HAVE

**Obecne działanie**: Brak kluczowego moba dla DK -  Koltira Deathweaver. Nie respawnuje się.

**Oczekiwane działanie**: NPC powinien się znajdować w piwnicy w scarlet hold.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić DK.
2. Dojść do etapu Brothers in Arms. Zadanie brane w tawernie w New Avalon
3. Znaleźć trupa w piwnicy i z nim zagadać.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12725/brothers-in-death
2. http://www.wowhead.com/npc=28912/koltira-deathweaver

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 63.68

**Comment by ramciachciach** [comment]
Koniec końców udało mi się ukończyć to zadanie. NPC wiesza się walcząc po całym zamku. Dopiero jak pokona się wszystkie jednostki, znika i po jakichś 10 min respawnuje się tam gdzie powinien być.

**Comment by Mithras2801** [comment]
Tak jak kolega wyżej. NPC wiesza się i walczy z NPC u góry, a że dmg jednych i drugich jest mały to NPC nie padają i trwa to bardzo długo i często trzeba mu pomóc.
