### ISSUE TITLE
[SPELL][GLYPH]

### ISSUE THREAD

**Issue by Kimdzongil** [RaphaelSunwell/Sunwell-BugTracker-SCv2#226]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Glyph of ice armor**:

**Glyph nie podnosci o 50% resistow pelli Ice armor I Frost Armor, w spell booku pokazuje ze niby dziala, ale po uzyciu tych spelli resisty sa takie jakby glypha nie bylo**: TU WPISZ NA CZYM POLEGA PROBLEM

**Po uzyciu glyph of ice armor powinien podniesc o 50% resisty spella Ice Armor i Frost Armor**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Uzyc Glyph of ice armor
2. Uzyc spella Ice Armor
3. Porownac resisty przed i po uzyciu glypha

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Glyphy nie aktualizują tooltipu.
