### ISSUE TITLE
[Vendor][Recipe] Jewelcrafting [important!]

### ISSUE THREAD

**Issue by Triceps69** [RaphaelSunwell/Sunwell-BugTracker-SCv2#228]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Vendor jewelcrafting nie posiada recek na  PvP gemy uncommon.

**Obecne działanie**: w patchu 3.0.2 zostały dodane recipy na uncommon pvp gemy do vendora recek w Dalaran

**Oczekiwane działanie**: Vendor powinien mieć recki na uncommon PvP gemy, recki rare są dostepne na Wintergrasp

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do vendora http://www.wowhead.com/npc=28721/tiffany-cartier#sells:50-2
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=41560/design-stormy-chalcedony
2. http://www.wowhead.com/item=41569/design-shattered-dark-jade
3. http://www.wowhead.com/item=41566/design-resplendent-huge-citrine
4. http://www.wowhead.com/item=41563/design-willful-huge-citrine
5. http://www.wowhead.com/item=41565/design-lucent-huge-citrine
6. http://www.wowhead.com/item=41566/design-resplendent-huge-citrine
7. http://www.wowhead.com/item=41575/design-mysterious-shadow-crystal
8. http://www.wowhead.com/item=41570/design-radiant-dark-jade
9. http://www.wowhead.com/item=41571/design-turbid-dark-jade
10. http://www.wowhead.com/item=41572/design-steady-dark-jade
11. http://www.wowhead.com/item=41559/design-mystic-sun-crystal

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Triceps69** [comment]
Podbijam!! Prosta naprawa a bardzo ważna

**Comment by ThePuppetMaster** [comment]
Recki sprzedawane są obecnie przez Captain O'Neal (A) i Lady Palanseer (H), znalazłem sprzeczne informacje odnośnie tego, czy powinny być też sprzedawane w Dalaranie. Są dostępne, więc zostawiam jak jest.
