### ISSUE TITLE
[QUEST][NPC]Bride of the Embalmer

### ISSUE THREAD

**Issue by Vaelevian** [RaphaelSunwell/Sunwell-BugTracker-SCv2#23]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest polega na udaniu się do grobu Elizy na cmenatrzu w Duskwood, zabiciu jej i zdobyciu przedmiotu The Embalmer's Heart.

**Obecne działanie**: Nie można przywołać NPC Eliza.

**Oczekiwane działanie**: Po kliknięciu na grób powinna pojawić się NPC Eliza, po której zabiciu powinniśmy zdobyć The Embalmer's Heart.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa Bride of the Embalme.
2. Udać się pod koordynaty (28,30) w Duskwood.
3. Spróbować "otworzyć" nagrodek.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=253/deprecated-bride-of-the-embalmer
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
(28,30) w Duskwood

**Comment by ThePuppetMaster** [comment]
Już działa.
