### ISSUE TITLE
[Quest] Besieged!

### ISSUE THREAD

**Issue by pjootr93** [RaphaelSunwell/Sunwell-BugTracker-SCv2#230]
**Opis**: Nie zalicza zabicia mobów, prawdopodobnie dlatego, że pomagają w tym rozmieszczeni wszędzie przyjaźni NPC. 

**Obecne działanie**: Nie zalicza zabijania mobów Infernal Attacker

**Oczekiwane działanie**: Powinno zaliczać zabijanie mobów Infernal Attacker

**Co należy zrobić, aby odtworzyć ten błąd**:
j.w.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10595/besieged
2. http://wotlk.openwow.com/quest=10595

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 
-3198.797607, 2560.571777, 62.272324, 530

**Comment by Verthe** [comment]
q dziala poprawnie wiadomo ze jak dobijasz to nie zalicza , zabij 1 moba i poczekaj az spadnie nastepny i zrobisz spokojnie
