### ISSUE TITLE
[NPC][Quest] Fiora Longears

### ISSUE THREAD

**Issue by felmad** [RaphaelSunwell/Sunwell-BugTracker-SCv2#231]
**Opis**: Nie można oddać zadania o nazwie "Fiora Longears"

**Obecne działanie**: Nie można oddać zadania u NPC

**Oczekiwane działanie**: Powinno dać się oddać zadanie u NPC

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć zadanie "Fiora Longears"
2. Udać się z zadaniem do NPC

**Linki WoWHead/OpenWoW**:

1. https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/194
2. http://db.vanillagaming.org/?npc=4456

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 33.8, 42.4 (Auberdine, Darkshore)

**Comment by mrfifiak** [comment]
Dodałbym tag [QUEST]

**Comment by FrostyGM** [comment]
Potwierdzam, sprawdzane.

**Comment by Shon-su** [comment]
DELETE FROM `creature_questender` WHERE `quest` = 1132;
INSERT INTO `creature_questender` VALUES 
(4456, 1132);

**Comment by ThePuppetMaster** [comment]
Done
