### ISSUE TITLE
[QUEST] Gathering the reagents

### ISSUE THREAD

**Issue by racusznik** [RaphaelSunwell/Sunwell-BugTracker-SCv2#232]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Drop rate w queście jest zbugowany

**Obecne działanie**: Gracze mają problem z ukończeniem tego questa, gdyż przedmioty nie chcą wypadać. Oczywiście, trochę wypada, ale ja (i znajoma mi osoba) utknęłam na 3/4 i mimo, że biłam te moby ponad godzinę już nic więcej nie poleciało.

**Oczekiwane działanie**: Moby będą dropić przedmioty w sposób normalny.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Brak linków i kordów.
