### ISSUE TITLE
Vanish zle działa

### ISSUE THREAD

**Issue by kevery123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#233]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

[**Opis**:] Vanish jest przerywany przez wysłane pociski  mirror imagów i water elementala maga 

**Obecne działanie**: water elemental i mirror images maga po wysłaniu spella jakims jest frostbolt albo waterbolt nie moga byc zvanishowane nie wiem jak inne pety pewnie podobnie dzialaja

**Oczekiwane działanie**: powinna byc mozliwosc po wysłaniu tych spelli ( w trackcie lotu ) aby je zvanishowac bez dostania dmga i bez wywalenia z vanisha (stealtha )

**Co należy zrobić, aby odtworzyć ten błąd**:

1. dac duel magowi niech najpierwc water elemental albo mirrory wysla casta
2. w trakcie lotu casta sprobowac go zvanishowac
3. zobaczyc efekty = cast wywala z vanisha i stealtha 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Patch 1.1.0 (2004-11-07): Will now cancel spells in progress and missiles in flight if they are being cast at the vanished player.
