### ISSUE TITLE
[TALENT][SPELL] Brain Freeze + Improved Blizzard

### ISSUE THREAD

**Issue by leman1991** [RaphaelSunwell/Sunwell-BugTracker-SCv2#234]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Talent "Brain Freeze" frost maga powinien mieć szansę na proc po kazdym spellu mającym "chilling effect".
Talent "Improved Blizzard" dodaje "chilling effect" do blizzarda.

**Obecne działanie**: 
Mając talent "improved blizzard" i uzywając blizzarda nie proca talent "brain freeze"

**Oczekiwane działanie**: 
 Procanie "brain freeze" po uzyciu blizzarda [z talentem "improved blizzard" minimum 1 pkt] tak jak ma to miejsce np po uderzeniu frostboltem.
Sprawdzone na wielu serwerach.
Problem leży prawdopodobnie w samym talencie "brain freeze" bo z "improved blizzard" proca "fingers of frost", ktory ma takie same wymagania do aktywowania.

**Comment by ThePuppetMaster** [comment]
Potwierdzam.

**Comment by Nuy** [comment]
FoF nie ma takich samych wymagań do aktywowania co Brain Feeze. FoF aktywuje się z każdego "chill" efektu a Brain Freeze tylko z takich, które zadają obrażenia, czyli FoF może wejść ze spowolnienia Frost/Ice Armor a Brain Freeze nie.

Właśnie sprawdziłem i talent normalnie wchodzi podczas Blizzard'a, dlatego NIE potwierdzam i moim zdaniem zgłoszenie jest niepoprawne. Zaznaczam, że miałem 1/3 Brain Freeze, więc może problem leży w randze talentu, chociaż wątpię.

**Comment by ThePuppetMaster** [comment]
1/3 Imp.Blizz i 3/3 Brain Freeze nie wbija.

**Comment by Nuy** [comment]
Wstawiam poszczególne rangi tych talentów.

Fingers of Frost:
http://wotlk.openwow.com/spell=11185
http://wotlk.openwow.com/spell=12487
http://wotlk.openwow.com/spell=12488

Brain Freeze:
http://wotlk.openwow.com/spell=44546
http://wotlk.openwow.com/spell=44548
http://wotlk.openwow.com/spell=44549

**Comment by ThePuppetMaster** [comment]
Done. Fix pojawi się jak wyjdzie z PTRa.
