### ISSUE TITLE
[QUEST] Battle of Hillsbrad (7) NPC - Brak NPC

### ISSUE THREAD

**Issue by halbazzer** [RaphaelSunwell/Sunwell-BugTracker-SCv2#235]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak NPC "Bragor Bloodfist" (Undercity: 56.2, 92,2) odbierającego quest (przez chwile był NPC ale nie odbierał questa)

**Obecne działanie**: brak - nie ma NPC, przez chwilę był ale nie odbierał q - dialog kończył się na standardowym tekscie NPC'a i "Goodbye"

**Oczekiwane działanie**: NPC powinien odebrać quest i wydać "nagrody" - itemy, reputację, xp i ewentulanie gold

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ukończyć chain od NPC "High Executor Darthalia" "Battle of Hillsbrad" 1-6 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. https://wotlk-twinhead.twinstar.cz/?quest=14351
2. http://wowwiki.wikia.com/wiki/Quest:Battle_of_Hillsbrad_%287%29
3. http://www.wowhead.com/quest=550/deprecated-battle-of-hillsbrad

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Undercity 56.2, 92.2

**Comment by Kougraa** [comment]
#69
