### ISSUE TITLE
[Item/Spell] Glyph of Quick Decay

### ISSUE THREAD

**Issue by Shatterx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#236]
Opis: Nie mozna nauczyc sie glypha Quick Decay u trainera, jest to jeden z najwazniejszych glyphow u locka.

Obecne działanie: Brak mozliwosci nauczenia sie glypha u trainera.

Oczekiwane działanie: Możliwosć nauczenia sie glypha u trainera.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Nauczyc sie inskrypcji
2. Pojsc do trainera inskrypcji w dalaran
3. 

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/item=50077
2. http://wotlk.openwow.com/spell=71102
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Dalaran

**Comment by KamaN442** [comment]
[http://wowwiki.wikia.com/wiki/Glyph_of_Quick_Decay](url)

"Patch 3.3.0 (08-Dec-2009): Added."

**Comment by mordeusz** [comment]
Zrobią updatem, będą recki. Zgłoszenie jest w zamkniętych, zgłoszenie 181. Co do patcha to jest to na tej samej zasadzie co book of glyph mastery, skoro booki dodali to ta recka jak i 2 pozostałe od vendora rowniez bedą dodane
