### ISSUE TITLE
[QUEST] Bug Withebark's Memory

### ISSUE THREAD

**Issue by Filipm95** [RaphaelSunwell/Sunwell-BugTracker-SCv2#237]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Brak NPC, u którego oddaje się questa

**Oczekiwane działanie**: Powinien być duch witherbarka, u którego oddaje się naszyjnik, który ma się w plecaku.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Należy postawić NPC w miejscu, w którym powinien stać
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=10166
2. http://www.wowhead.com/quest=10166/whitebarks-memory
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 37, 86, Eversong Woods

<a href="http://pl.tinypic.com?ref=2h3r4he" target="_blank"><img src="http://i63.tinypic.com/2h3r4he.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ThePuppetMaster** [comment]
Działa poprawnie.
