### ISSUE TITLE
[Quest] Frankly, It Makes No Sense...

### ISSUE THREAD

**Issue by pjootr93** [RaphaelSunwell/Sunwell-BugTracker-SCv2#238]
**Opis**: Klikam panel kontrolny, moja postać castuje, dostaję buffa infromującego, że kontroluje skorpiona, ale dalej steruje tylko swoją postacią.

**Obecne działanie**: Nie można sterować questowym skorpionem.

**Oczekiwane działanie**: Możliwość kontrolowania questowego skorpiona

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Kliknąć panel kontrolny

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10672/frankly-it-makes-no-sense
2. http://wotlk.openwow.com/quest=10672
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 
-3421.416016, 886.614197, 27.631849, 530

**Comment by kovaq** [comment]
https://youtu.be/2R5azlLrKb4
Sama kontrola skorpiona i tagowanie diametrodonow dziala, aczkolwiek mozna tagowac tyle razy ile leci pierwszy wystrzelony "tag" (szybkie palce i dobra odleglosc to 3-4, ale nawet 2 z bliska to wciaz 2 a nie 1.)
