### ISSUE TITLE
[Quest] Valduran the Stormborn(Part 1 of 2)

### ISSUE THREAD

**Issue by bartekmad** [RaphaelSunwell/Sunwell-BugTracker-SCv2#239]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po użyciu quest itemku nic się nie dzieje

**Obecne działanie**: Po użyciu quest itemku nic się nie dzieje

**Oczekiwane działanie**: Po użyciu quest itemku powinny przybyć posiłki i zacząć się walka z npc

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest
2. Użyć quest itemku
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12984/valduran-the-stormborn
2. https://www.youtube.com/watch?v=3VcxYiB-T-A
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/6CIa92e.jpg

**Comment by ThePuppetMaster** [comment]
Posiłki przybywają, jednak NPC nie przerywa swojej animacji, a po zakończeniu dialogów posiłki znikają.

**Comment by Shon-su** [comment]
23.02.2017 działa ok
