### ISSUE TITLE
Wpadanie pod tekstury

### ISSUE THREAD

**Issue by t0m3kkw** [RaphaelSunwell/Sunwell-BugTracker-SCv2#240]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Wpadanie pod tekstury
**Obecne działanie**: Gdy chodzę po mapie, lub podczas bicia mobków wpadam pod tekstury, nawet nie ruszając się. 

**Oczekiwane działanie**:  Nie powinno się wpadać pod tekstury :)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=6023 - robiłem np ten quest podczas wyłapania błędu
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:  Eastern Kingdoms, Western Plaguelands, Kordy: 54.25. i okolice.
Chodziłem póki co wzdłuż drogi i obok niej gdzie stoją skupiska mobków.

**Comment by ThePuppetMaster** [comment]
Nie udało mi się odtworzyć błędu ani na prywatnej postaci, ani na GMie.
