### ISSUE TITLE
[STRONA][VOTE] Słaba weryfikacja

### ISSUE THREAD

**Issue by tellekx3** [RaphaelSunwell/Sunwell-BugTracker-SCv2#241]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: strona zalicza głos jako oddany, gdy klikniemy w link "ooddaj glos" bez weryfikacji tego, czy oddalismy glos na stronie zewnetrznej. Powoduje to, ze gracz zostaje nagrodzony a serwer nie ma z tego zadnej korzysci, poniewaz glos nie zostal tak naprawde oddany.

**Oczekiwane działanie**: glos powinien byc uznawany za oddany dopiero, gdy faktycznie oddamy go na stronie zewnetrznej.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Skorzystać z API (o ile owe strony zewnetrzne takie udostepniaja) w celu poprawienia weryfikacji glosowania.

**Comment by Horpah** [comment]
Potwierdzam. Nieuczciwi gracze mogą sobie nawet zrobić skrypt który co 12 godzin sam kliknie te dwa przyciski głosowania i bez wysiłku (i bez zysku dla serwera) nabijają sobie VP.

**Comment by Shon-su** [comment]
System vote zostanie za niedługo zastąpiony czymś innym, więc myślę że można zamknąć.
