### ISSUE TITLE
[Quest] Orabus the Helmsman.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#244]
**Opis**: Quest polega na użyciu qitemu i zabiciu npc wyskakujacych ze statku.

**Obecne działanie**: Moby nie atakują automatycznie gracza. Stoją w miejscu. Z chwilą zabicia jednego, wyskakuje drugi, który jest w bezruchu; nie targetuje przeciwnika. Gracz ma możliwość regania do woli pomiedzy starciami z mobami.
https://youtu.be/N4Bd_q2ou28

**Oczekiwane działanie**: Moby wyskakujace ze statku powinny z automatu nabijac combat graczowi.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Odnaleźć miejsce.
3. Użyć quest itemu.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=11661/orabus-the-helmsman
2. [Quest item] http://www.wowhead.com/item=34844/horn-of-the-ancient-mariner
3. [NPC] http://www.wowhead.com/npc=32576/orabus-the-helmsman
http://www.wowhead.com/npc=32577/kvaldir-crewman

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
W nagraniu.

**Comment by Shon-su** [comment]
poprawione
