### ISSUE TITLE
[Quest] Bring 'Em Back Alive.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#245]
**Opis**: Quest polega na odnalezieniu kodo i doprowadzeniu go do wyznaczonego miejsca. 

**Obecne działanie**: Nie na każde kodo gracz ma możliwość wejścia.
https://youtu.be/iho4z85Qat4

**Oczekiwane działanie**: Gracz powinien mieć możliwość wejścia na każde kodo.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Odnaleźć kodo.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=11690/bring-em-back-alive
2. [NPC] http://www.wowhead.com/npc=25596/infected-kodo-beast

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
