### ISSUE TITLE
[Quest] Abduction.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#246]
**Opis**: Quest polega na zlapaniu NPC za pomoca qitemu oraz przeprowadzeniu go w wyznaczone miejsce. 

**Obecne działanie**: Quest jest zaliczany z chwilą złapania NPC.
https://youtu.be/Rxp3_-eumHE

**Oczekiwane działanie**: Quest powinien być zaliczony w chwili, gdy gracz przeprowadzi w wyznaczone miejsce zlapanego NPC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Zbic hp NPC do 5%.
3. Użyć qitemu.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=11590/abduction
2. [NPC] http://www.wowhead.com/npc=25474/captured-beryl-sorcerer
3. [Quest item] http://www.wowhead.com/item=34691/arcane-binder

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione nie dograne jeszcze
