### ISSUE TITLE
[Vendor][Recipe] Alchemy [Important]

### ISSUE THREAD

**Issue by rosenoo** [RaphaelSunwell/Sunwell-BugTracker-SCv2#249]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: brak recki u npc. quest "master of Transmution"

**Oczekiwane działanie**: 

**Co należy zrobić, aby odtworzyć ten błąd**: ....

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**: http://www.wowhead.com/item=23574/recipe-transmute-primal-might#sold-by

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by mordeusz** [comment]
Recka jest u NPCa widocznie ktoś ją wykupił przed tobą.
