### ISSUE TITLE
[QUEST] A map to to where

### ISSUE THREAD

**Issue by Nimush** [RaphaelSunwell/Sunwell-BugTracker-SCv2#25]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: [QUEST] A map to to where

**Obecne działanie**: Po znalezieniu księgi w pawilonie Bloodmyst Isle 61.2 , 41.8
nic się nie dzieje.  Księga odpowiada "Greetings" i nie prowadzi do dalszej części questa.

**Oczekiwane działanie**:  Księga powinna umożliwić kontynuację questa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9550/a-map-to-where

**Comment by ThePuppetMaster** [comment]
Powinno już działać.
