### ISSUE TITLE
[NPC] Ironhand Guardian.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#250]
**Obecne działanie**:  Na ten moment w instancji Blackrock Depths, jedynie ostatnie dwa Guardiany zadają dmg.
https://www.youtube.com/watch?v=c80jDo_K8EE

**Oczekiwane działanie**:  Każdy Ironhand Guardian powinien zadawać  288 to 432 Fire damage przy użyciu spella.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć Guardiany w instancji.
2. Przejść pomiedzy nimi.

**Linki WoWHead/OpenWoW**:

1. [NPC] http://www.wowhead.com/npc=8982/ironhand-guardian
2. [Spell] http://www.wowhead.com/spell=15529/gout-of-flame
3. [Instancja] http://www.wowhead.com/blackrock-depths

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
x

**Comment by Shon-su** [comment]
#489
