### ISSUE TITLE
[Spell] Gbom, Gbow i Gbok.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#251]
**Opis**: Gbom, Gbow i Gbok dla całego party.
https://www.youtube.com/watch?v=c80jDo_K8EE

**Obecne działanie**: W chwili, gdy paladyn użyje spella na pecie huntera, dk czy warlocka, całe party go dostaje.

**Oczekiwane działanie**: Spella powinien dostać jedynie pet.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Być paladynem.
2. Mieć party przynajmniej z jedna osobą, która posiada peta.
3. Użyć spella na pecie.

**Linki WoWHead/OpenWoW**:

1. [Spell] http://www.wowhead.com/spell=203528/greater-blessing-of-might
2. http://www.wowhead.com/spell=203539/greater-blessing-of-wisdom
3. http://www.wowhead.com/spell=203538/greater-blessing-of-kings

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy.

**Comment by ta55el** [comment]
potwierdzam

**Comment by Triceps69** [comment]
Tak samo jak paladyn daje sobie buffy, pety też go dostają.
