### ISSUE TITLE
Friends List, Guild Member Alert - brak powiadomień!

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#252]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Friends List, Guild Member Alert i brak pojawiających się powiadomień!

**Obecne działanie**: Jeżeli posiadamy kogoś dodanego do naszej 'Friends List' to jeżeli on się zaloguje/wyloguje to nie dostajemy powiadomienia '[X] has come online.' i 'X has gone offline.'. Jeżeli osoba X jest w naszej gildii oraz mamy ją dodaną do naszej listy znajomych to również nie otrzymujemy żadnych powiadomień o wejściu/wyjściu (Guild Member Alert włączone). Podsumowując bug polega na tym, że dla osób na liście znajomych nie są pokazywane powiadomienia przy wejściu/wyjściu. Dla osób, które są w naszej gildii i jednocześnie na liście znajomych również te powiadomienia nie są pokazywane.

**Oczekiwane działanie**: Powiadomienia o wejściu/wyjściu powinni pokazywać się ZAWSZE jeżeli osoba X jest na naszej friend liście. Jeżeli mamy wyłączone 'Guild Member Alert', ale osoba X jest na naszej friend liście to również powinniśmy dostać powiadomienie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać kogoś do 'Friends List' i sprawdzić czy powiadomienia działają.

**Comment by ThePuppetMaster** [comment]
#84
