### ISSUE TITLE
Warlock destro, conflagrate bug

### ISSUE THREAD

**Issue by Randomdog** [RaphaelSunwell/Sunwell-BugTracker-SCv2#253]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Conflagrate jest kluczowym spellem u locka destro pve, jak i pvp. Obecnie jest jednak bugged

**Obecne działanie**: Po uzyciu immolate moge uzyc confle dopiero jakies pol sec pozniej (nawet nie zaswieca sie od razu ikonka, tak jak powinna)

**Oczekiwane działanie**: Po immolate, confla nie powinna miec zadnego gcd i powinna byc do uzycia od razu. Tak przynajmniej dzialalo to kiedys na sunwellu i tak to dziala obecnie na arena tournament i nie tylko.

**Co należy zrobić, aby odtworzyć ten błąd**: Dac mozliwosc instantowego uzycia confli po immolate.

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=17962
2. http://www.wowhead.com/spell=17962/conflagrate
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by mordeusz** [comment]
Działa prawidłowo, na starym sunwellu również był delay około 0,5 s i tak powinno być. Nie wiem skąd masz takie informacje, ale nawet nie dałeś żadnego dowodu, że tak powinno być. AT to nie jest dobry przykład, to że coś działa na innym serwerze inaczej to nie znaczy, że działa poprawnie.
