### ISSUE TITLE
[REPUTACJA] Violet Hold

### ISSUE THREAD

**Issue by Kokaina** [RaphaelSunwell/Sunwell-BugTracker-SCv2#254]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Bug polega na tym, że nie leci reputacja z bossów oraz mobów na instancji Violet Hold w wersji normal oraz heroic. Nieistotne czy mamy założony tabard do jakiejś frakcji czy nie - poziom reputacji stoi w miejscu. Jeśli gracz nie ma założonego tabardu wówczas reputacja leci do frakcji Alliance Vanguard (ally) lub Horde Expedition (horde). W wersji Heroic mob powinien dawać 12 punktów reputacji, natomiast boss 250 punktów reputacji. W wersji normal boss daje 50 reputacji zaś moby 5 punktów.

**Obecne działanie**: Nie leci reputacja za zabijanie bossów oraz trashy na Violet Hold.

**Oczekiwane działanie**: Powinna lecieć reputacja z mobów oraz bossów na Violet Holdzie do frakcji zależnej od założonego tabardu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść na Violet Hold.
2. Zabijać trashe oraz bossy.
3. Zorientować się, że poziom reputacji się nie zmienił.

**Linki WoWHead/OpenWoW**:

1. Lista mobów na Violet Hold: http://www.wowhead.com/the-violet-hold#npcs
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://s11.postimg.org/rphazer5f/Wo_WScrn_Shot_120516_000254.jpg

**Comment by Kokaina** [comment]
bump

**Comment by dreamwalkerx1** [comment]
@Shon-su @xsitdev 
zgłoszone na bt od 5 grudnia i wciąż niepoprawione, jeżeli wylosuje nam VH przez rhc to ludzie czasami wychodzą, bo "repa mi nie leci" wypadałoby poprawić ;-)

**Comment by Shon-su** [comment]
Ok, przez święta przysiądę i spróbuję znaleźć co tam się zepsuło :)

**Comment by dreamwalkerx1** [comment]
super :)

**Comment by Shon-su** [comment]
poprawiłem. Jak zostatnie dograne na serwer ( changelog ) to prosiłbym o zerknięcie czy wszystko pasuje. Wydaje mi się że niczego nie pominąłem, ale może jakiś mobek mi umknął.
