### ISSUE TITLE
[Quest] Returning the Favor (9931)

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#255]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest Returning the Favor (9931) jest po części zbugowany, ponieważ Kil'sorrow Banner (25555) jest możliwy do użycia losowo czasami działa na mobach Warmaul Shaman/Reaver a czasami nie, pojawia się wtedy komunikat 'Invalid Target'. 

**Obecne działanie**: Kil'sorrow Banner (25555) posiada losowe działanie na mobach w Kil'Sorrow Fortress.

**Oczekiwane działanie**: Kil'sorrow Banner (25555) powinien zawsze działać na zabitych mobach w Laughing Skull Ruins.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa Returning the Favor i polecieć do Laughing Skull Ruins, zabijać tam moby i próbować postawić banner. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9931/returning-the-favor
2. http://www.wowhead.com/item=25555/kilsorrow-banner

**Comment by Shon-su** [comment]
a nie jest czasem tak że nie działa jak inny baner masz w pobliżu? Bo z tego co widzę jest ten sam error wrzucony i jak próbujesz użyć na złym targecie i jak w pobliżu jest inny banner postawiony.
