### ISSUE TITLE
[Armory] Brak talentów postaci

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#256]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Obecne działanie**: Na stronie jeżeli wejdziemy w armory i chcemy podejrzeć talenty danej postaci to drzewko talentów ma status 'Undetermined' mimo tego, że postać ma pełny pakiet talentów.

**Oczekiwane działanie**: Powinny być wyświetlane wszystkie rozdane talenty oglądanej postaci.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść na armory i znaleźć interesującą nas postać.

**Linki WoWHead/OpenWoW**:

1. http://sunwell.pl/character/1/2064

**Comment by ThePuppetMaster** [comment]
#56
