### ISSUE TITLE
Enchant - crusader

### ISSUE THREAD

**Issue by Cichutka** [RaphaelSunwell/Sunwell-BugTracker-SCv2#258]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Enchant odpala sie bardzo dziwnie, dla przykladu, przez 3min nie odpala sie ani razu, a nastepnie odpala sie 3 razy pod rzad, np Odpala sie pierwszy raz, po 5 sekundach trwania odpala sie po raz kolejny i po kolejnych 2 sekundach odpala sie ponownie, po czym znowu przez kolejne 3minuty nie odpala sie wcale, Ta czestotliwosc odpalania sie po 3 razy czesto sie powtarza aczkolwiek nie zawsze tak jest. Zdarzaja sie pojedyczne odpalenia rowniez.

**Obecne działanie**: Dziwna czestotliwosc procowania enchantu.

**Oczekiwane działanie**: Enchant powinien czesciej odpalac się pojedynczo i duzo rzadziej dwa lub wiecej raza pod rzad.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Powinno to byc latwe do sprawdzenia na kukle, 5min auto atakow ze zenchantowania bronia najlepiej klasa z dwoma bronmi i ta specyficzna schematycznosc powinna sie pojawic.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Lebiedz** [comment]
Prawdopodobnie coś jest nie tak nie z samym enchantem, ale mechaniką RNG, ponieważ osobiście zauważyłem nadzwyczaj częste serie parry/dodge/miss w trakcie walk. Zdarza się nie raz mieć kilka nietrafionych ataków pod rząd, co biorąc pod uwagę około 5-6% szansy na dodge i 10-12% na parry przy 0 expertise w trakcie lvlowania jest statystycznie mało prawdopodobne.

**Comment by Triceps69** [comment]
Podobnie jest z trinketami, niby ICD 45 sekund, a wcale to tak nie wygląda. Warto się temu przyjrzeć.

**Comment by ThePuppetMaster** [comment]
Jeżeli jest problem z RNG to sprawa jest poważna. Proszę wszystkich zainteresowanych tematem o dodatkowe testy i jakąś dokumentacje. Z góry dziękuję za waszą prace.

**Comment by Danieloses** [comment]
Właściwie jakby się nad tym zastanowić też miałem takie dziwne akcje, że nie missuje absolutnie nic i nagle 5 missów pod rząd na powiedzmy zielonego moba, którego raczej powinienem trafiać.

**Comment by kovaq** [comment]
Enchant o nazwie Crusader nie ma czasu odnowienia. Jest aktywowany czysto chance on hit co skutkuje ze raz moze sie odpalic raz na 2 minuty, a zdarzylo sie, ze aktywowalo sie jedno po drugim uderzeniu poprawiajac 13 sekund buffa na swieze 15. TO jest logiczne, opis buffa mowi o jasno: "OFTEN heal and buff..."
Dodatkowo ench ma notke, ze dla graczy powyzej 60lvlu aktywuje sie rzadziej - nie odczulem tego, wrecz przeciwnie, bylbym zadowolony, gdyby np berserk czy mongoose odpalaly mi sie tak na raidzie. I tu wlasnie widze problem, ench nie skaluje sie z lvlem, dajac zawsze wyjsciowa - wieksza - szanse na buffka. 
Udalo mi sie zlapac GMa, ktory zmodyfikowal mi lvl na poziom 59 (ponizej 61, bo tak mowi enchant) - po testach na 80tym postanowilem porownac sobie testy i na tym lvlu. Ku mojemu rozczarowaniu... buff ponizej 60 lvlu wpada zenujaco rzadko. Wyglada to tak, jakby statystyki te byly zamienione, w zupelnie nielogiczny dla mnie sposob.

Zaobserwowalem wspomniane zmiany buffka 3 na raz - dlugo nic, ale nie jest to niczym podejrzanym, przynajmniej wedlug mnie.

http://wotlk.openwow.com/item=38873
http://wotlk.openwow.com/spell=20034

Testy prowadzone 15:11-15:46, na hunterze ze stavem 2h. Powod? Latwiej wylapac kazdy melee swing, anizeli na full odpalonym rogalu 0,6 / 0,44 ;)

**Comment by Shon-su** [comment]
krótko mówiąc zgłoszenie jest inwalidą jeśli dobrze rozumiem
