### ISSUE TITLE
[PROFESJA][ITEM]Spellweave, Moonshroud, Ebonweave

### ISSUE THREAD

**Issue by Nuy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#259]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie ma CD na te przedmioty z tailo a na aktualnym contencie powinno być. Jest CD na Titansteel, ale do tailo tych CD coś już nie wprowadziliście. CD te zostały zdjęte w patchu 3.3.3 zarówno Titansteel jak i tych rzadkich clothów z tailo. Oprócz tego została wtedy też zdjęta wymagana lokacja do stworzenia tych przedmiotów a na aktualnym contencie na Sunwellu powinna być wymagana. Dodatkowo po stworzeniu danego clotha powinniśmy otrzymywać buffa w zależności od tego jakiego clotha stworzyliśmy.

**Obecne działanie**: Brak CD na Spellweave, Moonshroud i Ebonweave przez co można ich robić masę jednego dnia.

**Oczekiwane działanie**: Powinno być CD po zrobieniu tych clothów i poszczególne clothy powinny mieć przypisane lokacje, w których można je zrobić.

WYMAGANE LOKACJE:

Spellweave - Azure Dragonshrine w Dragonblight
Moonshroud - Emerald Dragonshire w Dragonblight
Ebonweave - Obsidian Dragonshire w Dragonblight

BUFFY PO STWORZENIU: 

Spellweave - http://wowwiki.wikia.com/wiki/Nexus_Residue
Moonshroud - http://wowwiki.wikia.com/wiki/Moonshroud_Residue
Ebonweave - http://wowwiki.wikia.com/wiki/Residue_of_Darkness

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić Spellweave/Moonshroud/Ebonweave.
2. Zobaczyć, że ni ma CD.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Spellweave - "Patch 3.3.3 (2010-03-23): Creating Spellweave no longer has a cooldown or location requirement, but also no longer provides the Nexus Residue buff on creation."
2. http://www.wowhead.com/item=41593/ebonweave
3. http://www.wowhead.com/item=41595/spellweave
4. http://www.wowhead.com/item=41594/moonshroud
5. http://wotlk.openwow.com/spell=59675
6. http://wotlk.openwow.com/spell=59674
7. http://wotlk.openwow.com/spell=59676

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 

EbonWeave @ 37,32
SpellWeave @ 55,65
MoonShroud @ 64,73

**Comment by ThePuppetMaster** [comment]
Z racji, że mining ma CD na Titansteel, dodaje critical. To powinno zostać wyrównane z innymi profkami ASAP.

**Comment by Triceps69** [comment]
Teraz Ci co nie zdążyli narobić bedą ostro poszkodowani :/

**Comment by ThePuppetMaster** [comment]
Pomyślimy jak to zrobić, żeby było sprawiedliwie.

**Comment by Nuy** [comment]
Z tego co widzę nie ma CD dalej, ale lokacje już działają. Nie pokazuje CD przy przedmiocie tak jak pokazuje przy Titansteel.

**Comment by Nuy** [comment]
Nie dostaje się buffów przy stworzeniu.

**Comment by ThePuppetMaster** [comment]
Linki do buffów.

**Comment by Nuy** [comment]
Są.

**Comment by ThePuppetMaster** [comment]
Buffy do dodania.
