### ISSUE TITLE
[QUEST] Iron Rune Constructs and You: The Bluff

### ISSUE THREAD

**Issue by Argonnath** [RaphaelSunwell/Sunwell-BugTracker-SCv2#260]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:[QUEST] Iron Rune Constructs and You: The Bluff jest zbugowany. Po wejściu na dywan krasnolud powinien się zacząć drzeć a my powinniśmy go uspokoić testowanym skillem robota. Nic takiego się niestety nie dzieje.

**Obecne działanie**: W momencie kiedy w robocie mamy wejść na dywan krasnolud powinien się odezwać a my wtedy użyć testowanej umiejętności robota. Po wejściu na dywan krasnolud się nie odzywa, używanie na nim umiejętności nie kończy questa.

**Oczekiwane działanie**: Wchodzimy robotem na dywan. Krasnolud drze się. że nie wolno. Używamy skilla robota i kończymy quest.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Jest to któryś tam quest z chaina. Rozpoczynamy quest Iron Rune Constructs and You: The Bluff.
2. Wchodzimy na dywan.
3. Nic sie nie dzieje nie możemy zakończyć questa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11491/iron-rune-constructs-and-you-the-bluff
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:75.0 65.4

**Comment by Shon-su** [comment]
13.02.2017 
działa ok
