### ISSUE TITLE
Rain of Fire i Backdraft locka destro

### ISSUE THREAD

**Issue by Randomdog** [RaphaelSunwell/Sunwell-BugTracker-SCv2#261]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Backdraft jest to spell locka, ktory przyspiesza casta i gcd na kolejne 3 skille z drzewka destro.

**Obecne działanie**: Problem polega na tym, ze backdraft nie reaguje na spell Rain of Fire (nie przyspiesza casta, ani 3 stacki backdraftu nie schodza podczas uzycia RoF)

**Oczekiwane działanie**: Backdraft powinien reagowac rowniez na Rain of Fire, gdyz jest to spell destruction

**Linki WoWHead/OpenWoW**:

1.  http://wotlk.openwow.com/spell=47260

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Cast to słowo klucz. Zamykam do przedstawienia dowodów.
