### ISSUE TITLE
[NPC] Alliance Conscript

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#264]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
NPC [http://www.wowhead.com/npc=27564/alliance-conscript](http://www.wowhead.com/npc=27564/alliance-conscript) nie atakuje wrogów mimo tego, że wrogowie atakują jego.
**Obecne działanie**: 
[http://i.imgur.com/atczxVV.jpg](http://i.imgur.com/atczxVV.jpg)
**Oczekiwane działanie**: 
NPC powinny walczyć.

**Comment by Shon-su** [comment]
na testowym wszystkie ładnie się biją. Zamykam.
