### ISSUE TITLE
[NPC] Strażnicy w miastach, Truesight Vision

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#265]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W miastach oprócz zwykłych strażników i elitarnych strażników broniących lidera miasta znajdują się także po dwie specjalne jednostki dla Stormwind są to Officer Brady oraz Officer Jaxon. 

**Obecne działanie**: Obecnie każdy "zwyczajny" strażnik w stormwind więc też zapewne w innych miastach (nie sprawdzałem) posiada tzw. Truesight tzn. nad jego głową widnieje symbol oka i jest on w stanie wykrywać wszystkie niewidzialne jednostki. Officer Jaxon i Officer Brady nie posiadają Truesight.

**Oczekiwane działanie**: Zwyczajni strażnicy nie powinni posiadać Truesight, do wykrywania niewidzialnych jednostek zostali zaprojektowani w wypadku Stormwind Officer Brady i Officer Jaxon, którzy patrolują rynek i okolice czyli te bardziej zaludnione części miasta. W wypadku Sunwella działa to na odwrót, zwykli strażnicy posiadają Truesight natomiast Officerowie nie. W innych miastach są to inne npc, "Scout's" w Orgrimmar czy też "Thief Catcher's" w Ironforge - nawet sama nazwa wskazuje na cel istnienia tych npc. Na końcu dodam, że na starym Sunwellu działało to poprawnie, lecz pod koniec jakiś newcomer z cataclysmu (gdzie każdy strażnik już posiadał truesight) napisał report, a starzy admini dali się nabrać :P.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odpalić stealth w stolicach i zobaczyć, które jednostki posiadają truesight vision.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=14423/officer-jaxon
2. http://www.wowhead.com/npc=14439/officer-brady
3. http://www.wowhead.com/npc=68/stormwind-city-guard

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by kovaq** [comment]
Zgadzam sie z przeznaczeniem "jednostek specjalnych", natomiast nie znalazlem nic co by wskazywalo na jednoznaczne potwierdzenie, ze zwykli straznicy nie powinni nas widziec. Wlasnie spotykalem komentarze, ktore glownie sugerowaly, ze ludzie sa przyzwyczajeni do tego, ze straznik ich wykrywa, ale nie podoba im sie ze np na vanishu ich klepie wciaz. (to akurat normalne). Dodatkowo jak juz o stormwind rozmawiamy to wydaje mi sie ze royal guardy u Vrynna (http://db.vanillagaming.org/?npc=1756) tez powinny byc ujednolicone z normalnymi straznikami (imo truesight on) oraz General Marcus Jonathan (http://db.vanillagaming.org/?npc=466) na wejsciu do miasta tez powinien byc traktowany jako jednostka specjalna.

**Comment by Shon-su** [comment]
poprawione nie dograne
