### ISSUE TITLE
[LOCATION] Icecrown, Argent Vanguard i bliskie okolice

### ISSUE THREAD

**Issue by FrostyGM** [RaphaelSunwell/Sunwell-BugTracker-SCv2#266]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 

**Obecne działanie**: Poruszając się po tej lokacji w pewnych momentach można wpaść w "niewidzialne pudełko" postać biega w miejscu i może się tylko kręcić wokół własnej osi. Są to randomowe miejsca w w/w lokacji. (Pomaga restart gry, ew. opróżnienie folderu cache).

**Oczekiwane działanie**: Powinno móc się swobodnie poruszać po tej lokacji. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do tej lokacji i pokręcić po okolicy. Najszybciej wpaść w to mniej więcej przy coordach 83, 71.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
X: 6427.168457 Y:213.010193 Z:401.155426 Map: 1 VMap: 1 MMap: 1931726428

**Comment by kovaq** [comment]
Jedyny block box jaki tam widze to centralne wejscie na pochodnie. Kazda pochodnia w icecrown (w sumie wiekszosc pochodni, latarni i plotkow w wowie) powoduje block w momencie, gdy wbiegasz centralnie na nia. Widzisz te pochodnie? Jezeli nie, proponuje zmienic wowa, z ktorego korzystasz, bo to moze sie wiazac z brakiem innych tekstur.
