### ISSUE TITLE
Goniące mobki w chmurach jak ja za moimi marzeniami ;/

### ISSUE THREAD

**Issue by Itashii** [RaphaelSunwell/Sunwell-BugTracker-SCv2#267]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: lewitujące moby w outland ( goniące)

**Obecne działanie**: no mobki leca za graczem, kiedy on znajduje sie w powietrzu i biją go też w powietrzu

**Oczekiwane działanie**: no powinny stanąc pod nim centralnie na ziemii jakiejs

**Co należy zrobić, aby odtworzyć ten błąd**: 

1.  nalezy miec fly mounta
2. umiec latac po out
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=tzjV1hcaDH4
2. https://www.youtube.com/watch?v=g0JPFnMfXVQ
To są moje autorskie filmiki nagrywane

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

wszystkie moby w out ktore zdolne są gonić

nagrałem tylko w dwóch lokacjach filmiki, ale pewno sa we wszystkich krainach na out

zangarmarsh
helfire peninsula
terokkar forest
shadowmoon
blade's edge mountain
netherstorm
nagrand

**Comment by Kougraa** [comment]
Duplikat. #219

**Comment by Kougraa** [comment]
Duplikat. #206

**Comment by Itashii** [comment]
rozumiem, nie dopatrzylem.
