### ISSUE TITLE
[quest] Missing scout

### ISSUE THREAD

**Issue by Bukaman** [RaphaelSunwell/Sunwell-BugTracker-SCv2#268]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Należy odnaleźć zaginionego scouta
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Po przybyciu do miejsca w którym powinien być i włączeniu /target [name] odkryłem że siedzi w górze pod lodem... nijak sie dostać pod te textury
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12864/missing-scouts
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
NPC leży koło harpii.
