### ISSUE TITLE
[FORGE] Stormwind, Dwarven District

### ISSUE THREAD

**Issue by MagicalNeko** [RaphaelSunwell/Sunwell-BugTracker-SCv2#269]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jeden z Forgów nie działa. (ten poza namiotem) 

**Obecne działanie**: Smelting nie odczytuje go jako Forge. 

**Oczekiwane działanie**: Powinien... ee... działać? 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejść i próbować smeltować przy forgu, pokaże się komunikat "Requires Forge" 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
X: -8427.394531 Y: 606.763062 Z: 95.087936 Map: 1 VMap: 1 MMap: 3164864512

**Comment by kovaq** [comment]
Forge istnieje w tym miejscu tylko jako visual, jego hitbox stoi za namiotem, jest to kilka yardow roznicy, ktore trzebaby poprawic.
https://youtu.be/BjR-U0KSHQg

**Comment by Shon-su** [comment]
poprawione
