### ISSUE TITLE
[NPC] Varimathras

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#27]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W Undericty brakuje NPC o nazwie 'Varimathras' (ID 2425), który daje 4 questy: An Unholy Alliance, Into The Scarlet Monastery, The Crimson Courier, The Power to Destroy...

**Obecne działanie**: Brak npc.

**Oczekiwane działanie**: Dodanie brakującego npc.

**Linki WoWHead/OpenWoW**:

1. http://db.vanillagaming.org/?npc=2425#starts

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
56 / 91, Undercity, Royal Quarter

**Comment by Io36** [comment]
Czy on nie został podmieniony na Bragor Bloodfist
 http://www.wowhead.com/npc=36273/bragor-bloodfist#abilities

Ba w linku który dałeś jest komentarz: 
"By pietrex on 10/03/2009 (Patch 3.1.3)
In 3.3 PTR he is replaced by Bragor Bloodfist <Kor'kron Captain>. He most likely offers all the quests Varimathras did. Yep, that's the 'B' we were told about.

It's also worth nothing that all abominations are gone and Kor'kron guards can be seen instead. There is also an overseer down in the Apothecarium. All of them talk as if they didn't trust undead at all."

**Comment by ellynd** [comment]
Tak, oni zostali podmienieni na patchu 3.3.0, zgadza się, ale my aktualnie mamy 'symulacje' patcha 3.0, więc postawienie tam Varimathrasa będzie jak najbardziej poprawne ;)

**Comment by Io36** [comment]
Tylko on, trzeba by  zmieniać też strażników. Ciekawe czy można zrobić że dopiero po oblężeniu UC aby był podmieniany NPC, lae pewnie to za dużo roboty.

**Comment by ThePuppetMaster** [comment]
#12
