### ISSUE TITLE
Combat BUG

### ISSUE THREAD

**Issue by xluuix** [RaphaelSunwell/Sunwell-BugTracker-SCv2#270]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
-Nie poprawie działający Combat w PVP

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
-Obecnie na serwerze combat znika po 6 sekundach od ostatniego ataku w gracza
dodając do tego minimalne opóźnienie serwera które wynosi od 0.3 setnej sekundy do nawet 0.7 lub czasem gdy diff podskoczy nawet do 2 sec co jest nazywane wtedy potocznie "Lagami"

Daje nam to minimalne zejście combatu po 6,3sec a nawet do 6.7sec co jest absurdalne jeśli chodzi o balans PVP gdzie combat na globalu zanikał po 5.5sec potocznie było mówione 6sec dla tego wszędzie utarło się ten 6 sekundowy combat 

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
-Combat powinien zanikać tak jak opisane zostało to niżej obecny system bardzo psuje pvp 1v1 lub 2v2 z racji takiej że znika po bardzo długim czasie co powoduje że niektóre klasy mają znaczną przewagę nad innymi 

**Co należy zrobić, aby odtworzyć ten błąd**:
-Najlepszym rozwiązaniem było by wprowadzenie znikania combatu po 5.5sec ale z racji takiej że server stoi stosunkowo nie długo i co najważniejsze nie posiada wystarczająco mocnego sprzętu aby 24/7 chodził płynnie czasem występują opóźnienia i lagi należało by wprowadzić zanikanie combatu po 5,2sec aby wyrównało się to do 5.5 pod warunkiem że będzie to minimalne opóźnienie serverowe a jak wcześniej wspomniałem wynosiło one od 0.3 do 0.7 sec biorąc średnią z tego mamy 0,5 więc należało by obniżyć combat do 5sec aby uzyskać globalny wynik 5.5sec combatu 

Mowa tu o średnim czasie który w rzeczywistości będzie i tak wynosił 5.3-5.7sec który znacznie poprawił by działanie balastu pvp
Mam nadzieje że developerzy weźmiecie sobie ten post poważnie i przywrócicie combat na właściwy poziom tak jak to miało miejsce na starym Sunwellu 
Pozdrawiam 
1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. Brak Linku powołuje się tutaj na moje 10 letnie doświadczenie gry na wielu serwerach, również wiedzy z globalu
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Danieloses** [comment]
nie do końca tak jest jak to opisałeś, na globalu co sekundę następowało odświeżenie serwera jeżeli chodzi o sprawdzanie combatu graczy więc wyjście z combatu mogło trwać od 5 do 6 sekund, jeżeli chodzi o prywatny serwer najlepszym wyjściem ustawienie jest 5.5sek, jest to idealnie zbalansowana opcja jeżeli chodzi o pvp, 5sek mocno faworyzuje rogali/druidów natomiast 6sek mocno faworyzuje pozostałe klasy w starciu z rogalami/druidami, na 5.5sek zdecydowała się zdecydowana większość prywatnych serwerów w tym serwery takie jak Tod, stary sunwell czy też Arena Tournament, Warmane, uważam, że 5.5sek lub nawet 5.5sek minus średni dzienny diff to idealne rozwiązanie

**Comment by xluuix** [comment]
Tak mi wyszło w pomiarach w addonie testowałem to nie jednokrotnie być może teraz trochę się to poprawiło testy robiłem nie całe 2 tyg temu również jestem za tym aby combat był 5,5 sec jak to miało miejsce na tod lub starym sunwellu ustawienie 5sec spowodowało by tak jak mówisz przewagę rogali i druidów a znowu 6sec faworyzuje inne klasy mocno takie które nie muszą wychodzić z combatu typu DK np.
więc póki co balast pvp jest bardzo nie równy a to również odbije się na różnych teamach w 2v2

**Comment by ThePuppetMaster** [comment]
Combat trwa 5.5s
