### ISSUE TITLE
[QUEST] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Yhavi** [RaphaelSunwell/Sunwell-BugTracker-SCv2#271]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Znikające NPC'ki do uratowania

**Obecne działanie**: Brak NPC'ow do uratowania. Pojawiają się na na kilka sekund i znikają. Nawet jak się uda załadować go na gryfa to i tak zaraz znika.

**Oczekiwane działanie**: Załadowanie Villager'a na gryfa i dolecenie do Wintergarde Keep. Czynność powtórzyć 10 razy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa
2. Użyć quest itemu [Wintergarde Gryphon Whistle]
3. Podlecieć do Villager'ów i patrzeć jak znikają

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Carrion fields - Dragonblight - 84.49

**Comment by Sleepingdog03** [comment]
Quest już był zgłaszany. Czytajcie zanim coś duplikujecie 

https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/189
