### ISSUE TITLE
[Quest] Adding Injury to Insult

### ISSUE THREAD

**Issue by pjootr93** [RaphaelSunwell/Sunwell-BugTracker-SCv2#272]
**Opis**: Quest polaga na uzyciu itemu Vrykul Insult
 na Bjorn Halgurdsson i przyciagniecie do wskazanego miejsca w celu zabicia go przez NPC, jednak ma on standardowy zasięg gonienia i przestaje on nas gonić przed wskazanym miejscem.

**Obecne działanie**: Bjorn Halgurdsson przestaje nas gonić zanim dojdziemy do wskazanego miejsca.

**Oczekiwane działanie**: Używamy questowego itemu, przyciągamy Bjorn Halgurdsson na wskazane miejsce. NPC zabijają go.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć itemu Vrykul Insult
2. Uciekać do wskazanego miejsca
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12481/adding-injury-to-insult
2. http://wotlk.openwow.com/quest=12481
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
1634.776611, -5365.972168, 192.276627, 571

**Comment by kovaq** [comment]
https://youtu.be/YESY-LOkTmY
Dziala.
