### ISSUE TITLE
William Saldean <Grain & Feed Vendor>

### ISSUE THREAD

**Issue by xnemeyethx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#277]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

Brak NPC William Saldean <Grain & Feed Vendor> id: 33996

**Obecne działanie**: 

NPC powinien znajdować się w miasteczku Brill, niedaleko kuźni jednak nigdzie go nie ma.

**Oczekiwane działanie**: 

NPC powinien znajdować się w miasteczku Brill, niedaleko kuźni.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Dodać NPC do miasteczka Brill
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=33996/william-saldean#comments
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
61, 52

**Comment by ThePuppetMaster** [comment]
Patch 3.1.0 (14-Apr-2009): Added.
