### ISSUE TITLE
Takk's Nest

### ISSUE THREAD

**Issue by xnemeyethx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#278]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

W The Barrens można natknąć się na gniazda raptora o imieniu Takk. Z gniazda powinien nam dropnąć pet Leaping Hatchling, szansa na drop wynosi 100%.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

Po otwarciu gniazdo znika, nie dostajemy peta ani żadnego innego itemu.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

Dodać peta do loot table gniazda?

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Znaleźć Takk's Nest w The Barrens
2. Kliknąć gniazdo.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/object=202081/takks-nest
2. http://www.wowhead.com/item=48118/leaping-hatchling
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by myentos** [comment]
Dodane w patchu 3.3
