### ISSUE TITLE
[Quest] You're Fired

### ISSUE THREAD

**Issue by Bainit123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#279]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Nie da się przyzwać bossa, którego należy zabić żeby ukończyć quest. Boss powinien zostać przywołany po otwarciu 5 obelisków znajdujących się w pobliżu NPC rozpoczynającego quest. Klucze można normalnie wydropić, jednak nie da się ich użyć. 

**Obecne działanie**: Tylko 1 z obelisków ma napisane "Requiers Camp Anger Key", pozostałe mają po prostu "Locked".

**Oczekiwane działanie**: Wszystkie obeliski powinno dać się otworzyć. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa "You're Fired!".
2. Wydropić klucze,
3. Spróbować otworzyć obeliski,

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/quest=10821/youre-fired](http://www.wowhead.com/quest=10821/youre-fired)
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
![image](https://cloud.githubusercontent.com/assets/22755789/20942717/f61e3506-bbfc-11e6-8ee6-e856d68eae03.png)

Uwagi: Gdy po raz pierwszy wziąłem questa mogłem otworzyć 2 obeliski, po abandonie już tylko jednego. Możliwe że po restarcie serwera działo prawidłowo, jednak po zrobieniu questa przez jedną osobę kolejne już nie mogą.

**Comment by Verthe** [comment]
Dziala prawidlowo

**Comment by plessico** [comment]
Mam ten sam problem nie wiem o co caman niektóre obeliski po prostu są Locked i nie jestem w stanie ich użyć
