### ISSUE TITLE
[MECHANIKA][AUTOATTACK] Autoattack po castowaniu

### ISSUE THREAD

**Issue by morrk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#281]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po castowaniu jakiegokolwiek spella mozna zadac instantowy melee auto-attack

**Obecne działanie**: Nie wystepuje cooldown na autoattack po wycastowaniu spella

**Oczekiwane działanie**: Po zakonczeniu casta postac powinna "zamachiwac" sie od nowa. Np jak mamy bron 2.30 speeda, to postac powinna odczekac 2.30 sekundy po zakonczeniu castowania, tak jakby koniec casta byl poczatkiem ladowania sie kolejnego ataku

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Kliknac spell, ktory sie castuje. (np. Fireball)
2. Spamowac PPM na przeciwnika.
3. Obserwowac.

**Linki WoWHead/OpenWoW**:

1. Brak

***SCREENSHOT***
![wowscrnshot_120616_221608](https://cloud.githubusercontent.com/assets/24419991/20943915/b298d1e2-bc01-11e6-8bdc-807fb09be7cf.jpg)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Wszedzie gdzie sa przeciwnicy

**Comment by Danieloses** [comment]
jeżeli nacisnąłeś PPM przed castem spella normalnie powinien zostać wykonany autoattack po skończeniu castu, nie istnieje żaden cooldown na autoattack po wycastowaniu spella, od początku wowa hardcorowi casterzy maxowali dps wykorzystując tą mechanikę, a hunterzy maxowali burst w pvp castując steadyshota by użyć go razem z innym instantem + autoshotem, jestem w 100% pewny, że wszystko działa poprawnie

**Comment by Rosenkrantz** [comment]
Nie, Panie Danieloses, taki problem resetowania melee swingów istnieje od zarania WoWa, wręcz cała gra na TBC warriorem arms i steadyshotowanie hunterem opierało się o to zagadnienie: https://eu.battle.net/forums/en/wow/topic/1820962304 w cata wciąż istniało, jak widać.
Nie trzeba było tego nikomu tłumaczyć, bo wiedział o tym każdy, kto lvlował palka, i rzucił na siebie holy light w trakcie autoatakowania mobka.

Jeżeli to występuje tylko u clothów to pal licho, ale w takiej sytuacji jak jest teraz, pal/sham mogą castować zaklęcia bez ubytku dla dpsu z autoataków, co może mieć jakieś konsekwencje. Czy duże, nie mi to oceniać, zależy od kreatywności graczy. Proponowałbym reopen, a na pewno co najmniej przemyślenie sprawy.
