### ISSUE TITLE
[Roll mechanics] Roll osoby martwej/będącej w duchu nie jest brany pod uwagę.

### ISSUE THREAD

**Issue by raveeneer** [RaphaelSunwell/Sunwell-BugTracker-SCv2#282]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zabijamy boss'a, jednak padam zaraz przed jego zabiciem, wyskakuje loot - klikam need na konkretny item i wchodzę w ducha. W między czasie roll zostaje rozstrzygnięty i jako jedyna osoba needująca nie jestem brany pod uwagę. Item zostaje rozdany dla greedujących.

**Obecne działanie**: Właściwie wyjaśnione w opisie.

**Oczekiwane działanie**: Osoba będąca martwa w chwili zabicia boss'a jest brana pod uwagę w momencie rozstrzygnięcia roll'a.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Paść.
2. Czekać, aż reszta ekipy zabije boss'a.
3. Zaneedować item, który wypadnie
4. Wstać do ducha i czekać na rozstrzygnięcie roll'a.

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Brak dowodu.
