### ISSUE TITLE
[NPC] Deathguard Molder.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#283]
**Opis**: Double NPC.

**Obecne działanie**: 2x NPC.

**Oczekiwane działanie**: Powinien być 1 NPC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć NPC.

**Linki WoWHead/OpenWoW**:

1. [NPC] http://www.wowhead.com/npc=27320/deathguard-molder

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/mGy3hTE

**Comment by Shon-su** [comment]
poprawione
