### ISSUE TITLE
[Strona][Armory] - Wyszukiwanie Armory

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#284]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wyszukiwarka armory na stronie nie pozwala nam wyszukać osób o nicku składającym się z dwóch liter
**Obecne działanie**: Gdy wpiszemy dwie litery w wyszukiwarkę Armory wyskakuje komunikat o błędzie: "Wyszukiwane słowo musi mieć więcej niż 2 znaki!"

**Oczekiwane działanie**: Na serwerze można stworzyć postać, której nick będzie składał się z dwóch liter więc powinniśmy także móc wyszukać taką postać na Armory jednak jest to obecnie niemożliwe.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Stworzyć/Znaleźć postać o nicku 2literowym
2. Spróbować wyszukąć ją na Armory
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by XevL** [comment]
still bugged.
