### ISSUE TITLE
[Quest] Fresh Remounts.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#287]
**Opis**: Quest polega na zabiciu npc i kradzieży konia przy pomocy quest itemu oraz doprowadzeniu go do wyznaczonego miejsca.

**Obecne działanie**: Obecnie quest można zaliczyć doprowadzając tylko jednego skradzionego wierzchowca.
https://youtu.be/tNSm-Qp_ugI

**Oczekiwane działanie**: Aby wykonać quest, gracz powinien skraść i doprowadzić do wyznaczonego miejsca 3 konie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Zabić npc na koniu.
3. Podnieść quest item i użyć go na koniu.
4. Doprowadzić konia do wyznaczonego miejsca. 

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=12214/fresh-remounts
2. [Quest item] http://www.wowhead.com/item=37202/onslaught-riding-crop
3. [Koń] http://www.wowhead.com/npc=27213/onslaught-warhorse
4. [NPC] http://www.wowhead.com/npc=27206/onslaught-knight

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
W nagraniu.

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
