### ISSUE TITLE
[Mob] Rabid Grizzly.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#288]
**Opis**: Zagubiony niedźwiadek.

**Obecne działanie**: Niedźwiedź jest w nieodpowiednim miejscu. Nie można go atakować.
https://youtu.be/aLJc4sp_TJA

**Oczekiwane działanie**: Niedźwiedzia nie powinno być przed wejściem do instancji. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć niedźwiedzia.

**Linki WoWHead/OpenWoW**:

1. [Niedźwiedź] http://www.wowhead.com/npc=26643/rabid-grizzly

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
W nagraniu.

**Comment by ThePuppetMaster** [comment]
Spadł przez tekstury.

**Comment by Kougraa** [comment]
Dokładnie tak. ;)

**Comment by Heartbraker** [comment]
Nie jest to problem z jednym niedźwiedziem, a ogólny problem. Wszędzie gdzie są jakieś podziemne jaskinie/tunele część mobów które powinny być na powierzchni nad nimi "zapada się" pod ziemię.

**Comment by ThePuppetMaster** [comment]
Zdaje sobie z tego sprawę.

**Comment by xsitdev** [comment]
Już dawno poprawione.
