### ISSUE TITLE
[QUEST]Elixir of Agony

### ISSUE THREAD

**Issue by Daeris** [RaphaelSunwell/Sunwell-BugTracker-SCv2#29]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie można oddać ostatniego questa (podłożenie beczki dla więźniów).

**Obecne działanie**: Beczka nie posiada znaku zapytania i po prostu nie można z nią "porozmawiać" w celu oddania questa. Wygląda jakby beczka po oddaniu questa (zamienia się wtedy w Tained Keg) nie wracała do początkowej postaci (Dusty Rug).

**Oczekiwane działanie**: Nie można oddać questa, znak zapytania nie pojawia się.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wystartować quest.
2.  Podejść do beczki.
3.  Zauważyć, że nie można oddać questa.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=524
2. http://wotlk.openwow.com/item=3520
3. http://wotlk.openwow.com/object=1728

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
6.28, 18.7

**Comment by ThePuppetMaster** [comment]
Dusty Rug - zakurzony dywan.
Questa oddaje się dywanowi, nie beczce.
