### ISSUE TITLE
[NPC] Prince Valanar visual bug.

### ISSUE THREAD

**Issue by jubasek21** [RaphaelSunwell/Sunwell-BugTracker-SCv2#291]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Prince Valanar - visual bug (chain DK).

**Obecne działanie**: Prince Valanar jest wbity w teksturę. Drobny visual. Warto dodać, że Prince biega w różnych kierunkach, raz wychodzi z tekstury raz w nią wchodzi.

**Oczekiwane działanie**: Prince Valanar powinien stać normalnie na tym "piedestale".

**Co należy zrobić, aby odtworzyć ten błąd**: Wszystko właściwie jest widoczne na screenie, wystarczy podejść do NPC i wszystko widać.

1. Wziąć questa.
2. Zobaczyć, że NPC jest w teksturze i nie stoi tak jak powinien.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=25601/prince-valanar - NPC
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://zapodaj.net/18f85e0182a16.jpg.html

**Comment by jubasek21** [comment]
https://zapodaj.net/18f85e0182a16.jpg.html - był problem z tamtym linkiem, tutaj powinno już być w porządku.

**Comment by Lebiedz** [comment]
W całej lokacji startowej DK jest kilka NPC, którzy nie umieją wystać w miejscu i się wiercą po okolicy. Btw, właściwy Valanar to: http://www.wowhead.com/npc=29107/prince-valanar

A pozostali, z moich obserwacji:
http://www.wowhead.com/npc=28760/hargus-the-gimp
http://www.wowhead.com/npc=28510/scourge-commander-thalanor

**Comment by jubasek21** [comment]
Tak, miałem edytować zgłoszenie, dzięki ;) Oczywiście w quescie z okiem mobki jeśli zauwazą gracza to biegną w powietrze, ale to globalny bug serwerowy jesli jest sie np. na fly mountcie i mamy aggro. Problem znany z tego co wiem

**Comment by Shon-su** [comment]
poprawione zachowanie valanara i hargusa, Commander wydaje się że ma tak chodzić. Nie dograne jeszcze.
