### ISSUE TITLE
[QUEST] Keeping Pace

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#292]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Description
The Brassbolts brothers have discovered a new building material, that's the only explanation that makes sense. Their cars have been operating faster than before, but their designs, and all the other data we've gathered from their runs is identical.

What we do know, is that Rizzle Brassbolts has been focused on the plans for this new discovery almost constantly.

Zamek can create a diversion for you, so that you can steal those plans from them.
Completion
Gains
Upon completion of this quest you will gain:

    3,415 experience
    75 reputation with Ratchet

**Obecne działanie**: O ile quest można pobrać, to niestety po znalezieniu w domku Rizzle's Unguarded Plans nie tylko obiekt leżący na podłodze nie posiada znaku zapytania, to klikając na niego nie zalicza questu.

**Oczekiwane działanie**: Po odnalezieniu obiektu w koordynantach podanych poniżej dodać znak zapytania do obiektu oraz dodać zaliczenie questu po jego otwarciu.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Dodać do obiektu na podłodze znak zapytania.
2. Dodać zaliczenie questu po jego otwarciu.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=1190/keeping-pace
2. http://www.wowhead.com/object=20805/rizzles-unguarded-plans#comments
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Mirage Raceway 77.2/77.4

**Comment by xsitdev** [comment]
Niepoprawne zgłoszenie, żeby wykonać ten quest trzeba wykonać quest od NPC "Zamek", co z resztą jest napisane w quescie.
