### ISSUE TITLE
[Fishing Daily][Quest] Dangerously Delicious

### ISSUE THREAD

**Issue by Gayfish1** [RaphaelSunwell/Sunwell-BugTracker-SCv2#294]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Prawdopodobnie wszystkie daily questy fishing są skopane. Jak dotąd próbowałem robić 3, bez skutku.

**Obecne działanie**: Nie da się złowić [[Terrorfish](http://www.wowhead.com/item=45904/terrorfish)] w Wintergrasp

**Oczekiwane działanie**: Zwiększyć szansę na złowienie [[Terrorfish](http://www.wowhead.com/item=45904/terrorfish)] na terenie Wintergrasp

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wyskillować fishing na 450
2. Przejść się do jeziorka Wintergrasp
3. Połowić chwilę

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13834/dangerously-delicious
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Wintergrasp

**Comment by ramciachciach** [comment]
Podbijam, widać administracja nic z tym nie robi...
