### ISSUE TITLE
[ARMORY] Złe pokazywanie talentów

### ISSUE THREAD

**Issue by Triceps69** [RaphaelSunwell/Sunwell-BugTracker-SCv2#295]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Talenty nie są prawidłowo pobierane z gry

**Oczekiwane działanie**: Powinny być pobierane prawidłowo

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść na armory i sprawdzić, bug występuję na każdej postaci
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Nie występuje.

**Comment by kevery123** [comment]
Nie rozumiem czemu zamykasz zreportowane bugi ktore powinny byc naprawione http://sunwell.pl/character/1/2020 moja postac ma w assasination pokazane 9 wybranych a normlanie mam 12 i wogole nie pokazuje wybranego ruthlessness 3/3 i prosilbym o blizsze przyjzenie sie bugom ktorr ja reportuje a nie odrazu je zamykasz.

**Comment by ThePuppetMaster** [comment]
Gracz nie podał linków do źle działających profili, profile, które testowałem nie były dotknięte tym błędem. Jeżeli coś zgłaszamy, postarajmy się pokazać, gdzie leży problem. Jeżeli nie będę w stanie w racjonalnym czasie odtworzyć błędu, a w zgłoszeniu nie będzie wystarczających dowodów, zostanie ono zamknięte. Podobnie jak twoje zgłoszenia. Proszę również nie rozpoczynać forumowych kłótni w zgłoszeniach, jednocześnie dziękuje za dostarczenie linku.

**Comment by Triceps69** [comment]
Przepraszam, że nie podałem linku. 
http://sunwell.pl/character/1/2125
http://sunwell.pl/character/1/18384

Ale naprzykład tutaj już działa:
http://sunwell.pl/character/1/3429

**Comment by Kougraa** [comment]
Aktualnie nie widać w ogóle talentów.
