### ISSUE TITLE
[BUFF] Tenacity - wintergrasp , jak wygrac 10 na 100?

### ISSUE THREAD

**Issue by Sevillan** [RaphaelSunwell/Sunwell-BugTracker-SCv2#297]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:buff powinien pojawiać się przy dużej różnicy graczy ally,horde przebywających podczas bitwy na wintergrasp

**Obecne działanie**: w ogóle nie działa

**Oczekiwane działanie**: jak w linku wowhead

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wejść na wintergrasp ...
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=58549/tenacity
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Northend

**Comment by khaztiv** [comment]
tenacity nie jest przyznawane wszystkim graczą frakcji ale tylko nie którym. Nie wiem, poki co od czego to zależy.
