### ISSUE TITLE
Brak exp boost i strata 30 VP

### ISSUE THREAD

**Issue by wwswswswswss** [RaphaelSunwell/Sunwell-BugTracker-SCv2#299]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po wykonaniu operacji zakupu expboost x3 za 30VP punkty zniknely a bosta nie ma

**Obecne działanie**: brak boosta 

**Oczekiwane działanie**: obecnosc boosta

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by myentos** [comment]
ogarnijcie się, przecież chyba w każdy możliwy sposób administracja informuje że trwają prace.
