### ISSUE TITLE
[QUEST][OBJECT][NPC] Recover the Cargo

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#3]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Wraki statku, po użyciu itemu z questu powinny znikać i dawać quest item bądź pojawiać murloka który nas atakuje.
**Obecne działanie**: 
Wraki statku nie znikają po użyciu qitemu, przez co można zdobyć dowolną ilość tego itemu oraz po 20 próbach ani razu nie pojawił się murlok. [Dowód](http://i.imgur.com/c6QEXQH.jpg)
**Oczekiwane działanie**: 
Wraki po jednokrotnym użyciu qitemu powinny zniknąć, oraz mieć szansę pojawienia się murloka.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć qitemu na obiekcie.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/quest=11140/deprecated-recover-the-cargo](http://www.wowhead.com/quest=11140/deprecated-recover-the-cargo)
2. [http://www.wowhead.com/npc=23701/mirefin-ambusher]( http://www.wowhead.com/npc=23701/mirefin-ambusher)
3.  [http://www.wowhead.com/object=214547/shipwreck-debris](http://www.wowhead.com/object=214547/shipwreck-debris)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Objectu nie łapie. Pisze, że jest jego brak.

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane dzisiaj (tj. 27.01) około 6 rano.
