### ISSUE TITLE
[Mob][WG] Mature Lasher

### ISSUE THREAD

**Issue by Valais** [RaphaelSunwell/Sunwell-BugTracker-SCv2#300]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Mature Lasher nie występuje mimo tego że twierdza jest w posiadaniu mojej frakcji
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Jeżeli twierdza jest w posiadaniu mojej frakcji powinny się spawnic Mature Lashery ze 100% szansa na drop Crystallized Life tak samo jak inne elementale
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przejąć twierdze
2. Podlecieć na skałke z kwiatuszkami na WG
3. Zaobserwowac calkowita absencje Mature Lasher

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=34300/mature-lasher
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
TO nie jest pojedynczy mob ktorego kordy moglbym umiescic

**Comment by ThePuppetMaster** [comment]
Added in patch 3.1.0.9767

Podobnie z pozostałymi.
