### ISSUE TITLE
[QUEST] Target: Felstone Field

### ISSUE THREAD

**Issue by Effimera** [RaphaelSunwell/Sunwell-BugTracker-SCv2#301]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest w Plaguelands polega na wydropieniu klucza z mobka obok kotła i oddania go wraz z pustą butelką, którą otrzymujemy wraz z q.

**Obecne działanie**: Posiadając oba itemy (butelkę i wydropiony klucz) nie da się oddać questa, mimo, że wyświetlany jest żółty znak zapytania.

**Oczekiwane działanie**: -

**Co należy zrobić, aby odtworzyć ten błąd**:

1. naprawić opcję oddawania q.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=5216/target-felstone-field
2. -
3. -

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Lebiedz** [comment]
Quest się czasami buguje, jednak da się go wykonać. Być może trzeba relognąć, bądź zrobić coś innego. W każdym razie u mnie początkowo też wystąpił ten bug. Zająłem się czymś innym i później udało mi się wykonać ten i pozostałe questy z chaina.

**Comment by Shon-su** [comment]
13.02.2017 realm Ostatnie Szlify
Działa ok
