### ISSUE TITLE
[Quest] Reconnaissance Flight

### ISSUE THREAD

**Issue by pjootr93** [RaphaelSunwell/Sunwell-BugTracker-SCv2#302]
**Opis**: Żeby ukończyć quest należy wylądować samolotem, czyli zejść nim na ziemie. Nie jest to możliwe ponieważ sterować nim można tylko lewo/prawo. 

**Obecne działanie**: Nie można sterować samolotem góra/dół i przez to nie można wylądować.

**Oczekiwane działanie**: Steruje samolotem w dół w celu sprowadzenia go na ziemie

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Bierzemy quest Reconnaissance Flight
2. Czekamy aż dostaniemy zadanie sterowania samolotem
3. Próbujemy zejść nim na ziemie

**Linki WoWHead/OpenWoW**:

1. www.wowhead.com/quest=12671/reconnaissance-flight
2. https://www.youtube.com/watch?v=bKDuH7VhXj4
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
5502.957520, 4752.115234, -191.944824, 571

**Comment by Kokaina** [comment]
Wystarczy nacisnąć spacje i przejmujesz pełną kontrolę nad samolotem.

**Comment by ThePuppetMaster** [comment]
Tak samo było na retailu. Podobnie jest z innymi 'pojazdami' questowymi, jak np protodrake w quescie z chaina dla Hodirów.
