### ISSUE TITLE
Stratholme

### ISSUE THREAD

**Issue by Kenrod96** [RaphaelSunwell/Sunwell-BugTracker-SCv2#309]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Źle działa insta

**Obecne działanie**:Po zabiciu bossów przed or mobków w środku zigguratów brama umożliwiająca dostęp do bossa Rivendera jest zamknięta

**Oczekiwane działanie**: Brama ta powinna była otworzyć się po zabiciu mobków z trzech zigguratów
w okolicy tej bramy

**Co należy zrobić, aby odtworzyć ten błąd**: Należy wejść do insty i spróbować ją zrobić w celu zabicia Rivendera, zauważycie wtedy że brama sie nie otworzy

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/stratholme
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
27.0; 12.5

**Comment by ThePuppetMaster** [comment]
Wszystko działa poprawnie. Podziękowania dla gracza Rokin za pomoc w testach.
