### ISSUE TITLE
[SKILL][PALADIN]Hand of Reckoning

### ISSUE THREAD

**Issue by sorgall909** [RaphaelSunwell/Sunwell-BugTracker-SCv2#31]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Skill Hand of Reckoning nie zadaje dmg momob które uciekają na low hp .

**Obecne działanie**: Nie zadaje dmg mobom które uciekają.

**Oczekiwane działanie**: Skill powinien zadawać dmg

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Zacząć walkę z humanoidem 
2. Zbić mu na tyle hp aby zaczynał uciekać
3. Użyć umiejętności Hand of Reckoning

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=62124
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by dilldadisbak** [comment]
Mnie sie nie zdazylo. Dzisiaj robilem caly czas insty i tak dobijalem moby.

**Comment by Triceps69** [comment]
Potwierdzam przedmówce, wystarczy użyc skilla na mobie który nas nie bije, a DMG zostanie zadany prawidłowo, więc skill działa poprawnie.

**Comment by myentos** [comment]
Dla kompletnego wyjaśnienia, dodam, że skill zadaje dmg tylko wtedy, kiedy NPC nas nie targetuje.

**Comment by sorgall909** [comment]
To dziwne bo mi i koledze nie działa na około 40 lvl , moby które maja low hp i uciekają nie mają nas już na tergecie a mimo to skill nie zadaje dmg , nie wyskakuje miss , tylko zwykły taunt jak by mobek miał nas na targecie.

**Comment by myentos** [comment]
Wypróbowałem na różnego rodzaju mobków i okazało się, że masz rację. Raz działa a raz nie, mimo tego samego typu NPC.

**Comment by ThePuppetMaster** [comment]
moby które maja low hp i uciekają nie mają nas już na tergecie - bzdura.

Najlepszy test to wziąć ze sobą kolegę grającego klasą która ma taunta i zagrać w pingpong mobem.
Póki co zamykam.

**Comment by myentos** [comment]
ThePuppetMaster, to wytłumacz mi dlaczego raz działa a raz nie?
