### ISSUE TITLE
Swift Flight Form

### ISSUE THREAD

**Issue by Rokin92** [RaphaelSunwell/Sunwell-BugTracker-SCv2#310]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W trakcie lotu skille są zablokowane.

**Obecne działanie**: Druid Swift Flight Form nie pozwala na używanie skilli i spelli w powietrzu.

**Oczekiwane działanie**:  Spelle oraz skille są odblokowane w trakcie lotu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wbić 70
2.  Nauczyć się szybszego latania.
3.  Kupić Swift Flight Form

**Linki WoWHead/OpenWoW**:

1.  [http://wotlk.openwow.com/spell=40120](url)
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
 Nie dotyczy

**Comment by Heartbraker** [comment]
Game Menu > Interface > Controls > Auto Dismount in Flight <-- musisz to zaznaczyć
