### ISSUE TITLE
Combat bug spowodowany przez pety

### ISSUE THREAD

**Issue by kevery123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#311]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Water elemental odrazu po przyzwaniu nabija combat jeszcze przed wycastowaniem spella. Testowalem tylko na water elementarze mysle ze z petami innych class moze tez byc ten sam bug

**Obecne działanie**:  Testowalem rogalem na duelu z magem. Wyszedlem ze staltha -> mag uzyl summon water elemental -> odrazu po uzyciu dostalem combat -> zvanishowalem -> zcancelowaelm vanisha i stealtha -> pet po zaczeciuciu casta juz nie nabijal combatu dalo sie stealthnac przed wycastowaniem spella

**Oczekiwane działanie**: po przywolaniu peta pet nie powinien nabijac combat, combat powinien byc nabity dopiero jak dostalem spellem

**Co należy zrobić, aby odtworzyć ten błąd**: wszystko wyzej wyjasnione

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
To działanie jest poprawne. Podziękowania dla gracza Ysirath za pomoc w testowaniu, oraz dla Mithrasa za testy na porównawcze na retailu.

**Comment by kevery123** [comment]
Serio poprawne jest to ze samo przyzwanie peta nabija combat na siebie i przeciwnika ?

**Comment by ThePuppetMaster** [comment]
Samo przyzwanie peta nie spowodowało combatu. Pet był na aggressive. Sprawdź dokładnie, my to zrobiliśmy.
