### ISSUE TITLE
Improved gouge

### ISSUE THREAD

**Issue by kevery123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#312]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po gougu z talentem improved gouge powinna byc mozliwosc wejscia w stealtha bez mozliwosci puszczenia instanta przez przeciwnika ( np. Ice lanca) 

**Obecne działanie**:  Po improved gougu nie da sie wejsc w stealtha jesli przeciwnik robi szybki ruch  spellem instantowym 

**Oczekiwane działanie**: powinna byc mozliwosc wejscia w steltha bez obawy przed wykryciem spellem single target instantowym zanim sie skonczy gouge ( nie mowie o mozliwosci wejscia w stealtha i zsapowania targetu ktory ma jeszcze gouga - tak to dzialalo na starym sunwellu )

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Uzyc gouga z talentem improved gouge na gracza ktora ma mozliwosc uzycia spella instantowego np ice lance.
2. Sprobowac wejsc w stealtha jak sie konczy gouge
3. Mag w tym samym czasie proboje uzyc np ice lanca
Mozna zaobserowac brak mozliwosci wejscia w stealth
**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Brak szybkich paluchów. Podziękowania dla gracza Kovaa za testy.

**Comment by kevery123** [comment]
Brak szybkich paluchow ? Jest to mozliwe ale tylko na graczy ktorzy nie spamuja spella zeby w nas walnac. Testowalem i kolega spamowal caly czas spella i jest niemozliwe wejscie w stealth na kogos kto spamuje nawet shadowstepem przerywa stealth. Bledne testy to nie testy gralem 8 lat na globie wiem co pisze. Radze saemu przetestowac zanim zamkniesz

**Comment by ThePuppetMaster** [comment]
Odświeżanie na retailu i na privach wygląda całkowicie inaczej. Generalnie na emu masz o wiele niższy margines do wykorzystania.
