### ISSUE TITLE
Shadowstep bug

### ISSUE THREAD

**Issue by kevery123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#313]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po uzyciu shadowstepa na kogos ktos sie porusza i wykonuje skok ( w tym moemencie jak stepnelismy a target jest w powietrzu nie mozemu uzyc spella, dopiero jak spadnie

**Obecne działanie**: Jak wyzej jeszcze dodam ze target musi sie caly czas poruszac i wyc w powietrzu. I jeszcze taki sam efekt jest jak probujemy shadowstepnac huntera ktory jest w locie disengagem np w polowie, jak shadowstepniemy nie mozemy uzyc np cheapshota czy garoty instantowo. Chodzi tu glownie o problem ze jestesmy w powietrzu po shadowstepie i takjakby spadamy i dopiero jak spadniemy mozemy uzyc spelli 
 

**Oczekiwane działanie**: Powinna byc mozliwosc instantowego uzycia shadowstepa i jakiegos spella jesli szybko to zrobimy np hunter leci na disegagu to mozemy uzyc shadowstepa i cheap shota w polowie lotu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dac duel np magowi albo hunterowi( disengage test )
2. Niech mag skacze caly czas i biegnie do przodu np
3.  Shadowstepujemy go jak jest w powietrzu i obserwujemy ze nie mamy mozliwosci uzycia spelli typu garota chocby dopoki nie jestesmy na ziemi a w locie.
Wydaje mi sie ze jest to problem majacy cos wspolnego z bugami typu ze po shadowstepie teleportujemy sie na dno zbironika wodnego mimo ze uzylismy shadowstepa na target plywajacy na gornej czesci zbiornika wodnego.
**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Brak reference-u potwierdzającego twoją wizję poprawności działania shadowstep.

**Comment by kevery123** [comment]
Wystarczy wlaczyc sobie pierwszy lepszy video z globala i zobaczyc ze shadowstep i np garota  te combo bylo do zrobienia instantowo instantow z tym bugem rogal jest nie do grania na takiego maga wystatczy ze skacze i daje freeza na stepa bo po stepie nic nie mozna uzyc.

**Comment by ThePuppetMaster** [comment]
Jeżeli posiadasz reference to popraw zgłoszenie. Wyobraź sobie, że jesteś devem, gracze walą zgłoszenia jak z kałacha, bez reference, twierdząc, że coś powinno być tak, a nie inaczej i ty poza swoją pracą, którą jest naprawienie tego problemu, musisz przeszukać dla każdego zgłoszenia cały internet, żeby potwierdzić jego poprawność.
