### ISSUE TITLE
Auto attack zadawany z daleka

### ISSUE THREAD

**Issue by kevery123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#315]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jest to bug ktory czesto mi sie przytrafia jak ogolnie np uzywam stealtha po stopnieciu auto attaku spellem typu gouge albo np bicu targetu i raptownego odskoczenia i uzycia macra stop attack albo stealtha  w granicach kiedy kasuje mi sie combat. Nie jestem pewny dokladnie jak to w 100%  dziala ale zdaza sie to dosc czesto glownie w sytuacjach resetowania fightu na przeciwniku ktorego wczesniej bilem i reset fightu konczy sie dostaniem dmga przez przeciwnika od mojego auto attacku ( pojedynczy cios  swingiem z weaponu) czasami nawet z odleglosci tak sie dzieje.

**Obecne działanie**: Jak wyzej

**Oczekiwane działanie**: Jak wyzej

**Co należy zrobić, aby odtworzyć ten błąd**:
Jak wyzej
1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Skoro jak wyżej, no to jak wyżej.

**Comment by kevery123** [comment]
Slyszalem ze duzo osob ma taki sam problem wiec nie wiem czemu closed, poprostu nie sprawdzalem tego bo dokladnie nie wiem w jakich sytuacjach to dziala. Jak testowalem to raz sie bugowalo a raz nie wiec poprostu nie wiem

**Comment by ThePuppetMaster** [comment]
Całkowicie olałeś szablon zgłoszenia, dodatkowo opis jest straszliwie nieczytelny i niekonkretny. Takie zgłoszenie wcale nie pomaga w rozwiązaniu problemu. Stąd masz label wontfix. Popraw zgłoszenie, napisz koment, że poprawione, wtedy będziemy dalej rozmawiać co dalej się z tym stanie.
