### ISSUE TITLE
[QUEST] Gathering Leather

### ISSUE THREAD

**Issue by Kokaina** [RaphaelSunwell/Sunwell-BugTracker-SCv2#317]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest od NPC w Thunder Bluff ogólnie działa poprawnie, polega na zeskinnowaniu harpii i otrzymaniu 12x Light Leather. Jedynym ustępstwem jest, że quest powinna pobrać osoba wyłącznie posiadająca profesję Skinning, natomiast mogą go pobrać wszyscy.

**Obecne działanie**: Każdy gracz na lvlu wyższym i równym 8 może pobrać questa niezależnie czy posiada profesję skinning czy nie.

**Oczekiwane działanie**: Tylko gracze z profesją skinningu powinni móc pobrać questa od questgivera.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wbić 8lvl.
2. Pójść do Questgivera po questa.
3. 

**Linki WoWHead/OpenWoW**:

1. QUEST: http://www.wowhead.com/quest=768/gathering-leather
2. Questgiver: http://www.wowhead.com/npc=3050

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://s18.postimg.org/wpq9hcf2h/Wo_WScrn_Shot_120916_002523.jpg

**Comment by ThePuppetMaster** [comment]
Label enhancement ze względu na marginalną szkodliwość buga.

**Comment by Shon-su** [comment]
poprawiony
