### ISSUE TITLE
[QUEST] Redemption

### ISSUE THREAD

**Issue by k3lus** [RaphaelSunwell/Sunwell-BugTracker-SCv2#318]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: NPC Tirion prosi o wysłuchanie swojej opowieści. Brak opcji dialogowej z npc uniemożliwia ukończenie questa.

**Obecne działanie**: Po zaakceptowaniu questa od npc Tirion Fordring, nie pojawia się opcja dialogowa, która umożliwia ukończenie zadania.

**Oczekiwane działanie**: Po zaakceptowaniu questa od npc Tirion Fordring powinna pojawić się u niego opcja dialogowa (mała ikonka "białego dymku", która po kilkukrotnym kliknięciu (wysłuchanie historii) powinna flagować quest jako "complete")

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wykonać od niego 3 poprzednie questy.
2.  Zaakceptować quest "Redemption"

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/quest=5742/redemption#comments
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
![wowscrnshot_120916_003217](https://cloud.githubusercontent.com/assets/16786142/21032280/d57e1836-bda8-11e6-8570-5c385f960978.jpg)

**Comment by ThePuppetMaster** [comment]
Potwierdzam.

**Comment by Kimik1** [comment]
Trzeba usiąść :)

**Comment by ThePuppetMaster** [comment]
Rzeczywiście! Tego się nie spodziewałem...
