### ISSUE TITLE
[NPC] Spirit of Ar'tor

### ISSUE THREAD

**Issue by Philosophers** [RaphaelSunwell/Sunwell-BugTracker-SCv2#319]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po wykonaniu questa Demonic Crystal Prisons powinien pojawić się NPC "Spirit of Ar'tor", lub powinien on tam po prostu być, tymczasem NPC tam nie ma i nie pojawia się on po interakcji.

**Obecne działanie**: NPC nie ma, ani nie pojawia się po wykonaniu questa

**Oczekiwane działanie**: duch NPC powinien stać obok ciała, lub pojawić się po interakcji

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wykonać cały chain zaczynający się od questa "The Hand of Gul'dan", aż do questa "Ar'tor, Son of Oronok"
2. Oddać powyższy quest do ciała NPC Ar'tor, Son of Oronok i wykonanie follow-up questa, Demonic Crystal Prisons
3. W tym momencie powinien pojawić się NPC Spirit of Ar'tor, lecz jego zwyczajnie nie ma- to jest problem.

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/quest=10681/the-hand-of-guldan
2.  http://www.wowhead.com/quest=10527/artor-son-of-oronok
3.  http://www.wowhead.com/quest=10528/demonic-crystal-prisons
4.  http://wowwiki.wikia.com/wiki/Ar'tor_Torn-heart
5.  http://wowwiki.wikia.com/wiki/Spirit_of_Ar%27tor

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 30|51 Shadowmoon Valley

**Comment by Kokaina** [comment]
Działa, aby zobaczyć duchy trzeba założyć Spectrecles :)

**Comment by Philosophers** [comment]
Nie, nie działa, pochopne zamknięcie na bazie jednego komentarza. Testowałem to z założonymi goglami, obleciałem całe Illidari point z trackingiem na low level quests na wypadek gdyby stał w niepoprawnym miejscu, dowód tutaj:
http://imgur.com/a/Zd0UJ

**Comment by Kokaina** [comment]
Ok finalnie quest i npc działają poprawnie (widać go tylko w qitemie Spectrecles 30719). Jedyny odstępstwem od normy jest to, że npc, mimo że jest "martwy" to mogą go zabić pobliskie moby - a nie powinny! Dlatego go nie było :) pozdrawiam
