### ISSUE TITLE
[QUEST] Lard Lost His Lunch

### ISSUE THREAD

**Issue by Fleffy3001** [RaphaelSunwell/Sunwell-BugTracker-SCv2#32]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Duża ilość addów przy tym quescie.

**Obecne działanie**: Możliwość zespawnowania niezliczonej liczby addów co uniemożliwia zrobienie danego questa innym graczom

**Oczekiwane działanie**: Ograniczenie ilości danych addów na danej wysepce aby umożliwić graczom zrobienie tego questa

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zacząć Questa
2. Podejść na miejsce wykonania Questa i klikać niezliczoną ilość razy na Lard's Picnic Basket
3. Uniemożliwić innym graczom zrobienie tego Questa samodzielnie bez pomocy przynajmniej 60/70 lvl 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=7840/lard-lost-his-lunch
2. http://www.wowhead.com/object=179910/lards-picnic-basket
3. http://www.wowhead.com/npc=14748/vilebranch-kidnapper

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 84.42, 40.08, The Hinterlands

**Comment by Mithras2801** [comment]
Zgodzę się lecz NPC powinny być możliwe do przyzwania jeśli wcześniejsze zostały zabite.

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane dzisiaj (tj. 27.01) około 6 rano.
