### ISSUE TITLE
[Panel gracza] Ban: loading error

### ISSUE THREAD

**Issue by patitt** [RaphaelSunwell/Sunwell-BugTracker-SCv2#320]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
W panelu gracza widnieje w rubryce Ban: Loading error... ale do gry można się normalnie logować wydaje mi się że to jakiś błąd na stronie.
**Obecne działanie**: Problem polega na tym że chyba każdy ma takie coś bo po stworzeniu nowego konta też to jest. Screen: http://i65.tinypic.com/30atmiv.jpg
**Oczekiwane działanie**: W tej rubryce powinien być locking system

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Utworzyć nowe konto/zalogować się na konto
2. Wejść do panelu
3. Widnieje wyraźnie jakiś Ban.

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Kougraa** [comment]
Tak, każdej osobie wyświetla się taka informacja.
