### ISSUE TITLE
[QUEST][NPC] Battle of the Crimson Watch

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#321]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Brak dialogów u NPC związanych z tym questem.
**Obecne działanie**: 
Brak dialogów u NPC związanych z tym questem. 
**Oczekiwane działanie**: 
NPC powinny coś tam gadać.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić quest chain zaczynający się od wydropienia [q itemu](http://www.wowhead.com/item=31345/the-journal-of-valzareq) z [NPC](http://www.wowhead.com/npc=21979/valzareq-the-conqueror)

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/object=185126/crystal-prison#starts](http://www.wowhead.com/object=185126/crystal-prison#starts)
2. [http://www.wowhead.com/quest=10781/battle-of-the-crimson-watch](http://www.wowhead.com/quest=10781/battle-of-the-crimson-watch)

Dialogi:

`Marcus Auralion whispers: Quickly! Get to the middle of the platform! Illidan's fury is soon to be unleashed!`

_llidan Stormrage appears, manifesting through one of the Fel Crystals_

`Lord Illidan Stormrage yells: What manner of fool dares stand before Illidan Stormrage? Soldiers, destroy these insects!`

_Several Illidari Soldiers appear and engage the party._

`Lord Illidan Stormrage yells: You are no challenge for the Crimson Sigil. Mind breakers, end this nonsense!`

_Two Mind Breakers appear and engage the party._

`Lord Illidan Stormrage yells: Run while you still can. The highlords come soon...`

_Four Illidari Highlords appear and engage the party._

`Lord Illidan Stormrage yells: Torloth, your master calls!`

_Torloth the Magnificent appears and kneels before the Fel Crystal._

`Torloth the Magnificent says: At your command my liege...
Lord Illidan Stormrage says: Destroy them, Torloth. Let loose their blood like a river upon this hallowed ground.
Torloth the Magnificent says: As you desire, Lord Illidan.
Torloth the Magnicicent says: For Lord Illidan, I would sacrifice even this magnificent physique. On this day, you will fall - another victim of Torloth...`

_Torloth the Magnificent attacks the party.`_

`Lord Illidan Stormrage yells: So you have defeated the Crimson Sigil. You now seek to challenge my rule? Not even Arthas could defeat me, yet you dare to even harbor such thoughts? Then I say to you, come! Come <name>! The Black Temple awaits...
Marcus Auralion says: Return to Shattrath, hero. Seek out the wisdom of A'dal.`

**Comment by kovaq** [comment]
Potwierdzam brak dialogow. Szkoda, ze nie mam pelnego nagrania (OBS sie zawiesil), ale tak, nie ma zadnego dialogu. Co wiecej, w momencie gdy zresetuje sie walke (w tym wypadku akurat feign death, pet martwy) moby wracaja na swoje miejsce. Gdy sie je zabije nie wychodzi kolejna fala. Postanowilem wyrzucic questa i wziac go ponownie, ale tym razem encounter nawet nie zaszczycil mnie odpaleniem sie.
https://youtu.be/F6N2oCZ02-k

**Comment by Shon-su** [comment]
poprawione nie dograne jeszcze
