### ISSUE TITLE
[NPC] 16904 - Unyielding Footman (brak broni i tarczy)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#322]
**Opis**: Jednostki używają normalnie umiejętności lecz brak broni i tarczy.

**Obecne działanie**: j/w

**Oczekiwane działanie**: NPC powinny mieć zestaw broni tak jak na screenie z linku wowhead

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Iść na miejsce
2. Zaatakować npc (must be)
3. Zobaczyć broń

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=16904/unyielding-footman

**Comment by Mithras2801** [comment]
Bug czasem wskakuje czasem nie. raz jest zestaw broni raz nie.

**Comment by Shon-su** [comment]
poprawione
