### ISSUE TITLE
[NPC] 16906 - Unyielding Knight (brak broni)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#323]
**Opis**: Zdarza się często, że npc wgl nie ma broni, a czasem ma.

**Obecne działanie**: NPC bije bez broni czasem.

**Oczekiwane działanie**: Zawsze npc powinien mieć broń.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Iść na miejsce
2. Znaleźć NPC (zaatakować)
3. Sprawdzić na kilku czy mają broń

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=16906/unyielding-knight

**Comment by Shon-su** [comment]
poprawione
