### ISSUE TITLE
[Instance]Culling of stratholme. Loot z malganisa przepada jeśli nie zostanie szybko zrollowany

### ISSUE THREAD

**Issue by DebowyMocny** [RaphaelSunwell/Sunwell-BugTracker-SCv2#325]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Jeśli po pokonaniu malganisa pojawia się skrzynka z lootem. Jesli jakiekolwiek itemy nie zostaną szybko zrollowane zanim skrzynka zniknie, to loot przepada. 

**Oczekiwane działanie**: Loot nie powinien przepadać
**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Przjesc culling of stratholme
2.  Pokonać malganisa 
3. Jak pojawi się loot z krzynki to wystarczy że jakikolwiek gracz nie wybierze need/greed/pass zanim skrzynka zniknie, to loot przepada.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=26533/malganis
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
#578
