### ISSUE TITLE
[ITEM]Hateful Gladiator's Longbow

### ISSUE THREAD

**Issue by zbynew** [RaphaelSunwell/Sunwell-BugTracker-SCv2#326]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Itemu poprostu nie da się używać na dystansie.

**Obecne działanie**: Bow strzela dopiero w range 1-5 yd od przeciwnika, dodatkowo sprawdziłem czy zmiana amunicji czegoś nie zmieni. Okazuje się, że w tym zasięgu bow działa nawet bez amunicji.

**Oczekiwane działanie**: Bow powinien strzelać w zasięgu ranged, nie melee.
**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Zmienić range działania :)
2.  Naprawić możliwość używania przedmiotu bez amunicji
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=42489/hateful-gladiators-longbow
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by xsitdev** [comment]
Usun cache.
