### ISSUE TITLE
[TALENT][MAGE] Permafrost

### ISSUE THREAD

**Issue by morrk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#328]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Talent dla maga permafrost ma zbugowny debuff na przeciwniku (i efekt?)

**Obecne działanie**: Na frostblocie jest napisane ze slowuje o 44% (poprawnie) lecz na przeciwniku debuff z frostbolta pokazuje tylko 40%. Nie mam nawet jak sprawdzic czy aby na pewno slow sie zwiekszyl, 4% ciezko zobaczyc "na oko".

**Oczekiwane działanie**: Debuff po frostbolcie na przeciwniku powinien pokazywac to co tooltip na spellu po najechaniu na niego

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Dac talent w permafrost w drzewku frost magiem
2. Zacastowac frostbolta
3. Najechac myszka na slowujacy efekt spella

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=11175
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Nuy** [comment]
Działa. To tylko wizualny bug.

**Comment by ThePuppetMaster** [comment]
Sprawdzone, działa poprawnie.
