### ISSUE TITLE
[Quest] Red Snapper - Very Tasty!

### ISSUE THREAD

**Issue by Vorczu** [RaphaelSunwell/Sunwell-BugTracker-SCv2#33]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Quest podczas którego nalezy złapac 10 szt. Red Snapper'ów. Szans ana wyłowienie murlocka który po zabiciu dropnie 1 szt.

**Obecne działanie**: Murlocki po zabiciu odbiegają i znikają.

**Oczekiwane działanie**: Murlocki po zabiciu powinny zostawica corpsy z których jest możliwość wylootowania quest itemu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=9452
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Zgadzam się. Jeśli nie złowimy ryby to wyskakuje murlock, który po zabiciu powinien dropić rybę do Q. Murlocki znikają.

**Comment by kovaq** [comment]
Murloki daja nam q item, natomiast problem jest z wyzej wymienionym znikaniem:
https://youtu.be/K2pfDL_XJH4?t=35s
Trzeba miec naprawde refleks, by zlapac loot, nie mowiac juz o celowaniu w rybke.
(reszta filmiku nie przedstawia juz nic, gdyz nawet jak wyskoczyl murlok, to 80 lvl zazwyczaj oneshotowal, minusy ostatniego szlifu ;p)

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane dzisiaj (tj. 27.01) około 6 rano.
