### ISSUE TITLE
[QUEST][NPC] No Fly Zone - Bone Gryphon

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#330]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Do wykonania [questa](http://www.wowhead.com/quest=12815/no-fly-zone) dostaliśmy gryfa który ma możliwość atakowania inne NPC niż zamierzono.
**Obecne działanie**: 
[Film](https://www.youtube.com/watch?v=ofIn_HWgI_w&feature=youtu.be)
**Oczekiwane działanie**: 
[Bone Gryphon](http://www.wowhead.com/item=40600/bone-gryphon) powinien tylko i wyłącznie zadawać obrażenia [Onslaught Gryphon Rider](http://www.wowhead.com/npc=29333/onslaught-gryphon-rider)
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa
2. Polecieć do wyznaczonego miejsca przez q
3. Zadać obrażenia innym NPC niż Onslaught Gryphon Rider

**Linki WoWHead/OpenWoW:**

1. [http://www.wowhead.com/spell=48766](http://www.wowhead.com/spell=48766)
2. [http://www.wowhead.com/spell=54469/plague-strike](http://www.wowhead.com/spell=54469/plague-strike)

**Comment by Shon-su** [comment]
poprawione
