### ISSUE TITLE
[QUEST][NPC] Gluttonous Lurkers - Zul'Drak Rat 

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#336]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Zul'Drak Rat, po zbieraniu ich na **mouncie** nie znikają i można je farmić.
**Obecne działanie**: 
[Film](https://www.youtube.com/watch?v=dOTHoDazuPQ&feature=youtu.be)
**Oczekiwane działanie**: 
Po zebraniu, Zul'Drak Rat powinny zniknąć.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. To co na filmie

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/npc=28202/zuldrak-rat](http://www.wowhead.com/npc=28202/zuldrak-rat)
2. [http://www.wowhead.com/quest=12527/gluttonous-lurkers](http://www.wowhead.com/quest=12527/gluttonous-lurkers)

**Comment by Shon-su** [comment]
poprawione
