### ISSUE TITLE
[QUEST][NPC] Escape from Durnhold

### ISSUE THREAD

**Issue by lierox90** [RaphaelSunwell/Sunwell-BugTracker-SCv2#337]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zdarzyła się sytuacja że Thrall nam zginał, zgodnie z tym co powinno być pojawia się ten NPC , który na początku daje Quest i u którego oddaje się ten quest, by wskrzesić martwego Thralla i pozwolić graczom po zrespieniu się powtórzyć event (fragment w którym przyzywa się ostatniego bossa), niestety po wskrzeszeniu Thrall nie posiada opcji dialogowej by ponownie rozpocząć event.

**Obecne działanie**: Gdy Thrall zginie i NPC z CoT wskrzesi go by zresetować encounter Thrall nie posiada opcji by ponownie aktywować encouter,

**Oczekiwane działanie**: Po śmierci i wskrzeszeniu powinno dać sie ponownie aktywować Thralla by kontynuować event

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Eskotuj Thralla do ostatniego miasta
2. Po rozpoczeciu ostatniej sekwencji aktywujacej bossa pozwol Thrallowi zginąć

**Linki WoWHead/OpenWoW**:

1. [WoW Wiki](http://wowwiki.wikia.com/wiki/Escape_from_Durnholde_Keep#Quests)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 51.2, 29.8 - ta sama lokalizacja co [Taretha](http://www.wowhead.com/npc=18887/taretha)

**Comment by kovaq** [comment]
Dziala jak nalezy, Celowo usmiercilem Thralla okolo 15 razy i wciaz wstaje i wciaz pozwala na rozpoczecie wedrowki, niezaleznie, po ktorym checkpoincie umrze.

**Comment by lierox90** [comment]
A w miedzy czasie nie bylo zadnych poprawek wgrywanych ? Spróbuje to
powtórzyć i się odezwę.

06.02.2017 17:54 "kovaq" <notifications@github.com> napisał(a):

**Comment by kovaq** [comment]
Prawdopodobnie byly, dlatego to sprawdzilem na serverze testowym. Na moje juz tego nie odwzorujesz, ale jezeli chcesz - sprawdz :)
