### ISSUE TITLE
[QUEST] 	 Discover Rolf's Fate

### ISSUE THREAD

**Issue by Mathar25** [RaphaelSunwell/Sunwell-BugTracker-SCv2#34]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie można oddać questa. 

**Obecne działanie**: Nie działa

**Oczekiwane działanie**: Po kliknięciu na ciało powinno dać się zakończyć to zadanie. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rozpocząć chain [A Fishy Peril]
2. Dotrzeć do (4) questa  [Discover Rolf's Fate]
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=45/discover-rolfs-fate
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
79, 55 - Ciało Rolfa (albo to co z niego zostało)

**Comment by ThePuppetMaster** [comment]
Powinno już działać.
