### ISSUE TITLE
[ITEM] Hateful Gladiator's Redoubt

### ISSUE THREAD

**Issue by Niekuba** [RaphaelSunwell/Sunwell-BugTracker-SCv2#341]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Item Hateful Gladiator's Redobut (item id: 42569) sprzedawany przez  Nargle Lashcord (npc id: 31863) w kanałach w Dalaran nie posiada jednej ze statystyk (Equip: Restores 14 mana per 5 sec.). Sprawdziłem, że to nie jest wina samego opisu - item po założeniu **nie podnosi statystyk mana per 5**

**Obecne działanie**: Założenie itemu dodaje (poza intellectem oraz staminą): spell power, oraz resillience

**Oczekiwane działanie**: Poza wyżej wymienionymi powinno również dodać 14 mana per 5 sec.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Wejść do Dalaran i spojrzeć na opis itemu.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Hateful_Gladiator's_Redoubt (poprawnie wyświetla statystyki itemu)
2. http://wotlk.openwow.com/item=42569 ( **niepoprawnie** wyświetla statystyki itemu)
3. http://wotlk.openwow.com/item=42570 (ten sam item, tylko o tier wyższy (deadly), który posiada ten stat)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Niekuba** [comment]
Podbijam...

**Comment by ellynd** [comment]
Wszystkie **tarcze** z dopiskiem właśnie Redoubt powinny dawać te dodatkowe mp5, bez tego tarcza jest bezużyteczna, bo bardziej się opłaca kupić Gladiator's Barrier, jest to więc bug, który należałoby naprawić.
