### ISSUE TITLE
[QUEST][NPC] Mor'vek <Ravasaur Trainers> They grown so fast

### ISSUE THREAD

**Issue by femozdw1** [RaphaelSunwell/Sunwell-BugTracker-SCv2#342]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
NPC Mor'vek <Ravasaur Trainers>w Un'goro Crater nie daje kolejnego questu na Venomhide Ravasaur mounta.
**Obecne działanie**: NPC daje 1 questa [Toxic Tolerance] lecz powykonaniu go nie dostaje kolejnego [venomhide eggs] ,przez co nie można dostac glownego questu na jego zdobycie [They Grown So Fast].

**Oczekiwane działanie**: Po wykonaniu questu [Toxic tolerance] powinien byc od razu dostepny [Venomhide eggs] , a po [Venomhide eggs] powinien byc {They Grown So Fast]. lecz po 1 q chain sie urywa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=11701/morvek
2. http://www.wowhead.com/npc=11701/morvek#starts
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by myentos** [comment]
Działa od 3.2 patcha.
