### ISSUE TITLE
[QUEST] Broodling Essence  (Burning Steppes)

### ISSUE THREAD

**Issue by Seavitia** [RaphaelSunwell/Sunwell-BugTracker-SCv2#343]
**Opis**:  Zebranie 8 sztuk broodling essence, używając q itemu (Draco Incarcinatrix 900) na mobie typu broodling (Scalding broodling, black broodling)

**Obecne działanie**:  Item da się użyć na każdym mobie. Dodatkowo drop rate jest zaniżony, lub nie ma go wcale. z 35 mobow scalding broodling wpadly 3 itemy. Z 50 black broodling - zaden.

**Oczekiwane działanie**: Należy użyć q item (Draco Incarcinatrix 900) na mobie, po czym go ubić. Po ubiciu powinien z moba wypaść broodling essence w formie czerwonego kryształu, z którego zbiera się q item o tej samej nazwie. (wg opewow drop rate 11% z black broodling 2% ze scalding broodling) 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac questa
2. Sprobowac go zrobic
3. 

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/quest=4726/broodling-essence
2. http://wotlk.openwow.com/quest=4726
3.

**Comment by Isilion** [comment]
Quest działa prawidłowo.
Problem w tym, że to quest polegający na zabiciu Broodlingów na czas. Więc nie ma co startować do niego jak ma się małe HP. 
Pierwszy raz jak go robiłem, to tak jak przedmówca pisze, wydropiłem quest item z 1 Broodlinga na zabitych ok. 100.
Wróciłem tam na 63 levelu z niezłym wyposażeniem postaci i ....  dropiło z 99% Broodlingów.
