### ISSUE TITLE
[SPELL] Seal of Command

### ISSUE THREAD

**Issue by rekeyf** [RaphaelSunwell/Sunwell-BugTracker-SCv2#345]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Seal of command po aktywacji daje paladynowi pewnego rodzaju cleave na 2 targety. Dziala on poprawnie dla podstawowych atakow jednak niepoprawnie gdy zostal zatriggerowany przez crusader strike/divine storm/judgment.

**Obecne działanie**: Efekt seala jest nakladany dla pojedynczego celu, nie dziala cleave gdy seal of command zostal zatriggerowany przez skill.

**Oczekiwane działanie**: Uzywajac skilla takiego jak np divine storm w grupie mobow kazdy zatriggerowany seal of command ma zatriggerowac 2 kolejne, ktore jednak nie zatriggeruja juz zadnego.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Sprawdzic czym sie rozni zatriggerowany seal of command przez auto attack i porownac go z tym zatriggerowanym przez skill
2.  Poprawic seal of command zatriggerowany przez skill
3.  Fixed?

**Linki WoWHead/OpenWoW**:

1.  http://wotlk.openwow.com/spell=20375
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by DinozaurWKamizelce** [comment]
Jakiś dowód?
W opisie spella jest, że ma on być triggerowany jedynie przez "attacks or abilities that strike single target" z tego co wiem to u paladyna takimi uderzeniami są: meele strike, crusader strike, judgement, hammer of wrath, uderzenie tarczą.
Nie wiem jak hammer of justice, niby nie zadaje on obrazeń, ale spełnia definicję z opisu
Nie wiem jak hand of reckoning (czy jest to abilities czy spell)

Seal nie powinien triggerować ze spelli (np exorcism) ani zdolności mulititarget (wspomniany Diwine Storm, czy Hammer of righteous ) Jeżeli tak jest to jest to błąd.

Nie doexpiłem jeszcze palka, więc na razie nie wiem jak jest i nie sprawdzę tego, ale domaganie się by Talent triggerował ze zdolności, która jest sprzeczna z opisem, bez żadnych dowodów na to jest rażącą próbą OP paladyna...
