### ISSUE TITLE
[QUEST] Keep Thornfang Hill Clear!

### ISSUE THREAD

**Issue by plessico** [RaphaelSunwell/Sunwell-BugTracker-SCv2#346]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W Queście chodzi o zabójstwo 8x Thornfang Ravager i 8x Thornfang Venomspitter

**Obecne działanie**: Zabijając Thornfang Ravanger nie zalicza ich do puli zabitych mobów, więc questa nie da się skończyć

**Oczekiwane działanie**: Zabijając owe moby powinno mi ich zaliczać w celu skończenia questa

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do Helfire Peninsula
2. Przyjąć quest Keep Thornfang Hill Clear!
3. Spróbować zabić Thornfang Ravagera

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10159/keep-thornfang-hill-clear
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by myentos** [comment]
Niedawno robiłem tego q, tak samo inni gracze i nie było żadnych problemów. Jesteś pewien, że zabijaleś odpowiednie moby?  Albo czy nie byłeś w raidzie?
