### ISSUE TITLE
[Quest] Shadow Vault Decree

### ISSUE THREAD

**Issue by Gerwazy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#348]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie można ukończyć questu. 
EDIT: Okazuje się, że faktycznie działa ale dużo dalej aniżeli na filmach wowhead.

**Obecne działanie**: Nie da się użyć quest itemu - odczytać Shadow Vault Decree.

**Oczekiwane działanie**: Po użyciu quest itemu powinien zrespić się mob, którego trzba zabić.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pobrać quest 
2. Użyć quest item 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12943/shadow-vault-decree
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y,  Z, [Map)**:] https://imgur.com/a/lm7Jj

**Comment by myentos** [comment]
Działa, robiłem 2 dni temu. Musisz stanąć przed Thanem na wysokości tych 2 kolumn drzewnych za Tobą.

**Comment by Gerwazy** [comment]
Okazuje się, że faktycznie działa ale dużo dalej aniżeli na filmach wowhead.
