### ISSUE TITLE
[NPC] 18257 - Gutripper 

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#349]
**Opis**: w/w npc daje się fearować i można zastosować na nim inne CC

**Obecne działanie**: Da się stosować na tym NPC różne CC przez co jest łatwiejszy.

**Oczekiwane działanie**: Ta jednostka jak pozostałe 2 nie powinna ulegać CC. Powinna być immune na CC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Znaleźć ptaszyne
2. Stosować CC różne.

**Linki WoWHead/OpenWoW**:
Jednostki elitarne do all Q mastery: (nieprawidłowe) 
1. http://www.wowhead.com/npc=18257/gutripper (działa CC)

prawidłowe:
2. http://www.wowhead.com/npc=18258/bachlor 
3. http://www.wowhead.com/npc=18259/banthar

Screeny z CC:
http://imgur.com/a/qy5eB

**Comment by myentos** [comment]
Dokładnie 

> This is not a two-man elite quest. I would recommend at least 4 players to successfully down him. I can solo kill elites a level above me, but this guy is in a different category. Immune to CC, hits like a truck.

>

**Comment by Shon-su** [comment]
poprawione
