### ISSUE TITLE
[Quest] Relic of the Earthen Ring

### ISSUE THREAD

**Issue by Shatterx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#35]
Obecne działanie: Nie można oddać questa u NPC Farseer Javad

Oczekiwane działanie: Quest powinien być możliwy do oddania u w/w NPC.

Co należy zrobić, aby odtworzyć ten błąd:

1. Wziąć quest Relic of the Earthen Ring
2. Podejść do NPC Farseer Javad
3. 

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/quest=14111
2. http://wotlk.openwow.com/npc=35073
3. 

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
-4720 -1150 502
https://zapodaj.net/ba983f90c7678.jpg.html

**Comment by ThePuppetMaster** [comment]
Patch 3.2.0 (04-Aug-2009): Added.
