### ISSUE TITLE
Carbonite

### ISSUE THREAD

**Issue by Sinnestra** [RaphaelSunwell/Sunwell-BugTracker-SCv2#351]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Witam , mam problem z chatem często wyskakuje mi na generalu "no player XXXX is currently playing" i zawala mi to cały czat i to co kilka minut  myślę że to wina Carbonite ale nie powinno tak być

**Oczekiwane działanie**: Brak wpisów "no player XXX is currently playing"

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Nie związane z serverem.
