### ISSUE TITLE
[ITEM] Hateful Gladiator's Redoubt

### ISSUE THREAD

**Issue by Bainit123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#353]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Tarcza dostępna u NPC nie daje mp5.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
![image](https://cloud.githubusercontent.com/assets/22755789/21081468/ee65c2a6-bfc7-11e6-9b39-26473d9a7421.png)
Tarcza nie daje mp5. 

**Oczekiwane działanie**: Obecnie tarcza ta jest dostępna, jednakże dostępna jest również Hateful Gladiator's Barrier, która od tarczy w tytule różni się tym że ma dodatkowo +34 crit rating. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Nie jestem na 100% pewien czy jest to błąd, na linku z openwowa tarcza nie ma mp5, jednak jest to trochę dziwne że dostępna jest tarcza która jest jak to się mówi "stricktly better", z tym samym item lvl i kosztuje tyle samo.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1.  [http://wowwiki.wikia.com/wiki/Hateful_Gladiator's_Redoubt](http://wowwiki.wikia.com/wiki/Hateful_Gladiator's_Redoubt)
2. [http://wotlk.openwow.com/item=42569](http://wotlk.openwow.com/item=42569)
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Niekuba** [comment]
Powtórzone #341
