### ISSUE TITLE
[NPC] Fel Reaver

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#354]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Fel Reaver to 70lvl elite, który chodzi po całym Hellfire Peninsula.

**Obecne działanie**: Fel Reaver znika z pola widzenia po około 60yardach tak jak zwykły npc.

**Oczekiwane działanie**:  Fel Reaver powinien być widoczny z odległości całej mapy, jeżeli znajdujemy się w hellfire peninsula powinniśmy zawsze móc zobaczyć Fel Reavera, nie jest to jakiś poważny bug wpływający na rozgrywkę jednak uważam, że to absolutnie bardzo fajna sprawa móc zobaczyć z dużej odległości spacerującego Fel Reavera po hellfire.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Zbliżyć się do Fel Reavera
2. Obserwować po jakim czasie zniknie z pola widzenia
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=18733
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Danieloses** [comment]
Dodam jeszcze, że ogólnie im mob jest większy tym powinien być większy zasięg, z którego go można zobaczyć. Np, Thrym gigant z Zul'Drak powinien być widoczny nawet z dalaranu itd. Na sunwellu wydaje się, że każdy pojedynczy mob ma taki same range ustawiony.

**Comment by ThePuppetMaster** [comment]
Reference?
