### ISSUE TITLE
[DUNGEON]Stormwind Stockade - Bossowie nie mają loota.

### ISSUE THREAD

**Issue by kalias21** [RaphaelSunwell/Sunwell-BugTracker-SCv2#355]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po zabicia bossa podczas instancji Stormwind Stockade, pokonani bossowie nie zostawiają loota.

**Obecne działanie**: Bossowie nie zostawiają nic - są zwykłe 'puste ciała'.

**Oczekiwane działanie**: Bossowie powinni zostawiać po sobie przedmioty rzadkie.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Aby odtworzyć wystarczy wejść poprzez Dungeon Findera na instancję Stormwind Stockade.
2. Pokonać jednego z bossów.
3. Spróbować zagarnąć loot.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/the-stockade
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by jubasek21** [comment]
Link, który wstawiłeś jest z cata, a insta różni się od tej z pre-cata. Tutaj link z pre-cata: http://wowwiki.wikia.com/wiki/The_Stockade_(original)

**Comment by jubasek21** [comment]
1. http://wowwiki.wikia.com/wiki/The_Stockade_loot_(original) - loot powinien wypadać tylko z dwóch bossów.
2. http://wowwiki.wikia.com/wiki/The_Stockade_(original) - link do Stockade Pre-Cata.

**Comment by Danieloses** [comment]
Stockade to insta gdzie masz jakieś 6-8 questów, to z nich są nagrody, większość bossów dropi quest itemy.
