### ISSUE TITLE
[QUEST] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Mojsik** [RaphaelSunwell/Sunwell-BugTracker-SCv2#356]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest nie działa poprawnie, blokuje chain questów.

**Obecne działanie**: NPC znikają gdy się do nich zbyt blisko podleci.

**Oczekiwane działanie**: NPC powinny poruszać się po terenie questu i po podleceniu do nich questowym mountem i wciśnięci skilla "Rescue Villager" przypisanego pod klawisz 1 NPC powinien zostać zabrany na mounta a następnie odwieziony do miejsca wzięcia questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest
2. Poszukać NPC na terenie
3. Podlecieć pod NPC, po czym npc zniknie

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12237
2. http://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
83, 45, Dragonblight

**Comment by myentos** [comment]
https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/189
