### ISSUE TITLE
[Quest] Basic chemistry

### ISSUE THREAD

**Issue by Bronies27** [RaphaelSunwell/Sunwell-BugTracker-SCv2#358]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Quest item w momencie odpalenia zaczyna castowanie lecz go nie kończy

**Obecne działanie**: To samo co wyzej

**Oczekiwane działanie**: Quest item zakończy castowanie i kocioł z plagą wyrzuci z siebie moby

**Co należy zrobić, aby odtworzyć ten błąd**: 

1.  Podejść pod kocioł
2.  użyć q itemu
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13279/basic-chemistry
2. 
3.

**Comment by Kozakko** [comment]
Z tego co wiem jest to jedyny q gdzie faktycznie potrzeba 2 osób do ukończenia, nie da się go skończyć solo.

**Comment by Kokaina** [comment]
Zgadza się bo podczas encountera trzeba użyć quest itemu drugi raz aby podtrzymać "efekt na kotle" a cd na questitemie jest za długi by to wysolować. Nie mniej zgłoszenie jest poprawne gdyż nie można poprawnie użyć itemu. 1 z 2 niedziałających Q w Icecrown.

**Comment by RaphaelSunwell** [comment]
Quest działa.
