### ISSUE TITLE
[QUEST][NPC] Battle at Valhalas: Final Challenge

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#359]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Aby ukończyć quest [Battle at Valhalas: Final Challenge](http://www.wowhead.com/quest=13219/battle-at-valhalas-final-challenge) mamy za zadanie pokonać [Prince Sandoval](http://www.wowhead.com/npc=14688/prince-sandoval)
**Obecne działanie**: 
Prince Sandoval pojawia się, ale zaraz znika. Nie ma walki, ale quest zalicza.
[http://i.imgur.com/LyiIvSL.jpg](http://i.imgur.com/LyiIvSL.jpg)
**Oczekiwane działanie**: 
Powinna odbyć się walka
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest (długi chain) (początek: [http://www.wowhead.com/quest=12887/its-all-fun-and-games](http://www.wowhead.com/quest=12887/its-all-fun-and-games) )
2. Udać się na arenę
3. Obserwować

**Comment by Baggedmilk** [comment]
miałem taki sam problem z tym questem oraz przy pierwszym quescie na tej arenie http://www.wowhead.com/quest=13214/battle-at-valhalas-fallen-heroes po zginieciu i wroceniu do ciala npc znikly i zaliczylo questa. prawdopodobnie z kazdym questem na tej arenie mozna tak zrobic
