### ISSUE TITLE
[Talenty] Talenty widziane przez drugiego gracza. 

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#36]
**Opis**: Visual talentow u innych graczy.

**Obecne działanie**: Gracz nie ma możliwości sprawdzenia talentów innych graczy.

**Oczekiwane działanie**: Gracz powinienem mieć możliwość sprawdzenia talentów innego gracza.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Prawym przyciskiem myszy kliknąc na portret kolegi/koleżanki.
2. Użyć opcji 'Inspect'.
3. Wybrać zakładkę 'Talents'.

**Linki WoWHead/OpenWoW**:

Nie dotyczy.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

Nie dotyczy.

**Comment by ThePuppetMaster** [comment]
#8
