### ISSUE TITLE
[QUEST] freedom for all creatures

### ISSUE THREAD

**Issue by Seavitia** [RaphaelSunwell/Sunwell-BugTracker-SCv2#361]
**Opis**: Quest W Feralas - polega na uwolnieniu Captured Sprite darter w towarzystwie NPC Kindal Moonveaver z obozu Gromtotemów. Ma się na to 6 minut. NPC i 6 uwalnianych mobków musi przeżyc.

**Obecne działanie**: Po dotarciu do klatki i wybiciu wszystkiego co zagraża npc, NPC siada obok klatki. Gdy otworzy się ją - mobki wylatują, odlatują kawałek, po czym znikają. Nie są zaliczane jako uwolnione. Około minuty przed zakończeniem czasu npc przechodzi na drugą stronę klatki i pojawia się szary znak zapytania. W momencie gdy konczy się czas - quest jest failed, 
Wypuszczenie mobkow dopiero po pojawieniu sie znaku zapytania nic nie daje. Próba rzeczywistej ochrony (czyt: ubijanie atakujących na bieżąco - bez uprzedniego wyczyszczenia) podobnie.

**Oczekiwane działanie**: Po wzięciu questa, wraz z npc. powinno dotrzeć sie klatki z mobami do uwolnienia, po drodze wybijajac agresywne moby. Za pomocą otrzymanego klucz otwiera się drzwi klatki, po czym mobki wylatują na wolność. Trzeba dopilnować, żeby 6 z nich przeżyło ucieczkę (oraz npc. dający questa, który nam towarzyszy)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Spróbować wykonać questa
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=2969/freedom-for-all-creatures
2. 
3. 

Dodam tu jeszcze, ze quest jest dośc istotny dla kolekcjonerów - ze względu na nagrode po zakońzceniu chaina - companion Sprite darter hatchling

**Comment by Shon-su** [comment]
15.02.2017 quest działa na serwerze testowym, bez żadnych udziwnien po prostu doeskortowałem npc-a, uwolniłem mobki z klatki, poczekałem aż 6 wyleciało i zaliczyło
