### ISSUE TITLE
[REPUTACJA] Netherwing

### ISSUE THREAD

**Issue by DajMacha** [RaphaelSunwell/Sunwell-BugTracker-SCv2#366]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Po wykonaniu chaina questów na reputację, otrzymujemy 42k reputacji co daje nam reputację neutral. Jednak moby w wiosce w Netherwing Ledge dalej są czerwone. 

Ukończyłem questa Ally of the Netherwing. 

**Obecne działanie**: Moby są agresywne

**Oczekiwane działanie**: Po wbiciu reputacji moby powinny być neutralne

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ukończyć chain
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10811/seek-out-neltharaku
2. 
3. 
![wowscrnshot_121316_003741](https://cloud.githubusercontent.com/assets/24534112/21121409/7c45ad3e-c0cc-11e6-89c7-4fb346fe097c.jpg)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by FrostyGM** [comment]
Potwierdzam, było już sporo zgłoszeń na ten temat.

**Comment by Shon-su** [comment]
13.02.2017 18:09 realm Ostatnie Szlify
"Buff" iluzji bycia orkiem jest poprawnie nakładany przy wkraczaniu na obszar wioski co sprawia że orki są friendly
