### ISSUE TITLE
[QUEST][NPC] The Deathstalkers (5 of 5) 

### ISSUE THREAD

**Issue by Widzi** [RaphaelSunwell/Sunwell-BugTracker-SCv2#368]
![b1](https://cloud.githubusercontent.com/assets/24544654/21140438/57bad342-c138-11e6-9b2e-4477a802c30f.png)
![bez tytulu](https://cloud.githubusercontent.com/assets/24544654/21140439/57be664c-c138-11e6-95c6-aa04a1a69a4d.png)

[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest powinien kończyć się u Varimathras'a (55.4, 97.2), a jak na razie kończy się u Aleric Hawkins'a (55.7, 92.8) (którego nie ma).

**Obecne działanie**: Quest kończy się u niewłaściwego NPC.

**Oczekiwane działanie**: Zmienienie ukończenia questa u Varimathras'a.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wypełnić wszystkie questy dla rouge pt. The Deathstalkers (Zaczynają się w Undercity w the Rogues' Quarter u NPC (83.5, 69.1))
2. Przy ostatnim quescie z tej serii udać się do miejsca docelowego by wykonać quest
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=1978
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
(55.4, 97.2), (55.7, 92.8)

**Comment by Shon-su** [comment]
dodany
