### ISSUE TITLE
[QUEST] The Last Line Of Defense - stuck

### ISSUE THREAD

**Issue by charmelina** [RaphaelSunwell/Sunwell-BugTracker-SCv2#370]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po oddaniu Q nasza postać nie może się ruszyć

**Obecne działanie**: Po zrobieniu questa ( http://www.wowhead.com/quest=13086/the-last-line-of-defense) jak należy powracamy do NPC aby oddać questa co skutkuje stuckiem, który jedynie da się rozwiązać poprzez Alt + F4.

[IMG]http://i68.tinypic.com/2wdc961.jpg[/IMG]

**Oczekiwane działanie**: Nie powinień się zdarzyć żaden stuck.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć Q od NPC
2. Zrobić Q poprawnie
3. Oddać Q

**Comment by kovaq** [comment]
NIewidzialna tekstura uprzykrzajaca zycie, znam ten przypadek, ale mimo najwiekszych wysilkow nie moglem jej teraz znalezc, co sugeruje, ze zostala naprawiona.

**Comment by Shon-su** [comment]
#266
