### ISSUE TITLE
[QUEST] Evil Dravs Near

### ISSUE THREAD

**Issue by Blazkow** [RaphaelSunwell/Sunwell-BugTracker-SCv2#371]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Nie można oddać zrobionego questa do NPC-Oakun (znak zapytania nad Npc cały czas jest szary, mimo iż quest jest complete)
**Obecne działanie**: nie można oddać gotowego questa (NPC "nie widzi" quest itema w plecaku który jest wymagany do zaliczenia zadania

**Oczekiwane działanie**: po zabiciu wymaganego moba powinniśmy móc go oddać u npc
(jedyne wymaganie - należy mieć w plecaku quest item dzięki któremu sumonowaliśmy moba z questa)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wziąść questa od Npc - Oakun
2. wydropić 20 czaszek z mobów

2. wydropić 20 czaszek z mobów
3. sumonować elitke we wskazanym miejscu za pomocą quest itema
4. po zabiciu elity i mając quest item w plecaku powinniśmy bez problemu oddać go u Npc

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10923/evil-draws-near
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 31.08,76.46

**Comment by kovaq** [comment]
http://screenshooter.net/103037023/lufyfyj
Potwierdzam.

**Comment by Shon-su** [comment]
poprawione
