### ISSUE TITLE
[QUEST] Escape Through Force

### ISSUE THREAD

**Issue by XevL** [RaphaelSunwell/Sunwell-BugTracker-SCv2#372]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
After the NPC leave the cave he start spamming this message **"HERE THEY COME!"**.
NPC not attacking MOBS that attack him.
After he approach to the road he disappeared the quest don't complete.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
NPC should attack back the MOBS.
When he reach the road a message should pop **"We made it...Thank you again."** Quest Completed!

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Here is 2 video showing how the quest should work
https://www.youtube.com/watch?v=TwSbAkMGDGY
Watch from 5:30 https://www.youtube.com/watch?v=8zDB-ucQAqw&feature=youtu.be&t=5m30s

**Co należy zrobić, aby odtworzyć ten błąd**:
Start the quest.

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/quest=994/escape-through-force
2. http://wotlk.openwow.com/quest=994

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
45;85.3 at Darkshore.

**Comment by kovaq** [comment]
#98

**Comment by Shon-su** [comment]
poprawione
