### ISSUE TITLE
[QUEST][NPC] 19055 Windroc Matriarch

### ISSUE THREAD

**Issue by fikaczu** [RaphaelSunwell/Sunwell-BugTracker-SCv2#373]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Są trzy ptaszki w jednym miejscu przez co ginie się za każdym razem kiedy chce się porozmawiać z Wazat'em.

**Obecne działanie**: Są trzy ptaki które nie znikają, jak otworze jajko do questa http://www.wowhead.com/quest=10111/bring-me-the-egg  pojawi sie czwarty.

**Oczekiwane działanie**: Ptak powinien po jakimś czasie znikać.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Udać się do Nagrand (62, 66)
2. Zobaczyć trzy ptaki
3. Uciekać

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=19055/windroc-matriarch
2. http://www.wowhead.com/quest=10111/bring-me-the-egg

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Nagrand (62, 66)

SS: http://i.imgur.com/qbbk4R3.jpg

**Comment by ThePuppetMaster** [comment]
Problem globalny.

**Comment by Shon-su** [comment]
pewnie w spellach sumających nie poustawiany despawn. Żeby się nie babrać za dużo można do tego przypadku dać np. :

DELETE FROM `smart_scripts` WHERE `entryorguid` = 19055 AND `id`= 5; 
INSERT INTO `smart_scripts` VALUES
(19055, 0, 5, 0, 1, 0, 100, 1, 60000, 60000, 10000, 12000, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Windroc Matriarch - Ooc for 60sec - Force Despawn');
