### ISSUE TITLE
[QUEST][NPC] Mounting Up - Highland Mustang

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#374]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Aby wykonać[ zadanie](http://www.wowhead.com/quest=12414/mounting-up#videos), należy znaleźć marchew i zarzucić nią jako przynętę na mustanga. 
Quest można wykonać tylko na koniach, które się paszą.  Na tych co biegają działa, ale nie da się nimi sterować.
**Obecne działanie**: 
[Film](https://www.youtube.com/watch?v=6AfCF8EclLQ&feature=youtu.be)
**Oczekiwane działanie**: 
Powinno dać się sterować wszystkimi[ tego typu koniami](http://www.wowhead.com/npc=26472/highland-mustang), niezależnie od tego co robią.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest
2. Znaleźć marchew
3. To co na filmie

**Comment by Shon-su** [comment]
23.02 wydaje się działać w porządku na testowym
