### ISSUE TITLE
[QUEST][NPC] New Recruit - Lithe Stalker

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#375]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Bug polega na tym, że można złapać Lithe Stalkera mimo posiadanego przez niego full hp.
**Obecne działanie**: 
[Film](https://youtu.be/8BckiAmOGz0)
**Oczekiwane działanie**: 
Powinno wyglądać to tak, że aby złapać Lithe Stalkera, należy zbić mu hp do około 1/3 hp (pojawia się tekst: "The Lithe Stalker is weakened by the assault") i użyć q itemu. 
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć [quest](http://www.wowhead.com/quest=13143/new-recruit) 
2. Użyć [q item](http://www.wowhead.com/item=43315/sigil-of-the-ebon-blade) na [lithe stalker](http://www.wowhead.com/npc=30894/lithe-stalker#drops)

**Comment by Shon-su** [comment]
poprawione
