### ISSUE TITLE
[SKILL][TALENT] Druid

### ISSUE THREAD

**Issue by evilday667** [RaphaelSunwell/Sunwell-BugTracker-SCv2#376]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Dash nie stackuje sie z talentem Feral Swiftness 

**Obecne działanie**: Obecnie dodaje 50% tylko Dash i wylacza nasze feral swifftnes :)

**Oczekiwane działanie**: Feral Swiftness daje 30% bazowego biegania czyli jest stale i nie zmienne na formie kota a wiec przy odpaleniu Dasha ktory daje nam 50% biegania powinnismy osiagnac predkosc 80% .. a nie niewelowac nasz talent 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodac w feral swifftenes
2. Zamienic sie w kota odpalic DASH 
3. Porownac predkosc z dashem i bez dasha :)

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Dash_(druid_ability)  tu jest widoczne pokazane 70% ale unas jest 50% + feral swiftness
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Zdajesz sobie sprawę z tego, że dasz ma ranki?

Inna sprawa, że nie dostarczyłeś reference i dowodów z pomiaru prędkości z nałożonymi efektami.
