### ISSUE TITLE
[Battleground] Zabity pet nie resa się wraz z postacią.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#377]
**Opis**: Otóż jest to dość znaczący problem, gdyż jak wiadomo - pet huntera jest bardzo ważny.
W chwili, gdy nasz pet zostanie pierwszy zabity, a następnie nasza postać - po podniesieniu się, pet nie zostaje wskrzeszony. Jest to znaczne utrudnienie przy rozgrywce, ponieważ ress peta trwa prawie 10 sekund. Przy każdym resie peta tracimy 10 sekund na gre, w tym czasie rozgrywka mogłaby się całkowicie zmienić. Kiedy np. hunter padnie 6 razy, mamy 1 minute w plecy, a wszyscy doskonale wiemy, że minuta to całkiem sporo przy rozgrywce bg.

**Obecne działanie**: Podczas powrotu do żywych postaci o klasie hunter, jego pet powinien wskrzesić się wraz z nim. Niestety tak się nie dzieje.

**Oczekiwane działanie**: Pet powinien wskrzesić się wraz z hunterem.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Być huntem i mieć peta.
2. Pójść na bg.
3. Pozwolić na zabicie peta, następnie siebie.
4. Wstać i przywołać peta.

**Linki WoWHead/OpenWoW**:

1. Brak.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy.

@edit
Dotyczy również Wintergrasp.

**Comment by jubasek21** [comment]
http://www.wowhead.com/forums&topic=177962.1 - " **_I remember that there was some issue with battleground resurrections not summoning and reviving your active pet at the time you had died (unlike the situation pre-4.0.1), meaning that you weren't ready to fend off yourself from graveyard campers and thus were at a distinct disadvantage_**"

**Comment by xsitdev** [comment]
Wgrane zostanie 28.12 (dzisiaj nad ranem)
