### ISSUE TITLE
[Battleground] Isle of Conquest - sterowiec. 

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#379]
**Obecne działanie**: Po przejęciu Hangaru i użyciu teleportu gracz wypada ze sterowca. Problemem jest również nie otwieranie się spadochronu, po uprzednim zeskoku ze sterowca. Oba przypadku kończą się - śmiercią.
https://youtu.be/nswW1z6owBQ   :( :( 

**Oczekiwane działanie**: Po użyciu teleportu na sterowiec, gracz powinien być przeniesiony bezpośrednio na sterowiec. Spadochron powinien się otwierać przy każdym zeskoku ze sterowca.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Być na battlegroundzie Isle of Conquest. 
2. Przejąć Hangar.
3. Użyć teleportu na sterowiec. 
[4.] Zeskoczyć ze sterowca.

**Linki WoWHead/OpenWoW**:

1. [Bg] http://www.wowhead.com/isle-of-conquest
2. [Baner] http://www.wowhead.com/object=195158/hangar-banner

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Brak.

**Comment by Triceps69** [comment]
Potwierdzam.
