### ISSUE TITLE
SKILL TALENT Rogue

### ISSUE THREAD

**Issue by Huggerek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#380]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Talent Combat potency nie działa (lub ma niepoprawnie ustawioną szansę na proc) z talentem killing spree, działania na skillach fan of knives oraz multilate nie mam jak sprawdzić, ale prawdopodobnie z nimi też może występować ten problem. Podczas używania umiejętności wspólnie z umiejętnością "blade flurry" również nie odnotowałem zwiększonej szansy na proc tego telentu.

**Obecne działanie**: Podczas używania umiejętności Killing Spree nie działa talent Combat Potency

**Oczekiwane działanie**: Uderzenia z offhandu przy wykorzystaniu skilli powinny mieć szansę na proc, działało to na poprzednim sunwellu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć umiejętności z talentów killing spree na przeciwniku, w sytuacji kiedy posiada się również nauczony talent "Combat Potency"
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=35551/combat-potency
2. http://www.wowhead.com/spell=51690/killing-spree
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Kougraa** [comment]
http://www.wowhead.com/spell=35551/combat-potency
http://www.wowhead.com/spell=51690/killing-spree

**Comment by ThePuppetMaster** [comment]
Przypomnienie dla siebie samego: sprawdzić.

**Comment by kovaq** [comment]
Potwierdzam nie dzialanie fan of knives z combat potency. podczas farmienia skor mam okazje wpasc w okolo 8-10 malp. Przeliczajac szanse jest to 20 hitow, w tym 10 z main handa, 10 z offhanda (opis spella: instantly throw both weapons...). Zakladajac, ze mamy hit cap i kazdy trafi, to mamy 20% szans na kazdorazowe zregenerowanie 15 energii, tak 10 razy. Maxymalnie wiec mozna zlapac nawet 150 energii. W rzeczywistosci, jezeli talent wejdzie chociaz raz to jest swieto, nie mowiac juz by wykorzystalo talent kazdorazowo i uzupelnilo do maxa. Szczerze, to podejrzewam, ze te jednorazowe wejscie odnosi sie do melee atakow wykonywanych pomiedzy FoK'ami, a samo combat potency nie dziala.

**Comment by DinozaurWKamizelce** [comment]
Wydaje mi się, że problem może być nie tylko u rogala ale w całej mechanice ataków AOE tzn uderzenie w 10 mobów naraz jest liczone jako 1 uderzenie. Jeszcze nie przeprowadziłem odpowiednich testów, ale w tej chwili skłaniam się w tę stronę (jeśli tak jest to nie wiem czy to błąd czy tak ma być)

**Comment by Rosenkrantz** [comment]
O ile mi wiadomo combat potency ma działać tylko na autoataki, jeżeli wygrzebię dowód to wpiszę. Ad hoc znalazłem taki o wpis https://samueltempus.wordpress.com/2009/01/20/rogue-how-to-spec-and-play-combat/ na ile wiarygodny, każdy sam oceni.

**Comment by Huggerek** [comment]
@DinozaurWKamizelce możesz mieć rację, często jak użyjesz foka to wchodzi to 15 energii, ale zawsze pojedynczo, wygląda to tak, jakby faktycznie szansa na proc była większa coś a'la z każdego uderzenia szansa - bo wchodzi niemal zawsze na grupie mobow, ale talent procuje tylko raz, bez szans na większą ilość proców na raz.

@Rosenkrantz nie masz racji, w patchu 3.0.9 było to na autoataki, bodaj już w patchu 3.2 opis talentu zostal zmieniony z "offhand autoattack" na "offhand attack" jak i jego działanie, wtedy też zaczął procować z skillami.

**Comment by kovaq** [comment]
Po 10 razach na Killing Spree i okolo 120 uzyciach fan of knives rzeczywiscie moge stwierdzic, ze combat potency nie proca ze skillami. Ja rowniez jestem przy wersji, ze powinien, ale o ile w killing spree co tick abilita ma szanse, tak i w fan of knives powinien (FoK ma 2 wave'y, wiec 2 ticki sa jak najbardziej ok)
