### ISSUE TITLE
Paladin quest The tome of divinity

### ISSUE THREAD

**Issue by Tommyo1995** [RaphaelSunwell/Sunwell-BugTracker-SCv2#381]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Problem polega na tym, iż wyrzuciłem przypadkowo Q item "Symbol of Life", i teraz gdy wyrzucam q i dodaje na nowo q item nie pojawia sie w ekwipunku, rozmawialem z dwoma Gmami i prosili bym zgosil to wlasnie tu.

**Oczekiwane działanie**: Powinienem dostać ww. Q item abym mógł zacząć wskrzeszać innych graczy. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wysłać ten item przez mailbox
2. Bądź dodać mi redemption
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=2998
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
72,51

**Comment by ThePuppetMaster** [comment]
Proszę o koment od GMów. Czy nie dało się otrzymać kopii przedmiotu od NPC, któremu oddawałeś poprzedniego questa po 'rozmowie'?

**Comment by Tommyo1995** [comment]
Nie udało się, konsultowałem to z Dreysothem,Snakiem, prosili bym zgłosił na BT :(
