### ISSUE TITLE
[ACHIEVMENT] Fa-la-la-la-Ogri'la

### ISSUE THREAD

**Issue by gitghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#382]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
"Napisz, że nie działa" - Athell

**Obecne działanie**:
Po wykonaniu questa na mouncie z buffem Preserved Holly nie zalicza achievmenta Fa-la-la-la-Ogri'la, potrzebnego do ukończenia Merrymaker.

**Oczekiwane działanie**:
Po wykonaniu questa z aktywnym buffem, powinno zaliczyć  achivmenta.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Blade's Edge Mountains.
2. Wykonać daily quest Bomb them again! z aktywnym buffem Preserved Holly.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11023/bomb-them-again
2. http://www.wowhead.com/achievement=1282/fa-la-la-la-ogrila

**Comment by Mithras2801** [comment]
Są 2 buffy o tym samym działaniu aczkolwiek powinny chyba oba być zaliczane.

http://www.wowhead.com/achievement=1282/fa-la-la-la-ogrila#comments:id=922739

**Comment by OrgiVed** [comment]
Potwierdzam niedziałanie tego achiwa i prosze o naprawienie :)

**Comment by Kougraa** [comment]
Hooraga zdobył ten achi. 
http://sunwell.pl/character/1/44406

**Comment by ThePuppetMaster** [comment]
Testowane, działa.
