### ISSUE TITLE
[NPC] 25838 - Hierophant Liandra <D.E.H.T.A.>

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#385]
**Obecne działanie**: NPC alta na sunwellu

**Oczekiwane działanie**: NPC powinien siedziec.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzic NPC

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=25838/hierophant-liandra

**Dowody:**
https://youtu.be/wseRZ7BpUqU?t=17s
https://youtu.be/soPDexGx3uY?t=1s (WotLK glob)
https://youtu.be/EKcNECXO1mQ?t=1s (WotLK glob)

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
