### ISSUE TITLE
[NPC] 25806 - Loot Crazed Poacher (brak patrolu)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#386]
**Obecne działanie**: NPC stoją w stealth i nic nie robią.

**Oczekiwane działanie**: NPC powinny mieć nadane patrole.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zobaczyć NPC

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=25806/loot-crazed-poacher

**Comment by Shon-su** [comment]
ciężko znaleźć informacje na temat ścieżek patroli niestety.

**Comment by Mithras2801** [comment]
Noc są ukryte, wystarczy ptr aby zesnifowac lub zobaczyć

**Comment by Mithras2801** [comment]
Npc są ukryte, wystarczy ptr aby zesnifowac lub zobaczyć
