### ISSUE TITLE
[quest] Iron Rune Constructs and You: The Bluff

### ISSUE THREAD

**Issue by Silisar** [RaphaelSunwell/Sunwell-BugTracker-SCv2#387]
**Obecne działanie**: Npc nie wchodzi w interakcję kiedy gracz wejdzie na jego posłanie.

**Oczekiwane działanie**: Quest powinien wyglądać jak na prezentowanym filmiku
https://www.youtube.com/watch?v=w84B28E_r_o
**Co należy zrobić, aby odtworzyć ten błąd**: Dodać interakcję w której npc zareaguje na chodzenie po posłaniu

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:
http://wotlk.openwow.com/quest=11491
.

**Comment by ThePuppetMaster** [comment]
#260
