### ISSUE TITLE
Mag needujący tarcze

### ISSUE THREAD

**Issue by kowalinios** [RaphaelSunwell/Sunwell-BugTracker-SCv2#388]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Mag i inne postaci mogące używać offhandów mogą needować tarczę w group loot.

**Obecne działanie**: Mag może needować tarczę w group loot.

**Oczekiwane działanie**: Mag nie powinien móc needować tarczy z uwagi na to, że nawet nie może jej nosić. Tyle.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Nawet jeżeli tak podpowiada logika, proszę wskazać refernce pokazujący, że takowe restrykcje działały na WotLK.
