### ISSUE TITLE
[QUEST] Missing In Action

### ISSUE THREAD

**Issue by XevL** [RaphaelSunwell/Sunwell-BugTracker-SCv2#389]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
NPC bugged.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
After you start the quest the NPC go under the ground and disappear. 

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/quest=219/missing-in-action
2. http://wotlk.openwow.com/quest=219

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
28.3 ; 13.0 Redridge Mountains.

**Comment by kovaq** [comment]
https://youtu.be/8agtuXxLcjI It works well :)
