### ISSUE TITLE
[NPC] 6236 - Klannoc Macleod

### ISSUE THREAD

**Issue by Kroczyciel** [RaphaelSunwell/Sunwell-BugTracker-SCv2#390]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak możliwości otrzymania od NPC quest'a.
Problem nie występował u wszystkich, niektórzy nie posiadali niżej opisanego błędu.

**Obecne działanie**: Brak możliwości wzięcia u NPC quest'a kontynuującego chain na Berserk Stance.

**Oczekiwane działanie**: Powinno dać się wziąć quest.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Być warriorem, posiadać 30lvl, wziąć quest zaczynający chain u trenera w jednej ze stolic.
2. Oddać quest u NPC.
3. Spróbować wziąć następny quest.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=6236/klannoc-macleod - link z NPC.
2. http://www.wowhead.com/quest=1718/the-islander - quest zaczynający chain.
3. http://www.wowhead.com/quest=1719/the-affray - quest, który powinno się móc otrzymać.

**Comment by Damien87** [comment]
Quest znów nie działa. Ten sam problem.

**Comment by kovaq** [comment]
Na 3 podejscia za kazdym razem udalo sie wszystko ladnie oddac, prawdopodobnie jest juz naprawione.
