### ISSUE TITLE
[DRUID] Utrudnienie wykonania Achievementa With a Little Helper from My Friends

### ISSUE THREAD

**Issue by OrgiVed** [RaphaelSunwell/Sunwell-BugTracker-SCv2#391]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Bug polega na Znikaniu Buffa z którym należy ten Achi zrobić

**Obecne działanie**: Problem polega na tym, że jak się weźmie buffka zmieniającego w gnoma i zmieni się formę to buff znika.

**Oczekiwane działanie**: Buffek nie powinien znikać po zmianie formy, ogranicza to możliwość wykonania achi do biegania bez formy

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Być druidem
2. Wejść do maszynki zmieniającej
3. Zmienić forme

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
@ThePuppetMaster  @OrgiVed 
a jakiś dowód że nie powinno ściągać? Bo forma jednak ściąga większość rzeczy
