### ISSUE TITLE
Lorgus Jett

### ISSUE THREAD

**Issue by xnemeyethx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#392]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

Lorgus Jett powinien znajdować się w instancji Blackfathom Deeps.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

Brak npc.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

Npc w instancji.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Udać się do bfd.
2.  Spróbować znaleźć moba.
3. 

**Linki WoWHead/OpenWoW**:

1.  http://wotlk.openwow.com/npc=12902#abilities
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Spawn istnieje, tylko z jakiegoś powodu NPC standardowo jest martwy.

**Comment by Shon-su** [comment]
Nie wiem co autor miał na myśli, ale bardzo ciekawa rzecz tam była zostawiona :D

DELETE FROM `smart_scripts` WHERE `entryorguid` = 12902 AND `id` = 0;
UPDATE `smart_scripts` SET `id`= 0 WHERE `entryorguid` = 12902 AND `id` = 1;
UPDATE `smart_scripts` SET `id`= 1 WHERE `entryorguid` = 12902 AND `id` = 2;

**Comment by Vansir** [comment]
Jest szansa ze ten bug zostanie naprawiony w najblizszych dniach? Czy to jakas grubsza sprawa?
