### ISSUE TITLE
Sorlof's booty QUEST

### ISSUE THREAD

**Issue by Bronies27** [RaphaelSunwell/Sunwell-BugTracker-SCv2#393]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie ma mobka który powinien być

**Obecne działanie**: Mobka po prostu nie ma

**Oczekiwane działanie**: Mobek się spawni i jest możliwy do zabicia przy pomocy quest itemu

**Co należy zrobić, aby odtworzyć ten błąd**:

1. pójść tam i sprawdzić 
2. 
3. 

**Linki WoWHead/OpenWoW**:
https://www.youtube.com/watch?v=gSbTj6YZAP0
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Spawn istnieje, tylko z jakiegoś powodu NPC standardowo jest martwy.

**Comment by ThePuppetMaster** [comment]
Nie wystarczające info.

**Comment by siwy92** [comment]
nadal nie dziala.
