### ISSUE TITLE
[NPC] Grand Warlock Nethekurse

### ISSUE THREAD

**Issue by Mojsik** [RaphaelSunwell/Sunwell-BugTracker-SCv2#395]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 1 Boss w The Shattered Halls na poziomie Normal (na Hero nie sprawdzałem) jest niemożliwy do zaatakowania.

**Obecne działanie**:  Po zabiciu 4 npc załączają się po kolei jego wypowiedzi (po każdym inna). Następnie po zabiciu czwartego nie włącza się możliwość bicia bossa. Po paru minutach bezczynnego czekania boss użył umiejętności "Shadow Sear" i zadał tylko sobie obrażenia z niego, a następnie po odczekaniu kolejnych paru minut i nie użyciu przez niego tej umiejętności napisałem ticketa.
https://s30.postimg.org/kc0qtyckh/Wo_WScrn_Shot_121616_004257.jpg - zdjęcie pokazujące stojącego bossa z brakującym życiem zabranym przez Shadow Sear.

**Oczekiwane działanie**: Boss po zabiciu 4 npc powinien zaatakować nas a my powinniśmy móc bić jego.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść na The Shattered Halls i zabić 4 npc stojącym przed bossem.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=16807/grand-warlock-nethekurse
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
The Shattered Halls (48.0, 51.9, Hellfire Peninsula)

**Comment by kovaq** [comment]
https://youtu.be/kE3JpuAJEaY Dziala ;)
