### ISSUE TITLE
[QUEST] Convocation at Zol'Heb

### ISSUE THREAD

**Issue by tomos3k** [RaphaelSunwell/Sunwell-BugTracker-SCv2#396]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Otrzymujemy od npc quest item Prophet of Akali Convocation, za pomocą którego powinno się przyzwać moba Prophet of Akali na zielonej runie w centrum lokacji Zol'Heb w Zul'Drak, Po dotarciu na miejsce i próbie użycia itemu w wyznaczonym miejscu postać gracza wykonuje tylko lekki 'tik' i nic więcej się nie dzieje, co uniemożliwia wykonanie Questu i kontynuację questowania w Zul'Drak.

**Oczekiwane działanie**: Po użyciu quest itemu w wyznaczonym miejscu postać gracza powinna wykonać cast, po którym pojawia się Prophet of Akali, którego następnie trzeba pokonać celem ukończenia zadania.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Umożliwić poprawne użycie itemu Prophet of Akali Convocation, które skutkować będzie spawnem Prophet of Akali.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. Quest: http://www.wowhead.com/quest=12730/convocation-at-zolheb
2. Quest item: http://www.wowhead.com/item=39566/prophet-of-akali-convocation
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
77.6, 36.7

**Comment by ThePuppetMaster** [comment]
#99
