### ISSUE TITLE
Death from Below

### ISSUE THREAD

**Issue by xnemeyethx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#397]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

Mamy obronić kapitana statku przed kilkoma atakami Nag.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

Zadania działa w miarę dobrze ale nie wiem czy kolejne fale nie następują po sobie zbyt szybko. Dodatkowo - jeżeli kapitan zginie i tak zaliczamy zadanie.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

Kapitan musi przeżyć żeby zadanie zostało zaliczone.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Udać się do Arathi
2.  Zrobić wszystkie questy od Kapitana.
3.  Spróbować wykonać zadanie Death from Below

**Linki WoWHead/OpenWoW**:

1.  http://db.vanillagaming.org/?quest=667
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
wydłużyłem przerwy między falami tak by odpowiadało to temu co udało mi się znaleźć na filmiku. Fail questa działa, tylko jest zrobiony w sposób który w szczególnych warunkach może nie zaskoczyć.
