### ISSUE TITLE
[QUEST] Agmar's Hammer

### ISSUE THREAD

**Issue by k3lus** [RaphaelSunwell/Sunwell-BugTracker-SCv2#398]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak możliwości oddania questa. Jest to jedno z kluczowych zadań, aby dojść do eventu przy Wrath Gate.

**Obecne działanie**: Brak interakcji z npc Overlord Agmar uniemożliwia ukończenie zadania.

**Oczekiwane działanie**: Możliwość interakcji z npc Overlord Agmar.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Jest to chain, który zaczyna się w zadaniu The Fall of Taunka'le Village

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11929/the-fall-of-taunkale-village
2. http://www.wowhead.com/quest=12008/agmars-hammer

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
X: 3842.982666 Y: 1495.128296 Z: 91.717621 Map: 571 (Northrend)

**Comment by ThePuppetMaster** [comment]
Added in patch 3.3.0.10772

**Comment by k3lus** [comment]
Damn, wybaczcie za niedopatrzenie :(

**Comment by jubasek21** [comment]
Ale przecież quest działa. Achiv zrobiony.

**Comment by k3lus** [comment]
też oddałem wczoraj... 
Wcześniej Overlord był po prostu zbugowany i zamiast siedzieć na tronie to stał obok i nie można było z nim w ogóle pogadać.
