### ISSUE TITLE
[profession][visual] Blacksmithing

### ISSUE THREAD

**Issue by Makakahehe** [RaphaelSunwell/Sunwell-BugTracker-SCv2#4]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Visual przy drobnicy, animacja nie nadaza. Prawdopodobnie to samo z JC.

**Obecne działanie**: Gdy tworzymy rough sharpening stone to animacja się włącza dopiero pod koniec. Wyglada jak zlagowana. Występowało też na testach przy JC. Wygląda to na bug przy tworzeniu przedmiotów które się szybko robi (koło sekundy).

**Oczekiwane działanie**: Animacja tworzenia powinna być od samego początku.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąść se profesje BS i zrobić rough sharpening stone np.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=2862
2. http://wotlk.openwow.com/spell=2660
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
nie dotyczy

**Comment by xsitdev** [comment]
Nie mogę potwierdzić.
