### ISSUE TITLE
[SKILL][DRUID] Flight form

### ISSUE THREAD

**Issue by Rokin92** [RaphaelSunwell/Sunwell-BugTracker-SCv2#40]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  W trakcie lotu skille są zablokowane.

**Obecne działanie**:  Druid Flight Form nie pozwala na używanie skilli i spelli w powietrzu.

**Oczekiwane działanie**:  Skille w trakcie lotu powinny być odblokowane i możliwe do użycia w powietrzu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wbić 60 lvl druidem.
2.  Użyć flight form.

**Linki WoWHead/OpenWoW**:

1. [http://wotlk.openwow.com/spell=33943](http://wotlk.openwow.com/spell=33943)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy.

**Comment by ThePuppetMaster** [comment]
W opisie na WoWiki zostało wyszczególnione, że w tej formie skille i itemy są nieużywalne.
