### ISSUE TITLE
[SPELL][PRIEST] Power World: Shield 

### ISSUE THREAD

**Issue by latro123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#401]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie da się reaktywować tarczy po otrzymaniu pewnej ilości obrażeń.

**Obecne działanie**: Kiedy mamy na sobie Power Word: Shield i zostaniemy zaatakowani przez kogoś np. npc i zada on jakieś obrażenia (nie wiem dokładnie jakie) to nie da się reaktywować tarczy(po zejściu weekned soul) i wyświetla się błąd: A more powerful spell is already active. Uwaga: błąd pojawia się po otrzymaniu małych obrażeń, gdy tarcza jest już mocno zniszczona da się ją reaktywować. Dzieje się to w wielu miejscach na mapie i nieco przeszkadza, szczególnie, gdy dochodzi do walki z obcą frakcją.

**Oczekiwane działanie**: Powinno dać się reaktywować tarczę nieważne ile pochłonęła ona obrażeń.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Aktywować na sobie Power Word: Shield.
2. Dostać kilka hitów od np. NPC. 
3. Jak nie będzie Weekned soul spróbować aktywować ponownie Power Word: Shield

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=17
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, [Map)**:]
![wowscrnshot_121216_183517](https://cloud.githubusercontent.com/assets/24612328/21275064/55670f08-c3cb-11e6-885f-a80737239c6e.jpg)
![wowscrnshot_121616_124947](https://cloud.githubusercontent.com/assets/24612328/21275066/5569461a-c3cb-11e6-8964-a7d7c6f44de6.jpg)

**Comment by ThePuppetMaster** [comment]
Kiedy zakładałeś pierwszą tarczę, miałeś więcej SP (proc?), przy próbie założenia nowej tarczy, efekt, który masz na sobie jest mocniejszy, niż działanie tego, którym chcesz tarczę nadpisać. Działanie poprawne.

**Comment by latro123** [comment]
Faktycznie mogło tak być przez Spirit tap i SP ze spirita, dziękuje za
wyjaśnienie. Przedtem o tym nie pomyślałem.

W dniu 16 grudnia 2016 22:51 użytkownik ThePuppetMaster <
notifications@github.com> napisał:
