### ISSUE TITLE
[QUEST] WANTED: Boss Grog'ak

### ISSUE THREAD

**Issue by Effimera** [RaphaelSunwell/Sunwell-BugTracker-SCv2#403]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest w Zangarmarsh brany z Zabra'jin, wioski hordy, z tablicy ogłoszeń.

**Obecne działanie**: Jako ALLIANCE biore q z wioski hordy, nie mam gdzie go oddać. Brak alliancowego odpowiednika q w Zanga.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9820/wanted-boss-grogak
2. -
3. -

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Zgłoszenie nie zgodne z szablonem. Popraw.
