### ISSUE TITLE
[Instance Trash] Shattered Halls norm

### ISSUE THREAD

**Issue by Effimera** [RaphaelSunwell/Sunwell-BugTracker-SCv2#404]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po pierwszym bossie na Shattered Halls norm, idąc w górę i potem długim korytarzem, na końcu jest zbugowana grupa trashu, która cały czas, bez końca, respi się falami. Generalnie wipe, za wipem, do póki nie przebiegnie się za falę, padnie i poressa. 

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Zgłoszenie do poprawy.
