### ISSUE TITLE
[QUEST] [A] 12499 i [H] 12500 - Return To Angrathar (brak fazowania + kilka bugów)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#405]
**Obecne działanie**: Po ukończeniu u wymaganych NPC dostajemy achieva, animacje, a potem oba NPC koncowe giną w filmie, ale nadal stoją jakby nic się nie stało i brak phasowania ze smokami ogniami itp

**Oczekiwane działanie**: Po wymienionych krokach do filmiku i achieva powinien po animacji wskoczyć phasing strefy na spalone/palące się otoczenie z 2 smokami. (proszę zwrócić uwagę na ich zachowanie i dialogi + chat)

**Filmiki**:
[A] https://www.youtube.com/watch?v=2whrNZz2USM
[H] https://www.youtube.com/watch?v=glZWGdWB-II

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć Q
2. Oddać Q 
3. Sprawdzić animacje i achivea
4. Sprawdzić po wszystkim phasing

**Linki WoWHead/OpenWoW**:

1. [H] http://www.wowhead.com/quest=12500/return-to-angrathar
2. [A] http://www.wowhead.com/quest=12499/return-to-angrathar

**Comment by Mithras2801** [comment]
Mała poprawka phasing jest do poprawienia i dialogi smoków. Phasing reaguje dopiero jak podejdziemy się w pobliże bramy gdzie toczyła się walka.

**Comment by Shon-su** [comment]
wydaje mi się że całkiem przyzwoicie teraz działa

**Comment by Mithras2801** [comment]
Problem był przed przejściem na SunwellCore. Na SunwellCore śmiga. Ale i tak wymaga poprawki/
