### ISSUE TITLE
[PVPITEMS] Marks of Honor z wsg, ab, av, eots oraz itemy za owe marki.

### ISSUE THREAD

**Issue by Baggedmilk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#406]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Brak nagród za BG w postaci mark of honor i brak wymaganych marek do kupna offestowych itemow pvp.
**Obecne działanie**: Itemy pvp mozna kupic za sam honor i nie dostajemy marek za granie BG.

**Oczekiwane działanie**: Itemy pvp powinny kosztowac honor oraz marki, ktore bedziemy dostawac za granie bg.
http://wowwiki.wikia.com/wiki/Mark_of_Honor

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodac do wygranych i przegranych BG dodatkowa nagrode w postaci mark of honor.
2. Do itemowpvp dodatkowo dodac koszt okreslonej ilosci marek.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=20560
2. http://wotlk.openwow.com/item=20559
3. http://wotlk.openwow.com/item=20558
4. http://wotlk.openwow.com/item=20559

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by tokacz** [comment]
te marki zostały usunięte z patchem 3.3.3, a ci którzy je mieli mogli wymienić za honor. Mamy niby patch 3.3.5 ale server ustawiony na niższą wersję i stąd takie "idiotyzmy" wychodzą co było chyba głupim posunięciem administracji.

**Comment by tokacz** [comment]
te marki zostały usunięte w wyższym patchu (chyba 3.3). Można było wymienić na honor. Jak przestawią server na patch 3.3.5 ta poprawka nie będzie miała sensu. Podobnie ma się z questami bo można wziąć ale nie idzie zrobić i jak administracja nie pójdzie po rozum do głowy i nie przestawi servera to będą raportowane takie pierdoły.

**Comment by Vaelevian** [comment]
24.12 przeszliśmy na nowe core, na którym blokujemy jedynie rajdy, profesje, oraz itemy (w tym kamyki JC), które nie odpowiadają aktualnemu contentowi. Zgłoszenie zamykam.
