### ISSUE TITLE
[QUEST] Into the world of spirits 1/3

### ISSUE THREAD

**Issue by Zurwan** [RaphaelSunwell/Sunwell-BugTracker-SCv2#407]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Quest Iteam "Reagent Pouch" nie pojawia sie w punkcie w ktorym zawsze to robil

**Obecne działanie**: Brak Quest Itemu co uniemozliwia wykonanie questow

**Oczekiwane działanie**: item powinien byc/respic sie

**Co należy zrobić, aby odtworzyć ten błąd**:

1. udac sie na Howling Fjord
2. po paru questach dostac w/w
3. dostac sie we wskazane przez tracker miejsce ;)

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11333/into-the-world-of-spirits
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

![wowscrnshot_121716_160728](https://cloud.githubusercontent.com/assets/24623644/21287803/2f5447f0-c474-11e6-8ef0-5243b2479a72.jpg)

**Comment by ThePuppetMaster** [comment]
Added in patch 3.3.0.10772
