### ISSUE TITLE
[QUEST] The Thane of Voldrune

### ISSUE THREAD

**Issue by jubasek21** [RaphaelSunwell/Sunwell-BugTracker-SCv2#409]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mobek potrzebny do questa jest zbugowany (visual), ponieważ nakłada się w jednym miejscu z innymi jego kopiami. 
**Obecne działanie**: Mamy za zadanie zabić bossa Torvald Eriksson, którego zabijamy za pomocą Proto-Drake'a Flamebringer. Jednak ciężko go wziąć z miejsca, w którym się znajduje, ponieważ jak widać na załączonym screenie tworzą się jego "kopie", które nakładają się na siebie przez co wejście na drake'a jest utrudnione. 

**Oczekiwane działanie**: Nie powinno być wizualnych kopii Flamebringera tylko jeden. Powinien być  przypięty łańcuchami wraz z opcją uwolnienia go i wejścia na niego.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa.
2. Podjechanie w miejsce gdzie należy uwolnić drake'a.
3. Zobaczyć, że jest visual tworzący jego "kopie" przez co ciężko go wybrać.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=27292/flamebringer
2. http://www.wowhead.com/quest=12255/the-thane-of-voldrune
3. https://www.youtube.com/watch?v=5G1P44KFTPE - tak to powinno wyglądać od 0:36.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://zapodaj.net/3fef01ee6065a.jpg.html - screen ukazujący błąd.

**Comment by kovaq** [comment]
http://screenshooter.net/103037023/aegjfwc - Problem wciaz wystepuje, aczkolwiek frekwencja robienia tego q zmalala.

**Comment by Shon-su** [comment]
Gdyby ktoś miał pomysł jak to odtworzyć to będę wdzięczny.

**Comment by Shon-su** [comment]
poprawione, nie dograne. Będą znikać po jakimś czasie
