### ISSUE TITLE
[QUEST] The Darkmoon Faire

### ISSUE THREAD

**Issue by wilq1337** [RaphaelSunwell/Sunwell-BugTracker-SCv2#41]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie ma NPC do którego można oddać quest.

**Obecne działanie**: Brak NPC powiązanego z oddaniem questa

**Oczekiwane działanie**: NPC powinien stać w wyznaczonym miejscu i umożliwić graczu ukończenie questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zacząć questa.
2. Udać się w wyznaczone miejsce.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=7926/the-darkmoon-faire
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 37, 38, Mulgore

**Comment by Shon-su** [comment]
możliwe że to przez to że dostępny jest tylko w czasie trwania Darkmoon Faire, a ten event nie powinien być jeszcze aktywny. Chyba na początku każdego miesiąca przez tydzień jest.
