### ISSUE TITLE
[QUEST]Guardian of the Monument.

### ISSUE THREAD

**Issue by D4ndriel** [RaphaelSunwell/Sunwell-BugTracker-SCv2#410]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Po zabiciu Apexis Gurdian nie pojawia sie jego głowa.

**Obecne działanie**: nie ma quest itemu do zebrania.

**Oczekiwane działanie**: po zabiciu elitki można podnieść jego głowę.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zacząć quest "Guardian of the Monument".
2. Zebrać 35 Apexis Shard.
3. Wykonać mini gierkę w lub znaleźć miejsce w którym elita pojawia się bez tego.
4. Zabić Apexis Guardian.
**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11059/guardian-of-the-monument
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:  Blade's Edge Mountains

**Comment by ThePuppetMaster** [comment]
Added in patch 3.3.0.10958
