### ISSUE TITLE
Fresh Meat

### ISSUE THREAD

**Issue by xnemeyethx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#411]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

Zadanie polega na zebraniu szczypców z krabów.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

Szansa na drop jest tragiczna, wynosi pewnie około 30%. Może mniej.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

Szansa na drop powinna wynosić około 80%.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Udać się do Swamp os Sorrows
2. Zabrać zadanie 'Fresh Meat'
3. Delektować się zabijaniem krabów.

**Linki WoWHead/OpenWoW**:

1. http://db.vanillagaming.org/?quest=1430
2. http://db.vanillagaming.org/?npc=1088
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by valcy** [comment]
W 1 linku ludzie w komentarzach rowniez mowia o niskim dropie - jeden wspomina o 38 szansy na drop.
W drugim widnieje ze szansa to 80 ale w komentarzu gosc tez mowi o niskiej szansy.

**Comment by Horpah** [comment]
30% to nie jest niska szansa na drop.  To oczywiście moja opinia

**Comment by xnemeyethx** [comment]
30% to było mierzone tak na oko. Jak np. na dziesięć krabów mam jedno mięso... to trochę średnio. Tak było na każdym serwerze na jakim grałem :)
