### ISSUE TITLE
Lack of Surplus

### ISSUE THREAD

**Issue by xnemeyethx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#412]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

Zadanie polega na zbieraniu mięsa z krokodyli.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

Szansa na drop jest tragiczna - prawdopodobnie około 30%

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

Szansa na drop powinna wynosić około 80%.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Swamp os Sorrows
2. Zabrać zadanie 'Lack of Surplus'
3. Delektować się zabijaniem krokodyli.

**Linki WoWHead/OpenWoW**:

1.  http://db.vanillagaming.org/?quest=698
2.  http://db.vanillagaming.org/?item=6169
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Afgann** [comment]
`UPDATE creature_loot_template SET ChanceOrQuestChance=80 WHERE entry IN(1082, 1087) AND item=6169;`

**Comment by Shon-su** [comment]
W kilku miejscach ( np. wowhead, twinstar db) można znaleźć informację że wynosi on około 30%. U nas jest 38%
