### ISSUE TITLE
[QUEST] Rallying the troops

### ISSUE THREAD

**Issue by Kimdzongil** [RaphaelSunwell/Sunwell-BugTracker-SCv2#414]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Po uzyciu itema nic sie nie dzieje**:

**Po użyciu itema na Grizzly hill Giant nie zalicza tego i nie pojawia sie krasnolud ktorego trzeba zabic**: TU WPISZ NA CZYM POLEGA PROBLEM

**Po uzyciu itema na gigancie powinno zaliczyc zbufowanego giganta i powinien pojawic sie krasnolud ktorego trzeba zabic.**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac quest od giganta Korun
2. Uzyc itemka ktory sie od niego dostaje na Grizzly Hills Giant
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=VgmKDh0wEkU
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by jubasek21** [comment]
Quest działa, polega on na uzyciu quest itemu na gigancie w momencie kiedy biję się z tym drzewcem. Najlepiej wziąć na siebie tego dużego drzewca, podbiec z nim do giganta, która złapie aggro i kiedy zaczynają walkę uzyć quest itemu na gigancie. Wtedy gigant pokonuje drzewca i pojawia się krasnolud. Quest zrobiony wczoraj.

**Comment by Kimdzongil** [comment]
wlasnie tak zrobilem teraz i nie dziala

**Comment by jubasek21** [comment]
Chodzi o ten odpowiedni moment uzycia quest itemu, trzeba to wyczuć.

**Comment by Kimdzongil** [comment]
ok do zamkniecia. q dziala, zrobiony, cos mi sie zbugowalo na postaci, pomoglo dopiero jak sie sma zabilem, moment uzycia q itemku nie ma znaczenia, mozna uzywac go na tych gigantach ktore sie bija i nie.
