### ISSUE TITLE
[QUEST] Bringing Down Heb'jin

### ISSUE THREAD

**Issue by jubasek21** [RaphaelSunwell/Sunwell-BugTracker-SCv2#415]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest nie posiada poprawnego skryptu przez co nie da się go ukończyć.

**Obecne działanie**: Gdy docieramy na miejsce mamy za zadanie zabić trolla Heb'jin, jednak stoi on nieruchomo, w złym miejscu i jest nie targetowalny. Jego mount również spawni się w inny miejscu niż na wieży wraz z bossem, znajduję się on przy bębnie.

**Oczekiwane działanie**: Podczas dotarcia na miejsce powinniśmy uderzyć w bęben i boss wraz ze swoim mountem powinien zlecieć z wieży, która jest umieszczona na filmiku i powinien wypowiedzieć swoją kwestie, potem go zabijamy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Dotrzeć na miejsce.
3. Zobaczyć, że bossa nie da się stargetować, stoi w złym miejscu jak również jego mount.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12662/bringing-down-hebjin
2. http://www.wowhead.com/npc=28636/hebjin
3. https://www.youtube.com/watch?v=efSG_pUgKEw - filmik jak powinien wyglądać quest.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://zapodaj.net/d0b18e973c299.jpg.html - złe miejsce bossa.
https://zapodaj.net/e9ace0b4fb19e.jpg.html - złe miejsce jego mounta.

**Comment by FrostyGM** [comment]
Potwierdzam, sprawdzałam.

**Comment by Verthe** [comment]
quest dziala poprawnie

**Comment by DinozaurWKamizelce** [comment]
Ale ten q u nas działa tak jak na fimiku.
Czasem potrafi się zbugować tak jak piszesz i wtedy trzeba jeszcze raz użyć bębna. Ale na 3 postacie, którymi go robiłem raz tylko musiałem powtórzyć.
