### ISSUE TITLE
[QUEST] MASTERY OF THE CRYSTALS

### ISSUE THREAD

**Issue by Triceps69** [RaphaelSunwell/Sunwell-BugTracker-SCv2#417]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:W queście musimy zabic 50 npc, do pomocy mamy 3 quest itemy które bierzemy ze skrzynki.

**Obecne działanie**: Quest itemy totalnie nie działają.
http://www.wowhead.com/item=39694/crystal-of-the-violent-storm
http://www.wowhead.com/item=39693/crystal-of-unstable-energy
http://www.wowhead.com/item=39689/crystal-of-the-frozen-grip

**Oczekiwane działanie**: quest itemy powinny działac

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wziać quest
2. użyc q itemów ze skrzynki cordy 33,75
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12761/mastery-of-the-crystals
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Verthe** [comment]
Quest do poprawy
