### ISSUE TITLE
[Battleground] Zabity pet nie resa się wraz z postacią v2

### ISSUE THREAD

**Issue by valcy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#418]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Odniesienie do https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/377

**Obecne działanie**: Spirit guide nie ressa peta.

**Oczekiwane działanie**: Spirit guide powinien ressac takze peta jak mowia SPRAWDZONE zrodla:
link 1 - Spirit Guides in Battlegrounds will now summon/resurrect your current pet when the Hunter is resurrected. 
link 2 -  Unlike Spirit Healers found in the rest of the world, players resurrected by Spirit Guides are restored to full health and mana, as are any pets or minions.
Mialbym prosbe aby nie bazowac na wypowiedzi typu "I remember that there was some issue with".

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Patch_1.5.0
2. http://wow.gamepedia.com/Battleground

**Comment by jubasek21** [comment]
http://wow.gamepedia.com/Battleground - z artykulu żeby ktoś nie musiał szukać: " Unlike Spirit Healers found in the rest of the world, players resurrected by Spirit Guides are restored to full health and mana, as are any pets or minions."

**Comment by Triceps69** [comment]
oczywiście, że powinen resać, tak samo z demonami u locka

**Comment by OrgiVed** [comment]
Ten bug pojawiał sie chyba już 2 razy tu i mam nadzieje że przy tym 3-cim razie w końcu go naprawią :)

**Comment by Kougraa** [comment]
Tak jak wyżej. Pet powinien się resać wraz z postacią.

**Comment by xsitdev** [comment]
Wgrane zostanie 28.12 (dzisiaj nad ranem)

**Comment by valcy** [comment]
No chyba jednak nie.

**Comment by valcy** [comment]
No chyba jednak nie zostalo wgrane. Albo fix nie dziala?
