### ISSUE TITLE
[QUEST] JUST FOLLOWING ORDERS [IMPORTANT]

### ISSUE THREAD

**Issue by Triceps69** [RaphaelSunwell/Sunwell-BugTracker-SCv2#419]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Quest polega na zagadniu do npc, następnie pojawia się krokodyl, trzeba go zabić i zalicza q. QUEST JEST BARDZO WAŻNY PONIEWAŻ BLOKUJE CHAIN W SCHOLAZAR BASIN.

**Obecne działanie**: NPC działa jednorazowo, tj. po interakcji nie resetuje się do pierwotnego stanu samoistnie, lecz pozostaje z szarym pytajnikiem, kolejny gracz nie ma możliwości zrobienia questa. Po użyciu przez GMa, komend .die i .respawn, npc działa poprawnie.
Było testowane z różnymi graczami i dwoma GMami, w tym HGM, w różnych konfiguracjach i odstępach czasu, NPC nie resetuje się samoistnie, dopiero restart servera, lub pomoc GM, umożliwia zrobienie questa.

**Oczekiwane działanie**: Po zrobieniu questa przez gracza npc powinien zniknąć, a następnie zrespawnować się w stanie umożliwiającym następnej osobie zrobienie questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wziać quest
2. iść do npc http://www.wowhead.com/npc=28217/injured-rainspeaker-oracle
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12540/just-following-orders
2. http://www.wowhead.com/npc=28217/injured-rainspeaker-oracle
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Potwierdzam. Nie jednokrotnie interweniowałem w tej sprawie, aby zrespawnić npc.

**Comment by kovaq** [comment]
Blad wciaz wystepuje.
http://screenshooter.net/103037023/dcvettr

**Comment by Shon-su** [comment]
poprawione
