### ISSUE TITLE
[Quest] Relic of the Earthen Ring

### ISSUE THREAD

**Issue by Piootrek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#42]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest Relic of the Earthen Ring jest dostępny dla graczy, mimo że został dodany dopiero w patchu 3.2.0

**Obecne działanie**: j.w

**Oczekiwane działanie**: Quest Relic of the Earthen Ring powinien być ukryty do momentu wypuszczenia contentu z patcha 3.2.0

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=14111
2. http://wowwiki.wikia.com/wiki/Quest:Relic_of_the_Earthen_Ring_(Alliance) //Wrath-Logo-Small Patch 3.2.0 (04-Aug-2009): Added.
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Piootrek** [comment]
To samo z questem dla hordy http://wotlk.openwow.com/quest=14100

**Comment by ThePuppetMaster** [comment]
#35
