### ISSUE TITLE
[QUEST] Convocation at Zol'heb

### ISSUE THREAD

**Issue by jubasek21** [RaphaelSunwell/Sunwell-BugTracker-SCv2#420]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Użycie quest itemu w kręgu, w którym powinniśmy go użyć niczym nie skutkuje, nic sie dzieje.

**Obecne działanie**: Quest item służący do przyzwania bossa "Prophet of Akali" w konkretnym miejscu nie działa. Całkowity brak eventu questa.

**Oczekiwane działanie**: Gdy dotrzemy na miejsce znajduje się w nim krąg, w którym używamy quest itemu, powinien pojawić się boss wypowiadając kwestie, zaczynamy z nim walkę po czym po zbiciu mu HP boss nakłada na siebie bańkę, wypowiada kwestie i pojawia się NPC Har'koa, który nam pomaga w zabiciu Propheta (wszystko widoczne na filmiku poniżej, który pokazuje jak powinno to działać).

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa.
2. Dotrzeć do kręgu w lokacji Zol'heb.
3. Zobaczyć, że quest item w kręgu nie działa, więc questa nie da się ukończyć.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12730/convocation-at-zolheb
2. http://www.wowhead.com/npc=29028/prophet-of-akali
3. http://www.wowhead.com/npc=28401/harkoa
4.https://www.youtube.com/watch?v=EBTPnGj1Etg - filmik z poprawnie działającym questem

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://wow.gamepedia.com/Zol%27Heb

**Comment by valcy** [comment]
Juz zgloszone 4ty raz.

**Comment by jubasek21** [comment]
Mój błąd, do zamknięcia, nie dopatrzyłem.

**Comment by valcy** [comment]
Jako zakladajacy powinienes miec mozliwosc zamkniecia tego samemu ;p
Close issue obok dodania komentarza

**Comment by garlyn** [comment]
do tej pory nie działa :)
