### ISSUE TITLE
[NPC] Kael'thas Sunstrider MGT

### ISSUE THREAD

**Issue by gitghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#421]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Na drugiej fazie walki NPC traci całe aggro i resetuje encounter.

**Obecne działanie**:
Rozpoczynamy encounter, dochodzimy do drugiej fazy, NPC castuje Gravity Lapse. 
Traci całe aggro, resetuje encounter.
Jeżeli zaggruje się go szybko rozpoczyna castowanie Gravity Lapse i sytuacja się powtarza.
Jeżeli NPC zregeneruje życie powyżej 50% walka rozpoczyna się od nowa od pierwszej fazy.

**Oczekiwane działanie**:
NPC nie powinien resetować walki.
Po trzydziestu sekundach od wycastowania Gravity Lapse faza druga powinna się skończyć i powinno istnieć 10 sekundowe okienko na dps.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do MGT i dojść do NPC.
2. Rozpocząć encounter i zbić last bossa poniżej 50%.
3. Bug nie zależy od poziomu trudności instancji. Występuje zarówno na normalu jak i na hero.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Kael%27thas_Sunstrider_(Magisters%27_Terrace_tactics)
2. http://www.wowhead.com/npc=19622/kaelthas-sunstrider
3. http://www.wowhead.com/spell=35941/gravity-lapse

**Comment by raveeneer** [comment]
Potwierdzam.

**Comment by xsitdev** [comment]
https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/549
