### ISSUE TITLE
<spell> Misdirection

### ISSUE THREAD

**Issue by valcy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#422]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Misdirection - The current party or raid member targeted will receive the threat caused by your next damaging attack and all actions taken for 4 sec afterwards.

**Obecne działanie**:  Mend pet triggeruje Misdirection.

**Oczekiwane działanie**: Misdirection powinien byc triggerowany wylacznie przez skille zadajace obrazenia.
Czytajac sam opis skilla widzimy ze dziala on blednie.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Uzyc MD
2. Uzyc Mend Peta

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=34477
2. http://wotlk.openwow.com/spell=48990

**Comment by OrgiVed** [comment]
Z tego co wiem, również samo zarzucenie Serpent Sting'a odpala MD a powinien dopiero pierwszy tick.

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane z najbliższym update.
