### ISSUE TITLE
[NPC] 26202 - Ziggurat Defender (1 poprawka spawnu)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#426]
**Obecne działanie**: 1 z wymienionych NPC respawn ma w The Wailing Ziggurat gdzie jest Thassarian.

Screen Sunwell: http://imgur.com/a/Af5PU

**Oczekiwane działanie**: Wymieniony NPC nie powinien mieć respawn pointu w tym Zigguracie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzić spawn.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=26202/ziggurat-defender
2. http://wowwiki.wikia.com/wiki/Wailing_Ziggurat

**Comment by Shon-su** [comment]
poprawione
