### ISSUE TITLE
[Localization] The Wailing Ziggurat (poprawka) Part 1

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#427]
**Obecne działanie**: Wchodząc w to miejsce poza [błędnym spawnem](https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/426) to NPC stoją i nic nie robią.
Dowód: http://imgur.com/a/Af5PU
**Oczekiwane działanie**: Opis dokładny każdej jednostki:
- **High Deathpriest Isidorus <Cult of the Damned>** - jednostka powinna używać ciągle błągania w kierunku do szkieleta o nazwie Lurid.
- **Lurid** - Szkielet companion Thassariana stojący przed w/w NPC
- **Thassarian** - Powinnien channelować w "licha" fioletową wstęgę. Co jakiś czas wypowiadać kwestię (Quotes) oraz dawać nam buffa [Empowered Blood Presence](http://www.wowhead.com/spell=50995/empowered-blood-presence)
- **Tanathal** - Lich, w którego channeluje Thassarian.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzić miejsce.

**Linki WoWHead/OpenWoW**:

1. [Loc.] http://wowwiki.wikia.com/wiki/Wailing_Ziggurat
2. http://www.wowhead.com/npc=26171/high-deathpriest-isidorus
3. http://www.wowhead.com/npc=26185/lurid
4. http://www.wowhead.com/npc=26170/thassarian
5. http://www.wowhead.com/npc=26173/tanathal

**Filmik**: https://youtu.be/W0yvLVhPFC4

**Comment by Afgann** [comment]
Thassarian channeluje spell 46685.
