### ISSUE TITLE
[Localization] The Wailing Ziggurat (poprawka) Part 2

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#428]
**Obecne działanie**: [Part 1](https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/427) odnosi się do wnętrza w/w Ziggurat'u. Part 2 odnosił się będzie do jego okolicy. Brak u nas NPC, które wybiegają z jego "wyjścia/wejścia". A u nas stoją obok Zigguratu.

Dowód: http://imgur.com/a/TOe7i

**Oczekiwane działanie**: NPC Fleeing Cultist nie powinni stać dookoła Zigguratu. Powinni wybiegać i co 10 - 20 s wypowiadać [Quotes](http://wowwiki.wikia.com/wiki/Fleeing_Cultist). Przed schodami powinien na chwilkę dosłownie 1s przystanąć na dialog swój.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzić.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Wailing_Ziggurat
2. http://www.wowhead.com/npc=26189/fleeing-cultist
3. Quotes: http://wowwiki.wikia.com/wiki/Fleeing_Cultist

**Filmik**: https://youtu.be/9O6gjVpoCP4

**Comment by Mithras2801** [comment]
Czym sniffa odczytać??

**Comment by Afgann** [comment]
https://github.com/TrinityCore/WowPacketParser

**Comment by Mithras2801** [comment]
@Afgann Napisz jak to dokładnie odczytać itp. Chodzi o uruchomienie programu.

**Comment by Shon-su** [comment]
przeciągasz sniffa na .exe generuje się plik. W configu ustawiasz co chcesz żeby generowało i jak generowało

**Comment by Shon-su** [comment]
\WowPacketParser\bin\Debug  
Jak zbudujesz w VS to w tej ścieżce masz plik "WowPacketParser.exe", a "WowPacketParser.exe.config" jak otworzysz notatnikiem to idzie ustawić różne rzeczy

**Comment by Mithras2801** [comment]
Ogarnąłem :D Fajne Dobra co trzeba może coś wrzucę a najlepiej podajcie mail jakiś.

**Comment by Shon-su** [comment]
tak w sumie to do tego konkretnego zgłoszenia niekoniecznie potrzebny jest sniff. Można to zrobić tak "na oko". Prawie mam to zrobione, kilka rzeczy tylko zmienię. Bardziej przydałoby się np. ściągnąć spella jakie castuje Thassarian czy path-y tych mobków co chodzą w stealth #729  . Generalnie jak ktoś jest w stanie dostarczyć sam plik z sniffem to ja już sobie wyciągne z tego co będę potrzebował :D

Tylko to są takie małe visuale więc wiesz

**Comment by Mithras2801** [comment]
Visuale najbardziej zadowalają. Pograsz na globie to zobaczysz :D JA jak wchodzę na raidy dungi z wotlk to nie ma porównania co jest na sunwellu. Jest masa pracy i teraz to zauważam dopiero kiedy chodzę po ToCH, Ulduar ICC i innych dungach czy raidach. Tego na sunwellu raczej nie zobaczą prędko pewnie :D
