### ISSUE TITLE
[NPC] 26673 i 26459 - Image of Archmage Modera i Commander Saia Azuresteel (brak)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#429]
**Obecne działanie**: Stoją i nie debatują.

**Oczekiwane działanie**: NPC powinny pokazywać jakby ze sobą rozmawiały przy mapie. 
Image of Archmage Modera - powinna lewitować.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzić

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=26673/image-of-archmage-modera
2. http://www.wowhead.com/npc=26459/commander-saia-azuresteel
3. http://wowwiki.wikia.com/wiki/Stars'_Rest

**Filmik**: https://youtu.be/pGpQo2o82jU

**Comment by Shon-su** [comment]
poprawione
