### ISSUE TITLE
[QUEST] Search Stillpine Hold

### ISSUE THREAD

**Issue by Obiwansowanobi** [RaphaelSunwell/Sunwell-BugTracker-SCv2#43]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:[QUEST] Search Stillpine Hold

**Obecne działanie**:Posiadając questa przy interakcji z kryształem nie wyświetla komunikatu dającym ukończyć quest.
Zamiast tego pojawia się koło zębate a kryształ pokazuje komunikat : "Greetings...".

**Oczekiwane działanie**: Interakcja z kryształem powinna pozwolić oddać questa. Dzięki czemu dostalibyśmy dostęp do pozostałych questów.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Naprawić interakcje z kryształem pozwalającą oddać questa. 
2.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9565/search-stillpine-hold#comments
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Powinno już działać.
