### ISSUE TITLE
[Quest] 12851 - Going Bearback (poprawka)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#431]
**Obecne działanie**: W chwili obecnej łatwo jest zabić Gianty do Questa. Problemem jest, że nie respią się wilki. A jak już 2 się zresztą to umierają (2 respawny tylko) oraz 3ci spell dodany ?.

**Oczekiwane działanie**: Powinno być więcej wilków do Q i szybszy respawn oraz 2 spelle możliwe do użytku.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzić Q
2. Sprawdzić misia, którym biegamy.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12851/going-bearback
2. http://www.wowhead.com/npc=29598/icefang

**Filmiki**: 
https://www.youtube.com/watch?v=GmOQtOsfXEk 
https://www.youtube.com/watch?v=uA7YubiAHGA

**Comment by Mithras2801** [comment]
Jutro dodam screen jak wygląda panel mounta do questa

**Comment by kovaq** [comment]
https://youtu.be/ZL5TNSgfTlQ - wraz z panelem mounta ;)
