### ISSUE TITLE
[ITEM] Hateful Gladiator's War Edge

### ISSUE THREAD

**Issue by Varocku** [RaphaelSunwell/Sunwell-BugTracker-SCv2#432]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Po założeniu throwna  Hateful Gladiator's War Edge kupionego za honor, nie ma możliwości użycia umiejętności Throw jak i za równo Deadly Throw.
Z każdą inną bronią typu Thrown tego problemu nie ma.

**Oczekiwane działanie**: Da się rzucać oraz używać Deadly Throw.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Założyć Hateful Gladiator's War Edge.
2. Target 
3. Użyć Thrown lub po nabiciu Combo point Deadly Throw.

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/item=42449/hateful-gladiators-war-edge
2.  http://www.wowhead.com/spell=2764/throw
3.  http://www.wowhead.com/spell=26679/deadly-throw

**Comment by royalkubix** [comment]
Potwierdzam, mam ten sam problem nie mogę używać Thrown Hateful Gladiator's War Edge. Statystyki dodaje ale nie można rzucać.

**Comment by bartekmad** [comment]
usunięcie cachu powinno pomóc

**Comment by slammerr** [comment]
Usunięcie cachu nie pomaga. Potwierdzam buga. Proszę o szybki rework

**Comment by xsitdev** [comment]
Poprawione prosze usunac cache w celu uzyskania efektu.
