### ISSUE TITLE
Violet Hold - Ichoron

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#437]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Obecne działanie**: W momencie wylosowania bossa Ichoron wszystko jest ok, ale kiedy zaatakujemy go zanim wyjdzie z wody to cały dung resetuje się do 0.

**Oczekiwane działanie**: Boss powinien być możliwy do zaatakowania po otwarciu bramy, ewentualnie do czasu wyjścia z wody dać mu unable to target.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść na VH (robiłem wersje HC) i wylosować wodnego bossa. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=29313/ichoron

**Comment by Mithras2801** [comment]
Po wyjściu z wody. 
https://www.youtube.com/watch?v=PT42k-l0wo0
