### ISSUE TITLE
[QUEST] Glyphic Letter

### ISSUE THREAD

**Issue by Obiwansowanobi** [RaphaelSunwell/Sunwell-BugTracker-SCv2#44]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:[QUEST] Glyphic Letter

**Obecne działanie**: Brak NPC.

**Oczekiwane działanie**: Pojawienie się NPC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wprowadzić NPC do gry.
2.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Quest:Glyphic_Letter
2. http://wowwiki.wikia.com/wiki/Khelden_Bremen
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
NPC znajduje się w odpowiednim miejscu.
