### ISSUE TITLE
[CORE] AUCTION HOUSE

### ISSUE THREAD

**Issue by Triceps69** [RaphaelSunwell/Sunwell-BugTracker-SCv2#441]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: AH nie działa od późnych godzin nocnych, do godzin porannych.  W tym momencie jest 8:45 i nic nie można wyszukać. Nie mam pojęcia czym to może być spowodowane.

**Oczekiwane działanie**: AH powinno działac 24/7

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Grać rano
2. Wejść na AH
3. 

**Linki WoWHead/OpenWoW**:

1. http://forum.sunwell.pl/viewtopic.php?f=35&p=28107&sid=05b771752013db9947e30a0a15a8a98a#p28107
![wowscrnshot_122116_084430](https://cloud.githubusercontent.com/assets/23584783/21381167/07c0e76e-c75a-11e6-9bef-bc0fa4bcf069.jpg)

2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by raveeneer** [comment]
Potwierdzam. Godzina 4:07 też nic nie da się wyszukać.

**Comment by raveeneer** [comment]
Jednak mogę wyszukać, natomiast samo wyszukiwanie trwa czasami zbyt długo (np. 2/3 min.)

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane około 6 rano.
