### ISSUE TITLE
[QUEST] Harp on This!

### ISSUE THREAD

**Issue by Bradsw** [RaphaelSunwell/Sunwell-BugTracker-SCv2#442]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Zbugowany pojazd z questa: "**Xink's Shredder**".

**Obecne działanie**:
Za pierwszym razem gdy otrzymamy quest po przywołaniu pojazdu "_**Xink's Shredder**_" przez "_**Xink's Shredder Control Device**_" da się do niego wsiąść. Lecz gdy wyjdziemy z niego i będziemy chcieli znów zasiąść za sterami to po najechaniu na jego myszka nie ma żadnej interakcji.

**Oczekiwane działanie**:
Po wyjściu z pojazdu powinien się zdespawnowac. Kolejny pojazd przywołujemy przez "_**Xink's Shredder Control Device**_".

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wziąć quest "**_Harp on This!_**" od **_Narf_**'a w **_Nozzlerust Post_**.
2. Udać się do **_Coldwind Heights_**.
3. Z pomocą "_**Xink's Shredder Control Device**_" przywołać "_**Xink's Shredder**_".
4. Spróbować zasiąść za sterami.
5. Jeżeli siedzimy w pojeździe to wyjść z niego.
6. Ponownie wejść do pojazdu (**może się nie udać z uwagi na bug**)

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12052/harp-on-this
2. https://www.youtube.com/watch?v=AYYbZFE4ajc
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
- **Narf** (questgiver): X: 54.5 Y: 23.6
- **Coldwind Heights** (zone): X: 48.1 Y: 20.1

**Comment by Shon-su** [comment]
poprawione nie dograne jeszcze
