### ISSUE TITLE
[Item] 41556 Slag Covered Metal - Drop z Stormforged Iron Giant (chain Sons of Hodir)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#443]
**Obecne działanie**: Quest item można dropnąć w każdym momencie.

**Oczekiwane działanie**: Quest item powinien dropić od questa [Mending Fences](http://www.wowhead.com/quest=12915/mending-fences) . Quest jest kontynuacją chain'u.
Kiedy gracz wyrzuci lub abandonuje misje powinien móc dropnąć item ponownie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Robić chain
2. Dropić item.

**Linki WoWHead/OpenWoW**:

1. Item: http://www.wowhead.com/item=41556/slag-covered-metal (**Drop Chance: 28.17%**)
2. Drop NPC: http://www.wowhead.com/npc=29375/stormforged-iron-giant
3. Quest, przy którym powinien item dropić:
http://www.wowhead.com/quest=12915/mending-fences

**Comment by Shon-su** [comment]
z tego co sprawdziłem to tak to właśnie działa w tej chwili.
