### ISSUE TITLE
The Culling of Stratholme - Human Illusion, forma druida

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#445]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: The Culling of Stratholme - Human Illusion i priorytet nadawania buffa przy wejściu w forme jest niepoprawny.

**Obecne działanie**: Po wejściu do CoSa jak druid i zmianie w kota, misia itd. cały czas posiadamy na sobie buffa Human Illusion, bicie w kocie jako human wyglądą dość dziwnie.

**Oczekiwane działanie**: Po wejściu w formie powinniśmy zmienić swój wygląd zgodnie z aktualnie używaną formą. Priorytet powinien wyglądać tak: Druid's Form > Human Illusion > Humanoid Form

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść na CoS jako druid i wejść w forme.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=35480

**Comment by Shon-su** [comment]
DELETE FROM `conditions` WHERE `SourceEntry` = 35480;
INSERT INTO `conditions` VALUES
(17, 0, 35480, 0, 0, 1, 0, 5487, 0, 0, 1, 0, 0, '','Don`t apply Human Illusion while in Bear Form'), -- bear 
(17, 0, 35480, 0, 0, 1, 0, 24858, 0, 0, 1, 0, 0, '','Don`t apply Human Illusion while in Moonkin Form'), -- moonkin
(17, 0, 35480, 0, 0, 1, 0, 768, 0, 0, 1, 0, 0, '','Don`t apply Human Illusion while in Cat Form'), -- cat form
(17, 0, 35480, 0, 0, 1, 0, 33891, 0, 0, 1, 0, 0, '','Don`t apply Human Illusion while in Tree of Life Form'); -- tree of life

**Comment by Shon-su** [comment]
`DELETE FROM `conditions` WHERE `SourceEntry` = 35480;
INSERT INTO `conditions` VALUES
(17, 0, 35480, 0, 0, 1, 0, 5487, 0, 0, 1, 0, 0, '','Don`t apply Humna Illusion while in Bear Form'), -- bear 
(17, 0, 35480, 0, 0, 1, 0, 24858, 0, 0, 1, 0, 0, '','Don`t apply Humna Illusion while in Moonkin Form'), -- moonkin
(17, 0, 35480, 0, 0, 1, 0, 768, 0, 0, 1, 0, 0, '','Don`t apply Humna Illusion while in Cat Form'), -- cat form
(17, 0, 35480, 0, 0, 1, 0, 33891, 0, 0, 1, 0, 0, '','Don`t apply Humna Illusion while in Tree of Life Form'); -- tree of life`

**Comment by Shon-su** [comment]
DELETE FROM `conditions` WHERE `SourceEntry` = 35480;
INSERT INTO `conditions` VALUES
(17, 0, 35480, 0, 0, 1, 0, 5487, 0, 0, 1, 0, 0, '','Don`t apply Human Illusion while in Bear Form'),
(17, 0, 35480, 0, 0, 1, 0, 24858, 0, 0, 1, 0, 0, '','Don`t apply Human Illusion while in Moonkin Form'), 
(17, 0, 35480, 0, 0, 1, 0, 768, 0, 0, 1, 0, 0, '','Don`t apply Human Illusion while in Cat Form'),
(17, 0, 35480, 0, 0, 1, 0, 33891, 0, 0, 1, 0, 0, '','Don`t apply Human Illusion while in Tree of Life Form');

**Comment by Shon-su** [comment]
będzie dograne

**Comment by sanctify21** [comment]
Z changeloga wynika, że dograne, ale moim zdaniem dalej niepoprawione ;-)

Dowód:
![](http://i.imgur.com/W9NQOX1.png)

**Comment by Shon-su** [comment]
hmmm.. to zerknę jeszcze raz :)

**Comment by Shon-su** [comment]
PTR
![wowscrnshot_020917_162036](https://cloud.githubusercontent.com/assets/17860936/22789606/bc759532-eee3-11e6-82fb-47f7d5707b18.jpg)

**Comment by sanctify21** [comment]
u mnie screen zrobiony dzisiaj około godziny 12stej, więc już sporo po wgraniu poprawki, coś na głównym realmie musiało się nie dograć może
