### ISSUE TITLE
LEASH - agro mobków w instach

### ISSUE THREAD

**Issue by bartekmad** [RaphaelSunwell/Sunwell-BugTracker-SCv2#447]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: "Non-boss mobs in instances generally do not leash. The only way to escape them is to exit the instance, or to use an aggro-clearing ability like the hunter's feign death."

**Obecne działanie**: Mobki na instach samoczynnie się odpulowywują, przeważnie gdy odbiegnie się na duży dystans od ich początkowego położenia.

**Oczekiwane działanie**: Mobki nie powinny się odpulowywać

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść do dowolnej instancji, np. stockade, czy scarlet monastery itp.
2. Zagrować mobki i biec przed siebie.
3. 

**Linki WoWHead/OpenWoW**:

1. https://youtu.be/NFu825jf4v4
2. http://wowwiki.wikia.com/wiki/Leash
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
-

**Comment by xsitdev** [comment]
Poprawione przy obróbce Naxxramas.
