### ISSUE TITLE
QUEST: Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Kilerek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#448]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Znikające Quest NPC 

**Obecne działanie**: Quest NPC znikają po zbliżeniu się do nich

**Oczekiwane działanie**: Quest NPC powinno dać się normalnie uratować gryfem

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zbliżyć się do Quest NPC 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Dragonblight, Wintergarde Keep

**Comment by Mithras2801** [comment]
Duplikat https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/189

**Comment by Mithras2801** [comment]
Quest można już zrobić normalnie.
