### ISSUE TITLE
[WEBSITE][Why Sunwell] 404 ERROR - FILE NOT FOUND

### ISSUE THREAD

**Issue by XevL** [RaphaelSunwell/Sunwell-BugTracker-SCv2#449]
[//]: # (****************************************************************)
[//]: # (** DO NOT REMOVE THIS TEMPLATE**)
[//]: # (****************************************************************)
 
**Description**:
 
**How it works now**: WRITE HERE WHAT'S THE PROBLEM
404 ERROR - FILE NOT FOUND

**How it's supposed to work**: WRITE HERE HOW IT SHOULD WORK
 http://webcache.googleusercontent.com/search?q=cache:q4xLiZyNQhgJ:sunwell.pl/page/whysunwell+&cd=1&hl=fr&ct=clnk

**Steps to reproduce bug**:
1.  Visit "Why Sunwell" under "Information" tab.
2.  http://sunwell.pl/page/whysunwell
 
**Links to WoWHead/OpenWoW**:
 
1. 
2. 
3. 
 
**Coordinates from GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
The bookmark "Why Sunwell" has been removed, that's a reason of 404 Error.
