### ISSUE TITLE
STRONA/STATYSTYKI

### ISSUE THREAD

**Issue by morgaur** [RaphaelSunwell/Sunwell-BugTracker-SCv2#45]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

Brak update achievments points na stronie:

W zakładce Ranking/Osiągnięcia Achievment points nie aktualizują się. Aktualizuje się tylko level a punkty pozostają niezmienione.

Achievment points powinny się aktualizować na bieżąco.

Wejść na stronę http://sunwell.pl/achievement_statistics i sprawdzic zgodność wyświetlanych tam punktów ze stanem faktycznym.

**Comment by xsitdev** [comment]
Poprawione, zostanie wgrane o 5 rano, dnia 22.11.
