### ISSUE TITLE
Pet huntera

### ISSUE THREAD

**Issue by spyke13** [RaphaelSunwell/Sunwell-BugTracker-SCv2#450]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Pet huntera nie uzywa skilli specjalnych na biegnacych targetach

**Obecne działanie**:  Pet huntera nie uzywa skilli specjalnych na biegnacych targetach, po dobiegniecu zatrzymuje sie jakby chcial uzyc ale stracil zasieg

**Oczekiwane działanie**: Pet powinien dobiec do targetu i uzyc skilla

**Co należy zrobić, aby odtworzyć ten błąd**: Wystraczy grac hunterem PvP ;d

https://www.youtube.com/watch?v=-yBec89GcPs&feature=youtu.be

Inne pety ze skillami melee range maja to samo

**Comment by Vaelevian** [comment]
Po przejściu na nowe core działa poprawnie.
