### ISSUE TITLE
[season5][arenarating]Zly rating arena teamu po jego stworzeniu

### ISSUE THREAD

**Issue by Baggedmilk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#453]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po stworzeniu arena teamu, rating tego teamu powinien wynosic 1500. Dopiero na sezonie 6 powinnismy zaczynac od 0 ratingu.

**Obecne działanie**: Tworzac arena team zaczynamy z ratingiem 0

**Oczekiwane działanie**: Tworzac arena team powinnismy zaczynac z ratingiem 1500.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Stworzyc arena team
2. Zobaczyc, ze ma sie rating 0
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Season_6_Arena_rewards
2. http://wowwiki.wikia.com/wiki/Arena_PvP_system
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Mamy s5 więc powinno być od 1500

**Comment by Baggedmilk** [comment]
bump
