### ISSUE TITLE
[Quest]  [63] [As the Crow Flies](Part 2 of 3)

### ISSUE THREAD

**Issue by winkros** [RaphaelSunwell/Sunwell-BugTracker-SCv2#455]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Po użyciu przedmiotu  [Stormcrow Amulet] i przeleceniu pod postacią kruka nad jeziorami nie zamienia nas do podstawowej postaci/modelu.

**Oczekiwane działanie**: Po użyciu przedmiotu  [Stormcrow Amulet] i przeleceniu pod postacią kruka nad jeziorami powinno zaliczyć quest oraz zmienić nas do podstawowej postaci/modelu

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić pierwszy quest z chaina
2. Wsiąść quest [As the Crow Flies](Part 2 of 3)
3. Użyć itemu przy NPC od którego bierze się quest

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=9718
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
78,4; 61,9
![wowscrnshot_122416_211724](https://cloud.githubusercontent.com/assets/24761349/21470218/0c7ac6d0-ca7f-11e6-8c4b-c79727e20bca.jpg)
![wowscrnshot_122516_084437](https://cloud.githubusercontent.com/assets/24761349/21470220/15043a52-ca7f-11e6-8dda-c9c2f3adab79.jpg)

**Comment by xsitdev** [comment]
Wgrane zostanie 28.01 (4 rano).
