### ISSUE TITLE
[DAILY QUEST]Will of the Titans

### ISSUE THREAD

**Issue by arianii0** [RaphaelSunwell/Sunwell-BugTracker-SCv2#457]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Zadanie polega na zabiciu 50 "Frenzyheart Attacker" wraz z pomocą Soo-Hulu.

**Obecne działanie**: Po wydropieniu "tainted crystal" biegniemy do posążku by przyzwać Soo-Hulu lecz nasz kryształ nie chce zadziałać "Great Lightning Stone requires" mimo, że stoimy w dobrym miejscu.

**Oczekiwane działanie**: Po użyciu powinniśmy przyzwać Soo-Hulu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dropimy kryształ.
2. Podbiegamy do posągu.
3. Domniemany Soo-Hulu nie chce nam się przyzwać.

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/quest=12705/will-of-the-titans](url)
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: X: 5110.493652 Y: 5467.497070 Z: -91.837143 Sholazar Basin

**Comment by xsitdev** [comment]
Wgrane zostanie 28.12 (jutro nad ranem)
