### ISSUE TITLE
[SPELL] TURN THE TABLES

### ISSUE THREAD

**Issue by wypas** [RaphaelSunwell/Sunwell-BugTracker-SCv2#458]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Talent Turn the tables daje buffa również innym klasom (na pewno druidowi w kocie)

**Obecne działanie**: Talent Turn the tables daje buffa również innym klasom (na pewno druidowi w kocie) [http://imgur.com/a/04Aah](url)

**Oczekiwane działanie**: Talen turn the tables powinien dawac buffa tylko dla assasination rogue z tym talentem

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wybrac sie na inste z rogue assa z talentem turn the tables
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=51629
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by wypas** [comment]
dorzucam jeszcze linka z dalaran-wow: 
http://www.dalaran-wow.com/forums/community/general-discussion/topic/5431/shared-talents-between-rogues 

mozliwe ze inne tego typu talenty rowniez dzialaja niepoprawnie, ale nie mam pewnosci

**Comment by xsitdev** [comment]
Wgrane zostanie 28.12 (jutro nad ranem)
