### ISSUE TITLE
The Oculus - Mage-Lord Urom (Summon Menagerie)

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#459]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Obecne działanie**: Mage-Lord Urom po wycastowaniu spella Summon Menagerie, który powinien przyzwać paczkę mobów do zbicia, nie przyzywa mobów tylko teleportuje się na kolejną 'wyspę'. Po 3krotnym goneniu ww. npc ten ucieka i jest niemożliwy do zbicia w centralnym pierścieniu. 

**Oczekiwane działanie**: Mage-Lord Urom w momencie zaatakowania na wyspie powinien w miejscu casta przyzwać jedną z trzech paczek mobów a następnie powinien wyteleportować się na kolejną wyspę, w momencie dolecenia na trzecią wyspę npc powinien przyzwać ostatnią paczkę i przeteleportować się do centralnego pierścienia. Ogólnie najlepiej prześledzić na spokojnie cały encounter i poprawić. Przed restartem cały dung śmigał dobrze, na dniach ostatnio coś się zrąbało.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do dunga 'The Oculus', zbić pierwszego bossa, constructy i zacząć walkę z Mage-Lord Urom. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=27655/mage-lord-urom#abilities

**Comment by mordeusz** [comment]
Miałem pare razy sytuacje gdzie teleportawal sie z pierwszej platformy na druga i tam stal juz z 4 mobami ktore powinny byc na tej poczatkowej platformie. Przy przejsciu z 2 na 3 bylo to samo, a potem juz bez addow teleportowal sie na srodkowy pierscien gdzie mozna go bylo normalnie zbic.

**Comment by xsitdev** [comment]
Wgrane zostanie 28.12 (dzis nad ranem)
