### ISSUE TITLE
Cloak of shadows i death grip

### ISSUE THREAD

**Issue by kevery123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#460]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Cloak of Shadows rogala nie dziala jak powinien. A mianowicie jest 100% szansy ze np spell jak death grip dka wejdzie w cloak of shadows a powinno byc 10%.

**Obecne działanie**: Jest 100% szansy ze dka gripnie rogala na cloaka

**Oczekiwane działanie**: powinno byc 10% szansy ze dk gripnie rogala na cloku

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rogal uzywa cloak of shadows na duelu z dka
2. Death Knight uzywa death gripa na cloak of shadows ( wchodzi zawsze )
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by tokacz** [comment]
o ile dobrze pamiętam to death grip jest czysto fizycznym skillem więc cloak of shadows go nie zatrzyma.

**Comment by tokacz** [comment]
o ile dobrze pamiętam to death grip jest czysto fizycznym skillem więc cloak of shadows go nie zatrzyma. Podobna sytuacja jest jak dk rzuci któreś plagi i ma glyphy na nie.

**Comment by kevery123** [comment]
Nie death grip jest magicznym spellem

**Comment by kevery123** [comment]
http://wotlk.openwow.com/spell=49575 tu wyraznie pisze "beam of unholy power"

**Comment by tokacz** [comment]
instant fizyczny:
[http://wotlk.openwow.com/spell=49576](url)
[http://wowwiki.wikia.com/wiki/Death_Grip](urll)
[https://us.battle.net/forums/en/wow/topic/1127152916](url)

**Comment by kevery123** [comment]
Chyba se jaja robisz na starym sunie/ na globalu( gralem calego wotlka ) i na AT dzialalo to tak ze nie mozna bylo walic gripa na cloka ( bylo 10% szansy ze wejdzie )

**Comment by tokacz** [comment]
Na globcu siedziałem od 4.x (nie pamiętam czy od 4.3 czy wcześniej) i trochę to wszystko inaczej wyglądało. Stary sunwell nie może być wykładnią działania, ani at który też jest privem (niby blisko globca ale jednak) Możliwe, że na 3.x był traktowany jako shadow spell i wtedy rzeczywiście ma buga i przy cos może być zmisowany/zablokowany. Nie gram dk, ale mam sentyment do niego i nie znalazłem wiarygodnego i 100% pewnego źródła czy powinien czy nie przechodzić przez cloak. Możliwe, że jestem w błędzie wtedy zwracam honor i kajam się i przyznaję ci rację. Ale to nie powód, żeby pisać, że sobie jaja robię bo też wiarygodnie nie udokumentowałeś jak powinno być, a zdania są podzielone. Na globcu później był fizycznym skillem, podobnie jak blizzard zmienił chains of ice (chyba na 4.1). I tak o wszystkim zdecyduje dev, a nie to co nam się wydaje. Sprawdzałeś cloak of shadows z innymi klasami?

**Comment by xsitdev** [comment]
Atak fizyczny, zostało zweryfikowane przez doświadczone osoby z Retaila.

**Comment by kevery123** [comment]
nie dziwie sie ze tyle bugów jest na tym servie jest zamykacie takie posty typowo 100% prawidłowe, jeśli potrzebujecie dowodów wejdzcie sobie do gry i przeczytajcie co robi death grip. Jest napisane "Harness the unholy energy" ale co tam wedlug administracji sunwella unholy nie jest magia tylko fizycznym skillem. Mam z was beke tworzycie server a nie ma cie pojecia o wotlku i wychodzi na to ze nigdy nie graliscie na retailu skoro zamykacie takie posty. PS combat jest tak zbugowany ze rogal jest niegrywalny i zwykle wyslanie peta nabija unedless combat ale co tam zamykajcie posty.
