### ISSUE TITLE
[WEBSITE][ARMORY]Search two characters name.

### ISSUE THREAD

**Issue by XevL** [RaphaelSunwell/Sunwell-BugTracker-SCv2#461]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Can't search two characters name.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Search string must be longer than 2 characters!

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Allow for 2 characters name search.

**Comment by Kougraa** [comment]
#284
