### ISSUE TITLE
Faction Leaders - brak skilli

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#463]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Obecne działanie**: Liderzy frakcji Alliance (Hordy raczej też) nie używają przypisanych im skilli w momencie zaatakowania

**Oczekiwane działanie**: Liderzy frakcji powinni w walce używać unikalnych dla nich umiejętności.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakować jednego z liderów frakcji Alliance lub Hordy.

**Linki WoWHead/OpenWoW**:

Alliance:
1. http://wotlk.openwow.com/npc=7999#abilities
2. http://wotlk.openwow.com/npc=2784#abilities 
3. http://wotlk.openwow.com/npc=29611#abilities
4. http://wotlk.openwow.com/npc=17468#abilities
5. http://wotlk.openwow.com/npc=7937#abilities

Horde (do sprawdzenia):
1. http://wotlk.openwow.com/npc=4949#abilities
2. http://wotlk.openwow.com/npc=10181#abilities
3. http://wotlk.openwow.com/npc=3057#abilities
4. http://wotlk.openwow.com/npc=10540#abilities
5. http://wotlk.openwow.com/npc=16802#abilities

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
