### ISSUE TITLE
[NPC] Harold Winston

### ISSUE THREAD

**Issue by Shatterx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#464]
Obecne działanie: Brak NPC

Oczekiwane działanie: Dodanie NPC

Co należy zrobić, aby odtworzyć ten błąd:

1. Pojsc w zaznaczone miejsce. Zaznaczone tutaj: http://wotlk.openwow.com/npc=32172
2. 
3. 

Linki WoWHead/OpenWoW:

1. http://wotlk.openwow.com/npc=32172
2. 
3. 

Lokalizacja z koordynatów GPS (X, Y, Z, Map):
Dalaran

**Comment by xsitdev** [comment]
Wgrane zostanie 28.12 (jutro nad ranem)
