### ISSUE TITLE
[SPELL][PALADIN] Złe działanie Judgementów

### ISSUE THREAD

**Issue by Heartbraker** [RaphaelSunwell/Sunwell-BugTracker-SCv2#465]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Przy próbie użycia jakiegokolwiek z judgementów na przeciwników stojących z boku/za nami otrzymujemy informację, że przeciwnik musi stać przed nami, aby można było użyć judgement. Chyba gdzieś czytałem(nie pamiętam czy w grze czy na forum), że już wcześniej tu ten bug występował. Zniknął i powrócił razem z sezonem pvp.

**Obecne działanie**: Nie ma możliwości użycia Judgement of Wisdom/Light/Justice na przeciwnikach nie stojących przed nami.

**Oczekiwane działanie**: Judgement powinien być możliwy do użycia na każdym przeciwniku w zasięgu, niezależnie od jego pozycji względem naszej postaci

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Stanąć plecami do przeciwnika
2. Spróbować użyć jakikolwiek judgement
3. 

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=-fvsNKcA8Ds  -  w ~10sekundzie widać paladyna używającego judgement na mobie stojącym za nim
2. http://wotlk.openwow.com/spell=20271
3. http://wotlk.openwow.com/spell=53408
4. http://wotlk.openwow.com/spell=53407
(nie jestem pewien czy to poprawne id judgementów z wotlk)

**Comment by xsitdev** [comment]
Wgrane zostanie 28.12 (jutro nad ranem)
