### ISSUE TITLE
[QUEST] [NPC] Dendrite Starblaze Aquatic Form

### ISSUE THREAD

**Issue by EdO9IV** [RaphaelSunwell/Sunwell-BugTracker-SCv2#466]
**Opis**: Nie mogę wziąć kolejnej misji od Dendrite Starblaze w Moonglade.

**Obecne działanie**: Jest nad NPC wykrzyknij, aczkolwiek nie mogę wziąć zadania, zadanie wiąże się z formą druida w wodzie.

**Oczekiwane działanie**: NPC zleca mi zadanie [http://wotlk.openwow.com/quest=31](url)
**Co należy zrobić, aby odtworzyć ten błąd**:  
1. Być Taurenem,
2. zrobić misję: [http://wotlk.openwow.com/quest=6124](url),
3. chcieć zrobić kolejną.
4. NPC Dendrite Starblaze w Moonglade nie chce nam zlecić kolejnej misji, mimo że ma nad sobą "wykrzyknij"

**Linki WoWHead/OpenWoW**:

1. [http://wotlk.openwow.com/quest=6124](url)
2. [http://wotlk.openwow.com/quest=31](url)
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
1.Aby otrzymać quest http://wotlk.openwow.com/quest=31 należy wykonać inny chain (jest w linku).
2. http://wotlk.openwow.com/quest=6124, jest częścią chaina dla Alliance więc jako Tauren nie ma szans byś był w stanie go zrobić
