### ISSUE TITLE
[SPELL][SHAMAN] Chain Heal ignoruje targety z full hp.

### ISSUE THREAD

**Issue by wderw** [RaphaelSunwell/Sunwell-BugTracker-SCv2#468]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Po ostatnim updacie serwera (który był mniej więcej 2 dni temu - zawierał między innymi: fix do dalaran fishing daily, frozen orb vendor, auctioneer dla inżynierów) zauważyłem, że chain heal zachowuje się inaczej niż wcześniej. Generalnie można go scastować na gracza z full hp ale późniejsze, automatyczne skoki ignorują targety z full hp (chain heal kończy działanie jeżeli następny jego target to gracz z full hp). Jest to problem nie tylko techniczny ale też może być to hps loss z kilku powodów:
1. Jeżeli 2 graczy z low hp jest oddzielonych od siebie targetem z full hp to chain heal przestanie działać po napotkaniu targetu z full hp (efekt: target z full hp odgrodzi drogę chain healowi do drugiego gracza).
2. Nie ma możliwości procnięcia buffów i hotów takich jak Earthliving, Chained Heal (hps loss)
3. Brak mana returnów z Improved Water Shield. (mana loss)

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Obecnie Chain Heal kończy swoje działanie jeżeli napotka target z full hp.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Powinno być tak, że jeżeli scastuję Chain Heala na np. tanka to później skoczy on do dodatkowych 3 targetów niezależnie od tego czy targety te mają 99 % czy 100 % hp. Powinien on oczywiście zawsze priorytetyzować targety z najmniejszym hp.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ustawić 4 graczy obok siebie.
2. Upewnić się, że mają full hp.
3. Wycastować Chain Heal na któregokolwiek z graczy.
4. Zobaczyć czy Chain Heal skoczy do wszystkich czy nie.

UWAGA: Chain Heal z glyphem skacze 4 razy, bez glypha tylko 3 razy.

**Linki WoWHead/OpenWoW**:

1. [Chain Heal](http://wotlk.openwow.com/spell=1064)
2. [Improved Water Shield](http://wotlk.openwow.com/spell=16180)

**Comment by xsitdev** [comment]
Wgrane zostanie 28.12 (jutro nad ranem)

**Comment by Mithras2801** [comment]
Targety full HP powinny być pomijane. Jesli wycastujemy w target full HP to jest jedyny moment kiedy cast trafia i targetuje gracza. Jest jeszcze jedno pytanie czy jeśli na graczu jest riptide to powinien on być brany pod uwagę po graczu na którym jest wykonywany cast czyli 

Caster - shaman z castem Chain heal
1 Target
2 xxx
3 xxx
4 Riptide
5 Riptide

target castu i riptide mają priority ustawione. Jeśli nie ma ripride skacze randomowo po targetach z ilością mniejszą niż 100% hp

**Comment by wderw** [comment]
Nie, tylko pierwszy riptide powinien być zjadany bo i tylko jeden jest potrzebny żeby buffnąć wszystkie skoki. 

Co do targetów full hp - masz rację, na serwerach live w czasie 3.3.5 rzeczywiście targety full hp były pomijane.
w 4:10 jest cast ktory dobrze to pokazuje
https://youtu.be/zHTklnfm9vU?t=4m5s

Zamykam temat
