### ISSUE TITLE
[QUEST]Summoning the Princess

### ISSUE THREAD

**Issue by myentos** [RaphaelSunwell/Sunwell-BugTracker-SCv2#47]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**
Elita po zabiciu powinna wydropić quest item który ma 100% szansy na wypadnięcie.
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Elita nie dropi quest itemu
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Elita powinna wydropić q item
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Uzyskać [Scroll of Myzrael](http://www.wowhead.com/item=4472/scroll-of-myzrael)
2. Użyć go w odpowiednim miejscu
3. Zabić elitę

**Linki WoWHead/OpenWoW**:

1. [http://www.wowhead.com/quest=656/summoning-the-princess](http://www.wowhead.com/quest=656/summoning-the-princess)
2. [http://db.vanillagaming.org/?item=4473](http://db.vanillagaming.org/?item=4473)
3. [http://wotlk.openwow.com/item=4473](http://wotlk.openwow.com/item=4473)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by RaphaelSunwell** [comment]
Q item dropi i ma 100% szansy

**Comment by myentos** [comment]
W takim razie ciekawe czemu mi nie wydropiła? Sprawdźcie jeszcze czy nie ma problemów z podnoszeniem czegokolwiek.

**Comment by ThePuppetMaster** [comment]
Testowane przez 3 inne osoby, brak problemów.

**Comment by myentos** [comment]
Dziwne. Może po zmianie core ustąpiło.

**Comment by myentos** [comment]
[http://i.imgur.com/2kIancW.jpg](http://i.imgur.com/2kIancW.jpg)
Znalazłem ss nawet z tamtej okazji. Za drugim razem jak wpadłem, qitem wydropił.

**Comment by ThePuppetMaster** [comment]
Możliwe, że zmiana core spowodowała rozwiązanie problemu.
