### ISSUE TITLE
Resilience 

### ISSUE THREAD

**Issue by Shekell** [RaphaelSunwell/Sunwell-BugTracker-SCv2#470]
Resilience bugged 
 Resilience aint work properly i was testing it on few servers.For example warlock on s8 with 3200 spell power do 7k crit to pala with 1k resi,on sunwell lock with around 2000 spellpower do 7400 chaos bolt crit to 980 resi 

 Fix resi.Dmg we got its unreal on this sesaon its not only my opinion but all top pvpers on sunwell actually

1. Get lock / shamy cast to guy with high resi then test it on for example AT with s8 items and check dmg

X:5787.528320 Y:602.000732 Z:609.886230 (Dalaran)

**Comment by Triceps69** [comment]
I think this bug might not be about resilience, but spells and spell power. Since the start of the server, monsters did insane amount of spell damage. Playing on level 80 rhcs, warlocks and mages also do shit ton of damage with bad gear. Maybe some formulas are broken, dunno.

**Comment by xnemeyethx** [comment]
+ we have 3.3.5a skills ;)

**Comment by Vaelevian** [comment]
3.3.5a core. Just download DrDamage and check it by yourself.
