### ISSUE TITLE
[Quest] Torgos!

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#472]
**Opis**: Quest polega na zabiciu ptaka (Trachela) i podnieseniu z niego qitemu, którego gracz ma za zadanie użyć w wyznaczonym miejscu, aby przywołać kolejnego ptaka (Torgosa) oraz ponieść z niego pióro.

**Obecne działanie**: Brak pojawienia się ptaka w chwili użycia qitemu. Qitem jest niewidoczny.
https://youtu.be/CLTpqaB6Awk

**Oczekiwane działanie**: W chwili, gdy gracz użyje qitemu podniesionego z Tracheli, powinien pojawić się ptak Torgosa. Qitem powinien być również widoczny w miejscu jego użycia. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od npc. 
2. Zabić Trachela i podnieść qitem.
3. Użyć qitemu w wyznaczonym miejscu.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://wotlk.openwow.com/quest=10036
2. [Ptaki] http://wotlk.openwow.com/npc=21515
http://wotlk.openwow.com/npc=18707
3. [Qitemy] http://wotlk.openwow.com/item=30618
http://wotlk.openwow.com/item=25852

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/8gPtjX9

**Comment by Gerwazy** [comment]
Potwierdzam nie działa. Po użyciu quest item znika i nic się nie dzieje.

**Comment by RaphaelSunwell** [comment]
Fix zostanie wgrany na główny realm przy porannym update.
