### ISSUE TITLE
Questy Call to Arms

### ISSUE THREAD

**Issue by mordeusz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#473]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Aktualnie kiedy się wezmie quest na jedno z bg i wygra dany battleground to quest jest nie zaliczany. Sprawdzane na radnom queue or specific. 

**Obecne działanie**: Questy Call to arms nie sa zaliczane pomimo spelnienia kryteriow.

**Oczekiwane działanie**: Questy powinny byc zaliczone po wygraniu danego bg.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wziac quest CtA
2.  Pojsc na bg na ktore jest quest i je wygrac.
3. 

**Linki WoWHead/OpenWoW**:

Questy na niektore bg sa dostepne na rozne lvl i dla obu frakcji dlatego podam je w listach gdyz kazdy z questow ma inne id. 

1.  http://wotlk.openwow.com/?search=call+to+arms%3A+alterac+valley
2.  http://wotlk.openwow.com/?search=call+to+arms%3A+Warsong+Gulch
3.  http://wotlk.openwow.com/?search=Call+to+arms%3A+Arathi+basin
4. http://wotlk.openwow.com/?search=call+to+arms%3A+eye+of+the+storm
5. http://wotlk.openwow.com/?search=call+to+arms%3A+strand+of+the+ancients
6. http://wotlk.openwow.com/?search=call+to+arms%3A+isle+of+conquest

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

Na koniec dodam, że questy te zostały wyłączone w patchu bodajże 3.3.0, ale z racji, że mamy content 3.0.1 czyli naxx/s5 to questy te powinny byc dostepne do zrobienia.

**Comment by Vaelevian** [comment]
Poprawione. Zostanie dodane dzisiaj (tj. 30.12) po godzinie 6 rano.
