### ISSUE TITLE
[ITEM] Defender of the Timbermaw - Trinket

### ISSUE THREAD

**Issue by daykiri** [RaphaelSunwell/Sunwell-BugTracker-SCv2#474]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Trinket za reputacje nie dziala poprawnie

**Obecne działanie**: Summniety furblog ma 51 lvl zamiast 60 i bije autoatakiem zamiast castowac lighting bolty, dodatkowo gdy hp gracza zejdzie ponizej 50% guardian nas nie leczy.

**Oczekiwane działanie**: Komentarz z wowheadu
-It seems to have ~500 hp
-It is level 60, but isn't very tough even versus lower level melee
-It seems to heal you ONLY if you drop below 50% HP, and this also seems to be subjective to if it's attacking something or not. You can exert some control over this by ensuring that all targets around you are CCd when you want it to heal you. As a rogue I blind, then gouge and start a bandaid while he casts a heal. 
-I've seen it's heals range from 200-900 however I wasn't paying attention to mortal strike or critical heals.
-It spams a lightning bolt that is ~2 second cast time for 250 damage. 
-It will not attack anything unless something attacks you while it's summoned, however it will heal if there are no enemies around and you are under ~50%

For hunters considering this grind, the ancestor does heal pets. Within its 30 second duration, it'll throw 3 heals up to 800 hlth each.

kazdy heal tego summnietego tym trinketem peta powinien leczyc okolo 800hp

**Co należy zrobić, aby odtworzyć ten błąd**:
kupic trinket za reputacje i go uzyc w walce

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/item=21326/defender-of-the-timbermaw
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
skalowanie levela jest ok, dodano  skille, nie dograne jeszcze
