### ISSUE TITLE
[NPC] brak deadly gladiator's offhandów

### ISSUE THREAD

**Issue by ush92** [RaphaelSunwell/Sunwell-BugTracker-SCv2#475]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: 
npc Nargle Lashcord nie przedaje 3 offhandów deadly: endgame, reprieve, grimoire
**Oczekiwane działanie**: 
Powinien je sprzedawać za 1350 ap (wymagania: 1930 rating)
**Co należy zrobić, aby odtworzyć ten błąd**:

1.  poprzeglądać strony z itemami u wyż.wym. npc.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1.  http://wowwiki.wikia.com/wiki/Deadly_Gladiator%27s_Grimoire
2.  http://wowwiki.wikia.com/wiki/Deadly_Gladiator%27s_Endgame
3.  http://wowis.net/wishead/?item=42531

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
58,58 dalaran

**Comment by ush92** [comment]
bump

**Comment by Shon-su** [comment]
poprawione nie dograne
