### ISSUE TITLE
[Battleground] Zabity pet nie resa się wraz z postacią v3

### ISSUE THREAD

**Issue by valcy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#476]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/418 nie otrzymalem odpowiedzi wiec zglaszam ponownie

**Obecne działanie**: Spirit guide nie ressa peta.

**Oczekiwane działanie**:
 Spirit guide powinien ressac takze peta jak mowia sprawdzone zrodla:
link 1 - Spirit Guides in Battlegrounds will now summon/resurrect your current pet when the Hunter is resurrected.
link 2 - Unlike Spirit Healers found in the rest of the world, players resurrected by Spirit Guides are restored to full health and mana, as are any pets or minions.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Patch_1.5.0
2. http://wow.gamepedia.com/Battleground

**Comment by Vaelevian** [comment]
Zostanie wgrane dzisiaj o 6 rano, tj. 30.12.
