### ISSUE TITLE
[QUEST] Emergency Protocol: Section 8.2: Paragraph D

### ISSUE THREAD

**Issue by Silisar** [RaphaelSunwell/Sunwell-BugTracker-SCv2#478]
**Opis**: Quest polega na podpaleniu wraków statków za pomocą q itemu. 

**Obecne działanie**: Jednego wraku nie da się podpalić.
**Oczekiwane działanie**: Przy użyciu q itemu wszystkie trzy wraki powinny zostać spalone. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać możliwość podpalenia samolotu q itemem.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
 59,6 39.1

**Comment by Shon-su** [comment]
na moje oko wszystko powinno byc ok, ale nie mam jak sprawdzic co na serwerze lezy ;p Spellfocus do spella w kazdym razie dobrze lezy na czystym sc

**Comment by ThePuppetMaster** [comment]
Brak linków.

**Comment by Larousene** [comment]
Koordy do poszczególnych wraków:
Eastern: 63,36
Southern: 61,39
Northwestern: 61,30
link q z wowheada: http://www.wowhead.com/quest=11796/emergency-protocol-section-8-2-paragraph-d
Q item nie działa jedynie w przypadku wraku na Southern
