### ISSUE TITLE
[ITEM] Respawn time of Recipe: Super Mana Potion

### ISSUE THREAD

**Issue by Janeczkov** [RaphaelSunwell/Sunwell-BugTracker-SCv2#479]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Recipe: Super Mana Potion respi sie u npc Daga Ramba prawdopodobnie (wedlug informacji od GMa) co jeden dzien. Sprawdzalem to dnia z 28.12 na 29.12 miedzy godzinami 22-02. Recepta sie nie zrespila, kolo poludnia rowniez sprawdzalem i jej nie bylo.

**Oczekiwane działanie**: Recepta powinna respic sie u npc co 30 minut wedlug komentarza ze strony podanej nizej (wowhead) od gracza Lettermage wedlug patcha 3.3.5

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Nalezy jedynie wejsc w interakcje z npc Daga Ramba tzn kliknac na niego prawym ^^ Recepty prawdopodobnie u niego nie bedzie
2. 
3. 

**Linki WoWHead/OpenWoW**:

1.  [http://www.wowhead.com/item=22907/recipe-super-mana-potion#sold-by](url)
2.  [http://wotlk.openwow.com/item=22907#sold-by](url)
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
![gps bugtracker wow](https://cloud.githubusercontent.com/assets/24829262/21548468/c9a9c13c-cdec-11e6-908c-04511f7b3bc4.png)

**Comment by Shon-su** [comment]
UPDATE `npc_vendor` SET `incrtime` = 1800 WHERE `item` = 22907;

**Comment by Mithras2801** [comment]
Zatwierdzam zgłoszenie za bug.
