### ISSUE TITLE
Rogue drobny bug z gouge

### ISSUE THREAD

**Issue by wedrowiecc90** [RaphaelSunwell/Sunwell-BugTracker-SCv2#48]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Bug

**Obecne działanie**: Podczas wrzucania gouge na moba często wystepuję drobny bug otrzymania 1 auto ataku od moba nawet mimo że jest się pare y od niego.

**Oczekiwane działanie**: Gouge zatrzymuje moba/gracza w miejscu bez otrzymania dmg od wroga.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Danieloses** [comment]
najprawdopodobniej może to być visual bug, polecam sprawdzić

**Comment by ThePuppetMaster** [comment]
2 rogali testowało, nie udało się odtworzyć. Zamykam.
