### ISSUE TITLE
[Quest] The Earthen Oath

### ISSUE THREAD

**Issue by druidert** [RaphaelSunwell/Sunwell-BugTracker-SCv2#480]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po użyciu q itemu (Horn of the Peaks) pojawiają się NPC pomagające zabić określone moby.

**Obecne działanie**: Zabijając moby w obecności friendly NPC q zalicza podwójnie. Zabijając moby solo q credit naliczany jest poprawnie

**Oczekiwane działanie**: Q credit powinien być przyznawany pojedynczo, po zabiciu odpowiedniego moba.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć wspomnianego q itemu w odpowiednim miejscu.
2. Zabić jeden z dwóch rodzajów mobów w obecności NPC z q itemu.
3. 

**Linki WoWHead/OpenWoW**:

1. quest - http://www.wowhead.com/quest=13005/the-earthen-oath
2. quest item - http://www.wowhead.com/item=42840/horn-of-the-peaks
3. moby - http://www.wowhead.com/npc=29984/iron-sentinel  http://www.wowhead.com/npc=29978/iron-dwarf-assailant#comments

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
52.2; 51.6 (kordy z wh)

**Comment by Verthe** [comment]
quest dziala poprawnie , bilem z pomoca q itemu i zaliczalo poprawnie

**Comment by Verthe** [comment]
jezeli ten mob rozpocznie walke to zwyczajnie nie zaliczy nam moba do q http://www.wowhead.com/npc=29980/earthen-elite
