### ISSUE TITLE
[ITEM] Bag of Fishing Treasures - epickie kamienie

### ISSUE THREAD

**Issue by VaderLord** [RaphaelSunwell/Sunwell-BugTracker-SCv2#481]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis - **: Bag of Fishing Treasures

**Obecne działanie**: Nagroda za ukończenie daily questa z fishingu, jest szansa na drop kamieni epickich.
Link do torby i możliwego lootu - http://www.wowhead.com/item=46007/bag-of-fishing-treasures#contains

**Oczekiwane działanie**:  kamienie te powinny pojawić się w loocie wraz z patchem 3.1.0.9658

**Co należy zrobić, aby odtworzyć ten błąd**: 
1. Miec fishing umożliwiający akceptowac daily quest
2. udać się do Dalaran - NPC **Marcia Chase**
3. akceptować daily quest 
4. po ukończeniu dostajemy nagrodę - Bag of Fishing Treasures

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=46007/bag-of-fishing-treasures#contains

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Daily fishing od NPC'a w Dalaran

**Comment by Shon-su** [comment]
W zaleznosci co chcecie sobie zrobic, bo i tak bedziecie to musieli przywrocic kiedys:
UPDATE `item_loot_template` SET `ChanceOrQuestChance` = 0 WHERE `entry` = 46007 AND `mincountOrRef` = 10019;

lub

DELETE FROM `item_loot_template` WHERE `entry` = 46007 AND `mincountOrRef` = 10019;

**Comment by Vaelevian** [comment]
Zostanie dodane dzisiaj (tj. 30.12) o 6 rano.
