### ISSUE TITLE
[MOUNT]Riding Turtle

### ISSUE THREAD

**Issue by Vansir** [RaphaelSunwell/Sunwell-BugTracker-SCv2#483]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Mount Riding Turtle (dostępny za donate pointy) porusza się w wodzie z taką samą prędkością z jaką porusza się gracz nie używający tego mounta.

**Oczekiwane działanie**: Mount ten powinien zwiększać szybkość gracza podczas pływania o 100%.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść do wody
2. Użyć mounta Riding Turtle
3. Porównać prędkość z i bez mounta Riding Turtle

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=23720/riding-turtle#comments
2. http://wotlk.openwow.com/item=23720/
3. http://www.wow-one.com/forum/topic/90933-riding-turtle/

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by OrgiVed** [comment]
A to przypadkiem nie Sea Turtle zwiększa szybkość w wodzie a ten nie robi nic? W opisie nie jest napisane, ze zwiększa szybkość w wodzie.

**Comment by Vansir** [comment]
Jestem w 100% przekonany że oba te żółwie zwiększają prędkość pływania i na starym sunwellu ten Riding Turtle ze sklepu był opcją dla ludzi którzy mieli dosyć prób zdobycia sea turtle.

**Comment by xsitdev** [comment]
The Riding Turtle **is one of only a few special mounts that increase your speed in water to that of a normal mount on land**. It can be used in any body of water. Its speed is not affected by effects that increase or decrease mount speed. Wgrane zostanie dzisiaj ok. 7 rano.
