### ISSUE TITLE
[INSTANCJA]Hellfire Ramparts

### ISSUE THREAD

**Issue by Vansir** [RaphaelSunwell/Sunwell-BugTracker-SCv2#484]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Podczas walczenia w instancji Hellfire Ramparts moby o nazwie Bonechewer Destroyer odrzucają gracza na dużą odległość, gubiąc aggro i resetując swoje punkty życia. Sprawdzone postacią na 80 lvlu, nie wiem jak działa na niższych levelach. Jest to kłopotliwe dlatego że po złapaniu kilku mobów i otrzymaniu tego odrzucenia, wszystkie moby gubią aggro i trzeba je łapać od nowa.

**Oczekiwane działanie**: Moby w instancji nie powinny gubić aggro wcale. Dodatkowo żaden mob nie powinien odrzucać gracza w taki sposób aby stracić aggro. Tymczasowym rozwiązaniem problemu może być pozbawienie Bonechewer Destroyerów możliwości odrzucania. Trwałe rozwiązania będzie wymagać zmiany sposobu w jaki odrzucanie się odbywa lub zmodyfikowanie aggro mobów tak aby go nie gubiły tam gdzie nie powinny.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść na Hellfire Ramparts normal postacią na 80 lvlu
2. Podejść do moba Bonechewer Destroyer (jest ich tam sporo)
3. Złapać aggro i poczekać aż mob odrzuci nas i straci aggro. Czasami odrzuca słabiej więc trzeba zaczekać aż odrzuci znowu.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/hellfire-ramparts#npcs
2. http://www.wowhead.com/npc=17271/bonechewer-destroyer#abilities
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Heartbraker** [comment]
Problemem nie jest skill Bonechewer Destroyera czy cokolwiek związanego z Hellfire Ramparts.
Problemem jest "fix" do https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/219 - moby tracą aggro gdy gracz znajdzie się w pewnej odległości albo raczej wysokości "z" od moba, co nie powinno mieć miejsca.
Niestety wgrywanie takich hacków ma to do siebie, że mogą rozwiązać jakiś problem, ale zwykle rodzą kilka innych problemów, jak w tym przypadku.
Proponuję zająć się problemem u źródła, bo robienie tymczasowych rozwiązań do tymczasowych rozwiązań nie prowadzi do niczego dobrego :)

**Comment by xsitdev** [comment]
Powyższy komentarz niestety mija się z prawdą, gdyż zmiana o której mowa tj. #219 całkowicie nie afektuje / dotyczy w żadnym wypadku instancji. 

Problem był w generatorze ruchu, który został poprawiony przy obróbce Naxxramas, problem już nie występuje.
