### ISSUE TITLE
[SKILL]Commanding Shout, Battle Shout

### ISSUE THREAD

**Issue by Vansir** [RaphaelSunwell/Sunwell-BugTracker-SCv2#485]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Obecnie informacja zawarta w buffie z Commanding Shout oraz Battle Shout dawanego przez warriora, nie uwzględnia talentu Commanding Presence. Przez to wyświetla zawsze bazową wartość nawet kiedy w rzeczywistości daje większy bonus, ponieważ gracz dający buffy zainwestował punkty talentów w Commanding Presence które zwiększa otrzymywane bonusy o od 5-25%. Jest to mylące dla graczy i utrudnia rozdawanie buffów na dungeonach/rajdach. Ponadto sprawia wrażenie że talent Commanding Presence nie działa.

**Oczekiwane działanie**: Buff powinien pokazywać rzeczywistą ilość bonusowych AP/Health.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść na Warriora i dodać punkty w talent commanding presence
2. Użyć Commanding Shout lub Battle Shout
3. Porównać bonus wyświetlany przez buff w górnym prawym rogu obok minimapy, z wartością deklarowaną przez umiejętność oraz wartością rzeczywiście otrzymaną

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/?search=commanding+presence
2. http://wotlk.openwow.com/spell=6673
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by valcy** [comment]
To nie jest bug. Na globie dzialalo to w ten sam sposob.
