### ISSUE TITLE
[SPELL][Warlock] Immolation aura trwa za długo

### ISSUE THREAD

**Issue by Kondonman** [RaphaelSunwell/Sunwell-BugTracker-SCv2#486]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 

**Obecne działanie**: Gdy mamy Glyph of Metamorphosis nasza Immolation Aura trwa o 6s za długo.

**Oczekiwane działanie**: Glyph of Metamorphosis nie powinien działać na długość trwania Immolation aury. 

**Co należy zrobić, aby odtworzyć ten błąd**: 

1.  Aktywować Glyph of Metamorphosis
2.  Użyć Immolation aury 
3.  Zobaczyć czas trwania debuffa Immolation aury

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=45780
2. http://wotlk.openwow.com/spell=50589
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Nie zgodze się z tym trwa 13 s cały czas niezależnie czy mamy glyph czy nie.

**Comment by Kondonman** [comment]
no i czemu zamknięte skoro bug dalej jest ?
