### ISSUE TITLE
[Dungeon] Blackrock Depths (Royal Chamber Entrance)

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker-SCv2#489]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W sali, w ktorej znajduje sie Magmus sa rowniez posagi, ktore zieja ogniem. Ogien ten nie zadaje obrazen.
"Magmus – Ambassador Flamelash charged the molten giant Magmus with guarding Emperor Dagran Thaurissan's throne room, but not even this act put the Dark Iron ruler's concerns to rest. Ever fearful of assassins, the emperor also granted **Magmus control over a series of fire-breathing statues outside his royal chambers.**"

**Obecne działanie**: Posagi nie zadaja obrazen od ognia.
http://screenshooter.net/103026569/flbkryx

**Oczekiwane działanie**: Posagi wraz z podmuchem ognia powinny zadac nam obrazenia.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejsc w sale, w ktorej przebywa Magmus.
2. Ustawic sie na wylocie jakiejs statuy i poczekac na wyziew ognia.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/blackrock-depths
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
-

**Comment by Shon-su** [comment]
#250

**Comment by Shon-su** [comment]
hmmm poprawiałem to, zapomniałem zamknąć
