### ISSUE TITLE
Execute Bug - Major Warrior dmg decreasing bug

### ISSUE THREAD

**Issue by Vertazwar** [RaphaelSunwell/Sunwell-BugTracker-SCv2#49]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

Hello, when I use execute there is a high chance that the spell wont do any damage or even show in combat log, it will just play the sound, use gcd, spend rage, but it wont proces the spell in any way. Its not miss/dodge/parry, the spell wont even show up in combat log and its just wasted rage and gcd, the bug happens very often, I can record it on video if needed, the same bug was on ToD. 

Please fix this asap, execute is warriors highest damaging spell and when its bugged whole dps mechanics of this class are RiP.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Makakahehe** [comment]
http://forum.sunwell.pl/viewtopic.php?f=83&p=19257#p19257

**Comment by ThePuppetMaster** [comment]
Please provide some evidence, that will help us work on this problem more efficient. Closing for now.
