### ISSUE TITLE
[Item] totemy Hateful za honor nie dzialaja jako totemy Earth, Fire, Water i Air

### ISSUE THREAD

**Issue by Ranforius** [RaphaelSunwell/Sunwell-BugTracker-SCv2#491]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:po zakupie przedmiotu [Hateful Gladiator's Totem of Survival] okazuje sie iz on ani zaden z totemow za honor nie dzialaja jako totemy zywiolow co przeklada sie na brak mozliwosci uzywania totemow ktore sa niezmiernie istotne

**Obecne działanie**: totemy za honor Hatefull nie sa wykrywane jako totemy zywiolow i nie mozna przez to korzystac z wszystkich umiejetnosci totemicznych 

**Oczekiwane działanie**: wszystkie totemy za honor powinny byc uwzgledniane jako totemy earht, fire, water i air bez tego nie mozna uzywac polowy skilli klasy shamana

**Co należy zrobić, aby odtworzyć ten błąd**:

1. zakupic jakikolwiek totem Hateful
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
UPDATE `item_template` SET  `AllowableClass` = 32767, `flags` = 36864, `TotemCategory` = 21 WHERE `entry` IN (42596, 42601, 42606);
