### ISSUE TITLE
[TALENT][MAGE][FIRE] Master of Elements

### ISSUE THREAD

**Issue by kacak0** [RaphaelSunwell/Sunwell-BugTracker-SCv2#492]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Czar powinien przywracać część bazowej many potrzebnej do rzucenia zaklęcia w momencie trafienia krytycznego.

**Obecne działanie**: Kiedy dostaje efekt Clearcasting który pozwala mi rzucić czar bez kosztu many czar w ogóle nie przywraca many. Pozwala mi to przypuszczać że talent przywraca procent many aktualnie zużytej do rzucenia czaru ale nie mam możliwości sprawdzenia tego dokładnie. Talent ponadto w ogóle nie przywraca many podczas "channeling". Ponadto czar w ogóle nie przywraca many w przypadku krytyka czarami ze szkoły Arcane

**Oczekiwane działanie**: Mana powinna zostać zwracana na podstawie kosztu czaru przed jakąkolwiek zmianą many potrzebną do rzucenia czaru. W przypadku "channeling" (blizzard, arcane missles) talent powinien dawać mane przy każdym krytyku podzieloną przez ilość ticków które dany czar wykonuje.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. trafić krytycznie czarem posiadając talent Master of Elements i coś co redukuje koszt czarów np. talent Arcane Concentration.
2.
3.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=29077
2. http://wowwiki.wikia.com/wiki/Master_of_Elements
3.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

nie dotyczy.

**Comment by Vaelevian** [comment]
Talent działa prawidłowo. Zwraca 30% many po każdym krytycznym uderzeniu.

**Comment by DinozaurWKamizelce** [comment]
Niestety ale talent nie działa prawidłowo i nie zwraca many po każdym krytycznym uderzeniu. Porobiłem trochę testów i oto moje wyniki.

Talent **ZWRACA** manę po krytykach z następujących spelli:

-Scorch
-Pyroblast
-Fire blast
-Fireboll
-Frostfire bolt
-Flamestrike
-Cone of Cold
-Frost nova
-Ice lance
-Frostbolt

Talent **NIE ZWRACA** many z następujących spelli:

-Living Bomb - http://wotlk.openwow.com/spell=44461
-Dragon's Breath - http://wotlk.openwow.com/spell=31661
-Blast Wave - http://wotlk.openwow.com/spell=11113
-Blizzard - http://wotlk.openwow.com/spell=10
-Arcane Missiles - http://wotlk.openwow.com/spell=7268
-Arcane Blast - http://wotlk.openwow.com/spell=30451
-Arcane Barrage - http://wotlk.openwow.com/spell=44425
-Arcane Explosion - http://wotlk.openwow.com/spell=1449


Nie sprawdziłem chyba tylko czaru Deep Freeze z drzewka frost bo na kukłach nie zadaje obrażeń (jak ktoś może niech sprawdzi)

**Co jest nie tak:**

1) Talent w ogóle nie zwraca many z wypisanych wyżej spelli

2) Talent nie zwraca 10/20/30% bazowego kosztu czaru tylko odpowiedni procent aktualnego kosztu czaru w momencie wystąpienia krytycznego trafienia (wliczają się w to zarówno talenty obniżające koszt czarów jak i efekty takie jak clearcasting lub Brain Freeze)

Dokładniejszy opis w przypadku clearcastingu:

Jeżeli mamy clearcasting i uderzymy z czarów, które uderzają natychmiastowo: Scorch, Fire Blast, Frost Nova, Cone of Cold, Flamestrike (czary, które zwracały manę bez clearcastingu) to nie zwróci nam many bo w momencie uderzenia mamy clearcasting (koszt many wynosi 0)

-Pojawia się clearcasting
-krytyczne trafienie
-Znika clearcasting

W przypadku fireballa itp zwróci nam manę bo clearcasting zniknie zanim czar doleci. (jestem przekonany że tylko dlatego zwraca manę w przypadku Brain Freeze )

W celu sprawdzenia można uderzyć Flamestrike posiadając clearcasting (tak by uderzył przed zniknięciem buffa) a następnie
Wywołać clearcasting
zacząć castować flamestrike
samemu wyłączyć buffa
Uderzyć krytycznie

Talent zwróci manę ale nie będzie to 30% base mana, ani też 30% mana wziętego do scastowania tylko 30% mana potrzebnego do scastowania branego w momencie uderzenia.

Linki:

Talent:
Master of Elements - http://wotlk.openwow.com/spell=29074

Czary, z których nie zwraca many:
Living Bomb - http://wotlk.openwow.com/spell=44461
Dragon's Breath - http://wotlk.openwow.com/spell=31661
Blast Wave - http://wotlk.openwow.com/spell=11113
Blizzard - http://wotlk.openwow.com/spell=10
Arcane Missiles - http://wotlk.openwow.com/spell=7268
Arcane Blast - http://wotlk.openwow.com/spell=30451
Arcane Barrage - http://wotlk.openwow.com/spell=44425
Arcane Explosion - http://wotlk.openwow.com/spell=1449

Linków do talentów i efektów nie będę dawał bo powinno brać % base mana niezależnie od wszystkiego (talenty, itemki, zewnętrzne buffy/debuffy i nie sposób tego wyliczyć)

O ile punkt 2 wydaje się dość dobrze rozpracowany o tyle nie mam pomysłu czym może być spowodowany punkt 1.
