### ISSUE TITLE
[SPELL] [PALADIN] Crusader aura + Pursuit of justice

### ISSUE THREAD

**Issue by sincrest** [RaphaelSunwell/Sunwell-BugTracker-SCv2#493]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie mam możliwości sprawdzenia tego gdyż nie posiadam Paladyna, a słyszałem od kumpli o takowym działaniu. Wątpię też by jakikolwiek paladyn podzielił się screenem z dowodem, gdyż byłoby na jego niekorzyść naprawa buga.

**Obecne działanie**: Aura stackuje się z talentem i Paladyni osiągają prędkość około  380%. To samo dotyczy słabszych mountów flying i grounding

**Oczekiwane działanie**: Crusader Aura and Pursuit of Justice does not stack with any other movement-enhancing effect.
"This does not stack with other movement speed increasing effects." x2

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=32223
2. http://wotlk.openwow.com/spell=26023

**Comment by Triceps69** [comment]
Gdzie jakiś dowód? bo według mnie to nieprawda.

**Comment by valcy** [comment]
http://www.wowhead.com/forums&topic=3714/pursuit-of-justice-crusader-aura-stacks
http://wowwiki.wikia.com/wiki/Crusader_Aura
The Crusader Aura's speed modifier is non-stacking

**Comment by Vaelevian** [comment]
Problem leży w stackowaniu oraz w samej crusader aurze, która dawała o wiele większe wartości procentowe, niż powinna. Postaramy się poprawić najszybciej, jak to możliwe.

**Comment by Heartbraker** [comment]
Że niby co?:D Kiedy crusader aura sie zepsuła i dawała większe wartości niż powinna? Po rozpoczęciu sezonu pvp (i "zmianie patcha")? Bo przed tym działało wszystko dobrze, stackowanie również (w sensie talent nie stackował się z crus aurą). 
Nie wiem kto to testował i w jaki sposób, ale chętnie bym zobaczył przebieg i wyniki testów, bo moim zdaniem ktoś się pomylił przy tych testach (chyba, że tak jak pisałem były jakieś zmiany z crus aurą przy starcie sezonu pvp)

**Comment by Heartbraker** [comment]
Dokładnie sprawdziłem każdą możliwą opcję i obecnie, po zepsuciu crusader aury wygląda to tak : 
1.Szybkość poruszania się bez mounta i bez Pursuit of Justice - 100%
2. Szybkość poruszania się bez mounta i z Pursuit of Justice - 115%
3. Szybkość poruszania się z mountem 100% (Journeyman riding) bez crusader aury i bez Pursuit of Justice - 200%
4. Szybkość poruszania się z mountem 100% (Journeyman riding) bez crusader aury i z Pursuit of Justice - 230%
5. Szybkość poruszania się z mountem 100% (Journeyman riding) z crusader aurą i z Pursuit of Justice - 230%
6. Szybkość poruszania się z mountem 100% (Journeyman riding) z crusader aurą i bez Pursuit of Justice - 220%

A tak powinno być : 
1. 100% 
2. 115% 
3. 200% 
4. 230% 
5. 240% 
6. 240% 

Więc Pursuit of Justice na chwilę obecną jeszcze działa dobrze, ale jak chcecie w godzinach wieczornych się tym zając to chyba planujecie to zepsuć?;P
Wynika też z tego, że Crusader aura po zepsuciu dodaje 10% mounted speed, a nie 20% tak jak powinna.
Mounted speed =/= mount speed, to że mount daje 100% nie znaczy, że crus aura ma dodać 20%, bo mounted speed na mouncie 100% wynosi 200%, co z crus aura ma dać 240% czyli tyle ile wcześniej dawało.

Istnieje wiele sposobów, żeby przekonać się, że ma być tak jak napisałem.
Najprostszym z nich jest wejście na jakąkolwiek stronę typu wowwiki.....
http://wowwiki.wikia.com/wiki/Crusader_Aura
