### ISSUE TITLE
[TALENT][ROGUE] Vigor

### ISSUE THREAD

**Issue by Korzonus** [RaphaelSunwell/Sunwell-BugTracker-SCv2#494]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Talent Vigor + glyph na niego nie daje 130, ale 120 energii.

**Obecne działanie**: Talent Vigor u rogala w drzewku assa daje 20 energii, w połączeniu z glyphem na Vigor mój rogal ma dalej 120 energii.
**Oczekiwane działanie**: Talent Vigor daje 20 energii, w połączeniu z glyphem na Vigor, rogal otrzymuje dodatkowo 10 energii, co w daje razem 30 dodatkowej energii (130 energii).

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Kupiłem dual speca i zrobiłem drzewko pvp sub, gdzie w assa dałem talent vigor.
2. Na ah kupiłem glyph na Vigor.
3. Zmiana talentów i kilkukrotny relog nie pomogły.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=42971
2. Trudno jest aktualnie znaleźć link do samego talentu.

**Comment by valcy** [comment]
http://wowwiki.wikia.com/wiki/Vigor
Vigor is an talent in the Assassination tree. It increases your maximum Energy by 10. Combined with the glyph this increases rogue energy total to 120.
Nie wiem od kiedy sam talent zapewnia 20 energii.

**Comment by Korzonus** [comment]
Dobra, w takim razie dlaczego duża część rogali w ally biega na 130 energii ?

**Comment by valcy** [comment]
Nightslayer Armor, Gladiator's Vestments, Merciless Gladiator's Vestments, Vengeful Gladiator's Vestments, and Brutal Gladiator's Vestments each have a set bonus that increases their wearer's maximum Energy by 10, which can be stacked with Vigor and its glyph. An extra 10 or 20 energy is a serious advantage in any fight. If you know how to use it, you can be killer in PvP.
http://wowwiki.wikia.com/wiki/Brutal_Gladiator%27s_Vestments
