### ISSUE TITLE
[Quest] Scouring the Desert

### ISSUE THREAD

**Issue by xnemeyethx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#495]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

W całej lokacji Silithus można napotkać object Silithyst Geyser. Mamy go kliknąć, zostajemy wtedy oflagowani PvP i dostajemy buffa, który spowalnia nasą prędkość ruchu. Z tym buffem mamy udać się do obozu naszej frakcji gdzie zostanie on z nas zdjęty a zadanie zaliczone.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

Po kliknięciu obiekt po prostu znika. Nie dostajemy debuffa ani nie zostajemy spowolnieni.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

Klikamy objekt, dostajemy debuffa oraz spowolnienie. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Udać się na Silithus
2. Zabrać zadanie Scouring the Desert
3. Spróbować je wykonać.

**Linki WoWHead/OpenWoW**:

1. http://db.vanillagaming.org/?quest=9422#wh-comments
2. http://db.vanillagaming.org/?object=181598
3. http://db.vanillagaming.org/?spell=29519

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Poprawione. Zostanie dodane około 6 rano.
