### ISSUE TITLE
[spell][warrior] charge

### ISSUE THREAD

**Issue by Makakahehe** [RaphaelSunwell/Sunwell-BugTracker-SCv2#5]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Charge czasem po podrzuceniu mobka zostawia go w powietrzu

**Obecne działanie**: Aktualnie charge podbija mobka w górę żeby nie wpadł w tekstury.  Niestety czasami po podbiciu mobek zostaje w tej górze.
**Oczekiwane działanie**: Powinien zleźć na ziemię. Idealnie nie powinno go w ogóle podbijać.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pograć warriorem i pochargować trochę.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=100
2. http://imgur.com/a/9ihyL
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
nie da rady komenda nie działa

**Comment by xsitdev** [comment]
Zabezpieczenie przed wpadnięciem w tekstury, musi tak zostać.
