### ISSUE TITLE
brak npc  Bragor Bloodfist <Hand of the Warchief>

### ISSUE THREAD

**Issue by Jarek250** [RaphaelSunwell/Sunwell-BugTracker-SCv2#50]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak npc Bragor Bloodfist <Hand of the Warchief> przez co nie mozna wziasc questa

**Obecne działanie**: Brak npc Bragor Bloodfist <Hand of the Warchief> w royal quarter undercity

**Oczekiwane działanie**: dodanie npc

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=36273/bragor-bloodfist
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by adraeth** [comment]
Duplikat #12, zobacz #27.
