### ISSUE TITLE
[Druid][Glyph] Glyph of rejuvenation nie działa

### ISSUE THREAD

**Issue by DinozaurWKamizelce** [RaphaelSunwell/Sunwell-BugTracker-SCv2#503]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Glyph zwyczajnie nie działa

**Obecne działanie**: Z glyphem czy bez rejuvenation leczy tak samo

**Oczekiwane działanie**: Jeśli posiadamy Glyph of rejuvenation cel, który ma mniej niż 50% hp powinien być leczony o 50% więcej przez spell rejuvenation.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Włożyć glyph of rejuvenation
2. Rzucić rejuvenation na cel który ma mniej niż 50% hp oraz na cel, który ma więcej niż 50% hp 
3. Porównać efekty lecznicze.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=40913
2. http://wotlk.openwow.com/spell=26982
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Glyph działa poprawnie. Jeśli target jest poniżej 50% hp, glyph leczy osobnym tickiem za połowę wartości normalnego ticka.

**Comment by DinozaurWKamizelce** [comment]
Działa, działa, bo naprawili po zgłoszeniu :)
