### ISSUE TITLE
[HUNTER][STEADY SHOT][HIERLOOM BOW]

### ISSUE THREAD

**Issue by Thaais** [RaphaelSunwell/Sunwell-BugTracker-SCv2#504]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Hunter, skill - Steady Shot, formula zle liczy dmg, hierloom bow

**Obecne działanie**: DAMAGE nie skaluje się poprawnie, według obserwacji WEAPON DAMAGE jest nie dodawany do formuły tak jak ammo dmg (chyba). 

**Oczekiwane działanie**: Podobniesz jest to bug z ToDa, ze hierloom weapon lvl nie skaluje sie z damagem. Czyli, formuła z opisu powinna pobierać WEAPON DAMAGE z aktualnego HIERLOOM WEAPON LVL. !!! Nie testowalem czy ten problem wystepuje kiedy target ma status DAZED, muscie to sprawdzic.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Hunter class ,mob, target, hierloom bow
2. Obserwowac damage ze skilla Steady Shot i porównać do formuły skilla. - znaczace rozbierzności

**Linki WoWHead/OpenWoW**:

1.  http://wotlk.openwow.com/spell=56641
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Globalne

**Comment by Vaelevian** [comment]
Poprawione. Zostanie dodane dzisiaj około 6 rano.
