### ISSUE TITLE
[QUEST] Song of Wind and Water

### ISSUE THREAD

**Issue by Vansir** [RaphaelSunwell/Sunwell-BugTracker-SCv2#507]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Po użyciu quest itema, Haiphoon którym kierujemy zadaje ponad 10x mniej obrażeń niż powinien przez co quest jest awykonalny (ok 100-200obrazen)

**Oczekiwane działanie**: Pojedynczy atak pierwszym skillem powinien zadawać ok 2-3k obrażeń.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa, polecieć we wskazane miejsce i użyć quest itemu
2. Zaatakować wskazane moby
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12726/song-of-wind-and-water
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Verthe** [comment]
Do poprawy

**Comment by Lebiedz** [comment]
Quest w dalszym ciągu działa jak w opisie błędu.
