### ISSUE TITLE
[NPC] 26878 - Rodney Wells <Gryphon Master> (poważny bug)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#509]
**Obecne działanie**: NPC nie daje nam questa po stronie Alliance [To Stars' Rest!](http://www.wowhead.com/quest=12440/to-stars-rest).

**Oczekiwane działanie**: NPC po wykonaniu poprzedniego Q czyli [A Disturbance In The West](http://www.wowhead.com/quest=12439/a-disturbance-in-the-west) powinien oferować nam quest: 
- To Stars' Rest! - http://www.wowhead.com/quest=12440/to-stars-rest

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ukończyć pierwszy quest
2. Sprawdzić kolejne

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=26878/rodney-wells
2. http://www.wowhead.com/quest=12440/to-stars-rest - brakujacy Q

**Comment by Mithras2801** [comment]
Do sprawdzenia jednak czy już działa. Poprzednie core tego nie oferowało, a na SC już jest.

**Comment by hunterka** [comment]
Ten quest jest już dostępny, dzisiaj go zrobiłam.
