### ISSUE TITLE
[QUEST] Leave No One Behind

### ISSUE THREAD

**Issue by garlyn** [RaphaelSunwell/Sunwell-BugTracker-SCv2#510]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 

**Obecne działanie**: Otrzymany quest item działa na NPC'y (Crusader Jonathan, Crusader Josephine, Crusader Lamoof) lecz eskortowane są losowo zaliczane u quest givera (raz zalicza a raz nie), z tego też powodu występują spore problemy z ukończeniem questa.

**Oczekiwane działanie**: Każdy doeskortowany NPC powinien być zaliczany u quest givera.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest od quest givera.
2. Podlecieć do któregoś z NPC'ów którzy mają być eskortowani
3. Użyć quest item
4. Eskortować NPC'a
5. Powtórzyć kroki 2-4 do pozostałych NPC'ów

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12512/leave-no-one-behind
2. http://wowwiki.wikia.com/wiki/Quest:Leave_No_One_Behind
3. https://www.youtube.com/watch?v=lLOpUvAxjw0

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
58,72 - quest giver
53,75 - crusader lamoof
50,69 - crusader jonathan
48,74 - crusader josephine

**Comment by mordeusz** [comment]
Jak robilem tego questa to nie zaliczalo mi tylko w wypadku jak bylem na mouncie.

**Comment by tokacz** [comment]
bez mounta zaliczało, na mouncie tez powinno

**Comment by Vaelevian** [comment]
Testowałem kilka razy. Za każdym razem quest działa poprawnie. Na 10 testów nie trafiłem ani jednego npc, którego eskorta byłaby zakończona niepowodzeniem.
