### ISSUE TITLE
[Quest] We have the power - nie działa, jeden z mobów nie dropi quest itemu

### ISSUE THREAD

**Issue by Argonnath** [RaphaelSunwell/Sunwell-BugTracker-SCv2#511]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**[QUEST] We have the power**:

**Obecne działanie**: Z moba  Rune-Smith Durar powinien dropić przedmiot Durar's Power Cell. Niestety nie dropi.

**Oczekiwane działanie**: Zabijasz Rune-Smith Durar. Lootujesz Durar's Power Cell.
**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Zabić Rune-Smith Durar
2.  Zobaczyć, że nie dropi quest itemu
3. 

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/quest=12197/we-have-the-power
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Cevillus** [comment]
Robiłem wczoraj tego questa. Za pierwszym razem item nie dropnął, ale poczekałem na respa moba i tym razem już poleciał. Wg wowheada item http://www.wowhead.com/item=36857/durars-power-cell ma 47% szansy na drop a wg. bazy twinstara ma 67% https://wotlk-twinhead.twinstar.cz/?item=36857 . Nigdzie nie jest powiedziane, że musi dropnąć za pierwszym razem.

**Comment by Vaelevian** [comment]
Quest item wypada średnio co 2-3 zabicia NPC Rune-Smith Durar.
