### ISSUE TITLE
Evasion zle działa

### ISSUE THREAD

**Issue by kevery123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#512]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Evasion zle działa ponieważ używając evasiona powinnismy miec 25% szansy ze spell przeciwnika w nas nie trafi a ma 100% szansy zeby nas trafic

**Obecne działanie**: po użyciu evasiona spelle przeciwnika maja 100% szansy ze trafia w nas, testowałem

**Oczekiwane działanie**: Powinno być 25% szansy ze zmissuja

**Co należy zrobić, aby odtworzyć ten błąd**:
np.
1. dać duel magowi
2.użyć evasiona
3. niech castuje np. frosbolta rank 1 caly czas na evasionie

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by xnemeyethx** [comment]
To jest na ranged attacks a nie spells...

**Comment by Heartbraker** [comment]
"używając evasiona powinnismy miec 25% szansy ze spell przeciwnika w nas nie trafi" - jest to nieprawdą.
Tak jak Nemeyeth napisał, działa to na ranged ataki jak np. strzelanie z luku, rzut thrownem, a nie czary jak np. frostbolt o którym piszesz.

**Comment by kevery123** [comment]
Nie mowie o ranged atakach huntera, bo wiem ze na to dziala tylko spellach, moim zdaniem powinno dzialac na spelle

**Comment by xnemeyethx** [comment]
http://wowwiki.wikia.com/wiki/Evasion

Notes:

Doesn't work against spells. 
Cooldown time is moderately long.
