### ISSUE TITLE
[NPC/Quest] Apprentice Nelphi, Dark Ranger Vorel - Inside the Frozen Citadel

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#513]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Ww. npc chodzą po dalaranie i oferują questa Inside the Frozen Citadel, który jest dostępny od patcha 3.3.0

**Oczekiwane działanie**: NPC powinny dostać dodane wraz z otworzeniem contentu ICC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do Dalaranu jako członek alliance lub hordy.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Dark_Ranger_Vorel
2. http://wowwiki.wikia.com/wiki/Quest:Inside_the_Frozen_Citadel_(Horde)
3. http://wowwiki.wikia.com/wiki/Apprentice_Nelphi
4. http://wowwiki.wikia.com/wiki/Quest:Inside_the_Frozen_Citadel_(Alliance)

**Comment by Mithras2801** [comment]
Potwierdzam. NPC są openerami frozen halls przed ICC

**Comment by ThePuppetMaster** [comment]
Skoro w/w instancje są niedostępne, to i tak nie wiele to zmienia. Mało istotne.
