### ISSUE TITLE
[Quest] The Great Fras Siabi

### ISSUE THREAD

**Issue by xnemeyethx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#514]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

Po wejściu do Stratholme mamy zabić moba Fras Siabi.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

Nie da się kliknąć na skrzynię z tabaką co uniemożliwia przyzwania npc.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

Powinno dać się kliknąć skrzynię co umożliwi przywanie Frasa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Zabrać Quest z Light's Hope Chapel
2.  Udać się do Stratholme.
3. Spróbować przyzwać Frasa.

**Linki WoWHead/OpenWoW**:

1. http://db.vanillagaming.org/?quest=5214#wh-comments
2. http://db.vanillagaming.org/?npc=11058#wh-comments
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Potwierdzam.

**Comment by Vaelevian** [comment]
Poprawione. Wgrane zostanie rano około godziny 6.
