### ISSUE TITLE
[TALENT][SHAMAN][ENCHANCEMENT] Improved Stormstrike

### ISSUE THREAD

**Issue by Shigekunx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#515]
**Opis**: Talent Improved Stormstrike u Shamana Enchanchment nie przywraca 20% many - przywraca za to jakieś 100,

**Obecne działanie**: Talent Improved Stormstrike nie przywraca odpowiedniej ilości many. Powinien przywracać 20% a przywraca około 10%. Na chwilę obecną posiadam na swoim Shamanie 3,5K many po użyciu przywróciło mi jakieś 100-150 many gdzie powinno przywrócić 700~.

**Oczekiwane działanie**: Po użyciu skilla Stormstrike wraz z talentem Improved Stormstrike powinien przywracać 20% bazowej many.

**Co należy zrobić, aby odtworzyć ten błąd:**

1. Stworzyć postać Shamana.
2. Wylevelować drzewko Enchancement.
3. Użyć skilla Stormstrike.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=63375

**Comment by tokacz** [comment]
sprawdź dobrze bo u mnie wygląda na to, że działa tak jak powinien.

**Comment by Shigekunx** [comment]
Na pewno nie jest dobrze. Przy 3.467 many odnawia mi 200. A 20% z tej
liczby to 695.6. Nawet gdyby wliczyć używanie skilla to odnawia w tej
chwili 300 a powinien o wiele więcej. Pozdrawiam.

**Comment by valcy** [comment]
wez pod uwage ze to ma przywracac base mane

**Comment by Shigekunx** [comment]
Base mana to Twoja maksymalna mana. http://wowwiki.wikia.com/wiki/Base_mana

**Comment by valcy** [comment]
Base mana refers to how much mana a character has before it is modified by talents, intellect, enchants, and other item effects.
