### ISSUE TITLE
[BOSS] Bloodlord Mandokir

### ISSUE THREAD

**Issue by Hooraga** [RaphaelSunwell/Sunwell-BugTracker-SCv2#516]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Podczas walki z Bloodlord Mandokir, w wypadku Wipe, boss odbiega i się despawnuje. Po 1 wipe, nie można go ponownie znaleźć w Zul'Gurub

**Obecne działanie**: Bloodlord Mandokir po wipe, odbiega i się despawnuje.

**Oczekiwane działanie**: Podczas wipe, Boss powinien się zresetować i wrócić na swoje miejsce (szczyt piramidy)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Zul'Gurub
2. Udać się do bossa "Bloodlord Mandokir"
3. Dać się mu zabić i obserwować efekty.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=11382
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://scr.hu/11lh/vymfe

**Comment by Afgann** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5ac000f1e9bb1cd8e9c9ac07000afa27944d7ae2
