### ISSUE TITLE
[Quest] The Mosswalker Savior ID: 12580 

### ISSUE THREAD

**Issue by faldrack** [RaphaelSunwell/Sunwell-BugTracker-SCv2#517]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**zadanie polega na uwolnieniu oraclesow z niewoli nieumarlych**:

**nie mozna wejsc w zadna interakcje z lezacymi oraklesami**: TU WPISZ NA CZYM POLEGA PROBLEM

**zabole powinny losowo zostawiac skarb, albo zostac uwolnione**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. spróbowac wykonac zadanie z chaina dla repki oracless
2. kliknac na lezace npc
3. 

**Linki WoWHead/OpenWoW**:

1. 
![wowscrnshot_010517_165854](https://cloud.githubusercontent.com/assets/24940603/21690364/3af8acf4-d374-11e6-8442-1c5d932c42b6.jpg)

2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Quest da się wykonać. Na screenshocie widać, iż jest Pan w grupie rajdowej, a w takim przypadku questy są awykonalne.
