### ISSUE TITLE
[Location] Azure Dragonshrine (poprawka)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#519]
**Obecne działanie**: Na platformach brakuje jednego efektu.

**Oczekiwane działanie**: Powinien byc ruchomy efekt jak na screenie.

**Co należy zrobić, aby odtworzyć ten błąd**:

Sunwell: http://i.imgur.com/ckBXgQx.jpg
Global: http://i.imgur.com/78Z6cV9.jpg

Ten biały efekt na platformie pod kulą.

**Comment by Afgann** [comment]
`SET @GUID = 56547; #wolny guid`
`DELETE FROM gameobject WHERE guid = @GUID;`
`INSERT INTO gameobject (guid, id, map, spawnMask, phaseMask, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecs, animprogress, state, VerifiedBuild)`
`VALUES (@GUID, 188448, 571, 1, 1, 3029.383301, 538.310791, 61.703758, 3.723384, 0, 0, 0, 1, 300, 100, 1, 0);`

**Comment by Shon-su** [comment]
dzięki za pomoc
