### ISSUE TITLE
[NPC] 27185 - Kuk'uq <Spearcrafter> (bug animacji i broni)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#520]
**Obecne działanie**: NPC wymieniony podczas używania (tylko kowadła posiada polearm zamiast młotka) i sprzedaje 2 itemy, a powinien 1.

**Oczekiwane działanie**: Powinno być tak, że przy kowadle uderza młotkiem. Po czasie idzie do belek drewna z polearmem już i tam go jakby naprawia lub robi. Nastepnie idzie do paleniska (forge) i tam ma kawałek rozgrzanego metalu dopiero przy nim. Na koniec biegnie do wody po kostki i zanurza w nim. Po chwili leci para z wody na koniec i wraca do kolejnej roboty z młotkiem. 

Dodatkowo można kupić u niego 2 itemy, a powinno się kupować 1!

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzić zachowanie i itemy na sell

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=27185/kukuq

Screen: http://imgur.com/a/Cah3v
Video global: https://youtu.be/ahOs9XNn_jE

**Comment by Shon-su** [comment]
poprawione nie dograne
