### ISSUE TITLE
[SPELL][PALADIN] Czesciowe proce Seal of Corruption

### ISSUE THREAD

**Issue by Hexmann** [RaphaelSunwell/Sunwell-BugTracker-SCv2#521]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Seal of Corruption (najpewniej tez Seal of Vengeance) ma proce dopiero od momentu wbicia 5 stacków seala.

**Oczekiwane działanie**: Od patcha 3.2 Seal ten otrzymał redesign, i powinien zadawać obrażenia przy melee strike'ach/auto attackach proporcjonalnie w zależności od ilości stacków na targecie. Do patcha 3.3.5 włącznie nie pojawiły się w patch note'ach kolejne zmiany działania tego spella.

http://us.battle.net/wow/en/game/patch-notes/3-2-0

Seal of Vengeance and Seal of Corruption: These seals have been redesigned. Only auto-attacks and Hammer of the Righteous can place the debuff on the paladin’s current target(s). However, while the seal is active, each melee swing or ability (excluding judgements) that lands on the target will deal a percentage of weapon damage as Holy damage to the target. **This damage maxes out at 33% weapon damage with 5 applications of the debuff and scales upward evenly based on how many applications of the debuff are active**. This Holy damage deals double-damage critical strikes. In addition, the damage-over-time debuff is now considered a melee attack for the purposes of determining its chance to hit, miss, be dodged or parried.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Aktywować Seal of Corruption.
2.  Zacząć uderzać target.
3.  Przestać uderzać target przed wbiciem 5tego stacka
4. Sprawdzić dmg done- nie powinno w logu być dmg z "Seal of Corruption".

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=53736
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Seal of Corruption zadaje dmg od pierwszego stacka, równo co 3 sekundy tick.

**Comment by Hexmann** [comment]
Ticki pojawiające się co 3 sekundy nie są procami seal of corruption, które powinny pojawić się na każdym melee swingu, tylko tickami dotki nakładanej przez seala. Bug z sealem nie dotyczy tej dotki która działa prawidłowo, tylko proców seala na melee swingach.
