### ISSUE TITLE
[NPC] 26245 - Tua'kea (brak animacji)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#522]
**Obecne działanie**: Stoi w jednym miejscu i trzyma wędkę w ręku.

**Oczekiwane działanie**: Co 15 min NPC odchodzi od domku w kierunku wody i tam przystaje na 5 min i wraca. Wędka powinna być na plecach.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzić animacje NPC

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=26245/tuakea

Filmik: https://www.youtube.com/watch?v=T6alZYVbH4c&feature=youtu.be (muzyczka mi się nagrała xD)

**Comment by Afgann** [comment]
Struktura z TC, ale z tego co pamiętam to wiele się to nie różni. Gdyby ktoś sniffy użyczył to byłoby ładniejsze.

-- Tua'kea http://wotlk.openwow.com/npc=26245
SET @GUID = 108023;
SET @PATH := @GUID * 10;

UPDATE `creature_template` SET `MovementType`=2 WHERE `entry`=26245;

DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`, `orientation`, `delay`, `action`) VALUES
(@PATH, 1, 2728.969971, 935.776001, 0.223537, 3.508110, 900000, 0),
(@PATH, 2, 2725.669678, 935.673706, 0.151242, 0, 0, 0),
(@PATH, 3, 2723.665771, 940.981506, 0.132434, 0, 0, 0),
(@PATH, 4, 2717.235352, 945.446838, 0.199544, 0, 0, 0),
(@PATH, 5, 2709.003662, 951.448914, 0.132410, 2.748710, 300000, 0),
(@PATH, 6, 2716.692627, 949.006226, 0.132410, 0, 0, 0),
(@PATH, 7, 2721.197510, 940.112305, 0.147814 , 0, 0, 0);
DELETE FROM `creature_addon` WHERE `guid`=@GUID;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES 
(@GUID, @PATH, 0, 0, 0, 0, '');

**Comment by Shon-su** [comment]
dzięki za pomoc

**Comment by Mithras2801** [comment]
Jest tam kilka jednostek które nie posiada animacji. I to jedna lokalizacja z Dragonblight. Jest wiele do poprawek. Sniffy miałem.
