### ISSUE TITLE
[HUNTER][SPELL] Flara 

### ISSUE THREAD

**Issue by jaroszkox** [RaphaelSunwell/Sunwell-BugTracker-SCv2#523]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Flara huntera nie wykrywa instant lecz posiada travel time, którego powinno nie być.

**Obecne działanie**: Po rzuceniu flary trzeba czekać, aż efekt wizualny spadnie na ziemie, wtedy flara wykrywa jednostki.

**Oczekiwane działanie**: Flara powinna być instant, travel time to tylko visual. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wycastować flarę na kukłe/gracza
2. Obserwować po jakim czasie efekt flary zadziała

**Linki WoWHead/OpenWoW**:

1.  http://forum.sunwell.pl/viewtopic.php?f=23&t=2720
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Poprawione. Wrzucone zostanie w nocy z 11 na 12 stycznia.
