### ISSUE TITLE
BUG z wchodzeniem do wody z zatakowanym mobem

### ISSUE THREAD

**Issue by krawath** [RaphaelSunwell/Sunwell-BugTracker-SCv2#524]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

W grze występuje bug który uniemożliwia wchodzenie mobom do wody 

Problem polega na tym że zakatowany mob nie chce wejść za nami do wody 

Mob powinien podążać za nami w ramach swojego range i wchodzić do wody

udać się w miejsce gdzie występuje przejscie z lądu do wody jak na filmie 
https://youtu.be/cezi0LqYpPc

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
To nie bug, Panie krawath, to move mapy. ;) Proszę sprawdzić z potworami, które mają atrybut mobów lądowych i wodnych jednocześnie - one nie mają problemu z poruszaniem się po lądzie i pływaniem w wodzie za graczem. Przy kolejnych zgłoszeniach zalecam weryfikację z serwerami globalnymi. ;)

**Comment by krawath** [comment]
Haha, dawno się tak nie uśmiałem.
