### ISSUE TITLE
Wolf of Razormane hunter agro bug

### ISSUE THREAD

**Issue by krawath** [RaphaelSunwell/Sunwell-BugTracker-SCv2#526]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

Problem polega na tym że sumonn Razormane Hunter nie agruje się
https://youtu.be/A0xkD3Ip1gg

Jak powinno wyglądać - wilk powinien się agrować na celu Razormane hunter

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione
