### ISSUE TITLE
[Quest] Mending Fences

### ISSUE THREAD

**Issue by dondiego85** [RaphaelSunwell/Sunwell-BugTracker-SCv2#529]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Problem znajduje sie w quescie Mending Fences.

**Obecne działanie**: do zabicia elit zarowno iron giantow jak i Fjorn'a uzywamy 'Thorim's Charm of Earth' problem polega na tym, ze na fjornie item nie dziala. Przy probie uzycia dostajemy komunikat 'invalid target'

**Oczekiwane działanie**: Quest item 'Thorim's Charm of Earth' powinien dzialac zarowno na iron gianty jak i na Fjorn'a

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12915
2. http://wotlk.openwow.com/item=41505
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Mi śmigało.

**Comment by ThePuppetMaster** [comment]
Śmiga.
