### ISSUE TITLE
[mechanika] dungeon finder

### ISSUE THREAD

**Issue by dondiego85** [RaphaelSunwell/Sunwell-BugTracker-SCv2#531]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: problem tkwi w 'oczku' ktore pozwala sie teleportowac do i z dungeona

**Obecne działanie**: po wyjsciu dwoch osob 'oczko' znika

**Oczekiwane działanie**: 'oczko' powinno byc dostepne dopoki instancji nie opusci ostatnia osoba

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Kiedyś dobrze działało na old sunwellu bo był sniff z retaila.

**Comment by ThePuppetMaster** [comment]
Nie jestem w stanie odtworzyć błędu, ani nikt z "ankietowanych". Reopen w przypadku większej ilości komentarzy.
