### ISSUE TITLE
Portal przy Kalecgosie na Sunwell Plateau

### ISSUE THREAD

**Issue by damianek23** [RaphaelSunwell/Sunwell-BugTracker-SCv2#532]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Sunwell Plateau bugg z portalem

**Obecne działanie**: Przy smoku Kalecgos pojawia się portal do którego powinni wejść tank helery i dpsy lecz działa tu tak że może wbić maksymalnie tylko 1 osoba a reszta nie może.
**Oczekiwane działanie**: Do portalu powinni wejść więcej niż 1 osoba poniewaz 1 osoba nie wystoji sama bossa w portalu

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Poprawione.
