### ISSUE TITLE
[Spell][Paladin]Hand of Freedom

### ISSUE THREAD

**Issue by yamm** [RaphaelSunwell/Sunwell-BugTracker-SCv2#533]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Skill Hand of Freedom ( dalej HoF ) powinien umożliwiać paladynom dispel wszystkich efektów spowalniających i uniemożliwiających ruch postaci ( za wyjątkiem Daze ), na chwilę obecną nie działa do końca dobrze. HoF nie dość, że nie reaguje na niektóre skille mobów ( np. na Frostfire Bolt Focus Wizarda z Dragonblight ), to nie usuwa debuffa co powinno mieć miejsce ( np. https://www.youtube.com/watch?v=brJoU3a2MoQ 2:11 ). Nie wiem jak ma się to ze skillami innych graczy ( np. Mage ).

**Oczekiwane działanie**: Skill powinien neutralizować działanie wszystkich efektów spowalniających i uniemożliwiających ruch, dodatkowo usuwając debuffy tych efektów, a także dawać postaci pod efektem tej umiejętności niewrażliwość na te efekty przez 6 sekund.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Iść do Dragonblight, do Glittering Strand
2. Rozpocząć walkę z mobem Focus Wizard
3. Gdy mob trafi nas Frostfire Boltem należy użyć Hand of Freedom

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=1044
2. http://wotlk.openwow.com/spell=51779
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Heartbraker** [comment]
Jeśli o pvp chodzi to 'raczej' działa ok, ale mogłem coś przeoczyć, bo wszystkiego nie sprawdzałem.
Natomiast w pve zaryzykowałbym stwierdzenie, że działa może w jakichś 50% przypadków, tak jakby spelle na które ma działać HoF były dodawane ręcznie po ich ID i sporo zostało przeoczonych (da się to bardzo odczuć podczas expienia, zwłaszcza na niższych poziomach)

**Comment by Vaelevian** [comment]
Poprawione. Wgrane zostanie rano tj. 13.01. około 6.
