### ISSUE TITLE
[Pets] Avoidance (passive)

### ISSUE THREAD

**Issue by bartekmad** [RaphaelSunwell/Sunwell-BugTracker-SCv2#534]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Avoidance is a passive summoned pet ability that decreases damage taken by creature AoE Spells and effects by 90%. This passive ability is innate for all classes' pets.

**Obecne działanie**: Aktualnie pety otrzymują olbrzymi dmg z umiejętności aoe bossów (fala na OS oraz erupcja na Heiganie)

**Oczekiwane działanie**: Pety powinny otrzymywać jedynie 10% obrażeń.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się na jednego z wyżej wymienionych bossów
2. Przywołać peta najlepiej hunterem, albo warlockiem z racji na ich niski poziom hp, ewentualnie DK.
3. Poczekać na falę/erupcję.

**Linki WoWHead/OpenWoW**:

1. http://wow.gamepedia.com/Avoidance_(passive)
2. http://i.imgur.com/6osalCD.png
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
-

**Comment by Vaelevian** [comment]
Erupcja na Heiganie zadaje około 70 tysięcy dmg. Przy 3 falach jest to blisko 22k dmg dla peta.

**Comment by bartekmad** [comment]
A co 3 fale mają do tego, że pet stoi w jednej i ginie od jednej?
