### ISSUE TITLE
[Item][Quest] Crimson Crystal Shard

### ISSUE THREAD

**Issue by halbazzer** [RaphaelSunwell/Sunwell-BugTracker-SCv2#535]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Item "Crimson Crystal Shard" nie dropi z NPC: "Raging Colossus" lub drop-rate jest za niski (powinien być w sumie 100%) (Hellfire Peninsula (coords: ~15, 40)) co nie pozwala kontynuować quest-chain'a (ubiłem 10 i zero drop'u)

**Obecne działanie**: jak w Opis-ie

**Oczekiwane działanie**: Item "Crimson Crystal Shard" powinien dropnąć w zasadzie z pierwszego ubitego NPC: "Raging Colossus" po podjęciu Quest-u "Colossal Menace" (nie znalazłem informacji czy Item powinien dropić bez Q)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. podjąć Quest "Colossal Menace" od NPC: "Tola'thion" (Hellfire Peninsula 15.6, 52.0)
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=29476/crimson-crystal-shard#comments
2. http://www.wowhead.com/npc=19188/raging-colossus
3. http://www.wowhead.com/quest=10132/colossal-menace

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Map: Hellfire Peninsula ZoneX: 15 ZoneY: 40

**Comment by Shon-su** [comment]
UPDATE `creature_loot_template` SET `ChanceOrQuestChance` = -100 WHERE `item` = 29476;

**Comment by Shon-su** [comment]
tylko jakbyscie to wrzucali to sprawdzcie czy jest podpięty ten item w quest_template bo zapomniałem ;p

**Comment by halbazzer** [comment]
cóż .. niestety nie mogę sprawdzić czy quest działa ..

bo nieopacznie (z rozpędu) oddałem quest "Colossal Menace" .. napisałem Ticket w tej sprawie, ale otrzymałem odmowną odpowiedź: "Nie ma możliwości cofnięcia wykonanego questa"

o ile wiem wiem to technicznie taka możliwość jest:

jako GM - target osobnika i: 
 .quest remove 10132

lub wykonać query na bazie: 
 delete character_queststatus_rewarded from character_queststatus_rewarded join characters using (guid) where name="<Charname>" and quest=10132 and active=1;

w takim razie nie wiem po co te komunikaty w grze "help us polish sunwell" skoro próbuje pomóc i trafiam na mur ..

Pozdrawiam

**Comment by Vaelevian** [comment]
Poprawione, dodane zostanie dzisiaj o 6 rano.
