### ISSUE TITLE
[STATISTIC] Armor Penetration

### ISSUE THREAD

**Issue by Somethiing** [RaphaelSunwell/Sunwell-BugTracker-SCv2#537]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
How much of ArP you need to reach 100% cap.
**Obecne działanie**: At the moment you need around 1400 ArP to reach 100%.

**Oczekiwane działanie**: For patch 3.1.2 it should be 1232 to get 100%. With ArP capped like this it is possible to get soft cap which is very important for few specs at this content.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Change armor penetration rating so it will reduce armor of the bosses at 83+ lvl by 100% with 1232 of this stat instead of 1400 as it is now.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Armor_penetration
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Kondonman** [comment]
nie prawda

**Comment by Somethiing** [comment]
Dopiero na patchu 3.2.2 powinno być 1400.

**Comment by Baggedmilk** [comment]
nie mamy patchu 3.1.2

**Comment by Somethiing** [comment]
Ale progressujemy od początku a jeśli chodzi o gearowanie się np do hunta mm bez zmniejszenia capu jest to bardzo słabe przy itemach z tego contentu.

**Comment by Baggedmilk** [comment]
no to musisz poszukac jaki powinien byc bo na pewno nie 1232 (w 3,1 arp mial jakiegos buffa)

**Comment by Somethiing** [comment]
Wejdź w link i popatrz na patch notes na tym patchu co obecnie powinniśmy być, powinien być właśnie taki czyli 1232 :)

**Comment by Baggedmilk** [comment]
Patch 3.1.2 (2009-05-19): Capped to 100% (or 1232 armor penetration rating)
Patch 3.1.0 (14-Apr-2009): All classes now receive 25% more benefit from Armor Penetration Rating.
dopiero w 3.1.2 zmienili cap do 100%, my jestesmy na 3.0.8(?)

**Comment by Somethiing** [comment]
Ale z pewnością nie był ustawiony na 1400 bo to wchodzi razem z tocem. Jak ustawia cap 1232 to będzie on prawidłowy od naxxa do uldu czyli dwa pełne rajdy które pewnie trochę potrwają na sunku :)

**Comment by Somethiing** [comment]
Before 3.2.2, a MM Hunter needed 1232 Armor Penetration in order to reduce a target’s armor to zero. This was attained by using either Mjolnir Runestone or Grim Toll, and by reaching an Armor Penetration soft cap not including the bonus from the trinket proc. With Mjolnir, 567 ArPen was needed, and with Grim Toll, 620 ArPen. With the respective procs, it would bring the total Armor Penetration level to the desired 1232, thus negating the target’s armor completely.

When 3.2.2 hit, it increased the amount of ArPen needed from 1232 to 1400 in order to obtain 100% armor reduction. This meant you’d now need 735 ArPen w/ Mjolnir, or 780 w/ Grim Toll. In other words, 168 more ArPen. Trying to reach that mark would force a Hunter to have to sacrifice a ton of agility, therefore compromising the overall effectiveness of the build.

**Comment by Baggedmilk** [comment]
znalezione w komentarzach wowhead (patch 3.0.3) 15.39 armor pen. rating is 1% armor pen. at level 80, so 612 armor pen. rating is 39.76% armor pen.

**Comment by Somethiing** [comment]
Jeśli chodzi o content i patch to jest różnie można powiedzieć teraz, bo mamy niby patch 3.3.5 a nie mamy. Przez większość naxxa i później całe uldu ten cap wynosił 1232. Zobaczymy co powie administracja :) Jeżeli tego nie zmienia to będzie naprawdę ciężko o ten soft cap bo na jego rzecz bardzo dużo agi np poleci.

**Comment by Baggedmilk** [comment]
przeciez w 3.1 (czyli ulduar) buffneli arp, przez calego naxxa cap prawdopodobnie wynosil 1540

**Comment by Heartbraker** [comment]
Weźcie pod uwagę, że gramy na patchu 3.3.5a z contentem z patcha...w sumie ciężko określić, bo naxx pojawił się na 3.0.2, EoE też na 3.0.2, a ciągle jest zamknięte, natomiast przed patchem z uldu 3.1.0 było jeszcze kilka patchy, w tym 3.0.8 który wprowadził m.in. zakup rare gemów za 10 Emblem of Heroism u vendora w Dalaran, co obecnie jest niedostępne (za to dostępny jest npc Frozo the Renowned z patcha 3.3.3 :P)
Wracając do tematu: gramy na patchu 3.3.5a, wszystkie skille i ogólne działanie oraz mechanika gry (w tym różne capy, również ArP), są takie (a przynajmniej powinny być) jak na patchu 3.3.5a. Content jaki obecnie jest określa jedynie na jakie rajdy da się wejść, jakie itemy da się zdobyć, a jakich nie, jakie npc widzimy, jakich nie, jakie questy możemy zrobić itp. 
Dostosowywanie całej mechaniki do contentu jaki administracja akurat wprowadza jest niemożliwe z powodu braku rąk do pracy, a podjęcie takiej próby byłoby idiotyczne, bo z małego burdelu związanego z samej różnicy contentu powstałaby kompletnie niegrywalna kupa.
W skrócie : arp powinien działać tak jak działał na 3.3.5a, więc skoro w patchu 3.2.2 była ostatnia zmiana, to tak własnie powinno być jak w patchu 3.2.2

**Comment by Baggedmilk** [comment]
z tego co napisales to dziala tak jak na 3.3.5a (1400 arp cap)

**Comment by Vaelevian** [comment]
Działamy na patchu 3.3.5, z blokowanymi instancjami odpowiednimi dla patcha 3.0.8. Statystyki i każdy inny aspekt gry (wyłączając profesje Jewelcrafting oraz Tailoring) odpowiadają patchowi 3.3.5.
