### ISSUE TITLE
[quest] Fletcher's Lost and Found

### ISSUE THREAD

**Issue by mariannnn** [RaphaelSunwell/Sunwell-BugTracker-SCv2#538]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: npc=32516 (w kanałach dalaranu) nie daje questa Fletcher's Lost and Found quest=13571

**Obecne działanie**: npc nie daje questa

**Oczekiwane działanie**: 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13571/fletchers-lost-and-found
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Musisz ukończyć chain zaczynający się tym questem:
http://www.wowhead.com/quest=12634/some-make-lemonade-some-make-liquor
