### ISSUE TITLE
Recka w Terokkar Forest Adamantite Rod

### ISSUE THREAD

**Issue by Xarafis** [RaphaelSunwell/Sunwell-BugTracker-SCv2#54]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:U vendora powinien być cd. na kupowanie tej recki.

**Obecne działanie**: Można ja kupować ile dusza zapragnie.

**Oczekiwane działanie**: Powinno się ją dać kupić raz i odczekać pewien czas aby ta recka była znowu dostępna.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się w miejsce gdzie vendor się znajduje. 
2. Kupić reckę.
3. Kupić reckę ponownie.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=25848/formula-runed-adamantite-rod#comments
2. 
3. 

**Lokalizacja z koordynatów GPS (48.85, 46.13,Terokkar Forest)**:

**Comment by Shon-su** [comment]
done
