### ISSUE TITLE
Xt53 touring rocket za pp

### ISSUE THREAD

**Issue by blizerdix** [RaphaelSunwell/Sunwell-BugTracker-SCv2#540]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Xt53 touring rocket dla dwóch osób 

**Obecne działanie**: Mount działa wyłącznie 
 na Northrend oraz Outland  oraz prędkość poruszania się na wintergrasp  podczas bitwy wynosi 0%

**Oczekiwane działanie**: poruszanie się z prędkością 100% (bądź mniejsza w zależności od riding) po kalimdor i eastern kingdoms  oraz poruszanie  podczas bitwy wintergrasp 100% bądź mniejsza w zależności od riding. Podczas kupowania mounta x53 nie ma informacji ze można go używać tylko po Northrend i Outland w przeciwieństwie do podobnego mounta (drugiej rakiety) x51 która również można kupić za pp

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Spróbować wsiąść na mounta na kontynentach eastern kingdoms oraz kalimdor 
2. Wsiąść na mounta podczas bitwy wintergrasp 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=54860/x-53-touring-rocket
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
X-53 touring rocket działa poprawnie. Dopiero w patchu 4.0.1 mogła być używana również jako ground mount.

**Comment by blizerdix** [comment]
Czyli na wg jest to normalne że porusza się z prędkością 0%?
