### ISSUE TITLE
Zbugowany combat na graczach i na nas

### ISSUE THREAD

**Issue by kevery123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#541]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Combat na serwerze jest strasznie zle oskryptowany jest wiele przykładów w których źle działa, niektóre nawet nie wiem jak uzasadnic bo nie wiem w czym leży problem ( jak np. jem sobie na arenie rogalem ( mage food ) i nagle przestaje jesc i mam combat a jestem 40 yrdow od przeciwników i mam dampena i 40 inta buffy od maga na comp bez petów. Kolejny przykład z zbugowanymi petami ( wystarczy wyslać peta na mnie i mam nikończący sie combat, ale nie zawsze tak było że niekończący, czasami udawalo mi się restealthowac stojąc za losem przez 20 secund gdy pet locka  na mnie biegl np z blades edge areny z góry schodami na dol za filar ( nie wiem jak moga byc tego typu bugi nic mnie nie bije a mam combat przez 20 sec / albo koles wyslal wilki na mnie na początku areny i nie moge stealhnąc a wilki dopiero biegną na mnie z drugiego końca areny/ albo summon water elemental odrazu po przywolaniu nabija combat bez wcastowania nawet spella( waterb bolta). Jest jeszcze wiele sytuacji w których np. przez buga combatu nie mogę sapnąć przciwnika przez długi czas bo ma utrzymujący się combat np. 10 sec  po bani paladyn sie healuje wogol po dugiej stronie nie ma blisko ani jego parterna ani mojego a ja pale vanisha po bani i czekam z sapem a combat się utrzymuje. Mam wrażenie że cos buffy moga nabijać combat ale nie jestem pewny 

**Obecne działanie**: wszystko opisałem w opisie

**Oczekiwane działanie**: combat nie powinien sie utrzymywac przez wiecej jak 6 sec  albo po wyslaniu na nas peta nie powinismy lapac combatu tylko dopiero po uderzeniu nas

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wyslac rozne pety na rogala i zobaczyc czy nabijaj mu combat bez ataku 
2. Poprobowac czy jak sie jest z kims w party kto ma od nas buffy albo my mamy czyjee buffy czy combat nabity tej ktorejs z tych osob nie sprawia tez nabica combatu drugiej przez posiadanie buffa 
3. Mozna poprobowac jeszcze innych rzeczy z combatem poniewaz czasami poprostu nie mam pojecia skad sie bierze na mnie albo na przeciwniku, strasznie zle działa ( na ta chwilę sub rogal sie nie nadaje do niczego z takimi bugami)

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Nie mamy możliwości przeprowadzenia tak obszernych testów, jakie Pan oczekuje. Z przypadków, które Pan opisał znany mi jest tylko przypadek Water Elementala, czy petów Warlocka, które nabijają combat już w czasie castowania spella - co jest jak najbardziej prawidłowe. Jeśli ma Pan dostęp do globalnych serwerów, polecam sprawdzić wiarygodność moich słów.

**Comment by kevery123** [comment]
Czyli jak jem sobie 40 yrdow od graczy przeciwnika i petów to samo wysłanie peta i nabicie mi combatu jest poprawne ? Pograjcie sobie rogalem chociaz 1 dzien areny zobaczycie jak bardzo jest niegrywalny na tym serwerze a wy nic nie robicie zeby to poprawic

**Comment by kevery123** [comment]
Po drugie czemu odrazu zamykasz post ktory jest prawidlowy to sa dosc powazne bugi i nie rozumiem czemu nie mozna przeprowadzic testow. Przeciez wystarcz pograc nawet pare dni i odrazu widac bugi rogala, szczegolnie jak combat sie utrzymuje na mnie czasami po 20 secund a nic mnie nie bije. Jesli wedlug was taka sytuacja nie wymaga poprawienia to ja podziekuje temu serverowi.

**Comment by valcy** [comment]
Sprawdz czy to sie nie dzieje poprzez zostawienie dot na targecie np poisonow czy bleedow.

**Comment by valcy** [comment]
Actions that will get you into combat 

    Attacking
    Casting an offensive Spell
    Casting a Buff or Healing spell on a unit that is in combat
    Getting on a mob's Aggro list
    Certain bosses always put everyone in the group (or raid) in combat when engaged, regardless their distance from the boss

**Comment by valcy** [comment]
A i jezeli grasz z magiem sprawdz czy to nie przez Replenishment

**Comment by DinozaurWKamizelce** [comment]
Jeżeli chodzi o combat to moje spostrzeżenia (całkiem przypadkowe podczas robienia innych testów na kukle) są takie:
1) Jeśli bijemy kukłe i przestaniemy ją bić, nawet jak zostały jakieś doty to po pewnym czasie wychodzimy z combatu a doty potrafią zniknąć jeszcze przed ich końcem. (sugerowałoby mechanikę combatu PvP)

2) jeśli przestaniemy bić kukłę ale zacznie bić ją ktoś inny(zupełnie z nami nie związany, bez party, naszych buffów itp) to żeby wyjść z combatu musimy czekać bardzo długo.

Nie wiem jak to wygląda w PvP i nie wiem czy kukła ma mechanikę combatu z PvP czy z PvE
