### ISSUE TITLE
[SKILL][DEATH KNIGHT] Skill Death Grip w PvP

### ISSUE THREAD

**Issue by Andrzei** [RaphaelSunwell/Sunwell-BugTracker-SCv2#543]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
![wowscrnshot_011217_004004](https://cloud.githubusercontent.com/assets/15867814/21871258/489513f6-d861-11e6-8184-bb900f7455d1.jpg)

**Obecne działanie**: Umiejętność Death Grip zgłasza błąd "Target is too close" w trakcie walki z innymi graczami. 

**Oczekiwane działanie**: Umiejętność Death Grip może zostać użyta przy każdej, nawet minimalnej odległości od przeciwnika tak jak jest to przy walce z mobami.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wyzwać innego gracza na duel i użyć umiejętności Death Grip będąc w melee range lub delikatnie poza
2. Będąc na arenie użyć umiejętności Death Grip aby przerwać cast przeciwnika będąc w melee range lub delikatnie poza
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=51399
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Piootrek** [comment]
Blizzlike
Patch 3.3.3 (2010-03-23): Minimum range has been changed to 8 yards in PvP.

**Comment by Andrzei** [comment]
Dziękuje za odpowiedź, Widocznie zmyliły mnie mechaniki które zapamiętałem z innych serwerów. Temat do zamknięcia
