### ISSUE TITLE
[NPC] 23008- Ethereum Jailor (brak dropu Iteamu )

### ISSUE THREAD

**Issue by Banstime** [RaphaelSunwell/Sunwell-BugTracker-SCv2#546]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po Zabiciu NPC-a nie ma dropu Iteamu ktory wg WowHeada ma 93 % dropu.

**Obecne działanie**: Po zabiciu NPC-ow z ktorych jest 93 % szans na zdobycie klucza (item=29460) ( Linku nr.2) iteam nie wypada.

**Oczekiwane działanie**: Przy 93 % Dropie- iteam powinien wypadac 9/10 zabitych NPC-ów.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabic kilka NPC -ców i co wydropilo. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=23008/ethereum-jailor
2. http://www.wowhead.com/item=29460/ethereum-prison-key
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Sa na pierwszym Linku.

**Comment by Akha72** [comment]
*Przy 93 % Dropie- iteam powinien wypadac 9/10 zabitych NPC-ów.* - nie tak działa % drop rate.

Klucze dropią normalnie, tylko musisz zrobić quest Ethereum Secrets - przynajmniej dropiły jakieś 2 tyg temu.

**Comment by Banstime** [comment]
Ok działa wszystko Dzieki Raphael :)

2017-01-15 1:54 GMT+01:00 ThePuppetMaster <notifications@github.com>:
