### ISSUE TITLE
Frozo the Renowned <Frozen Orb Trader>

### ISSUE THREAD

**Issue by daykiri** [RaphaelSunwell/Sunwell-BugTracker-SCv2#548]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: NPC nie powinien byc na tym patchu

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

**Oczekiwane działanie**: Added in patch 3.3.3.11573
**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=40160/frozo-the-renowned
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Done, powinien zniknąć niebawem.

**Comment by Heartbraker** [comment]
9dni pozniej npc dalej dostepny
