### ISSUE TITLE
[ITEM]Noggenfogger Elixir

### ISSUE THREAD

**Issue by zbynew** [RaphaelSunwell/Sunwell-BugTracker-SCv2#55]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po spożyciu i otrzymaniu efektu Noggenfogger Elixir "You've stopped breathing" nie można wejść na mounta.

**Obecne działanie**: Nie można użyć mounta po spożyciu dającego efektu "szkieleta"
**Oczekiwane działanie**: Po wypiciu i otrzymaniu efektu "szkieleta" powinna być możliwość przywołania mounta.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=8529/noggenfogger-elixir
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by zbynew** [comment]
to samo tyczy sie wszystkiego co zmienia formę, tj. Savory Deviate Delight, czy też Orb of Deception, ale nie jestem pewien cyz w tych przypadkach działa to tak samo.

**Comment by Immunez** [comment]
Podpinam sie pod to. Wydaje mi sie, ze powinna byc mozliwosc wsiascia na mounta, bo jestem pewien, ze uzywalem tego w ten sposob niejednokrotnie juz na TBC.

**Comment by Mithras2801** [comment]
Do zamknięcia dopiero po 5.0.4 była mozliwość wejścia na mounta z tym efektem i z Savory.

http://www.wowhead.com/item=8529/noggenfogger-elixir#comments:id=1706083
