### ISSUE TITLE
[QUEST] The Mindless Ones

### ISSUE THREAD

**Issue by Akha72** [RaphaelSunwell/Sunwell-BugTracker-SCv2#552]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest The Mindless Ones (http://wotlk.openwow.com/quest=364), który odblokowuje dalsze questy w Deathknell, Tirisfal Glades powinien być dostępny dla wszystkich ras hordy - tutaj podrzucam komentarz z wowheada na ten temat (http://www.wowhead.com/quest=364/the-mindless-ones), obecnie przyjąć go można tylko po zakończeniu Rude Awakening (http://wotlk.openwow.com/quest=363), który jest forsaken-only, co sprawia, że inną rasą jak Undead nie można zrobić questów z tej startówki.

The Mindless Ones quest that is required to progress with questing in Undead starting area (Deathknell) has Forsaken-only pre-q Rude Awakening. However, this quest should be obtainable by other horde races as well, though without the need to complete this Undead-specific pre -q. Currently, it is not possible.

**Obecne działanie**: W chwili obecnej quest ten mogą przyjąć jedynie grający rasą Undead, którzy skończyli uprzednio pre Rude Awakening

**Oczekiwane działanie**: Quest powinien być dostępny dla wszystkich ras hordy

**Linki WoWHead/OpenWoW**:

1. Rude Awakening (http://wotlk.openwow.com/quest=363)
2. The Mindless Ones (http://wotlk.openwow.com/quest=364)
3. Wowhead comment (http://www.wowhead.com/quest=364/the-mindless-ones)

**Comment by xsitdev** [comment]
http://www.wowhead.com/quest=363/rude-awakening

"This quest can only be done by undead (for obvious reasons). Went back with my blood elf to do all of these quests, to get my Undercity reputation up, and could not pick this one up. Just a minor thing, but still thought I'd mention it for anyone else looking to get their Undercity rep up."

**Comment by Akha72** [comment]
Obecnie quest Rude Awakening jest undead-only obowiązkowym pre-q do The Mindless Ones, co z automatu wyklucza inne rasy ze zrobienia The Mindless Ones i reszty follow-up q w Deathknell. Tak być nie powinno - rasy inne niż Undead powinny móc przyjąć q The Mindless Ones bez uprzedniego wykonania Rude Awakening, który powinien pozostać Undead-only.
Problem jest w tym, że dla innych ras do przyjęcia The Mindless Ones wymagany jest obecnie ukonczony Rude Awakening co jest niemożliwe.
Prawidłowym działaniem jest dla Undeadów kolejność Rude Awakening -> The Mindless Ones, dla innych ras start od The Mindless Ones.
Starałem się to napisać prosto, ale jeżeli jest to dalej niejasne, to po weekendzie zrobię reopen.
