### ISSUE TITLE
[quest] the eagle's essence

### ISSUE THREAD

**Issue by topolka23** [RaphaelSunwell/Sunwell-BugTracker-SCv2#553]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: jeden q z chaina do 280% formy latania dla druida, pre q do posiadania anzu

**Obecne działanie**: mob z tego q spawnuje sie wewnatrz pomnika i nie da sie go bic, ani aoe, ani auto atakiem, niczym. nie aggruje sie tez na graczy z low lvl. jest albo invalid target albo cannot attack

**Oczekiwane działanie**: mob powinien spawnowac sie przed pomnikiem z automatycznym atakiem na tego kto kliknal na pomnik

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  nie wiem nie jestem game masterem -.-
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10990/the-eagles-essence
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 
map 530, zone 3519, area 3519
x -2618 y 4573 z 138

**Comment by xsitdev** [comment]
Nie jestem w stanie potwierdzić, spokojnie mogłem atakować go po zakończeniu summowania.

Co do tego gdzie on ma się spawnować odpowie Ci film z Retail'a:
https://www.youtube.com/watch?v=XU8rtREO5vY
