### ISSUE TITLE
[SPELL] Escape Artist

### ISSUE THREAD

**Issue by Dragonk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#554]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jest to spell rasowy Gnomów, który powinien usunąć efekt unieruchomienia lub spowolnienia.

**Obecne działanie**: Nic nie robi

**Oczekiwane działanie**: Usunięcie debuffu spowolnienia albo unieruchomienia.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Oberwać spowolnieniem
2. Użyć skilla
3. 

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/spell=20589/escape-artist
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by DinozaurWKamizelce** [comment]
To nie jest tak że nic nie robi. Talent uwalnia z usidleń roots itp. ale nie zdejmuje spowolnień.
Sam trochę nad tym myślałem, ale nie miałem czasu zrobić odpowiednich testów bo byłem innymi błędami.

PS: Dobrze opisany problem rozwiązuje się łatwiej.
