### ISSUE TITLE
[BOSS] Anub'Rekhan

### ISSUE THREAD

**Issue by pkorthal** [RaphaelSunwell/Sunwell-BugTracker-SCv2#555]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nieprawidłowa ilość hp

**Obecne działanie**: Boss ma ~ 14 MLN hp
**Oczekiwane działanie**: boss powinien mieć  6,763,325 hit points

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przywrócić sunwell do blizzlike jako który się reklamuje http://topg.org/wow-private-servers/
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Anub'Rekhan
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by DinozaurWKamizelce** [comment]
Potwierdzam, jak ostatnio byłem na Naxx 25 to boss miał około 14 mln HP

**Comment by xsitdev** [comment]
Boss ma 14 MLN hp nawiązując do update boost'a  (utrudnienia) naxxramas.
