### ISSUE TITLE
[MAGE][TALENT][Master of Elements] talent niepoprawnie zwraca manę

### ISSUE THREAD

**Issue by DinozaurWKamizelce** [RaphaelSunwell/Sunwell-BugTracker-SCv2#556]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

Niestety nie wiem jak zrobić "Reopen" pochopnie zamkniętego tematu https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/492

**Obecne działanie**: 

Talent ZWRACA manę po krytykach z następujących spelli:

-Scorch
-Pyroblast
-Fire blast
-Fireboll
-Frostfire bolt
-Flamestrike
-Cone of Cold
-Frost nova
-Ice lance
-Frostbolt

Talent NIE ZWRACA many z następujących spelli:

-Living Bomb - http://wotlk.openwow.com/spell=44461
-Dragon's Breath - http://wotlk.openwow.com/spell=31661
-Blast Wave - http://wotlk.openwow.com/spell=11113
-Blizzard - http://wotlk.openwow.com/spell=10
-Arcane Missiles - http://wotlk.openwow.com/spell=7268
-Arcane Blast - http://wotlk.openwow.com/spell=30451
-Arcane Barrage - http://wotlk.openwow.com/spell=44425
-Arcane Explosion - http://wotlk.openwow.com/spell=1449

Nie sprawdziłem chyba tylko czaru Deep Freeze z drzewka frost bo na kukłach nie zadaje obrażeń (jak ktoś może niech sprawdzi)

Dodatkowo talent nie bierze %[base mana cost] tylko %[mana cost] w momencie wystąpienia krytycznego trafienia

**Jak powinno być:**
Talent powinien zwracać %[base mana cost] każdego spella jeżeli ten uderzy krytycznie

**Co jest nie tak:**

**1)** Talent w ogóle nie zwraca many z wypisanych wyżej spelli

**2)** Talent nie zwraca 10/20/30% bazowego kosztu czaru tylko odpowiedni procent aktualnego kosztu czaru w momencie wystąpienia krytycznego trafienia (wliczają się w to zarówno talenty obniżające koszt czarów jak i efekty takie jak clearcasting lub Brain Freeze)

Dokładniejszy opis w przypadku clearcastingu:

Jeżeli mamy clearcasting i uderzymy z czarów, które uderzają natychmiastowo: Scorch, Fire Blast, Frost Nova, Cone of Cold, Flamestrike (czary, które zwracały manę bez clearcastingu) to nie zwróci nam many bo w momencie uderzenia mamy clearcasting (koszt many wynosi 0)

-Pojawia się clearcasting
-krytyczne trafienie
-Znika clearcasting

W przypadku fireballa itp zwróci nam manę bo clearcasting zniknie zanim czar doleci. (jestem przekonany że tylko dlatego zwraca manę w przypadku Brain Freeze )

W celu sprawdzenia można uderzyć Flamestrike posiadając clearcasting (tak by uderzył przed zniknięciem buffa) a następnie
Wywołać clearcasting
zacząć castować flamestrike
samemu wyłączyć buffa
Uderzyć krytycznie

Talent zwróci manę ale nie będzie to 30% base mana, ani też 30% mana wziętego do scastowania tylko 30% mana potrzebnego do scastowania branego w momencie uderzenia.

**Linki:**

Talent:
Master of Elements - http://wotlk.openwow.com/spell=29074

Czary, z których nie zwraca many:
Living Bomb - http://wotlk.openwow.com/spell=44461
Dragon's Breath - http://wotlk.openwow.com/spell=31661
Blast Wave - http://wotlk.openwow.com/spell=11113
Blizzard - http://wotlk.openwow.com/spell=10
Arcane Missiles - http://wotlk.openwow.com/spell=7268
Arcane Blast - http://wotlk.openwow.com/spell=30451
Arcane Barrage - http://wotlk.openwow.com/spell=44425
Arcane Explosion - http://wotlk.openwow.com/spell=1449

Linków do talentów i efektów nie będę dawał bo powinno brać % base mana niezależnie od wszystkiego (talenty, itemki, zewnętrzne buffy/debuffy i nie sposób tego wyliczyć)

O ile punkt 2 wydaje się dość dobrze rozpracowany o tyle nie mam pomysłu czym może być spowodowany punkt 1.

**Comment by ThePuppetMaster** [comment]
OK, to jest bug. Teraz jak powinno być. Talent powinien zwracać base mana % od każdego dmg spella, zadającego dmg jednemu lub kilku przeciwnikom. W przypadku spelli channelowanych lub dot, krytyczny tick zwraca % base mana cost / ilość ticków w pełnym przejściu channelingu, lub pełnym czasie trwania doty.

**Comment by Crackaw** [comment]
Dragon's Breath oraz Blast Wave działają poprawnie i zwracają manę po critical stike'u.

**Comment by DinozaurWKamizelce** [comment]
Może już coś się zmieniło. W momencie gdy sprawdzałem nie zwracały.

**Comment by Crackaw** [comment]
Clearcasting znika po wycastowaniu, więc dlatego przywraca manę za instahit, a za castowalne już nie. To samo tyczy się Brain Freeze. Dzięki za dobrze udokumentowany bug :+1:
