### ISSUE TITLE
[Profesja][Fishing] loot przedmiotow jakości poor

### ISSUE THREAD

**Issue by remeyes** [RaphaelSunwell/Sunwell-BugTracker-SCv2#558]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Przedmioty jakości poor nie sa dodawane do ekwipunku po zlowieniu
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Po kliknieciu spławiki pojawia sie okno lootu, zbieram loot ale nie trafia on do bagow. Brak potwierdzenia także w postaci komunikatu na chat'cie. DOTYCZY TO TYLKO PRZEDMIOTÓW JAKOŚCI POOR.
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po kliknieciu spławiki pojawia sie okno lootu, zbieram loot, który trafia do plecaka.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zacząć łowić
2. Ppm na spławik
3. Zebrać loot

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Horpah** [comment]
Potwierdzam. Po wyłączeniu autoloota przedmioty poor pojawiają się ale nie można ich zlootować bo zamiast wpaść do plecaka znikają. Nie pojawia się także informacja na czacie.

**Comment by Neos3452** [comment]
Fix. Loot hack i updateskill nie jest aplikowany dla junk.

[0001-Fix-fishing-on-junk.patch.txt](https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/files/737476/0001-Fix-fishing-on-junk.patch.txt)
