### ISSUE TITLE
[Quest][NPC] WANTED: Murkdeep

### ISSUE THREAD

**Issue by chaosmapek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#561]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Brak NPC Murkdeep

**Obecne działanie**:
Brakuje potworka/NPC Murkdeep
**Oczekiwane działanie**: 
NPC zostanie dodany do kodu gry i będzie można wykonać quest

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=4740/wanted-murkdeep
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by DinozaurWKamizelce** [comment]
Czy na pewno? Nie tak dawno robiłem ten q i wyglądał on tak:

Koło lokalizacji NPC jest kilku murloków, po zabiciu ich Murkdeep wyszedł z wody. Inaczej czekając nawet długo NPC się nie pojawiał.

Nie wiem czy tak to miało wyglądać, ale wydaje mi się, że tak. 

PS: Poprawnie opisane problemy rozwiązuje się łatwiej. Nie napisałeś ile czekałeś, gdzie go szukałeś (kordynaty) ani poprawnie, co powinno być. "NPC zostanie dodany do kodu gry". Zapewniam Cię, że NPC już jest dodany do kodu gry.
Jeśli napiszesz "NPC powinien się spownować co xx minut", "stać/chodzić w podanej lokalizacji" to dobrze byłoby się upewnić czy na pewno tak powinno być.
