### ISSUE TITLE
[Spell] Ebon Gargoyle zmiana targetu 

### ISSUE THREAD

**Issue by Craackxo** [RaphaelSunwell/Sunwell-BugTracker-SCv2#563]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Gargulec nie reaguje na komendę zmiany celu ataku.

**Obecne działanie**: Gargulec bije tylko i wyłącznie cel na który został przywołany, po użyciu macro /petattack na inny cel gargulec nie reaguje, 

**Oczekiwane działanie**: Po użyciu macro /petattack na dany cel gargulec powinien go atakować, oczywiście takie typu sterowanie gargo jest możliwe tylko gdy Ghoul(pet) DK jest przywołany.W pewnym sensie Gargulec powinien być jakby podpięty pod mechanikę sterowania Ghoulem. Dla jasności na filmiku można zobaczyć pożądane działanie (od 7minuty) https://www.youtube.com/watch?v=7ujyyqvG9_c&t=442s DK przywołuje gargulca na priesta, po czym zmienia jego target na peta huntera. 
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przyzwac Gargulca na dany cel gdy ghoul jest aktywny.
2. Użyc macro /petattack na drugi cel.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=49206
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Piootrek** [comment]
Filmik z AT to żaden dowód. Równie dobrze można iść na BT AT (o ile mają) z filmikiem z Sunwella i powiedzieć, że to u nich działa źle.

**Comment by Craackxo** [comment]
Starałem sie znalezc cos z globa ale ciezko znalezc akurat taki moment i w dodatku na patchu 3.3.5a. Czyli przyjmujemy że na AT(prawdopodobnie najpierj oskryptowanym jezeli chodzi o PvP servie jak i na ToDzie i kilku innych prywatynch serverach działalo to zle?

**Comment by Afgann** [comment]
http://wayback.archive-it.org/all/20150801232057/http://forums.elitistjerks.com/topic/71616-unholy-dps-335-king-of-anything/

"**Your Gargoyle will follow the same commands you give your Ghoul (i.e, follow, stay, attack, etc)**, so you can move it out of AoEs such as Shock Blast â€“ however you are best off simply waiting until immediately after such spells to go off to summon it. "

O ile to wystarczająco.
