### ISSUE TITLE
[Profesja] Engineering

### ISSUE THREAD

**Issue by untouched1999** [RaphaelSunwell/Sunwell-BugTracker-SCv2#566]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Recka, której nie powinno być

**Obecne działanie**: Receptura na Jeeves w Engineeringu jest możliwa do wydroppienia, a potrzebne są do tego kamyki King's Amber

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**: -

1. Zajrzeć w screena poniżej :D
2. http://imgur.com/a/hQazl
3. 

**Linki WoWHead/OpenWoW**:

1. -
2. -
3. -

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
-------------------

**Comment by KamaN442** [comment]
recka leci z mobkow a ze jest 3,3,5 to recka dropi prawidlowo a to ze nie ma epickich zoltych gemow to inna sprawa do zamkniecia
