### ISSUE TITLE
[Paladin][Spell]Beacon of Light + Judgement of Light

### ISSUE THREAD

**Issue by Quasha** [RaphaelSunwell/Sunwell-BugTracker-SCv2#568]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Beacon of Light nie powinien healować tego co uleczy nasz judgement of Light.

**Obecne działanie**: Beacon leczy target na ktorym jest beacon jeżeli ktoś zostanie uleczony z naszego judgement of the light.

**Oczekiwane działanie**: Beacon nie powinien leczyć tego co uleczy nasz Judgement of light, 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rzucić na target enemy judgement of light.
2. Rzucić na siebie beacon.
3. Ktoś INNY z party musi zostać uleczony przez judgement czyli zautoattackować target, który ma na sobie naszego Judgementa.

**Linki WoWHead/OpenWoW**:

1. http://i.imgur.com/XQB5fDQ.png (dzialanie u nas)
2. http://www.worldoflogs.com/reports/s903mn2p6414mnmg/xe/?s=5373&e=5685&x=spell+%3D+%22Beacon+of+Light%22%0D%0AOR+spell+%3D+%22Judgement+of+Light%22 (dzialanie z globala z wotlka)
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by lachapelle** [comment]
potwierdzam, logi z globa ladnie to pokazuja
