### ISSUE TITLE
Utrage Keep. Last boss używa skila z wersji normalnej.

### ISSUE THREAD

**Issue by Xanador** [RaphaelSunwell/Sunwell-BugTracker-SCv2#569]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Last boss w wersji heroicznej używa skilla z wersji normalnej.

**Obecne działanie**: 
Boss w wersji Hero: http://wotlk.openwow.com/npc=31673 używa zaklęcia z normala: http://wotlk.openwow.com/spell=42705 ( wersja normalna bossa: http://wotlk.openwow.com/npc=23954 )

**Oczekiwane działanie**: 

Boss powinien używać tylko i wyłącznie zaklęć z wersji heroicznej to jest:
http://wotlk.openwow.com/spell=59734
http://wotlk.openwow.com/spell=59706
http://wotlk.openwow.com/spell=59708
http://wotlk.openwow.com/spell=59735
To akurat działa bez zarzutów :).

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Stawić czoła ostatniemu bossowi w instancji Utrage Keep w wersji heroicznej.
2. Zobaczyć, że używa on skila z wersji normalnej: http://wotlk.openwow.com/spell=42705 

**Linki WoWHead/OpenWoW**:
1. Boss z heroicznej wersji: http://wotlk.openwow.com/npc=31673
2. Boss z wersji normalnej: http://wotlk.openwow.com/npc=23954
3. Zaklęcie, które nie powinno być używane przez bossa z hero: http://wotlk.openwow.com/spell=42705

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
XYZ

**Comment by Shon-su** [comment]
http://wowwiki.wikia.com/wiki/Ingvar_the_Plunderer

> Heroic
> 
>     Same abilities as normal
