### ISSUE TITLE
[Item]Riding Training Pamphlet

### ISSUE THREAD

**Issue by felmad** [RaphaelSunwell/Sunwell-BugTracker-SCv2#57]
**Opis**:Po wbiciu 20 poziomu, na skrzynkę pocztową przychodzi nam list z informacją o tym że można się nauczyć jeździć na wierzchowcu, jednakże nie ma w tym liście przedmiotu "Riding Training Pamphlet".

**Obecne działanie**: Wraz z listem nie otrzymujemy przedmiotu rozpoczynającego zadanie.

**Oczekiwane działanie**: Wraz z listem powinniśmy otrzymać przedmiot rozpoczynający zadanie "Learn to Ride in X" gdzie "X" oznacza miejsce lokacji startowej z której pochodzi nasza postać.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wbić 20 poziom dowolną klasą lub rasą (nie dotyczy DK),
2. Otrzymać list gdzie odsyła nas do nauki jazdy na wierzchowcu.

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Riding_Training_Pamphlet
2. http://www.wowhead.com/quest=14079/learn-to-ride-in-elwynn-forest
3. http://wotlk.openwow.com/quest=14079
4. http://wotlk.openwow.com/item=46875#objective-of

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Brak

**Comment by Mithras2801** [comment]
Tak jak podałeś linki to od 3.3 wprowadzone, ale fakt prawdopodobnie to nie działało kiedyś też.

**Comment by kovaq** [comment]
Przedawnione, server od jakiegos czasu znajduje sie na 3.3.5a
https://youtu.be/9k7psUOTE0o

**Comment by felmad** [comment]
Skoro powyższy item jest zaimplementowany, to czy postaci które nabiły już 20 lvl i wyżej będą miały możliwość otrzymania tego quest itema?
