### ISSUE TITLE
[Spell] Counterspell Mage

### ISSUE THREAD

**Issue by Verthe** [RaphaelSunwell/Sunwell-BugTracker-SCv2#570]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: (osobiscnie nie sprawdzalem tego spella , dodaje temat na prośbę shd )

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Na serwie działa to tak, że odbijany jest we mnie (maga) silence. Co nie powinno mieć miejsca.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Counterspell Maga wrzucany na reflect Warriora powinien zlikwidować reflect o ile nie było resista.Reflect znika, warrior nie ma silenca, ja też nie mam. Tak to powinno działać.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=2139/counterspell
2. http://wotlk.openwow.com/spell=65790
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Baggedmilk** [comment]
nie wiem czy sprawdzales swoje informacje w internetach, ale znalazlem cos takiego
http://www.arenajunkies.com/topic/128917-mage-spell-reflect-tips-3/
Zakladam, ze masz talent imp. counterspell.

**Comment by ThePuppetMaster** [comment]
1. Counterspell może być odbity, chyba, że masz dane talenty w Imp. Counterspell, czego nie opisałeś w zgłoszeniu.
