### ISSUE TITLE
[NPC][Pit Commander] Stoi w złym miejscu

### ISSUE THREAD

**Issue by DinozaurWKamizelce** [RaphaelSunwell/Sunwell-BugTracker-SCv2#571]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: NPC stoi w złym miejscu przez co uniemożliwia zrobienie chaina na niszczenie portali

**Obecne działanie**: NPC stoi w złym miejscu

**Oczekiwane działanie**: NPC powinien stać w innym miejscu (84.6, 50.2)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przejść się do Hellfire
2. 
3. 

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/npc=18945/pit-commander
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Prawidłowa 84.6, 50.2
Aktualna 71.5, 55.2

**Comment by Vaelevian** [comment]
Wszystko działa prawidłowo. Pit Commander jest głównodowodzącym eventem na zniszczenie Dark Portalu. W przypadku, kiedy zginie odradza się On w jednym z kilku respawn pointów i prowadzi swoją armię do podboju Dark Portalu. Pozycja, którą podajesz ewidentnie wskazuje na początek jego ścieżki. ;)

**Comment by Shon-su** [comment]
stoi i się nie rusza. Tak mówią :)

**Comment by DinozaurWKamizelce** [comment]
Jak ostatnio patrzyłem to się już ruszył. Kilka razy się logowałem i zawsze tam stał. Po prostu miałem pecha. Po dłuższym czasie jednak sobie poszedł.

**Comment by Shon-su** [comment]
wygląda ok
