### ISSUE TITLE
[TALENT][RAID][PRIEST] Spirit of Redemption na Eye of Eternity powoduje utknięcie w środku

### ISSUE THREAD

**Issue by deltoro95** [RaphaelSunwell/Sunwell-BugTracker-SCv2#573]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Spirit of Redemption to talent, który po śmierci pozwala priestowi leczyć jeszcze przez ok 20sekund zamieniając go w anioła.

**Obecne działanie**: Po śmierci smoka na 3 fazie walki z Malygosem priest spada w odchłań. Po śmierci zmienia się w anioła. Gdy anioł zniknie nie można się releasnąć. Nie można wyjść z insty. Unstuck nie działa. Można jedynie wyjść z grupy, ale nie jest to dopuszczalne przy raidzie z PUGiem czy po śmierci bossa będąc master lootem.

**Oczekiwane działanie**: Po śmierci powinno dać się kliknąć "release spirit".

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Być priestem w holy z aktywnym talentem Spirit of Redemption.
2. Umrzeć na 3 fazie walki z Malygosem, podczas bicia go na smokach.
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by lachapelle** [comment]
Potwierdzam, tez mi sie to przytrafilo i mialem problem z wyjsciem/wstanie/resnieciem.

**Comment by Vaelevian** [comment]
Problem został naprawiony. Fix zostanie wgrany z najbliższym update.
