### ISSUE TITLE
[DRUID][SPELL]

### ISSUE THREAD

**Issue by Sh4dowson** [RaphaelSunwell/Sunwell-BugTracker-SCv2#575]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:[DRUID][SPELL]

**Obecne działanie**: spell druida swipe (bear) nie skaluje się z statystyka atack power, zadaje tylko podstawowe obrażenia ( w "rank1" wynoszą one 10) 

**Oczekiwane działanie**: spell druida swipe (bear) powinien skalować się ze statystyką atack power posiadana przez postać tj. podstawowa wartość + mele atack power w formie bear form

**Co należy zrobić, aby odtworzyć ten błąd**:

1. zaatakować moba będąc  w bear form i użyć skilla 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=779
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Swipe działa poprawnie, tj. skaluje się z attack power. Testowane na druidzie z 80 poziomem w 3 próbach. Pierwsza próba z pełnym ekwipunkiem - swipe hit 256/crit 540-560. Druga próba bez ekwipunku - swipe hit 101/crit 202-241. Trzecia próba z założonym staffem - swipe hit - 206/crit 374-401.
