### ISSUE TITLE
[NPC][Storm Peaks] Brak przypisanego lootu

### ISSUE THREAD

**Issue by Rosenkrantz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#577]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wszystkie mobki w obszarze daily questów dla Sons of Hodir nie mają zwykłego lootu albo mają absurdalnie niską szansę na drop czegokolwiek.

**Obecne działanie**: Po zabiciu wyszczególnione mobki nie mają dropu innego niż ewentualne quest itemy

**Oczekiwane działanie**: Po zabiciu wyszczególnione mobki mają normalny drop na mięso, clothy, pieniądze itp itd, zgodnie z własną tabelą lootu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabijać NPC z listy poniżej.

**Linki WoWHead/OpenWoW**: Poniżej lista NPC. Ravenous Jormungar i Seething Revenant mają więcej niż jedno ID - prawdopodobnie w różnych fazach. Jestem 100% pewien tylko wersji w końcowej fazie (ukończony quest chain; w trakcie robienia jakoś nie zwróciłem szczególnie uwagi).

1a. http://www.wowhead.com/npc=29605/ravenous-jormungar#drops
1b. http://www.wowhead.com/npc=30291/ravenous-jormungar#drops
2. http://www.wowhead.com/npc=30325/viscous-oil#drops
3. http://www.wowhead.com/npc=30222/stormforged-infiltrator#drops
4. http://www.wowhead.com/npc=30260/stoic-mammoth#drops
5. http://www.wowhead.com/npc=30422/roaming-jormungar#drops
6. http://www.wowhead.com/npc=30135/restless-frostborn-warrior#drops
7. http://www.wowhead.com/npc=29974/niffelem-forefather#drops
8. http://www.wowhead.com/npc=30160/brittle-revenant#drops
9a. http://www.wowhead.com/npc=29504/seething-revenant#drops
9b. http://www.wowhead.com/npc=30387/seething-revenant#drops
9c. http://www.wowhead.com/npc=30120/seething-revenant#drops

**Comment by Shon-su** [comment]
poprawione
