### ISSUE TITLE
Problem z itemami z bosa Mal'Gamis instancja the Culling of Stratholme,

### ISSUE THREAD

**Issue by saper305** [RaphaelSunwell/Sunwell-BugTracker-SCv2#578]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po zabiciu bosa Mal'Gamis instancja the Culling of Stratholme, heroic, pomimo needowania itemów nie następuje losowanie i loot nie jest dzielony. 

**Obecne działanie**: J.w. 28/01/2017 godz, 10:45 bezpośrednio po zabiciu bosa Mal'Gamis instancja the Culling of Stratholme, poziom trudności: Heroic. Wcześniej zaobserwowalem to raz na poziomie normal.
**Oczekiwane działanie**: Po zabiciu bosa Mal'Gamis instancja the Culling of Stratholme, po wybraniu need na itemie, powinien on zostac losowany i rozdzielony.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. #
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by KamaN442** [comment]
ten sam problem ? #325

**Comment by kovaq** [comment]
Po resecie servera o godzinie 17:55, bossa zaczelismy bic :58, padl o 18. loot znikl po okolo 15 sekundach, z czego loot rozdal sie w 2 z 3 itemow (spodnie epickie mail z sp oraz frozen orb sie rozdaly, natomiast gun rare z racji, ze nie odkliknalem greed nie zdazyl.). Problemem natomiast jest fakt, ze skrzynka zawierala rowniez Q item, co powinno powodowac, ze skrzynka lezy dluzej, a nie krocej.

**Comment by dreamwalkerx1** [comment]
@Shon-su 
zrobiłem przed chwilą CoSa i problem wziąć występuje, po otworzeniu skrzynki mija 10/15 sekund i loot znika
