### ISSUE TITLE
[strona] brak możliwości głosowania na stronie sunwell.pl/vote

### ISSUE THREAD

**Issue by ohmydear123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#579]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: od około 2 dni, po wejściu na strone sunwell.pl/vote widnieje sam napis ,,remaining"

**Oczekiwane działanie**: możliwość zagłosowania/ pozostały czas do ponownego głosowania

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  bład wyskakuje tylko na koncie ,,ohmydear", na dwóch różnych komputerach więc to raczej nie wina cookies 

![nowy obraz mapy bitowej](https://cloud.githubusercontent.com/assets/25414617/22403516/c26fd5ce-e619-11e6-9941-abcaa953f5e5.jpg)

2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by DinozaurWKamizelce** [comment]
Błąd pojawia się sporadycznie na różnych kontach i ja tak miałem ze 3 dni (wcale nie z rzędu) i kolega tez.

**Comment by RewAnd** [comment]
Błąd pojawia się, gdy ktoś z twojego IP zagłosował już. Spróbuj przez proxy.
