### ISSUE TITLE
[HUNTER'S PET][SPELLS] Pet nie używa automatycznie skilli po aktywowaniu Dash

### ISSUE THREAD

**Issue by g40pwrd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#58]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Po wpisaniu w macro/aktywowaniu umiejętności Dash, pet nie używa cyklicznie zaznaczonych umiejętności Growl i Bite wcelu zbywania punktów Focus widocznych na pasku. Gdy opisywana umiejętność nie zostaje aktywowana poprzez macro bądź ręcznie, pet używa spelli bez zarzutu. Na załączonym filmiku starałem się jak najdokładniej przedstawić problem.

**Obecne działanie**: Czytaj wyżej.

**Oczekiwane działanie**: Po aktywowaniu umiejętności Dash z macro bądź ręcznie, pet powinien cyklicznie aktywować resztę zaznaczonych umiejętności.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Aktywować Dash z macro/ręcznie mając zaznaczone wybrane umiejętności aby aktywowały się automatycznie.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. Link do materiału wideo przedstawiającego występujący problem: https://www.youtube.com/watch?v=LbnxyQslDEg&t=5s
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by kovaq** [comment]
To az niepokojace, ze zaden inny hunter nie zwrocil na to uwagi.
https://youtu.be/tTiz0UZ9qf8
Pet wciaz ma ten sam problem.

**Comment by OrgiVed** [comment]
Właśnie sobie expie Huntera i właśnie zauważyłem tego buga. Wszedłem żeby zobaczyć czy coś takiego było zgłaszane i było. Problem nadal występuje.

**Comment by MonichSC** [comment]
Powinno już być naprawione, może ktoś potwierdzić?

**Comment by xsitdev** [comment]
@MonichSC Potwierdzam, działa już poprawnie.
