### ISSUE TITLE
[fix][gameobject] 17154 Nie widac znacznika quest givera (wykrzyknik)

### ISSUE THREAD

**Issue by Neos3452** [RaphaelSunwell/Sunwell-BugTracker-SCv2#580]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Obiekt czesciowo zanurzony w scianie, nie widac znacznika quest givera (wykrzynik).

**Obecne działanie**: 
<img width="638" alt="zrzut ekranu 2017-01-29 o 18 31 53" src="https://cloud.githubusercontent.com/assets/5870673/22406454/9e34f48e-e653-11e6-8891-4efce4b56864.png">

**Oczekiwane działanie**:
<img width="508" alt="zrzut ekranu 2017-01-29 o 18 42 45" src="https://cloud.githubusercontent.com/assets/5870673/22406455/a9f90dfa-e653-11e6-83a7-3d298972ef87.png">

**Co należy zrobić, aby odtworzyć ten błąd**:

1. .character level 23
2. .go object 17154
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=567/deprecated-dangerous
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
position_x=-19.483, position_y=-935.304, position_z=58.0971, map=0

**Jak naprawić:**
- .gobject move 17154 -19.6 -935.304 58.0971
    (wymagany reload clienta zeby zobaczyc efekt)
- update gameobject set position_x=-19.6, position_y=-935.304, position_z=58.0971 where guid=17154;

**Comment by Verthe** [comment]
Do porawy
