### ISSUE TITLE
Eye of Eternity 10

### ISSUE THREAD

**Issue by Argonnath** [RaphaelSunwell/Sunwell-BugTracker-SCv2#581]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Eye of Eternity

**Obecne działanie**: Problem z ostatnią fazą. Niewidoczne chmury praktycznie instantowo zabijają graczy.

**Oczekiwane działanie**: W poprzednim resecie wszystko działało ok. Bez problemu dało się przejść 3cia fazę a teraz na 10tce nagle w ciągu kilku sekund pada np. 3 graczy. I tak naprawde niewiadomo od czego w 2 sekundy masz pół życia albo i mniej.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by lachapelle** [comment]
Static Field: Creates a blue, electric-looking orb on a random target. This orb deals 9,425 to 10,575 Arcane damage per second to anyone within 30 yards of it.

**Comment by xsitdev** [comment]
Padacie od Staic Field'ów, które przedtem były zepsute, teraz po prostu zadają to co powinny.
