### ISSUE TITLE
[Quest] The Mosswalker Savior

### ISSUE THREAD

**Issue by Dragwyn** [RaphaelSunwell/Sunwell-BugTracker-SCv2#582]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zadanie polega na sprawdzeniu czy Mosswalker Victims żyją, a jeśli tak to należy ich uratować.

**Obecne działanie**: Po zakończeniu "Lifeblood of the Mosswalker Shrine" nie można wejść w interakcję z npc, co wiąże się z brakiem możliwości ukończenia zadania.

**Oczekiwane działanie**: Nawet pomimo ukończenia wyżej wspomnianego zadania interakcja z npc powinna być wciąż możliwa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zakończyć zadanie "Lifeblood of the Mosswalker Victims" jednocześnie nie kończąc zadania "The Mosswalker Savior"
2. Spróbować wejść w interakcję z leżącym na ziemi NPC.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=12579
2. http://wotlk.openwow.com/quest=12580
3. ![wowscrnshot_011817_143900](https://cloud.githubusercontent.com/assets/6939620/22409780/9d08b00a-e68f-11e6-9d9a-436799897891.jpg)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: ![wowscrnshot_013017_014835](https://cloud.githubusercontent.com/assets/6939620/22409783/aa4a0566-e68f-11e6-99f2-1e12c65a9af7.jpg)

**Comment by Shon-su** [comment]
Testowane dzisiaj, działa ok.

**Comment by Dragwyn** [comment]
U mnie dalej nie działa, przez co mam zablokowaną możliwość zdobycia reputacji u The Oracles i Frenzyheart Tribe.

**Comment by Shon-su** [comment]
:(. Mógłby ktoś jeszcze sprawdzić? Bo mi zadziałało , i w kodzie też jest ok.

**Comment by Verthe** [comment]
Robilem i dziala
