### ISSUE TITLE
[Quest(y)] Agamaggan's Agility, Agamaggan's Strength etc.

### ISSUE THREAD

**Issue by Vaarku** [RaphaelSunwell/Sunwell-BugTracker-SCv2#583]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Chodzi o serię mini-questów od NPC http://wotlk.openwow.com/npc=3430 , ten nie daje nam buffów takich jak : http://wotlk.openwow.com/spell=17013 , http://wotlk.openwow.com/quest=5042 . Questów jest kilka, jednak wszystkie pochodzą od tego samego NPC i polegają na tym samym, dlatego zgłaszam je jako jeden.

**Obecne działanie**: Wyżęj wymieniony NPC po oddaniu questa nie "rzuca" buffa na gracza, który go wykonał, mimo zabrania quest itemów.

**Oczekiwane działanie**: NPC daje jeden z buffów (lista buffów taka jak zapisana pod questami http://wotlk.openwow.com/item=5075#objective-of ) na gracza, który wykonuje zadanie, zabierając przy tym quest itemy.

**Co należy zrobić, aby odtworzyć ten błąd**: Wystarczy spróbować oddać quest.

1. Po prostu oddać questa (wymagane 4x Blood Shard http://wotlk.openwow.com/item=5075)

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=5075#objective-of (lista questów, która nie działa poprawnie)
2. http://wotlk.openwow.com/npc=3430 (NPC, który daje questy)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Niestety, nie jestem w stanie nic podać na ten moment, jednak jest to dość banalne do znalezienia, gdyż NPC stoi w prawidłowym miejscu.

**Comment by Shon-su** [comment]
poprawione
