### ISSUE TITLE
[EVENT] Lunar Festival, brak npc w Darnassus

### ISSUE THREAD

**Issue by sanctify21** [RaphaelSunwell/Sunwell-BugTracker-SCv2#585]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: W Darnassus znajduje się npc 'Lunar Festival Emissary', który daje nam questa związanego z eventem, ale akurat w Darnassus nie ma npc odpowiedzialnych za ten event, głównie chodzi o Lunar Festival Harbringer

**Oczekiwane działanie**: NPC związani z eventem powinni być w każdej stolicy 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do Darnassus i wziąć ów questa.

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=4V9HoMWn7MA 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
![](http://i.imgur.com/M1e4nqD.png)

**Comment by Shon-su** [comment]
testowane na testowym, jest ok
