### ISSUE TITLE
[QUEST] Kindness ID 10804

### ISSUE THREAD

**Issue by PowerKeeper666** [RaphaelSunwell/Sunwell-BugTracker-SCv2#587]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Pojawił sie problem z w/w questem otwierającym chain dla reputacji Netherwing. Wykonanie go w sensownym przedziale czasowym nadal jest możliwe, jednak wymaga to pewnego zorientowania.

**Obecne działanie**: smoki po nakarmieniu nie odlatują, ale zostają na ziemi, co więcej po utraceniu buffa, można je ponownie nakarmić. Smoków będących w powietrzu za to ani razu nie udało mi się nakarmić, skutkowało to zmarnowaniem części mięsa.

**Oczekiwane działanie**: nakarmione smoki powinny odlatywać z powrotem w powietrze, ponadto smoki latające ponad ziemią powinno dać sie nakarmić.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wymagany level 70
2. wziąć questa u NPC Mordenai ID 22113
3. wydropić Rocknail Flayer Carcass ID 31372

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10804/kindness
2. http://www.wowhead.com/npc=22113/mordenai
3. http://www.wowhead.com/item=31372/rocknail-flayer-carcass

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione
