### ISSUE TITLE
[DUNGEON] STORMWIND STOCKADE rip loot na bossach

### ISSUE THREAD

**Issue by SebastiF** [RaphaelSunwell/Sunwell-BugTracker-SCv2#588]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Rip loot na bossach

**Obecne działanie**: Nic nie leci z bossow na tej inscie,prócz q itemow

**Oczekiwane działanie**: Loot z bossow

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabić bossa na stockade
2. zobaczyc loot
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by mistillate** [comment]
Potwierdzam, wczoraj również mi nic nie poleciało

**Comment by Shon-su** [comment]
http://wow.gamepedia.com/Stormwind_Stockade_loot_(original)

Loot jest taki jak tutaj. Niestety z tego co można przeczytać na wowheadzie za dużo tam nie leciało przed przerobieniem insty na cata. Szansa na staff jest mała, ale np. Bruegal Ironknuckle dropi dość regularnie rzeczy.
