### ISSUE TITLE
[PROFFESION] FISHING

### ISSUE THREAD

**Issue by SebastiF** [RaphaelSunwell/Sunwell-BugTracker-SCv2#589]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Problem z rzucaniem wędką z np. molo ,albo mostów

**Obecne działanie**: Nie można użyć wędki z mostów albo molo ,tylko trzeba stać zaraz nad wodą co utrudnia wydobywanie ryb z ławic

**Oczekiwane działanie**: Możność rzucania wędki z większej odległości jak np.mosty

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ustać na moście
2. Użyć fishingu
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by DinozaurWKamizelce** [comment]
Chodzi raczej o sprawdzanie odległości w osi Z. Nie możemy stać nad wodą nawet niewielka różnica wysokości skutkuje tym, że nie da się łowić. Musimy stać praktycznie w wodzie...

**Comment by Neos3452** [comment]
Wydaje się, że to jakaś customowa modyfikacja u nas na serwerze. Na oryginalnym sunwellcore mozna lowic nawet bedac kilometr nad woda. U nas to sa 3 jednoski. Testowane w undercity:
LiquidLevel:-64.478561
Z: -61.530220 - moge lowic
Z: -61.472969 - nie moge

Strzelam, ze w Spell::SelectImplicitCasterDestTargets jest jakis ekstra if. Nie ma go u mnie, ale raczej zamiast < 3.f, powinno byc cos w tym stylu:

```C++
Position casterPos;
m_caster->GetPosition(& casterPos);
if (casterPos.GetExactDistSq(x, y, liquidLevel) > 2*max_dis*max_dis)
{
    SendCastResult(SPELL_FAILED_NOT_HERE);
    SendChannelUpdate(0);
    finish(false);
    return;
}
```

2*max_dis*max_dis spowoduje ze bedziemy mogli lowic troche dalej niz jest w zasieg czaru. Tj. jak sie wylosuje ze rzucamy na maksymalna odleglosc i woda jest duzo nizej od nas, ale coz, IMO lepiej tak, niż jakby raz bylo ze mozemy, a raz ze nie mozemy. Zreszta to tylko fishing...

**Comment by xsitdev** [comment]
Błąd był w innym pliku, ale zmiana wymagała również tutaj.
