### ISSUE TITLE
[QUEST] The Bloodsail Buccaners

### ISSUE THREAD

**Issue by zasmazka11** [RaphaelSunwell/Sunwell-BugTracker-SCv2#59]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest item mianowicie Bloodsail Charts ma respawn około 20-30 minut, zostało to przetestowane wraz z Gm Snake i skierowane tutaj

**Obecne działanie**: Za długi respawn

**Oczekiwane działanie**: Respawn z czasem takim jak Bloodsail Orders

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Poczekać na respawn
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://db.vanillagaming.org/?quest=604
2. http://db.vanillagaming.org/?item=3920
3. http://www.wowhead.com/item=3920/bloodsail-charts

**Lokalizacja z koordynatów GPS (27.2, 82.7, Strangethorn Vale)**:

**Comment by sz4t4n** [comment]
Respawn Bloodsail Charts - (item-3920) faktycznie długi. Mi pojawił się po 10 minutach. Ale jest często dłuższy.

**Comment by Shon-su** [comment]
done
