### ISSUE TITLE
[SPELL]Pursuit of Justice,On a Pale Horse

### ISSUE THREAD

**Issue by Scythe-Kosiarz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#590]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Niestety zaden pal/dk nie chcieli do tej pory sie przyznac ze talenty daja im 2x tyle bonus speed.

**Obecne działanie**:  Bonus  z talentow jest podwojny

**Oczekiwane działanie**:  Odpowiedni speed dla danej klasy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Sprawdzic predkosc postaci ktora ma odpowiednie  talenty.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/On_a_Pale_Horse
2. http://wowwiki.wikia.com/wiki/Pursuit_of_Justice
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Quasha** [comment]
Nie jest podwójny, działa dobrze na mouncie mamy + 100% czyli razem 200% z aura daje nam to +240%, spell działa poprawnie.

**Comment by Quasha** [comment]
Na mouncie +60% powiesz, że talent działą 1,6x lepiej ?  BO wtedy mamy + 192% ms?

**Comment by Scythe-Kosiarz** [comment]
U paladyna na mouncie 100% bez aury (najwazniejszy punkt programu) speed wynosi 130% zamiast 115%

**Comment by Quasha** [comment]
BO talent daje 15% czyli jak masz + 100% i masz 200%ms na mouncie to masz 230%...

**Comment by Scythe-Kosiarz** [comment]
Powiem tak. TESTOWANE NA PALADYNIE
Carbonite pokazuje 0% speed bez mounta. 
z 100% mountem pokazuje 100% speed.
 jak dam talenty to pokazuje 130%

Tyle w temacie
