### ISSUE TITLE
[QUEST] The Killing Time

### ISSUE THREAD

**Issue by nerthe** [RaphaelSunwell/Sunwell-BugTracker-SCv2#592]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Druga część chaina już po animacji pod Angrathar. Problem z teleportem do miejsca wykonania questa. Po otrzymaniu questa od King Varian Wrynn powinno porozmawiać się z Jaina Proudmoore, aby otworzyła portal do miejsca wykonania questa(prawdopodobnie jakiś phase pod UC).

**Obecne działanie**: Po otrzymaniu questa od King Varian Wrynn, Jaina nie otwiera portalu ani proponuje opcji jego otworzenia.

**Oczekiwane działanie**: Jaina powinna otwierać portal na żądanie, tak jak w poprzednim queście z chaina.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ukończyć chain prowadzący do animacji pod Angratharem.
2. Rozpocząć drugi 5 questowy chain, który zaczynamy u smoka pojawiającego się po animacji.
3. Po powrocie z Orgrimmaru i ukończeniu questa [3] A Royal Coup wziąć następny - [4] The Killing Time.

http://i.imgur.com/4PzwHGE.jpg
http://i.imgur.com/3u9Ndhm.jpg

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13371/the-killing-time
2. http://wotlk.openwow.com/quest=13371
3. Pełen chain: http://wowwiki.wikia.com/wiki/Quest:The_Killing_Time

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/4dEc4kS.jpg

**Comment by nerthe** [comment]
Update ze screenami okien rozmowy z Varianem podczas brania Questu i z Jaina po wzięciu Questu + .npc info Jainy i GPS.

**Comment by Shon-su** [comment]
portal dorzucony natomiast bitwa i tak nie jest jeszcze oskryptowana
