### ISSUE TITLE
[RAID] [OBSIDIAN SANCTUM] Gift of Twilight

### ISSUE THREAD

**Issue by Quasha** [RaphaelSunwell/Sunwell-BugTracker-SCv2#593]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Shadron daje bańke na Sarthariona po pewnym czasie, która daje immune na WSZYSTKIE obrażenia.

**Obecne działanie**: U nas obecnie immune jest TYLKO NA MEELE HITY. Nie wime jak to działa na samego shadrona jak się zbija smoki robiąc na mniej niż 3d.

**Oczekiwane działanie**: Powinien dawać immune na WSZYSTKIE obrażenia.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pullnąć Sarthariona, z żywym Shadronem.
2. Poczekać na bańke na Shadrona.
3. Bić bossa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=58766/gift-of-twilight (Reduces damage taken by 100%)
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Opisany problem został naprawiony. Poprawka zostanie wgrana z najbliższym update.
