### ISSUE TITLE
[Mage][Talent] Clearcasting + Missile Barrage

### ISSUE THREAD

**Issue by Rosenkrantz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#594]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Efekty wymienione w tytule są zużywane łącznie, co nie powinno mieć miejsca, widać w patch notes: http://wowwiki.wikia.com/wiki/Patch_3.2.2 , ctrl+F missiles. 

O ile mi wiadomo, pod względem mechanik obowiązuje nas patch 3.3.5, więc jest to bug.

**Obecne działanie**: Mając jednocześnie Clearcasting + Missile Barrage, użycie Arcane Missiles powoduje zużycie obu buffów.

**Oczekiwane działanie**: Mając jednocześnie Clearcasting + Missile Barrage, uzycie Arcane Missiles powoduje zużycie wyłącznie Missile Barrage.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rozłożyć talenty tak, aby mieć do dyspozycji oba efekty
2. Rzucać zaklęcia włączające oba proce do momentu uzyskania obu buffów
3. Użyć Arcane Missiles, stuprocentowa powtarzalność.

**Linki WoWHead/OpenWoW**:

1. aura MB: http://wotlk.openwow.com/spell=44401
2. aura Clearcasting: http://wotlk.openwow.com/spell=12536

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: nie dotyczy

**Comment by DinozaurWKamizelce** [comment]
Nie grałem magiem jakies 2 tygodnie, ale jak ostatnio grałem użycie AM zużywało tylko jeden buff (MB)

**Comment by Rosenkrantz** [comment]
Eh, fck, tak się kończy pisanie zgłoszeń z pamięci. Z jakiegoś powodu byłem przekonany, że działa źle. Ten proc maga działa dobrze, inny nie :x zamknąć i zapomnieć, pardon za zamieszanie.
