### ISSUE TITLE
[NPC] Crazed Water Spiryt nie mogą się ruszać

### ISSUE THREAD

**Issue by DinozaurWKamizelce** [RaphaelSunwell/Sunwell-BugTracker-SCv2#596]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Większość mobów (nie wszystkie) stoją w miejscu i nie mogą się ruszać. Jeśli zaatakujemy je z dystansu nie mogą nam oddać i wychodzą z walki, więc musimy podejść na [meele range]. 
Wydaje mi się, że większość tych, które są na ziemi działa poprawnie a te które są w wodzie nie mogą się ruszać, tak jakby był problem z ich ruszaniem się po wodzie (płytkiej)

**Obecne działanie**: Większość NPC nie może się ruszać

**Oczekiwane działanie**: moby powinny móc do nas podejść i nas zaatakować

**Co należy zrobić, aby odtworzyć ten błąd**:

Pójść do lokacji (koordy z .gps na zdjęciu)
http://imagizer.imageshack.us/v2/xq90/923/c90Mgw.png

PS: jakieś dziwne te koordy

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=16570
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Verthe** [comment]
do poprawy

**Comment by DinozaurWKamizelce** [comment]
Ale co do poprawy? Kod w grze? Zgłoszenie?

**Comment by Verthe** [comment]
zgłoszenie jest ok :D moby sa do poprawy , nie patrz na to co pisze ja sam dla sb to robie

**Comment by DinozaurWKamizelce** [comment]
Dziś zauważyłem jeszcze, że ten sam problem jest z żywiołakami powietrza w Wintergrasp. Jutro poszukam linku do nich.

**Comment by Shon-su** [comment]
poprawione, nie dograne
