### ISSUE TITLE
[NPC] Sapphiron - Visual

### ISSUE THREAD

**Issue by Kokaina** [RaphaelSunwell/Sunwell-BugTracker-SCv2#597]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: O ile samo działanie mechaniki Sapphirona [id=15989] jest bez zarzutu, o tyle występuje mały visual samego bossa jeśli będzie wipe na phase 2. Wówczas po powrocie do komnaty ze smokiem, boss dalej wisi w powietrzu gdy powinien stać na ziemi.

**Obecne działanie**: j/w

**Oczekiwane działanie**: Smok po każdym wipie powinien stać na ziemi zamiast wisieć w powietrzu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zwipować podczas phase 2. 

**Linki WoWHead/OpenWoW**:

1. Niepotrzebne

Screen: 
https://s24.postimg.org/9qd76x4ed/Wo_WScrn_Shot_020117_220843.jpg

**Comment by Verthe** [comment]
Do poprawy + tomby

**Comment by Kokaina** [comment]
^Visual Tombów gdy ktoś dostanie w biegu, faktycznie :)

**Comment by Quasha** [comment]
Tomby Zostają po wipe i to nie tylko Wizualnie.
