### ISSUE TITLE
[NPC] Noth the Plaguebringer - Corpse

### ISSUE THREAD

**Issue by Kokaina** [RaphaelSunwell/Sunwell-BugTracker-SCv2#598]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mechanika bossa działa poprawnie. Te zgłoszenie jest raczej sugestią niż znalezieniem błędu nie mniej prosiłbym o przeczytanie!

**Obecne działanie**: Noth the Plaguebringer [id=24581] może zostać obecnie zabity na balkonie poprzez pozostawione na nim doty. Wówczas niemożliwym jest aby podnieść z niego loot (była już interwencja GMa w takim przypadku) - identyczne przypadki były na globalu (https://s24.postimg.org/yfpcxu4gl/hehe.jpg). Stąd moja propozycja aby zawsze po śmierci Notha, jego ciało wracało do raidu na parter. 

**Oczekiwane działanie**: Jeśli bylibyście przychylni mojej prośbie, która nie jest rzekomo naprawieniem bugu ale jednocześnie uprości życie graczom jak i GMom, wówczas oczekiwanym działaniem aby po śmierci Notha, jego ciało pojawiało się na parterze zamiast na balkonie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabić Notha na balkonie.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=15954/noth-the-plaguebringer#comments
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://s28.postimg.org/mieutirod/Wo_WScrn_Shot_020217_142733.jpg

**Comment by Vaelevian** [comment]
Sugestia została wzięta pod uwagę i wgraliśmy na niego poprawkę. Zostanie wgrane z najbliższym update.
