### ISSUE TITLE
[SPELL][PALADIN] Consecration 

### ISSUE THREAD

**Issue by Trzyememce** [RaphaelSunwell/Sunwell-BugTracker-SCv2#6]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Spell "Consecration"u klasy Paladyn nie powinien zadawać obrażeń wszelkim totemom.

**Obecne działanie**: Zadaje obrażenia.

**Oczekiwane działanie**: Nie powinien zadawać obrażeń.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wyłączyć wszelkie aoe aury
2. Poczekać aż przykładowy mob przyzwie totem
3. Użyć Consecration

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 
![wowscrnshot_111916_095147](https://cloud.githubusercontent.com/assets/23569717/20454357/0975a1aa-ae3f-11e6-8b4b-f595a45d3b22.jpg)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by myentos** [comment]
Sprawdziłem to właśnie na graczach oraz na mobkach i działa jak należy. Dowód: [http://i.imgur.com/sIbp7p2.jpg](http://i.imgur.com/sIbp7p2.jpg)
