### ISSUE TITLE
[ITEM]Amulet of the Moon

### ISSUE THREAD

**Issue by zasmazka11** [RaphaelSunwell/Sunwell-BugTracker-SCv2#60]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie można go sprzedać na AH

**Obecne działanie**: Item dopiero co zrobiony przez JC nie może zostać wystawiony na AH

**Oczekiwane działanie**: Możliwość wystawienia go na AH

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Stworzyć item (craf)
2. Spróbować go wystawić
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=20854/design-amulet-of-the-moon
2. 
3.

**Comment by kovaq** [comment]
Problem lezy w ladunkach uzycia.
Fabrycznie nowy neck uznawany jest domyslnie za uzyty.
https://youtu.be/RkEiIPqTpC4

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane dzisiaj (tj. 27.01) około 6 rano.
