### ISSUE TITLE
[Mage][Spell] Blink

### ISSUE THREAD

**Issue by Rosenkrantz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#604]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Blink pozwala na wspinaczki wysokogórskie, że tak to ujmę. Ogólnie ma coś pewnie skopane z uwzględnianiem wysokości w zasięgu teleportacji.

**Obecne działanie**: Używając blink przed stromą ścianą (na przykład na dole klifu przed bazą Lumber Mill na Arathi Basin) można dostać się na sam szczyt. Nie sprawdziłem tego jeszcze w innych miejscach, ale to jedno nie pozostawia wątpliwości, że coś jest zdecydowanie nie tak.

**Oczekiwane działanie**: Używając blink przed stromą ścianą, mag powinien po prostu zatrzymać się na niej, na tym samym poziomie, z którego zaczął. 

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Znaleźć odpowiednie miejsce.
2. Stanąć przy samej ścianie wysokiego klifu.
3. Użyć blink, patrząc w kierunku ściany.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=1953

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by DinozaurWKamizelce** [comment]
Wydaje mi się, że jest to problem dotyczący lokacji w BG.
Ogólnie blink działa tak jak należy, a nawet za bardzo - jak jest lekko pod górkę lub z górki, (tak że spokojnie można by przebiec) to już nas zatrzyma tym bardziej na ścianach. Ale faktycznie na LM w AB można w ten sposób się wspiąć. Wszakże nigdy nie próbowałem z dołu, ale jak mnie szaman zrzucił to szybko mogłem wrócić w locie.

**Comment by Rosenkrantz** [comment]
W tej chwili się blinkuję po sholazarze, na klify z krateru w centrum też można tak wchodzić.

**Comment by DinozaurWKamizelce** [comment]
No to faktycznie coś jest nie tak, bo tak jak pisałem, zatrzymuje się tam gdzie możemy wejść, a teleportuje tam gdzie nie możemy wejść...

**Comment by leman1991** [comment]
Kolejny przyklad - dismount na duzej wysokości - uzycie blinka teleportuje do powierzchni ziemi. Testowane wyskakujac z dalaranu :3

**Comment by slabymag** [comment]
Na wsg na plaszczyznie nad tunelem po uzyciu blinka teleportuje cie na dol. Przy klodzie z lewej strony mapy po uzyciu blinka wrzuca w przepasc bez txt. W przypadku uzycia przed graveyardem teleportuje na gore.

**Comment by slabymag** [comment]
WSG: Schodząc tunelem po użyciu blinka przenosi na niewidzialna teksture nad nim. Po zejsciu na sam dol gracz spada z powrotem do tunelu.

**Comment by Baggedmilk** [comment]
za to teraz nawet jak uzyjesz blinka na plaskiej powierzchnii to pojawiasz sie troszke nad ziemia przez co tracisz czas na spadniecie
