### ISSUE TITLE
[COMBAT BUG] Jedzenie maga

### ISSUE THREAD

**Issue by podludek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#605]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Dotyczy aren. Niepoprawne pojawianie się combatu w przypadku warlocka z petem. Combat blokuje regeneracje życia jedzeniem maga.

**Obecne działanie**: W przypadku kiedy zacznę jeść jedzenie od maga i zostanie wbity combat (na pecie) regeneracja hp zostaje wstrzymana.

**Oczekiwane działanie**: Jedzenie maga powinno regenerować hp za każdym razem w trakccie konsumpcji

**Co należy zrobić, aby odtworzyć ten błąd**: 

1.  Zacząć jeść magowe struggle
2.  Wbić combat bez zadania obrażeń warlockowi (atak na peta)
3.  

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by DinozaurWKamizelce** [comment]
Jedzenie zwiększa szybkość regeneracji many i życia. Jak wiadomo w walce życie się nie regeneruje (troll ma chyba 10% regeneracji) Jeśli masz combat to nie ważne co jesz, życie nie powinno się regenerować. Inną sprawą jest czy w pvp powinieneś mieć combat jak atakują tylko Twojego peta.

**Comment by podludek** [comment]
Podążając taką logiką Enraged Regeneration warriora nie powinien działać w walce. Nie potrafię znaleźć konkretnej analizy z globa, bo sprawa wymaga lepszego zagłębienia się w detale, które w googlu umarły już kilka lat temu wraz z nowymi patchami. Z doświadczenia mogę powiedzieć, że zarówno na globie, starym sunwellu jak i arena tournament rozpoczęcie jedzenia przez maga / partnera powodowało regeneracje i many i hp tak długo jak gracz jadł.

**Comment by Danieloses** [comment]
Potwierdzam, przy rozpoczęciu jedzenia i uzyskaniu combatu jedzenie nie powinno zostać przerwane i powinno nas dalej leczyć.

Jeden ze starszych tricków frost magów, owca > blink away > summon water elemental > zaczynasz jeść bez combatu > Freeze peta na poly > jesz sobie w spokoju, a przeciwnikowi wychodzą oczy ze złości
