### ISSUE TITLE
[COMBAT BUG] Nieprawidłowe wbijanie combat na pecie

### ISSUE THREAD

**Issue by podludek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#606]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Dotyczy aren. Warlockowy pet bity hen daleko powoduje wbijanie combatu warlockowi.

**Obecne działanie**: Combat na warlocku zostaje wbity, kiedy pet zostaje zaatakowany, nawet bardzo daleko od warlocka.

**Oczekiwane działanie**: Combat na warlocku powinien być wbijany w momencie podjęcia przez niego akcji (np rozkaz seduction) albo w przypadku otrzymania obrażeń lub innych (mass dispell priesta)

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wysłać peta daleko od warlocka i pozwolić na jego atak przez przeciwnika
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Baggedmilk** [comment]
a ja uwazam, ze powinien combat byc wbijany zawsze jak pet ma combat.
zero dowodow

**Comment by Danieloses** [comment]
A ja mam wrażenie, że komentujący tu nigdy w wowa nie grali, od zawsze było coś takiego jak fake combat, fake combat jest wbity jak, np. wyślesz peta do ataku. Sama nazwa mówi, że jest to tylko pozorny combat, gdy ma go przeciwnik na sobie można normalnie używac skilli takich jak sap.

**Comment by Baggedmilk** [comment]
tak jak autor tego zgloszenia wyrazilem swoje zdanie niepoparte zadnymi dowodami
