### ISSUE TITLE
[Exploracja UC]

### ISSUE THREAD

**Issue by Vicazen** [RaphaelSunwell/Sunwell-BugTracker-SCv2#607]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Wchodząc do UC nie odkrywa mi Achievmenta Exploration Trifistal Glades, poniewaz to ostatnia lokacja do odkrycia.

**Oczekiwane działanie**: Wchodząc do UC powinno odkryc mi Achievmenta Exploration Trifistal Glades.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Verthe** [comment]
Dodaj jakis screenshot , z tego co wiem to achi dziala bo nie jedna osoba juz go zrobila

**Comment by Piootrek** [comment]
Działa. Explorer buguje się na pojedynczych postaciach w losowych miejscach. Poproś GMa w tickecie o .achievement checkall. Zresztą jeśli dobrze pamiętam to Tobie już pomogłem.
