### ISSUE TITLE
The Darkmoon Faire

### ISSUE THREAD

**Issue by Impactorowy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#608]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak aktywnego The Darkmoon Faire.
**Obecne działanie**: Według internetu Darkmoon Faire festival powinien być teraz. Niestety nie ma go w żadnej lokacji.

**Oczekiwane działanie**: Aktywowanie Darkmoon Festivalu.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Piootrek** [comment]
Już jest.
