### ISSUE TITLE
Znikający Pet huntera

### ISSUE THREAD

**Issue by modzel1993** [RaphaelSunwell/Sunwell-BugTracker-SCv2#61]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Problem z paskiem ktory odpowiada za skille peta

**Obecne działanie**: Raz na jakis czas znika pasek kontroli peta,skilli i trzeba robic relog

**Oczekiwane działanie**: Nie powinno wgl znikac jak pet jest

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. NIE DOTYCZY
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. NIE DOTYCZY
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by valcy** [comment]
Problem ktory przewijal sie rowniez przez globa - o ile dalej nie wystepuje.
To moze miec zwiazek z addonami, zwykle wystepuje po reloadzie. Dismiss peta i przywolanie go ponownie rozwiazuje problem.

**Comment by ThePuppetMaster** [comment]
Nie byłem w stanie odtworzyć błędu. (Brak addonów)
