### ISSUE TITLE
[WARLOCK][SPELL][INFERNO][PET] Haste nie wpływa na szybkość casta.

### ISSUE THREAD

**Issue by PawloNazaruk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#610]
[//]: # (****************************************************************)
[//]: # (****)
[//]: # (****************************************************************)

**Spell ma stałe 1.5 sec czarowania. Dodatkowy Haste z postaci nie ma wpływu na przyspieszenie casotowania spella, mimo że w gui czas się aktualizuje. Ekstra info na screenach.**:

**Obecne działanie**:  Haste nie ma wpływu na szybkość castowania [INFERNO].

**Oczekiwane działanie**: Jakikolwiek Haste powinien przyspieszać cast [INFERNO].

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Posiadanie warlocka z minimum 55lev.
2. Zrobienie quest chaina na peta Inferno (Link 2)(http://wowwiki.wikia.com/wiki/Quest:What_Niby_Commands))
3. Zaopatrzenie się w [Infernal Stone] u sklepikarza z reagentami.
4. Podbijaj Haste itemkami/spell stonem lub jakimkolwiek buffem.
4. Użycie spella Inferno jest w zakładce Demonology.
5. Observe the issue.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=1122
2. http://wowwiki.wikia.com/wiki/Quest:What_Niby_Commands
3. http://imgur.com/a/LDYT8

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
N/A

**Comment by valcy** [comment]
Jakies potwierdzenie ze powinno sie skalowac ? ;p

**Comment by PawloNazaruk** [comment]
Cast time reszty petów lockow jest skracany prawidłowo z hastem postaci. Nawet przy summowaniu doom guarda to działa. W interfejsie widać że cast time Infernusa jest skrócony na 1.22sec, a rzuca się go w 1.5sec. 

Mam jakiś biedo filmik, z tamtego okresu. Dokładnego casta się nie zobaczy ale w interejsie też ma skrócny.
https://youtu.be/4R8j-IUuk50?t=1m51s
