### ISSUE TITLE
Warlock quest na sucubusa part 2 

### ISSUE THREAD

**Issue by dac777** [RaphaelSunwell/Sunwell-BugTracker-SCv2#611]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Robimy quest na Sucuba u warlocka, więc zabieramy się za to w Silvermoon city biorąc tego o to questa:
"http://wowwiki.wikia.com/wiki/Quest:Carendin_Summons" oddajemy go w UC, gdzie od tego samego npca powinniśmy dostać part drugi czyli http://wowwiki.wikia.com/wiki/Quest:Devourer_of_Souls_(Undercity) niestety nie dostajemy go.
**Obecne działanie**: jak wyżej

**Oczekiwane działanie**: no cóż powinien dawać questa.

**Co należy zrobić, aby odtworzyć ten błąd**:
P.S. jest jeszcze jeden mały bug u locka, warty zaglądnięcia bo naprawa nie potrwa długo jeśli warlock robi healthstone na 80 to kamień leczy za 4,2k hp, jeśli ma dane talenty to leczy za 5,1k. Jeśli zrobie sobie sam healthstone jest spoko leczy 5,1k, jeśli natomiast postawie kibel i zrobie hsy dla całego rajdu to wtedy leczą one po 4,2k pomimo rozdanych talentów, w takiej konfiguracji same talenty po prostu nie przydają sie na rajdach.

Pozdrawiam Łysynakoxie
1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Piootrek** [comment]
Quest dziala na 100%. Pewnie go zrobiles i zgubiles sie w chaine, napisz ticket to Ci pomoge.

**Comment by ThePuppetMaster** [comment]
Quest działa.
