### ISSUE TITLE
[hunter][spell] readiness

### ISSUE THREAD

**Issue by dathremar** [RaphaelSunwell/Sunwell-BugTracker-SCv2#612]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: nie mozna uzyc readinessa podczas global cooldownu, readiness wywołuje global cooldown, readiness nie resetuje global cooldownu

**Oczekiwane działanie**: 
Readiness powinien byc "off GCD" - powinno sie moc go uzywac podczas trwania GCD, sam nie powinien wywolywac tego efektu, powinien tez resetowac jakikolwiek GCD powstaly przed jego wycastowaniem
https://www.warcraftmovies.com/movieview.php?id=164633 - okolo 4:28 widac doskonale poprawne dzialanie readinessa - hunter uzywa chimera shot+silencing shot, nastepne readiness i kolejna chimera - wszystko odbywa sie w okolo pol sekundy., podobna sytuacja w tym samym filmiku okolo 6:27
https://www.warcraftmovies.com/movieview.php?id=163895 - 2:11 
**Co należy zrobić, aby odtworzyć ten błąd**:

1.  uzyc jakiejs umiejetnosci huntera np freezing arrow albo aimed shot (tylko silencing shot i kill command nie wywoluja GCD)
2. uzyc readiness jak najszybciej 
3. powtorzyc pkt.1 jak najszybciej
4. cala operacja normalnie nie powinna zajac wiecej niz 0,5 sekundy, na sunku beda to minimum 3sekundy (pkt1 - 1,5sec gcd - pkt2 - 1,5sec gcd - pkt3) przez co najsilniejszy spell huntera jest w zasadzie useless ;f
**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=23989
2. http://www.wowhead.com/spell=23989
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by valcy** [comment]
Nie wiem co na tych linkach masz bo nagrania sie nie odpalaja ale readiness dziala prawidlowo.

**Comment by Crackaw** [comment]
To co zauważyłeś to po prostu brak cd na silencing shot użyty zaraz po readiness, a na  tym filmiku, jak i innych dobrze jest pokazany gcd na readiness i spell działa dobrze.
