### ISSUE TITLE
[QUEST] Dragonmaw Race: Corlok the Vet

### ISSUE THREAD

**Issue by Vansir** [RaphaelSunwell/Sunwell-BugTracker-SCv2#615]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Mob blokuje sie w trakcie wykonywania przelotu na coordach 73.5, 88.9 i nie chce leciec dalej. Raz zdazylo mi sie ze po 2 minutach walenia o krysztal, polecial dalej ale pozniej znowu ten problem wystapil i nie chcial juz leciec dalej przez ponad 10 minut.

**Oczekiwane działanie**: Mob powinien przeleciec bez zatrzymania cala swoja trase.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaakceptowac questa
2. Leciec za mobem az do podanych kordynatów
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=11068/dragonmaw-race-corlok-the-vet
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
73.5, 88.9

**Comment by Shon-su** [comment]
637
