### ISSUE TITLE
Mechanika NPC castujących

### ISSUE THREAD

**Issue by ta55el** [RaphaelSunwell/Sunwell-BugTracker-SCv2#62]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Castujący mob/npc powinien podczas gdy target aggro jest za "losem" lub przerwy w castowaniu lub przerwaniu casta silencem/interuptem podbiegać do osoby która ma na nim aggro.

**Obecne działanie**: Mob stoi jak słup

**Oczekiwane działanie**: Powinien podbiegać jeśli target jest za losem lub jak nie castuje i bić z melee ataku.

Spotkałem się z tym w paru lokacjach między innymi w otwartym świecie np coldara Spellweaverzy, czy instancje takie jak nexus czy utgrade keep.

**Comment by Towoku** [comment]
Z doświadczenia powiem ze zbyt ogolnie napisales. 
Najprawdopodomniej moby maja cos nie tak ze skryptem, wiec lepiej by było jak bys podał id moba i co z nim nie tak.  
Bład ewidentny jest, ale najprawdompodobniej nikomu nie bedzie sie chciało szukac tych mobow ( chyba ze jest tutaj jakis team testerski  ktory dostanie takiego taska, badz jest to generic bug dla wszystkich castujacych mobow). Oraz czy dotyczy to wszystkich castujacych mobow czy widziales jakies ktore działaja dobrze(warto taka inf zamiescic np. jak nowy dev dostanie taka inf. moze zaobaczyc jak to powinno działac, i ułatwi mu to zlokalizowanie błedu)? [jbc to nie gram na serverze tylko błedy przegladam :D ]

Btw: nie dałes zadnych "Faktów"[czyt. linków] ze tak powinno byc jak napisales, np. osoba ktora nie zna gry przeczyta i pomysli ze tak ma byc, a ja uwazam ze jak player castuje silence to mob powinien uciekac i sie kryc przed playerem za LoS do poki nie moge znow castowac. Hope u will get it ;]

**Comment by ThePuppetMaster** [comment]
Zgłoszenie niepełne. Proszę o uzupełnienie. Póki co zamykam.
