### ISSUE TITLE
[QUEST CHAIN]Bhrothers in Death

### ISSUE THREAD

**Issue by Mikekun** [RaphaelSunwell/Sunwell-BugTracker-SCv2#620]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Gracz który gra Death Kinghtem musi odnaleźć osobę noszącą nazwę Kolitira Dheatweaver w twierdzy Scarlet Hold która obecnie znajduje się w podziemiach tego zamku. 

**Obecne działanie**: Kiedy dochodzę do miejsca przebywania npc mobek praktycznie nie leży tam gdzie powinien. W ogóle go nigdzie nie ma, a natomiast w wowhedzie dość jasno jest wskazane gdzie npc powinien leżeć. W takiej sytuacji respawn npc jest nie na miejscu. 

**Oczekiwane działanie**: Ogólnie rzecz biorąc npc powinien leżeć w lochach zamku, i nie zależnie ile osób przez dany czas się przewinie dowolny gracz może z niego korzystać. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Grać Dheat Kinght 
2. Dojść do momentu chaina gdzie mamy zajęte przed pola zamku Scareltów. 
3. W ukrytej kryjówce na obrzeżach zamku w wiejskiej chatce jest npc który daje nam questa. 
![wowscrnshot_020717_235632](https://cloud.githubusercontent.com/assets/24986580/22742912/c04d1dea-ee18-11e6-99b8-7d22efce9d38.jpg)

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12725/brothers-in-death#videos:id=52844
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Scarelt Hold ( 62.9, 67.9)

**Comment by jubasek21** [comment]
Ten quest działa prawidłowo, po prostu ktoś go zrobił przed Tobą i musisz poczekać aż NPC znowu się pojawi na tym łóżku.

**Comment by DinozaurWKamizelce** [comment]
Nie wiem ile trwa respown tego NPC ale jakoś długo. Pamiętam, że na starym Sunwellu była taka kolejka, że kolega chyba z 4 dni czekał swoim DK zanim zrobił ten q. Ja robiłem ten q tutaj jakieś 1,5-2 miesięcy temu bez żadnych problemów (ale też nie było widać innych DK)

**Comment by Shon-su** [comment]
6 minut respawn plus pewnie minuta na zniknięcie ciała, czyli mniej więcej po 7 minutach powinien się respić.

**Comment by Mikekun** [comment]
siemanko 

Mimo to quest widać że powoli się buguje ponieważ jak ja go robiłem ostatnio to niestety tutaj ten cały Koltiria utknął czasem przed wejściem do twierdzy Scareltów. I to sądzę że powodu nie raz bardzo długi respawn. Jednakże uważam iż sam postać jest bugnięta ponieważ jak porzuci się questa w środku robienia zadania między kolejnymi stepami, nie da się wziąć poprzedniego questa. 

Życzę udanego dnia 
pozdrawiam Mikekun
