### ISSUE TITLE
[QUEST] Gerenzo Wrenchwhistle

### ISSUE THREAD

**Issue by Orear** [RaphaelSunwell/Sunwell-BugTracker-SCv2#621]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Ostatnia część chaina. Gracz musi zlikwidować Gerenzo i przynieść jego mechaniczną rękę.

**Obecne działanie**: Gerenzo po prostu nie istnieje, lub nie pojawia się w odpowiednim miejscu.

**Oczekiwane działanie**: Gerenzo powinien stać na platformie koła wodnego obok swojego kolegi, który jest vendorem. Jednakże wcale go tam nie ma. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wykonać chain quest pobierany od gnoma imieniem Ziz Fizziks w Stonetalon Mountains. 58,62
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=1096/gerenzo-wrenchwhistle
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Stonetalon Mountains 62,40
![przechwytywanie](https://cloud.githubusercontent.com/assets/25643448/22748418/502a15e2-ee2a-11e6-8203-ae65517b1909.PNG)

**Comment by Verthe** [comment]
q dziala nie wiem jak mogles nie widziec Gerenzo :D 2 namioty wczesniej ze tak powiem

**Comment by Verthe** [comment]
musiales przejsc obok niego

**Comment by Shon-su** [comment]
![wowscrnshot_020917_161556](https://cloud.githubusercontent.com/assets/17860936/22789412/2688caee-eee3-11e6-99c9-93c06a5831c0.jpg)
