### ISSUE TITLE
Zulfarrak buged 

### ISSUE THREAD

**Issue by krawath** [RaphaelSunwell/Sunwell-BugTracker-SCv2#625]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Instancja buguje się 

**Obecne działanie**: Nie można ukończyc instancji ponieważ buguje sie najazd mobów

**Oczekiwane działanie**: Najazd mobów powinien się nie bugować a zamknięta brama powinna się otworzyć 

**Co należy zrobić, aby odtworzyć ten błąd**: Spróbować ukończyć instancję.

1. Naprawić bug
2. Przetestować czy działa
3. Przeprosić graczy za zmarnowany czas na instancji 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: https://www.argentarchives.org/files/gallery_image/zf1.jpg

**Comment by kovaq** [comment]
#107 

Staraj sie stosowac do wzoru, nie musisz przepraszac, za zmarnowany czas testerow.

**Comment by krawath** [comment]
Napisałem wystarczająco dużo żebyście nie musieli sprawdzać całej instancji. Wiadomo co się buguje wiec odbij delikatnie mówiąc.

**Comment by kovaq** [comment]
Event dziala. 
Zarowno robiac w czasie z mobami:
https://youtu.be/HrE02-R87Ic
Jak i nie czekajac na nie:
https://youtu.be/oifR3JP8XlY
Event trwa nawet gdy zgina gracze:
https://youtu.be/PXsh27rp9fc
Jedynym problemem wtedy jest fakt, ze gina moby. A jak te zgina to logicznym jest, ze event jest nie udany i jest to koniec instancji. (na Vanilli nie bylo czegos takiego jak reset encounteru od checkpointa z mobem)

Mozesz nieco rozwinac temat, jakies charakterystyczne zachowanie mobow/graczy, ktore moglo to spowodowac, cokolwiek tylko nie "no buguje sie"?

%% Do Deva: Zwracam uwage na ustawienie Orka i Dwarfki, jest to druga linia w tym NPCowym zespole - to logiczne, bo to rangedy, ale przez zagiecie schodow moby te nie pullaja sie do walki - dopiero jak podciagnalem jakiegos trolla na gore to walczyli.

**Comment by krawath** [comment]
Z czego co kojarzę to robiliśmy to na combat bugu. Resztę robiliśmy normalnie bez niczego charakterystycznego.

**Comment by krawath** [comment]
Byłem teraz raz jeszcze ale nie dostałem combat buga a i udało się ukończyć instancję.

**Comment by Shon-su** [comment]
na discordzie ktoś dzisiaj zgłaszał że moby zeszły na dół i nic mu się nie działo potem. Ale nic więcej nie napisał więc ciężko ocenić.

**Comment by Isilion** [comment]
Robiłem tą instancje 4 razy. 3 razy udało mi się otworzyć bramę, ale za 4 (ostatnim) razem faktycznie atak NPCów na mobki na schodach się zbugował.
Więc albo bug działa sporadycznie, albo niedawno (gdy robiłem instę ostatni raz) został zbugowany.

**Comment by krawath** [comment]
Tak to wygląda jak się zbuguje.
https://www.youtube.com/watch?v=DV-OQrU4h38

**Comment by Bainit123** [comment]
Kiedy expiłem postać tydzień po otwarciu serwera (prawie 3 miesiące temu) dokładnie tak samo nam się bugowało. Nie wiem czym bug spowodowany ani jak go odtworzyć, a czasami instancja działała normalnie więc nie zgłaszałem.

**Comment by Radeghost** [comment]
bump, event znow sie buguje
