### ISSUE TITLE
Scarlet Monastery bug

### ISSUE THREAD

**Issue by krawath** [RaphaelSunwell/Sunwell-BugTracker-SCv2#626]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po założeniu mind control na Scarlet Commander Mograine, mob buguje się i nie można go zabić

**Obecne działanie**: J/W

**Oczekiwane działanie**: Scarlet Commander Mograine powinien dać się zabić 

**Co należy zrobić, aby odtworzyć ten błąd**: Przejsc się prejem do Scarlet Monastery i dać mind controll na Scarlet Commander Mograine

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: http://wow.zamimg.com/uploads/screenshots/normal/62276-scarlet-commander-mograine.jpg

**Comment by Shon-su** [comment]
17.02.2017 Rzucałem na niego Mind Control wielokrotnie, działał normalnie i udało się go zbić.
