### ISSUE TITLE
[QUEST]Pyrewood Ambush

### ISSUE THREAD

**Issue by Vaelevian** [RaphaelSunwell/Sunwell-BugTracker-SCv2#63]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jest 4 fale mobów. Faerleia powinna zabić je wszystkie, ale można jej pomóc. Po zabiciu 4 fal mobów quest jest zaliczony.

**Obecne działanie**: Pojawiaja sie potworki do zabicia (3 potwory). NPC nam nie 
     pomaga w zabiciu ich, a po zgładzeniu wroga nie uznaje questa jako wykonany.

**Oczekiwane działanie**: Powinno być 4 fale moboów(1,2,3,3). Faerleia powinna móc zabić je wszystkie,
	można jej pomóc. Po wszystkim, nawet jeśli się zginie( nie można brać opcji
	realease spirit) i Faelaria dokończy zabijanie, quest musi być zaliczony.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Deathstalker Faerleia (46.5 , 74.39) w Silverpine Forest, by wziąć quest.
2. Udać się pod koordynaty 46.5, 73.8.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=452/pyrewood-ambush
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
https://github.com/RaphaelSunwell/Sunwell-BugTracker/issues/28

**Comment by ThePuppetMaster** [comment]
Done.
