### ISSUE TITLE
[TALENT/SPELL] Argent Defender nie procuje

### ISSUE THREAD

**Issue by Artanis02** [RaphaelSunwell/Sunwell-BugTracker-SCv2#630]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
W niektórych przypadkach talent paladyna Argent Defender nie odpala się. Niestety nie odróżniłem w jakich przypadkach to się przejawia.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Spell czasem nie broni nas od śmierci (pomimo braku CD).

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Talent powinien za każdym razem oddawać nam 10/20/30% HP (zależne od poziomu talentu oraz defa) przy otrzymywaniu dmg, który miałby nas zabić.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Nauczyć się talentu Argent Defender
2. Próbować zginąć od dmg zadawanego przez moby/graczy. (Fall dmg nie powinien procować tego talentu)
3. Przy otrzymaniu dmg, który ma nas zabić, powinien procnąć talent, a czasem tak nie jest.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=31850
2. http://wotlk.openwow.com/spell=31851
3. http://wotlk.openwow.com/spell=31852

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: BRAK

**Comment by Artanis02** [comment]
czyli, że chuj z tego?

**Comment by xsitdev** [comment]
Artanis02, jeżeli zostało zamknięte bez komentarza, a nie ma dodanej okładki invalid, to zostanie wgrane przy następnym update (czytaj changelog).

**Comment by Artanis02** [comment]
Ah, dzięki bardzo - sorry, jeszcze na tym serwerze nie zgłaszałem nic.
