### ISSUE TITLE
Grizzly Hills - moby

### ISSUE THREAD

**Issue by Matius8** [RaphaelSunwell/Sunwell-BugTracker-SCv2#631]
**Opis**: Moby z Grizzly Hills (chodzi o Grizzly bear) po zaatakowaniu zachowuja sie jakby nikt ich nie atakował, bądź stoją i nie atakują.

**Obecne działanie**: Tak jak wyżej. ,,Grizzly Bear'' nie reagują kompletnie na ataki gracza. Albo chodzą dalej tak jakby nie miały Combatu, albo stoją i nie atakują. Oprócz tego, kiedy w czasie atakowania ich, zanim ich się zabije, odejdzie się, nie idą za graczem. W moim przypadku nie dotyczyło to wszystkich Grizzly Bear'ów, a jedynie niektórych (dodaje przykładowy screen z komendą .gps). Nie jestem już teraz pewien, ale jeśli dobrze pamiętam inne moby w wspomnianej krainie równiez miały taki bład. 

**Oczekiwane działanie**: Mob powinien normalnie reagować na ingrencję gracza. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wystarczy zaatakować Grizzly Beara, w lokalizacji pokazanej na screenie.

**Linki WoWHead/OpenWoW**: Raczej nie ma potrzeby dodawania.

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: https://zapodaj.net/7b20e90c2b6dc.jpg.html

**Comment by Shon-su** [comment]
#286

**Comment by Matius8** [comment]
Faktycznie, przepraszam za niepotrzebne zgłoszenie.

**Comment by Shon-su** [comment]
poprawione, 

@Matius8  jeśli napotkałbyś inne moby z tym problemem, proszę daj znać.
