### ISSUE TITLE
[SPELL] Bone Shield

### ISSUE THREAD

**Issue by Hooraga** [RaphaelSunwell/Sunwell-BugTracker-SCv2#632]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Spell Death Knighta Bone Shield daje nam 3 stacki tarczy absorbującej 20% jakichkolwiek obrażeń zadanych naszej postaci. Kazdy atak zadający obrażenia konsumuje 1 stack tarczy.

**Obecne działanie**: W niektórych sytuacjach (Nie jestem w stanie określić przyczyny) Bone Shield nie schodzi mimo licznych otrzymywanych obrażeń.
https://youtu.be/xzIY167OeO4 Dowód 1
https://www.youtube.com/watch?v=qbKYFI2NFic Dowód 2

**Oczekiwane działanie**: Każdy nadchodzący atak w Death Knighta z Bone Shield'em na sobie powinien zdejmować 1 stack Bone Shielda. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Nie jestem w stanie określić przyczyny.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=49222

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie jest konieczne

**Comment by Heartbraker** [comment]
Na arenach ani razu nie widziałem, żeby dk tracił stacki Bone Shielda.
Dk maja teraz 20% redukcji dmg 100% uptime, ten bug powinien być jak najszybciej naprawiony (choćby przez cofnięcie ostatniej "poprawki" do bone shielda i próbę naprawienie w inny sposób)

**Comment by Rosenkrantz** [comment]
Nie wiem, czy tylko czeka na wgranie, czy poprawka nie zadziałała (w changelogu widzę coś na ten temat, nr 343 z dnia 13.02.2017), ale na dzień dzisiejszy **bug dalej występuje** - grając PvP stacki regularnie się bugują, przez co Bone Shield trwa bez ograniczeń przez całe 5min - imo bug priorytetowy.
