### ISSUE TITLE
Quest  [Dragonmaw Race: Corlok the Vet]

### ISSUE THREAD

**Issue by Recalli** [RaphaelSunwell/Sunwell-BugTracker-SCv2#637]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Quest u Netherwingów 

**Obecne działanie**: Npc w quescie  [Dragonmaw Race: Corlok the Vet] ma złą droge latania i czesto zacina sie przy krysztale i nei można dalej z nim leciec przez co nie da sie ukończyc questa.

**Oczekiwane działanie**: poprawić drogę npc 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
615

**Comment by Shon-su** [comment]
powinno działać lepiej po następnym update
