### ISSUE TITLE
Alliance Brigadier General

### ISSUE THREAD

**Issue by nexx94** [RaphaelSunwell/Sunwell-BugTracker-SCv2#638]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
http://wowwiki.wikia.com/wiki/Alliance_Brigadier_General
Nie ma w dala
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Powinien być w dala
**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione, nie dograne
