### ISSUE TITLE
[LOCATION][VISUAL BUG] Searing Gorge, Kopalnia The Cauldron.

### ISSUE THREAD

**Issue by Vaelevian** [RaphaelSunwell/Sunwell-BugTracker-SCv2#64]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Moby: Heavy War Golem [npc=5854], Greater Lava Spider [npc=5858], Magma Elemental [npc=5855], Dark Iron Steamsmith [npc=5840].

**Obecne działanie**: Wszystkie w/w moby wpadają przez tekstury do kopalni. Nie da się ich wtedy zabić.

**Oczekiwane działanie**: Moby nie powinny wchodzić, a co dopiero spadać przez tekstury.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Searing Gorge, do Kopalni The Cauldron, koordynaty (37, 49) i okolice.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Powinno już działać poprawnie.
