### ISSUE TITLE
[QUEST] Stunning View

### ISSUE THREAD

**Issue by Bluczek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#640]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Eye of Dominion nie chce zamienić mnie w ghula.

**Obecne działanie**: Robiąc questa Stunning View, musimy zamienić sie ghula i zabić 12 nietoperzy, do zamiany służy nam Eye of Dominion, jednakże o ile przy 2 poprzednich questach, oko miało opcje zamiany w ghula tak przy tym jej nie ma. Wszystko zamieszczone na screen shot-cie.

**Oczekiwane działanie**: Eye of Dominion powinno mieć możliwość zamiany gracza w ghula.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać możliwość zamiany w ghula.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13160/stunning-view
2. https://zapodaj.net/e0ed3f46664f8.jpg.html
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
