### ISSUE TITLE
[Event Item] Lovely Charm Collector's Kit

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker-SCv2#644]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Przedmiot lapie dziwne fazowanie, gdy wejdziemy do instancji poprzez narzedzie dungeon/event findera. Po wyjsciu z instancji nie wypadnie nam juz ani jeden lovely charm, dopoki nie wyrzucimy danego itemku i nie pobierzemy go na nowo od Mr. Peddlefeeta wraz z questem na Gift dla lidera frakcji (np A gift for a Warchief).

**Oczekiwane działanie**: Item nie powienien byc podatny na blokade dropu Lovely charmow.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziac q na gifta, by otrzymac skrzyneczke.
2. Dropic charmy, beda wypadac.
3. Wejsc np na event w SFK.
4. Wyjsc i znowu dropic itemy - juz nie beda wypadac.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=49661
2. http://wotlk.openwow.com/item=49655
3. http://wotlk.openwow.com/quest=24612 / 24613 / 24614 / 24615 (po stronie hordy)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/103037023/xvnaubf

**Comment by Heartbraker** [comment]
Jest prawie tak jak piszesz - Lovely Charms przestają wypadać ale nie po użyciu DF czy zrobieniu eventu w SFK, a po naszej śmierci. Pewnie biorąc q, podczas gdy dostajemy Lovely Charm Collector's Kit nakładana jest na nas jakaś aura, którą tracimy wraz ze śmiercią.

**Comment by kovaq** [comment]
To wielce prawdopodobne, gdyz padlem na instancji, a nie bylem do konca pewien. Dziekuje za sprostowanie. :)
