### ISSUE TITLE
[npc][faction] Fordragon hold jest friendly dla hordy

### ISSUE THREAD

**Issue by Neos3452** [RaphaelSunwell/Sunwell-BugTracker-SCv2#645]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Wiekszosc NPC w Fordragon hold jest friendly dla hordy. Oprocz jakis mobkow na samym srodku i FM.
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Wiekszosc NPC w Fordragon hold jest friendly dla hordy.
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Wiekszosc NPC w Fordragon hold jest aggresive dla hordy.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przeteleportwac sie do fordragon hold jako postac z hordy
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=27518/fordragon-footman
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
<img width="732" alt="zrzut ekranu 2017-02-13 o 11 51 16" src="https://cloud.githubusercontent.com/assets/5870673/22881660/e515d9aa-f1e7-11e6-938b-30b986c12621.png">

**Comment by Shon-su** [comment]
mobki te są z frakcji "Wrathgate Alliance", a pod Wrathgate alianci i horda się zjednoczyli. I dlatego są friendly

**Comment by Neos3452** [comment]
Jakbyś spojrzał na link wowhead to byś zobaczył ze są oznaczeni na czerwono dla hordy. Te o których mówisz to są zupełnie inne npc i maja specjalne oznaczenie frakcji o ktorej mówisz:
http://www.wowhead.com/npc=31296/wrathgate-alliance-fordragon-footman


W tym momencie alianci maja w ogóle niebroniony quest hub. Można wejść i zabić FM bez konsekwencji.

Inne npc, które powinny być hostile:
http://www.wowhead.com/npc=27540/fordragon-marksman
http://wotlk.openwow.com/npc=27535

Cała lista (linki z wowdb tez potwierdzają przynależność):
http://wow.gamepedia.com/Fordragon_Hold

**Comment by Shon-su** [comment]
w każdym razie do tej frakcji wrathgate'owej są w tej chwili podpięte te npc-e i przez to są przyjazne. Poprawię w wolnej chwili

**Comment by Shon-su** [comment]
poprawione nie dograne
