### ISSUE TITLE
[Object][Dalaran Arena] Shadow Sight

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#646]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Obecnie Shadow Sight na dalaran arenie znajduje się na platformie.

**Obecne działanie**: Dopiero po reworku Dalaran Areny w Warlords of Draenor Shadow Sight znajduje się na platformie.

**Oczekiwane działanie**: Shadow Sight powinno znajdować się w rogach areny.

https://youtu.be/sjV8ZgNDWYU?t=5m58s        w 6 minucie ładnie widać gdzie

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=34709/shadow-sight
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Danieloses** [comment]
To jak? Już drugi sezon a Shadow Sight nadal w złym miejscu

**Comment by Danieloses** [comment]
bump?

**Comment by cebulaxgodx** [comment]
bump - wciaz jest tak jak nie powinno, przeszkadza to głównie stealtherom
