### ISSUE TITLE
[NPC]Bleeding Hollow Tormentor

### ISSUE THREAD

**Issue by Vaelevian** [RaphaelSunwell/Sunwell-BugTracker-SCv2#65]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Bleeding Hollow Tormentor[npc=19424] - Hellfire Peninsula, Zeth'gor.

**Obecne działanie**: Moby rzucają na siebie samych spell fear i dodatkowo po każdym uderzeniu mob przywołuje jednego lub dwa wilki.

**Oczekiwane działanie**: Mob nie powinien rzucać feara na siebie, tylko na gracza; oraz powinien przywoływać tylko jednego wilka.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Hellfire Peninsula, Zeth'gor.
2. Zaatakować moba Bleeding Hollow Tormentor.
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
done

**Comment by Kougraa** [comment]
Proszę o otwarcie zgłoszenia.
https://youtu.be/Ih4_Q4JU53I
