### ISSUE TITLE
[ITEM] Magic Dust

### ISSUE THREAD

**Issue by Akha72** [RaphaelSunwell/Sunwell-BugTracker-SCv2#651]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Item magic dust (http://wotlk.openwow.com/item=2091) jest obecnie zbugowany w dwojaki sposób. Po pierwsze, cel pod jego wpływem może castować i poruszać się, a tymczasem powinien być objęty działaniem efektu sleep, tj. nie móc ani castować, ani się poruszać. Po drugie, item ten nie powinien działać użyty na graczach (tj. powinien pojawiać się komunikat *Fizzled*), a na npcach powinien działać okazjonalnie* (tj. rzadziej niż częściej).

**Obecne działanie**: Obecnie magic dust działa na graczy i npce, ponadto cele objęte jego działaniem mogą się poruszać i castować

**Oczekiwane działanie**: magic dust nie powinien działać na graczy, a na npce okazjonalnie*, przy czym npc pod jego wpływem nie powinny móc się poruszać ani castować

**Co należy zrobić, aby odtworzyć ten błąd**: wydropić item z Dust Devilów (http://wotlk.openwow.com/npc=832) / dodać komendą / użyć na graczach i npcach

Dowody, że magic dust nie powinien działać na graczy oraz powinien tylko czasami działać na npce -
(http://www.wowhead.com/item=2091/magic-dust#comments)

PATCH 3.2:
This dust has been nerfed further and now has a 100% chance to Fizzle (not work) as a level 80 character using this against another level 80 player.

Congrats on having a freed up bag slot, all! :(

PATCH 3.2:
In fact, it has been nerfed to a 100% chance to fizzle, period. I just tried using this on a lvl 18 elite in Wailing Caverns, and it kept fizzling forever, making it officially useless.

PATCH 3.3:
Have to agree completely....this is a huge stealth nerf. I couldn't even find it listed in the undocumented patch notes on WoWWiki. Tested it from my level 10 bank alt on a Level 1 Rat in Stormwind by the AH. 3 Fizzles before it actually worked. This is highly infuriating to me, as if the nerf to make it last only 10 seconds in PvP wasn't enough. Once again, Blizzard proves how stupid and elitist they are by taking out a fun, much lesser known part of the game either due to complaints or their pathetic attempts to "balance" PvP. The Blizzard devs can DIAF for all I care.

PATCH 3.3.5:
As a 39, I was able to get the dust to work once out of every 8 or 9 times on a level 7 mob in Dun Morogh. Each time the dust fizzled, it did not get consumed. When the dust finally worked, it did get consumed.

Curious, I then tried to get the dust to work against another 39 in a duel, to no avail.

Basically, the capability of the dust is still there, but remains almost completely inaccessible at this time.

PATCH 3.3.5:
Very disappointed. This stuff is officially worthless now, at level 80 i tried to use this on a 78 non-elite in crystalsong forest and it fizzeled something like 100 times in a row, I decided it just wasnt going to work and proceeding to one shot the stupid satyr. I got it to work against a lvl 6 defias cutpurse though... oh and also a rat by the auction house... and after only 5 fizzles!

Z tych komentów wynika jasno, że magic dust nie powinien działać na innych graczy (niezależnie od lvl), a wobec npc powinien działać wyjątkowo rzadko (plus npce pod jego wpływem nie powinny mieć możliwości poruszania się ani castowania), czyli w konsekwencji magic dust nie powinien być już do niczego na mechanice patcha 3.3.5a przydatny.

**Comment by Shon-su** [comment]
Poprawiono niemożliwość targetowania graczy. 
Co do NPC-ów. Spell działa tak że działa na mobki max 30 level powyżej już niekoniecznie.

**Comment by Akha72** [comment]
To z tym 30 lvl to inny item - Slumber Sand (http://www.wowhead.com/item=3434/slumber-sand). Tutaj chodzi o Magic Dust, który ma nie działać na graczy i sporadycznie działać na npc, chyba że odkopałeś gdzieś info, że faktycznie nie powinien zupełnie wchodzić na npc 30 lvl +, ale to w takim wypadku podziel się linkiem : )

**Comment by Shon-su** [comment]
z 30 levelem chodzi o to że powyżej 30 levela jak jest mobek to rezultat działania jest nieprzewidywalny.
Opis tego itemu sam pisze że "Unreliable on targets above level 30." i tylko o to mi chodziło

**Comment by Akha72** [comment]
Tooltip Magic Dusta z woheada (http://www.wowhead.com/item=2091/magic-dust#comments) to już tootlip zmieniony, na 3.3.5a nie ma w tooltipie wzmianki o 30 lvl. Zaraz dam screen.
