### ISSUE TITLE
[Quest] The Mindless Ones (#552 reopen)

### ISSUE THREAD

**Issue by Akha72** [RaphaelSunwell/Sunwell-BugTracker-SCv2#652]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wszystko jest w linku (https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/552) i dokładnie wyjaśnione w drugim komencie do reporta, a tutaj info z wowheada, że The Mindless Ones (http://wotlk.openwow.com/quest=364) i w konsekwencji cały chain powinien być dostępny dla innych ras (nie chodzi o quest Rude Awakening - http://wotlk.openwow.com/quest=363 ).

PATCH 3.3.2
I was able to complete this as a troll. Counts towards Loremaster of Eastern Kingdoms.

(http://www.wowhead.com/quest=364/the-mindless-ones)

**Comment by Shon-su** [comment]
ok, poprawione nie dograne jeszcze.
