### ISSUE TITLE
[Quest] Evil Draws Near

### ISSUE THREAD

**Issue by Tealan** [RaphaelSunwell/Sunwell-BugTracker-SCv2#656]
[//]: # (****************************************************************)
[//]: # (** [Quest] Evil Draws Near **)
[//]: # (****************************************************************)

**Opis**: Zadanie z zabiciem kościanego smoka w "Terokar Forest"

**Obecne działanie**: zadanie zalicza zabicie kościanego smoka "Teribus the Cursed" ale nie można go ukończyć ponieważ "Oakun" twierdzi że brakuje reliktu "Dread Relic" w ekwipunku 

**Oczekiwane działanie**: po zabiciu kościanego smoka "Teribus the Cursed" wraz reliktem "Dread Relic" w ekwipunku "Oakun" powinien zaliczyć zadanie

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Ukończyć wcześniej zadanie The Dread Relic
2. Być minimum na poziomie 63
3. Zebrać 20 czaszek "Doom Skull" do przywołania kościanego smoka

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10923/evil-draws-near
2. http://www.wowhead.com/quest=10877/the-dread-relic
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Verthe** [comment]
Racja nie da sie oddac

**Comment by kovaq** [comment]
#371

**Comment by Verthe** [comment]
Moj blad :D

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
