### ISSUE TITLE
Elite Luzran fruwa zamiast chodzic

### ISSUE THREAD

**Issue by Jarek250** [RaphaelSunwell/Sunwell-BugTracker-SCv2#66]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Elite Luzran fruwa w powietrzu zamiast chodzic 

**Obecne działanie**: Elite Luzran fruwa w powietrzu przy spadku terenu zaraz przy wyjsciu z deadholme  nie działajace dobrze mmap

**Oczekiwane działanie**:  Elite Luzran powinien chodzic naprawa mmap

**Co należy zrobić, aby odtworzyć ten błąd**: udac sie na sciezke npc  i zobaczyc

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**: http://www.wowhead.com/npc=16245/luzran

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Chodzi.
