### ISSUE TITLE
[NPC] Spirit of Ar'tor

### ISSUE THREAD

**Issue by FakeMarcin** [RaphaelSunwell/Sunwell-BugTracker-SCv2#662]
**Opis**: Spirit of Ar'tor is a level 70 quest giver located in Illidari Point in the contested territory of Shadowmoon Valley

**Obecne działanie**: Brak NPC dającego możliwość kontynuowania chainquest'a.

**Oczekiwane działanie**: Po oddaniu drugiego prequesta, powinno to wyglądać tak: [https://www.youtube.com/watch?v=1hVFPiwiXso](url)

**Co należy zrobić, aby odtworzyć ten błąd**:

1.Ukończyć pierwszy quest
2.Ukończyć drugi quest
3. Posiadać 70 lvl

**Linki WoWHead/OpenWoW**:

1. [http://wowwiki.wikia.com/wiki/Quest:Ar%27tor,_Son_of_Oronok](url)     prequest 1
2. [http://wowwiki.wikia.com/wiki/Quest:Demonic_Crystal_Prisons](url)        prequest 2
3. [http://wowwiki.wikia.com/wiki/Spirit_of_Ar%27tor](url) brakujący NPC :)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:  29.6, 50.6  Shadowmoon Valley

Klikanie bezpośrednio w link nie przekierowywuje, wklejajcie link ręcznie <_<

**Comment by Shon-su** [comment]
poprawione, nie dograne

**Comment by Shon-su** [comment]
będzie się pojawiał po Demonic Crystal Prisons
