### ISSUE TITLE
[MAG][WATER ELEMENTAL][BUG]

### ISSUE THREAD

**Issue by maprzybyla** [RaphaelSunwell/Sunwell-BugTracker-SCv2#663]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Posiadanie water elementala przez maga w innym specu niż frost.
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Po zmianie talentów mojego maga na 75lvl z frost na fire zdismisowałem ręcznie water elementala po czym zapisałem się na bg. Jakież było moje zdziwienie kiedy po przeteleportowaniu sie na EOtS zobaczyłem, iż nadal posiadam water elementala. Sytuacja powtarzała się po każdym respawnie po śmierci oraz po wyteleportowaniu z bg. Posiadany water elemental atakował normalnie atakował graczy, jednak nie widziałem jego paska skilli oraz postawy (defensywna, ofensywna itp.) W obawie przed banem zmieniłem spec na frost. Co ważne, levelując we frost posiadałem Glyph of Eternal Water, który jednak wymieniłem po zmianie na fire na Glyph of Scorch

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po zmianie specjalizacji maga na inną niż frost, nie powinniśmy posiadać water elementala

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Magiem w specjalizacji frost z posiadanym Glyph of eternal water przyzwać water elementala i zagrac przynajmniej jedno bg
2. Po bg zmienic specjalizacje na fire (nie wiem jak z arcane) zdismisować water elementala i ponownie zapisac się na bg. 
3. Podziwiać swojego water elementala będąc fire magiem 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Danieloses** [comment]
Po kicku waterbolta pet nadal może używać umiejętności Freeze, to tak na boku.

**Comment by Vaelevian** [comment]
Wykonywaliśmy mnóstwo testów, które łącznie zajęły Nam blisko 2 godziny, jednak nie mogliśmy odtworzyć problemu. Zgłoszenie jestem zmuszony zamknąć.
Jeśli problem dalej występuje, proszę, abyś nagrał krótki materiał video, obrazujący zgłoszenie.
