### ISSUE TITLE
[BOSS]High Priest Thekal 

### ISSUE THREAD

**Issue by Hooraga** [RaphaelSunwell/Sunwell-BugTracker-SCv2#664]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jeden z bossów na Zul'Gurub - High Priest Thekal (Tygrys) występuje razem z 2 addami (Zealot Zath i Zealot Lor'khan) oraz z 2 tygrysami. Podczas walki jeśli jeden z addów lub boss zginie w odstępie czasu od śmierci poprzedniego większej niż 10 sekund, powinien zostać on wskrzeszony. Dodatkowo po udanym zabiciu addów i bossa (w przeciągu 10 sekund), High Priest Thekal przemienia się w postać tygrysa.

**Obecne działanie**: Po zabiciu dowolnego z addów lub bossa, Addy stają się friendly i wracają na swoje miejsce sprzed pulla, a boss ginąc, zostawia loot. Nie przeistacza się w formę Tygrysa, a Addy nie wskrzeszają się jeśli minie czas 10 sekund od śmierci poprzednika. 
https://www.youtube.com/watch?v=NmBXA6XWsNU

**Oczekiwane działanie**: https://www.youtube.com/watch?v=TBtuliawIrM przykładowe zabicie bossa (poprawnie działającego)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Zul'Gurub
2. Udać się do High Priest Thekal
3. Po pullnięciu zabić addy i Bossa.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=14509
2. http://wotlk.openwow.com/npc=11348
3. http://wotlk.openwow.com/npc=11347

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://scr.hu/11lh/92t1r

**Comment by Afgann** [comment]
https://gist.github.com/Afgann/fb997a3f218eb691b8217a1686ac452c
Może troche oszczędzi pracy.
