### ISSUE TITLE
Demonic Empowerment Warlock talent

### ISSUE THREAD

**Issue by krawath** [RaphaelSunwell/Sunwell-BugTracker-SCv2#667]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Talent powinien usuwać stuny, mindcontrole, feary, spowolnienia a zapewne tego nie robi.

**Obecne działanie**: Obecnie nie dziala na feary.

**Oczekiwane działanie**: Uzycie talentu powinno powodować usuniecie feara i nalozenie 15 sekundowego immune na to.

**Co należy zrobić, aby odtworzyć ten błąd**: Pograć warlockiem do 50 lvla, zrobic sobie talenty pod felguarda i mocno rozczarować się podczas zabawy w/w talentem. 

1. https://youtu.be/0WOZnvGzjlQ
2. http://wotlk.openwow.com/spell=47193
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Rosenkrantz** [comment]
Przepraszam najmocniej, ale gdzie masz coś napisane o fearze? PvP trinket w takiej sytuacji mówi o "all effects which cause loss of control of your character", bladestorm/bestial wrath dające pełne immunity na cc mają cytat z terminatora, "...does not feel pity or remorse or fear and cannot be stopped unless killed". 

Przedmiot z identycznym opisem, Free Action Potion (http://wotlk.openwow.com/item=5634) nie daje i nie powinien dawać niewrażliwości na inne, niewyszczególnione CC (poly, sap, fear), stąd moje wątpliwości, czy fix w ogóle był potrzebny :s
