### ISSUE TITLE
[Rogue] Glyph of Sinister Strike.

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker-SCv2#668]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Witam. Problem jaki tu przedstawiam prezentuje sie nastepujaco. Glyph of Sinister Strike aktywuje sie stosunkowo rzadko, wrecz prawie wcale. Przeprowadzilem test oparty o rachunek prawdopodobienstwa i wyszlo mi cos takiego: http://screenshooter.net/103037023/xynvudo 32/250 razy glyph zadzialal. Daje to 12,8%. Malo, zwazajac na to, ze Sinister Strike jest to Core Combo Generator dla rotacji w buildzie pod Combat Rogue'a.

**Obecne działanie**: Glyph majac 50% procuje zenujaco rzadko.

**Oczekiwane działanie**: Rachunkiem prawdopodobienstwa, glyph powinien oscylowac w granicach 45-55%, a nie wynosic niecale 13%.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zalozyc glyph na rogala (wypadaloby combat, gdyz w tym buildzie uzywa sie tego glypha)
2. Postac troche na kukle i potestowac.
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=42972
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
nie dotyczy

**Comment by kubowe112** [comment]
Ile miales critical strike chance? Glyph procuje tylko z tego.

**Comment by kovaq** [comment]
Racja, zapomnialem uwzglednic tego przy obliczeniach.
93 kryty.
32/93 to 34,4%, jest to wciaz za malo, biorac pod uwage prawdopodobienstwo. Tak jak mowie, satysfakcjonujace bedzie 45-55% (i nie, nie jest to jednorazowa obserwacja, tym razem poprostu usiadlem i specjalnie to sprawdzilem, zapisujac dane)

**Comment by kubowe112** [comment]
Moze wkradl sie jakis inny blad? Wziales pod uwage, ze nie wyskoczy dwa combo gdy masz juz 4 na targecie?

**Comment by kovaq** [comment]
Majac 4 combo uzywalem eviscerate/ snd by zbic to do 0 lub 1 (talent w buildzie) i od nowa do 4-5.

**Comment by MonichSC** [comment]
Dostałem 49% w moich testach, mógłby ktoś jeszcze zrobić podobne? min 150 critów dla pewności
