### ISSUE TITLE
[NPC] Franclorn Forgewright

### ISSUE THREAD

**Issue by Hooraga** [RaphaelSunwell/Sunwell-BugTracker-SCv2#669]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: We wnętrzu Blackrock Mountain znajduje się NPC Franclorn Forgewright. Powinien być on widoczny tylko i wyłącznie, jeżeli jesteśmy w formie ducha. 

**Obecne działanie**: Franclorn Forgewright jest widoczny również, jeśli jesteśmy żywi. 
http://scr.hu/11lh/xp96t

**Oczekiwane działanie**: Franclorn Forgewright powinien być niewidoczny, gdy jesteśmy żywi. Powinien być widoczny dopiero w formie ducha

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do lokalizacji gdzie jest Franclorn Forgewright będąc żywym.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=8888/franclorn-forgewright

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://scr.hu/11lh/xp96t

**Comment by Shon-su** [comment]
poprawione, nie dograne
