### ISSUE TITLE
bug podczas castowania spella

### ISSUE THREAD

**Issue by Jarek250** [RaphaelSunwell/Sunwell-BugTracker-SCv2#67]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:bug podczas castowania spella

**Obecne działanie**: podczas castowania jestem w zasiegu moba gdy mob sie odsunie od nas przez co stracimy zasieg do niego nadal castujemy 

**Oczekiwane działanie**: gdy gubimy zasieg powinno przerwac castowanie spellu i wyswietlic komunikat out of range 

**Co należy zrobić, aby odtworzyć ten błąd**: przetestowac na jakims mobie 

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Danieloses** [comment]
Jest pewna odległość, na którą mob/gracz może się oddalić poza max. zasięg spella tuż przed ukończeniem castu, a cast zostaje ukończony.

**Comment by Towoku** [comment]
UP ^ Dobrze mowi, jest offset do dystansu jak juz sie spell castuje, nie pamietam jaki ale jest cos takiego. Jak osoba zgłaszajaca uwaza ze jest inaczej poprosze o dowód bo w zgłoszeniu takiego nie widze. jak sie nie pojawi to imo po tygodniu do zamkniecia.
