### ISSUE TITLE
(quest Blackrock Spire) Libram of Tenacity (wycofany w Cataclysm)

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#671]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 	 Required materials Edit

1x  [Libram of Tenacity]
1x  [Black Diamond]
4x  [Crystal Ward]
1x  [Eye of Kajal] 
30 gold 

**Obecne działanie**: Zebranie itemów z pozycji 1-3 i 5 nie sprawia problemów. Niestety item Eye of Kajal, który powinniśmy wydropić z głównego sejfu Dark Coffer w Blackrock Spire jest niemożliwe, ponieważ pomimo listy 162 itemów, jakie Dark Coffer powinien dropić z różną skalą procentową szansy, Dark Coffer nie dropi nic. Co sprawdzałem pięciokrotnie.
Item potrzebny do tego questa Eye of Kajal ma 30% szansę na wydropienie z sejfu.

**Oczekiwane działanie**: Dodać listę itemó jakie powinny się pojawiać w Dark Coffer w Blackrock Spire - 
http://www.wowhead.com/object=160845/dark-coffer
**Co należy zrobić, aby odtworzyć ten błąd**: 

1. dodać listę dropu do obiektu Dark Coffer w Blackrock Spire, ponieważ obiekt ten nic nie dropi pomimo, że powinien dropić jakikolwiek item z listy 162 pozycji.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=4482/libram-of-tenacity
2. http://www.wowhead.com/item=11753/eye-of-kajal
3. http://www.wowhead.com/object=160845/dark-coffer

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Hooraga** [comment]
Potwierdzam, z Dark Coffer nie dropią żadne w.w przedmioty. 8-krotnie to sprawdziłem. Zawsze leciały zielone itemy.
