### ISSUE TITLE
Dark Coffer Blackrock Spire

### ISSUE THREAD

**Issue by Shon-su** [RaphaelSunwell/Sunwell-BugTracker-SCv2#673]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Dark Coffer Nie dropi itemów do questów
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Nie dropi itemów
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Powinien wydropić
**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1.  #670
2. #671
3. #672

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawiony

**Comment by Isilion** [comment]
Jakoś nie widzę żeby Dark Coffer został poprawiony.
Robiłem go 2 razy od informacji, że "poprawiony" i nadal nic nie dropi.

**Comment by Hooraga** [comment]
https://youtu.be/aVKfp60CNKs  Potwierdzam. Dziś 8-krotnie próbowałem zdobyć w.w przedmioty. Jednak ani razu nie udało się ich zdobyć. Zakładam że poprawiony, lecz jeszcze nie wgrany.

**Comment by Shon-su** [comment]
@Isilion 
http://sunwell.pl/changelog

Nie dograny jeszcze
