### ISSUE TITLE
[QUEST] Just Following Orders 

### ISSUE THREAD

**Issue by Yestereczek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#675]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Niedziałający quest w Sholazar Basin. Quest polega na porozmawianiu ze zranionym oraclem, niestety jest brak tej możliwości

**Obecne działanie**: Nie da się porozmawiać ze zranionym npc

**Oczekiwane działanie**: Powinna być możliwość porozmawiania z tym npc aby wykonać zadanie.
**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Przyjąć zadanie od High-Shaman Rakjak
2.  Podejść do zranionego npc
3.  Nie móc nic zrobić

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12540/just-following-orders
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: X: 5413,43 Y: 4574,75 Z: -129,36 Map: 571
![wowscrnshot_021517_214704](https://cloud.githubusercontent.com/assets/25803782/22994740/552de7dc-f3c8-11e6-8e70-6791b8acce6a.jpg)

**Comment by Shon-su** [comment]
poprawka która powinna pomóc z resetowaniem mobka dorzucona, nie dograna jeszcze.
