### ISSUE TITLE
Kayls's gone missing

### ISSUE THREAD

**Issue by LordAnayami** [RaphaelSunwell/Sunwell-BugTracker-SCv2#676]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Zwierzak nie przychodzi na postaci Aleantra -druid tauren

**Obecne działanie**: 3 razy próbowałem zrobić tego questa, ale za każdym razem nie przychodzi. 

**Oczekiwane działanie**: Poprawienie błędu oraz zaliczenie questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabić strusia, który daje przedmiot do questa x 30
2. W miejscu oznaczonym na mapie użyć przedmiotu
3. Czekać aż przyjdzie.

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:Bloodhoof Village

**Comment by LordAnayami** [comment]
4 próba też się nie udała.

**Comment by Shon-su** [comment]
@LordAnayami  Testowałem przed chwilą, działa poprawnie. Ten quest nie polega na tym że masz położyć mięso i czekać. Ten pies biega dookoła wioski, jak go widzisz to należy przed nim/ obok położyć mięso. Wtedy się zatrzyma i zaliczy questa.

**Comment by LordAnayami** [comment]
Nie raz tak zrobiłem, nie działa na mojej postaci. PS, kolejna próba nieudana.

**Comment by Shon-su** [comment]
a co to znaczy nie udana? nie zatrzymuje się? 

Jakby ktoś miał jeszcze taki problem to dajcie znać. Jak sprawdzałem dzisiaj to działało. A tam się niestety nie ma za bardzo co zepsuć :/

**Comment by LordAnayami** [comment]
Pies nie przychodzi, pomimo, iż jest koło jedzenia. Może to jakiś bug, bo koło mnie ludzie robili normalnie, więc ... U mnie na postaci zaś się nie da. Raz zrobiłem chwilkę po tym, jak inna osoba zrobiła, do niej przybiegł zwierzak, zaś do mnie już nie.
