### ISSUE TITLE
[MOB] Fel Cannon MKI

### ISSUE THREAD

**Issue by Trzyememce** [RaphaelSunwell/Sunwell-BugTracker-SCv2#68]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mob Fel Cannon MKI powinien zadawać jedynie obrażenia ranged.

**Obecne działanie**: Fel Cannon MKI bije z bliska
**Oczekiwane działanie**: Powinien bić tylko ranged.
![wowscrnshot_112216_122200](https://cloud.githubusercontent.com/assets/23569717/20522243/8f68d42c-b0af-11e6-8699-ee542db589d1.jpg)
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaatakować Fel Cannon MKI
2. Stanąć blisko.

 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/g00/npc=22461/fel-cannon-mki#abilities
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Nie powinien bić z melee ataków.
