### ISSUE TITLE
[SPELL] Visual vs Dmg

### ISSUE THREAD

**Issue by Kokaina** [RaphaelSunwell/Sunwell-BugTracker-SCv2#684]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: W grze mamy spelle, które stricte wiążą się ze swoim visualem. Polega to na tym, że obrażenia z niektórych spelli powinniśmy otrzymać gdy wypuszczony w nas spell do nas doleci. Od jakiegoś czasu (prawdopodobnie jest to zmiana globalna), te spelle zadają instant dmg zanim visual do nas doleci. Zauważone to zostało na Meteorze (id 57467) podczas bicia bossa Four Horseman (id 16064), a także podczas questów w Grizzly Hills oraz Shadow Crash (id 62660) podczas testów bossa General Vezax (id 33271). Spark (id 57430) na Malygosie (id 28859) również pojawia się w graczach zanim Malygos wypluje sparka, podczas gdy ten najpierw powinien do nich dolecieć. Na pewno jest dużo więcej takich spelli.

**Oczekiwane działanie**: Damage powinien być zadany dopiero gdy pociski wylądują na ziemi/dosięgną gracza, a nie w momencie wypuszczenia spella przez bossa/moba. Opis spella Shadow Crash w linku na dole zawiera opis, że dmg jest zadany "when missle lands". Obecnie niemożliwym do wykonania jest np. achi Shadowdogger na Vezaxie, który polega na unikaniu tych pocisków.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Obczaić shadow crashe na Vezaxie bądź Meteor na 4 Horsemanach
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. Shadow Crash - http://www.wowhead.com/spell=62660/shadow-crash
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
everywhere

**Comment by grigorlives** [comment]
Dotyczy też wszystkich maszyn i rp-gg na wintergrasp, ioc i socie. Irytujące bo normalnie celując nie da się trafić ruchomego celu, trzeba jak na aim bocie.

**Comment by kubowe112** [comment]
Armatki na Wg i Socie zadaja dmg w momencie wypuszczenia pocisku przez co zadawanie obrazen stalo sie dziecinnie latwe a unikanie pociskow niemozliwe.

**Comment by Kokaina** [comment]
Tak, to jest to samo. Identycznie maszyny na levku na uldu.

**Comment by Camiinus** [comment]
To samo wszystkie pojazdy/czołgi/etc używane do questów.
