### ISSUE TITLE
[Q] Hezrul Bloodmark (3396)

### ISSUE THREAD

**Issue by rakun1** [RaphaelSunwell/Sunwell-BugTracker-SCv2#685]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Ww. mob powinien mieć respawn time około 10 minut z tego co piszą ludzie na wowheadzie "He appears to be on a ~10 min respawn timer, if you cant find him around the oasis wait around the entrance of WC.". Na moba aktualnie jeszcze nie trafiłem a biegałem w okolicy Lushwater Oasis z dobre 1,5 godziny. Nie sprawdzałem bezpośrednio po restarcie, czy mob się respi, ale jest szansa, że jest to tylko ten moment, w którym można go zbić i wykonać q.
ID moba - 3396
ID questa - 852

**Oczekiwane działanie**: Mob powinien po zbiciu respić się co 10 minut i patrolować Lushwater Oasis w asyście dwóch addów.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa Hezrul Bloodmark od Regthar Deathgate.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=3396/hezrul-bloodmark#comments
2. http://wotlk.openwow.com/quest=852
3. http://wotlk.openwow.com/npc=3396

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
![](http://i.imgur.com/GZnJ5AP.png)

**Comment by Shon-su** [comment]
![Uploading WoWScrnShot_021717_134822.jpg…]()
Chodzi do okoła oazy, respi się co kilka minut

**Comment by rakun1** [comment]
@Shon-su sprawdzane na głównym realmie, czy testowym?

**Comment by Shon-su** [comment]
ok mea culpa, w poprzedniej poprawce jak mu ustawiałem waypointy w jednej współrzędnej umknął mi minus. Przez co galopuje sobie radośnie na drugi koniec kalimdoru. Po restarcie będzie ok
