### ISSUE TITLE
Brak repy

### ISSUE THREAD

**Issue by wuwus** [RaphaelSunwell/Sunwell-BugTracker-SCv2#687]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Brak reputacji z inst 77+

**Obecne działanie**: Witam, otóż nie dostaje reputacji za zabicie mobków na instancjach 77+  a dokladnie na UP ( HoLu i Oculusa nie sprawdzalem), natomiast na CoS wszystko dziala idealnie :).

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
Doprecyzuj proszę o jaką reputację chodzi. Horde Expedition?
