### ISSUE TITLE
Deadly Gladiator's Waraxe

### ISSUE THREAD

**Issue by dathremar** [RaphaelSunwell/Sunwell-BugTracker-SCv2#690]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
item ma zawyzony koszt.
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Jest to axe mający takie same staty jak podobNy axe deadly (http://www.wowhead.com/item=42208/deadly-gladiators-cleaver), jednak ten jest przeznaczony tylko dla huntera - do sezonu s5 hunter mial swoje wlasne bronie melle, ktore byly duzo tansze (z oczywistych wzgledów), w tym przypadku powinno to byc 1200arena pointsow, na Sunwellu ten axe kosztuje ponad 3k (3150 jezeli mnie pamiec nie myli)
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Item powinien kosztowac 1200 arena pointsow

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  kliknac prawym na vendora w dalaranie
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Deadly_Gladiator's_Waraxe - jedyne zrodlo pokazujace poprawny koszt.
2. http://www.wowhead.com/item=42237/deadly-gladiators-waraxe
3. http://www.wowhead.com/npc=31863/nargle-lashcord

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
