### ISSUE TITLE
[GLYPH] Glyph of Quick Decay

### ISSUE THREAD

**Issue by suriv12** [RaphaelSunwell/Sunwell-BugTracker-SCv2#691]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Glyph of Quick Decay warlocka, kompletnie nie działa

**Obecne działanie**: Corruption powinien częściej Tick'ować a jest jak normalnie bez glypha

**Oczekiwane działanie**: Corruption powinien trwać krócej a tick'ować częściej.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wrzucic Corruption na dowolny target i spojrzec na czas trwania oraz czestotliwosc tickow
2. Zalozyc Glyph of Quick Decay
3. Wrzucic Corruption na dowolny target i spojrzec na czas trwania oraz czestotliwosc tickow

**Linki WoWHead/OpenWoW**:

1.  http://wowwiki.wikia.com/wiki/Glyph_of_Quick_Decay
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy

**Comment by Kokaina** [comment]
Glyph działa prawidłowo. Jak najedziesz myszką na ikonke Corruption w spellbooku to owszem pokazuje 18 sekund lecz zobacz ile trwa dota na targecie, addon OmniCC odlicza sekundy co ładnie pokazuje czas trwania doty. Mając 20% haste, moje corru trwa niecałe 16 sekund.
