### ISSUE TITLE
[Strona][Armory]

### ISSUE THREAD

**Issue by damraw** [RaphaelSunwell/Sunwell-BugTracker-SCv2#692]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Żądana strona nie została odnaleziona! 

**Oczekiwane działanie**: Strona istnieje 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zalogować się i kliknąć na Armory zakładkę

**Linki WoWHead/OpenWoW**:

**Comment by Shon-su** [comment]
Armory są chwilowo wyłączone więcej informacji w linku
http://forum.sunwell.pl/index.php?/topic/1417-czytaj-je%C5%BCeli-chcesz-by%C4%87-na-bie%C5%BC%C4%85co/&do=findComment&comment=36306
