### ISSUE TITLE
[Strona][Character]

### ISSUE THREAD

**Issue by damraw** [RaphaelSunwell/Sunwell-BugTracker-SCv2#693]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Po kliknięciu w ikonkę postaci (http://sunwell.pl/character/1/Hrul) biały ekran

**Oczekiwane działanie**: Powinny być widoczne statystyki

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Zalogować się na konto
2.  Kliknąć w ikonkę postaci (http://sunwell.pl/character/1/Hrul)
3. Pokazuje mi się na chwilę układ ze statystykami health i mana. Wszystko się ładuje (kręcą się animacje ładowania) po czym dostaję biały ekran
4. Wpis z developer tool:
GET https://wow.zamimg.com/images/wow/icons/large/%3C!DOCTYPE%20html%3E%3Chtml%…http://sunwell.pl/application/themes/sunwell/images/%22,CSRF:%20getCookie( 414 (Request-URI Too Large)

**Comment by Shon-su** [comment]
Związane z przebudową strony
