### ISSUE TITLE
[Strona][Panel głosowania]

### ISSUE THREAD

**Issue by damraw** [RaphaelSunwell/Sunwell-BugTracker-SCv2#694]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Nie działa panel głosowania

**Oczekiwane działanie**: Powinno się oddać głos na najlepszy serwer do Wow'a 3.3.5

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zalogować się i kliknąć na panel głosowania 
2. Żądana strona nie została odnaleziona!

**Comment by Shon-su** [comment]
http://forum.sunwell.pl/index.php?/topic/1417-czytaj-je%C5%BCeli-chcesz-by%C4%87-na-bie%C5%BC%C4%85co/&do=findComment&comment=35578
Jest to działanie pożądane, systetem Vote został porzucony. Więcej informacji w linku. Strona w przebudowie
