### ISSUE TITLE
[Achievement]  [Oh Novos!]

### ISSUE THREAD

**Issue by botek321** [RaphaelSunwell/Sunwell-BugTracker-SCv2#695]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie może mi przydzielić achiwa chociaż wszystko robie dobrze.

**Obecne działanie**: Całe grp robi wszystko dobrze żadna ada nie przejdzie i nie opuści schodów. Robiłem to juz 4-5 i każdy się dziwi że ten achi nie wchodzi.

**Oczekiwane działanie**: Całe party idzie na środek schodów, i nie pozwala żadnej adzie opuścić schody kiedy już zbliliśmy 4 crytstalize addy przestaly się respić wiec przechodzimy na bossa i go zabijamy. Powinien wyskoczyć [Achievement]  [Oh Novos!]

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Trzeba zabijać potwory które respia sie na na górze na schodach i nie dać im sie dostać na sam dół.
A potem skupić się na bosie i go zabic

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/achievement=2057

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshot.sh/oeWD7ivW6bXOJ

**Comment by krawath** [comment]
potwory wychodzą nie tylko od strony schodów.
