### ISSUE TITLE
[QUEST]  To Netherwing Ledge!

### ISSUE THREAD

**Issue by kak4rotto** [RaphaelSunwell/Sunwell-BugTracker-SCv2#696]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest polega na zbieraniu kryształów, w Outland dokładniej Netherwing Ledge. By wziać quest nalezy zrobic chain. Jest to 5 quest.

**Obecne działanie**: Nie mozna zebrac kryształów (w ogole sie nie podswietlają)

**Oczekiwane działanie**:  Powinno dać sie zebrac kryształy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziać quest u Neltharaku
2. Polecien na wyspę Netherwing Ledge
3. Próbować podniesc kwiatki z kryształami

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10837/to-netherwing-ledge
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Kwiatki występuja na całej "wyspie" Netherwing Ledge

**Comment by Shon-su** [comment]
testowane przed chwilą, działa dobrze
