### ISSUE TITLE
[Quest][Shaman] Call of Water

### ISSUE THREAD

**Issue by crovm** [RaphaelSunwell/Sunwell-BugTracker-SCv2#7]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Po zdobyciu quest itemow, nalezy "porozmawiac" z brazerem, aby pojawil sie duch wody
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Brazer Cie olewa i tylko sie z Toba wita, duch sie nie pojawia
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po zdobyciu quest itemow, powinno sie podejsc do brazera kliknac go, obejrzec fajerwerki i porozmawiac z duchem aby oddac quest
**Co należy zrobić, aby odtworzyć ten błąd**:

1. sprobowac go zrobic
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=63/call-of-water
2. http://www.wowhead.com/item=7812/corrupt-manifestations-bracers
3. 
http://imgur.com/a/gcu1l
**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
38.0 45.0 Silverpine Forest
Zaznacze tylko ze przed upem dalo sie go zrobic normalnie, teraz cos jest nie halo
Abadon questa i proba zrobienia go ponownie nic nie daje, nawet przychodzac na gotowe juz z itemami duch tez sie nie pojawia

**Comment by ThePuppetMaster** [comment]
Powinno już działać.
