### ISSUE TITLE
[Gryphon Master] cień.

### ISSUE THREAD

**Issue by TomkiPL** [RaphaelSunwell/Sunwell-BugTracker-SCv2#70]
**Opis**: http://i.imgur.com/mT09fTu.jpg

**Obecne działanie**: Widoczny cień druida na sródku ekranu.

**Oczekiwane działanie**: Bez cienia.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Zapłacimy i wybieramy lot.
2. Musimy być na instancji po wyszukaniu "duengon finder"
3. Użyć prowl (druid) czyli sleath.
4. Zrezygnować z instancji.

**Linki WoWHead/OpenWoW**:

1.  Nie dotyczy.
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Nie dotyczy.

**Comment by ThePuppetMaster** [comment]
Tak lakonicznie opisane, że aż zastanawiam się czy nie troll.
