### ISSUE TITLE
Reputacja Timbermaw Hold

### ISSUE THREAD

**Issue by krawath** [RaphaelSunwell/Sunwell-BugTracker-SCv2#700]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

Gdy dostajemy ujemne punkty reputacji w okienku wyswietla sie napis **
Reputation with Timbermaw Hold increased by 20.**

**Oczekiwane działanie**: Powinno pisać Reputation with Timbermaw Hold decreased by 20.

**Udac sie do winterspring i zabic jakiegos niedzwiadka 

1. http://i.imgur.com/smbBagm.jpg
2. http://i.imgur.com/71m3ATd.jpg
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Hooraga** [comment]
Zabijanie tych niedźwiadków z "Winterfall" dodaje nam reputację do Timbermaw Hold. I tak powinno być. Samo ich zabijanie nie odejmuje, lecz dodaje reputację. Nie ma tu błędu.

**Comment by krawath** [comment]
Ale ta reputacja jest negatywna nie pozytywna

2017-02-19 16:14 GMT+01:00 Hooraga <notifications@github.com>:

**Comment by Hooraga** [comment]
Timbermaw Hold to frakcja u, której startujesz z pułapu negatywnego (Hostile bodajże). Możesz u nich reputację wbijać m.in poprzez zabijanie niedźwiedzi w Winterspring i Felwood. Reputacja u nic nie zmniejsza Ci się, a zwiększa i z Hostile, stają się oni Unfriendly -> Neutral -> itd.

**Comment by krawath** [comment]
Ale reputacja mi nie rosnie w stronę neutral tylko w stronę Hated

**Comment by krawath** [comment]
Do zamknięcia, mój błąd.
