### ISSUE TITLE
[BOSS] Emperor Vek'nilash (Twin Emperors)

### ISSUE THREAD

**Issue by Hooraga** [RaphaelSunwell/Sunwell-BugTracker-SCv2#701]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Na raidzie Temple of Ahn'Qiraj znajduje się boss Twin Emperors.

**Obecne działanie**: Jeden z bossów Emperor Vek'nilash nie posiada w ręku tekstury broni.
http://imgur.com/a/ph7Bq

**Oczekiwane działanie**: Powinien on posiadać w ręku broń identyczną jak Kalimdor's Revenge.
http://www.allvatar.com/rex/files/emperor_vek__nilash.jpg

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się na Temple of Ahn'Qiraj
2. Udać się do bossa Twin Emperors i przyjrzeć się Emperor Vek'nilash

**Linki WoWHead/OpenWoW**:

1. https://wotlk-twinhead.twinstar.cz/?npc=15275
2. https://wotlk-twinhead.twinstar.cz/?item=21679
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
