### ISSUE TITLE
[QUEST]Roll the Bones

### ISSUE THREAD

**Issue by Hooraga** [RaphaelSunwell/Sunwell-BugTracker-SCv2#702]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Quest Roll the Bones polega na zbieraniu Dinosaur Bone rozsianych po Un'Goro Crater, lub lootwania ich z różnorakich dinozaurów w Un'Goro.

**Obecne działanie**: Dinozaury w Un'Goro Crater nie dropią Dinosaur Bone. Wytłukłem całe Un'Goro z każdego możliwego Dinozaura i żaden nie wydropił quest itemu.

**Oczekiwane działanie**: Dinozaury takie jak np. Diemetradon, Stegodon itp, powinny dropić Dinosaur Bone.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest 'Roll the Bones' od Spark Nilminer w Un'Goro Crater
2. Zabijać Dinozaury w celu wydropienia Dinosaur Bone.

**Linki WoWHead/OpenWoW**:

1. https://wotlk-twinhead.twinstar.cz/?quest=3882
2. https://wotlk-twinhead.twinstar.cz/?item=11114

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://scr.hu/11lh/k0vl9

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
