### ISSUE TITLE
[QUEST] Missing Scouts

### ISSUE THREAD

**Issue by arktoos88** [RaphaelSunwell/Sunwell-BugTracker-SCv2#704]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak możliwości ukończenia questa.

**Obecne działanie**: Npc którego trzeba znaleźć i z nim porozmawiać znajduje sie pod ziemią.

**Oczekiwane działanie**: Aby wykonać questa trzeba porozmawiać z Frostborn Scout.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa
2. Znaleść npc o nazwie Frostborn Scout
3. Próbować z nim porozmawiać

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12864/missing-scouts
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 36.4 , 77.3 , Storm Peaks

**Comment by Shon-su** [comment]
sprawdziłem wszystkie 5 spawnów, wygląda ok. Mógłby ktoś ewentualnie dostarczyć screen który z nich jest niepoprawny?

**Comment by arktoos88** [comment]
![wowscrnshot_022017_215948](https://cloud.githubusercontent.com/assets/25887418/23141632/037bbe84-f7b8-11e6-8be3-ad7d2b646d3b.jpg)
