### ISSUE TITLE
[Rogue][Skill][Stealth]

### ISSUE THREAD

**Issue by Namzaj** [RaphaelSunwell/Sunwell-BugTracker-SCv2#706]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Skill rogala stealth działa niepoprawnie. 

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Skill rogala stealth działa niepoprawnie. Jeśli rogal ma jakikolwiek absorb będąc w stealth, direct dmg AOE powinno go wyrzucić ze stealth. Jedynie tickajace AOE nie są w stanie (concetration, flamestrike itp.).
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Jeśli rogal ma jakikolwiek absorb będąc w stealth, direct dmg AOE powinno go wyrzucić ze stealth. Jedynie tickajace AOE nie są w stanie (concetration, flamestrike itp.).
**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Dać rogalowi shielda i uderzyć AOE.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Stealth
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Rosenkrantz** [comment]
Kiedyś w tym siedziałem na starym todzie i powynajdowałem jakieś tematy, na teraz nie mam linków. Może do tego znowu dojdę.
Ogólnie wnioski, do jakich doszliśmy:
-blizzard/rain of fire/volley = wypadniesz ze stealth przy dmgu
-bezpośrednie trafienie rzucaną consą (czytaj: stoisz na plecach palka, kiedy ją rzuca) = wypadniesz ze stealth mimo absorba
-wejście w consę już na ziemi = możesz chodzić dopóki absorb trzyma.
-nie pamiętam jak z Magma Totemem i D&D - bezpośrednie zrzucenie D&D na głowę na pewno powinno wyrzucić.
Ofc podkreślam, że linków będę musiał poszukać, chyba że ktoś je ma pod ręką.

**Comment by Namzaj** [comment]
Magma co tick wyrzuca.
