### ISSUE TITLE
[Quset] No Mercy for the captured

### ISSUE THREAD

**Issue by anbusek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#711]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Quest polega na zabiciu 4 npc przetrzymywanych prez scarlet onslaught
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Npc po wybraniu opacji dialogowej w celu zabicia ich, pozostaja w klatkach i nie da sie ich zabic
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
powinni wyjsc z klatek zeby mozna bylo ich zabic
**Co należy zrobić, aby odtworzyć ten błąd**:

1. wziąć quest
2. porozmawiac z npc

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12245/no-mercy-for-the-captured
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
przejrzałem wszystkie klatki i działa ok. Npc po wybraniu opcji dialogowej aggruje się na gracza i da się go zabić

**Comment by anbusek** [comment]
z wszystkimi ale doszedlem do tego co to powodowalo, moby aggrowaly sie na mojego water elementa a on nie mogl castowac przez klatki(a meele bic nie moze)
