### ISSUE TITLE
[spell] LOCK zlw dzialanie speli

### ISSUE THREAD

**Issue by Kamilhope** [RaphaelSunwell/Sunwell-BugTracker-SCv2#712]
Chce zglosic bug wykorzystywany przez wsyztskich lockow.
1. SACRIFACE u voida
     - void nie znika po uzyciu skila (nie posiadam glyfa)
2. DRAIN SOUL 
     - podstawowy spell wysysa wiecej niz jedna dusze ( wysysa wiecej dopiero wtedy gdy ma sie glyfa)

**Comment by Akha72** [comment]
Zbanujcie to zanim złoży jaja.
1. Void nie znika od WotLKa, znikał natomiast na Vanillii i TBC (obecnie Sacrifice zabiera X hp Voidowi).
2. Drain Soul ma szansę na zrobienie Soul Sharda przy każdym ticku + 100% jeżeli lock zabije drainowany target w czasie channela. Glif zwiększa po prostu procentową szansę na Sharda z ticków.

**Comment by Kamilhope** [comment]
co do Soula nie ma bata. uzycie skila bez glyfa zawsze wysysal 1 shard. dopiero z glyfem mozesz nawet 5 dostac. idz poczytac co to blizlike.

**Comment by Rosenkrantz** [comment]
Przeczytaj dokładnie opis Drain Soul. Psst, przedostatnie zdanie.
http://wotlk.openwow.com/spell=47855

**Comment by Kamilhope** [comment]
czekam na odpowiedz/reakcje GMow. gram lockiem od 9 lat(w tym global). nie robic spamu,.

pozdrawiam
