### ISSUE TITLE
[Quest] The Mindless Ones (REOPEN Vol. II)

### ISSUE THREAD

**Issue by Akha72** [RaphaelSunwell/Sunwell-BugTracker-SCv2#713]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

Wszystko jest wyjaśnione w linku : (https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/652)
oraz (i przede wszystkim)
(https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/552)

Sprawdzane orkiem i blood elfem, dalej nie da się przyjąć questa inną rasą niż Undead.

**Comment by Shon-su** [comment]
hmmm... dziwne. No ale sprawdzę jak wróce

**Comment by Shon-su** [comment]
poprawione, nie dograne
