### ISSUE TITLE
[ITEM] Dr.Whitherlimb Loot - 0 stamina (REOPEN)

### ISSUE THREAD

**Issue by Akha72** [RaphaelSunwell/Sunwell-BugTracker-SCv2#714]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

Wszystko jest w linkach :

https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/649

https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/648

https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/647

**Comment by Shon-su** [comment]
wrzuciłem to wszystko do jednego tematu wtedy, bo problem jest w tym samym miejscu. Także jest już zgłoszenie otwarte odnośnie tego
