### ISSUE TITLE
[ITEM] Magic Dust (REOPEN)

### ISSUE THREAD

**Issue by Akha72** [RaphaelSunwell/Sunwell-BugTracker-SCv2#715]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

Wszystko w linku https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/651
plus moje komenty.

**Comment by Shon-su** [comment]
A co teraz nie działa? Bo z tego co pamiętam to coś tam poprawiałem

**Comment by Akha72** [comment]
Dalej można używać Magic Dust na graczach, dalej Magic Dust ma 100% wejścia w moby, sprawdzałem na 5ciu proszkach na mobach pod Dala - wszystkie weszły, ponadto targety objęte działaniem mogą się poruszać, atakować i castować. Dowody, że tak być nie powinno są w zgłoszeniach.

**Comment by Shon-su** [comment]
ustalenia na tą chwilę:
-wchodzi w graczy
- 100% szansy że pojawi się znaczek że mobek jest objęty działaniem
- dla mobków powyżej pewnego poziomu nie działa i mimo że pokazuje że śpią to mogą atakować

**Comment by xsitdev** [comment]
Dziś z update w nocy będzie, załatwione po core side.
