### ISSUE TITLE
[QUEST] Fortunate Misunderstandings

### ISSUE THREAD

**Issue by Larousene** [RaphaelSunwell/Sunwell-BugTracker-SCv2#716]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jeden z quest-chaina na reputację dla The Oracles. Quest polega na eskorcie NPC Injured Rainspeaker Oracle do Rainspaker Canopy

**Obecne działanie**: Po otrzymaniu questa i kliknięciu na NPC:
1. NPC kładzie się na ziemi i nie można z nim ani porozmawiać ani eskortować lub
2. Pojawia się okienko z dymkiem "I.m ready to travel", po czym po kliknięciu dymka NPC zachowuje się jak wyżej.
**Oczekiwane działanie**: Po kliknięciu na NPC, powienien pojawić się dymek "I'm ready to travel" po czym NPC powienien zacząc podróż do wioski.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zaakceptować quest od Injured Rainspeaker Oracle.
2. Kliknąc NPC a następnie dymek "I'm ready to travel"
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12570/fortunate-misunderstandings
2. 
3. 

**Lokalizacja z koordynatów GPS (55, 65)**:

**Comment by Shon-su** [comment]
dorzuciłem coś co powinno pomóc. Jeszcze nie dograne do serwera

**Comment by Larousene** [comment]
Quest nadal nie działa (sprawdzane kilka dni z rzędu, na róznych NPC) - dzieje się dokładnie to samo, co podałam we wcześniejszym opisie problemu.

**Comment by Shon-su** [comment]
taa, jest szansa że po najbliższym update (jak w changelogu pojawi się adnotacja do tego q) nie będzie się blokować. Niestety pomysłowość graczy nie zna granic i może znowu się poblokuje :(

http://sunwell.pl/changelog
