### ISSUE TITLE
Rouge - Vanish

### ISSUE THREAD

**Issue by Vanrine** [RaphaelSunwell/Sunwell-BugTracker-SCv2#717]
Vanish

Aktualnie z tego co widzę to każdy spell (nawet auto atak) jest wstanie wyrzucić rouge z Vanishu

Wyrzucanie z vanishu przez dowolne byle co.

Rouge powinien mieć możliwość vanishowania Spelli ponieważ po użyciu shadowcloacka jest on totalnie jak kukła i wszystko w niego wchodzi.

1. Filmik z Arena tournament z działającym poprawnie vanishem na wotlk -https://www.youtube.com/watch?v=_otkuhHWbys 6:25 -vanish na deepa /5:31 Vanish Polymophi

1. http://wotlk.openwow.com/?spell=1856

**Comment by Baggedmilk** [comment]
AT to nie dowod. Skad te przekonanie, ze na AT dziala poprawnie?

**Comment by Crackaw** [comment]
To że wychodzi z controli tłumu to ok do poprawy, ale z dmg powinien ściągać normalnie stealtha, o ile nie został puszczony przed włączeniem vanisha.

**Comment by Vanrine** [comment]
Czyli twoim zdaniem jeśli ktoś wypuści czar przed Vanishem to powinno wyrzucać ? To wyjaśnij mi na czym bazuje Vanish bo wątpię ze podstawowy spell dla rouge pvp jest tylko zapychaczem do rotów

**Comment by Crackaw** [comment]
Zamiast się przekomarzać prosiłbym o dowód i o dokładniejsze wyjaśnienie buga. Napisałem, że jeżeli spelle w locie nadal zrzucają vanisha to to jest błąd i należy dowiedzieć się dlaczego on występuje.

**Comment by nexx94** [comment]
http://www.wowhead.com/spell=1856/vanish#comments

Jest cytat blizzarda jak wchodziło cata, to że vanisha dało się używać do unikania spelli wynikało ze sposobu w jaki został zaprogramowany, z założenia miał służyć tylko do wchodzenia w stealth.

http://www.arenajunkies.com/topic/64325-rogue-how-to-vanish-serious-question/

Tu jest opisane jak działał kiedyś tam na globie, na beta testach działał prawidłowo, nie wiem czy coś z nim robiono. Po poziomie zgłoszenia zakładam że autor należy do grupy która vanishować po prostu nie umie, przypadek speli które wyrzucają z vanisha jest opisany, żadnego dowodu że działa nieprawidłowo jeszcze nie widziałem.
Jeśli da się vanishować tak że wyrzuca za stealtha i tak że nie wyrzuca wszystko jest w porządku.
