### ISSUE TITLE
[QUEST] Pilgrim's Bounty

### ISSUE THREAD

**Issue by belzer** [RaphaelSunwell/Sunwell-BugTracker-SCv2#72]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: BRAK NPC PRZED STORMWINDEM, U KTÓREGO ODDAJE SIĘ QUEST Pilgrim's Bounty, PIERWSZY Z EVENTU. / BTW NIE WIDZĘ RÓWNIEŻ NPCA OD KTÓREGO MOŻNA WZIĄĆ QUEST W IRONFORGE I DARNASSUS. - NPC DO WZIĘCIA QUESTA W SW SĄ OBAJ NA SWOIM MIEJSCU.

**Oczekiwane działanie**: WIDOCZNY NPC / ZDANIA QUESTA ORAZ QUEST GIVERZY W IRONFORGE I DARNASSUS

**Co należy zrobić, aby odtworzyć ten błąd**:

1. ZACZĄĆ QUESTA Pilgrim's Bounty
2.  UDAĆ SIĘ PRZED STORMWIND W MIEJSCE ZAZNACZONE NA MAPIE JAKO LOKALIZACJA NPC.
3. 

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/quest=14022/pilgrims-bounty
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
Dodaje NPC które dają Q dla hordy i alliance w każdej frakcji.

Alliance: http://wotlk.openwow.com/quest=14022 
Horde: http://wotlk.openwow.com/quest=14036

Wszystko w linku

**Comment by belzer** [comment]
Ok, to już coś. Teraz czekamy na NPC u którego się zdaje Questa. Jest zaznaczony na Mapie przed SW. Ale go tam nie ma.

**Comment by Shon-su** [comment]
po update powinny się pojawić

**Comment by Radeghost** [comment]
@Shon-su jak sie po update pojawi to przedluz event o 2-3 dni

**Comment by belzer** [comment]
Dzięki wielkie Panowie! :)

**Comment by belzer** [comment]
Nadal nie widać NPC u którego zdaje się Quest, Na mapie jest zaznaczony przed SW, ale go tam nie ma,
