### ISSUE TITLE
Eye of Eternity id bug expoit

### ISSUE THREAD

**Issue by KamaN442** [RaphaelSunwell/Sunwell-BugTracker-SCv2#724]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: obecnie umierajac na eye of eternity przez zabiciem nie wbija id dopiero jak wejdziesz na nowo to wyskakuje okienko i masz minute na zaakceptowanie id

**Obecne działanie**: mozna wejsc do isnty sprawidzc jakie sa itemy i wyjsc bez id .. nie jestem pewny co z rollem bo znam to z opowiesci

**Oczekiwane działanie**: id powinno sie wbijac nie zaleznie czy umarles czy nie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. wejsc na eoe, bic smoka, umrzec przed kilem 
2. Po zabicu, raid lider czeka na osoby ktore umarly wchodzisz do insty i masz min na zaakceptowanie id
3.  widzisz loot bez id ( nie jestem pewnny co do rolla)

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Eye_of_Eternity
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by KamaN442** [comment]
"po prostu umierasz, na 3 fazie lepiej zeby jak najbardziej pomoc druzynie
potem dajesz release spirit i czekasz az zabija spamujac wejscie do portalu zeby nie otwarli przed Toba xd
no i potem masz okienko do ID, to olewasz to nic nie dajesz oni otwieraja loot
i sa ikonki need greed nie wiem nigdy nie wygralem i zawsze passowalm
przy master loocie pewnie nie zdazy lider loota rozdac pewnie, ale przy grup loocie ja kkazdy da need/greed/pass to lajtowo pewnie dostaniesz"

**Comment by Heartbraker** [comment]
Hmm...to by rozwiązywało pewną zagadkę ->  http://image.prntscr.com/image/e41c11b83f514d7283c1137b7301d3db.png
No, ale to "tester" więc pewnie sobie tylko "testował", a nie wykorzystywał buga :>
