### ISSUE TITLE
[spell][glyph] Aimed Shot

### ISSUE THREAD

**Issue by TYMSON** [RaphaelSunwell/Sunwell-BugTracker-SCv2#73]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po użyciu glyphu zmniejszającego o 2s Cooldown na spell "Aimed shot" Cd skraca się tylko w opisie, ale w praktyce już nie. 

**Obecne działanie**:  http://imgur.com/a/aYSRk Niby wszystko dziala. Ale Porównując cooldowny spelli "aimed shot" i "Multi Shot" zauważamy że w praktyce mają dalej identyczny cooldown. W zależności od tego jaki spell użyjemy, to Cooldown drugiego się "dostosowuje". I tak używając spella "Multi Shot", mając glyph skracający Cd spella Aimed Shot to mimo wszystko jego Cd sie nam nie zmieni.

**Oczekiwane działanie**: Cooldown spella "Aimded Shot" powinien być o 2 sec krótszy od Cd spella "Multi Shot". Bezwzględnie na użyty spell. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zamontować "Glyph of Aimed Shot" 
2. zaatakować spellem: "Aimed shot" albo "Multi Shot" 
3. Spostrzec że w zależności od użytego spella, oba spelle będą miały identyczny Cd. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=42897#can-be-placed-in 
2. http://wotlk.openwow.com/spell=67978
3. http://wotlk.openwow.com/spell=49047

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: spellbok, domyślnie dół ekranu :)

**Comment by valcy** [comment]
CD sa od siebie zalezne, jezeli uzyjesz multi shota to oba spelle wskocza Ci na 10s cd, jezeli aimeda oba na 8s

**Comment by Danieloses** [comment]
Potwierdzam to o czym mówi valcy, nie mam dowodów lecz pamiętam, że zawsze działało to sposób następujący:

Większe znaczenie ma cooldown spellu, który obecnie castujemy, np. Po użyciu multishotu oba spelle otrzymują CD multi shot 10sec, po użyciu aimed shot oba spelle zyskują 8sec więc działa to w dwie strony.

Sprawa tyczy się wielu innych rzeczy typu użycie 5minutowej insygnii z 60lvla powinno naliczyć 5min CD na insygnii 2minutowej jeżeli mamy taką w bagu oraz 5min cd na Everyman for Himself jeżeli jesteśmy humanem, natomiast gdy użyjemy insygnii 2minutowej powinniśmy dostać 2min CD na 5minutowej insygnii. Więc tak jak wcześniej pisałem działa to w obie strony zależnie od obecnie użytego spella.
