### ISSUE TITLE
[QUEST] The tome of divinity

### ISSUE THREAD

**Issue by zurirbk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#730]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brakuje mi do questu itemu "symbol of life"

**Obecne działanie**: Brak możliwości wykonania zadania.

**Oczekiwane działanie**: Potrzebny mi ten item ponieważ za wykonane zadanie otrzymuje umiejętność wskrzeszania.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=1786
2. http://wotlk.openwow.com/item=6866
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
381

**Comment by Shon-su** [comment]
A brakuje to znaczy to samo co w zgłoszeniu #381 czyli "zgubiłeś" lub wyrzuciłeś?

**Comment by Shon-su** [comment]
item otrzymuje się po zabraniu poprzedniego quest'a. (http://wotlk.openwow.com/quest=1781). Niestety Blizz nie przewidział że w quest'cie w którym należy dostarczyć item od jednego npc'a do drugiego, a w kolejnym ten sam item do jeszcze innego, że ktoś może ten item wywalić :D

**Comment by Shon-su** [comment]
dorzuciłem coś co powinno pomóc, nie dograne jeszcze
