### ISSUE TITLE
[BOSS] Grobbulus

### ISSUE THREAD

**Issue by nexx94** [RaphaelSunwell/Sunwell-BugTracker-SCv2#731]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Boss nie trafia skillem, z tego co mi wiadomo powinien mieć hit capa. Tak samo jak nie da się uniknąć reapera na LK, tak samo slime spray powinien zawsze trafiać.
**Obecne działanie**: 
Slime Spray ma szansę nie trafić w graczy
**Oczekiwane działanie**: 
Powinien zawsze trafiać.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. http://worldoflogs.com/reports/tojgp9p7vm8z1t8o/xe/?x=spell%3D%22Slime+Spray%22
2. http://worldoflogs.com/zone/eu-us/naxxramas/grobbulus/normal-25/kills/p7/ <-- tu można zobaczyć czy takie cuda się na globie działy
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=15931/grobbulus#comments
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Kokaina** [comment]
Potwierdzam, wczoraj raz missnął w naszego tanka co było zaskoczeniem.

**Comment by nexx94** [comment]
Ja tam widze 4 missy, nie jeden.

**Comment by Kokaina** [comment]
No to raz który widziałem, nie jestem Deszczem :P tak czy siak do poprawy
w linku "<-- tu można zobaczyć czy takie cuda się na globie działy" są gildie z naszego serwera

**Comment by nexx94** [comment]
Podejrzewam że jak będziesz klikał linki z 2008 albo 2009 roku nie znajdziesz zbyt wiele gildii z naszego serwera.
Nie udało Ci się zauważyć że przez pół minuty nie wyszedł żaden ooze? Brak jednego ooza jest dość trudny do przeoczenia, zwłaszcza dpsem który te oozy bił.
