### ISSUE TITLE
[BOSS]Ouro

### ISSUE THREAD

**Issue by Hooraga** [RaphaelSunwell/Sunwell-BugTracker-SCv2#732]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Przedostatnim bossem na Temple of Ahn'Qiraj jest wielki robal Ouro. Pojawia się on po podejściu to spawnera (efekt wizualny jakby pod ziemią kopał robak)

**Obecne działanie**: Ouro Spawner jest targetowalny, aggruje nas po podejściu, zachowuje się jak zwykły mob. 
https://youtu.be/7v85q3VHjzw

**Oczekiwane działanie**: Po podejściu do Ouro Spawner z ziemi powinien wyjść boss Ouro.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Udać się do Temple of Ahn'Qiraj
2. Udać się do Ouro (Ouro Spawner).
3. Podejść do niego i zaagrować. (Zacznie nas bić zamiast zespawnić bossa)

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=15517/ouro
2. http://www.wowhead.com/npc=15957/ouro-spawner
3. http://www.wowhead.com/temple-of-ahnqiraj

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://scr.hu/11lh/wz078

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane z najbliższą aktualizacją.
