### ISSUE TITLE
[SHAMAN][MACRO][TOTEMY]

### ISSUE THREAD

**Issue by Zozusa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#733]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: targetowanie totemow shamana

**Obecne działanie**: Zadne macro ani samo wpisanie polecenia w grze /target tremor totem nie zaznaczy totemu 

**Oczekiwane działanie**: po wpisaniu /target tremor totem powino zaznaczyc nam totem odpowiednio dla macra /cast [target=tremor totem] spel,  powinno castowac spel w totem a jest brak efektu. 

**postawić totem i spróbować targetowac za pomocą komendy**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Danieloses** [comment]
Nie można targetować totemów macrem mniej więcej od połowy TBC

**Comment by Akha72** [comment]
Za zgłoszenia, które mogą potencjalnie wprowadzić w błąd powinny być rozdawane banany.

**Comment by Zozusa** [comment]
Prosze mi wybaczyc nie wiedzialem o takim czyms ( jestem z tbc i moje macra skopiwalem tez z tbc dlatego dziwilem sie dlaczego nie dzialaja)

**Comment by Akha72** [comment]
No widzisz, jest pełno różnić w działaniach skilli pomiędzy TBC, a WotLKiem, dlatego warto takie rewelacje skonfrontować z tym jak powinno faktycznie być, czy nawet zapytać na forum, niż od razu wybierać się z nimi na BugTracker.

Pozdrawiam : )
