### ISSUE TITLE
[Quest] Leave No One Behind

### ISSUE THREAD

**Issue by Pansrubka** [RaphaelSunwell/Sunwell-BugTracker-SCv2#734]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest w Zul'Drak. mamy znależć trzech NPC wyleczyć ich i eskortować do bazy

**Obecne działanie**: , Gdy wyleczymy i uda nam się eskortować wybrane NPC do bazy powinno zaliczyć quest lecz tak się nie dzieje a wyleczone NPC ciągle nas sledzą. 

**Oczekiwane działanie**: Znajdujemy jednego z trzech NPC leczymy go, eskortujemy do bazy i zalicza quest. Powtarzamy to z pozostała dwójką. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12512/leave-no-one-behind
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione, nie dograne
