### ISSUE TITLE
[Quest] Fortunate Misunderstandings

### ISSUE THREAD

**Issue by taranow** [RaphaelSunwell/Sunwell-BugTracker-SCv2#735]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Po zaakceptowaniu questa i po rozmowie z npc, on znika i nic się nie da zrobić. Quest nie jest zaliczany. 

**Npc powinien zmierzać do zaznaczonego miejsca, gdzie ma nastąpić zaliczenie questa. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
z tego co widzę ostatnia poprawka jeszcze nie jest dograna, jak pojawi się w changelog'u powinno już być ok
