### ISSUE TITLE
[Mag][Spell] Empowered Fire - nie zwraca many

### ISSUE THREAD

**Issue by Brilunes** [RaphaelSunwell/Sunwell-BugTracker-SCv2#736]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Talent powoduje zwrot 2% bazowej many gdy na targecie masz spell ignite jest na to 100% szans przy 3/3 wpakowaniu
**Obecne działanie**: Talent nie zwraca w ogóle many.

**Oczekiwane działanie**: Talent powinien zwracac 2% bazowej many gdy na targecie jest spell ignite

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przeliczyc ile powinien talent zwracac many z bazowej many
2. Zaczać bic
3. Patrzec jak talent nie zwraca many

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=31658
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Talent działa poprawnie. Zwraca dokładnie 2% based mana. Definicja based mana: "Base mana refers to how much mana a character has before it is modified by talents, intellect, enchants" - według niej, bazowa ilość many postaci na 80 levelu to 3268 i od tej wartości talent zwraca 2%.
