### ISSUE TITLE
[Mag][Spell] Mirror image

### ISSUE THREAD

**Issue by Brilunes** [RaphaelSunwell/Sunwell-BugTracker-SCv2#737]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Spell Mirror image uzycie powoduje ze nie pokazujesz sie w aggro do momentu dzialania mirrorow

**Obecne działanie**: Po mimo uzycia mirror image czasem jest sie w aggro.

**Oczekiwane działanie**: Po uzyciu Mirror Image nie powinio sie pokazywac ile mamy aggro.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Isc na jakigo kolwiek moba/bossa
2. Zaczać bic z mirror image
3. Patrzec czy pokazuje sie aggro czy nie.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/?spell=55342#taught-by-npc
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Vaelevian** [comment]
Testowane wiele razy, nie mogliśmy odtworzyć problemu. Na ogól, w dodatku WotLK pety chociażby Maga czy Warlocka działają tak, iż wrzucają combat już w trakcie castowania spella, a nie dopiero po wycastowaniu. Jeśli uważasz, że zgłoszenie zostało zamknięte bezpodstawnie, proszę, abyś opisał dokładnie problem, podając uzasadnienia swoich teorii w postaci linków do odpowiednich revision.
