### ISSUE TITLE
[Mage][Talent] Brain Freeze

### ISSUE THREAD

**Issue by Rosenkrantz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#739]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Procuje również z Ice/Frost Armor, a zdecydowanie nie powinien. Spory + przeciwko melee dla maga, być może związane z fixem https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/234

**Obecne działanie**: Brain Freeze ma szansę włączyć się z efektu Frost/Ice Armor.

**Oczekiwane działanie**: Brain Freeze powinien włączać się z zaklęć mających efekt chill **i zadających obrażenia**. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć talent Brain Freeze, ofc
2. Włączyć Ice/Frost Armor
3. Znaleźć przeciwnika, który będzie okładać maga.
4. Obserwować swoje buffy, przy szansie 15% szybko się włączy.

**Linki WoWHead/OpenWoW**:

1. Brain Freeze
http://wotlk.openwow.com/spell=44546
http://wotlk.openwow.com/spell=44548
http://wotlk.openwow.com/spell=44549
2. Ice Armor
http://wotlk.openwow.com/spell=43008#see-also-ability
3. Frost Armor
http://wotlk.openwow.com/spell=168
http://wotlk.openwow.com/spell=7300
http://wotlk.openwow.com/spell=7301

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: nie dotyczy.

**Comment by Baggedmilk** [comment]
Skad ty takie bzdury wymysliles? Frost armor jak i Ice armor procuja FoF oraz Brain freeze i nie jest to zaden bug. Oczywiscie kolejne wymyslone zgloszenie bez dowodow.

**Comment by Rosenkrantz** [comment]
Hm, nie sprawdzałem takiej korelacji, ale zdaje mi się, że nie trzeba Frostbite, żeby się odpaliło. Jak wrócę z pracy to zresetuję talenty i zobaczę, czy jest związek.

**Comment by Baggedmilk** [comment]
mozesz sie upewnic w dodatkowych testach, a najlepiej nie laduj w talent frostbite i sprawdz czy sie odpali przynajmniej raz proc z brain freeze

**Comment by Rosenkrantz** [comment]
Sprawdziłem (na głównym realmie, nie mam dostępu do testowego). Nie robi rożnicy, czy jest Frostbite, czy nie, Brain Freeze po prostu się włącza ze zbroi.

**Comment by Baggedmilk** [comment]
Nie rozumiem tego fixa, poniewaz Freeze od Frostbite przez blizzard jest liczony jako damaging chill effect

**Comment by Rosenkrantz** [comment]
Juz tłumaczę, w terminologii wowa:
negatywne efekty aplikowane komuś bez obrażeń (albo debuff od dotki, np corruption) = "harmful spell/effect"
efekty zadające obrażenia = "damaging spell/effect/ability"
Czyli przymrożenie kogoś do ziemi bez zadania obrażeń (czyt. Frostbite) = "harmful spell/effect"

Blizzard (z talentem) procuje Brain Freeze, bo zadaje obrażenia i ma chill. Nie ma to nic wspólnego z Frostbite.

**Comment by Baggedmilk** [comment]
przez blizzard chodzilo mi o firme blizzard;p, wczesniej sie z tym opisem napotkalem, ze zamrozenie kogos jest liczone jako wlasnie ten rodzaj spella. moze uda mi sie cos znalezc
