### ISSUE TITLE
[Object] Podwójny mailbox w Undercity

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#74]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: W Uc znajdują sie dwa mailboxy jeden na drugim. 

**Oczekiwane działanie**: Jeden z mailboxów powinien zostać skasowany.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pójść do Undercity.

**Screen**:

1. http://i.imgur.com/KkJQzGP.jpg

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
66.6/49.8, Undericty - Trade Quarter

**Comment by Shon-su** [comment]
done

**Comment by ellynd** [comment]
Jednak nie jest naprawione ;)
