### ISSUE TITLE
[quest] Cleansing the Waters (Outland)

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#740]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Description
I must ask that you finish what we've set in motion. Now that the demonic influence has weakened you must take this cleansing vial and pour it at the very source of the taint - Aggonar's own corpse.

You will find the demon's bones at the northern end of the pools. Beware, I sense that Aggonar's essence has not quite left this world.
Progress
You return, <name>.  Are the waters cleansed?
Completion
The essence of Aggonar lived on in the form of his foul offspring Aggonis.  With your success in defeating the demon, we can begin to work towards restoring the pools to their former purity.

You have our thanks, <name>.  Your work will have a deep impact in this world.
Rewards
You will be able to choose one of these rewards:

**Obecne działanie**: Nie da się napełnić flaszki. Flaszka w miejscu 40.2/30.8 faktycznie da się kliknąć pasek postępu pokazuje się, ale nie finalizuje się, Nie zalicza wykonania questu O dziwo jakies 2 tygodnie temu na innej postaci żona wykonała ten quest. Obecnie próbowałem kilkanaście razy i nic z tego. Po kliknięciu flaszka jest pusta, należy odczekać 2 minuty cooldownu flaszki i klikać ponownie bez skutku.

**Oczekiwane działanie**: Po kliknięciu flaszki i odliczeniu czasu jej napełnienia powinno zaliczyć quest i pozwolić odebrać zaliczenie u zleceniodawcy.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Po kliknięciu flaszki i jej napełnieniu powinno zaliczyć zadanie.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9427/cleansing-the-waters
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Hellfire Peninsula (Outland) 40.2/30.8

**Comment by Verthe** [comment]
Quest dziala poprawnie , pobilem go identycznie jak na tym filmie 
https://www.youtube.com/watch?v=Xlu6gUYSGLk

**Comment by Rosenkrantz** [comment]
Użycie flaszki przywołuje NPC, którego należy zabić - dopiero wtedy quest jest zaliczony, to tak gwoli sprostowania.

Dawnymi czasy jak się tam kręciłem, lvlując, zauważyłem w tej okolicy jakies dziwne LoSy (nie ma przeszkód terenowych, a nie da się atakować mobków), właśnie pod szkieletem, gdzie używa się quest itema. Może to one przeszkadzają.

**Comment by Verthe** [comment]
Nic nie przeszkadza dzis robilem ten q
