### ISSUE TITLE
Brak dodatkowego XP x2 na RaFie

### ISSUE THREAD

**Issue by frezz234** [RaphaelSunwell/Sunwell-BugTracker-SCv2#741]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Nie działa XP x2 na RaF. (jestem w party,mniej niz 40 yardow of frienda) Z góry dziękuje administracji za rozwiązanie/wyjaśnienie problemu.
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Brak XP x2 na RaFie
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
XP x2
**Co należy zrobić, aby odtworzyć ten błąd**:

1. zalogować się na konto Agand
2. zalogować się na konto greatdeath 
3. zobaczyć czy XP jest naliczany poprawnie

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Baggedmilk** [comment]
obstawiam za duza roznice lvli pomiedzy postaciami

**Comment by xsitdev** [comment]
Zasięg jest w porządku, lecz macie zbyt dużą różnice poziomów, RaF działa maksymalnie na różnice 4 poziomów, a Wy macie ponad 10.
