### ISSUE TITLE
[quest item] Eroded Leather Case

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#742]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Itwm potrzebny do wykonania questu 

**Obecne działanie**: 2 stwory powinny dropic ten item z największą szansą:
1. Marauding Crust Burster - 7%
2. Tunneler - 5%
W przypadku 1 stwora zabiłem ich 50, i żaden nie wydropił tego itemu. W przypadku 2 stwora zabiłem ich ponad 70 i dropią jedynie junka Fractured Carapace. Quest bardzo potrzebny do zaliczenia Achi na wykonanie 80 questó na Hellfire Peninsula, gdyż brakuje questów do dobicia 80 wykonanych questów.

**Oczekiwane działanie**: Poprawić szansę na drop quest itemu, tak by zwiększyć szansę do faktycznej liczby procentowej z WoWheada

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Naprawić szansę na drop quest itemu Eroded Leather Case
2. Zweryfikować czy w ogóle testwory dropią quest item.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=23338/eroded-leather-case
2. http://www.wowhead.com/quest=9373/missing-missive
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
jest ustawione 7% i 5%.

**Comment by Isilion** [comment]
Chyba kolega ma problemy z matematyką, bo przy zabiciu 70 stworów to raczej gdyby było 0,7% mógłbym się nie dziwić, że mi nie wydropiło. Przy 7% szansie mniej więcej co 15 stwór powinien to dropić, a nie co 70-ty.

**Comment by Baggedmilk** [comment]
Zgadzam sie, tez nie moglem tego wydropic, warte sprawdzenia.
