### ISSUE TITLE
{1 quest z chain questu] Ravager Egg Roundup (quest na Loremaster Outland)

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#743]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:I'm starving!

There's irony in that, wouldn't you say? A starving cook?

<Legassi laughs half-heartedly and taps a folded piece of parchment he has in his pocket.>

According to this tourist map we were following - before we were so rudely shot down - there's an area to the southwest, near Terokkar Forest. It's called the Razorthorn Trail, and supposedly it's brimming with delicious ravager eggs!

I could cook up quite a feast if only someone were brave enough to go down there and get me some!
Progress
You have those eggs yet?

<Legassi's stomach grumbles in anticipation.>
Completion
In order to have great cuisine, you need to have great ingredients.  And these eggs look great!

I've just finished cleaning off my frying pan, so you're more than welcome to join me for a meal!
Rewards
You will receive:
	Ravager Egg Omele

**Obecne działanie**: NPC nie zleca tego questu, więc nie da się zrobić również kolejnych 2 questów z chaina.

**Oczekiwane działanie**: Dodać quest do NPC'a.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać quest do NPC'a.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9349/ravager-egg-roundup
2. http://www.wowhead.com/npc=19344/legassi
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Outland/ Hellfire Peninsula 49,2/74,8

**Comment by Shon-su** [comment]
1. Wystarczyło zrobić jedno zgłoszenie, bo skoro nie zrobiłeś pierwszego questa z chaina to skąd wiesz że drugiego nie ma? :D
2. Opisałeś to tak że kilka minut zajeło mi połapanie się o co chodzi. 
3. Testowane przed chwilą, działa chain.

Jedyne wymaganie żeby zabrać pierwszy quest z tego chaina jest posiadanie levela 58.

**Comment by Isilion** [comment]
Wszystkie questy na WoWie wymagają minimalnego levelu poza questami Eventowymi świątecznymi. Posiadam level 71 więc raczej powinienem móc pobrać questy z minimalnym levelem 58. Tym bardziej questy na Repę dla Honor Hold. A okazuje się, że poza daily questem i questami w instancjach pozostałe są nie do pobrania,
