### ISSUE TITLE
[2 quest z chain questu] Helboar, the Other White Meat (loremaster Outland)

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#745]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: NPC nie zleca questu 	Ravager Egg Roundup, więc nie da się wykonać całego chaina na Loremaster Outland

**Obecne działanie**: NPC nie zleca questu Ravager Egg Roundup, więc nie da się wykonać całego chaina na Loremaster Outland

**Oczekiwane działanie**: Dodać quest rozpoczynający chain Ravager Egg Roundup

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Dodać quest rozpoczynający chain Ravager Egg Roundup
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9361/helboar-the-other-white-meat
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
Aby otrzymać ten quest należy wykonać:
www.wowhead.com/quest=9349

oraz posiadać co najmniej level 58

**Comment by Shon-su** [comment]
1. Wystarczyło zrobić jedno zgłoszenie, bo skoro nie zrobiłeś pierwszego questa z chaina to skąd wiesz że drugiego nie ma? :D
2. Opisałeś to tak że kilka minut zajeło mi połapanie się o co chodzi. 
3. Testowane przed chwilą, działa chain.

Jedyne wymaganie żeby zabrać pierwszy quest z tego chaina jest posiadanie levela 58.
