### ISSUE TITLE
[quest] An Old Gift

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#746]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Description
<The priest's gaze slowly moves from his mug to you.>

Don't you know better than to bother a man in his cups?

Oh, what's the use? I suppose newcomers are a good sign. What would Turalyon think?

I remember the eve of our departure, when I gave Mysteries of the Light to him. During the campaign and the ensuing years, he never forgot to read his daily passage to the men.

When he left us again, he gave the book back to me. Like a fool, I believed it safe in my quarters to the south of the armory.
Progress
I thought I asked you not to bother me. What is it?
Completion
Is that really it? It's hard to believe it survived the battle. Conditions in the ruins haven't been kind to the book, but still, I'm glad to have it.

It's the only token I have of Turalyon.

<Father Devidicus seems to be fighting back tears.>

When you fight beside someone for so many years, they become closer than even family.
Rewards
You will receive: 2
Gains
Upon completion of this quest you will gain:

    9,580 experience
    250 reputation with Honor Hold

**Obecne działanie**: Zleceniodawca nie zleca questu

**Oczekiwane działanie**: Dodać quest do dialogu zleceniodawcy

**Co należy zrobić, aby odtworzyć ten błąd**:

1. odać quest do dialogu zleceniodawcy
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10058/an-old-gift
2. http://www.wowhead.com/npc=16825/father-malgor-devidicus
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Outland/ Hellfire Peninsula 54,2/63,4

**Comment by Shon-su** [comment]
testowane przed chwilą, działa dobrze.  Min level 58, Ally only

**Comment by Isilion** [comment]
Mam level 71 więc powinien być ten quest dla mnie dostępny, no chyba, że Warrior go wziąć nie może.
