### ISSUE TITLE
[quest] Unyielding Souls

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#747]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Honor Guard Wesilow wants you to defeat 12 Unyielding Footmen, 10 Unyielding Sorcerers, and 5 Unyielding Knights at the Expedition Armory to the south.
Unyielding Footman slain (12)
Unyielding Sorcerer slain (10)
Unyielding Knight slain (5)

**Obecne działanie**: NPC nie zleca questa

**Oczekiwane działanie**: Dodać quest do dialogu NPC'a

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać quest do dialogu NPC'a
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10050/unyielding-souls
2. http://www.wowhead.com/npc=16827/honor-guard-wesilow
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Outland/ Hellfire Peninsula 50,8/60,2

**Comment by Shon-su** [comment]
Min level 58, ally only. Testowane przed chwilą. Działa dobrze

**Comment by Isilion** [comment]
Mam level 71 więc powinien być ten quest dla mnie dostępny, no chyba, że Warrior go wziąć nie może.
