### ISSUE TITLE
[1 quest z chaina] The Longbeards

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#748]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Description
We were having a problem with arakkoa bandits raiding many of our supply caravans, so I hired some dwarves to take care of them.

They were brothers; Gremni Longbeard was the oldest.

I'm a little worried about them. Those crazy dwarves packed more ale than food or ammunition! Maybe you can go check up on them?

The arakkoa's hideout, the Den of Haal'esh, can be found to the far west of here - beyond the Great Fissure. They set up camp northwest of there, south of Dustquill Ravine.
Completion
Gains
Upon completion of this quest you will gain:

    970 experience

**Obecne działanie**: NPC nie zleca questu

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ: NPC powinien zlecić 1 quest z chaina
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać zlecenie questu do rozmowy NPC'a
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=9558/the-longbeards
2. http://www.wowhead.com/npc=16826/sid-limbardi
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Outland / Hellfire Peninsula 54,1/63,6 Barman

**Comment by Shon-su** [comment]
Min level 60, Ally only. Działa
