### ISSUE TITLE
[NPC] Marticar

### ISSUE THREAD

**Issue by Heartbraker** [RaphaelSunwell/Sunwell-BugTracker-SCv2#749]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jest to rare mob występujący w Zangarmarsh

**Obecne działanie**: Obecnie respi się co parę minut, jak zwykły mob

**Oczekiwane działanie**: Powinien respić się co parę godzin jak inne rare moby

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Sprawdzic resp time komenda .npc info
2. albo ubic Marticara i poczekac na resp
3. 

**Linki WoWHead/OpenWoW**:

1.  http://wotlk.openwow.com/npc=18680
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
