### ISSUE TITLE
Interakcja z npc Princess oraz Porcine Entourage

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#75]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Strażnicy Princess nie reagują na jej atak przez co pierwszy trudniejszy quest w Elwynn Forest staję się banalnie prosty.
**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Po zaatakowaniu "Princess" aggrowana jest tylko npc Princess.
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po zaatakowaniu Princess gracza powinny zaatakować również dwa "Porcine Entourage", które stoją po lewej i prawej stronie Princess służąc jej za obstawę.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zagrować npc Princess
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=330
2. http://wotlk.openwow.com/npc=390
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
done
