### ISSUE TITLE
[ITEM] Unidentified Plant Parts

### ISSUE THREAD

**Issue by Heartbraker** [RaphaelSunwell/Sunwell-BugTracker-SCv2#750]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Unidentified Plant Parts - item do powtarzalnego questa w zangarmarsh, powinien dropic z mobów w tej krainie, obecnie dropi tylko z niektórych mobów, np. w ogóle nie leci z Bogflare Needler (http://wotlk.openwow.com/npc=20197)

**Obecne działanie**: Unidentified Plant Parts nie wypada z mobów z których powinien wypadać

**Oczekiwane działanie**: Lista mobów z których powinien ten item dropic - http://wotlk.openwow.com/item=24401#dropped-by

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=24401
2. 
3.

**Comment by Shon-su** [comment]
poprawione, nie dograne jeszcze
