### ISSUE TITLE
[QUEST] Fortunate Misunderstandings

### ISSUE THREAD

**Issue by Mati1993** [RaphaelSunwell/Sunwell-BugTracker-SCv2#752]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: [QUEST]  Fortunate Misunderstandings

**Obecne działanie**: Problem polega na tym iż mobek od ktorego bierzemy zadanie znika po powiedzeniu swojego dialogu a powinienem go eskortowac i dlatego nie zalicza zadania mało tego jak zrobie quest abandon to nie moge go wziac na nowo nie wiem dlaczego 

**Oczekiwane działanie**: POWINNO DZIALAC TAK IZ PO WZIECIU Q POWINNISMY MOBKA ESKORTOWAC w LINKU DO WOW HEAD JEST WSZYSTKO OPISANE 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. WZIAC Q OD MOBKA I POCZEKAC CHWILE 
2. ABANDONOWAC Q DWU KROTNIE I ZOBACZYC CZY MOZNA WZIAC PORAZ KOLEJNY Q
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12570/fortunate-misunderstandings
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 55,7 64,9 SHOLAZAR BASIN

**Comment by Shon-su** [comment]
Jak tam quest? Bo weszło kilka poprawek

**Comment by Verthe** [comment]
Sprawdzilem znow ten quest , dziala on prawidlowo .
Po anulowaniu idz poprostu do innego NPC bo jest ich tam kilku nawet jak nie ma < ! > nad glowa pogadaj i robisz misje dalej.  Shon-su juz wie co i jak
