### ISSUE TITLE
[spell] Blessing of Sanctuary

### ISSUE THREAD

**Issue by Edrad** [RaphaelSunwell/Sunwell-BugTracker-SCv2#753]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Buff ten powinien prócz zmniejszenia obrażeń na zbuffowanym targecie , zwiększać jego staminę o 10%

**Obecne działanie**: Nie zwiększa poziomu staminy
**Oczekiwane działanie**: Powinien zwiększyć poziom staminy o 10%

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by nexx94** [comment]
Po poziomie zgłoszenia podejrzewam że autor miał na sobie boka w momencie wrzucania bosa, jako że się nie stackują nie zauważył wzrostu hp. I tak powinno to działać.

**Comment by Radeghost** [comment]
do zakniecia
