### ISSUE TITLE
[Druid][Talent] Omen of Clarity

### ISSUE THREAD

**Issue by davidb9310** [RaphaelSunwell/Sunwell-BugTracker-SCv2#754]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Talent Omen of Clarity powinien wprowadzac nas w status Clearcasting, co sprawia ze redukuje mane, rage, ebergie nastepnego leczacego lub zadajacego obrazenia zaklecia.

**Obecne działanie**: działa normalnie na zaklęciach po za zaklęciem Hurricane, nie wazne ile celow uderzysz tym zakleciem zadne nie nabija statusu clearcasting.

**Oczekiwane działanie**: zeby nabijal sie status clearcasting podczas uzywania zaklecia Hurricane.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by nexx94** [comment]
http://www.mmo-champion.com/threads/622133-Omen-of-Clarity-Hurricane-Ninja-Nerf
http://eu.battle.net/wow/en/game/patch-notes/3-0-3
Druid: Omen of Clarity now has a reduced chance to be triggered by Hurricane.

Wynika stąd że tylko pierwszy tick hurricane powinien mieć szansę na odpalenie clearcasting.

**Comment by davidb9310** [comment]
> http://www.mmo-champion.com/threads/622133-Omen-of-Clarity-Hurricane-Ninja-Nerf
http://eu.battle.net/wow/en/game/patch-notes/3-0-3
Druid: Omen of Clarity now has a reduced chance to be triggered by Hurricane.

Wynika stąd że tylko pierwszy tick hurricane powinien mieć szansę na odpalenie clearcasting.

ooo, ok, to nie wiedzialem, dziekuje za info i przepraszam za klopot :/

**Comment by Radeghost** [comment]
do zamkniecia
