### ISSUE TITLE
 [SPELL][INSTANCJA][TEKSTURKI] Heroic Azjol-Nerub 

### ISSUE THREAD

**Issue by zoltekman** [RaphaelSunwell/Sunwell-BugTracker-SCv2#756]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: [SPELL][INSTANCJA][TEKSTURKI]

**Obecne działanie**: Po użyciu spella BLINK wyrzuca pod teksturki przed Last Bosem Anub'arak  w instancji Heroic Azjol-Nerub.

**Oczekiwane działanie**: Przy normalnym użyciu spella BLINK Mage powinien oddalić się o około 20 yrd w kierunku w jakim jest początkowo ustawiony. Bądź od razu ( np: przy uzyciu spacji ) po skoku  ( w tym wypadku ze schodów) powinien, jak jest powietrzu od razu znaleźć się na "ziemi" nie przebywając tych 20 yrd, lecz jedynie skrócić dystans "wysokości" do podłoża.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść do Instancji Heroic Azjol-Nerub
2. Dojść do schodów znajdujących się przed Last Bosem
3. Użyć Spella BLINK na środku schodów ( postać skierować w kierunku Bosa )

**Linki WoWHead/OpenWoW**:

1. BLINK - > http://www.wowhead.com/spell=1953/blink
2. Azjol-Nerub - > http://www.wowhead.com/azjol-nerub
3. [FILMIK PREZENTUJĄCY] https://youtu.be/joXp-abTJUw

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
#604
