### ISSUE TITLE
Basic Chemistry - Quest

### ISSUE THREAD

**Issue by Verthe** [RaphaelSunwell/Sunwell-BugTracker-SCv2#757]
**Opis**: Koltira Deathweaver aboard Orgrim's Hammer wants you to use Pustulant Spinal Fluid on a plague cauldron at Mord'rethar.

**Obecne działanie**: Obecnie dziala to tak podchodze do kociolka , uzywal flaszki , wylazi 1 ghoul zbijam po kilku sec 2 ghoule i w sumie tyle . Questa nie zalicza . Powtarzalem ta czynnasc kilka razy oraz zmienialem kociolki nic to nie zmienia 

**Oczekiwane działanie**: Nie bd sie rozpisywal robiac q sugerowalem sie wideo z http://www.wowhead.com/quest=13279/basic-chemistry

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Bierzemy q  http://www.wowhead.com/quest=13279/basic-chemistry
2.  .quest add 13279 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13279/basic-chemistry
2. http://wotlk.openwow.com/?search=basic+chemistry
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Verthe** [comment]
Sam sobie sprawdzilem i nie pyklo , moze poprostu cos zle robie i ktos sie wypowie .

**Comment by nexx94** [comment]
Przeczytaj komentarze w linku który wstawiłeś, tego questa solo da się zrobić dopiero od cata. Gdybyś był w stanie go zrobić sam miałbyś co zgłaszać.

**Comment by Verthe** [comment]
To jest sugerowana ilosc graczy , a nie wymagana wiec co to zmienia .

**Comment by Verthe** [comment]
Dodam , ze u nas flaszka ma 1.30min cd i moze w tym problem ? 
http://www.wowhead.com/item=44010/pustulant-spinal-fluid
http://wotlk.openwow.com/item=44010
Zgodnie z tym powinno byc to 30sec wiec dalbym rade odpalic flaszke kilka razy jezeli o to chodzi.

**Comment by nexx94** [comment]
Na cata cooldown został zmniejszony z 90 do 30s, dlatego da się zrobić solo. Znajdź 2gą osobę, wrzucajcie co 45s (łącznie około 10 razy), jeśli dalej nie zaliczy to prawdopodobnie nie działa.
Lekcja czytania ze zrozumieniem - jeśli ludzie na patchu 4.0.6. piszą że da się już zrobić solo to wcześniej się nie dało.

**Comment by Verthe** [comment]
http://wotlk.openwow.com/item=44010 aha to ten cd tez jest z cata ?

**Comment by nexx94** [comment]
Tak.
http://wowwiki.wikia.com/wiki/Quest:Basic_Chemistry_(Horde)
http://wowwiki.wikia.com/wiki/Quest:Basic_Chemistry_(Alliance)
Trochę się motają w wyjaśnieniach ale jedno jest pewne: cd na item to 90s i nie da się questa wykonać solo.
"Not soloable."
"This quest can not be done by a solo player."
"The Fluid has a cooldown of 90 seconds."
https://www.youtube.com/watch?v=DY-bYM0hNec
Tak działało na beta testach, spróbuj zrobić to co na tym video.

**Comment by anibus21** [comment]
Da sie zrobic solo bo teraz grajac huntem BM trzymam wszystko petem i schodzi plynnie. Problem tkwi glownie w tym jak przebiega caly enqounter... leje flaszke, w pierwszej kolejnosci powinny wyjsc male ooze po zbiciu ktorych pojawia sie napis zeby ponownie uzyc flaska i potem wychodza male ghoule i na koniec duzy i finito ;p u nas nie ma faz zadnych ;/
