### ISSUE TITLE
Cap dotek na Bossach

### ISSUE THREAD

**Issue by Ddooss1** [RaphaelSunwell/Sunwell-BugTracker-SCv2#758]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Dotki na bossach

**Obecne działanie**: Bossy mają capa dotek i utrudnia to trackowanie debuffow w trakcie walki co zmniejsza dps i dmg done w trakcie walki

**Oczekiwane działanie**: Zredukowanie capa ilości dotek na bossach. Z tego co wiem na wotlku nie było capa debuffow i buffow ( przy dużej ilości buffow dzieje się to samo i heale np nie mogą hotować rzucać baniek). Przeszkadza to bardzo w trackowaniu debuffow, przy 4 lockach affi i 3 sprejah i paru huntach i balancach zaniża to dps który moglibyśmy osiągnąć.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. nie wiem
2. może zwiększyć capa debuffow i buffow
3. znalazłem coś takiego:
WotLK Patch 3.0.2 (2008-10-14): There is no longer a limit on the amount of debuffs a target can have on them at any time.
TBC Patch 2.0.1 (2006-12-05): Debuff slot limit increased to 40.
Patch 1.7.0 (2005-09-22): The debuff limit has been increased to 16 (from 8). In addition, the client will now display all 16 debuffs.

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by nexx94** [comment]
https://www.engadget.com/2008/12/03/debuff-limit-removed/
He notes that the default UI won't normally be able to show all the debuffs, but that's just a bug in the UI.
Debuffy są nakładane na bossa, twoje UI nie jest ich w stanie poprawnie wyświetlić. Przynajmniej tak podejrzewam. Z buffami chyba faktycznie jest problem, przy 6 perfumach z eventu healerzy skarżyli się że nie wchodzą hoty na ludzi w raidzie.

**Comment by Ddooss1** [comment]
tak ale koleś przez całą walke na patchwerku spamił serpent stinga by zobaczyć czy działa i miał 35% uptimu np. więc nie jest to problem z UI

**Comment by Scythe-Kosiarz** [comment]
Najlepiej to widac na bosie eventowym, przy bijacym calym radzie dpsowanie shadow prejem jest beznadziejne
