### ISSUE TITLE
[QUEST] Saltherill's Heaven

### ISSUE THREAD

**Issue by kompanpawel** [RaphaelSunwell/Sunwell-BugTracker-SCv2#759]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:[QUEST] Saltherill's Heaven

**Obecne działanie**: Brak możliwości rozpoczęcia questa u NPC Magistrix Landra Dawnstrider w Fairbreeze Village. 

**Oczekiwane działanie**: Powinna być możliwość rozpoczęcia q po porozmawianiu z ww. NPC

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wystarczy porozmawiać z NPC by stwierdzić brak możliwości wzięcia questa.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=9395
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 44.1, 70.7 Eversong Woods

**Comment by Akha72** [comment]
Działał jakieś 2 tyg temu. Bierzesz ten q 80, czy jakimś lowem?

**Comment by Verthe** [comment]
ja sprawdzalem na 80 i nie ma tego q

**Comment by Akha72** [comment]
Na wowheadzie jest w opisie, że dodany w patchu 3.3.0, ale to mija się z prawdą, ponieważ poniżej są commenty z TBC. Na 100% tutaj działał, bo robiłem inną postacią, ale faktycznie obecnie jest coś źle, bo 80 UD lockiem nie mogę go przyjąć.

**Comment by Akha72** [comment]
Okej, zrobiłem q The Wayward Apprentice od tego samego q givera (http://wotlk.openwow.com/quest=9254), potem Corrupted Soil (http://wotlk.openwow.com/quest=8487), następnie Unexpected Results (http://wotlk.openwow.com/quest=8488), a na koniec wróciłem za pomocą Research Notes (http://wotlk.openwow.com/quest=9255) do Magistrix Landra Dawnstrider (http://wotlk.openwow.com/npc=16210) i pojawił się u niej q Saltheril's Heaven (http://wotlk.openwow.com/quest=9395). Done by 80 ud lock.

**Comment by Shon-su** [comment]
Potwierdzam, jest zrobione tak że quest ten dostaje się po zrobieniu Research Notes
