### ISSUE TITLE
[QUEST] A Strange Request - Feralas

### ISSUE THREAD

**Issue by sz4t4n** [RaphaelSunwell/Sunwell-BugTracker-SCv2#76]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie można dokończyć ukończyć questu A Strange Request w lokalizacji Feralas

**Obecne działanie**: Brak NPC - 36208 (Xerash Fireblade) / Nie można oddać questa.

**Oczekiwane działanie**: NPC na swoim miejscu tj. 76.8, 37.6

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pobrać quest od NPC - 8115 (Witch Doctor Uzer'i)
2. Spróbować wykonać
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=3121/a-strange-request
2. http://www.wowhead.com/npc=8115/witch-doctor-uzeri
3. http://www.wowhead.com/npc=36208/xerash-fireblade

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by ThePuppetMaster** [comment]
Quest powinien prowadzić do:
http://wotlk.openwow.com/npc=3216

**Comment by Kokaina** [comment]
Przeszliśmy na 3.3.5 więc oddajemy teraz questa npc Xerash Fireblade (36208) który działa prawidłowo więc zgłoszenie do usunięcia :)
