### ISSUE TITLE
[NPC] Franclorn Forgewright

### ISSUE THREAD

**Issue by Biggyx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#760]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W Blackrock Mountains nie ma npc Franclorn Forgewright, ktory powienien zaczynac q-chain Dark Iron Legacy

**Obecne działanie**: brak NPC Franclorn Forgewright

**Oczekiwane działanie**: Franclorn Forgewright powinien po prostu byc i dawac quest jak masz 52 lvl

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/npc=8888

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/ikcEj

**Comment by Akha72** [comment]
Ale wiesz, że ten npc jest widoczny tylko jak jesteś martwy?

**Comment by Biggyx** [comment]
Tego nie wiedzialem, bo na tych serwerach, gdzie ja gralem, on po prostu stoi tam i nie tzreba byc duszkiem zeby z nim gadac.

**Comment by Akha72** [comment]
to zabij się i sprawdź, czy wtedy się pojawia

**Comment by Verthe** [comment]
Jest tak jak napisal/a Akha  musisz byc martwy

**Comment by Shon-su** [comment]
potwierdzam, sam to ustawiałem ostatnio żeby był widoczny tylko po śmierci bo było zgłoszenie na BT :D

**Comment by Biggyx** [comment]
eh, spoko, dzieki, biegalem 2 dni jak debil u myslalem ze go po prostu nie ma ;d
