### ISSUE TITLE
[QUEST] Into the World of Spirits

### ISSUE THREAD

**Issue by Mocart4** [RaphaelSunwell/Sunwell-BugTracker-SCv2#761]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest polega na zebraniu plecaczka z reagentami z pokładu zatopionego statku

**Obecne działanie**: Plecak nie respi się bądź w ogóle się nie pojawia

**Oczekiwane działanie**: Plecak powinien się respić

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wystarczy wziąć questa i popłynąć tam, gdzie plecak powinna się znajdować

**Linki WoWHead/OpenWoW**:

1. Quest - http://www.wowhead.com/quest=11333/into-the-world-of-spirits
2. Item - http://www.wowhead.com/item=33635/reagent-pouch

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Quest item powinien znajdować się przy sterze zatopionego statku na koordach 62,41  59,27 w Howling Fjord

**Comment by Shon-su** [comment]
zaraz zajrzę, z tego co pamiętam ten plecak respi się pewnie w innym miejscu niż na mapie pokazuje. Też pod wodą ale statek dalej. Przestawię
