### ISSUE TITLE
[NPC] 10390 Skeletal Guardian SAI

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#764]
Po prostu kiedy NPC skonczy sie mana, przestaje castowac spelle ofensywne i stoi, a powinien podbiec i bic z melee tak jak kazdy caster bez many.

**Comment by Verthe** [comment]
Potwierdzam , stoja i nic nie robia jak regnie im sie mana znow cos castuje i tak caly czas .
