### ISSUE TITLE
[Quest 10644] - Teron Gorefiend - Lore and Legend

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#765]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zorus the Judicator at Wildhammer Stronghold in Shadowmoon Valley wants you to find the Ancient Shadowmoon Spirit.

If you lose your Spectrecles, Zorus the Judicator can make you a new pair.
Provided item:
	Spectrecles
Relevant Locations
The entirety of this quest happens in Shadowmoon Valley.

**Obecne działanie**: Po założeniu googli i udaniu się do lokacji Shadowmoon Valley 58,2/70,8 brak zespawnowanego Ancient Shadowmoon Spirit

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**: Dzialanie questa przedstawione w linku z Youtube

1. Dodać do questa Ancient Shadowmoon Spirit widzianego wyłącznie gdy postać gracza ma założone google.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10644/teron-gorefiend-lore-and-legend#comments
2. https://www.youtube.com/watch?v=uNqirbrJFiE
3. http://www.wowhead.com/npc=21797/ancient-shadowmoon-spirit

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Shadowmoon Valley 58,2/70,8

**Comment by Verthe** [comment]
NPC jest na swoim miejscu , mozna go tez zobaczyc jako duch
