### ISSUE TITLE
[Rogue][Ability] Shadowstep

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#767]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Skill Shadowstep powinien przenosić za plecy przeciwnika jednakże, 

**Obecne działanie**:  Obecnie jeżeli gracz ustawi się dokładnie na krawędzi platformy, np. na Ring of Valor po użyciu shadowstepa jesteśmy przenoszeni pod platformę za przeciwnika.

**Oczekiwane działanie**: To co dzieje się obecnie nie powinno mieć miejsca w dodatku jeżeli jakimś cudem przeciwnikowi udało się ustawić dokładnie na ostatnim pixelu platformy powinniśmy zostać teleportowani przez Shadowstep na ten sam pixel co przeciwnik, w żadnym wypadku nie powinniśmy zostać zrzuceni na ziemię pod platformę.

Dodam jeszcze, że obecnie ten bug jest wykorzystywany przez ogromną ilość osób na arenach i nieraz Shadowstep jest kompletnie wyłączony z użycia na arenie, biorąc to pod uwagę jest to dość gamebreaking bug.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Radeghost** [comment]
>powinniśmy zostać teleportowani przez Shadowstep na ten sam pixel co przeciwnik
nie wydaje mi sie ;d dowody

**Comment by Danieloses** [comment]
Podsumowując, nigdy nie powinniśmy zostać umieszczeni wyżej lub niżej niż przeciwnik i zawsze powinniśmy mieć możliwość używania umiejętności wymagających stania za przeciwnikiem.

**Comment by Notzx** [comment]
Potwierdzam, zaobserwowałem też dziwne zjawisko a mianowicie gdy użyjemy shadowstepa podczas charge warriora(wiem, trwa ona krótko aczkolwiek to możliwe) pojawiamy się w miejscu w którym aktualnie jest warrior(środek charge albo 3/4 drogi czy jakikolwiek inny ułamek) a powinniśmy pojawić się w miejscu w którym warrior użył charge (z którego ruszył). Myślę, że naprawienie tego co opisał Danieloses powinno naprawić również sytuacje w tym przypadku.

**Comment by Danieloses** [comment]
Proszę o naprawienie przed początkiem nowego sezonu, ponieważ abuserzy wykorzystują ten bug nagminnie i w wielu walkach/arenach shadowstep to martwa umiejętność.

**Comment by Crackaw** [comment]
W końcu po wielu próbach naprawione xD
Niech ktoś coś to z warriorem, bo nie mam jak przetestować. Jak coś nowe issue otworzyć. 
Tymczasem zamykam :D
