### ISSUE TITLE
Kalendarz i eventy

### ISSUE THREAD

**Issue by ghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#77]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Kalendarz nie pokazuje kilku eventów m.in.: Darkmoon Faire, Lunar Festival, Children's Week, Pilgrim's Bounty, Harvest Festival

**Oczekiwane działanie**: Kalendarz powinien pokazywać w.w. eventy.

**Co należy zrobić, aby odtworzyć ten błąd**: Otworzyć kalendarz.

**Aktualny kalendarz**:
1. http://imgur.com/a/mDgbc

**Link do screenów z poprawnym kalendarzem**:

1. http://imgur.com/a/oTBgs

**Comment by kovaq** [comment]
Zjawisko to zwiazane jest z 2 faktami:
1. swieta, ktore nie sa zaznaczone, sa swietami dynamicznymi, a nasz server ich nie uaktualnia, bo nie jest globalem.
2. blizzard raczej nie przewidywal, ze w 2017 ludzie wciaz beda grali na dodatku z 2008 roku, nie wprowadzil calego kalendarza.

Dodatkowo, na globalu rowniez nie aktualizuja z wyprzedzeniem swiat dynamicznych, spojrz:
aktualny miesiac
http://screenshooter.net/103037023/hpyueqi
nastepny miesiac
http://screenshooter.net/103037023/efejpsc
i za rok
http://screenshooter.net/103037023/gphugek (i jest to ostatni wpis w kalendarz, nie ma lutego 2018)

**Comment by sanctify21** [comment]
Nie trzeba być 'globalem', żeby ogarnąć eventy dynamiczne. Ekipa z Gamer District potrafi jakoś to zrobić ;-) Polecam rzucić okiem na ich działający kalendarz.
