### ISSUE TITLE
[quest] Blueleaf Tubers

### ISSUE THREAD

**Issue by Morgahard** [RaphaelSunwell/Sunwell-BugTracker-SCv2#771]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W miejscu "pierścienia wykopów" na razorfen kraul (RFK) nie można wypuścić istotki do questa kopiącej nam quest itemki. 

**Obecne działanie**: 
Brak możliwości użycia quest itemu- nie przypisany zone prawdopodobnie.

**Oczekiwane działanie**: 
W pierścieniu wykopów (rów na RFK taki dość duży ze mobami  świniami) powinna być możliwość użycia quest itemów. W sumie są dwa: klatka- wypuszcza naszego pupilka, różdżka- do "sterowania nim". 

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wejść na RFK
2.  Droga: prosto, za mobami po lewej stronie ukarze się rów/pierścień wykopów. 
3. Wejść do rowy/pierścienia wykopów- użyć quest itemów, które zbieramy w Ratchet zaraz po wzięciu questa, są obok banku. 

**Linki WoWHead/OpenWoW**:

1.  https://www.google.pl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjIjaHy1L3SAhWFF5oKHXU_D7EQFggdMAA&url=http%3A%2F%2Fwww.wowhead.com%2Fquest%3D1221%2Fblueleaf-tubers&usg=AFQjCNE-bDrMCBStc7bRDS7Q2o1v0lf41Q&sig2=rFQZtsT7avMFtXZb2A_6Nw
2.  Mechanikę działania questa można zobaczyć na youtube.com wpisując nazwę questa. Są 3 filmiki
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Brak. 

Pozdrawiam, Cruelsky

**Comment by Shon-su** [comment]
#547
