### ISSUE TITLE
[quest] Frostmaw's Mane

### ISSUE THREAD

**Issue by Morgahard** [RaphaelSunwell/Sunwell-BugTracker-SCv2#772]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Mamy wydropić rzadki itemek i użyć go w określonym miejscu.

**Obecne działanie**: 
Drop jest niski 0,5-1%, zawsze szło to długo- ale nie dropi. Myślę że po 2h dropienia i ubiciu dobrych 200 mobów z których jest szansa na drop powinno to działać. Na ToDzie qest robiło się około 30-40 minut. 

**Oczekiwane działanie**: 
Sprawdzić czy loot jest poprawnie przypisany, ewentualnie przypisać loot do określonej grupy stworków (lodowe giganty przy jaskini gdzie później należy używać dropionego itemku- Rod of Hercular). 

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Iść do miejsca przeznaczenia questa
2.  Zabijać i próbować wydropić lub sprawdzić w systemie poprawność % drop
3.  Jeśli wszystko w bazie gra, napiszcie że gra, jeśli nie poprawcie.

**Linki WoWHead/OpenWoW**:

1.  https://www.google.pl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiRgvOR073SAhVGhiwKHe4sBlkQFggaMAA&url=http%3A%2F%2Fwww.wowhead.com%2Fitem%3D3708%2Fhelculars-rod&usg=AFQjCNGtc7KkaUqibP3G5-V8mNLMtsK_2g&sig2=JXG6ocAkvo0InIAdpQ29qA

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Brak. 

Pozdrawiam, Cruelsky

**Comment by Shon-su** [comment]
dropią go 4 stworki z szansą 8%
wowhead.com/npc=2248
wowhead.com/npc=2249
wowhead.com/npc=2250
wowhead.com/npc=2251

**Comment by Morgahard** [comment]
Ubijałem te stwory dwie godziny (godzinę jednego dnia 2x buf + drugiego
dnia). Palladynem jeden schodzi w 15 sekund.

http://www.wowhead.com/npc=2251/giant-yeti
http://www.wowhead.com/npc=2250/mountain-yeti

Nie lubię kiedy z wieloletnich graczy chcących pomóc robi się debili
(prawie 11 lat z wowem, tester uldu na Todzie). 8% to 8 na 100, a mam q nie
oddany, lecę na everyquescie.
Dzisiaj zbadam jaskinię z dwoma kolejnymi mobami, które mi Pan podał.
Pochylcie się nad tym lootem, sprawdzcie.

Mimo wszystko dziękuję za odpowiedź :) Będę zgłaszał inne napotkane błędy
podczas loremasterowanie.
Cruelsky

2017-03-04 21:44 GMT+01:00 Shon-su <notifications@github.com>:
