### ISSUE TITLE
[INSTANCE] Zul'Farrak schody

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#774]
**Opis**:
Kiedy otwierana jest klatka z NPC w trakcie, kiedy mamy aggro, po jej otwarciu moby typu Sergeant Bly atakuja moba, ktory atakuje nas, a po jego smierci wracaja do klatki. Zespawniione juz na dole moby biegna po schodach, a potem z nich... "zlatuja" w powietrzu, bo nie lapia aggro (bo NPC siedza w otwartych juz klatkach). Po jakims czasie moby przestaja wbiegac. Po ich zabiciu nie dzieje sie zupelnie nic, nie spawnuje sie kolejna fala, a NPC dalej stoja w klatkach.

**Jak powinno byc** Powinno byc tak, ze nie wazne co, NPC **nie wracaja** do klatek i event powinien byc kontynuowany. Jezeli zrobienie tego nie jest w jakis sposob mozliwe, dodajcie opcje resetowania encountera (z zabezpieczeniami, zeby ktos nie naspawnowal fali mobow pod schodami tysiac razy i wbil instant 10 leveli;d)

[edit]
z tego co sie wypytalem, ten bug wystepuje, kiedy otwieramy klatki majac aggro. Zeby temu zapobiec mozna albo fixnac jakos normalnie, albo ustawic im, zeby ignorowaly wszystkie hostile NPC oprocz tych zespawnionych. Lepiej jest oczywiscie sprawic, zeby nie wracaly do klatek ;d

**Comment by kubowe112** [comment]
Event zbugowal sie mi rowniez na dole po ubiciu wszystkich fal.
