### ISSUE TITLE
Trial of sea lion

### ISSUE THREAD

**Issue by LordAnayami** [RaphaelSunwell/Sunwell-BugTracker-SCv2#782]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Trial of sea lion

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Nie mogę znaleźć Pendant of endurance, pomimo, iż kręcę się w okolicy zaznaczonej na mapie, nigdzie nie widać skrzyni.
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Powinna skrzynia być w miejscu, podanym przez koordynaty. 
**Co należy zrobić, aby odtworzyć ten błąd**:
Pływać w okolicy zaznaczonej na mapie i znaleźć skrzynie. 
1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by LordAnayami** [comment]
W miejscu pokazanym na video przez osobę, która to zdobyła też nie ma.

**Comment by LordAnayami** [comment]
![image](https://cloud.githubusercontent.com/assets/25817718/23590120/843f926c-01da-11e7-9ae7-80f517442184.png)

**Comment by LordAnayami** [comment]
Prosiłbym o przebadanie sprawy, szukałem go przez godzinę, jeżeli można, to prosiłbym o uzyskanie go, gdyż potrzebuje go do questa, a jak widać, nie ma go u mnie tam, gdzie powinien być. Z góry dziękuję.

**Comment by Shon-su** [comment]
potwierdzam że jest dodany. znajduje się na 38.9 | 38.1 w silverpine forest. Po update serwera ( sprawdzić changelog) będzie przestawiony w miejsce oznaczone na mapie.
