### ISSUE TITLE
Quest item respawn na instach

### ISSUE THREAD

**Issue by kubowe112** [RaphaelSunwell/Sunwell-BugTracker-SCv2#783]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest itemy na instach nie respia sie. Dowody nie sa jakies betonowe:
1. Quest itemy respily sie na  Nostalriusie
2. Wbrew logice byloby gdyby tylko jedna osoba mogla ukonczyc questa na inscie, gdy mozna je sharowac.

**Obecne działanie**: 

**Oczekiwane działanie**: Powinny sie respic.

**Co należy zrobić, aby odtworzyć ten błąd**: Zebrac ksiazke na scarlet monastery Library, automaty na gnomeregan, czy urny na Uldaman.

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Akha72** [comment]
Ile czekałeś na ten resp? Ja na Shadowfang Keep po zabiciu lasta cofnąłem się do książki (http://wotlk.openwow.com/quest=1013), którą wcześniej zebrała inna osoba w czasie bicia przedostatniego bossa i item normalnie się zrespił.

**Comment by kubowe112** [comment]
Ciezko powiedziec, ile czekalem;  ns Scarlet Monastery kilkanascie minut? W tym czasie wszyscy powinni zebrac a nie dopiero druga osoba.

**Comment by Akha72** [comment]
To faktycznie może być coś na rzeczy, bo comment z wowheada twierdzi, że książka z SM powinna się respić około minuty. Na resztę nie patrzyłem, ale w takim wypadku to zgłoszenie robiłoby sens.
