### ISSUE TITLE
[TALENT] ARDENT DEFENDER

### ISSUE THREAD

**Issue by mateusznin123** [RaphaelSunwell/Sunwell-BugTracker-SCv2#784]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Problem dotyczy Talentu w drzewku Paladyna - Protection o nazwie ARDENT DEFENDER.

**Obecne działanie**: Witam serdecznie. Talent o nazwie ARDENT DEFENDER mimo że jest wymaksowany nie odpala się podczas gdy moje hp spada poniżej 35 % i nie leczy mnie o 30 % mojego max hp w chwili gdy otrzymam śmiertelne obrażenia.

Link ze zdjęciami poniżej:
http://imgur.com/a/sQLLw

**Oczekiwane działanie**: Talent powinien działać zgodnie z  jego opisem: http://imgur.com/c7ntuAc. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wymaksować skill ARDENT DEFENDER.
2. Iść na moby.
3. Zbić się poniżej 35 % hp a następnie pozwolić mobą zadać nam śmiertelny hit.

**Comment by Rosenkrantz** [comment]
Ten talent leczy zależnie od skilla defense - a konkretnie, od DODATKOWEJ ilości, jaką masz.
Przy 0 dodatkowego defense = 0 heala
Przy 140 dodatkowego defense = 30% maxHP heala.
Pomiędzy - interpolacja liniowa.

Przy lvlowaniu jest wysoce prawdopodobne, że nie masz ani jednego przedmiotu z "Defense Rating". W takiej sytuacji, część dotycząca leczenie nie będzie się aktywować i jest to najzupełniej poprawne. 

Jeżeli jednak masz dodatkowy Defense (W karcie postaci, w zakładce Defenses, gdy najedziesz na "Defense" masz np 400+54 - 400 to bazowa wartość, 54 to ta dodatkowa, o którą chodzi) i talent wciąż nie działa, rzeczywiście jest zbugowany.

**Comment by mateusznin123** [comment]
Dziękuję za odpowiedź. W takim razie opis skilla kuleje, nikt nie jest w stanie się domyślić ze chodzi o ten dodatkowy def rating a nie ten bazowy podstawowy.

**Comment by Radeghost** [comment]
do zamkniecia
