### ISSUE TITLE
[Achievement][Tytuł]

### ISSUE THREAD

**Issue by Paroof** [RaphaelSunwell/Sunwell-BugTracker-SCv2#786]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Pomimo ukończenia wszystkich wymaganych achievementów nie otrzymałem tytułu "The Love Fool". 

**Obecne działanie**: brak tytułu

**Oczekiwane działanie**: chciałbym otrzymać powyższy tytuł ;)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Możliwe, że bug powstał w wyniku tego, że pokonałem Apothecary Trio tej samej nocy co wyszedł event a na drugi dzień było to zamieszanie z neckami. Może przez to w grze mam zaliczony achiv a w logach sie gdzieś pogubiło (nie wiem, nie znam się na tym ;) )
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/achievement=1693
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

![bez tytulu](https://cloud.githubusercontent.com/assets/26213381/23597207/14dfa036-0231-11e7-92d3-1d9a14af3e45.jpg)

**Comment by Rosenkrantz** [comment]
Screen pokazuje że masz suwak do przesunięcia listy tytułów w dół - wiem, że to banalne pytanie, ale na pewno nie masz tego tytułu tam niżej?
