### ISSUE TITLE
(Quest) (Ally) Time to Kill

### ISSUE THREAD

**Issue by greywolvee** [RaphaelSunwell/Sunwell-BugTracker-SCv2#794]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po powrocie z Orgrimmaru i rozmowie z Thrallem dowiadujemy sie że Undercity zostało zajęte przez zdrajce. Król Varian Wrynn zleca Ci wejscie do portalu do Undercity i porozmawianie z siłami które sa po drugiej stronie teleportu.
**Obecne działanie**: Po przyjęciu zadania "Time to Kill" otwiera się portal do UC lecz nie jest interaktywny i nie teleportuje po nacisnieciu na niego.

**Oczekiwane działanie**: Portal powinien przenosić na Tirisfal Glades, tuż przy wylocie z kanałów Undercity

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
jest już gdzieś zgłoszenie, generalnie bitwa o UC nie jest oskryptowana i portal blokuje dostęp.
