### ISSUE TITLE
[HUD] [PL] Talent Inspect 

### ISSUE THREAD

**Issue by Volpin** [RaphaelSunwell/Sunwell-BugTracker-SCv2#8]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Nie wykrywa talentów innych graczy w trakcie inspectu.

**Oczekiwane działanie**: Pokazywanie pełnego drzewka talentów gracza

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wystarczy spróbować sprawdzić czyjeś talenty
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by xsitdev** [comment]
Zostalo wprowadzone dnia wczorajszego, nie bug, a blad konfiguracji emulatora 👍
