### ISSUE TITLE
[quest] Investigate the Alchemist Shop [part 2 of 3]

### ISSUE THREAD

**Issue by MorgothPalantir** [RaphaelSunwell/Sunwell-BugTracker-SCv2#80]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Quest item nie działa na mobie questowym - nie można ukończyć.

**Obecne działanie**: W miejscu, w którym należy zrobić questa używa się itemu do zespawnienia mobów (Rift Spawn), kiedy mają 1 hp są zestunowane i użyje się na nich itemu questowego on nie działa. Widoczny jest komunikat "you can't do that yet"

**Oczekiwane działanie**: W miejscu, w którym należy zrobić questa używa się itemu do zespawnienia mobów (Rift Spawn), kiedy mają 1 hp są zestunowane i używa się na nich itemu questowego powinien pojawić się item (Filled Containment Coffer), który można zebrać do ekwipunku.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Mieć maga o minimum 15 levelu
2. Wziąć pierwszą część questa od mage trainera "Report to Anastasia"
3. Wziąć kolejną część questa u NPC Anastasia Hartwell w Undercity (mage trainer)

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=1960
2. http://wotlk.openwow.com/item=7292
3. http://wotlk.openwow.com/npc=6492

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Towoku** [comment]
Ah, az musze stworzyc postac i sprawdzic ten Q :D Zedytuje za dzien czy 2 i sie wypowiem (w ostatecznosci swoj słaby skrypt dam ;p)

**Comment by Towoku** [comment]
http://pastebin.com/Te3WBU2J  skrypt referencyjny, bodajze tez uzywalem jakies reference z tego głownego cora z wotlka(juz nie pamietam jak sie to zwie :P). Skrypt nie jest idalny, nie wiadomo czy wam do bazy podpasuje, ktos musi to zobaczyc. Był stworzony na potrzeby ToD, z własnej inicjatywy i był to moj 1 skrypt. Jako ze ragehost portaktowal mnie nie miło i wykickowal z czatu prawe bez powodu co mnie troche poirytowało, wiecej skryptow  jakos nie mam ochoty udostepniac ;)  a widze ze macie jakies podstawowe bazy bo wiekszosc z tych questowych błedów sam łatałem na ToDie(przynajmniej zanim zaczełem pracowac ;p). Pozdrawiam :)

**Comment by Shon-su** [comment]
poprawione

**Comment by Rastlinek** [comment]
Witam!
Ten quest dalej nie działa tu jest filmik jak zrobiłem https://youtu.be/lIudwxoM5k8 mam nadzieję że to pomoże
