### ISSUE TITLE
Minor Wizard Oil

### ISSUE THREAD

**Issue by VintageRuah** [RaphaelSunwell/Sunwell-BugTracker-SCv2#801]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:https://images83.fotosik.pl/421/17109ded9b48d70d.jpg

**Obecne działanie**: Otóż nie można użyć jak widać na obrazku Minor Wizard Oil na Heirloom.
Do którego potrzebny jest tylko poziom postaci, a nie item lvl.

**Oczekiwane działanie**: Powinno się móc użyć Minor Wizard Oil
od 1 item lvl do 165 item lvl. Włączając w to minimalny swój 5 lvl postaci.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić minimum 5 lvl postaci.
2. 
3. Nałożyć Minor Wizard Oil na podany Staff

**Linki WoWHead/OpenWoW**:

1. Informacje do Minor Wizard Oil: http://wotlk.openwow.com/spell=25124
2. Pokazuję poprawne działanie w 7:43 minucie: https://www.youtube.com/watch?v=ROvKJuJTqK0 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Akha72** [comment]
Temporary weapon enchantments wymagają x lvla zarówno od zakładającego, jak i od itemu. Dlatego właśnie na broń heir założyć można tylko (http://wotlk.openwow.com/spell=3115) oraz (http://wotlk.openwow.com/item=2862). Info na ten temat można znaleźć w wowhead commentach olejków, osełek oraz heir weaponsów. Powrzucam jeśli będzie trzeba jak wrócę, poza tym ten filmik to z jakiegoś priva jest.

**Comment by VintageRuah** [comment]
Wymóg jedyny do założenia olejku to 5 lvl postaci: http://wotlk.openwow.com/spell=25124 Jest jasno napisane co potrzeba by założyć olejek na broń. Nie widzę tu ze strony blizzarda informacji że nie można nosić olejka na heirloom. Tylko że jest on nie dostępny powyżej 165 item lvl. No i oczywiście 5 req lvl postaci.

**Comment by Akha72** [comment]
http://www.wowhead.com/item=20744/minor-wizard-oil#comments

(3.0.9 - As of Patch 3.0.9 this does not apply to Heirloom weapons, specifically Dignified Headmasters Charge.

Error message says "Item is too low level.")

(3.1.3 - Target weapon should have Item lvl 5 or greater.)

Poszperam w archiwach twinkinfo, jeżeli tyle nie wystarczy do zamknięcia zgłoszenia, ale jest czarno na białym, więc nwm jakie tutaj można mieć wątpliwości.
Za celowe wprowadzanie w błąd powinny być wyciągane konsekwencje od zgłaszającego.
