### ISSUE TITLE
[RAID][BOSS] Razorgore the Untamed - Blackwing Lair

### ISSUE THREAD

**Issue by zasmazka11** [RaphaelSunwell/Sunwell-BugTracker-SCv2#806]
**Opis**:
Jest problem na samym początku Blackwing Lair co uniemożliwia dalsze przejście do insty.
**Obecne działanie**: 
Jak przejmujemy kontrole nad 1 bossem za pomocą Orba wszystko jest ok.
**Oczekiwane działanie**: 
Jednak kiedy próbujemy zniszczyć jajko za pomocą skilla "Egg destroy" z jajkiem nic się nie dzieje
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejść do Blackwing Lair
2. Odpalić Bossa
3. Spróbować zniszczyć Jajko

**Linki WoWHead/OpenWoW**:

1. https://www.youtube.com/watch?v=eqEeqPfL9mA
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Hooraga** [comment]
https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/408  
to już zostało zgłoszone.

**Comment by Kaczusia** [comment]
Mozna to zrobic czekajac, po jakiś 5-7min traci sie kontrole i mozna zabic bossa
