### ISSUE TITLE
[DEATH KNIGHT][SPELL] Blood Tap

### ISSUE THREAD

**Issue by Rufusan** [RaphaelSunwell/Sunwell-BugTracker-SCv2#808]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Zbugowane działanie skilla blood tap. 

**Obecne działanie**: Skill blood tap odnawia 2 runy blood, z czego jedną w postaci death rune a drugą w blood.

**Oczekiwane działanie**: Powinien odnawiać  tylko 1 runę blood i zmienić ją na death.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wykorzystać runy blood.
2. Użyć skilla blood tap.
3. Zaobserwować odnowioną runę blood i death.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=45529 opis działania spella
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Radeghost** [comment]
a to nie ma zwiazku z talentami?

**Comment by Rufusan** [comment]
Naprawione, sprawdzałem talenty przed zgłoszeniem.
