### ISSUE TITLE
[POSTAĆ] Złe działanie flagowania gracza jako pvp

### ISSUE THREAD

**Issue by hunterka** [RaphaelSunwell/Sunwell-BugTracker-SCv2#81]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po wyłączeniu flagi pvp (world pvp) po 5 minutach powinna zniknąć możliwość bicia nas przez wrogie frakcje na terenie dla nas friendly.

**Obecne działanie**: Po wyłączeniu flagi czas 5 minut odnawia się z każdym combatem; jeśli wyłączymy flagę i zaczniemy bić moby w czasie kiedy nam zostało np. 2 minuty do wyłączenia flagi, po combacie ten czas zresetuje się znowu do 5 minut.

**Oczekiwane działanie**: Na czas 5 minut do wyłączenia flagi nie powinien mieć wpływu combat pve, jedynie gdybyśmy się w tym czasie bili pvp z innym graczem to wówczas ten czas się powinien resetować.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Należy w terenie friendly włączyć flagę pvp, następnie ją wyłączyć i po upłynięciu minuty lub dwóch, tak żeby było widać, że czas się zmienił na inna wartość niż 5 minut, zaatakować moba. Po skończeniu combatu czas znowu resetuje się do 5 minut.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by MonichSC** [comment]
Proszę o testy. dalej zbugowane?
