### ISSUE TITLE
[PROFESJE] Alchemia - potion master

### ISSUE THREAD

**Issue by Heartbraker** [RaphaelSunwell/Sunwell-BugTracker-SCv2#813]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Potion master daje szansę na dodatkowe potiony podczas ich tworzenia.

**Obecne działanie**: Na przestrzeni ostatnich paru dni (po jakimś restarcie) potion master przestał działać, w ogóle nie procuje dodatkowych potionów

**Oczekiwane działanie**: Przy tworzeniu potionów przez potion mastera powinna być szansa na dodatkowe 1-4 potiony (czyli w sumie 2-5)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić specjalizację potion master
2. Robić potiony
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Potion_Master
2. 
3. 

Znajomy posiadający elixir mastery napisał, że ta specjalizacja prawdopodobnie też nie działa, ale nie wiem jak obszerne były jego testy.

**Comment by KamaN442** [comment]
a ile potionow robiles 10? bo ja robilem 3 dni temu 120 i normalnie dzialalo

**Comment by Heartbraker** [comment]
Jeden zrobiłem, nie procnęło i dlatego zgłosiłem... /s

Na ponad 100 potek z potion master i 40 flaszek z elixir master nie było żadnych proców + inne osoby z alchemią które w tym czasie o to pytałem też nie miały żadnych proców ze specjalizacji. Coś musiało być spieprzone po jednym z licznych ostatnio restartów/crashy, już jest ok.
