### ISSUE TITLE
[ADDON] Auctioneer nie działa.

### ISSUE THREAD

**Issue by Slepotek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#817]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:[ADDON] Auctioneer nie działa.

**Obecne działanie**: Podczas wystawiania aukcji za pomocą "Appriser'a" wyskakuje błąd o nie możności usunięcia przedmiotu z torby. Dodam, że na innych serwerach działa normalnie. 

**Oczekiwane działanie**: Użycie opcji ""Appriser'a" powinno wystawić aukcje w Auction Housie

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zainstalować AuctioneerSuite- odpowiednią wersję 5.8.4723
2. Spróbować wystawić aukcję za pomocą zakładki Appriser
![wowscrnshot_031517_170714](https://cloud.githubusercontent.com/assets/26437452/23958283/e890ce4c-09a1-11e7-8506-68372de003d3.jpg)

3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Sheime** [comment]
Witaj , ściagnij Auctioneer na wersje 4.0.1 z cursa :) mi pomoglo.
Pozdrawiam :)
