### ISSUE TITLE
[Quest] Stranglethorn Fever (ID 349)

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#82]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak dokładnego opisu w ww. queście.

**Obecne działanie**: http://i.imgur.com/StpvmC7.jpg

**Oczekiwane działanie**: Powinien zostać dodany kompletny opis questa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa od Witch Doctor Unbagwa w SV.

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/quest=349 (również błedny opis)
2. http://db.vanillagaming.org/?quest=349 (opis questa poprawny, ale ilość fangów do zdobycia ma wynosić 1)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
35.3/60.4 Stranglethorn Vale

**Comment by Shon-su** [comment]
done
