### ISSUE TITLE
[Umiejętność]Runeforge

### ISSUE THREAD

**Issue by tociek84** [RaphaelSunwell/Sunwell-BugTracker-SCv2#821]
**Opis**:Dzień przed nocnymi problemami z serwerem, robiąc początkowe questy dla dk, miałem normalnie umiejętność runeforge. Po nocnych problemach takowej w spellbooku nie posiadam. Wyexpiłbym nową postać, ale szkoda mi dnia exp boosta i 1k na dual spec. Umieszczam dowód w postaci ss: http://imgur.com/a/T13tU

**Obecne działanie**: Brak umiejetności Dk "Runeforge"

**Oczekiwane działanie**: Posiadanie Runeforge

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by jatoja** [comment]
Też mam ten sam problem na moim dk :(

**Comment by jatoja** [comment]
Też mam ten sam problem :(
