### ISSUE TITLE
RDF BUG

### ISSUE THREAD

**Issue by Sheime** [RaphaelSunwell/Sunwell-BugTracker-SCv2#822]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Problem z Party na RDF

**Obecne działanie**: Problem polega na tym , gdy 2-3 osoby wyjda z party na rdf'ie , uniemożliwia to wyjsciem przyciskiem "ikona na minimapie"  oraz gdy osoby wyjda z party (nie skonczony dungeon) , nie da sie wejsc spowrotem do niego . i trzeba uzyć spirita 
Dzisiaj zdazył mi się ten bug az 4-5 razy na dungeonach 15-30 lvl .
**Oczekiwane działanie**: , Kazdy gracz moc powinien wyjsc po skonczony / nie udanym dungeonie , 

**Co należy zrobić, aby odtworzyć ten błąd**: 

1.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by kubowe112** [comment]
Potwierdzam, po wyjscu chyba 3 graczy znika: mozliwosc dobrania kolejnych osob, wejscia do instancji oraz ikonka przy mini mapie.
