### ISSUE TITLE
[Shaman][Ability] Spirit Wolves Bash

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#824]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Bash to spell Spirit Wolves, który stunnuje cel na 2sek.

**Obecne działanie**: Obecnie Bash nie posiada Cooldownu i walka na shamana wygląda mniej więcej w ten sposób. Dostajesz 2sec stuna następnie 1sec i 0.5sec aż nie zostanie wyczerpany limit DR, w dodatku gdy chcesz trinketować pierwszego stuna dostajesz drugiego tak szybko przy pecie ustawionym na auto, że nawet ikonka debuffu nie znika.

**Oczekiwane działanie**: Bash powinien mieć 45sec CD, nie wiem w czym tkwi problem. Skill jest przypisany do wszystkich 3 wilków więc łącznie występuje jeden Bash. Obecnie albo nie ma on CD albo wszystkie 3 wilki posiadają osobny Bash. Nawet opis skilla "Command your spirit wolves to bash the target" sugeruje, że jest on przypisany do wszystkich 3 wilków.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Danieloses** [comment]
Proszę o jak najszybsze naprawienie tego, bug jest strasznie broken i uniemożliwia niektórym compom arenowym zwycięstwo na beastcleave przez praktycznie brak możliwości trinketowania tego stuna i o połowę za długie jego działanie, w dodatku jest ten stunlock wkonywany automatycznie przez pety ustawione na auto i drugi stun wchodzi tak szybko, że nie zdążymy użyć żadnej umiejętności po trinkecie.

**Comment by Crackaw** [comment]
3 wilki, a nie 2? Problem jest taki, że wszystkie umiejętności są dzielone oprócz tej i mają korzystać ze wspólnego cd, a mają osobny i jeszcze drugi wilczek czeka, aż zejdzie stun co praktycznie daje 1,5 sec stuna

**Comment by Crackaw** [comment]
It's not a bug it's a feature 
![image](https://cloud.githubusercontent.com/assets/25255402/24366624/f6010552-1319-11e7-9e74-5d8350dca969.png)
A tak na serio to każdy wilk ma osobne spelle więc i stun wchodzi jeden po drugim, z tym, że jeden dłuższy 1s drugi odpowiednio krótszy ~0,5 s, na są również filmiki z tego okresu na którym widać, że stuny są 2, o ile bash jest na auto, jeżeli czegoś nie rozumiem, to proszę o dowód.

**Comment by Danieloses** [comment]
Problem jest taki, że tak jak napisałeś mają korzystać ze wspólnego CD, ale był bug związany z tym po ustawieniu Basha na automatyczny po każdym summonie wilków, tylko w tej sytuacji ten podwójny Bash występował. Nie mogłeś ręcznie zrobić podwójnego stuna, ponieważ miała ten wspólny CD, który to ograniczał.

**Comment by Crackaw** [comment]
Tobie chodzi o opóźnienie między stunami, że nic nie da się zrobić? Bo z tego co widzę, nie występuje ono tak jak powinno.
