### ISSUE TITLE
[QUEST] Leave No One Behind

### ISSUE THREAD

**Issue by Owlseer** [RaphaelSunwell/Sunwell-BugTracker-SCv2#825]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Quest polega na przyprowadzenie 3 (trzech) NPC poprzez użycie na nich quest itemu (Crusader's Bandage 38330) do Quest Givera (Dr. Rogers 28125)

**Obecne działanie**: Nie zalicza zadnego z przyprowadzonych NPC.

**Oczekiwane działanie**: Po przyprowadzeniu każdego z NPC (28136, 28142, 28148) powinno zaliczyć daną część questa. https://www.youtube.com/watch?v=Evx9-8J1Z8w

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Wziąć questa (12512). Posiadać 74 poziom.
2.  Użyć Itemu z questa (38330) na jednym z NPC.
3.  Przyprowadzić pod Dr. Rogers (28125)

**Linki WoWHead/OpenWoW**:

1.  http://www.wowhead.com/quest=12512/leave-no-one-behind
2.  http://www.wowhead.com/npc=28125/dr-rogers
3.  http://www.wowhead.com/npc=28136/crusader-jonathan
4.  http://www.wowhead.com/npc=28142/crusader-lamoof
5.  http://www.wowhead.com/npc=28148/crusader-josephine
6. http://www.wowhead.com/item=38330
7. https://www.youtube.com/watch?v=Evx9-8J1Z8w

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:  
Map: 571 (Northrend) Zone: 66 (Zul'Drak) Area: 4279 (Drak'Sotra) Phase: 4294967295
X: 5255.219238 Y: -3527.563721 Z: 291.692993 Orientation: 1.775001
grid[41,25]cell[6,3] InstanceID: 0
ZoneX: 58.624554 ZoneY: 72.496536
GroundZ: 289.204956 FloorZ: 291.692047 Have height data (Map: 1 VMap: 1 MMap: 3881692764)

**Comment by Shon-su** [comment]
spróbuj iść blisko NPC-a lub nie na mouncie może pomoże. Ostatnio jak robiłem działało bez problemu

**Comment by StepUP777** [comment]
Quest jak najbardziej dziala i brak problemow.
