### ISSUE TITLE
[Quest] Gambling Debt

### ISSUE THREAD

**Issue by Artanis02** [RaphaelSunwell/Sunwell-BugTracker-SCv2#826]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie da się zakończyć questa (jak w tytule)

**Obecne działanie**: Mob zamiast zmieniać nastawianie z hostile na neutral i oddawać q item, po prostu ginie.

**Oczekiwane działanie**: W czasie bicia moba powinien on przy około 10% się poddać i dać nam q item.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Wziąć q
2. Zacząć bić moba
3. zabić moba

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/g00/quest=11464/gambling-debt
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Howling Fjord 34.80

**Comment by Bainit123** [comment]
Działa, za szybko go zabijasz. Zdejmij bron i spróbuj bić wolniej.

**Comment by Artanis02** [comment]
Dzięki, pomogło :)
