### ISSUE TITLE
[NPC] Grave Robber [218]

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#832]
NPC Grave Robber ID 218 nie powinny chodzic. Powinny stac w miejscu. nie mam zadnych dowodow poza tym, ze pamietam to z globala sprzed Cataclysm (zginalem z ich reki wiele razy na low levelu).

**Comment by Shon-su** [comment]
cóż Cataclysm wyszedł 7 lat temu. Niestety nie mogę zdać się na twoją pamięć, by zmienić tak kluczowy element gry.

**Comment by Radeghost** [comment]
Mówisz serio czy to sarkazm xd

**Comment by Radeghost** [comment]
Btw pisz które zamykasz a które fixujesz bo nie wiem czy dostarczyć więcej dowodów czy nie
