### ISSUE TITLE
Powiadomienia Gildiowe/Friendlist Online/Offline

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#84]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Gdy osoba dodana na Friendlist loguje się do gry powinno wyskakiwać powiadomienie przykładowo "Gracz has come online.", a w przypadku wylogowania "has gone offline" jednak to nie następuje. Tak samo z opcją o powiadamianiu online/offline członków gildii.

**Obecne działanie**: Powyżej opisana opcja nie działa, spytałem parę osób z gildii jak to wygląda u nich i także potwierdzili nie działanie tej opcji. Jest to zdecydowanie wina serwera.
**Oczekiwane działanie**: Opis

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać dowolnego gracza na Friendlist.
2. Musi się on wylogować/zalogować.
3. Brak powiadomienia.

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Mithras2801** [comment]
MI pokazuje

**Comment by Danieloses** [comment]
Też zauważyłem, że właśnie zaczęło działać, ale wcześniej na 100% nie działało, bo sprawdzałem z kumplami być może warto to sprawdzić

**Comment by Danieloses** [comment]
Kolejna uwaga, właśnie jedna osoba się zalogo

**Comment by morgaur** [comment]
U mnie z kolei jeśli chodzi o friendlist to gdy osoba z listy się wyloguje ( i tylko wtedy) mam na chacie spam  ze się wylogowała dopóki nie otworzę i zamknę listy. Nie wiem czym to spowodowane (pewnie u mnie coś). Ale wcześniej działało normalnie i z dnia na dzień taki bonus:)

**Comment by Mithras2801** [comment]
Friend lista nie działa / guild ann działa

**Comment by Danieloses** [comment]
podobny problem jest z wchodzeniem lub wychodzeniem z custom kanału, w dodatku zauważyliśmy z gildią po dłuższym czasie, że guild annoucement czasem działa lecz zdecydowanie częściej nie

**Comment by ellynd** [comment]
Od siebie dodam, że jeżeli ktoś jest u nas w gildii i jest dodany na naszej friend liście to nie pokaże sie żadne powiadomienie jeżeli wszedł lub opuścił grę (przynajmniej u mnie tak jest).
