### ISSUE TITLE
[ULDUAR]Freya (Ancient Conservator)

### ISSUE THREAD

**Issue by Scythe-Kosiarz** [RaphaelSunwell/Sunwell-BugTracker-SCv2#840]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Zbyt szybki cast przez co czasami grzyby sie nie pojawiaja. Cast tego spella powinien trwac 5 sekund. Widac to np tutaj https://youtu.be/z0GD8QNQUgA?t=160

**Obecne działanie**:  zbyt szybki cast

**Oczekiwane działanie**:  conservator grip powinien byc castowany 5 sekund

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Patrzec na dlugosc casta
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=32906/freya
2. http://www.wowhead.com/npc=33203/ancient-conservator
3. http://www.wowhead.com/spell=62532/conservators-grip

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by FinessaSunwell** [comment]
ANCIENT CONSERVATOR after hes instantly spawned already gives raid the debuff. 5 sec before the mushrooms are spawned. THAT is problem - taunt, even attack and healing not possible.

**Comment by gretowy** [comment]
Wczoraj na 25 **w ogóle nie występował** silence! Dodatkowo przypominam, że jest to nie tyle czysty silence co blokada używania **wszelkich spelli** (warek też nie powinien móc ich używać)

**Comment by raveeneer** [comment]
Potwierdzam, na 10 jest to problem, a na 25... no cóż na 25, ostatnio w ogóle nie było silence'a.
