### ISSUE TITLE
Ulduar - Kologarn, Council of Iron, Freya. Hodir?

### ISSUE THREAD

**Issue by FinessaSunwell** [RaphaelSunwell/Sunwell-BugTracker-SCv2#843]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: ULDUAR 10 normal mode boss. 

**Obecne działanie**: 
Yesterday We were at 7 bosses, so far i noticed, that 4 of them have bugs, which are benefitial or overly unfair to raid. 

**Oczekiwane działanie**: Please take a look and repair it.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Kologarn Overhand smash instant on pull + Melee dmg = over 40K+! dmg to tank = instant kill.
Adds spawned from killed hand (5x Rubbme elemental) have melee range AOE dmg with stacking +Physical dmg taken debuff, the debuff does not stack according to the offtank.

2. Iron Council - Stormcaller Brundir - Lightning whirl is not interruptible. BUG. 
Stormcaller Brundir- Lightning tendrils - He should fly to RANDOM target, not only stay at his main target (tank) This makes the phase overly easy.
Stormcaller Brundir: Overload : From 3.1.2 patch the range should be 20 yard, not 30, as it is right now.

3. Freya - Ancient Conservator issue.  The add is spawned 5 sec before any mushroom is spawned and it gives instantly Conservators Grip, which makes Tank taunt and casting (protpaladin meh) and even misdirect impossible, usually kills someone. Correctly the add should be spawned, then after 5 sec (conservators grip is 5 sec cast spell) mushrooms are spawned at the same time raid is silenced by the spell. If add gets to tank, whos on freya and they both hit, its almost IK (and they have another attack as  sec is impossible to heal, so more or less it could lead to wipe, if it stays only on MT. 

4. Hodir - I was there just once, but it seems to me that frozen blows do not work how it was intended. I noticed just more physical damage, but no frost bonus DMG + no extra dmg to raid. I will confirm this first.
Hodir - Biting cold stacks should be clearable using DS as paladin. 
 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Kologarn
http://ptr.wowhead.com/spell=63978/stone-nova

2. http://wowwiki.wikia.com/wiki/Assembly_of_Iron

**Stormcaller Brundir**

    10 million hp on heroic, 3 million hp on normal
    Melee hits for: 8-10k, crit for 25k against leather on normal mode. 

    Spell nature chainlightning  Chain Lightning - Deals 5550 to 6450 nature damage on heroic or 4163 to 4837 nature damage on normal. Can chain onto an additional target within 10 yards up to five targets. Spread out to avoid chaining this ability. Can be interrupted and is affected by effects which increase casting time.
    Spell nature wispsplode  Overload - Similar to Loken or Murmur this 6 second channeled spell deals 25,000 nature damage on heroic or 20,000 nature damage on normal to all targets within 20 yards of Brundir. Brundir generates the emote "Stormcaller Brundir begins to Overload!" while casting. While casting gains the Stormshield effect which deals 250 nature damage and grants immunity to stun effects.
        Spell nature wispheal  Lightning Whirl (1 dead) - Deals 5655 to 6345 nature damage on heroic or 3770 to 4230 nature damage on normal per bolt. F**ires multiple bolts per second and needs to be interrupted as quickly as possible.**
            Spell nature lightningoverload  **Lightning Tendrils** (2 dead) - Brundir lifts off into the air and gains an aoe ability that deals 5000 nature damage per second on heroic or 3000 nature damage per second to all targets in close range. **Will randomly switch targets** and needs to be kited away from the raid to minimize damage. Raid members should spend this portion of the fight keeping as far away from Brundir as possible. Resets aggro when he lands.
            Spell nature lightningshield Stormshield (2 dead) Brundir also becomes immune to stun effects once Steelbreaker and Runemaster Molgeim are dead, as he is not previously. Stun effects against him before this are affected by diminishing returns however. 

http://www.wowhead.com/spell=61915/lightning-whirl#comments

3. 
    http://www.wowhead.com/npc=32906/freya
    http://www.wowhead.com/npc=33203/ancient-conservator
    http://www.wowhead.com/spell=62532/conservators-grip

4. http://www.wowhead.com/npc=32845/hodir#abilities

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by gretowy** [comment]
Potwierdzam, Frozen Blows nie działają poprawnie. Przede wszystkim boss nie ma na sobie buffa, po drugie z tego co zauważyłem, przynajmniej w melee range występuje AoE 4k frost dmg, nie wiem czy na całym raidzie (powinien). Pomimo widocznej frost aury na jego rękach dmg pozostaje bez zmian (tylko physical + 4k frost z AoE na tanku)

**Comment by gretowy** [comment]
Lightning Whirl nadal nie da się przerywać na 25tce, chociaż na 10tce działa. Nie byłoby to tak upierdliwe, gdyby dmg z tego spella był poprawny. Obecnie zadaje około 10k (a nie 5655 do 6345) z jednego bolta co powoduje, że ewentualne 2 bolty na 1 celu ubijają daną osobę.
