### ISSUE TITLE
[EOE] Drop

### ISSUE THREAD

**Issue by gretowy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#849]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wczoraj (23.03) na Eye of Eternity 25 padły spodnie z tokenu pod warka prot.

**Obecne działanie**: Nieodpowiedni item w tabeli lootu.

**Oczekiwane działanie**: Usunięcie podanego w linku przedmiotu z tabeli, ewentualne sprawdzenie tabeli lootu. Jeżeli podany przedmiot w niej nie występuje, będzie to oznaczało innego rodzaju bug.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 

**Linki WoWHead/OpenWoW**:

1. [BOSS](http://wotlk.openwow.com/npc=31734#abilities)
2. [Valorous Dreadnaught Legguards](http://wotlk.openwow.com/item=40547)
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Baggedmilk** [comment]
potwierdzam, czesto ten item dropi

**Comment by Crackaw** [comment]
#1096
