### ISSUE TITLE
Necki z walentynek

### ISSUE THREAD

**Issue by Baggedmilk** [RaphaelSunwell/Sunwell-BugTracker-SCv2#853]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 

**Obecne działanie**: mozna zalozyc neck z eventu walentynkowego

**Oczekiwane działanie**: nie powinno byc mozliwosci zalozenia necka z tego eventu (content 3.3.x)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. zalozyc neck z eventu
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=51807
2. http://wotlk.openwow.com/item=51804
3. http://wotlk.openwow.com/item=51806
http://wotlk.openwow.com/item=51805
**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Brilunes** [comment]
content 3.3 to jest icc wiec napewno nie byl wtedy. Wedlug wowwiki event ten wszedl w patchu 3.0.8 wiec content uldu.

**Comment by Baggedmilk** [comment]
jak ci ciezko znalezc to prosze http://www.wowhead.com/item=51807/sweet-perfume-broach napisane jak byk kiedy bylo dodane. przeczytaj rowniez komentarz

**Comment by Bainit123** [comment]
To nie bug, administracja świadomie włączyła. Na forum możesz gdzieś znajdziesz wpis MrCule na ten temat, jeśli dobrze poszukasz.
