### ISSUE TITLE
Power Word: Shield i Prowl

### ISSUE THREAD

**Issue by Valais** [RaphaelSunwell/Sunwell-BugTracker-SCv2#854]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: efekty obszarowe typu Death and Decay od DK wyrzucaja gracza z Prowla mimo aktywnego efektu Power Word Shield na druidzie
**Oczekiwane działanie**: Tylko umiejetnosci obszarowe typu active(np. Blood Boil, Blizzard) powinny wyrzucac ze stealth/prowl chronione przez PW:S

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Fixnac Kappa
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=5215
2. http://wotlk.openwow.com/item=42408
3. http://wotlk.openwow.com/spell=49937
4. http://wotlk.openwow.com/spell=49941
5. http://wotlk.openwow.com/spell=10187
**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Radeghost** [comment]
brak dowodow...

**Comment by Valais** [comment]
http://www.arenajunkies.com/topic/163617-power-word-shield-and-stealth/

Prowl dziala identycznie jak stealth z tym ze moze go breaknac rowniez fall dmg

**Comment by Rosenkrantz** [comment]
Aktualnie DND robi pushback, więc zdecydowanie nie jest pasywnym efektem, pewnie dlatego wyrzuca. Prawidłowe pytanie brzmi, czy DND powinien być aktywnym efektem (wyrzucac ze stealth mimo absorba + robic pushback).
