### ISSUE TITLE
[WARRIOR]

### ISSUE THREAD

**Issue by gretowy** [RaphaelSunwell/Sunwell-BugTracker-SCv2#855]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Źle naliczane Dodge i Parry z itemów.

**Obecne działanie**: W tej chwili trzeba nieco ponad 45 dodge rating na 1% dodge oraz bardzo podobną ilość parry na 1% parry. 

**Oczekiwane działanie**: Bazując na przeliczeniach w opisie itemów z avoidem na OpenWoW, przelicznik dodge powinien wynosić około 39,39 dodge rating na 1% dodge'a oraz około 49,4 parry rating na 1% parry.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 

**Linki WoWHead/OpenWoW**:

1. [Necklace of Unerring Mettle](http://wotlk.openwow.com/item=45262)
2. [Sand-Worn Band](http://wotlk.openwow.com/item=40107)

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Radeghost** [comment]
Open WoW to zadne zrodlo. Znajdz dowody np. na wowwiki (zaloz konto tam, najedz na Edit i szukaj w history z patcha 3.3.5, to byl koniec 2009 chyba), albo w poradnikach z 3.3 np elitist jerks.

**Comment by Akha72** [comment]
Podbijam, zmieńcie regulamin BT czy coś, żeby openwow służył tylko do podawania ID, bo to już któreś zgłoszenie bazujące na tym database.

**Comment by Unbugable** [comment]
Już pomijając fakt, że avo diminishing returns podlega.
