### ISSUE TITLE
[Quest] Return of the High Chief

### ISSUE THREAD

**Issue by Artanis02** [RaphaelSunwell/Sunwell-BugTracker-SCv2#857]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie działa Quest "Return of the High Chief"

**Obecne działanie**: Po otrzymaniu, a następnie aktywacji itemu w odpowiednim miejscu, nic się nie dzieje, NPC tylko wymawia kwestię i koniec, quest niezaliczony.

**Oczekiwane działanie**: Po aktywacji itemu NPC powinien wskrzesić martwych NPC dookoła i zacząć walkę z minibossem, z którego leci quest item.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć questa. (~23.43 Dragonblight)
2. Podejść do miejsca ~25.40 w Dragonblight
3. Użyć migającego przy tym miejscu obiektu do questa.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12069/return-of-the-high-chief
2. http://www.wowhead.com/item=36759/fragment-of-anubetkans-husk
3. http://www.wowhead.com/item=36760/anubar-prison-key

**Lokalizacja z koordynatów GPS X, Y, Z, Map)**: ~23.43 Dragonblight / ~25.40 w Dragonblight

**Comment by Radeghost** [comment]
dodaj jakies linki z yt

**Comment by Artanis02** [comment]
https://www.youtube.com/watch?v=dTV1htL_eRI

**Comment by Wofanique** [comment]
W moim przypadku quest zadziałał. Trzeba użyć klucz jak Roanauk Icemist jest żywy. Czasami leży martwy zabity przez okoliczne moby, wtedy dalsza sekwencja zadania nie zastartuje.

http://imgur.com/a/BPjh3
http://imgur.com/a/MwtUZ
http://imgur.com/a/YDF3h
http://imgur.com/a/o4HA3
