### ISSUE TITLE
[Quest] Argent Dawn Commission [5405]

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#859]
Zly gossip, brak '-' po "<class>"

powinno byc tak:

All who fight evil on behalf of the Argent Dawn must don our commission.  Wearing such will earn your right to claim rewards our quartermasters have to offer.

While under commission, you'll be able to acquire Scourgestones from slain Scourge; these are marks of insignia that they sometimes possess.  Procure these insignia and bring them to me.  For each set you turn in, you will receive our marker of heroism - the Argent Dawn Valor Token.

Achieve your destiny, <class> - join the fight today!

**Comment by Shon-su** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/17860936/24334643/11ad3c14-126e-11e7-87f8-362270fdc655.png)
Jak dla mnie wygląda ok

**Comment by Radeghost** [comment]
Brakuje myslnika  po klasie.

**Comment by Radeghost** [comment]
Github ucial mi po prostu class
