### ISSUE TITLE
[Quest] 14022 [A] i 14036 [H] - Pilgrim's Bounty (brakujacy NPC) (Pilgrim)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#86]
**Opis**: W alliance jak i hordzie nie da się oddać Q zaczynającego event.

**Obecne działanie**: W Alliance brakuje NPC - Gregory Tabor | W hordzie - Miles Standish.

**Oczekiwane działanie**: Quest ten zaczynający event powinno się kończyć u danych NPC i zaczybnać chain dalszy. ( w późniejszym zgłoszeniu będzie chain H i A)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć Q od Commonera któregoś
2. Iść do Qendera.
3. 

**Linki WoWHead/OpenWoW**:

1. NPC [A] Gregory Tabor - http://wotlk.openwow.com/npc=34675
2. NPC [H] Miles Standish - http://wotlk.openwow.com/npc=34677

3. http://www.wowhead.com/quest=14036/pilgrims-bounty [H]
4. http://www.wowhead.com/quest=14022/pilgrims-bounty [A]

5. Źródło - http://wowwiki.wikia.com/wiki/Quest:Pilgrim%27s_Bounty

**Comment by Shon-su** [comment]
poprawione, po update powinno być
