### ISSUE TITLE
[Item] 12815

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#862]
**Opis**: Tego itemu mzna uzywac tylko w wyznaczonych do tego miejscach - ale w kazdym miejscu powinno sie moc go uzyc TYLKO RAZ.

**Obecne działanie**: Mozna uzywac tego itemu w jednym miejscu pare razy co nam traci Charge

**Oczekiwane działanie**: przy jednej wiezy powinno sie moc go uzywac tylko raz - kiedy wieza jest zaliczona (quest 5098)

**Comment by Shon-su** [comment]
Jaki to jest quest?
