### ISSUE TITLE
[NPC] ID w opisie - Braki u vendorów [Pilgrim]

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#87]
**Opis**: Podane NPC nie posiadaja wszystkich itemów do kupienia.

**Obecne działanie**: Zagadujemy i otwiera się okno kupna z brakami.

**Oczekiwane działanie**: Podane NPC powinny posiadać możliwość kupienia danych itemów.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Podejść do wymienionych NPC
2. Sprawdzić zawartość kupna
3. 

**Linki WoWHead/OpenWoW**:

[Alliance]
1. Wilmina Holbeck <Pilgrim's Bounty Vendor> - http://wotlk.openwow.com/npc=34682
2. Ranisa Whitebough <Pilgrim's Bounty Vendor> - http://wotlk.openwow.com/npc=34783
3. Ikaneba Summerset <Pilgrim's Bounty Vendor> - http://wotlk.openwow.com/npc=34681
4. Elizabeth Barker Winslow <Pilgrim's Bounty Vendor> - http://wotlk.openwow.com/npc=34645

[Horde]
1. Rose Standish <Pilgrim's Bounty Vendor> - http://wotlk.openwow.com/npc=34683
2. Laha Farplain <Pilgrim's Bounty Vendor> - http://wotlk.openwow.com/npc=34684
3. John Rigsdale <Pilgrim's Bounty Vendor> - http://wotlk.openwow.com/npc=34787
4. Dalni Tallgrass <Pilgrim's Bounty Vendor> - http://wotlk.openwow.com/npc=34685

Pozostałe:
[Alliance] **Sprawdzić lokalizacje!**
1. Bountiful Barrel <Pilgrim's Bounty Supplies> - http://wotlk.openwow.com/npc=35337
2. Bountiful Barrel <Pilgrim's Bounty Supplies> - http://wotlk.openwow.com/npc=35338
3. Bountiful Barrel <Pilgrim's Bounty Supplies> - http://wotlk.openwow.com/npc=35340

[Horde] **Sprawdzić lokalizacje!**
1. Bountiful Barrel <Pilgrim's Bounty Supplies> - http://wotlk.openwow.com/npc=35341
2. Bountiful Barrel <Pilgrim's Bounty Supplies> - http://wotlk.openwow.com/npc=35342
3. Bountiful Barrel <Pilgrim's Bounty Supplies> - http://wotlk.openwow.com/npc=35343

**Proszę dokładnie sprawdzić itemy, które mają być kupowane. Timery / co które dają po otwarciu oraz te z wymaganiami np cooking.**

**Comment by Shon-su** [comment]
powinno być poprawione po update
