### ISSUE TITLE
[Quest] Tomb of the Lightbringer [9446]

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#871]
**Opis**: Quest dziala zle. NPC biegnie zamiast isc i ma jakies dziwne AI (czesto bijemy 3 moby, zabije 2 a on juz biegnie dalej).

**Obecne działanie**:  up, duzo bugow, npc sie nie zatrzymuje w danym miejscu etc

**Oczekiwane działanie**: caly quest jest na yt: https://www.youtube.com/watch?v=6A6k8EFoIzc.
Poza tym Uther w tym quescie mowi zupelnie zly tekst (wtf xD). NPC nie kleka, etc. Wszystko jest w filmiku.

**Comment by Ravenus** [comment]
Plus NPC zgarnia bardzo dużą ilość mobków po drodzę przez co może bardzo łatwo zginąć
