### ISSUE TITLE
[Reputacja] Ponad 22 k na minusie Reputacji w The Sons of Hodir mimo wykonania questów.

### ISSUE THREAD

**Issue by Mathaus9o** [RaphaelSunwell/Sunwell-BugTracker-SCv2#875]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Po wykonaniu ciągu questów powinienem być na poziomie neutral/friendly a zamiast tego mam na minusie 22K Reputacji.

**Obecne działanie**: Za wykonanie zadania  -Mending Fences- otrzymałem 22K Reputacji The Sons of Hodir na minusie.

**Oczekiwane działanie**: Po wykoanniu zadania -Mending Fences- powinieniem otrzymać 22K Reputacji The Sons of Hodir co skutkowałoby zmianą nastawienia na neutral/friendly

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Należy rozpocząć quest -The Last of Her Kind-
2. Kontynuować wykonywanie zadań 
3. Ósmym zadanie jest  -Mending Fences-

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12915/mending-fences
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

![wowscrnshot_032717_180607](https://cloud.githubusercontent.com/assets/25955088/24368713/6192cc16-1319-11e7-85d6-51f370a52e2c.jpg)

**Comment by KamaN442** [comment]
najpiew sie naucz szukac a potem co kolwiek zglaszaj

**Comment by Mathaus9o** [comment]
W ogóle Ciebie nie rozumiem     Mam problem więc go zgłosiłem o co Tobie chodzi  ?  Wszystkim dodaje a mi nie dodało repki  wiec to jest dla mnie problem godny zgłoszenia.

**Comment by Rosenkrantz** [comment]
Przeczytaj pierwszy komentarz z Twojego linka z wowheada:

(...) Step 4: Your first or second giant should drop Slag Covered Metal. Start the quest and kill Seething Revenant (non-elite) until you have 10x Furious Spark.
Step 5: By now, you should have killed 5 giants. Pick up another boulder and kill Fjorn. After he's dead, make sure to turn in The Refiner's Fire to the anvil. If you forget to do so, Fjorn will respawn and camp the anvil. Also, make sure to pick up the follow-up quest from the anvil.
Step 6: Fly back to Thorim, turn in both quests. Both quests will award you 22000 reputation with the Sons of Hodir (each), taking you from Hated to Neutral.

BOTH QUESTS. Są dwa questy na repę. Acz zdaje się, że bug polega na tym, że "Step 5" ma niepoprawne połączenie - quest http://www.wowhead.com/quest=12956/a-spark-of-hope powinien być dostępny *równolegle* z http://www.wowhead.com/quest=12915/mending-fences ; zdaje się, że jest dostępny dopiero PO wykonaniu Mending Fences. Nie mam postaci, którą mógłbym w tej chwili zrobić chain, więc prosżę kogoś o sprawdzenie wzajemnej dostępności tych questów.

**Comment by Mathaus9o** [comment]
Wykonując  Mending Fences zabijając mobki dostajesz item który pozwala zacząc quest The Refiner's Fire ----> którego zakończeniem jest  zadanie A Spark of Hope.   Wykonałem oba questy, ( Mending Fences i A Spark of Hope ) zaniosłem je do Thorim-a i niestety wyszło tak jak na umieszczonym screenie :/ .

**Comment by Bainit123** [comment]
Leć do kowadła i bierz następnego questa, wystarczy zapytać na worldzie zamiast lecieć z płaczem na bugtacker.

**Comment by Mathaus9o** [comment]
Przepraszam za zamieszanie    Pomogło z tym kowadłem  Bainit123   Dziekuję      
Inni nauczą sie na moim błędzie  :p     Byłem pewny że to był błąd.   Jeszcze raz dziękuję za pomoc :)

**Comment by Rosenkrantz** [comment]
Bugiem jest to, co napisałem. Powinno być równolegle dostępne, więc uwaga o lataniu z płaczem na BT jest nieco nietrafiona.

**Comment by Radeghost** [comment]
do zamkniecia

**Comment by Shon-su** [comment]
http://www.wowhead.com/quest=12922/the-refiners-fire jest napisane że trzeba wykonać ten quest żeby odblokować Spark of Hope.

Na serwerze jest teraz tak że trzeba mieć zrobione i to i Mending Fences
