### ISSUE TITLE
Quest chain Alliance - (Pilgrim)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#88]
**Opis**: Przygotowany chain, kolejności Questów dla Alliance.

**Obecne działanie**: Nie ma ich.

**Oczekiwane działanie**: Tak powinno się wykonywać chain.

**Co należy zrobić, aby odtworzyć ten błąd**:

**1.** Nie ma chainu.

**Linki WoWHead/OpenWoW**:
Questy w kolejności: (npc giver / ender w linku): **Sprawdzić dokładnie lokalizacje !**

Questem rozpoczynającym jest jak wspomniałem już Pilgrim's Bounty

**1.** Pilgrim's Bounty - http://www.wowhead.com/quest=14022/pilgrims-bounty
**2.** Spice Bread Stuffing - http://www.wowhead.com/quest=14023/spice-bread-stuffing
**3.** Pumpkin Pie - http://www.wowhead.com/quest=14024/pumpkin-pie
**4.** Cranberry Chutney - http://www.wowhead.com/quest=14028/cranberry-chutney
**5.** They're Ravenous In Darnassus - http://www.wowhead.com/quest=14030/theyre-ravenous-in-darnassus
**6.** Candied Sweet Potatoes - http://www.wowhead.com/quest=14033/candied-sweet-potatoes
**7.** Slow-roasted Turkey - http://www.wowhead.com/quest=14035/slow-roasted-turkey

Po wykonianu tego Q chaina dostaniemy item z last Q: 
Turkey Caller - http://www.wowhead.com/item=44844/turkey-caller

Źródło: http://wowwiki.wikia.com/wiki/Quest:Pilgrim%27s_Bounty

**Comment by Shon-su** [comment]
po update powinnien pojawić się npc i chain zacznie działać.
