### ISSUE TITLE
[INSTANCE] UP

### ISSUE THREAD

**Issue by charmelina** [RaphaelSunwell/Sunwell-BugTracker-SCv2#883]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Otóż podczas bicia bossa Gortok Palehoof boss dalej posiadał aggro na nieżywej postaci w momencie kiedy wszyscy umarli.

**Obecne działanie**: Boss ma aggro na martwej postaci.

**Oczekiwane działanie**: Chyba jasne :)

**Co należy zrobić, aby odtworzyć ten błąd**:

1. szczerze nie mam pojęcia.

Screeny : 
http://imgur.com/a/SCZ9D
http://imgur.com/a/u8NnJ
http://imgur.com/a/1GNJ9

**Comment by dreamwalkerx1** [comment]
Problemem ów bossa jest to, że w momencie odpalenia piedestału zaczynającego encounter on zaczyna zbierać cały threat generowany przez heala (bardzo dobrze widać to na omenie w momencie pulla), w momencie zaczęcia walki z nim powinien on mieć reset threatu ze **wszystkich** postaci w party.
