### ISSUE TITLE
Quest chain Horde - (Pilgrim)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#89]
**Opis:** Przygotowany chain, kolejności Questów dla Horde.

**Obecne działanie:** Nie ma ich.

**Oczekiwane działanie:** Tak powinno się wykonywać chain.

**Co należy zrobić, aby odtworzyć ten błąd:**

**1.** Nie ma chainu.

**Linki WoWHead/OpenWoW:**
Questy w kolejności: (npc giver / ender w linku): **Sprawdzić dokładnie lokalizacje !**

Questem rozpoczynającym jest jak wspomniałem już Pilgrim's Bounty

**1.** Pilgrim's Bounty - http://www.wowhead.com/quest=14036/pilgrims-bounty
**2.** Spice Bread Stuffing - http://www.wowhead.com/quest=14037/spice-bread-stuffing
**3.** Pumpkin Pie - http://www.wowhead.com/quest=14040/pumpkin-pie
**4.** Cranberry Chutney - http://www.wowhead.com/quest=14041/cranberry-chutney
**5.** Candied Sweet Potatoes - http://www.wowhead.com/quest=14043/candied-sweet-potatoes
**6.** Undersupplied in the Undercity - http://www.wowhead.com/quest=14044/undersupplied-in-the-undercity
**7.** Slow-roasted Turkey - http://www.wowhead.com/quest=14047/slow-roasted-turkey

Po wykonianu tego Q chaina dostaniemy item z last Q:
Turkey Caller - http://www.wowhead.com/item=44844/turkey-caller

Źródło: http://wowwiki.wikia.com/wiki/Quest:Pilgrim%27s_Bounty

**Comment by Shon-su** [comment]
chain działa tylko npc-ów nie ma, po update się pojawią i wtedy proszę o ewentualny komentarz jakby coś było nie tak
