### ISSUE TITLE
[Rogue][Ability] Fan of Knives

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#893]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Fan of Knives powinien zadawać dmg instantowo po użyciu umiejętności

**Obecne działanie**: Obecnie jest koło 0.2-0.3sec opóźnienia pomiędzy użyciem zdolności, a dmg

**Oczekiwane działanie**: Nie powinno być żadnego opóźnienia, zdolność powinna zadawać obrażenia w tym samym momencie, w którym jej używamy

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Akha72** [comment]
Dowody :?

**Comment by Kougraa** [comment]
Dowody:
https://youtu.be/0WnZUJUNb5Y
Linki WoWHead/OpenWoW:
[Spell] http://www.wowhead.com/spell=51723/fan-of-knives

**Comment by Rosenkrantz** [comment]
@Kougraa dowody na to, że ma być tak, jak piszą, a nie na to, że tutaj tak jest.

**Comment by Danieloses** [comment]
na tym filmiku widzisz to, że przez ten zbugowany delay moge rzucić fan of knives i użyć Stealtha zanim zada dmg xD

**Comment by Danieloses** [comment]
0:35 - https://www.youtube.com/watch?v=9dzArHY5kS8 - byle jaki film przedstawiający fan of knives, powienien działać jak każdy inny aoe tego samego typu, holy nova, arcane explosion, frost nova, tzn. instant effect
