### ISSUE TITLE
[Spell] Disengage.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#896]
**Opis**: W chwili, gdy Death Knight użyje gripa na hunterze, a ten natomiast użyje odskoku - Disengage dostaje cd na skill, a o odskoku ani widu ani słychu.  
[Filmy] https://youtu.be/x3OKBwSNj8g
https://youtu.be/HUY9Hdf63Tw

**Obecne działanie**: Disengage nie dziala podczas trwania gripa.

**Oczekiwane działanie**: Hunter powinien mieć możliwość odskoku podczas trwania gripa.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Byc hunterem.
2. Pozwolic, aby dk uzyl grip.
3. Wchwili trwania skilla dk - użyć disengage.

**Linki WoWHead/OpenWoW**:

1. [Grip] http://www.wowhead.com/spell=49576/death-grip
2. [Disengage] http://www.wowhead.com/spell=781/disengage

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Brak.

**Comment by valcy** [comment]
Z tego co wiem nie powinno byc mozliwosci disengagowania podczas gripa.
Mysle ze mozna to podpiac pod
 Patch 3.0.3 (04-Nov-2008): Now fails if you're rooted and is no longer on the global cooldown.

**Comment by Radeghost** [comment]
brak dowodow
