### ISSUE TITLE
[QUEST] The Cipher of Damnation v2

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#898]
#705 Nadal nie działa.

"**Obecne działanie:** Nie można ukończyć questa zabijając bossa

**Oczekiwane działanie**: Po użyciu quest itema powinien pojawić się boss którego mamy zabić

**Co należy zrobić, aby odtworzyć ten błąd:**

**1.** Bierzemy quest i lecimy pod Altar of the Damnation (środek shadowmoon)
**2.** Używamy qitema
**3.** Bossa nie da sięuderzyć.

**Linki WoWHead/OpenWoW**:

http://www.wowhead.com/quest=10588/the-cipher-of-damnation link do questa
**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:"

**Comment by Shon-su** [comment]
1. Zagadaj do NPC Oronok Torn-heart, stoi trochę przed guldanem w okolicy ławeczek. Tam jest po prostu mini-event i można bić

**Comment by Kougraa** [comment]
Nie ma mozliwosci rozmowy z npc.
