### ISSUE TITLE
[QUEST] Data Rescue

### ISSUE THREAD

**Issue by OrgiVed** [RaphaelSunwell/Sunwell-BugTracker-SCv2#9]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mając Red Punch Card w plecaku i używając Matrix Punchograph 3005-D nie mamy opcji wyboru ostatniej karty Prismatic Punch Card

**Obecne działanie**: Brak opcji wybrania ostatniej karty, jest tylko opcja dla inżynierów

**Oczekiwane działanie**: Powinny być 2 opcje na Matrix Punchraph 3005-D gdy ma sie Red Punch Card w plecaku

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wydropić białą kartę
2. Przejść się po wszystkich Matrix Punchcard 3005-A/C
3. Przyjść z Red Punch Card do Matrix Punchcard 3005-D

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/item=9316#created-by
2. http://wowwiki.wikia.com/wiki/Matrix_Punchograph_3005
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Instancja Gnomeregan

**Comment by Shon-su** [comment]
#154
