### ISSUE TITLE
[NPC] 34653 - Bountiful Table Hostess [Alliance] (Pilgrim)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#90]
**Opis**: Brak npc

**Obecne działanie**: Brak NPC i questa

**Oczekiwane działanie**: Powinien być NPC i dawać Q Sharing a Bountiful Feast

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Poszukać npc :D
2. Wziąć q
3. (brak npc i q)

**Linki WoWHead/OpenWoW**:

1. Sharing a Bountiful Feast - http://www.wowhead.com/quest=14065/sharing-a-bountiful-feast
2. Bountiful Table Hostess - http://www.wowhead.com/npc=34653/bountiful-table-hostess (2)

**Comment by Shon-su** [comment]
poprawione po udpate powinien się pojawić
