### ISSUE TITLE
Komenda ".friendsummon <name>

### ISSUE THREAD

**Issue by Xanador** [RaphaelSunwell/Sunwell-BugTracker-SCv2#902]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Wygląda,jakby komenda naliczała czas ze sporym opóźnieniem, coś w stylu 1 min CD = x czasu rzeczywistego

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
 Po przywołaniu przyjaciela przy pomocy komendy, ta prawidłowo dostaje CD ~60 minut. 
Niestety komenda ta ma dziwne odliczanie ingame( SS PONIŻEJ_

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Niechaj 1minuta w grze równa się 1minucie czasu odnowy.
**Co należy zrobić, aby odtworzyć ten błąd**:
1. Party zkolegą z RAFA
2. .friendsummon <name>
3. spróbować za pare minut, sprawdzić czas CD

SS:http://imgur.com/a/ONsop

**Comment by xsitdev** [comment]
Komenda wycofana, naprawiona funkcja z gry.
