### ISSUE TITLE
[Bazar] Wymiana Golda na PP

### ISSUE THREAD

**Issue by Nate015** [RaphaelSunwell/Sunwell-BugTracker-SCv2#903]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Niestety, nie działa wymiana golda na PP. Wszystkim graczom wcina golda a nie otrzymują oni PP. Nie wiem jak w drugą stronę (chyba ok).

**Obecne działanie**: Wystawiam X golda w zamian za Y PP. Ktoś wymienia. Ja nie dostaję PP, a kasa przepada. 

**Oczekiwane działanie**: Wystawiam X golda w zamian za Y PP. Ktoś wymienia. Ja dostaję PP, a kasa trafia do kupca. 

**Co należy zrobić, aby odtworzyć ten błąd**: Podjąć się wymiany golda na PP, w drugą stronę nietestowane.

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by tokacz** [comment]
zerknij tutaj https://forum.sunwell.pl/index.php?/topic/4304-bazar-kradnie-golda/#comment-46626 i pisz ticket
