### ISSUE TITLE
[QUEST] Seek out Neltharaku

### ISSUE THREAD

**Issue by Warderka** [RaphaelSunwell/Sunwell-BugTracker-SCv2#906]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie ma NPC, nie lata wokół Netherwing Fields(a powinien)

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić pierwszy quest chain na netherwingi.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=10811/seek-out-neltharaku
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
dobrze szukałeś? Bo lata

**Comment by Warderka** [comment]
juz wiem na czym polega błąd, jak sie do niego zagada to staje w miejscu i
nie lata :<


2017-04-04 19:37 GMT+02:00 Shon-su <notifications@github.com>:
