### ISSUE TITLE
[quest] Hard to Swallow

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#907]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nalezy zabic Hulking Jormungar wrzucając w otwartą paszczę dynamit (provided item). Po zabiciu dynamitem potwór eksploduje, a z jego fragmentów należy zebrać z dropem 100% Seared Jormungar Meat. 

**Obecne działanie**: W szczątkach rozrzuconych po zabiciu potwora brak jakiegokolwiek dropu.

**Oczekiwane działanie**: W mięsnych szczątkach zabitego dynamitem potwora powinny wydropić się ze 100% szansą itemy Seared Jormungar Meat

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. dodać do dropu quest item.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=12049/hard-to-swallow
2. http://www.wowhead.com/item=36731/seared-jormungar-meat
3. http://www.wowhead.com/object=188434/jormungar-meat

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Northend - Dragonblight 58,2/22,6

**Comment by Shon-su** [comment]
bezproblemowo to przed chwilą zrobiłem
