### ISSUE TITLE
[quest] The edge of winter

### ISSUE THREAD

**Issue by Isilion** [RaphaelSunwell/Sunwell-BugTracker-SCv2#908]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Należy zabić Lorda Everblaze, który dropić powinien ze 100% szansą na drop item Everburning Ember. Następnie należy się udać na wyspę w lokacji Howling Fjord by kontynuować dalej quest.

**Obecne działanie**: Lord Everblaze nic nie dropi (4 krotnie zabijany), więc nie da się pchnąć questu dalej.

**Oczekiwane działanie**: Lord Everblaze powinien dropić po śmierci item Everburning Ember

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać Lordowi Everblaze drop w postaci itemu Everburning Ember.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13675/the-edge-of-winter
2. http://www.wowhead.com/item=45005/everburning-ember#dropped-by
3. http://www.wowhead.com/npc=33289/lord-everblaze

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 
Northend Crystalsong Forrest 55,0/74,4

**Comment by Isilion** [comment]
Za 7 razem wydropił item, ale to oznacza, że szansa na drop jest nieprawidłowo ustawiona.

**Comment by Shon-su** [comment]
hmmm.. dziwne drop ustawiony na 100%

**Comment by tokacz** [comment]
mnie zawsze dropi

**Comment by Rosenkrantz** [comment]
Również nie miałem z tym problemu, co więcej - zabity w party dał quest item dla obu osób. Jesteś pewien że nie byłeś w rajdzie, albo nie był jakimś sposobem flagnięty na kogoś innego?
