### ISSUE TITLE
Crimson Crystal Shard

### ISSUE THREAD

**Issue by Morgahard** [RaphaelSunwell/Sunwell-BugTracker-SCv2#914]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: W archiwum jak napisane że quest z tym itemem z dropu został naprawiony i wgrany w okolicach 12 stycznia. http://www.wowhead.com/npc=19188/raging-colossus  powinno dropić (19%) tytułowy q item. Nie dropi. Ubiłem z 40 bo akurat skilowałem mining. 

**Obecne działanie**: BRAK DROPU

**Oczekiwane działanie**: DROP NA POZIOMIE 19%

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. FARMIĆ
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. BYŁ WYŻEJ
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: DOLNE HP - outland. 

Brakuje tego q na low level żeby machnąć lore quest z hp. 

Pozdrawiam Cruelsky

**Comment by Shon-su** [comment]
rzeczywiście nie chcą lecieć. Dorzuciłem coś co powinno pomóc, powinno się pojawić za jakiś czas na serwerze
