### ISSUE TITLE
[Paladin][Ability] Hand of Protection

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#919]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
"Patch 2.2.0:

Blessing of Protection: This spell can no longer be cast on others
when stunned. It can only be cast on self (to break the stun) under
those circumstances."

**Obecne działanie**: Obecnie paladyn może używać Hop'a podczas na innych graczach podczas stuna, incapacitate itd.

**Oczekiwane działanie**: Paladyn pod wpływem cc nie powinien móc używać tego skilla na innych graczach.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Danieloses** [comment]
Dodam jeszcze, że podczas tbc Hand of Protection nazywał się Blessing of Protection.

**Comment by Heartbraker** [comment]
> Oczekiwane działanie: Paladyn pod wpływem cc nie powinien móc używać tego skilla na innych graczach.

HoP(i HoF) powinien być możliwy do użycia na innych graczach przez paladyna będącego pod wpływem niektórych cc jak np. sap,blind, gouge, intimidating shout itp.  więc nie jest tak jak piszesz w "oczekiwane działanie"
Nie powinien być możliwy do użycia na innych podczas stuna - i o tym też mówi fragment z Patch Notes 2.2.0 który wkleiłeś.

**Comment by Danieloses** [comment]
Dowodów już na to nie będę szukał, ale powinno być tak. Hop powinien być możliwy do użycia na innych podczas physical cc, tj. Blind, Intimidating shout, Sap, Gouge itd. za wyjątkiem cyklona. Nie powinien być możliwy do wycastowania w żadnym innnym cc, tj. stuny physical, stuny magical, feary magic, polymorphy itd.

**Comment by sitovsky** [comment]
>Dowodów już na to nie będę szukał, ale powinno być tak

To tak nie dziala, dowody musza byc.

**Comment by Danieloses** [comment]
Wiadomo, zlećcie to jakiemuś testerowi, ja dzisiaj już przejrzałem z 50 różnych filmików szukając czegoś innego i mam dość na ten tydzień.

**Comment by Danieloses** [comment]
A no i jeżeli można to chociaż usuńcie możliwość używania tego spella podczas stunów, ponieważ na to już podałem dowód w reporcie. Jest to dosyć mocno broken biorąc pod uwagę, że hpal war to zdecydowanie najsilniejszy comp 2s (może nie na tym sezonie, ale już od rele), a w dodatku zyskują na sunwellu nowy feature.
