### ISSUE TITLE
Remove insignia World PvP

### ISSUE THREAD

**Issue by ellynd** [RaphaelSunwell/Sunwell-BugTracker-SCv2#92]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po zabiciu gracza pojawią się opcja remove insignia, która powinna być tylko i wyłącznie dostępna na bg. Ww. interakcja nie daje żadnej nagrody w postaci waluty.

**Obecne działanie**: W momencie zabicia gracza (często) pojawią się interakcja w postaci remove insignia.

**Oczekiwane działanie**: Opcja 'remove insignia' powinna być dostępna tylko i wyłącznie w trakcie trwania bg.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zabić gracza z przeciwnej frakcji.

**Screen**:
1. http://i.imgur.com/ajutMff.jpg

**Comment by Mithras2801** [comment]
In PvP Battlegrounds, you can right-click on an enemies corpse to "remove their insignia". This will give you and your party a negligible amount of copper or silver, and prevent that player from being able to resurrect at their body.

http://wowwiki.wikia.com/wiki/Insignia

**Comment by ThePuppetMaster** [comment]
Nie jestem w stanie odtworzyć.
