### ISSUE TITLE
[Quest] [Mutiny on the Mercy]

### ISSUE THREAD

**Issue by adamutp** [RaphaelSunwell/Sunwell-BugTracker-SCv2#920]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:

**Obecne działanie**: Jest tylko 1 mob, którego nie można zabić bo siedzi w teksturach

**Oczekiwane działanie**: Na najniższym piętrze statku powinno być dużo mobów.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Dodać npc w odpowiednim miejscu
2. 
3. 

**Linki WoWHead/OpenWoW**:

1.  https://www.youtube.com/watch?v=_ZfheZP46i4
2.  http://www.wowhead.com/quest=11527/mutiny-on-the-mercy
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 40, 75: Howling Fjord

**Comment by Shon-su** [comment]
przejechałem z nimi całą trasę tym statkiem i nie wygląda na to żeby spadały pod tekstury/ wypadały z statku. Może ktoś je przed Tobą zabił? Stoi ich tam 9. Mógłbyś się przejść jeszcze raz zobaczyć za jakiś czas?

**Comment by adamutp** [comment]
No dobra. Sprawdzę i wstawie screeny. Na 100% jeden mob siedział pod teksturami. Stałem tam z 10 minut i nic nowego się nie respiło.

**Comment by adamutp** [comment]
http://imgur.com/a/DeWZs  Rzeczywiście ktoś musiał zabić je przede mną. Pomimo tego jeden mob nadal siedzi pod teksturami, a znak na mapie odwołuje gracza do Hillsbrad Foothils. Z tego co pamietam to model tego statku właśnie znajduje się pod teksturami w hillsbradzie i stąd ten błąd.

**Comment by Shon-su** [comment]
pewnie coś z mapami i transportami
