### ISSUE TITLE
[Achievement] 3478 - Pilgrim (Pilgrim)

### ISSUE THREAD

**Issue by Mithras2801** [RaphaelSunwell/Sunwell-BugTracker-SCv2#93]
**Opis**: Nie można go dostać jeszcze.

**Obecne działanie**: Brak możliwości.

**Oczekiwane działanie**: Po wykonaniu pozostałych wymagań dostajemy achieva i peta na mail oraz Title.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Zrobić event

**Linki WoWHead/OpenWoW**:

1. Achievement - http://www.wowhead.com/achievement=3478/pilgrim
2. Pet na mail - http://www.wowhead.com/item=44810/turkey-cage
3. Title - http://www.wowhead.com/title=168/the-pilgrim

**Comment by RaphaelSunwell** [comment]
"Turkey-cage" Added in patch 3.2.2.10505
