### ISSUE TITLE
[OBSIDIAN SANCTUM] Twilight Torment od Vesperona

### ISSUE THREAD

**Issue by Kowson** [RaphaelSunwell/Sunwell-BugTracker-SCv2#930]
**Opis**:
Nie znika debuff Twilight Torment po śmierci Vesperona.
**Obecne działanie**: Walcząc z samym Vesperonem, po otworzeniu przez niego portalu na wszystkich zostaje rzucony debuff Twilight Torment, który nie znika po jego śmierci.

**Oczekiwane działanie**: Jeśli nie walczymy z Sartharionem, debuff powinien znikać wraz ze śmiercią Vesperona.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rozpocząć walkę z samym Vesperonem.
2. Poczekać aż otworzy portal i rzuci na wszystkich debuff.
3. Zabić Vesperona.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=57935/twilight-torment
2. http://www.wowhead.com/npc=30449/vesperon
3. https://github.com/RaphaelSunwell/Sunwell/blob/master/src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp

**Comment by dreamwalkerx1** [comment]
#697
