### ISSUE TITLE
[Item] Crimson Crystal shard 29476

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#935]
Item dropi z: 19188. Jest to item rozpoczynajacy quest
Powinien dropic, dopoki sie nie ma questa z niego (q id 10134). Nie wiem jak teraz dziala drop, bo po prostu go nie ma, mimo, ze zabilem okolo 20 mobow.

While the drop rate is listed as 20%, it will only drop once for the quest, as as people have to kill a total of 5 for another quest, it's likely that really the drop rate is 100%.

**Comment by Shon-su** [comment]
udało mi się wydropić w szóstym gigancie

**Comment by Radeghost** [comment]
drop powinien byc 100% poki nie masz questa
