### ISSUE TITLE
Shadowfang - brak dodatkowego shadow damage

### ISSUE THREAD

**Issue by Takisobielaps** [RaphaelSunwell/Sunwell-BugTracker-SCv2#939]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Sword jakim jest Shadowfang ma procz proca na shadowbolta, dodatkowy shadow 4-8 dmg(additional shadow damage), przy kazdym uderzeniu. Shadowfang nie zadaje dodatkowego 4-8shadoow dmg przy mele swingu, ani przy niczym.

**Obecne działanie**: Shadowfang nie zadaje w ogole dodatkowego 4-8 shadow dmg przy atakach.

**Oczekiwane działanie**: 4-8 shadow dmg przy kazdym ataku. Shadowfang is a one-hand sword with a Shadow damage proc and ## **additional Shadow damage**

**Co należy zrobić, aby odtworzyć ten błąd**:

1. zalozyc shadowfanga
2. wziac duela i dac /attack
3. zobaczyc czy to w combat logu czy na damage txt ze nie zadaje dodatkowego shadow dmg

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Shadowfang
2. http://www.wowhead.com/item=1482/shadowfang#comments (komentarze o tym ze 4-8 extra shadow dmg powinno przechodzic przez Blessing of Protection, robiac jednoczesnie pushback)
3. http://wow.gamepedia.com/Shadowfang

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: nie dziala .GPS

**Comment by Akha72** [comment]
Jeżeli to takie oczywiste to wrzuć jakiś filmik, na którym widać ten osobny dmg fanga.
