### ISSUE TITLE
[QUEST] Venomhide Eggs - 13887

### ISSUE THREAD

**Issue by sz4t4n** [RaphaelSunwell/Sunwell-BugTracker-SCv2#94]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest polega na zebraniu 4 itemów - 46364 (venomhide ravasaur egg), które są porozrzucane po lokacji Un'Goro Crater.

**Obecne działanie**: Nie można wejść w interakcję z itemem - 195022 (venomhide egg). Itemy są widoczne lecz się nie podświetlają.

**Oczekiwane działanie**: Po wejściu w interakcję z itemem - 195022 powinniśmy otrzymać loot w postaci item - 46364.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Pobrać quest od NPC - 11701 (Mor'vek)
2. Udać się na poszukiwanie jaj
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/quest=13887/venomhide-eggs
2. http://www.wowhead.com/object=195022/venomhide-egg
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by kovaq** [comment]
Tego q nie powinno wcale byc, nie ten content.

**Comment by xsitdev** [comment]
Dlatego tez nie dzialal, gdyz obiekt byl wylaczony, a quest niestety omylkowo nie zostal 👍

**Comment by Kougraa** [comment]
Tu drugi quest, którego nie powinno być. Nie jestem pewna, ale chyba go nawet wykonałam.
https://youtu.be/m6UektbHdig
