### ISSUE TITLE
[SPELL] Charge Warriora

### ISSUE THREAD

**Issue by Ravenus** [RaphaelSunwell/Sunwell-BugTracker-SCv2#941]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Skill Warriora Charge trafiając w moba ustawia gracza  "w mobie" przez co gracz musi zrobić po szarży krok w tył by mob nie był za plecami

**Obecne działanie**: Po Charge gracz dostaje informację, że mob jest za plecami

**Oczekiwane działanie**: Charge powinna się zatrzymywać krok przed mobem

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wybrać Warriora
2. Namierzyć Moba
3. Użyć na nim Charge

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/spell=100/charge
2. https://www.youtube.com/watch?v=t8niuOe5CVo
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Akha72** [comment]
Mam bliźniaczy issue z Interceptem.

**Comment by Ravenus** [comment]
Bardzo możliwe, testowałem tylko Charge ale widocznie każdy Spell szarżujący u Warriora powoduje ten problem
