### ISSUE TITLE
[QUEST][ITEM]

### ISSUE THREAD

**Issue by zeshindal** [RaphaelSunwell/Sunwell-BugTracker-SCv2#942]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Q item do q "I'm Stuck in this Damned Cage... But Not For Long!" nie wypada lub ma zbyt małą szanse na wypadnięcie

**Obecne działanie**: Wybiłem 2x całą lokalizacje w celu zdobycia przedmiotu i nic

**Oczekiwane działanie**: Item wg baz danych dostępnych w internecie powinien mięć 9-10% szans na wypadnięcie, ludzie opisujący go tam najpóźniej po parunastu zabitych ghoulach powinni go wydropić

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Wziąć q i zacząć je zabijać :)
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/item=34957/engine-core-crystal
2. http://wotlk.evowow.com/?item=34957
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
68 16

**Comment by Bainit123** [comment]
Nie spełniasz wymagań żeby ci poleciał quest item, możesz zabić 10000000 mobów, a i tak nie poleci. Do zamknięcia.

**Comment by Radeghost** [comment]
Dlaczego nie spełnia? Jeśli ma quest to automatycznie spelnia wymagania do podniesienia quest itemow...

**Comment by Shon-su** [comment]
9% szansy na drop. Sprawdziłem i udało mi się wydropić po około 15 ghoulach
