### ISSUE TITLE
[Talenty] Brak możliwości wykupienia "Dual Talent Specialization".

### ISSUE THREAD

**Issue by wasiu1367** [RaphaelSunwell/Sunwell-BugTracker-SCv2#947]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Brak możliwości wykupienia "Dual Talent Specialization" u NPC.

**Obecne działanie**: Mimo posiadania odpowiednio wysokiego poziomu doświadczenia oraz kwoty niezbędnej do zakupienia tzw. Dual Spec na mojej postaci (o nicku Wasx) po odbyciu rozmowy z NPC i zaakceptowaniu transakcji nic się nie dzieje. Gold nie zostaje pobrany ani w interfejsie talentów nie ma możliwości uruchomiania drugiego specu. 

**Oczekiwane działanie**: Po odbyciu rozmowy z NPC z wirtualnego konta postaci powinno zniknąć 1000 gold a w zakładce "Talents (N)" powinna być możliwość ułożenia dwóch niezależnych od siebie drzewek talentów oraz możliwość swobodnej zmiany między talentami.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/achievement=2716/dual-talent-specialization
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Shon-su** [comment]
próbowałeś usunąć Cache / podejść do npc drugi raz?

**Comment by wasiu1367** [comment]
Dziękuję bardzo usunięcie pamięci podręcznej pomogło :)
