### ISSUE TITLE
[QUEST] The Bloodsail Buccaneers

### ISSUE THREAD

**Issue by bartekmad** [RaphaelSunwell/Sunwell-BugTracker-SCv2#95]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie da się podnieść przedmiotu "Bloodsail Charts". Relog nie pomógł.

**Obecne działanie**: Nie da się podnieść przedmiotu "Bloodsail Charts"

**Oczekiwane działanie**: Powinno dać się podnieść przedmiot "Bloodsail Charts"

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest The Bloodsail Buccaneers
2. Udać się miejsce w którym powinien respić się przedmiot "Bloodsail Charts"
3. Spróbować go podnieść

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/object=2086
2. http://wotlk.openwow.com/quest=604
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/lXD7zJ0.jpg

**Comment by sz4t4n** [comment]
Jeszcze wczoraj dało się podnieść, sprawa została już zgłoszona wcześniej

**Comment by Shon-su** [comment]
zmieniałem tylko resp time ;p. no nic

**Comment by Shon-su** [comment]
macie jakiś error jak próbujecie podnieść? czy po prostu nie da się kliknąć

**Comment by bartekmad** [comment]
nie da się kliknąć

**Comment by bartekmad** [comment]
kilka  godzin później udało mi się oddać

**Comment by RaphaelSunwell** [comment]
Można podnieść q item z "Bloodsail Charts". Sprawdzane i testowane.
