### ISSUE TITLE
[RAID] Molten Core

### ISSUE THREAD

**Issue by Hooraga** [RaphaelSunwell/Sunwell-BugTracker-SCv2#951]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Nie chcę robić pojedynczych zgłoszeń do każdego zaobserwowanego buga (wszystkie sprawdzone na PTR)

**Obecne działanie**: 
1. Flamewaker Protector (Lucifron Trash) - Nie używa Dominate Mind.
2. Gehennas - Nie używa Shadow Bolt
3. Firesworn (Garr Trash) - Brak visualu śmierci (powinny wybuchać jak normalne elementale), brak enrage po odciągnięciu ich daleko od bossa [http://wowwiki.wikia.com/wiki/Patch_1.5.0](Patch 1.5.0). Brak używania spella Immolate.
4. Flamewaker Priest - Nie używają umiejętności Dark Strike (Sulfuron Harbinger trash)
5. Majordomo Executus - Brak visualu po jego pokonaniu (znika zamiast wycastować czerwony piorun [https://www.youtube.com/watch?v=t4-ABTsU_Ys](tak jak na filmie). Po jego odpaleniu przy Ragnarosie, brak eventu (powinien castować odpalając Ragnarosa).
6. Ragnaros - Nie bije magma blast kiedy jesteśmy poza melee range, Hand of Ragnaros, Eruption, Lava Burst i Hammer of Ragnaros (na graczy z mana barem), nic nie powodują. W combat logu Ragnaros ich używa, jednak nie oddziałują na gracza w żaden sposób.

**Oczekiwane działanie**: 
1. Flamewaker Protector rzuca Dominate Mind - Mind Controllując gracza
2. Gehennas używa Shadow Bolt
3. Firesworn w trakcie smierci wybucha, odrzucając graczy (Eruption), po odciągnięciu ich od Garra na dużą odległość, dostaje enrage (buff schodzi gdy się przyprowadzi go z powrotem do Garra). Używa spella Immolate.
4. Flamewaker Priest uzywa Dark Strike.
5. Poprawne Visuale.
6. Ragnaros obecnie jest kukłą (tylko odrzuca i bije melee (no i submerge)). Wszystkie skille są do naprawy

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przejść się po Molten Core :)

**Linki WoWHead/OpenWoW**:

1. http://db.vanillagaming.org/?npc=12119  |  http://db.vanillagaming.org/?spell=20740#used-by-npc
2. http://wowwiki.wikia.com/wiki/Gehennas
3. http://www.wowhead.com/npc=12099/firesworn
4. http://db.vanillagaming.org/?npc=11662
5. http://db.vanillagaming.org/?npc=12018
6. http://wowwiki.wikia.com/wiki/Ragnaros_(tactics)

**Comment by Radeghost** [comment]
Jesli sie da ukonczyc, to jest spoko. Nie trzeba poki co nic fixowac - jak czas pozwoli to sie przeniesie z Elysium Core i wtedy bedzie mozna zglaszac.
