### ISSUE TITLE
[Quest] Herald of War [13257]

### ISSUE THREAD

**Issue by Szarbi** [RaphaelSunwell/Sunwell-BugTracker-SCv2#953]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Końcówka długiego łańcuchu Questów. 
1. Zaczyna się u 'High Overlord Saurfang' [25256] (działa)
2. Powinniśmy być w osobnej... fazie? Nie jestem pewny czy tak to się zwało ale będę używał tego zwrotu w dalszej części. Chodzi o coś w stylu Questów u DK. (nie wiem czy działa)
3. Powinien pojawić się portal do Durotaru (nie działa)
4. Po wejściu w portal pojawiamy sie przed Orgri w osobnej fazie (działa)
5. Przechodzimy do Thralla, gdzie oglądamy scenke (działa)
6. Oddajemy Q Thrallowi i...

**Obecne działanie**:

6. ... wyrzuca nas z fazy łańcucha Questów do normalnej. Nie możemy wziąć kolejnego Q.

**Oczekiwane działanie**:

6. ... zostajemy w fazie z Questami. Bierzemy kolejnego: 'A Life Without Regret' [13266]
7. Pojawia się portal do Trisfal Glades i zaczynamy cały event z bitwą o UC. 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Weź Q 'Herald of War' [13257]
2. Oddaj go Thrall'owi w Orgrimarze

**Linki WoWHead/OpenWoW**:

1. Q ' Herald of War': http://www.wowhead.com/quest=13257
2. Video poglądowe końcówki chaina: https://www.youtube.com/watch?v=cqvnd_1aleY
Patrz 01:08 do 2:28

**Comment by Radeghost** [comment]
Battle nie jest oskryptowane.

**Comment by Shon-su** [comment]
przeniesione do zbiorczego
