### ISSUE TITLE
[arena] healing

### ISSUE THREAD

**Issue by Zozusa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#960]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Heal na arenach**:

**healing jest mniejszy na arenach niz normalnie. **: 

**heal na arenach powinien być taki sam jak przykładowo w dalanar (ostatnie info administracji dotyczace nowego 6 sezonu, dodatek zmiejszajacy heal miał być zniesiony.**: 

**jak już wgracie ten fix to polecam sprawdzić czy działa na głównym serverze wchodząc na arene**:

**Comment by Radeghost** [comment]
Jest przeciez zdjete, ale - @Shon-su

**Comment by Zozusa** [comment]
Skąd wiesz, ze jest zdjęte? bo administacja tak napisała? Wiem, ze tak było napisane, ale nie jest zdjęte, dlatego o tym informuje.
