### ISSUE TITLE
[reputation] horde/alliance

### ISSUE THREAD

**Issue by braeinia** [RaphaelSunwell/Sunwell-BugTracker-SCv2#962]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: 
Otrzymując reputacje za questy/tokeny do 1 miasta Hordy/Alliance (np. Orgrimmar) powinno dostawać się tzw. splashem % repy do innych miast (Darkspear, Undercity itd.) 

**Obecne działanie**: Dostając reputacje do 1 miasta nie dostaje sie splashem do reszty. 

**Oczekiwane działanie**: 25% repy ktora sie dostaje do 1 miasta powinno się dostawać do reszty miast. Być może jest to spowodowane eventem bądź wyłączyliście to celowo.

Linków chyba nie musze wklejać gdyż wiadomo o co chodzi.

**Comment by Radeghost** [comment]
Dostaje sie spillover. Zglaszalem bug, bo spillover capuje sie na 5999/6000 Friendly, a na Sunwellu nie mial w ogole capa, przez co ludzie mieli prawie ambassadory nie oddajac Runeclothow.

**Comment by Radeghost** [comment]
https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/945

**Comment by braeinia** [comment]
Niestety nadal nie dziala jak nalezy robilem questy do Darkspear w argent tournament repa do innych miast stoi w miejscu to samo z Runeclothami, questami w mulgore i tokenami za champion's writ.

**Comment by Radeghost** [comment]
https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/945
