### ISSUE TITLE
[Talent] Close Quaters Combat

### ISSUE THREAD

**Issue by chinek** [RaphaelSunwell/Sunwell-BugTracker-SCv2#963]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Jeden z trzech talentów dający bonus przy użyciu danego rodzaju broni u rogue. CQC wykorzystuje 2x fist weapon / 2x dagger / fist weapon+dagger. Przy wydaniu w niego 5 punktów zwiększa crit chance o 5%.

**Obecne działanie**: Talent nie dodaje 5% crit chance przy kombinacji broni fist+dagger. Fist+fist jednak działa, dagger+dagger rowniez

**Oczekiwane działanie**: Kombinacja broni fist+dagger przy uzyciu tego talentu powinna dawać dodatkowy % crit chance

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Ubrać kombinacje fist+fist / dagger+dagger i sprawdzić crit chance
2.  Ubrać kombinacje fist+dagger i sprawdzić crit chance

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Close_Quarters_Combat

**Comment by MonichSC** [comment]
Jakiś screen potwierdzający buga?

**Comment by chinek** [comment]
http://imgur.com/a/KkK5x

Przy fist+dagger powinienem mieć o 2% więcej, a jak widać troszke ten crit spada :)

**Comment by MonichSC** [comment]
[http://imgur.com/a/10kwt](http://imgur.com/a/10kwt)
Zrobiłem testy z najsłabszymi daggerami i fistami jakie znalazłem i minimalnymi talentami, żeby nie dostać żadnego dodatkowego crit chance. Jak widać crit chance jest taki sam dla każdej kombinacji i o 5% większy niż kiedy jestem unarmed.

Nie wiem czy czegoś nie widzę/coś robię źle czy na twój crit chance działa jednak jakiś inny czynnik.

**Comment by chinek** [comment]
Źle napisałem poprzedni komentarz, 2% więcej odnosiło się do buildu w assasination w którym mam 3/5 talentów, tutaj crit chance powinno wynosić mniej więcej tyle ile jest na screenie z daggerami. Czyli uważasz ze tracę 7% crit chance ze względu na zmianę jednego itemu? :) Jak widzisz cała reszta gearu jest taka sama, bo nie zmieniałem go pod combat, tylko zostawiłem ten, który używam pod assasination, więc nie jest to moja wina, tylko coś od serwera. Jeden item nie zmieni crit chance o 7%.

**Comment by MonichSC** [comment]
Mógłbyś podać nazwę lub ID tego fista którego używasz?
Upewnij się również że masz max skill w unarmed.
