### ISSUE TITLE
Gundrak Raptor 

### ISSUE THREAD

**Issue by Ciawa** [RaphaelSunwell/Sunwell-BugTracker-SCv2#964]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:
Dodatkowy item przy skinningowaniu npc.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Po użyciu skinningu na npc Gundrak Raptor wylatuje item Nerubian Chitin, który nie powinien wypadać z tego npc, tylko z Nerubianow.
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Z npc Gundrak Raptor powinny wypadać tylko 2 itemy, Borean leather i Arctic Fur. Według mnie Nerubian Chitin został dodany przez przypadek.

**Co należy zrobić, aby odtworzyć ten błąd**:

1.  Zabij npc o nazwe Gundrak Raptor
2. Zbierz z niego wszystkie itemy
3.  Użyj na nim skinningu.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=29334/gundrak-raptor#skinning
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
72.6, 27.8, Zol' Heb w Zul Drak koło Gundraka.

**Comment by Ciawa** [comment]
Bug nadal nie został naprawiony, czy będą robione jakies kroki ku naprawie tego błędu?

**Comment by Shon-su** [comment]
bo jeszcze nie jest dograne na serwer :)
