### ISSUE TITLE
[ITEM] X-53 Touring Rocket

### ISSUE THREAD

**Issue by feralxgodx** [RaphaelSunwell/Sunwell-BugTracker-SCv2#966]
Opis: Problem dotyczy rakiety ze sklepu za pp http://www.wowhead.com/item=54860/x-53-touring-rocket

Obecne działanie: rakiety nie można użyć jako ground mounta.

Oczekiwane działanie: Rakieta w lokacjach w których nie można używać fly mounta powinna działać jako ground mount.

Co należy zrobić, aby odtworzyć ten błąd:

    Użyć itemu w dowolnej lokacji w której nie można latać np. Dalaran.

**Comment by Radeghost** [comment]
Zaznaczam critical bo ten bug psuje mounta z pp

**Comment by Crackaw** [comment]
Jak wrócę do domu leci bugfix

**Comment by Crackaw** [comment]
http://wowwiki.wikia.com/wiki/X-53_Touring_Rocket
Jest dopisane, że:

> As of Patch 4.0.1 the rocket can now be ridden as a ground mount in no fly zones at 100% ground speed.
Więc zgłoszenie nie prawidłowe i było poruszane wiele razy ;) - https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/540

Więc rakieta działa poprawnie 👍

**Comment by Radeghost** [comment]
Doh, prawda. W takim razie mój błąd, nie zauważyłem, że edit z wowhead był z 4.0.3
