### ISSUE TITLE
[BG] Eye of the Storm teleport

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#974]
Po zbyt duzym oddaleniu sie od respawna przed rozpoczeciem bg, postac powinna teleporta dostac do banki z powrotem. Mozna wyjsc z banki (blizzlike) sposobem, ale jak sie za bardzo oddalisz, to powinno sie wrocic.
U nas tego teleportu nei ma
https://youtu.be/43cdkZWgvDI

**Comment by Danieloses** [comment]
jest teleport tylko następuje parę metrów dalej, a nie od razu po zeskoczeniu
