### ISSUE TITLE
[SPELL]Pestilence

### ISSUE THREAD

**Issue by leahcim333** [RaphaelSunwell/Sunwell-BugTracker-SCv2#975]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Podstawowa umiejętność Death Knight'a Pestilence nie daje żadnego efektu.

**Obecne działanie**: Pestilence nic nie robi.

**Oczekiwane działanie**: Po użyciu przez gracza Pestilence, wszystkie cele w odległości do 10 jardów powinny otrzymać debuffy Frost Fever i Blood Plague.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Użyć umiejętności Pestilence w pobliżu wroga.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Pestilence
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Radeghost** [comment]
...spreads your **existing** diseases from your target to all other enemies hit.
