### ISSUE TITLE
[Spell] Hemorrhage

### ISSUE THREAD

**Issue by Artanis02** [RaphaelSunwell/Sunwell-BugTracker-SCv2#976]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Umiejętność Hemorrhage (klasa rogal, drzewko subtlety) nie działa odpowiednio z dotami fizycznymi takimi jak bleedy. Zgłaszałem ten błąd na starym sunwellu (jakies 2 lata temu) i został poprawiony.

**Obecne działanie**: Podczas gdy target posiada na sobie debuff z umiejętności Hemorrhage, powinien otrzymywać dodatkowe obrażenia ze wszystkich fizycznych źródeł. DoTy fizyczne są takimi obrażeniami, więc powinny "triggerować" stacki Hemorrhage. Nie otrzymują one niestety żadnego bonusa i stacki Hemorhage nie są usuwane.

**Oczekiwane działanie**: Po użyciu hemorrhage każde fizyczne obrażenie powinno "zjadać" jeden stack hemorrhage i zadawać powiększone obrażenia - również przy działaniu DoT. Czyli np. Hemorrhage -> Rupture -> obrażenia z "ticków" Rupture powinny być zwiększone o bonus z Hemorrhage

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Klasą rogal należy użyć umiejętności Hemorrhage na mobie.
2. Następnie użyć umiejętności Rupture i poczekać chwilę
3. Każdy "tick" obrażeń Rupture powinien pobierać 1 stack umiejętności Hemorrhage i być powiększony o bonus z Hemorrhage, a tak się nie dzieje.

**Linki WoWHead/OpenWoW**:

(Servery DB padły - podrzucę co mogę)

1. http://wowwiki.wikia.com/wiki/Hemorrhage
2. http://scr.hu/85m5/u39g6
3. http://www.wowhead.com/spell=16511/hemorrhage#comments **(dowód na sposób działania opisanego powyżej) - **proszę o sprawdzenie piątego komentarza oraz odpowiedzi na niego**

**Comment by Rosenkrantz** [comment]
Komentarz nr 5 jest z Cata, gdzie hemo zmieniło działanie i zwiększało damage z bleedów o 30% jeżeli dobrze pamiętam. W Patch notes z wowwiki od razu masz:

Patch 1.11.0 (20-Jun-2006): Your damage over time effects will no longer consume charges of Hemorrhage.

Innymi słowy - working as intended, a jeżeli zostało poprawione na starym sunie, to brawo, udało Ci się wprowadzić deva w błąd.

**Comment by Artanis02** [comment]
Sorry, nie zwróciłem uwagi. Dzięki za wyjaśnienie.
Pozdrawiam
