### ISSUE TITLE
[Tytuł] HK

### ISSUE THREAD

**Issue by dziarski1** [RaphaelSunwell/Sunwell-BugTracker-SCv2#978]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Mam ponad 1200 HK i dalej posiadam tytuł Private

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM
Mam ponad 1200 HK i dalej posiadam tytuł Privat
**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Powinna być ranga Corporal
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odbugować mi postać, nick Beastalski.
2. ?
3. ?

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Kowson** [comment]
Odsyłam do posta na forum:
https://forum.sunwell.pl/index.php?/topic/1417-czytaj-je%C5%BCeli-chcesz-by%C4%87-na-bie%C5%BC%C4%85co/&page=3#comment-46510
