### ISSUE TITLE
[QUEST] Escape Through Stealth [995] & Escape Through Force [994]

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#98]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Quest na eskorte. Nie dziala - mob wychodzi z jaskini, spamuje "HERE THEY COME!". Zadne moby nie wyskakuja, a npc znika jak podchodzi do drogi.

**Obecne działanie**: jak wyzej. W quescie escape through stealth mob tez zle sie zachowuje.

**Oczekiwane działanie**:  ESCAPE THROUGH FORCE https://www.youtube.com/watch?v=TwSbAkMGDGY ESCAPE THROUGH STEALTH: https://www.youtube.com/watch?v=y5AMXINUv3Q
**Co należy zrobić, aby odtworzyć ten błąd**: wziac quest Lost Master id 993, a potem oddac u npc Volcor id 369. Potem wziac q Escape Through Stealth albo Through Force.

1.  Escape Through Force 994 https://www.youtube.com/watch?v=TwSbAkMGDGY 
2. Escape through Stealth 995 https://www.youtube.com/watch?v=y5AMXINUv3Q
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Towoku** [comment]
Moje pytanie brzmi czy ten filmik z Escape Through Force jest wotlkowy czy nowszy? nie przypominam sobie zeby ten ziomek miał taka fajna bron. i czy q idzie oddac u tego ziomka jak on podejdzie do drogi czy nie? ;p

**Comment by Seavitia** [comment]
Robilam wersje escpae trought force - poszlo bez najmniejszego problemu.
Zadalabym tu podstawowe pytanie - o to czy robiac q zachowywales sie zgodnie z zalozeniem questa - trought force - bijac moby po drodze.

**Comment by c0me10** [comment]
I have same problem... It is a bug, definitely.

I googled for this bug and i saw Azeroth and Trinity cores had same bug.

**Comment by Mithras2801** [comment]
NPC nie daje Q

**Comment by kovaq** [comment]
Po zrobieniu chaina z panterkami (brane z Auberdine) oraz questa na znalezienie Volcora rzeczywiscie stajemy przed wyborem zrobienia q na sile i na ukrycie. Jednakze sa to tylko nazwy, w obu questach postac pokonuje ta sama odleglosc, odpowiednia dla questu trough force. Dodatkowo wystepuje to zachowanie ze spamowaniem tekstu Here they come.
https://youtu.be/HXAy2oTzHSs

**Comment by Vaelevian** [comment]
Poprawione. Zostanie wgrane dzisiaj (tj. 27.01) około 6 rano.
