### ISSUE TITLE
[Rogue][Ability] Detect Traps

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#984]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Obecnie trapy widać po zbliżeniu się do nich na około 15yardów, sam disarm trap ma zasięg 20 yardów co sugeruje, że jest coś nie tak. Zasięg powinien być z tego co pamiętam o wiele wiele większy. Po przejrzeniu koło 50 filmów pvp wotlk rogue pov udało mi się znaleźć niestety jedynie coś takiego. https://www.youtube.com/watch?v=U1cqp2ih4Ng - mniej więcej w 15 sekundzie widać jak rogue jest oddalony od trapów o około 28-30yardów i cały czas je widzi. W dodatku trapy często są renderowany z gigantycznym opóźnieniem, czasem znikają z widzenia na parę sekund bez powodu lub, gdy hunter je postawi musimy się poruszyć by się zrenderowały.

**Obecne działanie**: ^

**Oczekiwane działanie**: Trapy powinny być widoczne z co najmniej tych 30 yardów, które widać na filmie. W dodatku, gdy hunter je postawi nie powinno być potrzeby poruszenia się w 100% przypadków, by się wczytały. Dodam, że na starym sunwellu z tego co pamiętam dobrze to działało więc może warto zajrzeć do sunwell core, nie wiem nie znam się na tym. Dodam jeszcze, że są posty, w których rogale mówią, że zawsze widzieli trapy nawet z drugiego końca BG, ale nie wiadomo czy z wotlka, w dodatku znalazłem tylko  2 posty więc nie wrzucam.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by pewik** [comment]
Rzeczywiście jest to spory problem, z doświadczenia wiem że trapy powinny być widoczne dla rogue'a z dużego dystansu inaczej skill disarm trap jest bezsensowny i bezużyteczny.

**Comment by cebulaxgodx** [comment]
Rzeczywiście jest to spory problem dla rogue'a, z dużego doświadczenia z retaila oraz wielu serverów wiem, że detekcja trapów powinna działać z dużego range, w przypadku sunwella trapy widać z bardzo bliska lub ich nie widać wcale, w przeciwnym razie skill o nazwie disarm trap staje się bezużyteczny co skutkuje dużym minusem podczas walki przeciwko hunterom.
