### ISSUE TITLE
[QUEST] Convocation at Zol'Heb [12730]

### ISSUE THREAD

**Issue by Radeghost** [RaphaelSunwell/Sunwell-BugTracker-SCv2#99]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Po wejsciu do okregu nie mozna uzyc quest itemu

**Obecne działanie**:  jak wyzej. Przebywajac w okregu i uzywajac quest itemu Prophet of Akali Convocation id 39556 dostajemy errora, ze "You can't do that yet". Jesli nie stoimy w kregu to wyskakuje error "Requires COnvocation Summoning Circle"

**Oczekiwane działanie**: po wejsciu do okregu powinno sie dac uzyc quest item, po czym nastapi summon bossa do questa

**Co należy zrobić, aby odtworzyć ten błąd**: Wziac quest  id 12730

1.  ID Gobjecta Convocation Summoning circle: 66735 (entry 191123), Convocation Summoning Circle Spell FOcus: 99737 (entry 191124)
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by Immunez** [comment]
Bump.

**Comment by ThePuppetMaster** [comment]
Potwierdzam.

**Comment by KamaN442** [comment]
bump

**Comment by Kokaina** [comment]
bump, wisi półtora miesiąca a quest ciągle się przewija w ticketach
