### ISSUE TITLE
[Core] Guardiany, a combat pvp  - ultra broken

### ISSUE THREAD

**Issue by Danieloses** [RaphaelSunwell/Sunwell-BugTracker-SCv2#991]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:  Wszelkie pety i guardiany po wysłaniu do ataku na przeciwnika powinny otrzymać combat pvp jednak osoba, na która zostały wysłane powinna otrzymać combat dopiero po zostaniu ofiarą jakiejś umiejętności/ataku ze strony petów/guardianów. Działą to identycznie jak w przypadku castowania spelli, np. Castujemy frostbolta, ukończyliśmy cast - otrzymujemy combat, lecz osoba, na którą go wycastowaliśmy otrzyma combat dopiero po otrzymaniu dmg.

**Obecne działanie**: Obecnie jeżeli jakiś guardian (gargoryle, water elemental, spirit wolves itd.) został wysłany na ciebie będziesz w combacie tak długo jak będzie za tobą podążał. Przykład: jestem 40yardów od death knighta, wysyła on na mnie gargoryle, los'uje gargoryle nie otrzymuje żadnego ataku od niego przez 20 sekund jednak cały ten czas mam combat.

**Oczekiwane działanie**: Guardiany powinny nabijać combat osobie, za którą podążają dopiero w momencie, gdy wycastują jakąś umiejętność, nie zaczną cast czy po prostu będą za nią biegać. Muszą ukończyć cast lub po prostu wykonać autoattack. Jeżeli po wykonaniu autoattacku uda nam się nie zostać ofiarą innego lub tego samego ataku ze strony guardiana powinniśmy utracić combat zwyczajnie po 5.5sek.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by szopn** [comment]
Dodam tez od siebie maly dowod na to, ze jest wiecej sytuacji, gdzie combat nie schodzi po 5 sekundach.

https://youtu.be/qaqIv3-NTS8

Nasza wersja z wowa jest z June 2010, wiec sprawdzilem July i mamy.
```
July 17, 2010‎
In PvP, a player will leave combat if they have not attacked or been attacked for 5 seconds, or all the enemy characters that have attacked you are killed.

Under most circumstances in PvE, once all monsters have lost interest in you, you will be removed from combat.

Actions that will get you into combat
Attacking
Casting an offensive Spell
Casting a Buff or Healing spell on a unit that is in combat
Getting on a mob's Aggro list
Certain bosses always put everyone in the group (or raid) in combat when engaged, regardless their distance from the boss

```

**Comment by Danieloses** [comment]
Polecam naprawić tak ze 2 miesiące przed końcem sezonu, albo kolejne tytuły możemy rozbić o kant dupy
